-- Merge controlado de bairros e enderecos duplicados apos normalizacao.
-- Cliente/base: MELLACO DE CANA / MELLACODECANAPRD.SANKHYACLOUD.COM.BR
-- ID_EXECUCAO fixo para auditoria e reversao: MELLACO_20260904_083530

SET SERVEROUTPUT ON SIZE UNLIMITED
SET SQLBLANKLINES ON
SET DEFINE OFF
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

PROMPT === 01. CRIACAO DAS ESTRUTURAS PERSISTENTES DE BACKUP ===
DECLARE
  PROCEDURE cria(p_nome VARCHAR2, p_sql VARCHAR2) IS
    v_qtd NUMBER;
  BEGIN
    SELECT COUNT(*) INTO v_qtd
      FROM ALL_TABLES
     WHERE OWNER = SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA')
       AND TABLE_NAME = UPPER(p_nome);
    IF v_qtd = 0 THEN EXECUTE IMMEDIATE p_sql; END IF;
  END;
BEGIN
  cria('BKP_MBE_MAP_BAI', 'CREATE TABLE BKP_MBE_MAP_BAI (ID_EXECUCAO VARCHAR2(30), COD_OBSOLETO NUMBER, COD_MANTIDO NUMBER)');
  cria('BKP_MBE_MAP_END', 'CREATE TABLE BKP_MBE_MAP_END (ID_EXECUCAO VARCHAR2(30), COD_OBSOLETO NUMBER, COD_MANTIDO NUMBER)');
  cria('BKP_MBE_TSIBAI', 'CREATE TABLE BKP_MBE_TSIBAI AS SELECT CAST(NULL AS VARCHAR2(30)) ID_EXECUCAO, t.* FROM TSIBAI t WHERE 1=0');
  cria('BKP_MBE_TSIEND', 'CREATE TABLE BKP_MBE_TSIEND AS SELECT CAST(NULL AS VARCHAR2(30)) ID_EXECUCAO, t.* FROM TSIEND t WHERE 1=0');
  cria('BKP_MBE_TGFPAR', 'CREATE TABLE BKP_MBE_TGFPAR AS SELECT CAST(NULL AS VARCHAR2(30)) ID_EXECUCAO, CAST(NULL AS VARCHAR2(30)) ROWID_ORIGINAL, t.* FROM TGFPAR t WHERE 1=0');
  cria('BKP_MBE_TSICEP', 'CREATE TABLE BKP_MBE_TSICEP AS SELECT CAST(NULL AS VARCHAR2(30)) ID_EXECUCAO, CAST(NULL AS VARCHAR2(30)) ROWID_ORIGINAL, t.* FROM TSICEP t WHERE 1=0');
END;
/

PROMPT === 02. MAPAS E BACKUPS DAS LINHAS AFETADAS ===
DECLARE
  v_qtd NUMBER;
BEGIN
  SELECT (SELECT COUNT(*) FROM BKP_MBE_MAP_BAI WHERE ID_EXECUCAO='MELLACO_20260904_083530')
       + (SELECT COUNT(*) FROM BKP_MBE_MAP_END WHERE ID_EXECUCAO='MELLACO_20260904_083530')
    INTO v_qtd FROM DUAL;
  IF v_qtd <> 0 THEN
    RAISE_APPLICATION_ERROR(-20011, 'ID_EXECUCAO ja utilizado: MELLACO_20260904_083530');
  END IF;
END;
/

INSERT INTO BKP_MBE_MAP_BAI (ID_EXECUCAO, COD_OBSOLETO, COD_MANTIDO)
SELECT 'MELLACO_20260904_083530', CODBAI, KEEP_ID
  FROM (
    SELECT CODBAI,
           MIN(CODBAI) OVER (PARTITION BY REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEBAI),
             'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇáàâãäéèêëíìîïóòôõöúùûüçÃãÕõÂâÊêÎîÔôÛû',
             'AAAAAEEEEIIIIOOOOOUUUUCAAAAAEEEEIIIIOOOOOUUUUCAAAOOAAEIIOOUU')), ' {2,}', ' ')) KEEP_ID,
           COUNT(*) OVER (PARTITION BY REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEBAI),
             'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇáàâãäéèêëíìîïóòôõöúùûüçÃãÕõÂâÊêÎîÔôÛû',
             'AAAAAEEEEIIIIOOOOOUUUUCAAAAAEEEEIIIIOOOOOUUUUCAAAOOAAEIIOOUU')), ' {2,}', ' ')) CNT
      FROM TSIBAI
  ) WHERE CNT > 1 AND CODBAI <> KEEP_ID;

INSERT INTO BKP_MBE_MAP_END (ID_EXECUCAO, COD_OBSOLETO, COD_MANTIDO)
SELECT 'MELLACO_20260904_083530', CODEND, KEEP_ID
  FROM (
    SELECT CODEND,
           MIN(CODEND) OVER (PARTITION BY TIPO, REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEEND),
             'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇáàâãäéèêëíìîïóòôõöúùûüçÃãÕõÂâÊêÎîÔôÛû',
             'AAAAAEEEEIIIIOOOOOUUUUCAAAAAEEEEIIIIOOOOOUUUUCAAAOOAAEIIOOUU')), ' {2,}', ' ')) KEEP_ID,
           COUNT(*) OVER (PARTITION BY TIPO, REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEEND),
             'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇáàâãäéèêëíìîïóòôõöúùûüçÃãÕõÂâÊêÎîÔôÛû',
             'AAAAAEEEEIIIIOOOOOUUUUCAAAAAEEEEIIIIOOOOOUUUUCAAAOOAAEIIOOUU')), ' {2,}', ' ')) CNT
      FROM TSIEND
  ) WHERE CNT > 1 AND CODEND <> KEEP_ID;

DECLARE
  v_bai NUMBER; v_end NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_bai FROM BKP_MBE_MAP_BAI WHERE ID_EXECUCAO='MELLACO_20260904_083530';
  SELECT COUNT(*) INTO v_end FROM BKP_MBE_MAP_END WHERE ID_EXECUCAO='MELLACO_20260904_083530';
  IF v_bai <> 345 OR v_end <> 7285 THEN
    RAISE_APPLICATION_ERROR(-20012, 'Diagnostico divergiu: bairros=' || v_bai || ', enderecos=' || v_end);
  END IF;
  DBMS_OUTPUT.PUT_LINE('OK: mapas conferidos: bairros=' || v_bai || ', enderecos=' || v_end);
END;
/

INSERT INTO BKP_MBE_TSIBAI
SELECT 'MELLACO_20260904_083530', b.* FROM TSIBAI b
 WHERE b.CODBAI IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_BAI WHERE ID_EXECUCAO='MELLACO_20260904_083530')
    OR b.CODBAI IN (SELECT COD_MANTIDO FROM BKP_MBE_MAP_BAI WHERE ID_EXECUCAO='MELLACO_20260904_083530');

INSERT INTO BKP_MBE_TSIEND
SELECT 'MELLACO_20260904_083530', e.* FROM TSIEND e
 WHERE e.CODEND IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_END WHERE ID_EXECUCAO='MELLACO_20260904_083530')
    OR e.CODEND IN (SELECT COD_MANTIDO FROM BKP_MBE_MAP_END WHERE ID_EXECUCAO='MELLACO_20260904_083530');

INSERT INTO BKP_MBE_TGFPAR
SELECT 'MELLACO_20260904_083530', ROWIDTOCHAR(ROWID), p.* FROM TGFPAR p
 WHERE p.CODBAI IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_BAI WHERE ID_EXECUCAO='MELLACO_20260904_083530')
    OR p.CODEND IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_END WHERE ID_EXECUCAO='MELLACO_20260904_083530');

INSERT INTO BKP_MBE_TSICEP
SELECT 'MELLACO_20260904_083530', ROWIDTOCHAR(ROWID), c.* FROM TSICEP c
 WHERE c.CODBAI IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_BAI WHERE ID_EXECUCAO='MELLACO_20260904_083530')
    OR c.CODEND IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_END WHERE ID_EXECUCAO='MELLACO_20260904_083530');

DECLARE
  v_pb NUMBER; v_pe NUMBER; v_cb NUMBER; v_ce NUMBER;
  v_bb NUMBER; v_be NUMBER; v_missing NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_pb FROM TGFPAR WHERE CODBAI IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_BAI WHERE ID_EXECUCAO='MELLACO_20260904_083530');
  SELECT COUNT(*) INTO v_pe FROM TGFPAR WHERE CODEND IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_END WHERE ID_EXECUCAO='MELLACO_20260904_083530');
  SELECT COUNT(*) INTO v_cb FROM TSICEP WHERE CODBAI IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_BAI WHERE ID_EXECUCAO='MELLACO_20260904_083530');
  SELECT COUNT(*) INTO v_ce FROM TSICEP WHERE CODEND IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_END WHERE ID_EXECUCAO='MELLACO_20260904_083530');
  IF v_pb <> 18 OR v_pe <> 4 OR v_cb <> 10717 OR v_ce <> 49746 THEN
    RAISE_APPLICATION_ERROR(-20013, 'Referencias divergiram: TGFPAR.BAI=' || v_pb || ', TGFPAR.END=' || v_pe || ', TSICEP.BAI=' || v_cb || ', TSICEP.END=' || v_ce);
  END IF;
  SELECT COUNT(*) INTO v_bb FROM BKP_MBE_TSIBAI WHERE ID_EXECUCAO='MELLACO_20260904_083530';
  SELECT COUNT(*) INTO v_be FROM BKP_MBE_TSIEND WHERE ID_EXECUCAO='MELLACO_20260904_083530';
  IF v_bb <> 684 OR v_be <> 14230 THEN
    RAISE_APPLICATION_ERROR(-20014, 'Backups dos pais divergiram: TSIBAI=' || v_bb || ', TSIEND=' || v_be);
  END IF;
  SELECT
    (SELECT COUNT(*) FROM TGFPAR p WHERE (p.CODBAI IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_BAI WHERE ID_EXECUCAO='MELLACO_20260904_083530') OR p.CODEND IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_END WHERE ID_EXECUCAO='MELLACO_20260904_083530')) AND NOT EXISTS (SELECT 1 FROM BKP_MBE_TGFPAR b WHERE b.ID_EXECUCAO='MELLACO_20260904_083530' AND CHARTOROWID(b.ROWID_ORIGINAL)=p.ROWID))
  + (SELECT COUNT(*) FROM TSICEP c WHERE (c.CODBAI IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_BAI WHERE ID_EXECUCAO='MELLACO_20260904_083530') OR c.CODEND IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_END WHERE ID_EXECUCAO='MELLACO_20260904_083530')) AND NOT EXISTS (SELECT 1 FROM BKP_MBE_TSICEP b WHERE b.ID_EXECUCAO='MELLACO_20260904_083530' AND CHARTOROWID(b.ROWID_ORIGINAL)=c.ROWID))
    INTO v_missing FROM DUAL;
  IF v_missing <> 0 THEN RAISE_APPLICATION_ERROR(-20015, 'Linhas dependentes sem backup: ' || v_missing); END IF;
  DBMS_OUTPUT.PUT_LINE('OK: referencias e backups conferidos.');
END;
/

COMMIT;
PROMPT === BACKUPS PERSISTIDOS; INICIO DO MERGE TRANSACIONAL ===

DECLARE
  v_restantes NUMBER; v_dup_bai NUMBER; v_dup_end NUMBER;
BEGIN
  UPDATE TGFPAR p
     SET CODBAI = NVL((SELECT m.COD_MANTIDO FROM BKP_MBE_MAP_BAI m WHERE m.ID_EXECUCAO='MELLACO_20260904_083530' AND m.COD_OBSOLETO=p.CODBAI), p.CODBAI),
         CODEND = NVL((SELECT m.COD_MANTIDO FROM BKP_MBE_MAP_END m WHERE m.ID_EXECUCAO='MELLACO_20260904_083530' AND m.COD_OBSOLETO=p.CODEND), p.CODEND)
   WHERE EXISTS (SELECT 1 FROM BKP_MBE_MAP_BAI m WHERE m.ID_EXECUCAO='MELLACO_20260904_083530' AND m.COD_OBSOLETO=p.CODBAI)
      OR EXISTS (SELECT 1 FROM BKP_MBE_MAP_END m WHERE m.ID_EXECUCAO='MELLACO_20260904_083530' AND m.COD_OBSOLETO=p.CODEND);

  UPDATE TSICEP c
     SET CODBAI = NVL((SELECT m.COD_MANTIDO FROM BKP_MBE_MAP_BAI m WHERE m.ID_EXECUCAO='MELLACO_20260904_083530' AND m.COD_OBSOLETO=c.CODBAI), c.CODBAI),
         CODEND = NVL((SELECT m.COD_MANTIDO FROM BKP_MBE_MAP_END m WHERE m.ID_EXECUCAO='MELLACO_20260904_083530' AND m.COD_OBSOLETO=c.CODEND), c.CODEND)
   WHERE EXISTS (SELECT 1 FROM BKP_MBE_MAP_BAI m WHERE m.ID_EXECUCAO='MELLACO_20260904_083530' AND m.COD_OBSOLETO=c.CODBAI)
      OR EXISTS (SELECT 1 FROM BKP_MBE_MAP_END m WHERE m.ID_EXECUCAO='MELLACO_20260904_083530' AND m.COD_OBSOLETO=c.CODEND);

  SELECT (SELECT COUNT(*) FROM TGFPAR p WHERE p.CODBAI IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_BAI WHERE ID_EXECUCAO='MELLACO_20260904_083530') OR p.CODEND IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_END WHERE ID_EXECUCAO='MELLACO_20260904_083530'))
       + (SELECT COUNT(*) FROM TSICEP c WHERE c.CODBAI IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_BAI WHERE ID_EXECUCAO='MELLACO_20260904_083530') OR c.CODEND IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_END WHERE ID_EXECUCAO='MELLACO_20260904_083530'))
    INTO v_restantes FROM DUAL;
  IF v_restantes <> 0 THEN RAISE_APPLICATION_ERROR(-20001, 'Referencias operacionais restantes: ' || v_restantes); END IF;

  DELETE FROM TSIBAI WHERE CODBAI IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_BAI WHERE ID_EXECUCAO='MELLACO_20260904_083530');
  DELETE FROM TSIEND WHERE CODEND IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_END WHERE ID_EXECUCAO='MELLACO_20260904_083530');

  UPDATE TSIBAI SET NOMEBAI = REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEBAI),
    'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇáàâãäéèêëíìîïóòôõöúùûüçÃãÕõÂâÊêÎîÔôÛû',
    'AAAAAEEEEIIIIOOOOOUUUUCAAAAAEEEEIIIIOOOOOUUUUCAAAOOAAEIIOOUU')), ' {2,}', ' ')
   WHERE CODBAI IN (SELECT COD_MANTIDO FROM BKP_MBE_MAP_BAI WHERE ID_EXECUCAO='MELLACO_20260904_083530');

  UPDATE TSIEND SET NOMEEND = REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEEND),
    'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇáàâãäéèêëíìîïóòôõöúùûüçÃãÕõÂâÊêÎîÔôÛû',
    'AAAAAEEEEIIIIOOOOOUUUUCAAAAAEEEEIIIIOOOOOUUUUCAAAOOAAEIIOOUU')), ' {2,}', ' ')
   WHERE CODEND IN (SELECT COD_MANTIDO FROM BKP_MBE_MAP_END WHERE ID_EXECUCAO='MELLACO_20260904_083530');

  SELECT COUNT(*) INTO v_dup_bai FROM (SELECT 1 FROM TSIBAI GROUP BY REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEBAI), 'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇáàâãäéèêëíìîïóòôõöúùûüçÃãÕõÂâÊêÎîÔôÛû', 'AAAAAEEEEIIIIOOOOOUUUUCAAAAAEEEEIIIIOOOOOUUUUCAAAOOAAEIIOOUU')), ' {2,}', ' ') HAVING COUNT(*) > 1);
  SELECT COUNT(*) INTO v_dup_end FROM (SELECT 1 FROM TSIEND GROUP BY TIPO, REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEEND), 'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇáàâãäéèêëíìîïóòôõöúùûüçÃãÕõÂâÊêÎîÔôÛû', 'AAAAAEEEEIIIIOOOOOUUUUCAAAAAEEEEIIIIOOOOOUUUUCAAAOOAAEIIOOUU')), ' {2,}', ' ') HAVING COUNT(*) > 1);
  IF v_dup_bai <> 0 OR v_dup_end <> 0 THEN RAISE_APPLICATION_ERROR(-20016, 'Duplicidades restantes: bairros=' || v_dup_bai || ', enderecos=' || v_dup_end); END IF;

  COMMIT;
  DBMS_OUTPUT.PUT_LINE('OK: merge concluido. ID_EXECUCAO=MELLACO_20260904_083530');
EXCEPTION WHEN OTHERS THEN
  ROLLBACK;
  DBMS_OUTPUT.PUT_LINE('ERRO: DML revertido; backups preservados. ' || SQLERRM);
  RAISE;
END;
/

PROMPT === FIM DO MERGE ===
