-- Reversao integral do merge MELLACO_20260904_083530.
SET SERVEROUTPUT ON SIZE UNLIMITED
SET DEFINE OFF
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

DECLARE
  v_qtd NUMBER; v_cols VARCHAR2(32767); v_sql VARCHAR2(32767);
  PROCEDURE reinsere(p_origem VARCHAR2, p_backup VARCHAR2, p_chave VARCHAR2) IS
  BEGIN
    SELECT LISTAGG(column_name, ',') WITHIN GROUP (ORDER BY column_id)
      INTO v_cols FROM ALL_TAB_COLUMNS
     WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND TABLE_NAME=UPPER(p_origem);
    v_sql := 'INSERT INTO ' || DBMS_ASSERT.SIMPLE_SQL_NAME(p_origem) || '(' || v_cols || ') SELECT ' || v_cols ||
             ' FROM ' || DBMS_ASSERT.SIMPLE_SQL_NAME(p_backup) || ' b WHERE b.ID_EXECUCAO=:id AND NOT EXISTS (SELECT 1 FROM ' ||
             DBMS_ASSERT.SIMPLE_SQL_NAME(p_origem) || ' o WHERE o.' || DBMS_ASSERT.SIMPLE_SQL_NAME(p_chave) || '=b.' || DBMS_ASSERT.SIMPLE_SQL_NAME(p_chave) || ')';
    EXECUTE IMMEDIATE v_sql USING 'MELLACO_20260904_083530';
  END;
BEGIN
  SELECT (SELECT COUNT(*) FROM BKP_MBE_MAP_BAI WHERE ID_EXECUCAO='MELLACO_20260904_083530')
       + (SELECT COUNT(*) FROM BKP_MBE_MAP_END WHERE ID_EXECUCAO='MELLACO_20260904_083530') INTO v_qtd FROM DUAL;
  IF v_qtd = 0 THEN RAISE_APPLICATION_ERROR(-20010, 'ID_EXECUCAO nao encontrado'); END IF;

  reinsere('TSIBAI','BKP_MBE_TSIBAI','CODBAI');
  reinsere('TSIEND','BKP_MBE_TSIEND','CODEND');

  UPDATE TSIBAI b SET NOMEBAI=(SELECT x.NOMEBAI FROM BKP_MBE_TSIBAI x WHERE x.ID_EXECUCAO='MELLACO_20260904_083530' AND x.CODBAI=b.CODBAI)
   WHERE EXISTS (SELECT 1 FROM BKP_MBE_TSIBAI x WHERE x.ID_EXECUCAO='MELLACO_20260904_083530' AND x.CODBAI=b.CODBAI);
  UPDATE TSIEND e SET NOMEEND=(SELECT x.NOMEEND FROM BKP_MBE_TSIEND x WHERE x.ID_EXECUCAO='MELLACO_20260904_083530' AND x.CODEND=e.CODEND)
   WHERE EXISTS (SELECT 1 FROM BKP_MBE_TSIEND x WHERE x.ID_EXECUCAO='MELLACO_20260904_083530' AND x.CODEND=e.CODEND);

  UPDATE TGFPAR p SET (CODBAI,CODEND)=(SELECT x.CODBAI,x.CODEND FROM BKP_MBE_TGFPAR x WHERE x.ID_EXECUCAO='MELLACO_20260904_083530' AND CHARTOROWID(x.ROWID_ORIGINAL)=p.ROWID)
   WHERE EXISTS (SELECT 1 FROM BKP_MBE_TGFPAR x WHERE x.ID_EXECUCAO='MELLACO_20260904_083530' AND CHARTOROWID(x.ROWID_ORIGINAL)=p.ROWID);
  UPDATE TSICEP c SET (CODBAI,CODEND)=(SELECT x.CODBAI,x.CODEND FROM BKP_MBE_TSICEP x WHERE x.ID_EXECUCAO='MELLACO_20260904_083530' AND CHARTOROWID(x.ROWID_ORIGINAL)=c.ROWID)
   WHERE EXISTS (SELECT 1 FROM BKP_MBE_TSICEP x WHERE x.ID_EXECUCAO='MELLACO_20260904_083530' AND CHARTOROWID(x.ROWID_ORIGINAL)=c.ROWID);

  COMMIT;
  DBMS_OUTPUT.PUT_LINE('OK: execucao MELLACO_20260904_083530 revertida; backups mantidos.');
EXCEPTION WHEN OTHERS THEN
  ROLLBACK;
  DBMS_OUTPUT.PUT_LINE('ERRO: reversao cancelada. ' || SQLERRM);
  RAISE;
END;
/
