SELECT 'SESSION_USER' METRICA, SYS_CONTEXT('USERENV','SESSION_USER') VALOR FROM DUAL
UNION ALL SELECT 'CURRENT_SCHEMA', SYS_CONTEXT('USERENV','CURRENT_SCHEMA') FROM DUAL
UNION ALL SELECT 'SERVICE_NAME', SYS_CONTEXT('USERENV','SERVICE_NAME') FROM DUAL
UNION ALL SELECT 'MAPA_BAI', TO_CHAR(COUNT(*)) FROM RMD_MVE_MRG_20260922
  WHERE ID_EXECUCAO='MOVE_MRG_20260922_01' AND TIPO='BAI'
UNION ALL SELECT 'MAPA_END', TO_CHAR(COUNT(*)) FROM RMD_MVE_MRG_20260922
  WHERE ID_EXECUCAO='MOVE_MRG_20260922_01' AND TIPO='END'
UNION ALL SELECT 'BACKUP_BAI_OBSOLETO', TO_CHAR(COUNT(*)) FROM BKP_RMD_MVE_20260922_BAI
  WHERE ID_EXECUCAO='MOVE_MRG_20260922_01'
UNION ALL SELECT 'BACKUP_END_OBSOLETO', TO_CHAR(COUNT(*)) FROM BKP_RMD_MVE_20260922_END
  WHERE ID_EXECUCAO='MOVE_MRG_20260922_01'
UNION ALL SELECT 'REFERENCIAS_AUDITADAS', TO_CHAR(COUNT(*)) FROM RMD_MVE_MRG_20260922_DEP
  WHERE ID_EXECUCAO='MOVE_MRG_20260922_01'
UNION ALL SELECT 'EXCECOES', TO_CHAR(COUNT(*)) FROM RMD_MVE_MRG_20260922_EXC
  WHERE ID_EXECUCAO='MOVE_MRG_20260922_01'
UNION ALL SELECT 'TSICEP_BAI_REMANESCENTE', TO_CHAR(COUNT(*)) FROM TSICEP t
  WHERE EXISTS (SELECT 1 FROM RMD_MVE_MRG_20260922 m WHERE m.ID_EXECUCAO='MOVE_MRG_20260922_01' AND m.TIPO='BAI' AND m.COD_OBSOLETO=t.CODBAI)
UNION ALL SELECT 'TSICEP_END_REMANESCENTE', TO_CHAR(COUNT(*)) FROM TSICEP t
  WHERE EXISTS (SELECT 1 FROM RMD_MVE_MRG_20260922 m WHERE m.ID_EXECUCAO='MOVE_MRG_20260922_01' AND m.TIPO='END' AND m.COD_OBSOLETO=t.CODEND)
UNION ALL SELECT 'TGFPAR_BAI_REMANESCENTE', TO_CHAR(COUNT(*)) FROM TGFPAR t
  WHERE EXISTS (SELECT 1 FROM RMD_MVE_MRG_20260922 m WHERE m.ID_EXECUCAO='MOVE_MRG_20260922_01' AND m.TIPO='BAI' AND m.COD_OBSOLETO=t.CODBAI)
UNION ALL SELECT 'TSIEMP_BAI_REMANESCENTE', TO_CHAR(COUNT(*)) FROM TSIEMP t
  WHERE EXISTS (SELECT 1 FROM RMD_MVE_MRG_20260922 m WHERE m.ID_EXECUCAO='MOVE_MRG_20260922_01' AND m.TIPO='BAI' AND m.COD_OBSOLETO=t.CODBAI)
UNION ALL SELECT 'BKP_TGFPAR_NOVO_BAI_INTACTO', TO_CHAR(COUNT(*)) FROM BKP_TGFPAR_NOVO t
  WHERE EXISTS (SELECT 1 FROM RMD_MVE_MRG_20260922 m WHERE m.ID_EXECUCAO='MOVE_MRG_20260922_01' AND m.TIPO='BAI' AND m.COD_OBSOLETO=t.CODBAI)
UNION ALL SELECT 'FILA_LOG_EVENTOS', TO_CHAR(COUNT(*)) FROM TEMP_TGLATS_V2
