WITH NORMALIZADO AS (
  SELECT CODEND, TIPO,
         REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEEND),
           'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇáàâãäéèêëíìîïóòôõöúùûüçÃãÕõÂâÊêÎîÔôÛû',
           'AAAAAEEEEIIIIOOOOOUUUUCAAAAAEEEEIIIIOOOOOUUUUCAAAOOAAEIIOOUU')),
           ' {2,}', ' ') AS NORM
    FROM TSIEND
), GRUPOS AS (
  SELECT CODEND, TIPO, NORM,
         COUNT(*) OVER (PARTITION BY TIPO, NORM) AS QTD_GRUPO,
         MIN(CODEND) OVER (PARTITION BY TIPO, NORM) AS CODIGO_MANTIDO
    FROM NORMALIZADO
)
SELECT 'LINHAS_EM_GRUPOS_DE_COLISAO' AS METRICA, TO_CHAR(COUNT(*)) AS VALOR
  FROM GRUPOS WHERE QTD_GRUPO > 1
UNION ALL
SELECT 'GRUPOS_DE_COLISAO', TO_CHAR(COUNT(*)) FROM (
  SELECT TIPO, NORM FROM GRUPOS WHERE QTD_GRUPO > 1 GROUP BY TIPO, NORM
)
UNION ALL
SELECT 'CODIGOS_OBSOLETOS_PELA_REGRA_SQL', TO_CHAR(COUNT(*))
  FROM GRUPOS WHERE QTD_GRUPO > 1 AND CODEND <> CODIGO_MANTIDO
UNION ALL
SELECT 'CODEND_NULOS_EM_GRUPOS_DE_COLISAO', TO_CHAR(COUNT(*))
  FROM GRUPOS WHERE QTD_GRUPO > 1 AND CODEND IS NULL
UNION ALL
SELECT 'GRUPOS_COM_CODEND_NULO', TO_CHAR(COUNT(*)) FROM (
  SELECT TIPO, NORM FROM GRUPOS
   WHERE QTD_GRUPO > 1 AND CODEND IS NULL GROUP BY TIPO, NORM
)
UNION ALL
SELECT 'MAPA_END', TO_CHAR(COUNT(*)) FROM RMD_MVE_MRG_20260922
 WHERE ID_EXECUCAO='MOVE_MRG_20260922_01' AND TIPO='END'
UNION ALL
SELECT 'BACKUP_END_OBSOLETO', TO_CHAR(COUNT(*)) FROM BKP_RMD_MVE_20260922_END
 WHERE ID_EXECUCAO='MOVE_MRG_20260922_01'
UNION ALL
SELECT 'PAIS_MAPEADOS_AINDA_VIVOS', TO_CHAR(COUNT(*)) FROM TSIEND p
 WHERE EXISTS (
   SELECT 1 FROM RMD_MVE_MRG_20260922 m
    WHERE m.ID_EXECUCAO='MOVE_MRG_20260922_01'
      AND m.TIPO='END' AND m.COD_OBSOLETO=p.CODEND
 )
