SELECT SYS_CONTEXT('USERENV','SESSION_USER') AS SESSION_USER,
       SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AS CURRENT_SCHEMA,
       SYS_CONTEXT('USERENV','SERVICE_NAME') AS SERVICE_NAME,
       SYS_CONTEXT('USERENV','DB_NAME') AS DB_NAME
  FROM DUAL;

SELECT COUNT(*) AS BASE_TOTAL_MAPA
  FROM BKP_RMD_FDUP_20260922
 WHERE ID_EXECUCAO='MOVE_FDUP_20260922_01';

SELECT STATUS_MAPA,COUNT(*) AS QTD_LINHAS,COUNT(DISTINCT NUNOTA) AS QTD_NOTAS
  FROM BKP_RMD_FDUP_20260922_PPG
 WHERE ID_EXECUCAO='MOVE_FDUP_20260922_01'
 GROUP BY STATUS_MAPA
 ORDER BY STATUS_MAPA;

SELECT COUNT(*) AS APTOS_COM_TGFFIN_POS_MAPA
  FROM BKP_RMD_FDUP_20260922_PPG M
 WHERE M.ID_EXECUCAO='MOVE_FDUP_20260922_01'
   AND M.STATUS_MAPA='APTO_PARA_VALIDACAO_FINAL'
   AND EXISTS (SELECT 1 FROM TGFFIN F WHERE F.NUNOTA=M.NUNOTA);
