-- Pos-validacao read-only da fase 32B do Card 09 para a MOVE.
-- A chave de auditoria continua vinculada ao mapa 32A; o ID do lote 32B
-- fica registrado separadamente pelo oracle_batch.py.

SELECT 'MAPA_TOTAL' AS METRICA, TO_CHAR(COUNT(*)) AS VALOR
  FROM BKP_RMD_FDUP_20260922_PPG
 WHERE ID_EXECUCAO='MOVE_FDUP_20260922_01'
UNION ALL
SELECT 'MAPA_APTOS', TO_CHAR(COUNT(*))
  FROM BKP_RMD_FDUP_20260922_PPG
 WHERE ID_EXECUCAO='MOVE_FDUP_20260922_01'
   AND STATUS_MAPA='APTO_PARA_VALIDACAO_FINAL'
UNION ALL
SELECT 'MAPA_SEM_VDUP', TO_CHAR(COUNT(*))
  FROM BKP_RMD_FDUP_20260922_PPG
 WHERE ID_EXECUCAO='MOVE_FDUP_20260922_01'
   AND STATUS_MAPA='SEM_VDUP_XML'
UNION ALL
SELECT 'AUDITORIA_INS', TO_CHAR(COUNT(*))
  FROM BKP_RMD_FDUP_20260922_INS
 WHERE ID_EXECUCAO='MOVE_FDUP_20260922_01'
UNION ALL
SELECT 'FINANCEIROS_AUDITADOS', TO_CHAR(COUNT(*))
  FROM BKP_RMD_FDUP_20260922_INS I
  JOIN TGFFIN F ON F.NUFIN=I.NUFIN AND F.NUNOTA=I.NUNOTA
 WHERE I.ID_EXECUCAO='MOVE_FDUP_20260922_01'
UNION ALL
SELECT 'AUDITORIA_SEM_TGFFIN', TO_CHAR(COUNT(*))
  FROM BKP_RMD_FDUP_20260922_INS I
 WHERE I.ID_EXECUCAO='MOVE_FDUP_20260922_01'
   AND NOT EXISTS (
       SELECT 1 FROM TGFFIN F WHERE F.NUFIN=I.NUFIN AND F.NUNOTA=I.NUNOTA
   )
UNION ALL
SELECT 'APTOS_SEM_FINANCEIRO', TO_CHAR(COUNT(*))
  FROM BKP_RMD_FDUP_20260922_PPG M
 WHERE M.ID_EXECUCAO='MOVE_FDUP_20260922_01'
   AND M.STATUS_MAPA='APTO_PARA_VALIDACAO_FINAL'
   AND NOT EXISTS (SELECT 1 FROM TGFFIN F WHERE F.NUNOTA=M.NUNOTA)
UNION ALL
SELECT 'DUPLICADOS_TGFFIN_POR_NUNOTA', TO_CHAR(COUNT(*))
  FROM (
      SELECT F.NUNOTA
        FROM TGFFIN F
        JOIN BKP_RMD_FDUP_20260922_PPG M ON M.NUNOTA=F.NUNOTA
       WHERE M.ID_EXECUCAO='MOVE_FDUP_20260922_01'
         AND M.STATUS_MAPA='APTO_PARA_VALIDACAO_FINAL'
       GROUP BY F.NUNOTA
      HAVING COUNT(*)>1
  )
UNION ALL
SELECT 'FINANCEIROS_SEM_AUDITORIA', TO_CHAR(COUNT(*))
  FROM TGFFIN F
  JOIN BKP_RMD_FDUP_20260922_PPG M ON M.NUNOTA=F.NUNOTA
 WHERE M.ID_EXECUCAO='MOVE_FDUP_20260922_01'
   AND M.STATUS_MAPA='APTO_PARA_VALIDACAO_FINAL'
   AND NOT EXISTS (
       SELECT 1 FROM BKP_RMD_FDUP_20260922_INS I
        WHERE I.ID_EXECUCAO='MOVE_FDUP_20260922_01'
          AND I.NUNOTA=F.NUNOTA AND I.NUFIN=F.NUFIN
   )
UNION ALL
SELECT 'DIVERGENCIA_VALOR_XML', TO_CHAR(COUNT(*))
  FROM BKP_RMD_FDUP_20260922_PPG M
  JOIN BKP_RMD_FDUP_20260922_INS I
    ON I.ID_EXECUCAO=M.ID_EXECUCAO AND I.NUNOTA=M.NUNOTA
  JOIN TGFFIN F ON F.NUFIN=I.NUFIN AND F.NUNOTA=I.NUNOTA
 WHERE M.ID_EXECUCAO='MOVE_FDUP_20260922_01'
   AND M.STATUS_MAPA='APTO_PARA_VALIDACAO_FINAL'
   AND (F.VLRDESDOB IS NULL OR ABS(F.VLRDESDOB-TO_NUMBER(TRIM(M.VDUP_XML),
       '999999999999999999D99999999',
       'NLS_NUMERIC_CHARACTERS=''.,'''))>0.01)
UNION ALL
SELECT 'DIVERGENCIA_VENCIMENTO_XML', TO_CHAR(COUNT(*))
  FROM BKP_RMD_FDUP_20260922_PPG M
  JOIN BKP_RMD_FDUP_20260922_INS I
    ON I.ID_EXECUCAO=M.ID_EXECUCAO AND I.NUNOTA=M.NUNOTA
  JOIN TGFFIN F ON F.NUFIN=I.NUFIN AND F.NUNOTA=I.NUNOTA
 WHERE M.ID_EXECUCAO='MOVE_FDUP_20260922_01'
   AND M.STATUS_MAPA='APTO_PARA_VALIDACAO_FINAL'
   AND (F.DTVENC IS NULL OR TRUNC(F.DTVENC)<>TO_DATE(TRIM(M.DVENC_XML),'YYYY-MM-DD'))
UNION ALL
SELECT 'DIVERGENCIA_CODCTABCOINT', TO_CHAR(COUNT(*))
  FROM BKP_RMD_FDUP_20260922_PPG M
  JOIN BKP_RMD_FDUP_20260922_INS I
    ON I.ID_EXECUCAO=M.ID_EXECUCAO AND I.NUNOTA=M.NUNOTA
  JOIN TGFFIN F ON F.NUFIN=I.NUFIN AND F.NUNOTA=I.NUNOTA
 WHERE M.ID_EXECUCAO='MOVE_FDUP_20260922_01'
   AND M.STATUS_MAPA='APTO_PARA_VALIDACAO_FINAL'
   AND DECODE(F.CODCTABCOINT,M.CODCTABCOINT,0,1)=1
UNION ALL
SELECT 'SOMA_VDUP_XML_APTOS',
       TO_CHAR(SUM(TO_NUMBER(TRIM(VDUP_XML),
           '999999999999999999D99999999',
           'NLS_NUMERIC_CHARACTERS=''.,''')),
           'FM9999999999999999990D00','NLS_NUMERIC_CHARACTERS=''.,''')
  FROM BKP_RMD_FDUP_20260922_PPG
 WHERE ID_EXECUCAO='MOVE_FDUP_20260922_01'
   AND STATUS_MAPA='APTO_PARA_VALIDACAO_FINAL'
UNION ALL
SELECT 'SOMA_AUDITORIA',
       TO_CHAR(NVL(SUM(VLRDESDOB),0),
           'FM9999999999999999990D00','NLS_NUMERIC_CHARACTERS=''.,''')
  FROM BKP_RMD_FDUP_20260922_INS
 WHERE ID_EXECUCAO='MOVE_FDUP_20260922_01'
UNION ALL
SELECT 'TGFNUM_ROWS', TO_CHAR(COUNT(*))
  FROM TGFNUM WHERE ARQUIVO='TGFFIN'
UNION ALL
SELECT 'TGFNUM_STATUS',
       CASE WHEN (SELECT COUNT(*) FROM TGFNUM WHERE ARQUIVO='TGFFIN')=1
                  AND NVL((SELECT MAX(ULTCOD) FROM TGFNUM WHERE ARQUIVO='TGFFIN'),-1)
                      >=NVL((SELECT MAX(NUFIN)
                               FROM BKP_RMD_FDUP_20260922_INS
                              WHERE ID_EXECUCAO='MOVE_FDUP_20260922_01'),0)
            THEN 'CONSISTENTE' ELSE 'DIVERGENTE' END
  FROM DUAL
UNION ALL
SELECT 'EXCECAO_13881_COM_FINANCEIRO', TO_CHAR(COUNT(*))
  FROM TGFFIN WHERE NUNOTA=13881;
