-- Somente leitura. Execute conectado exclusivamente na MEGANET RJ.
SET SERVEROUTPUT ON SIZE UNLIMITED;
SET DEFINE OFF;
SET PAGESIZE 500;
SET LINESIZE 240;

PROMPT === IDENTIDADE DA CONEXAO ===
SELECT SYS_CONTEXT('USERENV','DB_NAME') DB_NAME,
       SYS_CONTEXT('USERENV','SERVICE_NAME') SERVICE_NAME,
       SYS_CONTEXT('USERENV','CURRENT_SCHEMA') CURRENT_SCHEMA
  FROM DUAL;
SELECT CODEMP, RAZAOSOCIAL, CGC FROM TSIEMP WHERE CODEMP = 1;

PROMPT === PARES PROPOSTOS (ORIGEM -> DESTINO) ===
WITH MAPA AS (
  SELECT 2667 ORIGEM, 1619 DESTINO, '00262857707' DOCUMENTO FROM DUAL UNION ALL
  SELECT 2689, 481, '01820733000135' FROM DUAL
)
SELECT M.ORIGEM, O.NOMEPARC NOME_ORIGEM, M.DESTINO, D.NOMEPARC NOME_DESTINO,
       REGEXP_REPLACE(O.CGC_CPF,'[^0-9]') DOC_ORIGEM,
       REGEXP_REPLACE(D.CGC_CPF,'[^0-9]') DOC_DESTINO
  FROM MAPA M
  LEFT JOIN TGFPAR O ON O.CODPARC=M.ORIGEM
  LEFT JOIN TGFPAR D ON D.CODPARC=M.DESTINO
 ORDER BY M.DESTINO;

PROMPT === COMPARACAO CADASTRAL (IGNORA DTCAD E DTALTER) ===
DECLARE
  V_COLS VARCHAR2(32767);
  V_SQL  VARCHAR2(32767);
  V_DIF  NUMBER;
  PROCEDURE COMPARA(P_A NUMBER, P_B NUMBER) IS
  BEGIN
    V_SQL := 'SELECT COUNT(*) FROM ('||
             'SELECT '||V_COLS||' FROM TGFPAR WHERE CODPARC='||P_A||
             ' MINUS SELECT '||V_COLS||' FROM TGFPAR WHERE CODPARC='||P_B||
             ' UNION ALL SELECT '||V_COLS||' FROM TGFPAR WHERE CODPARC='||P_B||
             ' MINUS SELECT '||V_COLS||' FROM TGFPAR WHERE CODPARC='||P_A||')';
    EXECUTE IMMEDIATE V_SQL INTO V_DIF;
    DBMS_OUTPUT.PUT_LINE('PAR='||P_A||'/'||P_B||';DIFERENCAS='||V_DIF||
      CASE WHEN V_DIF=0 THEN ';STATUS=IDENTICOS_NOS_CAMPOS_COMPARAVEIS'
           ELSE ';STATUS=DIVERGENTES_NAO_EXECUTAR' END);
  END;
BEGIN
  SELECT LISTAGG('"'||COLUMN_NAME||'"', ',') WITHIN GROUP (ORDER BY COLUMN_ID)
    INTO V_COLS
    FROM ALL_TAB_COLUMNS
   WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
     AND TABLE_NAME='TGFPAR'
     AND COLUMN_NAME NOT IN ('CODPARC','DTCAD','DTALTER')
     AND DATA_TYPE NOT IN ('BLOB','CLOB','NCLOB','LONG','LONG RAW','BFILE','XMLTYPE');
  COMPARA(2667,1619);
  DBMS_OUTPUT.PUT_LINE('PAR=2689/481;STATUS=FORA_DO_ESCOPO_POR_DIVERGENCIA_CADASTRAL');
END;
/

PROMPT === DETALHAMENTO DOS CAMPOS DIVERGENTES ===
DECLARE
  V_DIF NUMBER;
  V_A   VARCHAR2(4000);
  V_B   VARCHAR2(4000);
  PROCEDURE DETALHA(P_A NUMBER, P_B NUMBER) IS
  BEGIN
    FOR C IN (
      SELECT COLUMN_NAME, DATA_TYPE
        FROM ALL_TAB_COLUMNS
       WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
         AND TABLE_NAME='TGFPAR'
         AND COLUMN_NAME NOT IN ('CODPARC','DTCAD','DTALTER')
         AND DATA_TYPE NOT IN ('BLOB','CLOB','NCLOB','LONG','LONG RAW','BFILE','XMLTYPE')
       ORDER BY COLUMN_ID
    ) LOOP
      EXECUTE IMMEDIATE
        'SELECT COUNT(*),MAX(TO_CHAR(A."'||C.COLUMN_NAME||'")),MAX(TO_CHAR(B."'||C.COLUMN_NAME||'")) '||
        'FROM TGFPAR A JOIN TGFPAR B ON B.CODPARC=:1 WHERE A.CODPARC=:2 '||
        'AND DECODE(A."'||C.COLUMN_NAME||'",B."'||C.COLUMN_NAME||'",0,1)=1'
        INTO V_DIF,V_A,V_B USING P_B,P_A;
      IF V_DIF>0 THEN
        DBMS_OUTPUT.PUT_LINE('PAR='||P_A||'/'||P_B||';CAMPO='||C.COLUMN_NAME||
          ';ORIGEM='||NVL(V_A,'<NULL>')||';DESTINO='||NVL(V_B,'<NULL>'));
      END IF;
    END LOOP;
  END;
BEGIN
  DETALHA(2667,1619);
  DBMS_OUTPUT.PUT_LINE('PAR=2689/481;DETALHAMENTO=NAO_APLICAVEL_FORA_DO_ESCOPO');
END;
/

PROMPT === CAMPOS NAO COMPARADOS AUTOMATICAMENTE ===
SELECT COLUMN_NAME, DATA_TYPE FROM ALL_TAB_COLUMNS
 WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
   AND TABLE_NAME='TGFPAR'
   AND DATA_TYPE IN ('BLOB','CLOB','NCLOB','LONG','LONG RAW','BFILE','XMLTYPE')
 ORDER BY COLUMN_ID;

PROMPT === REFERENCIAS A SEREM TRATADAS E QUANTIDADES ===
DECLARE
  V_QTD NUMBER;
BEGIN
  FOR R IN (
    WITH FKS AS (
      SELECT C.OWNER, C.TABLE_NAME, CC.COLUMN_NAME
        FROM ALL_CONSTRAINTS C
        JOIN ALL_CONS_COLUMNS CC ON CC.OWNER=C.OWNER AND CC.CONSTRAINT_NAME=C.CONSTRAINT_NAME
        JOIN ALL_CONSTRAINTS P ON P.OWNER=C.R_OWNER AND P.CONSTRAINT_NAME=C.R_CONSTRAINT_NAME
        JOIN ALL_CONS_COLUMNS PC ON PC.OWNER=P.OWNER AND PC.CONSTRAINT_NAME=P.CONSTRAINT_NAME AND PC.POSITION=CC.POSITION
       WHERE C.CONSTRAINT_TYPE='R' AND C.STATUS='ENABLED'
         AND P.OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND P.TABLE_NAME='TGFPAR'
         AND PC.COLUMN_NAME='CODPARC'
         AND (SELECT COUNT(*) FROM ALL_CONS_COLUMNS X WHERE X.OWNER=C.OWNER AND X.CONSTRAINT_NAME=C.CONSTRAINT_NAME)=1
    ), NOMINAIS AS (
      SELECT C.OWNER, C.TABLE_NAME, C.COLUMN_NAME
        FROM ALL_TAB_COLUMNS C
        JOIN ALL_TABLES T ON T.OWNER=C.OWNER AND T.TABLE_NAME=C.TABLE_NAME
       WHERE C.OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND C.COLUMN_NAME='CODPARC'
    )
    SELECT DISTINCT OWNER, TABLE_NAME, COLUMN_NAME FROM (
      SELECT * FROM FKS UNION ALL SELECT * FROM NOMINAIS
    ) WHERE NOT (TABLE_NAME='TGFPAR' AND COLUMN_NAME='CODPARC')
      AND TABLE_NAME NOT LIKE 'BKP\_%' ESCAPE '\'
      AND TABLE_NAME NOT LIKE '%\_BKP' ESCAPE '\'
    ORDER BY OWNER,TABLE_NAME,COLUMN_NAME
  ) LOOP
    BEGIN
      EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM "'||R.OWNER||'"."'||R.TABLE_NAME||
                        '" WHERE "'||R.COLUMN_NAME||'" = 2667' INTO V_QTD;
      IF V_QTD>0 THEN
        DBMS_OUTPUT.PUT_LINE(R.OWNER||'.'||R.TABLE_NAME||'.'||R.COLUMN_NAME||'='||V_QTD);
      END IF;
    EXCEPTION WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE('NAO_LIDA='||R.OWNER||'.'||R.TABLE_NAME||'.'||R.COLUMN_NAME||';ERRO='||SQLERRM);
    END;
  END LOOP;
END;
/

PROMPT STATUS FINAL: DIAGNOSTICO APENAS; NENHUM DADO ALTERADO.
