-- Merge controlado MEGANET RJ. NAO executar antes de validar o diagnostico.
-- Destino preservado: 1619. Origem removida: 2667.
-- DTCAD e DTALTER sao campos de auditoria e nao impedem a equivalencia cadastral.
SET SERVEROUTPUT ON SIZE UNLIMITED;
SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

-- DDL isolado: as tabelas precisam existir antes da compilacao do bloco funcional.
DECLARE
  N NUMBER;
  PROCEDURE CRIA(P_NOME VARCHAR2, P_DDL VARCHAR2) IS
  BEGIN
    SELECT COUNT(*) INTO N FROM ALL_TABLES
     WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND TABLE_NAME=UPPER(P_NOME);
    IF N=0 THEN EXECUTE IMMEDIATE P_DDL; END IF;
  END;
BEGIN
  IF UPPER(SYS_CONTEXT('USERENV','SERVICE_NAME')) NOT LIKE 'MEGANETRJPRD%' THEN
    RAISE_APPLICATION_ERROR(-20500,'Conexao nao e MEGANETRJPRD. Operacao bloqueada.');
  END IF;
  CRIA('BKP_MPC_MAP_MEGANET',
    'CREATE TABLE BKP_MPC_MAP_MEGANET (ID_EXECUCAO VARCHAR2(30),DH_EXECUCAO TIMESTAMP,USUARIO_EXECUCAO VARCHAR2(128),CODPARC_ORIGEM NUMBER,CODPARC_DESTINO NUMBER,CGC_CPF VARCHAR2(30))');
  CRIA('BKP_MPC_REF_MEGANET',
    'CREATE TABLE BKP_MPC_REF_MEGANET (ID_EXECUCAO VARCHAR2(30),DH_EXECUCAO TIMESTAMP,OWNER_REF VARCHAR2(128),TABELA_REF VARCHAR2(128),COLUNA_REF VARCHAR2(128),ROWID_ORIGINAL VARCHAR2(30),CODPARC_ANTES NUMBER,CODPARC_DEPOIS NUMBER)');
  CRIA('BKP_MPC_PAR_MEGANET',
    'CREATE TABLE BKP_MPC_PAR_MEGANET AS SELECT CAST(NULL AS VARCHAR2(30)) ID_EXECUCAO,CAST(NULL AS TIMESTAMP) DH_EXECUCAO,CAST(NULL AS VARCHAR2(128)) USUARIO_EXECUCAO,T.* FROM TGFPAR T WHERE 1=0');
  CRIA('BKP_MPC_TGFCPP_MEGANET',
    'CREATE TABLE BKP_MPC_TGFCPP_MEGANET AS SELECT CAST(NULL AS VARCHAR2(30)) ID_EXECUCAO,CAST(NULL AS TIMESTAMP) DH_EXECUCAO,CAST(NULL AS VARCHAR2(10)) PAPEL,T.* FROM TGFCPP T WHERE 1=0');
  DBMS_OUTPUT.PUT_LINE('ESTRUTURAS_DE_BACKUP=OK');
END;
/

DECLARE
  C_ID CONSTANT VARCHAR2(30) := 'MEGANET_20260909_MPC02';
  V_QTD NUMBER;
  V_COLS VARCHAR2(32767);
  V_DIF NUMBER;
  PROCEDURE EXIGE_IDENTICOS(P_A NUMBER,P_B NUMBER) IS
    S VARCHAR2(32767);
  BEGIN
    S := 'SELECT COUNT(*) FROM (SELECT '||V_COLS||' FROM TGFPAR WHERE CODPARC='||P_A||
         ' MINUS SELECT '||V_COLS||' FROM TGFPAR WHERE CODPARC='||P_B||
         ' UNION ALL SELECT '||V_COLS||' FROM TGFPAR WHERE CODPARC='||P_B||
         ' MINUS SELECT '||V_COLS||' FROM TGFPAR WHERE CODPARC='||P_A||')';
    EXECUTE IMMEDIATE S INTO V_DIF;
    IF V_DIF<>0 THEN RAISE_APPLICATION_ERROR(-20501,'TGFPAR divergente: '||P_A||'/'||P_B); END IF;
  END;
BEGIN
  IF UPPER(SYS_CONTEXT('USERENV','SERVICE_NAME')) NOT LIKE 'MEGANETRJPRD%' THEN
    RAISE_APPLICATION_ERROR(-20500,'Conexao nao e MEGANETRJPRD. Operacao bloqueada.');
  END IF;
  SELECT COUNT(*) INTO V_QTD FROM TGFPAR
   WHERE CODPARC IN (1619,2667)
     AND REGEXP_REPLACE(CGC_CPF,'[^0-9]')='00262857707';
  IF V_QTD<>2 THEN RAISE_APPLICATION_ERROR(-20502,'O par 1619/2667 nao confere.'); END IF;

  SELECT LISTAGG('"'||COLUMN_NAME||'"', ',') WITHIN GROUP (ORDER BY COLUMN_ID)
    INTO V_COLS FROM ALL_TAB_COLUMNS
   WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
     AND TABLE_NAME='TGFPAR' AND COLUMN_NAME NOT IN ('CODPARC','DTCAD','DTALTER')
     AND DATA_TYPE NOT IN ('BLOB','CLOB','NCLOB','LONG','LONG RAW','BFILE','XMLTYPE');
  EXIGE_IDENTICOS(2667,1619);

  SELECT COUNT(*) INTO V_QTD FROM BKP_MPC_MAP_MEGANET WHERE ID_EXECUCAO=C_ID;
  IF V_QTD>0 THEN RAISE_APPLICATION_ERROR(-20503,'ID de execucao ja utilizado: '||C_ID); END IF;
  INSERT INTO BKP_MPC_MAP_MEGANET VALUES(C_ID,SYSTIMESTAMP,USER,2667,1619,'00262857707');
  INSERT INTO BKP_MPC_PAR_MEGANET
    SELECT C_ID,SYSTIMESTAMP,USER,P.* FROM TGFPAR P WHERE P.CODPARC = 2667;
  INSERT INTO BKP_MPC_TGFCPP_MEGANET
    SELECT C_ID,SYSTIMESTAMP,'DESTINO',T.* FROM TGFCPP T
     WHERE T.CODPROD=300003 AND T.CODPARC=1619 AND T.TIPMOV='V';
  INSERT INTO BKP_MPC_TGFCPP_MEGANET
    SELECT C_ID,SYSTIMESTAMP,'ORIGEM',T.* FROM TGFCPP T
     WHERE T.CODPROD=300003 AND T.CODPARC=2667 AND T.TIPMOV='V';

  FOR R IN (
    WITH FKS AS (
      SELECT C.OWNER,C.TABLE_NAME,CC.COLUMN_NAME
      FROM ALL_CONSTRAINTS C JOIN ALL_CONS_COLUMNS CC ON CC.OWNER=C.OWNER AND CC.CONSTRAINT_NAME=C.CONSTRAINT_NAME
      JOIN ALL_CONSTRAINTS P ON P.OWNER=C.R_OWNER AND P.CONSTRAINT_NAME=C.R_CONSTRAINT_NAME
      JOIN ALL_CONS_COLUMNS PC ON PC.OWNER=P.OWNER AND PC.CONSTRAINT_NAME=P.CONSTRAINT_NAME AND PC.POSITION=CC.POSITION
      WHERE C.CONSTRAINT_TYPE='R' AND C.STATUS='ENABLED' AND P.OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
        AND P.TABLE_NAME='TGFPAR' AND PC.COLUMN_NAME='CODPARC'
        AND (SELECT COUNT(*) FROM ALL_CONS_COLUMNS X WHERE X.OWNER=C.OWNER AND X.CONSTRAINT_NAME=C.CONSTRAINT_NAME)=1
    ), NOMINAIS AS (
      SELECT C.OWNER,C.TABLE_NAME,C.COLUMN_NAME FROM ALL_TAB_COLUMNS C
      JOIN ALL_TABLES T ON T.OWNER=C.OWNER AND T.TABLE_NAME=C.TABLE_NAME
      WHERE C.OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND C.COLUMN_NAME='CODPARC'
    )
    SELECT DISTINCT OWNER,TABLE_NAME,COLUMN_NAME FROM (SELECT * FROM FKS UNION ALL SELECT * FROM NOMINAIS)
     WHERE NOT (TABLE_NAME='TGFPAR' AND COLUMN_NAME='CODPARC')
       AND TABLE_NAME NOT LIKE 'BKP\_%' ESCAPE '\'
       AND TABLE_NAME NOT LIKE '%\_BKP' ESCAPE '\'
       AND TABLE_NAME <> 'TGFCPP'
  ) LOOP
    EXECUTE IMMEDIATE
      'INSERT INTO BKP_MPC_REF_MEGANET SELECT :1,SYSTIMESTAMP,:2,:3,:4,ROWIDTOCHAR(ROWID),'||
      '"'||R.COLUMN_NAME||'",1619 '||
      'FROM "'||R.OWNER||'"."'||R.TABLE_NAME||'" WHERE "'||R.COLUMN_NAME||'" = 2667'
      USING C_ID,R.OWNER,R.TABLE_NAME,R.COLUMN_NAME;
  END LOOP;
  COMMIT; -- backups persistentes antes de qualquer alteracao funcional
  DBMS_OUTPUT.PUT_LINE('BACKUPS_CONFIRMADOS;ID_EXECUCAO='||C_ID);

  BEGIN
    -- A PK da TGFCPP e (CODPROD,CODPARC,TIPMOV). Para o produto 300003/V,
    -- preserva o registro mais recente ja existente no parceiro destino.
    DELETE FROM TGFCPP O
     WHERE O.CODPROD=300003 AND O.CODPARC=2667 AND O.TIPMOV='V'
       AND EXISTS (
         SELECT 1 FROM TGFCPP D
          WHERE D.CODPROD=O.CODPROD AND D.CODPARC=1619 AND D.TIPMOV=O.TIPMOV
            AND D.DTULT >= O.DTULT
       );
    IF SQL%ROWCOUNT<>1 THEN
      RAISE_APPLICATION_ERROR(-20506,'Colisao TGFCPP nao corresponde ao registro mais recente esperado.');
    END IF;
    DBMS_OUTPUT.PUT_LINE('COLISAO_RESOLVIDA=TGFCPP;CODPROD=300003;TIPMOV=V;PRESERVADO=1619');

    FOR R IN (SELECT OWNER_REF,TABELA_REF,COLUNA_REF,COUNT(*) QTD
                FROM BKP_MPC_REF_MEGANET WHERE ID_EXECUCAO=C_ID
               GROUP BY OWNER_REF,TABELA_REF,COLUNA_REF ORDER BY 1,2,3) LOOP
      EXECUTE IMMEDIATE
        'UPDATE "'||R.OWNER_REF||'"."'||R.TABELA_REF||'" T SET "'||R.COLUNA_REF||
        '"=1619 '||
        'WHERE ROWID IN (SELECT CHARTOROWID(B.ROWID_ORIGINAL) FROM BKP_MPC_REF_MEGANET B '||
        'WHERE B.ID_EXECUCAO=:1 AND B.OWNER_REF=:2 AND B.TABELA_REF=:3 AND B.COLUNA_REF=:4)'
        USING C_ID,R.OWNER_REF,R.TABELA_REF,R.COLUNA_REF;
      IF SQL%ROWCOUNT<>R.QTD THEN RAISE_APPLICATION_ERROR(-20504,'Atualizacao divergente em '||R.TABELA_REF||'.'||R.COLUNA_REF); END IF;
      DBMS_OUTPUT.PUT_LINE('ATUALIZADO='||R.OWNER_REF||'.'||R.TABELA_REF||'.'||R.COLUNA_REF||';QTD='||R.QTD);
    END LOOP;
    DELETE FROM TGFPAR WHERE CODPARC = 2667;
    IF SQL%ROWCOUNT<>1 THEN RAISE_APPLICATION_ERROR(-20505,'Exclusao TGFPAR divergente.'); END IF;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('STATUS=SUCESSO;ID_EXECUCAO='||C_ID||';PARCEIROS_REMOVIDOS=1');
  EXCEPTION WHEN OTHERS THEN
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('STATUS=ERRO;ALTERACOES_FUNCIONAIS_REVERTIDAS;BACKUPS_PRESERVADOS');
    RAISE;
  END;
END;
/
