-- Rollback pontual do merge MEGANET_20260909_MPC02.
SET SERVEROUTPUT ON SIZE UNLIMITED;
SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;
DECLARE
  C_ID CONSTANT VARCHAR2(30) := 'MEGANET_20260909_MPC02';
  V_COLS VARCHAR2(32767);
  V_QTD NUMBER;
BEGIN
  IF UPPER(SYS_CONTEXT('USERENV','SERVICE_NAME')) NOT LIKE 'MEGANETRJPRD%' THEN
    RAISE_APPLICATION_ERROR(-20520,'Conexao nao e MEGANETRJPRD. Rollback bloqueado.');
  END IF;
  SELECT COUNT(*) INTO V_QTD FROM BKP_MPC_PAR_MEGANET WHERE ID_EXECUCAO=C_ID;
  IF V_QTD<>1 THEN RAISE_APPLICATION_ERROR(-20521,'Backup do parceiro 2667 nao encontrado.'); END IF;
  SELECT COUNT(*) INTO V_QTD FROM TGFPAR WHERE CODPARC = 2667;
  IF V_QTD<>0 THEN RAISE_APPLICATION_ERROR(-20522,'Parceiro origem ja existe; rollback bloqueado.'); END IF;

  SELECT LISTAGG('"'||COLUMN_NAME||'"',',') WITHIN GROUP(ORDER BY COLUMN_ID)
    INTO V_COLS FROM ALL_TAB_COLUMNS
   WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
     AND TABLE_NAME='TGFPAR' AND VIRTUAL_COLUMN='NO';
  EXECUTE IMMEDIATE 'INSERT INTO TGFPAR ('||V_COLS||') SELECT '||V_COLS||
                    ' FROM BKP_MPC_PAR_MEGANET WHERE ID_EXECUCAO=:1' USING C_ID;
  IF SQL%ROWCOUNT<>1 THEN RAISE_APPLICATION_ERROR(-20523,'Restauracao TGFPAR divergente.'); END IF;

  INSERT INTO TGFCPP (CODPROD,CODPARC,TIPMOV,NUNOTA,DTULT,QTDNEG,VLRUNIT)
  SELECT CODPROD,CODPARC,TIPMOV,NUNOTA,DTULT,QTDNEG,VLRUNIT
    FROM BKP_MPC_TGFCPP_MEGANET
   WHERE ID_EXECUCAO=C_ID AND PAPEL='ORIGEM';
  IF SQL%ROWCOUNT<>1 THEN RAISE_APPLICATION_ERROR(-20525,'Restauracao TGFCPP divergente.'); END IF;
  DBMS_OUTPUT.PUT_LINE('RESTAURADO=TGFCPP;CODPARC=2667;CODPROD=300003;TIPMOV=V');

  FOR R IN (SELECT OWNER_REF,TABELA_REF,COLUNA_REF,COUNT(*) QTD
              FROM BKP_MPC_REF_MEGANET WHERE ID_EXECUCAO=C_ID
             GROUP BY OWNER_REF,TABELA_REF,COLUNA_REF ORDER BY 1,2,3) LOOP
    -- Nao sobrescreve linha que tenha sido redirecionada novamente apos o merge.
    EXECUTE IMMEDIATE
      'UPDATE "'||R.OWNER_REF||'"."'||R.TABELA_REF||'" T SET "'||R.COLUNA_REF||
      '"=(SELECT B.CODPARC_ANTES FROM BKP_MPC_REF_MEGANET B WHERE B.ID_EXECUCAO=:1 '||
      'AND B.OWNER_REF=:2 AND B.TABELA_REF=:3 AND B.COLUNA_REF=:4 AND CHARTOROWID(B.ROWID_ORIGINAL)=T.ROWID) '||
      'WHERE ROWID IN (SELECT CHARTOROWID(B.ROWID_ORIGINAL) FROM BKP_MPC_REF_MEGANET B WHERE B.ID_EXECUCAO=:5 '||
      'AND B.OWNER_REF=:6 AND B.TABELA_REF=:7 AND B.COLUNA_REF=:8) AND "'||R.COLUNA_REF||
      '"=(SELECT B.CODPARC_DEPOIS FROM BKP_MPC_REF_MEGANET B WHERE B.ID_EXECUCAO=:9 '||
      'AND B.OWNER_REF=:10 AND B.TABELA_REF=:11 AND B.COLUNA_REF=:12 AND CHARTOROWID(B.ROWID_ORIGINAL)=T.ROWID)'
      USING C_ID,R.OWNER_REF,R.TABELA_REF,R.COLUNA_REF,
            C_ID,R.OWNER_REF,R.TABELA_REF,R.COLUNA_REF,
            C_ID,R.OWNER_REF,R.TABELA_REF,R.COLUNA_REF;
    IF SQL%ROWCOUNT<>R.QTD THEN RAISE_APPLICATION_ERROR(-20524,'Rollback divergente em '||R.TABELA_REF||'.'||R.COLUNA_REF); END IF;
    DBMS_OUTPUT.PUT_LINE('REVERTIDO='||R.OWNER_REF||'.'||R.TABELA_REF||'.'||R.COLUNA_REF||';QTD='||R.QTD);
  END LOOP;
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('STATUS=ROLLBACK_CONCLUIDO;ID_EXECUCAO='||C_ID);
EXCEPTION WHEN OTHERS THEN
  ROLLBACK;
  DBMS_OUTPUT.PUT_LINE('STATUS=ERRO_ROLLBACK;NENHUMA_ALTERACAO_CONFIRMADA');
  RAISE;
END;
/
