-- FKs reais que apontam para TSIBAI/TSIEND; somente leitura.
SELECT C.OWNER,
       C.CONSTRAINT_NAME,
       C.TABLE_NAME,
       C.STATUS,
       R.OWNER AS REFERENCED_OWNER,
       R.TABLE_NAME AS REFERENCED_TABLE
  FROM ALL_CONSTRAINTS C
  JOIN ALL_CONSTRAINTS R
    ON R.OWNER = C.R_OWNER
   AND R.CONSTRAINT_NAME = C.R_CONSTRAINT_NAME
 WHERE C.CONSTRAINT_TYPE = 'R'
   AND R.TABLE_NAME IN ('TSIBAI', 'TSIEND')
 ORDER BY R.TABLE_NAME, C.OWNER, C.TABLE_NAME, C.CONSTRAINT_NAME;
