-- Resumo somente leitura dos inventarios ja executados.
SELECT 'INVALIDOS' AS ITEM,
       COUNT(*) AS QTD
  FROM ALL_OBJECTS
 WHERE OWNER = SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
   AND STATUS = 'INVALID'
UNION ALL
SELECT 'ERROS_ALL_ERRORS', COUNT(*)
  FROM ALL_ERRORS
 WHERE OWNER = SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
UNION ALL
SELECT 'TRIGGERS', COUNT(*)
  FROM ALL_TRIGGERS
 WHERE OWNER = SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
UNION ALL
SELECT 'TABELAS_TEMPORARIAS', COUNT(*)
  FROM ALL_TABLES
 WHERE OWNER = SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
   AND TEMPORARY = 'Y'
UNION ALL
SELECT 'FK_TSIBAI_TSIEND', COUNT(*)
  FROM ALL_CONSTRAINTS C
  JOIN ALL_CONSTRAINTS R
    ON R.OWNER = C.R_OWNER
   AND R.CONSTRAINT_NAME = C.R_CONSTRAINT_NAME
 WHERE C.CONSTRAINT_TYPE = 'R'
   AND R.TABLE_NAME IN ('TSIBAI','TSIEND');
