-- Resumos somente leitura para separar os inventarios por categoria.
SELECT R.TABLE_NAME AS REFERENCED_TABLE,
       COUNT(*) AS QTD_FKS
  FROM ALL_CONSTRAINTS C
  JOIN ALL_CONSTRAINTS R
    ON R.OWNER = C.R_OWNER
   AND R.CONSTRAINT_NAME = C.R_CONSTRAINT_NAME
 WHERE C.CONSTRAINT_TYPE = 'R'
   AND R.TABLE_NAME IN ('TSIBAI','TSIEND')
 GROUP BY R.TABLE_NAME
 ORDER BY R.TABLE_NAME;
