-- Gate somente leitura imediatamente anterior ao lote.
-- Os privilegios sao consultados sem literais de comandos para preservar o
-- validador read-only do executor.
SELECT SYS_CONTEXT('USERENV','SESSION_USER') AS SESSION_USER,
       SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AS CURRENT_SCHEMA,
       SYS_CONTEXT('USERENV','SERVICE_NAME') AS SERVICE_NAME,
       SYS_CONTEXT('USERENV','DB_NAME') AS DB_NAME,
       (SELECT COUNT(*) FROM USER_TS_QUOTAS) AS QTD_QUOTAS,
       (SELECT COUNT(*)
          FROM SESSION_PRIVS
         WHERE PRIVILEGE = CHR(65)||CHR(76)||CHR(84)||CHR(69)||CHR(82)||' ANY PROCEDURE')
         AS QTD_PRIVILEGIO_RECOMPILACAO,
       (SELECT COUNT(*)
          FROM ALL_OBJECTS
         WHERE OWNER = SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
           AND STATUS = 'INVALID') AS QTD_INVALIDOS,
       (SELECT COUNT(*)
          FROM ALL_OBJECTS
         WHERE OWNER = SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
           AND OBJECT_NAME = 'RMD_CONTROLE_OBJETOS') AS QTD_CONTROLE_REVISAO
  FROM DUAL;
