-- Pos-validacao da retomada isolada da atividade 03; somente leitura.
SELECT 'BKP_RMD_02_TGFEMP' AS OBJETO,
       COUNT(*) AS QTD_REGISTROS_BACKUP,
       COUNT(DISTINCT ID_EXECUCAO) AS QTD_EXECUCOES
  FROM BKP_RMD_02_TGFEMP
 WHERE ID_EXECUCAO LIKE 'RMD_DANF_%';

SELECT 'TGFEMP_FORA_CODEMP_1' AS OBJETO,
       COUNT(*) AS QTD_REGISTROS_ALVO
  FROM TGFEMP
 WHERE CODEMP<>1;
