-- Pos-validacao da retomada isolada da atividade 12; somente leitura.
SELECT 'BKP_RMD_11_TGFEMP' AS OBJETO,
       COUNT(*) AS QTD_REGISTROS_BACKUP,
       COUNT(DISTINCT ID_EXECUCAO) AS QTD_EXECUCOES
  FROM BKP_RMD_11_TGFEMP
 WHERE ID_EXECUCAO LIKE 'RMD_RUPE_%';

SELECT 'TGFEMP_RUPTURA_S' AS OBJETO,
       COUNT(*) AS QTD_REGISTROS
  FROM TGFEMP
 WHERE RUPTURAEST='S';
