-- Pos-validacao da retomada isolada da atividade 13; somente leitura.
SELECT 'BKP_RMD_12_TGFTOP' AS OBJETO,
       COUNT(*) AS QTD_REGISTROS_BACKUP,
       COUNT(DISTINCT ID_EXECUCAO) AS QTD_EXECUCOES
  FROM BKP_RMD_12_TGFTOP
 WHERE ID_EXECUCAO LIKE 'RMD_TOPG_%';

SELECT 'TGFTOP_TOTAL' AS OBJETO,
       COUNT(*) AS QTD_REGISTROS
  FROM TGFTOP;
