-- Pos-validacao das atividades 14 e 15; somente leitura.
SELECT 'BKP_RMD_13_TSIIMP' AS OBJETO,
       COUNT(*) AS QTD_REGISTROS_BACKUP,
       COUNT(DISTINCT ID_EXECUCAO) AS QTD_EXECUCOES
  FROM BKP_RMD_13_TSIIMP;

SELECT 'BKP_RMD_14_TGFPRO' AS OBJETO,
       COUNT(*) AS QTD_REGISTROS_BACKUP,
       COUNT(DISTINCT ID_EXECUCAO) AS QTD_EXECUCOES
  FROM BKP_RMD_14_TGFPRO;

SELECT 'TSIIMP_CODREL_848' AS OBJETO,
       COUNT(*) AS QTD_REGISTROS
  FROM TSIIMP
 WHERE CODREL=848;
