-- Estado da atividade 14 apos rollback por divergencia; somente leitura.
SELECT 'BKP_RMD_13_TSIIMP' AS OBJETO,
       COUNT(*) AS QTD_REGISTROS_BACKUP,
       COUNT(DISTINCT ID_EXECUCAO) AS QTD_EXECUCOES
  FROM BKP_RMD_13_TSIIMP;

SELECT 'TSIIMP_CODREL_848' AS OBJETO,
       COUNT(*) AS QTD_REGISTROS,
       MIN(DBMS_LOB.GETLENGTH(LISTA1)) AS MENOR_TAMANHO_LISTA1,
       MAX(DBMS_LOB.GETLENGTH(LISTA1)) AS MAIOR_TAMANHO_LISTA1
  FROM TSIIMP
 WHERE CODREL=848;
