-- Pos-validacao da atividade 15; somente leitura.
SELECT 'BKP_RMD_14_TGFPRO' AS OBJETO,
       COUNT(*) AS QTD_REGISTROS_BACKUP,
       COUNT(DISTINCT ID_EXECUCAO) AS QTD_EXECUCOES
  FROM BKP_RMD_14_TGFPRO;
