-- Pos-validacao da atividade 16; somente leitura.
SELECT 'BKP_RMD_TSICFG' AS OBJETO,
       COUNT(*) AS QTD_REGISTROS_BACKUP,
       COUNT(DISTINCT ID_EXECUCAO) AS QTD_EXECUCOES
  FROM BKP_RMD_TSICFG;

SELECT 'TSICFG_TOTAL' AS OBJETO,
       COUNT(*) AS QTD_REGISTROS
  FROM TSICFG;
