-- Pos-validacao da atividade 17; somente leitura.
SELECT 'RMD_MAP_UNIDADES' AS OBJETO,
       COUNT(*) AS QTD_REGISTROS
  FROM RMD_MAP_UNIDADES
UNION ALL
SELECT 'BKP_RMD_UNID_MAP',COUNT(*)
  FROM BKP_RMD_UNID_MAP
UNION ALL
SELECT 'BKP_RMD_UNID_TGFVOL',COUNT(*)
  FROM BKP_RMD_UNID_TGFVOL;
