SELECT 'RMD_MAP_UNIDADES' AS OBJETO, 'OBJECT' AS ORIGEM, OBJECT_NAME, OBJECT_TYPE, OWNER, STATUS
FROM ALL_OBJECTS
WHERE OWNER = 'SANKHYA'
  AND OBJECT_NAME IN ('RMD_MAP_UNIDADES', 'BKP_RMD_UNID_MAP')
UNION ALL
SELECT 'RMD_MAP_UNIDADES' AS OBJETO, 'PRIVILEGE' AS ORIGEM, TABLE_NAME, PRIVILEGE, GRANTEE, GRANTOR
FROM ALL_TAB_PRIVS
WHERE TABLE_NAME IN ('RMD_MAP_UNIDADES', 'BKP_RMD_UNID_MAP')
UNION ALL
SELECT 'TSIIMP' AS OBJETO, 'PRIVILEGE' AS ORIGEM, TABLE_NAME, PRIVILEGE, GRANTEE, GRANTOR
FROM ALL_TAB_PRIVS
WHERE TABLE_NAME IN ('TSIIMP', 'BKP_RMD_13_TSIIMP')
ORDER BY 1, 2, 3, 4, 5, 6
