SELECT OBJECT_NAME, OBJECT_TYPE, STATUS, CREATED, LAST_DDL_TIME
FROM ALL_OBJECTS
WHERE OWNER = 'SANKHYA'
  AND (OBJECT_NAME = 'RMD_MAP_UNIDADES'
       OR OBJECT_NAME LIKE 'BKP_RMD_UNID_%')
ORDER BY OBJECT_NAME
