SELECT OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE
FROM ALL_TAB_COLUMNS
WHERE OWNER='SANKHYA'
  AND ((TABLE_NAME='TSIIMP' AND COLUMN_NAME IN ('CODREL','LISTA1'))
       OR (TABLE_NAME='BKP_RMD_13_TSIIMP' AND COLUMN_NAME IN ('ID_EXECUCAO','DH_EXECUCAO','USUARIO_EXECUCAO','CODREL','LISTA1_ANTES')))
ORDER BY TABLE_NAME, COLUMN_ID
