SELECT 'BAI_GRUPOS_DUPLICADOS_EXATOS' AS INDICADOR, COUNT(*) AS QUANTIDADE
  FROM (
    SELECT UPPER(TRIM(NOMEBAI)) N
      FROM TSIBAI
     GROUP BY UPPER(TRIM(NOMEBAI))
    HAVING COUNT(*)>1
  )
UNION ALL
SELECT 'END_GRUPOS_DUPLICADOS_EXATOS', COUNT(*)
  FROM (
    SELECT TIPO, UPPER(TRIM(NOMEEND)) N
      FROM TSIEND
     GROUP BY TIPO, UPPER(TRIM(NOMEEND))
    HAVING COUNT(*)>1
  )
UNION ALL
SELECT 'BAI_NAO_NORMALIZADOS', COUNT(*)
  FROM TSIBAI
 WHERE NOMEBAI<>UPPER(TRIM(NOMEBAI))
UNION ALL
SELECT 'END_NAO_NORMALIZADOS', COUNT(*)
  FROM TSIEND
 WHERE NOMEEND<>UPPER(TRIM(NOMEEND))
