SELECT 'BASE_TOTAL' AS INDICADOR, COUNT(*) AS QUANTIDADE
  FROM BKP_RMD_JCLM_FDUP_20260919
UNION ALL
SELECT 'CLASSIFICACAO_'||STATUS_MAPA, COUNT(*)
  FROM BKP_RMD_JCLM_FDUP_20260919_PPG
 GROUP BY STATUS_MAPA
UNION ALL
SELECT 'TGFFIN_NUNOTA_MAPA', COUNT(DISTINCT B.NUNOTA)
  FROM BKP_RMD_JCLM_FDUP_20260919 B
 WHERE EXISTS (SELECT 1 FROM TGFFIN F WHERE F.NUNOTA=B.NUNOTA)
ORDER BY 1
