SELECT 'RMD_CONTROLE_OBJETOS' AS INDICADOR, COUNT(*) AS VALOR, 'auditoria de objetos' AS DETALHE
  FROM RMD_CONTROLE_OBJETOS
UNION ALL
SELECT 'RMD_MAP_UNIDADES', COUNT(*), 'mapa persistente atividade 17'
  FROM RMD_MAP_UNIDADES
UNION ALL
SELECT 'BKP_RMD_UNID_MAP', COUNT(*), 'backup persistente atividade 17'
  FROM BKP_RMD_UNID_MAP
UNION ALL
SELECT 'BKP_RMD_13_TSIIMP', COUNT(*), 'backup configuração 848'
  FROM BKP_RMD_13_TSIIMP
UNION ALL
SELECT 'TSIIMP_CODREL_848', COUNT(*), 'configuração 848 atual'
  FROM TSIIMP WHERE CODREL=848
UNION ALL
SELECT 'OBJETOS_INVALIDOS', COUNT(*), 'atividade 31 sem privilegio de recompilacao'
  FROM ALL_OBJECTS
 WHERE OWNER='SANKHYA' AND STATUS='INVALID'
UNION ALL
SELECT 'TRIGGERS_TGFITE_HABILITADOS', COUNT(*), 'estado final dos gatilhos'
  FROM ALL_TRIGGERS
 WHERE OWNER='SANKHYA'
   AND TRIGGER_NAME IN ('TRG_INC_UPD_TGFITE','TRG_UPT_TGFITE')
   AND STATUS='ENABLED'
UNION ALL
SELECT 'BKP_RMD_GOL_TSIPAR', COUNT(*), 'backup atividade 18'
  FROM BKP_RMD_GOL_TSIPAR
UNION ALL
SELECT 'BKP_RMD_PAR_MATRIZ', COUNT(*), 'backup atividade 19'
  FROM BKP_RMD_PAR_MATRIZ
UNION ALL
SELECT 'BKP_RMD_CARD_TTKINDAGT', COUNT(*), 'backup atividade 20'
  FROM BKP_RMD_CARD_TTKINDAGT
UNION ALL
SELECT 'BKP_CLASSICMS_TGFPAR', COUNT(*), 'backup atividade 21'
  FROM BKP_CLASSICMS_TGFPAR
UNION ALL
SELECT 'BKP_AJNP_TGFPAR', COUNT(*), 'backup atividade 22'
  FROM BKP_AJNP_TGFPAR
UNION ALL
SELECT 'BKP_RMD_PAD_TGFPAR', COUNT(*), 'backup atividade 24'
  FROM BKP_RMD_PAD_TGFPAR
UNION ALL
SELECT 'BKP_RMD_PAD_TGFPRO', COUNT(*), 'backup atividade 25'
  FROM BKP_RMD_PAD_TGFPRO
UNION ALL
SELECT 'BKP_RMD_PAD_TSIBAI', COUNT(*), 'backup atividade 29'
  FROM BKP_RMD_PAD_TSIBAI
UNION ALL
SELECT 'BKP_RMD_PAD_TSIEND', COUNT(*), 'backup atividade 30'
  FROM BKP_RMD_PAD_TSIEND
UNION ALL
SELECT 'CARD09_BASE', COUNT(*), 'mapa direto XML'
  FROM BKP_RMD_JCLM_FDUP_20260919
UNION ALL
SELECT 'CARD09_APTOS', COUNT(*), 'candidatos aptos para validação final'
  FROM BKP_RMD_JCLM_FDUP_20260919_PPG
 WHERE STATUS_MAPA='APTO_PARA_VALIDACAO_FINAL'
UNION ALL
SELECT 'CARD09_SEM_VDUP_XML', COUNT(*), 'pendências preservadas no mapa'
  FROM BKP_RMD_JCLM_FDUP_20260919_PPG
 WHERE STATUS_MAPA='SEM_VDUP_XML'
ORDER BY 1
