SELECT OWNER, TABLE_NAME, COLUMN_ID, COLUMN_NAME, DATA_TYPE
  FROM ALL_TAB_COLUMNS
 WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
   AND TABLE_NAME IN (
       'TSIBAI',
       'TSIEND',
       'RMD_JCLM_MRG_20260919_BAI',
       'RMD_JCLM_MRG_20260919_END',
       'RMD_JCLM_MRG_20260919_DEP'
   )
 ORDER BY TABLE_NAME, COLUMN_ID
