SELECT USER AS SESSION_USER,
       SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA') AS CURRENT_SCHEMA,
       SYS_CONTEXT('USERENV', 'SERVICE_NAME') AS SERVICE_NAME,
       E.CODEMP,
       E.RAZAOSOCIAL,
       E.CGC,
       E.INSCESTAD,
       E.CODCID,
       C.NOMECID,
       C.UF
  FROM TSIEMP E
  LEFT JOIN TSICID C ON C.CODCID = E.CODCID
 ORDER BY E.CODEMP
