SELECT 'EMPRESA' AS ORIGEM,
       TO_CHAR(CODEMP) AS IDENTIFICADOR,
       SERVIDORSMTP AS SERVIDOR_PORTA,
       TIPOSMTP AS CRIPTOGRAFIA,
       CASE WHEN USUARIOSMTP IS NULL THEN 'AUSENTE' ELSE 'PRESENTE_NAO_EXIBIDO' END AS REMETENTE,
       CASE WHEN SENHASMTP IS NULL THEN 'AUSENTE' ELSE 'PRESENTE_NAO_EXIBIDA' END AS STATUS_CREDENCIAL
  FROM TSIEMP
 ORDER BY 1, 2
