SELECT CHAVE,
       REGEXP_SUBSTR(TEXTO, '[^'||CHR(59)||']+', 1, 1) AS SERVIDOR_PORTA,
       REGEXP_SUBSTR(TEXTO, '[^'||CHR(59)||']+', 1, 2) AS CRIPTOGRAFIA,
       REGEXP_SUBSTR(TEXTO, '[^'||CHR(59)||']+', 1, 3) AS REMETENTE,
       CASE
         WHEN TEXTO IS NULL THEN 'AUSENTE'
         WHEN INSTR(TEXTO, CHR(59), 1, 3) > 0 THEN 'CREDENCIAL_PRESENTE_NAO_EXIBIDA'
         ELSE 'FORMATO_INCOMPLETO'
       END AS STATUS_CREDENCIAL
  FROM TSIPAR
 WHERE CHAVE = 'MSDSMTPPROP'
