SELECT 'TSICTA_CONTAS_BANCARIAS' AS OBJETO, COUNT(*) AS QUANTIDADE FROM TSICTA
UNION ALL
SELECT 'TSIUSU_USUARIOS', COUNT(*) FROM TSIUSU
UNION ALL
SELECT 'TGFVEN_VENDEDORES_COMPRADORES', COUNT(*) FROM TGFVEN
UNION ALL
SELECT 'TGFGRU_GRUPOS_PRODUTO', COUNT(*) FROM TGFGRU
UNION ALL
SELECT 'TSICUS_CENTROS_RESULTADO', COUNT(*) FROM TSICUS
UNION ALL
SELECT 'TGFNAT_NATUREZAS', COUNT(*) FROM TGFNAT
UNION ALL
SELECT 'TGFLOC_LOCAIS_ESTOQUE', COUNT(*) FROM TGFLOC
UNION ALL
SELECT 'TGFPRO_PRODUTOS', COUNT(*) FROM TGFPRO
ORDER BY 1
