SELECT E.CODEMP,
       E.CGC,
       E.RAZAOSOCIAL,
       COUNT(A.CODCTABCOINT) AS CONTAS_BANCARIAS,
       SUM(CASE WHEN A.EMITEBOLETA = 'S' THEN 1 ELSE 0 END) AS CONTAS_EMITEM_BOLETO,
       SUM(CASE WHEN A.ATIVA = 'S' THEN 1 ELSE 0 END) AS CONTAS_ATIVAS
  FROM TSIEMP E
  LEFT JOIN TSICTA A ON A.CODEMP = E.CODEMP
 GROUP BY E.CODEMP, E.CGC, E.RAZAOSOCIAL
 ORDER BY E.CODEMP
