WITH FONTES (FONTE, CNPJ, NOME_ESPERADO) AS (
    SELECT 'RESUMO_01_DADOS_DA_EMPRESA', '33649134000197', 'JCLM INDUSTRIA E COMERCIO LTDA' FROM DUAL
    UNION ALL SELECT 'RESUMO_01_DADOS_DA_EMPRESA', '33649134000278', 'JCLM INDUSTRIA E COMERCIO LTDA' FROM DUAL
    UNION ALL SELECT 'RESUMO_01_DADOS_DA_EMPRESA', '33649134000359', 'JCLM INDUSTRIA E COMERCIO LTDA' FROM DUAL
    UNION ALL SELECT 'DADOS_INICIAIS', '33649134000278', 'JCLM INDUSTRIA E COMERCIO LTDA' FROM DUAL
    UNION ALL SELECT 'DADOS_INICIAIS', '37008355000137', 'FUTURA PRODUTOS ALIMENTICIOS LTDA' FROM DUAL
    UNION ALL SELECT 'DADOS_INICIAIS', '07056520000165', 'INDUSTRIA DE SUCOS SUMO INDUSTRIAL LTDA EM RECUPERACAO JUDICIAL' FROM DUAL
)
SELECT F.FONTE,
       F.CNPJ,
       F.NOME_ESPERADO,
       E.CODEMP,
       E.RAZAOSOCIAL AS NOME_ORACLE,
       E.INSCESTAD,
       C.UF,
       CASE WHEN E.CODEMP IS NULL THEN 'AUSENTE_NO_ORACLE' ELSE 'LOCALIZADO_NO_ORACLE' END AS CLASSIFICACAO
  FROM FONTES F
  LEFT JOIN TSIEMP E ON REPLACE(REPLACE(REPLACE(E.CGC, '.', ''), '/', ''), '-', '') = F.CNPJ
  LEFT JOIN TSICID C ON C.CODCID = E.CODCID
 ORDER BY F.FONTE, F.CNPJ
