SELECT CASE WHEN CODGRUPO > 0 THEN 'COM_GRUPO' ELSE 'MODELO_SEM_GRUPO' END AS CLASSIFICACAO,
       COUNT(*) AS QUANTIDADE
  FROM TSIUSU
 GROUP BY CASE WHEN CODGRUPO > 0 THEN 'COM_GRUPO' ELSE 'MODELO_SEM_GRUPO' END
 ORDER BY 1
