SELECT CODUSU,
       NOMEUSU,
       LOWER(TRIM(EMAIL)) AS EMAIL,
       CODGRUPO,
       CODEMP,
       CODVEND,
       CASE WHEN CODGRUPO > 0 THEN 'COM_GRUPO' ELSE 'SEM_GRUPO_MODELO' END AS CLASSIFICACAO
  FROM TSIUSU
 WHERE LOWER(TRIM(EMAIL)) IN ('comercial@sumobrasil.com.br', 'controle@sumobrasil.com.br')
 ORDER BY LOWER(TRIM(EMAIL)), CODUSU
