SELECT CAB.TIPMOV,
       TIPMOV_DESC.OPCAO AS DESC_TIPMOV,
       COUNT(*) AS QTD_REGISTROS
  FROM TGFCAB CAB
  LEFT JOIN TDDCAM CAM_TIPMOV
    ON CAM_TIPMOV.NOMETAB = 'TGFCAB'
   AND CAM_TIPMOV.NOMECAMPO = 'TIPMOV'
  LEFT JOIN TDDOPC TIPMOV_DESC
    ON TIPMOV_DESC.NUCAMPO = CAM_TIPMOV.NUCAMPO
   AND TIPMOV_DESC.VALOR = CAB.TIPMOV
 WHERE CAB.NUNOTA IN (
           SELECT DISTINCT C.NUNOTA
             FROM TGFCAB C
             INNER JOIN TGFTOP T
               ON C.CODTIPOPER = T.CODTIPOPER
              AND C.DHTIPOPER = T.DHALTER
            WHERE T.ATUALFIN <> 0
              AND C.TIPMOV <> 'Z'
              AND NOT EXISTS (
                    SELECT 1
                      FROM TGFFIN F
                     WHERE F.NUNOTA = C.NUNOTA
              )
       )
 GROUP BY CAB.TIPMOV, TIPMOV_DESC.OPCAO
 ORDER BY QTD_REGISTROS DESC;
