SELECT COUNT(DISTINCT P.CODPROD) AS QTD_REGISTROS
  FROM TGFITE I
  JOIN TGFCAB C ON C.NUNOTA = I.NUNOTA
  JOIN TGFPRO P ON P.CODPROD = I.CODPROD
 WHERE C.TIPMOV = 'V'
   AND NOT EXISTS (
         SELECT 1
           FROM TGFEXC E
          WHERE E.CODPROD = P.CODPROD
       );
