WITH PROD_HASH AS (
  SELECT CODPROD,
         DESCRPROD,
         ORA_HASH(UPPER(REGEXP_REPLACE(DESCRPROD, '[^A-Z0-9 ]', '')), 999999) AS HASH_DESCR,
         UPPER(REGEXP_REPLACE(DESCRPROD, '[^A-Z0-9 ]', '')) AS DESCRNORM
    FROM TGFPRO
)
SELECT COUNT(*) AS QTD_REGISTROS
  FROM PROD_HASH A
  JOIN PROD_HASH B
    ON A.HASH_DESCR = B.HASH_DESCR
   AND A.CODPROD < B.CODPROD
 WHERE UTL_MATCH.JARO_WINKLER_SIMILARITY(A.DESCRNORM, B.DESCRNORM) > 85;
