SELECT COUNT(*) AS QTD_REGISTROS
  FROM TGFPAR P
 WHERE SUBSTR(P.CGC_CPF, 9, 4) = '0001'
   AND LENGTH(P.CGC_CPF) = 14
   AND SUBSTR(P.CGC_CPF, 1, 8) <> '00000000'
   AND EXISTS (
         SELECT 1
           FROM TGFPAR F
          WHERE SUBSTR(F.CGC_CPF, 1, 8) = SUBSTR(P.CGC_CPF, 1, 8)
            AND SUBSTR(F.CGC_CPF, 9, 4) <> '0001'
            AND LENGTH(F.CGC_CPF) = 14
       );
