SELECT COUNT(DISTINCT I.CODPROD) AS QTD_REGISTROS
  FROM TGFITE I
  JOIN TGFCAB C ON C.NUNOTA = I.NUNOTA
 WHERE C.TIPMOV = 'C'
   AND NOT EXISTS (
         SELECT 1
           FROM TGFITE IC
           JOIN TGFCAB CC
             ON CC.NUNOTA = IC.NUNOTA
            AND CC.TIPMOV = 'V'
          WHERE IC.CODPROD = I.CODPROD
       );
