-- Card 09 - inclusao controlada de financeiros derivados de <Dup>.
-- Este executor permanece inofensivo com CONFIRMA_INSERCAO=NAO.
-- A alteracao de TGFFIN/TGFNUM somente ocorre com confirmacao explicita.
-- O mapa desta base usa ID_EXECUCAO_MAPA e status APTO_PARA_INSERCAO_CONTROLADA.

SET DEFINE ON
SET SERVEROUTPUT ON SIZE UNLIMITED
SET SQLBLANKLINES ON
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

DEFINE ID_EXECUCAO = 'RMD_FDUP_IMS_20260914165524'
DEFINE TBL_PPG = 'BKP_RMD_IMS_DUP_PPG_20260914'
DEFINE TBL_INS = 'BKP_RMD_IMS_DUP_INS_20260914'
DEFINE CONFIRMA_INSERCAO = 'NAO'

PROMPT === CARD 09 - INSERT CONTROLADO TGFFIN - INSTITUTO MOREIRA SALLES ===

DECLARE
  v_qtd NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_qtd
    FROM ALL_TABLES
   WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
     AND TABLE_NAME='&TBL_INS';
  IF v_qtd=0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE &TBL_INS (
        ID_EXECUCAO VARCHAR2(40) NOT NULL,
        DH_EXECUCAO TIMESTAMP NOT NULL,
        NUNOTA NUMBER NOT NULL,
        NUFIN NUMBER NOT NULL,
        VLRDESDOB NUMBER,
        DTVENC DATE,
        CODCTABCOINT NUMBER,
        CODTIPTIT NUMBER,
        NDUP_XML VARCHAR2(4000)
      )]';
    DBMS_OUTPUT.PUT_LINE('AUDITORIA_CRIADA=&TBL_INS');
  ELSE
    DBMS_OUTPUT.PUT_LINE('AUDITORIA_EXISTENTE=&TBL_INS');
  END IF;
END;
/

DECLARE
  v_confirm VARCHAR2(3) := UPPER('&&CONFIRMA_INSERCAO');
  v_qtd NUMBER;
  v_distinct NUMBER;
  v_existentes NUMBER;
  v_pendentes NUMBER;
  v_tgfnum_rows NUMBER;
  v_ultcod TGFNUM.ULTCOD%TYPE;
  v_nufin TGFFIN.NUFIN%TYPE;
  v_vldup TGFFIN.VLRDESDOB%TYPE;
  v_dvenc TGFFIN.DTVENC%TYPE;
  v_inseridos NUMBER := 0;
BEGIN
  SELECT COUNT(*), COUNT(DISTINCT NUNOTA)
    INTO v_qtd, v_distinct
    FROM &TBL_PPG
   WHERE ID_EXECUCAO_MAPA='&ID_EXECUCAO'
     AND STATUS_MAPA='APTO_PARA_INSERCAO_CONTROLADA';
  DBMS_OUTPUT.PUT_LINE('LINHAS_APTAS='||v_qtd||'; NOTAS_APTAS='||v_distinct);
  IF v_qtd <> 24 OR v_distinct <> 24 THEN
    RAISE_APPLICATION_ERROR(-20324,
      'Quantidade apta divergente: esperado 24 linhas e 24 notas.');
  END IF;

  SELECT COUNT(*) INTO v_qtd
    FROM &TBL_PPG M
   WHERE M.ID_EXECUCAO_MAPA='&ID_EXECUCAO'
     AND M.STATUS_MAPA='APTO_PARA_INSERCAO_CONTROLADA'
     AND (M.VDUP_XML IS NULL
       OR NOT REGEXP_LIKE(TRIM(M.VDUP_XML),'^[0-9]+([.][0-9]+)?$')
       OR M.DVENC_XML IS NULL
       OR NOT REGEXP_LIKE(TRIM(M.DVENC_XML),'^[0-9]{4}-[0-9]{2}-[0-9]{2}$')
       OR M.CODTIPTITPAD IS NULL
       OR NOT EXISTS (SELECT 1 FROM TGFTIT T WHERE T.CODTIPTIT=M.CODTIPTITPAD)
       OR M.QTD_TGFTPV_EXATA <> 1
       OR M.CODCTABCOINT_RESOLVIDO IS NULL
       OR M.QTD_TGFNUM_TGFFIN <> 1
       OR M.QTD_TGFFIN_ATUAL <> 0
       OR M.QTD_LINHAS_APTAS_NUNOTA <> 1
       OR M.RECDESP_RESOLVIDO=0);
  IF v_qtd > 0 THEN
    RAISE_APPLICATION_ERROR(-20325,
      'Uma ou mais linhas aptas falharam na validacao consolidada.');
  END IF;

  SELECT COUNT(DISTINCT F.NUNOTA) INTO v_existentes
    FROM TGFFIN F
    JOIN &TBL_PPG M
      ON M.NUNOTA=F.NUNOTA
     AND M.ID_EXECUCAO_MAPA='&ID_EXECUCAO'
     AND M.STATUS_MAPA='APTO_PARA_INSERCAO_CONTROLADA';
  SELECT COUNT(*) INTO v_pendentes
    FROM &TBL_PPG M
   WHERE M.ID_EXECUCAO_MAPA='&ID_EXECUCAO'
     AND M.STATUS_MAPA='APTO_PARA_INSERCAO_CONTROLADA'
     AND NOT EXISTS (SELECT 1 FROM TGFFIN F WHERE F.NUNOTA=M.NUNOTA);
  DBMS_OUTPUT.PUT_LINE('JA_EXISTIAM_TGFFIN='||v_existentes);
  DBMS_OUTPUT.PUT_LINE('PENDENTES_PARA_INSERCAO='||v_pendentes);
  IF v_pendentes = 0 THEN
    DBMS_OUTPUT.PUT_LINE('STATUS=SEM_PENDENTES_PARA_INSERCAO');
    RETURN;
  END IF;

  SELECT COUNT(*) INTO v_qtd
    FROM &TBL_PPG M
   WHERE M.ID_EXECUCAO_MAPA='&ID_EXECUCAO'
     AND M.STATUS_MAPA='APTO_PARA_INSERCAO_CONTROLADA'
     AND NOT EXISTS (
       SELECT 1 FROM TGFTPV V
        WHERE V.CODTIPVENDA=M.CODTIPVENDA
          AND V.DHALTER=M.DHTIPVENDA);
  IF v_qtd > 0 THEN
    RAISE_APPLICATION_ERROR(-20329,
      'Uma ou mais notas nao possuem a versao exata da TGFTPV usada no cabecalho.');
  END IF;

  SELECT COUNT(*) INTO v_tgfnum_rows
    FROM TGFNUM WHERE ARQUIVO='TGFFIN';
  DBMS_OUTPUT.PUT_LINE('TGFNUM_TGFFIN_ROWS='||v_tgfnum_rows);
  IF v_tgfnum_rows <> 1 THEN
    FOR t IN (SELECT ARQUIVO, ULTCOD FROM TGFNUM
               WHERE ARQUIVO='TGFFIN' ORDER BY ULTCOD) LOOP
      DBMS_OUTPUT.PUT_LINE('TGFNUM_ROW ARQUIVO='||t.ARQUIVO||' ULTCOD='||t.ULTCOD);
    END LOOP;
    RAISE_APPLICATION_ERROR(-20326,
      'TGFNUM deve possuir exatamente uma linha para TGFFIN.');
  END IF;

  IF v_confirm <> 'SIM' THEN
    DBMS_OUTPUT.PUT_LINE(
      'STATUS=NAO_EXECUTADO; confirme explicitamente antes de alterar TGFFIN/TGFNUM.');
    RETURN;
  END IF;

  DBMS_OUTPUT.PUT_LINE('ANTES_LOCK_TGFNUM');
  SELECT ULTCOD INTO v_ultcod
    FROM TGFNUM WHERE ARQUIVO='TGFFIN' FOR UPDATE WAIT 5;
  DBMS_OUTPUT.PUT_LINE('APOS_LOCK_TGFNUM ULTCOD='||v_ultcod);

  SELECT COUNT(*) INTO v_qtd FROM &TBL_INS
   WHERE ID_EXECUCAO='&ID_EXECUCAO';
  IF v_qtd > 0 THEN
    RAISE_APPLICATION_ERROR(-20327,
      'Ja existem inclusoes auditadas para este ID_EXECUCAO.');
  END IF;

  FOR r IN (
    SELECT M.*
      FROM &TBL_PPG M
     WHERE M.ID_EXECUCAO_MAPA='&ID_EXECUCAO'
       AND M.STATUS_MAPA='APTO_PARA_INSERCAO_CONTROLADA'
       AND NOT EXISTS (SELECT 1 FROM TGFFIN F WHERE F.NUNOTA=M.NUNOTA)
     ORDER BY M.NUNOTA, M.SEQ_PPG
  ) LOOP
    v_nufin := v_ultcod + 1;
    DBMS_OUTPUT.PUT_LINE('PROCESSANDO NUNOTA='||r.NUNOTA||
      ' NUFIN='||v_nufin||' VDUP='||r.VDUP_XML||
      ' DVENC='||r.DVENC_XML||' NDUP='||NVL(r.NDUP_XML,'<NULL>'));
    BEGIN
      v_vldup := TO_NUMBER(TRIM(r.VDUP_XML),
                           '999999999999999999D99999999',
                           'NLS_NUMERIC_CHARACTERS=''.,''');
      v_dvenc := TO_DATE(TRIM(r.DVENC_XML),'YYYY-MM-DD');

      INSERT INTO TGFFIN ( ABATIMENTO,ABATIMENTOCAN,AGENCIA_CMC7,ALIQICMS,AUTORIZADO,BAIXAAPI,BASEICMS,BASEINSS,BASEIRF,BLOQVAR,CARTA,CARTAODESC,CGC_CPF_CMC7,CHAVECTE,CHAVECTEREF,CHAVENFEGNRE,CHEQUERASTREADO_CMC7,CLASSIFCESSAOOBRA,CODBARRA,CODBCO,CODBCO_CMC7,CODCBE,CODCC,CODCENCUS,CODCFO,CODCIDFIMCTE,CODCIDINICTE,CODCONTATO,CODCTABCOINT,CODEMP,CODEMPBAIXA,CODFUNC,CODIGOBARRA,CODIMOVELRURAL,CODIPTU,CODLST,CODMOEDA,CODNAT,CODOBRA,CODOBSPADRAO,CODPARC,CODPROJ,CODRECEITA,CODREGUA,CODTIPOPER,CODTIPOPERBAIXA,CODTIPTIT,CODTRIB,CODUSU,CODUSUBAIXA,CODUSUCOBR,CODVEICULO,CODVEND,CONTA_CMC7,CUSTASPROCESSUAIS,DEPOSITOJUDICIAL,DESCRTPAGNFCE,DESDOBDUPL,DESDOBRAMENTO,DESPADVOGADO,DESPCART,DHBAIXA,DHMOV,DHTIPOPER,DHTIPOPERBAIXA,DH_IMPRESSAO,DIGSAFRA,DTALTER,DTBAIXAPREV,DTCONTAB,DTCONTABBAIXA,DTENTSAI,DTENTSAIINFO,DTINITREFAPURACAO,DTINTEGRACAOIPI,DTNEG,DTPRAZO,DTREFERENCIA,DTVENC,DTVENCINIC,EMVPIX,EXIGEISSQN,HISTORICO,IDLOTEFDIC,IDUNICO,INDRECEFDCONT,INFCOMPLEFDCONT,INSSRETIDO,IRFRETIDO,ISSRETIDO,JUROSAVP,LINHADIGITAVEL,M2,METODOCALCIRRF,MODELONFDES,MONIOCOREM,MOTNAORETERISSQN,NATUREZAOPERDES,NFCOMPLFIX,NFENTSEQFIX,NOMEEMITENTE_CMC7,NOSSONUM,NROIMPORT,NROLOTEGNRE,NUANTBANC,NUAPONTA,NUBCO,NUCAIXA,NUCCR,NUCHQ,NUCKC,NUCOMPENS,NUDEV,NUFIN,NUFTC,NUMBOR,NUMCONTRATO,NUMDOCARRECAD,NUMDUPL,NUMNFSE,NUMNOTA,NUMOCORRENCIAS,NUMOS,NUMPROCADMJUDIC,NUMREMESSA,NUNOTA,NUPED,NURENEG,NUVERBA,OBRACONSTCIVIL,ORDEMCARGA,ORIGEM,PARCRENEG,PDD,PIXTEF,PROVISAO,RATEADO,RECADIANTAMENTORURAL,RECDESP,RECEBCARTAO,RECEBIDO,REFATCON,REGESPTRIBUT,REJEICAOGNRE,SANGDESPDV,SEQCAIXA,SEQUENCIA,SERIENFDES,SERIENOTA,SITESPECIALRESP,STATUSGNRE,TIMBLOQUEADA,TIMCONTALANC,TIMCONTAREP,TIMCONTRATOADM,TIMCONTRATOLOC,TIMCONTRATOLTV,TIMDATADEJUR,TIMDHBAIXA,TIMDHGERREPASSE,TIMDHGERREPPARCIAL,TIMDTIMPBOL,TIMDTIMPBOLLOCAL,TIMDTREPASSE,TIMDTREPPARCIAL,TIMFECHAMENTO,TIMFECHAMENTOALU,TIMFINGARANTORIG,TIMIMOVEL,TIMNEGOCIACAO,TIMNOMEADVOGADO,TIMNUFINORIG,TIMNUMREG,TIMORIGEM,TIMORIGRENEG,TIMPARCELA,TIMRENEGCANCLOTE,TIMRENEGIMV,TIMRENEGLOTE,TIMREPINTELIGENTE,TIMREPPARCIAL,TIMRESCISAOLOC,TIMRESCISAOLTV,TIMSAC,TIMTIPOINTERMED,TIMTXADMGERALU,TIMVENDAIMV,TIMVENDALOTE,TIMVLRAMORTCONTRATO,TIMVLRCORRMONET,TIMVLRJUROCONTRATO,TIPAPURACAO,TIPJURO,TIPMARCCHEQ,TIPMULTA,TPAGNFCE,TROCOPDV,VALORPRESENTE,VENDAMAIS,VLRALIBERAR,VLRBAIXA,VLRCESSAO,VLRCHEQUE,VLRDESC,VLRDESCCALC,VLRDESCEMBUT,VLRDESDOB,VLRDESDOBCALC,VLRFATCARTAO,VLRGNREDOIS,VLRICMSXMLCTE,VLRINSS,VLRIRF,VLRISS,VLRJURO,VLRJUROEMBUT,VLRJUROLIB,VLRJURONEGOC,VLRMOEDA,VLRMOEDABAIXA,VLRMULTA,VLRMULTAEMBUT,VLRMULTALIB,VLRMULTANEGOC,VLRPROV,VLRVARCAMBIAL,VLRVENDOR ) VALUES (
      NULL,
      NULL,
      NULL,
      0,
      'N',
      NULL,
      0,
      NULL,
      NULL,
      'N',
      NULL,
      0,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      r.CODBCO_RESOLVIDO,
      NULL,
      NULL,
      NULL,
      r.CODCENCUS_RESOLVIDO,
      NULL,
      NULL,
      NULL,
      NULL,
      r.CODCTABCOINT_RESOLVIDO,
      r.CODEMP,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      0,
      r.CODNAT_RESOLVIDO,
      NULL,
      NULL,
      r.CODPARC,
      r.CODPROJ_RESOLVIDO,
      NULL,
      NULL,
      r.CODTIPOPER,
      0,
      r.CODTIPTITPAD,
      NULL,
      0,
      NULL,
      NULL,
      0,
      r.CODVEND,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      0,
      NULL,
      0,
      NULL,
      NVL(r.DTMOV,r.DTNEG),
      r.DHTIPOPER,
      TO_DATE('1998-01-01','YYYY-MM-DD'),
      NULL,
      NULL,
      SYSDATE,
      NULL,
      NULL,
      NULL,
      r.DTENTSAI,
      NULL,
      NULL,
      NULL,
      TRUNC(r.DTNEG),
      NULL,
      NULL,
      v_dvenc,
      v_dvenc,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      'N',
      'N',
      'N',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      v_nufin,
      NULL,
      NULL,
      0,
      NULL,
      r.NDUP_XML,
      NULL,
      r.NUMNOTA,
      NULL,
      NULL,
      NULL,
      NULL,
      r.NUNOTA,
      NULL,
      NULL,
      NULL,
      NULL,
      0,
      'E',
      NULL,
      NULL,
      NULL,
      'N',
      'N',
      NULL,
      r.RECDESP_RESOLVIDO,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NVL(r.SEQ_PPG,1),
      NULL,
      r.SERIENOTA,
      NULL,
      NULL,
      'N',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      'S',
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      r.TIPJURO_RESOLVIDO,
      'I',
      1,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      0,
      NULL,
      NULL,
      0,
      NULL,
      0,
      v_vldup,
      NULL,
      NULL,
      NULL,
      NULL,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      NULL,
      0.00
    );
    EXCEPTION
      WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERRO_NUNOTA='||r.NUNOTA||' NUFIN='||v_nufin);
        DBMS_OUTPUT.PUT_LINE(SQLERRM);
        DBMS_OUTPUT.PUT_LINE(DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
        RAISE;
    END;

    UPDATE TGFNUM SET ULTCOD=v_nufin WHERE ARQUIVO='TGFFIN';
    INSERT INTO &TBL_INS
      (ID_EXECUCAO,DH_EXECUCAO,NUNOTA,NUFIN,VLRDESDOB,DTVENC,CODCTABCOINT,CODTIPTIT,NDUP_XML)
    VALUES
      ('&ID_EXECUCAO',SYSTIMESTAMP,r.NUNOTA,v_nufin,v_vldup,v_dvenc,
       r.CODCTABCOINT_RESOLVIDO,r.CODTIPTITPAD,r.NDUP_XML);
    v_ultcod := v_nufin;
    v_inseridos := v_inseridos + 1;
  END LOOP;

  IF v_inseridos <> 24 THEN
    RAISE_APPLICATION_ERROR(-20333,
      'Quantidade inserida divergente: esperado 24.');
  END IF;
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('FINANCEIROS_INSERIDOS='||v_inseridos);
  DBMS_OUTPUT.PUT_LINE('STATUS=INSERT_EXECUTADO');
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END;
/

PROMPT === POS-VALIDACAO IMEDIATA ===
SELECT COUNT(*) AS TGFFIN_CRIADOS
  FROM &TBL_INS WHERE ID_EXECUCAO='&ID_EXECUCAO';
