-- Etapa 32A - Mapeamento para inclusao controlada de financeiros
--
-- Este arquivo ainda nao insere TGFFIN. Ele materializa, por nota e por
-- registro da TGFPPG, os valores necessarios para a futura inclusao direta.
-- Somente linhas com status APTO podem ser encaminhadas ao INSERT.

SET DEFINE ON

-- Parametros obrigatorios: altere os tres valores declarados antes de executar.
DEFINE ID_EXECUCAO = 'IMPORTUDO_20260910_FDUP_01'
DEFINE TBL_BASE = 'BKP_RMD_FDUP_IMPORTUDO_01'
DEFINE TBL_PPG = 'BKP_RMD_FDUP_IMPORTUDO_01_PPG'
SET SERVEROUTPUT ON SIZE UNLIMITED
SET SQLBLANKLINES ON
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

PROMPT === CARD 09 - MAPA PARA INSERT DIRETO TGFFIN ===

DECLARE
  v_qtd NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_qtd
    FROM ALL_TABLES
   WHERE OWNER = SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
     AND TABLE_NAME = '&TBL_PPG';
  IF v_qtd > 0 THEN
    RAISE_APPLICATION_ERROR(-20322,
      'Mapa &TBL_PPG ja existe. Gere novo ID antes de repetir.');
  END IF;

  NULL;
END;
/

CREATE TABLE &TBL_PPG AS
WITH C AS (
  SELECT B.ID_EXECUCAO, B.DH_EXECUCAO, B.USUARIO_EXECUCAO,
         B.NUNOTA, B.CODEMP, B.NUMNOTA, B.SERIENOTA, B.DTNEG,
         B.CODPARC, B.CODTIPOPER, B.DESCROPER,
         C.CODTIPVENDA, C.DHTIPOPER, C.DTENTSAI, C.DTMOV,
         C.CODVEND, C.CODNAT AS CODNAT_CAB,
         C.CODCENCUS AS CODCENCUS_CAB, C.CODPROJ AS CODPROJ_CAB,
         C.RATEADO AS RATEADO_CAB,
         B.VDUP_XML, B.DVENC_XML, B.NDUP_XML
    FROM &TBL_BASE B
    JOIN TGFCAB C ON C.NUNOTA = B.NUNOTA
   WHERE B.ID_EXECUCAO = '&ID_EXECUCAO'
), P AS (
  SELECT C.*,
         P.TIPOEMP, P.CODEMP AS CODEMP_PPG, P.TIPOPAR,
         P.CODPARC AS CODPARC_PPG, P.SEQUENCIA AS SEQ_PPG,
         P.PRAZO, P.CODTIPTITPAD, P.CODBCOPAD, P.CODCTABCOINT,
         P.CODCENCUSPAD, P.CODNATPAD, P.CODPROJPAD,
         P.TIPRECDESP, P.TIPOFIN, P.PERCENTUAL,
         COUNT(P.CODTIPVENDA) OVER (PARTITION BY C.NUNOTA) AS QTD_PPG_ENCONTRADAS,
         COUNT(P.CODTIPVENDA) OVER (PARTITION BY C.NUNOTA, P.SEQUENCIA) AS QTD_PPG_MESMA_SEQ,
         ROW_NUMBER() OVER (
           PARTITION BY C.NUNOTA
           ORDER BY P.SEQUENCIA, P.PRAZO, P.TIPOEMP,
                    P.CODEMP, P.TIPOPAR, P.CODPARC
         ) AS RN_PPG
    FROM C
    LEFT JOIN TGFPPG P ON P.CODTIPVENDA = C.CODTIPVENDA
)
SELECT P.ID_EXECUCAO, P.DH_EXECUCAO, P.USUARIO_EXECUCAO,
       P.NUNOTA, P.NUMNOTA, P.SERIENOTA, P.CODEMP, P.CODPARC,
       P.CODTIPOPER, P.DESCROPER, P.CODTIPVENDA, P.DHTIPOPER,
       P.DTNEG, P.DTENTSAI, P.DTMOV, P.CODVEND,
       P.CODNAT_CAB, P.CODCENCUS_CAB, P.CODPROJ_CAB, P.RATEADO_CAB,
       P.TIPOEMP, P.CODEMP_PPG, P.TIPOPAR, P.CODPARC_PPG,
       P.SEQ_PPG, P.PRAZO, P.CODTIPTITPAD, P.CODBCOPAD,
       P.CODCTABCOINT, P.CODCENCUSPAD, P.CODNATPAD, P.CODPROJPAD,
       P.TIPRECDESP, P.TIPOFIN, P.PERCENTUAL,
       P.VDUP_XML, P.DVENC_XML, P.NDUP_XML,
       (SELECT MAX(N.ULTCOD) FROM TGFNUM N WHERE N.ARQUIVO = 'TGFFIN')
         AS ULTCOD_TGFNUM_ATUAL,
       CASE
         WHEN P.QTD_PPG_ENCONTRADAS = 0 THEN 'SEM_TGFPPG'
         WHEN P.QTD_PPG_MESMA_SEQ > 1 THEN 'REVISAR_DUPLICIDADE_TGFPPG'
         WHEN P.VDUP_XML IS NULL THEN 'SEM_VDUP_XML'
         WHEN NOT REGEXP_LIKE(P.DVENC_XML, '^[0-9]{4}-[0-9]{2}-[0-9]{2}$')
           THEN 'DVENC_XML_INVALIDO'
         WHEN P.CODTIPTITPAD IS NULL THEN 'SEM_CODTIPTITPAD'
         WHEN (SELECT COUNT(*) FROM TGFNUM N WHERE N.ARQUIVO = 'TGFFIN') <> 1
           THEN 'REVISAR_TGFNUM'
         ELSE 'APTO_PARA_VALIDACAO_FINAL'
       END AS STATUS_MAPA,
       CASE
         WHEN P.QTD_PPG_ENCONTRADAS = 0 THEN 'Nao foi encontrada condicao em TGFPPG.'
         WHEN P.QTD_PPG_MESMA_SEQ > 1 THEN 'Mais de uma TGFPPG para a mesma sequencia; aplicar regra de precedencia.'
         WHEN P.DVENC_XML IS NULL THEN 'Vencimento deve ser obtido do XML.'
         WHEN P.CODTIPTITPAD IS NULL THEN 'Tipo de titulo ausente na condicao de pagamento.'
         ELSE 'Revisar valores e somente depois gerar o INSERT.'
       END AS OBSERVACAO
  FROM P;

PROMPT === RESUMO DO MAPA ===
SELECT STATUS_MAPA, COUNT(*) AS QTD
  FROM &TBL_PPG
 WHERE ID_EXECUCAO='&ID_EXECUCAO'
 GROUP BY STATUS_MAPA
 ORDER BY STATUS_MAPA;

PROMPT === CAMPOS QUE SERAO USADOS NO INSERT ===
PROMPT TGFCAB: NUNOTA, NUMNOTA, SERIENOTA, CODEMP, CODPARC, CODTIPOPER, DHTIPOPER, DTNEG, DTENTSAI, DTMOV
PROMPT TGFPPG: CODTIPTITPAD, CODBCOPAD, CODCTABCOINT, CODCENCUSPAD, CODNATPAD, CODPROJPAD, TIPRECDESP, SEQUENCIA
PROMPT XML: vDup, dVenc e nDup
PROMPT TGFNUM: ULTCOD com bloqueio FOR UPDATE no momento do INSERT
PROMPT PADRAO: PROVISAO=N, RATEADO=N, RECEBIDO=NULL, VLRBAIXA=0, descontos/juros/multas=0
PROMPT Este arquivo nao altera TGFCAB, TGFTOP, TGFFIN ou TGFNUM.
