CREATE TABLE TGFCUS_BKP AS SELECT * FROM TGFCUS;

ALTER TRIGGER TRG_DLT_UPD_TGFCUS DISABLE;

DELETE TGFCUS C
WHERE C.DTATUAL = '01/01/1900'
AND C.CUSSEMICM = 0
AND EXISTS (SELECT 1 FROM TGFCUS WHERE CODPROD = C.CODPROD AND DTATUAL <> '01/01/1900' /*CUSSEMICM > 0*/); COMMIT;

ALTER TRIGGER TRG_DLT_UPD_TGFCUS ENABLE;


--Gerar custo com margem de 40%
--UPDATE TGFCUS C
--   SET C.CUSSEMICM = ROUND((SNK_PRECO (0, C.CODPROD) * 0.6), 2)
-- WHERE C.DTATUAL = '01/01/1900'
--   AND C.CUSSEMICM = 0
--   AND SNK_PRECO (0, C.CODPROD) > 0
--   AND NOT EXISTS (SELECT 1 FROM TGFCUS WHERE CODPROD = C.CODPROD AND CUSSEMICM > 0); COMMIT;



-- VERIFICAR ITENS SEM CUSTO MAS DEVERIAM TER
--SELECT DISTINCT P.CODPROD
--FROM TGFPRO P
--JOIN TGFITE I ON I.CODPROD = P.CODPROD
--JOIN TGFCAB C ON C.NUNOTA = I.NUNOTA 
--JOIN TGFTOP T ON T.CODTIPOPER = C.CODTIPOPER AND T.DHALTER = C.DHTIPOPER AND T.PRECIFICA <> 'N'
--WHERE NOT EXISTS (SELECT 1 FROM TGFCUS WHERE CODPROD = P.CODPROD AND CUSSEMICM > 0 AND DTATUAL <> '01/01/1900')
--AND NOT EXISTS (SELECT 1 FROM TGFCUS WHERE CODPROD = P.CODPROD AND CUSREP > 0 AND DTATUAL <> '01/01/1900');



--UPDATE TGFCUS
--   SET CUSMEDICM = CUSSEMICM,
--        CUSREP = CUSSEMICM,
--        CUSVARIAVEL = CUSSEMICM,
--        CUSGER = CUSSEMICM,
--        CUSMED = CUSSEMICM,
--        ENTRADACOMICMS = CUSSEMICM,
--        ENTRADASEMICMS = CUSSEMICM
-- WHERE DTATUAL = '01/01/1900'
--   AND CUSMEDICM = 0
--    AND        CUSREP = 0
--    AND        CUSVARIAVEL = 0
--    AND        CUSGER = 0
--    AND        CUSMED = 0
--    AND        ENTRADACOMICMS = 0
--    AND        ENTRADASEMICMS = 0;