SELECT * 
  FROM (
        SELECT C.TIPMOV, C.CODTIPOPER, T.DESCROPER, I.CODPROD, P.DESCRPROD, ROUND(AVG(I.VLRUNIT),2) AS VLRUNITMEDIO, I.CODVOL
          FROM TGFITE I
          JOIN TGFPRO P ON P.CODPROD = I.CODPROD
          JOIN TGFCAB C ON C.NUNOTA = I.NUNOTA AND C.TIPMOV = 'C' 
          JOIN TGFTOP T ON T.CODTIPOPER = C.CODTIPOPER AND T.DHALTER = C.DHTIPOPER AND T.PRECIFICA <> 'N'
      GROUP BY C.TIPMOV, C.CODTIPOPER, T.DESCROPER, I.CODPROD, P.DESCRPROD, I.CODVOL
    
        UNION ALL
    
        SELECT C.TIPMOV, C.CODTIPOPER, T.DESCROPER, I.CODPROD, P.DESCRPROD, ROUND(AVG(I.VLRUNIT),2) AS VLRUNITMEDIO, I.CODVOL
          FROM TGFITE I
          JOIN TGFPRO P ON P.CODPROD = I.CODPROD
          JOIN TGFCAB C ON C.NUNOTA = I.NUNOTA AND C.TIPMOV = 'V' 
          JOIN TGFTOP T ON T.CODTIPOPER = C.CODTIPOPER AND T.DHALTER = C.DHTIPOPER AND T.GOLSINAL = -1
      GROUP BY C.TIPMOV, C.CODTIPOPER, T.DESCROPER, I.CODPROD, P.DESCRPROD, I.CODVOL    
      ) Q
 WHERE Q.CODPROD = 714
ORDER BY Q.CODPROD, Q.TIPMOV
;
