SELECT 
    CAB.NUNOTA,
    CAB.OBSERVACAO

FROM TGFCAB CAB
JOIN (
    SELECT 
        T.CODTIPOPER,
        T.DESCROPER,
        T.CODCFO_ENTRADA,
        T.CODCFO_SAIDA,
        T.CODCFO_ENTRADA_FORA,
        T.CODCFO_SAIDA_FORA
    FROM TGFTOP T
    JOIN (
        SELECT CODTIPOPER, MAX(DHALTER) AS MAX_DHALTER
        FROM TGFTOP
        GROUP BY CODTIPOPER
    ) M
      ON M.CODTIPOPER = T.CODTIPOPER
     AND M.MAX_DHALTER = T.DHALTER
) TOPS
  ON TOPS.CODTIPOPER = CAB.CODTIPOPER
LEFT JOIN TGFCFO CFO_E
       ON CFO_E.CODCFO = TOPS.CODCFO_ENTRADA
LEFT JOIN TGFCFO CFO_S
       ON CFO_S.CODCFO = TOPS.CODCFO_SAIDA
LEFT JOIN TGFCFO CFO_EF
       ON CFO_EF.CODCFO = TOPS.CODCFO_ENTRADA_FORA
LEFT JOIN TGFCFO CFO_SF
       ON CFO_SF.CODCFO = TOPS.CODCFO_SAIDA_FORA

WHERE CAB.CODTIPOPER = :A_CODTIPOPER
  AND CAB.NUNOTA IN (
    SELECT DISTINCT C.NUNOTA
    FROM TGFCAB C
    WHERE C.TIPMOV <>'Z'
      AND NOT EXISTS (
          SELECT 1
          FROM TGFFIN F
          WHERE F.NUNOTA = C.NUNOTA
      )
)
ORDER BY CAB.CODTIPOPER;

--VENDA COMPLEMENTAR 1116
--COMPRA COMPLEMENTAR 1494

ALTER TRIGGER TRG_UPD_TGFCAB DISABLE;

UPDATE TGFCAB C
SET C.CODTIPOPER = :CODTIPOPERNOVA,
    C.DHTIPOPER = (SELECT MIN(DHALTER) 
                     FROM TGFTOP 
                     WHERE CODTIPOPER = :CODTIPOPERNOVA 
                     AND DHALTER <= C.DTNEG)
WHERE C.CODTIPOPER = :CODTIPOPERATUAL
AND C.NUNOTA IN (122682);

ALTER TRIGGER TRG_UPD_TGFCAB ENABLE;