--SELECT CODPARC, RAZAOSOCIAL, TIPPESSOA, IDENTINSCESTAD,  
--       F_DESCROPC('TGFPAR','CLASSIFICMS',CLASSIFICMS) AS CLASSIFICMS,
--       CASE WHEN (TIPPESSOA = 'J' AND IDENTINSCESTAD  IS NOT NULL AND UPPER(IDENTINSCESTAD) <> 'ISENTO' AND NVL(CLASSIFICMS, 'Z') <> 'R') THEN 'R-Revendedor'
--            WHEN (TIPPESSOA = 'F' AND IDENTINSCESTAD IS NOT NULL AND UPPER(IDENTINSCESTAD) <> 'ISENTO' AND NVL(CLASSIFICMS, 'Z') <> 'P') THEN 'P-Produtor Rural'
--            WHEN (NVL(IDENTINSCESTAD, 'ISENTO') = 'ISENTO' AND NVL(CLASSIFICMS, 'Z') <> 'C') THEN 'C-Consumidor Final Não Contribuinte'
--        END CLASSIFICMS_ESPERADO
--FROM TGFPAR
--WHERE (TIPPESSOA = 'J' AND IDENTINSCESTAD  IS NOT NULL AND UPPER(IDENTINSCESTAD) <> 'ISENTO' AND NVL(CLASSIFICMS, 'Z') <> 'R') 
--   OR (TIPPESSOA = 'F' AND IDENTINSCESTAD IS NOT NULL AND UPPER(IDENTINSCESTAD) <> 'ISENTO' AND NVL(CLASSIFICMS, 'Z') <> 'P')
--   OR (NVL(IDENTINSCESTAD, 'ISENTO') = 'ISENTO' AND NVL(CLASSIFICMS, 'Z') <> 'C')
--;

CREATE TABLE TGFPAR_BKP AS SELECT * FROM TGFPAR;

UPDATE TGFPAR
SET CLASSIFICMS =  (CASE WHEN (TIPPESSOA = 'J' AND IDENTINSCESTAD  IS NOT NULL AND UPPER(IDENTINSCESTAD) <> 'ISENTO' AND NVL(CLASSIFICMS, 'Z') <> 'R') THEN 'R'
                         WHEN (TIPPESSOA = 'F' AND IDENTINSCESTAD IS NOT NULL AND UPPER(IDENTINSCESTAD) <> 'ISENTO' AND NVL(CLASSIFICMS, 'Z') <> 'P') THEN 'P'
                         WHEN (NVL(IDENTINSCESTAD, 'ISENTO') = 'ISENTO' AND NVL(CLASSIFICMS, 'Z') <> 'C') THEN 'C'
                    END)
WHERE (TIPPESSOA = 'J' AND IDENTINSCESTAD  IS NOT NULL AND UPPER(IDENTINSCESTAD) <> 'ISENTO' AND NVL(CLASSIFICMS, 'Z') <> 'R') 
   OR (TIPPESSOA = 'F' AND IDENTINSCESTAD IS NOT NULL AND UPPER(IDENTINSCESTAD) <> 'ISENTO' AND NVL(CLASSIFICMS, 'Z') <> 'P')
   OR (NVL(IDENTINSCESTAD, 'ISENTO') = 'ISENTO' AND NVL(CLASSIFICMS, 'Z') <> 'C')
; COMMIT;