--ALTER TRIGGER TRG_UPT_TGFFIN_NUBCO DISABLE;
--ALTER TRIGGER TRG_DLT_TGFCAB_ESTTERC DISABLE;
--
--CREATE TABLE TGFPAR_BKP AS SELECT * FROM TGFPAR;
--CREATE TABLE TGFCAB_BKP AS SELECT * FROM TGFCAB;
--CREATE TABLE TGFPAP_BKP AS SELECT * FROM TGFPAP;
--
--ALTER TRIGGER TRG_UPT_TGFFIN_NUBCO ENABLE;
--ALTER TRIGGER TRG_DLT_TGFCAB_ESTTERC ENABLE;

--DELETE TGFPAP;
--INSERT INTO TGFPAP
--SELECT * FROM TGFPAP_BKP P WHERE EXISTS (SELECT 1 FROM TGFPAR WHERE CODPARC = P.CODPARC);

--INSERT INTO TGFPAP
--SELECT * FROM TGFPAP_BKP P WHERE EXISTS (SELECT 1 FROM TGFPAR WHERE CODPARC = P.CODPARC);


BEGIN
FOR i IN
(SELECT
  P.CODPARC,
  P.CGC_CPF,
  (
    SELECT MIN(P2.CODPARC)
    FROM TGFPAR P2
    JOIN TSICID C2 ON P2.CODCID = C2.CODCID
    JOIN TSIUFS U2 ON C2.UF = U2.CODUF
    WHERE P2.CGC_CPF = P.CGC_CPF
      AND U2.CODUF   = U.CODUF
  ) AS MENOR
FROM TGFPAR P
JOIN TSICID C ON P.CODCID = C.CODCID
JOIN TSIUFS U ON C.UF     = U.CODUF
WHERE EXISTS (
  SELECT 1
  FROM TGFPAR P3
  JOIN TSICID C3 ON P3.CODCID = C3.CODCID
  JOIN TSIUFS U3 ON C3.UF     = U3.CODUF
  WHERE P3.CGC_CPF = P.CGC_CPF
    AND U3.CODUF   = U.CODUF
  GROUP BY P3.CGC_CPF, U3.CODUF
  HAVING COUNT(*) > 1
)
AND P.CODPARC > (
  SELECT MIN(P4.CODPARC)
  FROM TGFPAR P4
  JOIN TSICID C4 ON P4.CODCID = C4.CODCID
  JOIN TSIUFS U4 ON C4.UF     = U4.CODUF
  WHERE P4.CGC_CPF = P.CGC_CPF
    AND U4.CODUF   = U.CODUF
)
--AND P.CODPARC IN (604, 628) --*** apenas se quiser direcionar para parceiros pontuais ***
)

LOOP
UPDATE TGFPAR SET FORNECEDOR = 'S', CLIENTE = 'S' WHERE CODPARC = i.MENOR; COMMIT;
UPDATE TGFCAB SET CODPARC = i.MENOR, 
                  CODPARCTRANSP = i.MENOR 
                 -- CODPARCDEST = i.MENOR 
 WHERE CODPARC =i.CODPARC; COMMIT;
UPDATE TGFFIN SET CODPARC = i.MENOR WHERE CODPARC =i.CODPARC; COMMIT;
UPDATE TGFPRO SET CODPARCFORN = i.MENOR WHERE CODPARCFORN = i.CODPARC; COMMIT;
UPDATE TGFGIR SET CODPARCFORN = i.MENOR WHERE CODPARCFORN =i.CODPARC; COMMIT;
UPDATE TGFPAP SET CODPARC = i.MENOR WHERE CODPARC = i.CODPARC; COMMIT;


--DELETE TGFPAP WHERE CODPARC = i.CODPARC; COMMIT;
--DELETE TGFPAP WHERE CODPARC = i.CODPARC; COMMIT;
--DELETE TGFPAR1 WHERE CODPARC = i.CODPARC; COMMIT;
DELETE TGFPAR WHERE CODPARC = i.CODPARC AND NOMEPARC NOT LIKE '%CONSUMIDOR%'; COMMIT;

END LOOP;

END;

