ALTER TRIGGER TRG_UPT_TGFFIN DISABLE;

-- Estornar
UPDATE TGFFIN
SET DHBAIXA = NULL
WHERE DHBAIXA IS NOT NULL; COMMIT;


--Re-baixar
UPDATE TGFFIN
SET DHBAIXA = DTVENC
WHERE CODCTABCOINT = 3
AND CODEMPBAIXA IS NOT NULL
AND VLRBAIXA <> 0
AND NUBCO IS NOT NULL;



ALTER TRIGGER TRG_UPT_TGFFIN ENABLE;