   SELECT C.NUNOTA, 
          F.NUFIN, 
          F.DTVENC AS DTVENC_FIN, 
          TO_CHAR(TO_DATE(FNC_BUSCA_TAG_XML_GERAL(C.NUNOTA, 'dVenc'), 'YYYY-MM-DD'),'DD/MM/YYYY') AS dVenc_XML,
          FNC_BUSCA_TAG_XML_GERAL(C.NUNOTA, 'vNF') AS vNF,
          C.OBSERVACAO
     FROM TGFCAB C
LEFT JOIN TGFFIN F ON F.NUNOTA = C.NUNOTA 
    WHERE C.CODTIPOPER = :CODTIPOPER
      AND F.DTVENC IS NULL
      --AND TO_CHAR(TO_DATE(FNC_BUSCA_TAG_XML_GERAL(C.NUNOTA, 'dVenc'), 'YYYY-MM-DD'),'DD/MM/YYYY') IS NOT NULL
 ORDER BY 1;


SELECT NUNOTA, NUFIN, DTVENC, TO_CHAR(
  TO_DATE(FNC_BUSCA_TAG_XML_GERAL(NUNOTA, 'dVenc'), 'YYYY-MM-DD'),
  'DD/MM/YYYY'
) AS dVenc
FROM TGFFIN 
WHERE CODTIPOPER = :CODTIPOPER;
SELECT NUNOTA, TO_CHAR(
  TO_DATE(FNC_BUSCA_TAG_XML_GERAL(NUNOTA, 'dVenc'), 'YYYY-MM-DD'),
  'DD/MM/YYYY'
) AS dVenc
FROM TGFCAB 
WHERE CODTIPOPER = :CODTIPOPER
AND TO_CHAR(
  TO_DATE(FNC_BUSCA_TAG_XML_GERAL(NUNOTA, 'dVenc'), 'YYYY-MM-DD'),
  'DD/MM/YYYY'
) IS NULL 
ORDER BY 1;


UPDATE TGFFIN
   SET DTVENC = TO_CHAR(TO_DATE(FNC_BUSCA_TAG_XML_GERAL(NUNOTA, 'dVenc'), 'YYYY-MM-DD'),'DD/MM/YYYY')
 WHERE CODTIPOPER = 1124
   AND DTVENC <> NVL(TO_CHAR(TO_DATE(FNC_BUSCA_TAG_XML_GERAL(NUNOTA, 'dVenc'), 'YYYY-MM-DD'),'DD/MM/YYYY'), DTVENC);
   
   
DELETE TGFFIN
WHERE CODTIPOPER = 1123
AND TO_CHAR(TO_DATE(FNC_BUSCA_TAG_XML_GERAL(NUNOTA, 'dVenc'), 'YYYY-MM-DD'),'DD/MM/YYYY') IS NULL;



SELECT * FROM TGFITE WHERE CODPROD IN (225,
230,
236,
237);
   




