UPDATE TGFCAB C
   SET C.NUMPROTOC = 0
 WHERE C.NUMPROTOC IS NULL
   AND C.TIPMOV    = 'V'
   AND C.STATUSNFE = 'A'
   AND C.CHAVENFE IS NOT NULL
   AND EXISTS (
        SELECT 1
          FROM TGFTOP T
         WHERE T.CODTIPOPER = C.CODTIPOPER
           AND T.DHALTER   = C.DHTIPOPER
           AND T.CODMODDOC = 55
   );
COMMIT;
