-- Card 29/30 - preflight antifragil para merge de bairros e enderecos.
-- Somente leitura: inventaria colisoes, dependencias, chaves e quota.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET LINESIZE 300
SET PAGESIZE 500
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

SPOOL "/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Clientes/INSTITUTO MOREIRA SALLES/Logs/29_30_Preflight_Merge_20260914.log"

PROMPT === CARD 29/30 - PREFLIGHT MERGE INSTITUTO MOREIRA SALLES ===

SELECT USER AS USUARIO,
       SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AS CURRENT_SCHEMA,
       SYS_CONTEXT('USERENV','SERVICE_NAME') AS SERVICE_NAME,
       SYS_CONTEXT('USERENV','INSTANCE_NAME') AS INSTANCE_NAME
  FROM DUAL;

PROMPT === QUOTA DA SESSAO ===
SELECT TABLESPACE_NAME, BYTES, MAX_BYTES, BLOCKS, MAX_BLOCKS
  FROM USER_TS_QUOTAS
 ORDER BY TABLESPACE_NAME;

PROMPT === TABELAS E COLUNAS FISICAS CODBAI/CODEND ===
SELECT COUNT(*) AS COLUNAS_FISICAS,
       COUNT(DISTINCT C.TABLE_NAME) AS TABELAS_FISICAS,
       SUM(CASE WHEN C.COLUMN_NAME='CODBAI' THEN 1 ELSE 0 END) AS COLUNAS_CODBAI,
       SUM(CASE WHEN C.COLUMN_NAME='CODEND' THEN 1 ELSE 0 END) AS COLUNAS_CODEND
  FROM ALL_TAB_COLUMNS C
  JOIN ALL_TABLES T ON T.OWNER=C.OWNER AND T.TABLE_NAME=C.TABLE_NAME
 WHERE C.OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
   AND C.COLUMN_NAME IN ('CODBAI','CODEND')
;

PROMPT === COLISOES NORMALIZADAS DE BAIRROS ===
WITH N AS (
  SELECT CODBAI, NOMEBAI,
         REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEBAI),
           'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇáàâãäéèëíìîïóòôõöúùûüçÃãÕõÂâÊêÎîÔôÛû',
           'AAAAAEEEEIIIIOOOOOUUUUCAAAAAEEEEIIIIOOOOOUUUUCAAAOOAAEIIOOUU')),
           ' {2,}',' ') AS CHAVE_NORM
    FROM TSIBAI
), G AS (
  SELECT CHAVE_NORM, COUNT(*) AS QTD, MIN(CODBAI) AS CODBAI_MANTIDO,
         MAX(CODBAI) AS CODBAI_MAXIMO
    FROM N
   GROUP BY CHAVE_NORM
  HAVING COUNT(*)>1
)
SELECT COUNT(*) AS GRUPOS_COLISAO,
       NVL(SUM(QTD),0) AS REGISTROS_COLISAO,
       NVL(SUM(QTD-1),0) AS REGISTROS_OBSOLETOS,
       MIN(CODBAI_MANTIDO) AS MENOR_CODBAI_MANTIDO,
       MAX(CODBAI_MAXIMO) AS MAIOR_CODBAI_ENVOLVIDO
  FROM G;

PROMPT === COLISOES NORMALIZADAS DE ENDERECOS POR TIPO ===
WITH N AS (
  SELECT CODEND, TIPO, NOMEEND,
         REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEEND),
           'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇáàâãäéèëíìîïóòôõöúùûüçÃãÕõÂâÊêÎîÔôÛû',
           'AAAAAEEEEIIIIOOOOOUUUUCAAAAAEEEEIIIIOOOOOUUUUCAAAOOAAEIIOOUU')),
           ' {2,}',' ') AS CHAVE_NORM
    FROM TSIEND
), G AS (
  SELECT TIPO, CHAVE_NORM, COUNT(*) AS QTD, MIN(CODEND) AS CODEND_MANTIDO,
         MAX(CODEND) AS CODEND_MAXIMO
    FROM N
   GROUP BY TIPO, CHAVE_NORM
  HAVING COUNT(*)>1
)
SELECT COUNT(*) AS GRUPOS_COLISAO,
       NVL(SUM(QTD),0) AS REGISTROS_COLISAO,
       NVL(SUM(QTD-1),0) AS REGISTROS_OBSOLETOS,
       MIN(CODEND_MANTIDO) AS MENOR_CODEND_MANTIDO,
       MAX(CODEND_MAXIMO) AS MAIOR_CODEND_ENVOLVIDO
  FROM G;

PROMPT === INVENTARIO DE FKS PARA TSIBAI/TSIEND (INCLUI COMPOSTAS) ===
SELECT P.TABLE_NAME AS PARENT_TABLE,
       COUNT(DISTINCT C.CONSTRAINT_NAME) AS FK_CONSTRAINTS,
       COUNT(DISTINCT C.TABLE_NAME) AS CHILD_TABLES,
       COUNT(*) AS FK_COLUMNS,
       SUM(CASE WHEN CC.POSITION>1 THEN 1 ELSE 0 END) AS COMPOSITE_COLUMNS
  FROM ALL_CONSTRAINTS C
  JOIN ALL_CONS_COLUMNS CC
    ON CC.OWNER=C.OWNER AND CC.CONSTRAINT_NAME=C.CONSTRAINT_NAME
  JOIN ALL_CONSTRAINTS P
    ON P.OWNER=C.R_OWNER AND P.CONSTRAINT_NAME=C.R_CONSTRAINT_NAME
 WHERE C.OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
   AND C.CONSTRAINT_TYPE='R'
   AND P.TABLE_NAME IN ('TSIBAI','TSIEND')
 GROUP BY P.TABLE_NAME
 ORDER BY P.TABLE_NAME;

PROMPT === PKS/UKS DAS TABELAS COM DEPENDENCIA OU COLUNA CODBAI/CODEND ===
SELECT C.CONSTRAINT_TYPE,
       COUNT(DISTINCT C.CONSTRAINT_NAME) AS CONSTRAINTS,
       COUNT(DISTINCT C.TABLE_NAME) AS TABLES_WITH_KEYS,
       COUNT(*) AS KEY_COLUMNS,
       SUM(CASE WHEN CC.POSITION>1 THEN 1 ELSE 0 END) AS COMPOSITE_COLUMNS
  FROM ALL_CONSTRAINTS C
  JOIN ALL_CONS_COLUMNS CC
    ON CC.OWNER=C.OWNER AND CC.CONSTRAINT_NAME=C.CONSTRAINT_NAME
 WHERE C.OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
   AND C.CONSTRAINT_TYPE IN ('P','U')
   AND (
        C.TABLE_NAME IN (
          SELECT DISTINCT R.TABLE_NAME
            FROM ALL_CONSTRAINTS R
            JOIN ALL_CONSTRAINTS P
              ON P.OWNER=R.R_OWNER AND P.CONSTRAINT_NAME=R.R_CONSTRAINT_NAME
           WHERE R.OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
             AND R.CONSTRAINT_TYPE='R'
             AND P.TABLE_NAME IN ('TSIBAI','TSIEND')
        )
        OR EXISTS (
          SELECT 1 FROM ALL_CONS_COLUMNS X
           WHERE X.OWNER=C.OWNER
             AND X.CONSTRAINT_NAME=C.CONSTRAINT_NAME
             AND X.COLUMN_NAME IN ('CODBAI','CODEND')
        )
       )
 GROUP BY C.CONSTRAINT_TYPE
 ORDER BY C.CONSTRAINT_TYPE;

PROMPT === AMOSTRA CONTROLADA DOS LIMITES DAS COLISOES ===
SELECT 'TSIBAI' AS TABELA, MIN(CODBAI) AS MENOR_ID, MAX(CODBAI) AS MAIOR_ID
  FROM TSIBAI
UNION ALL
SELECT 'TSIEND', MIN(CODEND), MAX(CODEND)
  FROM TSIEND;

PROMPT === PREFLIGHT 29/30 CONCLUIDO; NENHUM DML FOI EXECUTADO ===
SPOOL OFF
