-- Card 09 - compilacao autorizada da funcao de leitura XML.
-- Autorizacao explicita registrada em 2026-09-14.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET SQLBLANKLINES ON
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

SPOOL "/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Clientes/INSTITUTO MOREIRA SALLES/Logs/Card09_Compilacao_Funcao_XML_20260914.log"

PROMPT === CARD 09 - COMPILACAO AUTORIZADA DA FUNCAO XML ===
PROMPT FONTE: 7 - QA2/Scripts Originais/FNC_BUSCA_TAG_XML_GERAL.sql

@"/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Scripts Originais/FNC_BUSCA_TAG_XML_GERAL.sql"

PROMPT === STATUS DO OBJETO ===
SELECT OWNER, OBJECT_NAME, OBJECT_TYPE, STATUS
  FROM ALL_OBJECTS
 WHERE OBJECT_NAME = 'FNC_BUSCA_TAG_XML_GERAL'
 ORDER BY OWNER, OBJECT_TYPE;

PROMPT === ERROS DE COMPILACAO ===
SELECT OWNER, NAME, TYPE, LINE, POSITION, TEXT
  FROM ALL_ERRORS
 WHERE NAME = 'FNC_BUSCA_TAG_XML_GERAL'
 ORDER BY OWNER, SEQUENCE;

PROMPT === CARD 09 - COMPILACAO DA FUNCAO XML CONCLUIDA ===
SPOOL OFF
