-- Card 09 - validacao read-only da funcao XML contra o preflight.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET SQLBLANKLINES ON
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

SPOOL "/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Clientes/INSTITUTO MOREIRA SALLES/Logs/Card09_Validacao_Funcao_XML_20260914.log"

PROMPT === CARD 09 - VALIDACAO DA FUNCAO XML CONTRA O PREFLIGHT ===
SELECT OWNER, OBJECT_NAME, OBJECT_TYPE, STATUS
  FROM ALL_OBJECTS
 WHERE OBJECT_NAME = 'FNC_BUSCA_TAG_XML_GERAL'
 ORDER BY OWNER, OBJECT_TYPE;

SELECT COUNT(*) AS TOTAL_APTOS,
       SUM(CASE WHEN NVL(B.VDUP_XML,CHR(0)) = NVL(FNC_BUSCA_TAG_XML_GERAL(B.NUNOTA,'vDup','dup'),CHR(0))
                  AND NVL(B.DVENC_XML,CHR(0)) = NVL(FNC_BUSCA_TAG_XML_GERAL(B.NUNOTA,'dVenc','dup'),CHR(0))
                  AND NVL(B.NDUP_XML,CHR(0)) = NVL(FNC_BUSCA_TAG_XML_GERAL(B.NUNOTA,'nDup','dup'),CHR(0))
                THEN 0 ELSE 1 END) AS DIVERGENCIAS
  FROM BKP_RMD_IMS_DUP_20260914 B
 WHERE B.STATUS_MAPA = 'APTO_PARA_VALIDACAO_FINAL';

PROMPT === CARD 09 - VALIDACAO DA FUNCAO XML CONCLUIDA ===
SPOOL OFF
