-- Card 09 - mapa persistente para inclusao controlada, sem INSERT em TGFFIN.
-- A leitura da funcao XML ja foi validada separadamente contra o preflight.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET SQLBLANKLINES ON
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

SPOOL "/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Clientes/INSTITUTO MOREIRA SALLES/Logs/Card09_Mapa_20260914_retry.log"

PROMPT === CARD 09 - MAPA PERSISTENTE INSTITUTO MOREIRA SALLES ===

DECLARE
  v_exists NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_exists
    FROM ALL_TABLES
   WHERE OWNER = SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
     AND TABLE_NAME = 'BKP_RMD_IMS_DUP_PPG_20260914';
  IF v_exists > 0 THEN
    RAISE_APPLICATION_ERROR(-20322,
      'Mapa BKP_RMD_IMS_DUP_PPG_20260914 ja existe; nao repetir sem novo ID.');
  END IF;

  EXECUTE IMMEDIATE q'~
    CREATE TABLE BKP_RMD_IMS_DUP_PPG_20260914 AS
    WITH R AS (
      SELECT
        'RMD_FDUP_IMS_20260914165524' AS ID_EXECUCAO_MAPA,
        SYSTIMESTAMP AS DH_MAPA,
        SYS_CONTEXT('USERENV','SESSION_USER') AS USUARIO_MAPA,
        B.ID_EXECUCAO AS ID_PREFLIGHT,
        B.DH_EXECUCAO AS DH_PREFLIGHT,
        B.USUARIO_EXECUCAO AS USUARIO_PREFLIGHT,
        B.NUNOTA, B.CODEMP, B.NUMNOTA, B.SERIENOTA, B.DTNEG, B.DTMOV,
        B.CODPARC, B.CODTIPOPER, B.CODTIPVENDA, B.DHTIPVENDA,
        C.DHTIPOPER, C.DTENTSAI, C.CODVEND,
        C.CODNAT AS CODNAT_CAB, C.CODCENCUS AS CODCENCUS_CAB,
        C.CODPROJ AS CODPROJ_CAB, C.RATEADO AS RATEADO_CAB,
        B.TIPMOV, B.VLRNOTA,
        B.TIPOEMP, B.CODEMP_PPG, B.TIPOPAR, B.CODPARC_PPG,
        B.SEQ_PPG, B.PRAZO, B.CODTIPTITPAD, B.CODBCOPAD,
        B.CODCTABCOINT, B.CODCENCUSPAD, B.CODNATPAD, B.CODPROJPAD,
        B.TIPRECDESP, B.TIPOFIN, B.PERCENTUAL,
        B.VDUP_XML, B.DVENC_XML, B.NDUP_XML,
        B.QTD_PPG, B.QTD_PPG_SEQ, B.STATUS_MAPA AS STATUS_PREFLIGHT,
        (SELECT MAX(V.TIPJURO)
           FROM TGFTPV V
          WHERE V.CODTIPVENDA = B.CODTIPVENDA
            AND V.DHALTER = B.DHTIPVENDA) AS TIPJURO_TPV,
        (SELECT COUNT(*)
           FROM TGFTPV V
          WHERE V.CODTIPVENDA = B.CODTIPVENDA
            AND V.DHALTER = B.DHTIPVENDA) AS QTD_TGFTPV_EXATA,
        (SELECT COUNT(*)
           FROM TGFFIN F
          WHERE F.NUNOTA = B.NUNOTA) AS QTD_TGFFIN_ATUAL,
        (SELECT COUNT(*)
           FROM TGFNUM N
          WHERE N.ARQUIVO = 'TGFFIN') AS QTD_TGFNUM_TGFFIN,
        (SELECT MAX(N.ULTCOD)
           FROM TGFNUM N
          WHERE N.ARQUIVO = 'TGFFIN') AS ULTCOD_TGFNUM_ATUAL,
        (SELECT MIN(A.CODCTABCOINT)
           FROM TSICTA A
          WHERE A.ATIVA = 'S'
            AND A.CODEMP = B.CODEMP) AS CODCTABCOINT_ATIVA,
        (SELECT COUNT(*)
           FROM BKP_RMD_IMS_DUP_20260914 X
          WHERE X.NUNOTA = B.NUNOTA
            AND X.STATUS_MAPA = 'APTO_PARA_VALIDACAO_FINAL')
          AS QTD_LINHAS_APTAS_NUNOTA
      FROM BKP_RMD_IMS_DUP_20260914 B
      JOIN TGFCAB C ON C.NUNOTA = B.NUNOTA
    )
    SELECT R.*,
           NVL(R.CODCTABCOINT, R.CODCTABCOINT_ATIVA) AS CODCTABCOINT_RESOLVIDO,
           NVL(R.CODBCOPAD, 0) AS CODBCO_RESOLVIDO,
           CASE
             WHEN UPPER(TRIM(R.TIPRECDESP)) IN ('I','R','1') THEN 1
             WHEN UPPER(TRIM(R.TIPRECDESP)) IN ('D','P','-1') THEN -1
             WHEN R.TIPMOV = 'V' THEN 1
             WHEN R.TIPMOV = 'C' THEN -1
             ELSE 0
           END AS RECDESP_RESOLVIDO,
           CASE WHEN UPPER(TRIM(R.TIPJURO_TPV)) = 'I' THEN 1 ELSE 0 END
             AS TIPJURO_RESOLVIDO,
           NVL(R.CODCENCUSPAD, R.CODCENCUS_CAB) AS CODCENCUS_RESOLVIDO,
           NVL(R.CODNATPAD, R.CODNAT_CAB) AS CODNAT_RESOLVIDO,
           NVL(R.CODPROJPAD, R.CODPROJ_CAB) AS CODPROJ_RESOLVIDO,
           CASE
             WHEN R.STATUS_PREFLIGHT <> 'APTO_PARA_VALIDACAO_FINAL'
               THEN R.STATUS_PREFLIGHT
             WHEN R.QTD_LINHAS_APTAS_NUNOTA <> 1
               THEN 'REVISAR_MULTIPLAS_PARCELAS'
             WHEN R.QTD_TGFTPV_EXATA <> 1
               THEN 'REVISAR_TGFTPV_EXATA'
             WHEN R.QTD_TGFNUM_TGFFIN <> 1
               THEN 'REVISAR_TGFNUM'
             WHEN R.QTD_TGFFIN_ATUAL <> 0
               THEN 'TGFFIN_JA_EXISTE'
             WHEN NVL(R.CODCTABCOINT, R.CODCTABCOINT_ATIVA) IS NULL
               THEN 'SEM_CONTA_ATIVA'
             ELSE 'APTO_PARA_INSERCAO_CONTROLADA'
           END AS STATUS_MAPA
      FROM R
  ~';
  COMMIT;
END;
/

PROMPT === RESUMO DO MAPA PERSISTENTE ===
SELECT STATUS_MAPA, COUNT(*) AS QTD
  FROM BKP_RMD_IMS_DUP_PPG_20260914
 GROUP BY STATUS_MAPA
 ORDER BY STATUS_MAPA;

PROMPT === CONTROLES DO MAPA ===
SELECT COUNT(*) AS LINHAS_MAPA,
       COUNT(DISTINCT NUNOTA) AS NOTAS_MAPA,
       SUM(CASE WHEN STATUS_MAPA = 'APTO_PARA_INSERCAO_CONTROLADA' THEN 1 ELSE 0 END) AS LINHAS_APTAS,
       COUNT(DISTINCT CASE WHEN STATUS_MAPA = 'APTO_PARA_INSERCAO_CONTROLADA' THEN NUNOTA END) AS NOTAS_APTAS,
       SUM(QTD_TGFFIN_ATUAL) AS TGFFIN_EXISTENTE_NO_MAPA,
       MIN(QTD_TGFNUM_TGFFIN) AS TGFNUM_LINHAS,
       MIN(ULTCOD_TGFNUM_ATUAL) AS ULTCOD_TGFNUM
  FROM BKP_RMD_IMS_DUP_PPG_20260914;

PROMPT === CANDIDATOS APTOS PARA REVISAO FINAL ===
SELECT NUNOTA, CODEMP, NUMNOTA, SERIENOTA, CODTIPOPER, CODTIPVENDA,
       VDUP_XML, DVENC_XML, NDUP_XML, CODTIPTITPAD, CODBCO_RESOLVIDO,
       CODCTABCOINT_RESOLVIDO, RECDESP_RESOLVIDO, TIPJURO_RESOLVIDO,
       STATUS_MAPA
  FROM BKP_RMD_IMS_DUP_PPG_20260914
 WHERE STATUS_MAPA = 'APTO_PARA_INSERCAO_CONTROLADA'
 ORDER BY NUNOTA, SEQ_PPG;

PROMPT === CARD 09 - MAPA CONCLUIDO; NENHUM TGFFIN FOI INSERIDO ===

SPOOL OFF
