SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET SQLBLANKLINES ON
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
SPOOL "/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Clientes/INSTITUTO MOREIRA SALLES/Logs/Card09_Validacao_Final_20260914.log"

PROMPT === CARD 09 - VALIDACAO FINAL ANTES DA INCLUSAO ===

SELECT OWNER, OBJECT_NAME, OBJECT_TYPE, STATUS
  FROM ALL_OBJECTS
 WHERE OWNER = SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
   AND OBJECT_NAME = 'FNC_BUSCA_TAG_XML_GERAL';

SELECT COUNT(*) AS ERROS_COMPILACAO
  FROM ALL_ERRORS
 WHERE OWNER = SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
   AND NAME = 'FNC_BUSCA_TAG_XML_GERAL';

PROMPT === DISTRIBUICAO DO MAPA ===
SELECT STATUS_MAPA, COUNT(*) AS QTD_LINHAS,
       COUNT(DISTINCT NUNOTA) AS QTD_NOTAS
  FROM BKP_RMD_IMS_DUP_PPG_20260914
 GROUP BY STATUS_MAPA
 ORDER BY STATUS_MAPA;

PROMPT === TESTES DAS LINHAS APTAS ===
SELECT COUNT(*) AS LINHAS_APTAS,
       COUNT(DISTINCT NUNOTA) AS NOTAS_APTAS,
       SUM(CASE WHEN REGEXP_LIKE(TRIM(VDUP_XML),'^[0-9]+([.][0-9]+)?$') THEN 1 ELSE 0 END) AS VDUP_NUMERICO,
       SUM(CASE WHEN REGEXP_LIKE(TRIM(DVENC_XML),'^[0-9]{4}-[0-9]{2}-[0-9]{2}$') THEN 1 ELSE 0 END) AS DVENC_VALIDO,
       SUM(CASE WHEN CODTIPTITPAD IS NOT NULL
                  AND EXISTS (SELECT 1 FROM TGFTIT T WHERE T.CODTIPTIT= M.CODTIPTITPAD)
                THEN 1 ELSE 0 END) AS TITULOS_VALIDOS,
       SUM(CASE WHEN QTD_TGFTPV_EXATA=1 THEN 1 ELSE 0 END) AS TGFTPV_EXATA,
       SUM(CASE WHEN CODCTABCOINT_RESOLVIDO IS NOT NULL THEN 1 ELSE 0 END) AS CONTAS_RESOLVIDAS,
       SUM(CASE WHEN QTD_TGFFIN_ATUAL=0 THEN 1 ELSE 0 END) AS SEM_TGFFIN,
       SUM(CASE WHEN QTD_TGFNUM_TGFFIN=1 THEN 1 ELSE 0 END) AS TGFNUM_UNICO,
       SUM(CASE WHEN QTD_LINHAS_APTAS_NUNOTA=1 THEN 1 ELSE 0 END) AS UMA_LINHA_POR_NOTA
  FROM BKP_RMD_IMS_DUP_PPG_20260914 M
 WHERE STATUS_MAPA='APTO_PARA_INSERCAO_CONTROLADA';

PROMPT === PRECONDICOES CONSOLIDADAS ===
SELECT CASE
         WHEN COUNT(*)=24
          AND COUNT(DISTINCT NUNOTA)=24
          AND SUM(CASE WHEN REGEXP_LIKE(TRIM(VDUP_XML),'^[0-9]+([.][0-9]+)?$') THEN 1 ELSE 0 END)=24
          AND SUM(CASE WHEN REGEXP_LIKE(TRIM(DVENC_XML),'^[0-9]{4}-[0-9]{2}-[0-9]{2}$') THEN 1 ELSE 0 END)=24
          AND SUM(CASE WHEN CODTIPTITPAD IS NOT NULL
                         AND EXISTS (SELECT 1 FROM TGFTIT T WHERE T.CODTIPTIT= M.CODTIPTITPAD)
                       THEN 1 ELSE 0 END)=24
          AND SUM(CASE WHEN QTD_TGFTPV_EXATA=1 THEN 1 ELSE 0 END)=24
          AND SUM(CASE WHEN CODCTABCOINT_RESOLVIDO IS NOT NULL THEN 1 ELSE 0 END)=24
          AND SUM(CASE WHEN QTD_TGFFIN_ATUAL=0 THEN 1 ELSE 0 END)=24
          AND SUM(CASE WHEN QTD_TGFNUM_TGFFIN=1 THEN 1 ELSE 0 END)=24
          AND SUM(CASE WHEN QTD_LINHAS_APTAS_NUNOTA=1 THEN 1 ELSE 0 END)=24
         THEN 'APTO_PARA_CONFIRMACAO_DE_INSERCAO'
         ELSE 'BLOQUEAR_INSERCAO_E_REVISAR'
       END AS STATUS_VALIDACAO_FINAL
  FROM BKP_RMD_IMS_DUP_PPG_20260914 M
 WHERE STATUS_MAPA='APTO_PARA_INSERCAO_CONTROLADA';

PROMPT === LINHAS QUE PERMANECEM FORA DA INCLUSAO ===
SELECT STATUS_MAPA, CODEMP, COUNT(*) AS QTD_LINHAS,
       MIN(NUNOTA) AS PRIMEIRA_NUNOTA, MAX(NUNOTA) AS ULTIMA_NUNOTA
  FROM BKP_RMD_IMS_DUP_PPG_20260914
 WHERE STATUS_MAPA <> 'APTO_PARA_INSERCAO_CONTROLADA'
 GROUP BY STATUS_MAPA, CODEMP
 ORDER BY STATUS_MAPA, CODEMP;

PROMPT === CARD 09 - VALIDACAO FINAL CONCLUIDA; TGFFIN AINDA NAO FOI ALTERADA ===
SPOOL OFF
