SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET SQLBLANKLINES ON
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
SPOOL "/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Clientes/INSTITUTO MOREIRA SALLES/Logs/Card09_Diagnostico_Contas_20260914.log"

PROMPT === DIAGNOSTICO DAS LINHAS SEM CONTA ATIVA ===
SELECT CODEMP, COUNT(*) AS QTD_LINHAS,
       COUNT(DISTINCT NUNOTA) AS QTD_NOTAS,
       MIN(CODCTABCOINT) AS MENOR_CODCTABCOINT_INFORMADO,
       MIN(CODCTABCOINT_ATIVA) AS MENOR_CONTA_ATIVA_ENCONTRADA
  FROM BKP_RMD_IMS_DUP_PPG_20260914
 WHERE STATUS_MAPA = 'SEM_CONTA_ATIVA'
 GROUP BY CODEMP
 ORDER BY CODEMP;

PROMPT === DETALHE DAS LINHAS SEM CONTA ATIVA ===
SELECT NUNOTA, CODEMP, NUMNOTA, SERIENOTA, CODTIPVENDA,
       VDUP_XML, DVENC_XML, NDUP_XML, CODTIPTITPAD,
       CODBCOPAD, CODCTABCOINT, CODCTABCOINT_ATIVA,
       STATUS_PREFLIGHT, STATUS_MAPA
  FROM BKP_RMD_IMS_DUP_PPG_20260914
 WHERE STATUS_MAPA = 'SEM_CONTA_ATIVA'
 ORDER BY CODEMP, NUNOTA;

PROMPT === CONTAS POR EMPRESA ===
SELECT A.CODEMP, A.CODCTABCOINT, A.ATIVA, A.CODBCO, A.CODCTABCO,
       A.DESCRICAO
  FROM TSICTA A
 WHERE A.CODEMP IN (SELECT DISTINCT CODEMP
                      FROM BKP_RMD_IMS_DUP_PPG_20260914
                     WHERE STATUS_MAPA = 'SEM_CONTA_ATIVA')
 ORDER BY A.CODEMP, A.ATIVA DESC, A.CODCTABCOINT;

PROMPT === FIM DIAGNOSTICO ===
SPOOL OFF
