
-- Card 09 - pos-validacao integral da inclusao controlada em TGFFIN.
-- Somente consultas; nao altera TGFFIN, TGFNUM, mapa ou auditoria.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET SQLBLANKLINES ON
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

SPOOL "/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Clientes/INSTITUTO MOREIRA SALLES/Logs/Card09_Posvalidacao_20260915.log"

PROMPT === CARD 09 - POS-VALIDACAO INSTITUTO MOREIRA SALLES ===
PROMPT === IDENTIFICACAO DA EXECUCAO ===
SELECT 'RMD_FDUP_IMS_20260914165524' AS ID_EXECUCAO,
       SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AS CURRENT_SCHEMA,
       SYS_CONTEXT('USERENV','SESSION_USER') AS SESSION_USER,
       SYS_CONTEXT('USERENV','SERVICE_NAME') AS SERVICE_NAME,
       SYSTIMESTAMP AS DH_VALIDACAO
  FROM DUAL;

PROMPT === AUDITORIA DA INCLUSAO ===
SELECT COUNT(*) AS AUDITORIA_LINHAS,
       COUNT(DISTINCT NUNOTA) AS AUDITORIA_NOTAS,
       MIN(NUFIN) AS PRIMEIRO_NUFIN,
       MAX(NUFIN) AS ULTIMO_NUFIN,
       SUM(VLRDESDOB) AS VLRDESDOB_AUDITADO
  FROM BKP_RMD_IMS_DUP_INS_20260914
 WHERE ID_EXECUCAO='RMD_FDUP_IMS_20260914165524';

PROMPT === TGFFIN LOCALIZADO PELA AUDITORIA ===
SELECT COUNT(*) AS TGFFIN_MATCH_AUDITORIA,
       COUNT(DISTINCT F.NUNOTA) AS TGFFIN_NOTAS,
       COUNT(DISTINCT F.NUFIN) AS TGFFIN_NUFIN,
       MIN(F.NUFIN) AS PRIMEIRO_NUFIN,
       MAX(F.NUFIN) AS ULTIMO_NUFIN
  FROM BKP_RMD_IMS_DUP_INS_20260914 A
  JOIN TGFFIN F
    ON F.NUNOTA=A.NUNOTA
   AND F.NUFIN=A.NUFIN
 WHERE A.ID_EXECUCAO='RMD_FDUP_IMS_20260914165524';

PROMPT === TGFFIN COM VALORES E DATAS EXATOS DA AUDITORIA ===
SELECT COUNT(*) AS TGFFIN_CAMPOS_EXATOS
  FROM BKP_RMD_IMS_DUP_INS_20260914 A
  JOIN TGFFIN F
    ON F.NUNOTA=A.NUNOTA
   AND F.NUFIN=A.NUFIN
 WHERE A.ID_EXECUCAO='RMD_FDUP_IMS_20260914165524'
   AND F.VLRDESDOB=A.VLRDESDOB
   AND F.DTVENC=A.DTVENC
   AND F.CODCTABCOINT=A.CODCTABCOINT
   AND F.CODTIPTIT=A.CODTIPTIT
   AND ((F.NUMDUPL=TO_NUMBER(TRIM(A.NDUP_XML)))
        OR (F.NUMDUPL IS NULL AND A.NDUP_XML IS NULL));

PROMPT === UMA LINHA FINANCEIRA POR NOTA TRATADA ===
SELECT COUNT(*) AS NOTAS_COM_QTD_TGFFIN_DIVERGENTE
  FROM (
    SELECT A.NUNOTA, COUNT(F.NUFIN) AS QTD_TGFFIN
      FROM BKP_RMD_IMS_DUP_INS_20260914 A
      LEFT JOIN TGFFIN F ON F.NUNOTA=A.NUNOTA
     WHERE A.ID_EXECUCAO='RMD_FDUP_IMS_20260914165524'
     GROUP BY A.NUNOTA
  ) X
 WHERE X.QTD_TGFFIN<>1;

PROMPT === TGFNUM E CONTINUIDADE DA FAIXA GERADA ===
SELECT T.ARQUIVO,
       T.ULTCOD,
       A.MIN_NUFIN,
       A.MAX_NUFIN,
       A.QTD_AUDITADA,
       CASE WHEN T.ULTCOD=A.MAX_NUFIN THEN 'OK' ELSE 'REVISAR' END AS STATUS_ULTCOD,
       CASE WHEN A.MAX_NUFIN-A.MIN_NUFIN+1=A.QTD_AUDITADA
             THEN 'OK' ELSE 'REVISAR' END AS STATUS_CONTINUIDADE
  FROM TGFNUM T
 CROSS JOIN (
    SELECT MIN(NUFIN) AS MIN_NUFIN,
           MAX(NUFIN) AS MAX_NUFIN,
           COUNT(*) AS QTD_AUDITADA
      FROM BKP_RMD_IMS_DUP_INS_20260914
     WHERE ID_EXECUCAO='RMD_FDUP_IMS_20260914165524'
  ) A
 WHERE T.ARQUIVO='TGFFIN';

SELECT COUNT(*) AS TGFNUM_TGFFIN_ROWS
  FROM TGFNUM
 WHERE ARQUIVO='TGFFIN';

PROMPT === CONSISTENCIA MAPA X AUDITORIA X TGFFIN ===
SELECT COUNT(*) AS MAPA_AUDITORIA_TGFFIN_EXATOS
  FROM BKP_RMD_IMS_DUP_INS_20260914 A
  JOIN BKP_RMD_IMS_DUP_PPG_20260914 M ON M.NUNOTA=A.NUNOTA
   AND M.ID_EXECUCAO_MAPA='RMD_FDUP_IMS_20260914165524'
   AND M.STATUS_MAPA='APTO_PARA_INSERCAO_CONTROLADA'
  JOIN TGFFIN F ON F.NUNOTA=A.NUNOTA
   AND F.NUFIN=A.NUFIN
 WHERE A.ID_EXECUCAO='RMD_FDUP_IMS_20260914165524'
   AND TO_NUMBER(TRIM(M.VDUP_XML),
                 '999999999999999999D99999999',
                 'NLS_NUMERIC_CHARACTERS=''.,''')=A.VLRDESDOB
   AND TO_DATE(TRIM(M.DVENC_XML),'YYYY-MM-DD')=A.DTVENC
   AND F.VLRDESDOB=A.VLRDESDOB
   AND F.DTVENC=A.DTVENC
   AND F.CODCTABCOINT=A.CODCTABCOINT
   AND F.CODTIPTIT=A.CODTIPTIT;

PROMPT === DISTRIBUICAO FINAL DO MAPA ===
SELECT STATUS_MAPA, COUNT(*) AS QTD
  FROM BKP_RMD_IMS_DUP_PPG_20260914
 GROUP BY STATUS_MAPA
 ORDER BY STATUS_MAPA;

SELECT COUNT(*) AS MAPA_APTOS,
       COUNT(DISTINCT NUNOTA) AS MAPA_NOTAS_APTAS,
       SUM(CASE WHEN QTD_TGFFIN_ATUAL=0 THEN 1 ELSE 0 END) AS MAPA_APTOS_SEM_PREEXISTENTE,
       SUM(CASE WHEN CODCTABCOINT_RESOLVIDO IS NOT NULL THEN 1 ELSE 0 END) AS MAPA_APTOS_COM_CONTA
  FROM BKP_RMD_IMS_DUP_PPG_20260914
 WHERE ID_EXECUCAO_MAPA='RMD_FDUP_IMS_20260914165524'
   AND STATUS_MAPA='APTO_PARA_INSERCAO_CONTROLADA';

PROMPT === FUNCAO XML E ERROS DE COMPILACAO ===
SELECT OBJECT_NAME, OBJECT_TYPE, STATUS
  FROM ALL_OBJECTS
 WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
   AND OBJECT_NAME='FNC_BUSCA_TAG_XML_GERAL';

SELECT COUNT(*) AS ERROS_FUNCAO_XML
  FROM ALL_ERRORS
 WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
   AND NAME='FNC_BUSCA_TAG_XML_GERAL';

PROMPT === STATUS FINAL DO CARD 09 ===
SELECT CASE
         WHEN (SELECT COUNT(*) FROM BKP_RMD_IMS_DUP_INS_20260914
                WHERE ID_EXECUCAO='RMD_FDUP_IMS_20260914165524')=24
          AND (SELECT COUNT(DISTINCT NUNOTA) FROM BKP_RMD_IMS_DUP_INS_20260914
                WHERE ID_EXECUCAO='RMD_FDUP_IMS_20260914165524')=24
          AND (SELECT COUNT(*)
                 FROM BKP_RMD_IMS_DUP_INS_20260914 A JOIN TGFFIN F
                   ON F.NUNOTA=A.NUNOTA AND F.NUFIN=A.NUFIN
                WHERE A.ID_EXECUCAO='RMD_FDUP_IMS_20260914165524')=24
          AND (SELECT COUNT(*)
                 FROM BKP_RMD_IMS_DUP_INS_20260914 A JOIN TGFFIN F
                   ON F.NUNOTA=A.NUNOTA AND F.NUFIN=A.NUFIN
                WHERE A.ID_EXECUCAO='RMD_FDUP_IMS_20260914165524'
                  AND F.VLRDESDOB=A.VLRDESDOB AND F.DTVENC=A.DTVENC
                  AND F.CODCTABCOINT=A.CODCTABCOINT
                  AND F.CODTIPTIT=A.CODTIPTIT
                  AND ((F.NUMDUPL=TO_NUMBER(TRIM(A.NDUP_XML)))
                       OR (F.NUMDUPL IS NULL AND A.NDUP_XML IS NULL)))=24
          AND (SELECT COUNT(*) FROM TGFNUM WHERE ARQUIVO='TGFFIN')=1
          AND (SELECT COUNT(*) FROM ALL_OBJECTS
                WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
                  AND OBJECT_NAME='FNC_BUSCA_TAG_XML_GERAL'
                  AND OBJECT_TYPE='FUNCTION' AND STATUS='VALID')=1
          AND (SELECT COUNT(*) FROM ALL_ERRORS
                WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
                  AND NAME='FNC_BUSCA_TAG_XML_GERAL')=0
         THEN 'CARD09_POSVALIDADO_SEM_DIVERGENCIAS'
         ELSE 'CARD09_REVISAR_DIVERGENCIAS'
       END AS STATUS_CARD09
  FROM DUAL;

PROMPT === CARD 09 - POS-VALIDACAO CONCLUIDA ===
SPOOL OFF
