-- Diagnostico read-only da atividade CMV/CPV acima do faturamento.
-- Nao altera TGFTOP, TGFCUS, TGFCAB, TGFITE ou qualquer objeto do banco.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET SQLBLANKLINES ON
SET LONG 1000000
SET LONGCHUNKSIZE 1000000
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

SPOOL "/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Clientes/INSTITUTO MOREIRA SALLES/Logs/34_Atividade_CMV_maior_faturamento_Diagnostico_20260915.log"

PROMPT === ATIVIDADE CMV MAIOR QUE FATURAMENTO - DIAGNOSTICO IMS ===
SELECT SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AS CURRENT_SCHEMA,
       SYS_CONTEXT('USERENV','SESSION_USER') AS SESSION_USER,
       SYS_CONTEXT('USERENV','SERVICE_NAME') AS SERVICE_NAME,
       SYSTIMESTAMP AS DH_DIAGNOSTICO
  FROM DUAL;

PROMPT === TOPS 1451 1452 1458 - TODAS AS VERSOES HISTORICAS ===
SELECT T.CODTIPOPER,
       T.DHALTER,
       T.DESCROPER,
       T.TIPMOV,
       T.PRECIFICA,
       T.ATUALEST,
       T.ATUALFIN,
       T.TIPATUALFIN,
       T.CODMODDOC,
       T.GOLSINAL,
       T.ANALISEGIRO,
       T.ATUALULTIMACOMP,
       T.ATUALULTIMAVEND,
       COUNT(DISTINCT C.NUNOTA) AS QTD_NOTAS_COMPRA,
       COUNT(I.CODPROD) AS QTD_ITENS_COMPRA,
       ROUND(AVG(I.VLRUNIT),2) AS VLRUNIT_MEDIO_COMPRA
  FROM TGFTOP T
  LEFT JOIN TGFCAB C
    ON C.CODTIPOPER=T.CODTIPOPER
   AND C.DHTIPOPER=T.DHALTER
   AND C.TIPMOV='C'
  LEFT JOIN TGFITE I
    ON I.NUNOTA=C.NUNOTA
 WHERE T.CODTIPOPER IN (1451,1452,1458)
 GROUP BY T.CODTIPOPER,T.DHALTER,T.DESCROPER,T.TIPMOV,T.PRECIFICA,
          T.ATUALEST,T.ATUALFIN,T.TIPATUALFIN,T.CODMODDOC,T.GOLSINAL,
          T.ANALISEGIRO,T.ATUALULTIMACOMP,T.ATUALULTIMAVEND
 ORDER BY T.CODTIPOPER,T.DHALTER;

PROMPT === PRODUTO DE REFERENCIA 2237205929 - MEDIA POR TOP ===
SELECT Q.TIPMOV,
       Q.CODTIPOPER,
       Q.DESCROPER,
       Q.CODPROD,
       Q.DESCRPROD,
       ROUND(Q.VLRUNITMEDIO,2) AS VLRUNITMEDIO,
       Q.CODVOL,
       Q.AD_ORIGDEPLOY
  FROM (
        SELECT C.TIPMOV,C.CODTIPOPER,T.DESCROPER,I.CODPROD,P.DESCRPROD,
               AVG(I.VLRUNIT) AS VLRUNITMEDIO,I.CODVOL,C.AD_ORIGDEPLOY
          FROM TGFITE I
          JOIN TGFPRO P ON P.CODPROD=I.CODPROD
          JOIN TGFCAB C ON C.NUNOTA=I.NUNOTA AND C.TIPMOV='C'
          JOIN TGFTOP T ON T.CODTIPOPER=C.CODTIPOPER
                        AND T.DHALTER=C.DHTIPOPER
                        AND T.PRECIFICA<>'N'
         GROUP BY C.TIPMOV,C.CODTIPOPER,T.DESCROPER,I.CODPROD,
                  P.DESCRPROD,I.CODVOL,C.AD_ORIGDEPLOY
        UNION ALL
        SELECT C.TIPMOV,C.CODTIPOPER,T.DESCROPER,I.CODPROD,P.DESCRPROD,
               AVG(I.VLRUNIT) AS VLRUNITMEDIO,I.CODVOL,C.AD_ORIGDEPLOY
          FROM TGFITE I
          JOIN TGFPRO P ON P.CODPROD=I.CODPROD
          JOIN TGFCAB C ON C.NUNOTA=I.NUNOTA AND C.TIPMOV='V'
          JOIN TGFTOP T ON T.CODTIPOPER=C.CODTIPOPER
                        AND T.DHALTER=C.DHTIPOPER
                        AND T.GOLSINAL=-1
         GROUP BY C.TIPMOV,C.CODTIPOPER,T.DESCROPER,I.CODPROD,
                  P.DESCRPROD,I.CODVOL,C.AD_ORIGDEPLOY
       ) Q
 WHERE Q.CODPROD=2237205929
 ORDER BY Q.CODPROD,Q.CODVOL,Q.TIPMOV,Q.CODTIPOPER;

PROMPT === PRODUTOS COM MEDIA DE COMPRA ACIMA DA MEDIA DE VENDA ===
WITH MOVIMENTOS AS (
  SELECT 'C' AS TIPMOV,I.CODPROD,P.DESCRPROD,I.CODVOL,
         C.CODTIPOPER,T.DESCROPER,I.VLRUNIT
    FROM TGFITE I
    JOIN TGFPRO P ON P.CODPROD=I.CODPROD
    JOIN TGFCAB C ON C.NUNOTA=I.NUNOTA AND C.TIPMOV='C'
    JOIN TGFTOP T ON T.CODTIPOPER=C.CODTIPOPER
                  AND T.DHALTER=C.DHTIPOPER
                  AND T.PRECIFICA<>'N'
  UNION ALL
  SELECT 'V' AS TIPMOV,I.CODPROD,P.DESCRPROD,I.CODVOL,
         C.CODTIPOPER,T.DESCROPER,I.VLRUNIT
    FROM TGFITE I
    JOIN TGFPRO P ON P.CODPROD=I.CODPROD
    JOIN TGFCAB C ON C.NUNOTA=I.NUNOTA AND C.TIPMOV='V'
    JOIN TGFTOP T ON T.CODTIPOPER=C.CODTIPOPER
                  AND T.DHALTER=C.DHTIPOPER
                  AND T.GOLSINAL=-1
), RESUMO AS (
  SELECT CODPROD,DESCRPROD,CODVOL,
         AVG(CASE WHEN TIPMOV='C' THEN VLRUNIT END) AS MEDIA_COMPRA,
         AVG(CASE WHEN TIPMOV='V' THEN VLRUNIT END) AS MEDIA_VENDA,
         COUNT(CASE WHEN TIPMOV='C' THEN 1 END) AS ITENS_COMPRA,
         COUNT(CASE WHEN TIPMOV='V' THEN 1 END) AS ITENS_VENDA,
         COUNT(DISTINCT CASE WHEN TIPMOV='C' THEN CODTIPOPER END) AS TOPS_COMPRA,
         COUNT(DISTINCT CASE WHEN TIPMOV='V' THEN CODTIPOPER END) AS TOPS_VENDA
    FROM MOVIMENTOS
   GROUP BY CODPROD,DESCRPROD,CODVOL
)
SELECT CODPROD,DESCRPROD,CODVOL,
       ROUND(MEDIA_COMPRA,2) AS MEDIA_COMPRA,
       ROUND(MEDIA_VENDA,2) AS MEDIA_VENDA,
       ROUND(MEDIA_COMPRA-MEDIA_VENDA,2) AS DIFERENCA,
       ITENS_COMPRA,ITENS_VENDA,TOPS_COMPRA,TOPS_VENDA
  FROM RESUMO
 WHERE MEDIA_COMPRA>MEDIA_VENDA
 ORDER BY DIFERENCA DESC,CODPROD,CODVOL;

PROMPT === LISTA CODPROD PARA FILTRO IN ===
WITH MOVIMENTOS AS (
  SELECT 'C' AS TIPMOV,I.CODPROD,I.CODVOL,I.VLRUNIT
    FROM TGFITE I
    JOIN TGFCAB C ON C.NUNOTA=I.NUNOTA AND C.TIPMOV='C'
    JOIN TGFTOP T ON T.CODTIPOPER=C.CODTIPOPER
                  AND T.DHALTER=C.DHTIPOPER
                  AND T.PRECIFICA<>'N'
  UNION ALL
  SELECT 'V' AS TIPMOV,I.CODPROD,I.CODVOL,I.VLRUNIT
    FROM TGFITE I
    JOIN TGFCAB C ON C.NUNOTA=I.NUNOTA AND C.TIPMOV='V'
    JOIN TGFTOP T ON T.CODTIPOPER=C.CODTIPOPER
                  AND T.DHALTER=C.DHTIPOPER
                  AND T.GOLSINAL=-1
), CANDIDATOS AS (
  SELECT CODPROD,CODVOL
    FROM MOVIMENTOS
   GROUP BY CODPROD,CODVOL
  HAVING AVG(CASE WHEN TIPMOV='C' THEN VLRUNIT END)
       > AVG(CASE WHEN TIPMOV='V' THEN VLRUNIT END)
)
SELECT RTRIM(XMLAGG(XMLELEMENT(E,TO_CHAR(CODPROD)||',') ORDER BY CODPROD)
              .EXTRACT('//text()').getClobVal(),',') AS CODPROD_IN
  FROM (SELECT DISTINCT CODPROD FROM CANDIDATOS);

PROMPT === TOPS DE COMPRA ACIMA DA MEDIA DE VENDA DO PRODUTO ===
WITH COMPRAS AS (
  SELECT I.CODPROD,P.DESCRPROD,I.CODVOL,C.CODTIPOPER,T.DESCROPER,
         AVG(I.VLRUNIT) AS MEDIA_TOP_COMPRA,COUNT(*) AS ITENS_TOP_COMPRA
    FROM TGFITE I
    JOIN TGFPRO P ON P.CODPROD=I.CODPROD
    JOIN TGFCAB C ON C.NUNOTA=I.NUNOTA AND C.TIPMOV='C'
    JOIN TGFTOP T ON T.CODTIPOPER=C.CODTIPOPER
                  AND T.DHALTER=C.DHTIPOPER
                  AND T.PRECIFICA<>'N'
   GROUP BY I.CODPROD,P.DESCRPROD,I.CODVOL,C.CODTIPOPER,T.DESCROPER
), VENDAS AS (
  SELECT I.CODPROD,I.CODVOL,AVG(I.VLRUNIT) AS MEDIA_VENDA
    FROM TGFITE I
    JOIN TGFCAB C ON C.NUNOTA=I.NUNOTA AND C.TIPMOV='V'
    JOIN TGFTOP T ON T.CODTIPOPER=C.CODTIPOPER
                  AND T.DHALTER=C.DHTIPOPER
                  AND T.GOLSINAL=-1
   GROUP BY I.CODPROD,I.CODVOL
)
SELECT C.CODPROD,C.DESCRPROD,C.CODVOL,C.CODTIPOPER,C.DESCROPER,
       ROUND(C.MEDIA_TOP_COMPRA,2) AS MEDIA_TOP_COMPRA,
       ROUND(V.MEDIA_VENDA,2) AS MEDIA_VENDA,
       ROUND(C.MEDIA_TOP_COMPRA-V.MEDIA_VENDA,2) AS DIFERENCA,
       C.ITENS_TOP_COMPRA
  FROM COMPRAS C
  JOIN VENDAS V ON V.CODPROD=C.CODPROD AND V.CODVOL=C.CODVOL
 WHERE C.MEDIA_TOP_COMPRA>V.MEDIA_VENDA
 ORDER BY DIFERENCA DESC,C.CODPROD,C.CODVOL,C.CODTIPOPER;

PROMPT === OBJETOS DO BANCO COM POSSIVEL ROTINA DE CUSTO OU GOL ===
SELECT OBJECT_TYPE,OBJECT_NAME,STATUS
  FROM ALL_OBJECTS
 WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
   AND (UPPER(OBJECT_NAME) LIKE '%CUST%'
     OR UPPER(OBJECT_NAME) LIKE '%CMV%'
     OR UPPER(OBJECT_NAME) LIKE '%CPV%'
     OR UPPER(OBJECT_NAME) LIKE '%GOL%'
     OR UPPER(OBJECT_NAME) LIKE '%CONSOL%')
 ORDER BY OBJECT_TYPE,OBJECT_NAME;

PROMPT === ROTINAS COM REFERENCIA A TGFCUS, CUSTO OU CONSOLIDACAO ===
SELECT S.NAME,S.TYPE,O.STATUS,COUNT(*) AS LINHAS_ENCONTRADAS
  FROM ALL_SOURCE S
  LEFT JOIN ALL_OBJECTS O
    ON O.OWNER=S.OWNER AND O.OBJECT_NAME=S.NAME AND O.OBJECT_TYPE=S.TYPE
 WHERE S.OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
   AND (UPPER(S.TEXT) LIKE '%TGFCUS%'
     OR UPPER(S.TEXT) LIKE '%CUSSEMICM%'
     OR UPPER(S.TEXT) LIKE '%CUSTO%'
     OR UPPER(S.TEXT) LIKE '%CONSOLID%'
     OR UPPER(S.TEXT) LIKE '%GERENTE%ONLINE%'
     OR UPPER(S.TEXT) LIKE '%GOL%')
 GROUP BY S.NAME,S.TYPE,O.STATUS
 ORDER BY S.NAME,S.TYPE;

PROMPT === PROCEDURES/FUNCTIONS/PACKAGES POR NOME ===
SELECT OBJECT_TYPE,OBJECT_NAME,PROCEDURE_NAME
  FROM ALL_PROCEDURES
 WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
   AND (UPPER(OBJECT_NAME) LIKE '%CUST%'
     OR UPPER(OBJECT_NAME) LIKE '%CMV%'
     OR UPPER(OBJECT_NAME) LIKE '%CPV%'
     OR UPPER(OBJECT_NAME) LIKE '%GOL%'
     OR UPPER(OBJECT_NAME) LIKE '%CONSOL%'
     OR UPPER(PROCEDURE_NAME) LIKE '%CUST%'
     OR UPPER(PROCEDURE_NAME) LIKE '%CONSOL%'
     OR UPPER(PROCEDURE_NAME) LIKE '%GOL%')
 ORDER BY OBJECT_TYPE,OBJECT_NAME,PROCEDURE_NAME;

PROMPT === TRIGGERS SOBRE TGFCUS E MOVIMENTOS ===
SELECT OWNER,TRIGGER_NAME,TABLE_NAME,STATUS,TRIGGERING_EVENT,TRIGGER_TYPE
  FROM ALL_TRIGGERS
 WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
   AND TABLE_NAME IN ('TGFCUS','TGFITE','TGFCAB')
 ORDER BY TABLE_NAME,TRIGGER_NAME;

PROMPT === FIM DIAGNOSTICO CMV/CPV ===
SPOOL OFF
