SET ECHO ON
SET FEEDBACK ON
SET HEADING ON
SET LINESIZE 240
SET PAGESIZE 500
SET LONG 100000
SET LONGCHUNKSIZE 100000
SET TAB OFF
SET DEFINE OFF
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

SPOOL "7 - QA2/Clientes/INSTITUTO MOREIRA SALLES/Logs/35_Atividade_CMV_maior_faturamento_Objetos_ReadOnly_20260915.log"

PROMPT === ATIVIDADE CMV MAIOR QUE FATURAMENTO - OBJETOS READ-ONLY IMS ===

SELECT SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AS CURRENT_SCHEMA,
       SYS_CONTEXT('USERENV','SESSION_USER') AS SESSION_USER,
       SYS_CONTEXT('USERENV','SERVICE_NAME') AS SERVICE_NAME,
       SYSTIMESTAMP AS DH_DIAGNOSTICO
  FROM DUAL;

PROMPT === ASSINATURAS DOS PROCEDIMENTOS DE CUSTO E GOL ===

SELECT OWNER, OBJECT_NAME, PROCEDURE_NAME, OVERLOAD, POSITION,
       ARGUMENT_NAME, IN_OUT, DATA_TYPE, DATA_LENGTH, DEFAULTED
  FROM ALL_ARGUMENTS
 WHERE OWNER = 'SANKHYA'
   AND OBJECT_NAME IN (
       'STP_CALCCUSTOMEDIOPRODGENERICO',
       'STP_CALCULARCUSTOMEDIODIA',
       'STP_CALCULARCUSTOMEDIOFAMILIA',
       'STP_CALCULARCUSTOPRODGENERICO',
       'STP_PROCESSOATUALCUSTO',
       'STP_EFETIVA_CONSOLIDACAO_GOL',
       'PFCM_CONSOLIDACAO',
       'SNK_MATGIRCALCTOTAIS'
   )
 ORDER BY OBJECT_NAME, PROCEDURE_NAME, OVERLOAD, POSITION;

PROMPT === DEPENDENCIAS DOS PROCEDIMENTOS ===

SELECT OWNER, NAME, TYPE, REFERENCED_OWNER, REFERENCED_NAME,
       REFERENCED_TYPE, DEPENDENCY_TYPE
  FROM ALL_DEPENDENCIES
 WHERE OWNER = 'SANKHYA'
   AND NAME IN (
       'STP_CALCCUSTOMEDIOPRODGENERICO',
       'STP_CALCULARCUSTOMEDIODIA',
       'STP_CALCULARCUSTOMEDIOFAMILIA',
       'STP_CALCULARCUSTOPRODGENERICO',
       'STP_PROCESSOATUALCUSTO',
       'STP_EFETIVA_CONSOLIDACAO_GOL',
       'PFCM_CONSOLIDACAO',
       'SNK_MATGIRCALCTOTAIS'
   )
 ORDER BY NAME, REFERENCED_OWNER, REFERENCED_NAME;

PROMPT === FONTE DOS PROCEDIMENTOS DE CUSTO - LINHAS RELEVANTES ===

SELECT OWNER, NAME, TYPE, LINE, TEXT
  FROM ALL_SOURCE
 WHERE OWNER = 'SANKHYA'
   AND NAME IN (
       'STP_CALCCUSTOMEDIOPRODGENERICO',
       'STP_CALCULARCUSTOMEDIODIA',
       'STP_CALCULARCUSTOMEDIOFAMILIA',
       'STP_CALCULARCUSTOPRODGENERICO',
       'STP_PROCESSOATUALCUSTO'
   )
   AND (
       UPPER(TEXT) LIKE '%TGFCUS%'
       OR UPPER(TEXT) LIKE '%CODPROD%'
       OR UPPER(TEXT) LIKE '%CUSSEMICM%'
       OR UPPER(TEXT) LIKE '%DTATUAL%'
       OR UPPER(TEXT) LIKE '%CALC%'
       OR UPPER(TEXT) LIKE '%CUSTO%'
   )
 ORDER BY NAME, TYPE, LINE;

PROMPT === FONTE DOS PROCEDIMENTOS DE CONSOLIDACAO GOL - LINHAS RELEVANTES ===

SELECT OWNER, NAME, TYPE, LINE, TEXT
  FROM ALL_SOURCE
 WHERE OWNER = 'SANKHYA'
   AND NAME IN (
       'STP_EFETIVA_CONSOLIDACAO_GOL',
       'PFCM_CONSOLIDACAO',
       'SNK_MATGIRCALCTOTAIS'
   )
   AND (
       UPPER(TEXT) LIKE '%GOL%'
       OR UPPER(TEXT) LIKE '%CONSOLID%'
       OR UPPER(TEXT) LIKE '%TGFCMV%'
       OR UPPER(TEXT) LIKE '%TFPCMV%'
       OR UPPER(TEXT) LIKE '%TCB%'
       OR UPPER(TEXT) LIKE '%CODUSU%'
   )
 ORDER BY NAME, TYPE, LINE;

PROMPT === REFERENCIAS A ROTINAS DE CALCULO E CONSOLIDACAO ===

SELECT OWNER, NAME, TYPE, LINE, TEXT
  FROM ALL_SOURCE
 WHERE OWNER = 'SANKHYA'
   AND (
       UPPER(TEXT) LIKE '%STP_CALCULARCUSTOPRODGENERICO%'
       OR UPPER(TEXT) LIKE '%STP_CALCCUSTOMEDIOPRODGENERICO%'
       OR UPPER(TEXT) LIKE '%STP_EFETIVA_CONSOLIDACAO_GOL%'
       OR UPPER(TEXT) LIKE '%PFCM_CONSOLIDACAO%'
   )
 ORDER BY NAME, TYPE, LINE;

PROMPT === FIM OBJETOS READ-ONLY ===

SPOOL OFF
