SET ECHO ON
SET FEEDBACK ON
SET HEADING ON
SET LINESIZE 240
SET PAGESIZE 500
SET LONG 100000
SET LONGCHUNKSIZE 100000
SET TAB OFF
SET DEFINE OFF
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

SPOOL "/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Clientes/INSTITUTO MOREIRA SALLES/Logs/36_Atividade_CMV_maior_faturamento_Objetos_Foco_ReadOnly_20260915.log"

PROMPT === ATIVIDADE CMV MAIOR QUE FATURAMENTO - OBJETOS FOCO READ-ONLY IMS ===

SELECT SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AS CURRENT_SCHEMA,
       SYS_CONTEXT('USERENV','SESSION_USER') AS SESSION_USER,
       SYS_CONTEXT('USERENV','SERVICE_NAME') AS SERVICE_NAME,
       SYSTIMESTAMP AS DH_DIAGNOSTICO
  FROM DUAL;

PROMPT === INVENTARIO DOS OBJETOS ===

SELECT OWNER, OBJECT_NAME, OBJECT_TYPE, STATUS, LAST_DDL_TIME
  FROM ALL_OBJECTS
 WHERE OWNER = 'SANKHYA'
   AND OBJECT_NAME IN (
       'STP_CALCCUSTOMEDIOPRODGENERICO',
       'STP_CALCULARCUSTOMEDIODIA',
       'STP_CALCULARCUSTOMEDIOFAMILIA',
       'STP_CALCULARCUSTOPRODGENERICO',
       'STP_PROCESSOATUALCUSTO',
       'STP_EFETIVA_CONSOLIDACAO_GOL',
       'PFCM_CONSOLIDACAO',
       'SNK_MATGIRCALCTOTAIS'
   )
 ORDER BY OBJECT_NAME, OBJECT_TYPE;

PROMPT === ASSINATURAS DOS OBJETOS ===

SELECT OWNER, PACKAGE_NAME, OBJECT_NAME, PROCEDURE_NAME, OVERLOAD,
       SUBPROGRAM_ID, SEQUENCE, POSITION, ARGUMENT_NAME, IN_OUT,
       DATA_TYPE, DATA_LENGTH, DEFAULTED
  FROM ALL_ARGUMENTS
 WHERE OWNER = 'SANKHYA'
   AND OBJECT_NAME IN (
       'STP_CALCCUSTOMEDIOPRODGENERICO',
       'STP_CALCULARCUSTOMEDIODIA',
       'STP_CALCULARCUSTOMEDIOFAMILIA',
       'STP_CALCULARCUSTOPRODGENERICO',
       'STP_PROCESSOATUALCUSTO',
       'STP_EFETIVA_CONSOLIDACAO_GOL',
       'PFCM_CONSOLIDACAO',
       'SNK_MATGIRCALCTOTAIS'
   )
 ORDER BY OBJECT_NAME, PACKAGE_NAME, PROCEDURE_NAME, OVERLOAD,
          SUBPROGRAM_ID, SEQUENCE;

PROMPT === FONTE DOS OBJETOS DE CUSTO - LINHAS RELEVANTES ===

SELECT OWNER, NAME, TYPE, LINE, TEXT
  FROM ALL_SOURCE
 WHERE OWNER = 'SANKHYA'
   AND NAME IN (
       'STP_CALCCUSTOMEDIOPRODGENERICO',
       'STP_CALCULARCUSTOMEDIODIA',
       'STP_CALCULARCUSTOMEDIOFAMILIA',
       'STP_CALCULARCUSTOPRODGENERICO',
       'STP_PROCESSOATUALCUSTO'
   )
   AND REGEXP_LIKE(
       UPPER(TEXT),
       'TGFCUS|CODPROD|CUSSEMICM|DTATUAL|CALCULARCUSTO|CALCCUSTOMEDIO|PROCESSOATUALCUSTO|DELETE|INSERT|UPDATE|COMMIT|ROLLBACK'
   )
 ORDER BY NAME, TYPE, LINE;

PROMPT === FONTE DOS OBJETOS DE GOL - LINHAS RELEVANTES ===

SELECT OWNER, NAME, TYPE, LINE, TEXT
  FROM ALL_SOURCE
 WHERE OWNER = 'SANKHYA'
   AND NAME IN (
       'STP_EFETIVA_CONSOLIDACAO_GOL',
       'PFCM_CONSOLIDACAO',
       'SNK_MATGIRCALCTOTAIS'
   )
   AND REGEXP_LIKE(
       UPPER(TEXT),
       'GOL|CONSOLID|TGFCMV|TFPCMV|TCB|CODUSU|DELETE|INSERT|UPDATE|COMMIT|ROLLBACK'
   )
 ORDER BY NAME, TYPE, LINE;

PROMPT === CHAMADAS DESTAS ROTINAS EM OUTROS OBJETOS ===

SELECT OWNER, NAME, TYPE, LINE, TEXT
  FROM ALL_SOURCE
 WHERE OWNER = 'SANKHYA'
   AND REGEXP_LIKE(
       UPPER(TEXT),
       'STP_CALCULARCUSTOPRODGENERICO|STP_CALCCUSTOMEDIOPRODGENERICO|STP_EFETIVA_CONSOLIDACAO_GOL|PFCM_CONSOLIDACAO|SNK_MATGIRCALCTOTAIS'
   )
 ORDER BY NAME, TYPE, LINE;

PROMPT === FIM OBJETOS FOCO READ-ONLY ===

SPOOL OFF
