SET ECHO ON
SET FEEDBACK ON
SET HEADING ON
SET LINESIZE 240
SET PAGESIZE 200
SET TAB OFF
SET DEFINE OFF
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

SPOOL "/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Clientes/INSTITUTO MOREIRA SALLES/Logs/37_Atividade_CMV_maior_faturamento_Assinaturas_ReadOnly_20260915.log"

PROMPT === ATIVIDADE CMV MAIOR QUE FATURAMENTO - ASSINATURAS READ-ONLY IMS ===

SELECT SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AS CURRENT_SCHEMA,
       SYS_CONTEXT('USERENV','SESSION_USER') AS SESSION_USER,
       SYS_CONTEXT('USERENV','SERVICE_NAME') AS SERVICE_NAME,
       SYSTIMESTAMP AS DH_DIAGNOSTICO
  FROM DUAL;

PROMPT === OBJETOS DE CUSTO ===
SELECT OWNER, OBJECT_NAME, OBJECT_TYPE, STATUS
  FROM ALL_OBJECTS
 WHERE OWNER = 'SANKHYA'
   AND OBJECT_NAME IN (
       'STP_CALCCUSTOMEDIOPRODGENERICO',
       'STP_CALCULARCUSTOMEDIODIA',
       'STP_CALCULARCUSTOMEDIOFAMILIA',
       'STP_CALCULARCUSTOPRODGENERICO',
       'STP_PROCESSOATUALCUSTO'
   )
 ORDER BY OBJECT_NAME, OBJECT_TYPE;

PROMPT === ASSINATURA STP_CALCCUSTOMEDIOPRODGENERICO ===
SELECT OWNER, PACKAGE_NAME, OBJECT_NAME, PROCEDURE_NAME, OVERLOAD,
       SUBPROGRAM_ID, SEQUENCE, POSITION, ARGUMENT_NAME, IN_OUT,
       DATA_TYPE, DATA_LENGTH, DEFAULTED
  FROM ALL_ARGUMENTS
 WHERE OWNER = 'SANKHYA'
   AND OBJECT_NAME = 'STP_CALCCUSTOMEDIOPRODGENERICO'
 ORDER BY PACKAGE_NAME, PROCEDURE_NAME, OVERLOAD, SUBPROGRAM_ID, SEQUENCE;

PROMPT === ASSINATURA STP_CALCULARCUSTOPRODGENERICO ===
SELECT OWNER, PACKAGE_NAME, OBJECT_NAME, PROCEDURE_NAME, OVERLOAD,
       SUBPROGRAM_ID, SEQUENCE, POSITION, ARGUMENT_NAME, IN_OUT,
       DATA_TYPE, DATA_LENGTH, DEFAULTED
  FROM ALL_ARGUMENTS
 WHERE OWNER = 'SANKHYA'
   AND OBJECT_NAME = 'STP_CALCULARCUSTOPRODGENERICO'
 ORDER BY PACKAGE_NAME, PROCEDURE_NAME, OVERLOAD, SUBPROGRAM_ID, SEQUENCE;

PROMPT === ASSINATURA STP_PROCESSOATUALCUSTO ===
SELECT OWNER, PACKAGE_NAME, OBJECT_NAME, PROCEDURE_NAME, OVERLOAD,
       SUBPROGRAM_ID, SEQUENCE, POSITION, ARGUMENT_NAME, IN_OUT,
       DATA_TYPE, DATA_LENGTH, DEFAULTED
  FROM ALL_ARGUMENTS
 WHERE OWNER = 'SANKHYA'
   AND OBJECT_NAME = 'STP_PROCESSOATUALCUSTO'
 ORDER BY PACKAGE_NAME, PROCEDURE_NAME, OVERLOAD, SUBPROGRAM_ID, SEQUENCE;

PROMPT === FIM ASSINATURAS READ-ONLY ===
SPOOL OFF
