SET ECHO ON
SET FEEDBACK ON
SET HEADING ON
SET LINESIZE 240
SET PAGESIZE 200
SET LONG 100000
SET LONGCHUNKSIZE 100000
SET TAB OFF
SET DEFINE OFF
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

SPOOL "/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Clientes/INSTITUTO MOREIRA SALLES/Logs/38_Atividade_CMV_maior_faturamento_Rotina_Custo_01_ReadOnly_20260915.log"

PROMPT === ATIVIDADE CMV MAIOR QUE FATURAMENTO - ROTINA DE CUSTO 01 READ-ONLY IMS ===

SELECT SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AS CURRENT_SCHEMA,
       SYS_CONTEXT('USERENV','SESSION_USER') AS SESSION_USER,
       SYS_CONTEXT('USERENV','SERVICE_NAME') AS SERVICE_NAME,
       SYSTIMESTAMP AS DH_DIAGNOSTICO
  FROM DUAL;

PROMPT === OBJETO ===
SELECT OWNER, OBJECT_NAME, OBJECT_TYPE, STATUS
  FROM ALL_OBJECTS
 WHERE OWNER = 'SANKHYA'
   AND OBJECT_NAME = 'STP_CALCCUSTOMEDIOPRODGENERICO';

PROMPT === ASSINATURA ===
SELECT OWNER, PACKAGE_NAME, OBJECT_NAME, PROCEDURE_NAME, OVERLOAD,
       SUBPROGRAM_ID, SEQUENCE, POSITION, ARGUMENT_NAME, IN_OUT,
       DATA_TYPE, DATA_LENGTH, DEFAULTED
  FROM ALL_ARGUMENTS
 WHERE OWNER = 'SANKHYA'
   AND OBJECT_NAME = 'STP_CALCCUSTOMEDIOPRODGENERICO'
   AND ROWNUM <= 100;

PROMPT === FONTE ===
SELECT OWNER, NAME, TYPE, LINE, TEXT
  FROM ALL_SOURCE
 WHERE OWNER = 'SANKHYA'
   AND NAME = 'STP_CALCCUSTOMEDIOPRODGENERICO'
   AND ROWNUM <= 250;

PROMPT === FIM ROTINA DE CUSTO 01 ===
SPOOL OFF
