SET ECHO ON
SET FEEDBACK ON
SET HEADING ON
SET LINESIZE 240
SET PAGESIZE 200
SET LONG 100000
SET LONGCHUNKSIZE 100000
SET TAB OFF
SET DEFINE OFF
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

SPOOL "/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Clientes/INSTITUTO MOREIRA SALLES/Logs/40_Atividade_CMV_maior_faturamento_Rotina_Custo_02_ReadOnly_20260915.log"

PROMPT === ATIVIDADE CMV MAIOR QUE FATURAMENTO - ROTINA DE CUSTO 02 READ-ONLY IMS ===

SELECT LISTAGG(ARGUMENT_NAME||'|'||POSITION||'|'||IN_OUT||'|'||DATA_TYPE||'|'||DEFAULTED,'; ') WITHIN GROUP(ORDER BY POSITION) AS ASSINATURA
  FROM ALL_ARGUMENTS
 WHERE OWNER='SANKHYA' AND OBJECT_NAME='STP_CALCULARCUSTOPRODGENERICO';

SELECT LINE||'|'||TEXT AS FONTE
  FROM ALL_SOURCE
 WHERE OWNER='SANKHYA' AND NAME='STP_CALCULARCUSTOPRODGENERICO'
 ORDER BY LINE;

PROMPT === FIM ROTINA DE CUSTO 02 ===
SPOOL OFF
