-- Atividade: CMV sem ICMS acima do faturamento
-- Fase: localizacao read-only dos objetos que alimentam o GOL
-- Base: INSTITUTO MOREIRA SALLES
-- Execucao: 2026-09-15

SPOOL "/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Clientes/INSTITUTO MOREIRA SALLES/Logs/45_Atividade_CMV_maior_faturamento_Referencias_GOL_ReadOnly_20260915.log"

SELECT OWNER, NAME, TYPE, MIN(LINE) AS PRIMEIRA_LINHA, MAX(LINE) AS ULTIMA_LINHA, COUNT(*) AS OCORRENCIAS
  FROM ALL_SOURCE
 WHERE OWNER='SANKHYA'
   AND (UPPER(TEXT) LIKE '%TGFMGC_TMP%'
        OR UPPER(TEXT) LIKE '%STP_EFETIVA_CONSOLIDACAO_GOL%'
        OR UPPER(TEXT) LIKE '%TGFMGC%')
 GROUP BY OWNER, NAME, TYPE
 ORDER BY NAME, TYPE;

SELECT OWNER, NAME, TYPE, LINE, TEXT
  FROM ALL_SOURCE
 WHERE OWNER='SANKHYA'
   AND (UPPER(TEXT) LIKE '%TGFMGC_TMP%'
        OR UPPER(TEXT) LIKE '%STP_EFETIVA_CONSOLIDACAO_GOL%')
 ORDER BY NAME, TYPE, LINE;

SPOOL OFF
