-- Atividade: CMV sem ICMS acima do faturamento
-- Fase: investigacao read-only das origens do recalculo e do GOL
-- Base: INSTITUTO MOREIRA SALLES
-- Execucao: 2026-09-15

SPOOL "/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Clientes/INSTITUTO MOREIRA SALLES/Logs/46_Atividade_CMV_maior_faturamento_Origens_ReadOnly_20260915.log"

SELECT OWNER, NAME, TYPE, MIN(LINE) AS PRIMEIRA_LINHA, MAX(LINE) AS ULTIMA_LINHA, COUNT(*) AS OCORRENCIAS
  FROM ALL_SOURCE
 WHERE OWNER='SANKHYA'
   AND (UPPER(TEXT) LIKE '%STP_CALCULARCUSTOMEDIODIA%'
        OR UPPER(TEXT) LIKE '%STP_CALCCUSTOMEDIOPRODGENERICO%'
        OR UPPER(TEXT) LIKE '%STP_CALCULARCUSTOPRODGENERICO%'
        OR UPPER(TEXT) LIKE '%TGFMGC_TMP%')
 GROUP BY OWNER, NAME, TYPE
 ORDER BY NAME, TYPE;

SELECT OWNER, NAME, TYPE, REFERENCED_OWNER, REFERENCED_NAME, REFERENCED_TYPE
  FROM ALL_DEPENDENCIES
 WHERE OWNER='SANKHYA'
   AND (REFERENCED_NAME IN ('STP_CALCULARCUSTOMEDIODIA','STP_CALCCUSTOMEDIOPRODGENERICO','STP_CALCULARCUSTOPRODGENERICO','STP_EFETIVA_CONSOLIDACAO_GOL','TGFMGC_TMP')
        OR NAME IN ('STP_CALCULARCUSTOMEDIODIA','STP_CALCCUSTOMEDIOPRODGENERICO','STP_CALCULARCUSTOPRODGENERICO','STP_EFETIVA_CONSOLIDACAO_GOL'))
 ORDER BY NAME, REFERENCED_NAME;

SELECT OWNER, OBJECT_NAME, OBJECT_TYPE, STATUS
  FROM ALL_OBJECTS
 WHERE OWNER='SANKHYA'
   AND OBJECT_NAME IN ('TGFMGC_TMP','TGFMGC','STP_EFETIVA_CONSOLIDACAO_GOL');

SELECT OWNER, TRIGGER_NAME, TABLE_NAME, STATUS, TRIGGERING_EVENT
  FROM ALL_TRIGGERS
 WHERE TABLE_OWNER='SANKHYA'
   AND TABLE_NAME IN ('TGFMGC_TMP','TGFMGC');

SPOOL OFF
