-- Atividade: CMV sem ICMS acima do faturamento
-- Fase: preflight read-only das TOPs que serao ajustadas
-- Base: INSTITUTO MOREIRA SALLES
-- Execucao: 2026-09-15
-- Nenhum DML/DDL nesta etapa.

SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET SQLBLANKLINES ON
SET LINESIZE 250
SET PAGESIZE 500
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

SPOOL "/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Clientes/INSTITUTO MOREIRA SALLES/Logs/51_Atividade_CMV_maior_faturamento_TOPs_Preflight_20260915.log"

PROMPT === CONTEXTO DA SESSAO ===
SELECT SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AS CURRENT_SCHEMA,
       SYS_CONTEXT('USERENV','SESSION_USER') AS SESSION_USER,
       SYS_CONTEXT('USERENV','SERVICE_NAME') AS SERVICE_NAME,
       SYSTIMESTAMP AS DH_PREFLIGHT
  FROM DUAL;

PROMPT === EXISTENCIA DO BACKUP RESERVADO PARA A EXECUCAO ===
SELECT OWNER,OBJECT_NAME,OBJECT_TYPE,STATUS
  FROM ALL_OBJECTS
 WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
   AND OBJECT_NAME='BKP_CMV_TOP_20260915_140624';

PROMPT === QUANTIDADE DE VERSOES E VALORES ATUAIS ===
SELECT CODTIPOPER,
       COUNT(*) AS VERSOES,
       SUM(CASE WHEN PRECIFICA='N' THEN 1 ELSE 0 END) AS PRECIFICA_N,
       SUM(CASE WHEN PRECIFICA='C' THEN 1 ELSE 0 END) AS PRECIFICA_C,
       SUM(CASE WHEN PRECIFICA IS NULL OR PRECIFICA NOT IN ('N','C') THEN 1 ELSE 0 END) AS PRECIFICA_OUTROS,
       MIN(DHALTER) AS PRIMEIRA_VERSAO,
       MAX(DHALTER) AS ULTIMA_VERSAO
  FROM TGFTOP
 WHERE CODTIPOPER IN (1451,1452,1458)
 GROUP BY CODTIPOPER
 ORDER BY CODTIPOPER;

PROMPT === TODAS AS VERSOES QUE SERAO COBERTAS PELO BACKUP ===
SELECT CODTIPOPER,DHALTER,DESCROPER,PRECIFICA,ATUALEST,ATUALFIN,
       ATUALULTIMACOMP,ATUALULTIMAVEND,GOLSINAL,
       ROWIDTOCHAR(ROWID) AS ROWID_ORIGINAL
  FROM TGFTOP
 WHERE CODTIPOPER IN (1451,1452,1458)
 ORDER BY CODTIPOPER,DHALTER;

PROMPT === TOP 1401 - REFERENCIA QUE DEVE PERMANECER INALTERADA ===
SELECT CODTIPOPER,
       COUNT(*) AS VERSOES,
       SUM(CASE WHEN PRECIFICA='N' THEN 1 ELSE 0 END) AS PRECIFICA_N,
       SUM(CASE WHEN PRECIFICA='C' THEN 1 ELSE 0 END) AS PRECIFICA_C,
       MIN(DHALTER) AS PRIMEIRA_VERSAO,
       MAX(DHALTER) AS ULTIMA_VERSAO
  FROM TGFTOP
 WHERE CODTIPOPER=1401
 GROUP BY CODTIPOPER;

PROMPT === RESTRICOES DE CHAVE/HISTORICO DE TGFTOP ===
SELECT C.CONSTRAINT_NAME,C.CONSTRAINT_TYPE,
       LISTAGG(CC.COLUMN_NAME,',') WITHIN GROUP(ORDER BY CC.POSITION) AS COLUNAS
  FROM ALL_CONSTRAINTS C
  JOIN ALL_CONS_COLUMNS CC
    ON CC.OWNER=C.OWNER AND CC.CONSTRAINT_NAME=C.CONSTRAINT_NAME
 WHERE C.OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
   AND C.TABLE_NAME='TGFTOP'
   AND C.CONSTRAINT_TYPE IN ('P','U')
 GROUP BY C.CONSTRAINT_NAME,C.CONSTRAINT_TYPE
 ORDER BY C.CONSTRAINT_NAME;

PROMPT === QUANTIDADE ESPERADA PARA O BACKUP E ALTERACAO ===
SELECT COUNT(*) AS VERSOES_ALVO,
       SUM(CASE WHEN NVL(PRECIFICA,'#')<>'N' THEN 1 ELSE 0 END) AS VERSOES_QUE_MUDARAO,
       SUM(CASE WHEN PRECIFICA='N' THEN 1 ELSE 0 END) AS VERSOES_JA_N
  FROM TGFTOP
 WHERE CODTIPOPER IN (1451,1452,1458);

SPOOL OFF
