-- Atividade: CMV sem ICMS acima do faturamento
-- Fase: backup persistente e ajuste de PRECIFICA nas TOPs 1451, 1452 e 1458
-- Base: INSTITUTO MOREIRA SALLES
-- ID da execucao: RMD_CMV_IMS_20260915_140624
-- A TOP 1401 nao faz parte do escopo e nao e alterada.

SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET SQLBLANKLINES ON
SET LINESIZE 250
SET PAGESIZE 500
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

SPOOL "/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Clientes/INSTITUTO MOREIRA SALLES/Logs/52_Atividade_CMV_maior_faturamento_TOPs_Execucao_20260915.log"

PROMPT === INICIO DA EXECUCAO CONTROLADA ===
SELECT SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AS CURRENT_SCHEMA,
       SYS_CONTEXT('USERENV','SESSION_USER') AS SESSION_USER,
       SYS_CONTEXT('USERENV','SERVICE_NAME') AS SERVICE_NAME,
       SYSTIMESTAMP AS DH_EXECUCAO,
       'RMD_CMV_IMS_20260915_140624' AS ID_EXECUCAO
  FROM DUAL;

PROMPT === PREFLIGHT DE SEGURANCA, ANTES DO BACKUP ===
DECLARE
  v_backup NUMBER;
  v_alvo NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_backup
    FROM ALL_OBJECTS
   WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
     AND OBJECT_NAME='BKP_CMV_TOP_20260915_140624';

  IF v_backup>0 THEN
    RAISE_APPLICATION_ERROR(-20351,
      'O backup BKP_CMV_TOP_20260915_140624 ja existe. A execucao foi interrompida para evitar sobreposicao.');
  END IF;

  SELECT COUNT(*) INTO v_alvo
    FROM TGFTOP
   WHERE CODTIPOPER IN (1451,1452,1458);

  IF v_alvo=0 THEN
    RAISE_APPLICATION_ERROR(-20352,
      'Nenhuma versao das TOPs 1451, 1452 ou 1458 foi encontrada.');
  END IF;

  DBMS_OUTPUT.PUT_LINE('PREFLIGHT_OK=SIM; VERSOES_ALVO='||v_alvo);
END;
/

PROMPT === CRIACAO DO BACKUP PERSISTENTE ===
CREATE TABLE BKP_CMV_TOP_20260915_140624 AS
SELECT CAST('RMD_CMV_IMS_20260915_140624' AS VARCHAR2(40)) AS ID_EXECUCAO,
       SYSTIMESTAMP AS DH_EXECUCAO,
       CAST(SYS_CONTEXT('USERENV','SESSION_USER') AS VARCHAR2(128)) AS USUARIO_EXECUCAO,
       ROWIDTOCHAR(T.ROWID) AS ROWID_ORIGINAL,
       T.*
  FROM TGFTOP T
 WHERE T.CODTIPOPER IN (1451,1452,1458);

PROMPT === VALIDACAO DO BACKUP ANTES DO UPDATE ===
SELECT ID_EXECUCAO,USUARIO_EXECUCAO,COUNT(*) AS REGISTROS_BACKUP,
       MIN(DH_EXECUCAO) AS DH_BACKUP,
       COUNT(DISTINCT CODTIPOPER) AS TOPS_BACKUP
  FROM BKP_CMV_TOP_20260915_140624
 GROUP BY ID_EXECUCAO,USUARIO_EXECUCAO;

DECLARE
  v_backup NUMBER;
  v_alvo NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_backup FROM BKP_CMV_TOP_20260915_140624;
  SELECT COUNT(*) INTO v_alvo FROM TGFTOP WHERE CODTIPOPER IN (1451,1452,1458);
  IF v_backup<>v_alvo THEN
    RAISE_APPLICATION_ERROR(-20353,
      'Quantidade do backup diverge da quantidade atual das TOPs alvo. Nenhum UPDATE sera aplicado.');
  END IF;
  DBMS_OUTPUT.PUT_LINE('BACKUP_OK=SIM; REGISTROS='||v_backup);
END;
/

PROMPT === ALTERACAO EXCLUSIVA DE PRECIFICA ===
UPDATE TGFTOP
   SET PRECIFICA='N'
 WHERE CODTIPOPER IN (1451,1452,1458)
   AND NVL(PRECIFICA,'#')<>'N';

PROMPT === VALIDACAO IMEDIATA E COMMIT ===
DECLARE
  v_bad NUMBER;
  v_updated NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_updated
    FROM BKP_CMV_TOP_20260915_140624 B
    JOIN TGFTOP T ON B.ROWID_ORIGINAL=ROWIDTOCHAR(T.ROWID)
   WHERE DECODE(B.PRECIFICA,T.PRECIFICA,1,0)=0;
  SELECT COUNT(*) INTO v_bad
    FROM TGFTOP
   WHERE CODTIPOPER IN (1451,1452,1458)
     AND NVL(PRECIFICA,'#')<>'N';

  IF v_bad>0 THEN
    RAISE_APPLICATION_ERROR(-20354,
      'Persistem versoes alvo com PRECIFICA diferente de N. O bloco sera revertido.');
  END IF;

  COMMIT;
  DBMS_OUTPUT.PUT_LINE('ID_EXECUCAO=RMD_CMV_IMS_20260915_140624');
  DBMS_OUTPUT.PUT_LINE('REGISTROS_ALTERADOS='||v_updated);
  DBMS_OUTPUT.PUT_LINE('TOPS_ALVO=1451,1452,1458');
  DBMS_OUTPUT.PUT_LINE('TOP_1401=FORA_DO_ESCOPO');
  DBMS_OUTPUT.PUT_LINE('STATUS=EXECUTADO_COMMIT');
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END;
/

PROMPT === CONTAGEM FINAL DAS TOPS ALVO ===
SELECT CODTIPOPER,
       COUNT(*) AS VERSOES,
       SUM(CASE WHEN PRECIFICA='N' THEN 1 ELSE 0 END) AS PRECIFICA_N,
       SUM(CASE WHEN NVL(PRECIFICA,'#')<>'N' THEN 1 ELSE 0 END) AS PENDENTES
  FROM TGFTOP
 WHERE CODTIPOPER IN (1451,1452,1458)
 GROUP BY CODTIPOPER
 ORDER BY CODTIPOPER;

PROMPT === REFERENCIA FINAL DA TOP 1401 ===
SELECT CODTIPOPER,COUNT(*) AS VERSOES,
       SUM(CASE WHEN PRECIFICA='N' THEN 1 ELSE 0 END) AS PRECIFICA_N,
       SUM(CASE WHEN PRECIFICA='C' THEN 1 ELSE 0 END) AS PRECIFICA_C
  FROM TGFTOP
 WHERE CODTIPOPER=1401
 GROUP BY CODTIPOPER;

SPOOL OFF
