-- Atividade: CMV sem ICMS acima do faturamento
-- Fase: pos-validacao read-only do ajuste das TOPs
-- Base: INSTITUTO MOREIRA SALLES
-- ID da execucao: RMD_CMV_IMS_20260915_140624

SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET SQLBLANKLINES ON
SET LINESIZE 250
SET PAGESIZE 500
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

SPOOL "/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Clientes/INSTITUTO MOREIRA SALLES/Logs/54_Atividade_CMV_maior_faturamento_TOPs_Posvalidacao_20260915.log"

PROMPT === CONTEXTO E STATUS DO BACKUP ===
SELECT SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AS CURRENT_SCHEMA,
       SYS_CONTEXT('USERENV','SESSION_USER') AS SESSION_USER,
       SYS_CONTEXT('USERENV','SERVICE_NAME') AS SERVICE_NAME,
       SYSTIMESTAMP AS DH_POSVALIDACAO
  FROM DUAL;

SELECT ID_EXECUCAO,USUARIO_EXECUCAO,COUNT(*) AS REGISTROS_BACKUP,
       MIN(DH_EXECUCAO) AS DH_BACKUP,
       COUNT(DISTINCT CODTIPOPER) AS TOPS_BACKUP
  FROM BKP_CMV_TOP_20260915_140624
 GROUP BY ID_EXECUCAO,USUARIO_EXECUCAO;

PROMPT === TODAS AS VERSOES ALVO DEVEM ESTAR COM PRECIFICA N ===
SELECT CODTIPOPER,
       COUNT(*) AS VERSOES,
       SUM(CASE WHEN PRECIFICA='N' THEN 1 ELSE 0 END) AS PRECIFICA_N,
       SUM(CASE WHEN NVL(PRECIFICA,'#')<>'N' THEN 1 ELSE 0 END) AS PENDENTES
  FROM TGFTOP
 WHERE CODTIPOPER IN (1451,1452,1458)
 GROUP BY CODTIPOPER
 ORDER BY CODTIPOPER;

PROMPT === DIFERENCA ENTRE O ESTADO ORIGINAL E O ESTADO ATUAL ===
SELECT B.CODTIPOPER,
       COUNT(*) AS LINHAS_BACKUP,
       SUM(CASE WHEN B.PRECIFICA=T.PRECIFICA THEN 0 ELSE 1 END) AS LINHAS_ALTERADAS,
       SUM(CASE WHEN T.PRECIFICA='N' THEN 1 ELSE 0 END) AS LINHAS_ATUAIS_N
  FROM BKP_CMV_TOP_20260915_140624 B
  JOIN TGFTOP T ON B.ROWID_ORIGINAL=ROWIDTOCHAR(T.ROWID)
 GROUP BY B.CODTIPOPER
 ORDER BY B.CODTIPOPER;

PROMPT === TOP 1401 FORA DO ESCOPO ===
SELECT CODTIPOPER,COUNT(*) AS VERSOES,
       SUM(CASE WHEN PRECIFICA='N' THEN 1 ELSE 0 END) AS PRECIFICA_N,
       SUM(CASE WHEN PRECIFICA='C' THEN 1 ELSE 0 END) AS PRECIFICA_C
  FROM TGFTOP
 WHERE CODTIPOPER=1401
 GROUP BY CODTIPOPER;

PROMPT === VERSOES ALVO EVENTUALMENTE PENDENTES ===
SELECT CODTIPOPER,DHALTER,DESCROPER,PRECIFICA,ROWIDTOCHAR(ROWID) AS ROWID_ATUAL
  FROM TGFTOP
 WHERE CODTIPOPER IN (1451,1452,1458)
   AND NVL(PRECIFICA,'#')<>'N'
 ORDER BY CODTIPOPER,DHALTER;

SPOOL OFF
