-- Atividade: CMV sem ICMS acima do faturamento
-- Fase: desativacao temporaria e controlada da trigger de TGFCUS
-- Base: INSTITUTO MOREIRA SALLES
-- Trigger: SANKHYA.TRG_DLT_UPD_TGFCUS
-- Execucao: 2026-09-15 14:23:59 -03:00
-- A trigger so sera desativada se estiver originalmente ENABLED.

SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET SQLBLANKLINES ON
SET LINESIZE 250
SET PAGESIZE 500
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

SPOOL "/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Clientes/INSTITUTO MOREIRA SALLES/Logs/55_Atividade_CMV_maior_faturamento_Desativar_Trigger_TGFCUS_20260915.log"

PROMPT === DESATIVACAO TEMPORARIA DA TRIGGER TGFCUS ===
SELECT SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AS CURRENT_SCHEMA,
       SYS_CONTEXT('USERENV','SESSION_USER') AS SESSION_USER,
       SYS_CONTEXT('USERENV','SERVICE_NAME') AS SERVICE_NAME,
       SYSTIMESTAMP AS DH_EXECUCAO
  FROM DUAL;

PROMPT === STATUS ANTES DA ALTERACAO ===
SELECT OWNER,TRIGGER_NAME,TABLE_NAME,STATUS,TRIGGERING_EVENT,TRIGGER_TYPE
  FROM ALL_TRIGGERS
 WHERE OWNER='SANKHYA'
   AND TRIGGER_NAME='TRG_DLT_UPD_TGFCUS';

DECLARE
  v_status_antes VARCHAR2(20);
  v_status_depois VARCHAR2(20);
BEGIN
  SELECT STATUS INTO v_status_antes
    FROM ALL_TRIGGERS
   WHERE OWNER='SANKHYA'
     AND TRIGGER_NAME='TRG_DLT_UPD_TGFCUS';

  IF v_status_antes<>'ENABLED' THEN
    RAISE_APPLICATION_ERROR(-20370,
      'A trigger nao estava ENABLED antes da operacao. Nenhuma alteracao foi aplicada. Status='||v_status_antes);
  END IF;

  EXECUTE IMMEDIATE 'ALTER TRIGGER SANKHYA.TRG_DLT_UPD_TGFCUS DISABLE';

  SELECT STATUS INTO v_status_depois
    FROM ALL_TRIGGERS
   WHERE OWNER='SANKHYA'
     AND TRIGGER_NAME='TRG_DLT_UPD_TGFCUS';

  IF v_status_depois<>'DISABLED' THEN
    RAISE_APPLICATION_ERROR(-20371,
      'A trigger nao ficou DISABLED apos o comando. Status='||v_status_depois);
  END IF;

  DBMS_OUTPUT.PUT_LINE('TRIGGER=SANKHYA.TRG_DLT_UPD_TGFCUS');
  DBMS_OUTPUT.PUT_LINE('STATUS_ANTES='||v_status_antes);
  DBMS_OUTPUT.PUT_LINE('STATUS_DEPOIS='||v_status_depois);
  DBMS_OUTPUT.PUT_LINE('STATUS=DESATIVADA_TEMPORARIAMENTE');
EXCEPTION
  WHEN OTHERS THEN
    IF v_status_antes='ENABLED' THEN
      BEGIN
        EXECUTE IMMEDIATE 'ALTER TRIGGER SANKHYA.TRG_DLT_UPD_TGFCUS ENABLE';
        DBMS_OUTPUT.PUT_LINE('RESTAURACAO_EXCECAO=TRIGGER_REATIVADA');
      EXCEPTION
        WHEN OTHERS THEN
          DBMS_OUTPUT.PUT_LINE('RESTAURACAO_EXCECAO=FALHOU; ERRO='||SQLERRM);
      END;
    END IF;
    RAISE;
END;
/

PROMPT === STATUS FINAL DA DESATIVACAO ===
SELECT OWNER,TRIGGER_NAME,TABLE_NAME,STATUS,TRIGGERING_EVENT,TRIGGER_TYPE
  FROM ALL_TRIGGERS
 WHERE OWNER='SANKHYA'
   AND TRIGGER_NAME='TRG_DLT_UPD_TGFCUS';

SPOOL OFF
