-- Atividade: CMV sem ICMS acima do faturamento
-- Fase: reativacao controlada da trigger apos o recalc de custos
-- Base: INSTITUTO MOREIRA SALLES
-- Trigger: SANKHYA.TRG_DLT_UPD_TGFCUS
-- O script e idempotente quando a trigger ja estiver ENABLED.

SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET SQLBLANKLINES ON
SET LINESIZE 250
SET PAGESIZE 500
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

SPOOL "/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Clientes/INSTITUTO MOREIRA SALLES/Logs/56_Atividade_CMV_maior_faturamento_Reativar_Trigger_TGFCUS_20260915.log"

PROMPT === REATIVACAO DA TRIGGER TGFCUS ===
SELECT SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AS CURRENT_SCHEMA,
       SYS_CONTEXT('USERENV','SESSION_USER') AS SESSION_USER,
       SYS_CONTEXT('USERENV','SERVICE_NAME') AS SERVICE_NAME,
       SYSTIMESTAMP AS DH_EXECUCAO
  FROM DUAL;

PROMPT === STATUS ANTES DA REATIVACAO ===
SELECT OWNER,TRIGGER_NAME,TABLE_NAME,STATUS,TRIGGERING_EVENT,TRIGGER_TYPE
  FROM ALL_TRIGGERS
 WHERE OWNER='SANKHYA'
   AND TRIGGER_NAME='TRG_DLT_UPD_TGFCUS';

DECLARE
  v_status_antes VARCHAR2(20);
  v_status_depois VARCHAR2(20);
BEGIN
  SELECT STATUS INTO v_status_antes
    FROM ALL_TRIGGERS
   WHERE OWNER='SANKHYA'
     AND TRIGGER_NAME='TRG_DLT_UPD_TGFCUS';

  IF v_status_antes='ENABLED' THEN
    DBMS_OUTPUT.PUT_LINE('STATUS=JA_ESTAVA_ENABLED; NENHUMA ALTERACAO NECESSARIA');
    RETURN;
  END IF;

  IF v_status_antes<>'DISABLED' THEN
    RAISE_APPLICATION_ERROR(-20372,
      'Status inesperado para reativacao. Status='||v_status_antes);
  END IF;

  EXECUTE IMMEDIATE 'ALTER TRIGGER SANKHYA.TRG_DLT_UPD_TGFCUS ENABLE';

  SELECT STATUS INTO v_status_depois
    FROM ALL_TRIGGERS
   WHERE OWNER='SANKHYA'
     AND TRIGGER_NAME='TRG_DLT_UPD_TGFCUS';

  IF v_status_depois<>'ENABLED' THEN
    RAISE_APPLICATION_ERROR(-20373,
      'A trigger nao ficou ENABLED apos o comando. Status='||v_status_depois);
  END IF;

  DBMS_OUTPUT.PUT_LINE('TRIGGER=SANKHYA.TRG_DLT_UPD_TGFCUS');
  DBMS_OUTPUT.PUT_LINE('STATUS_ANTES='||v_status_antes);
  DBMS_OUTPUT.PUT_LINE('STATUS_DEPOIS='||v_status_depois);
  DBMS_OUTPUT.PUT_LINE('STATUS=REATIVADA');
END;
/

PROMPT === STATUS FINAL DA REATIVACAO ===
SELECT OWNER,TRIGGER_NAME,TABLE_NAME,STATUS,TRIGGERING_EVENT,TRIGGER_TYPE
  FROM ALL_TRIGGERS
 WHERE OWNER='SANKHYA'
   AND TRIGGER_NAME='TRG_DLT_UPD_TGFCUS';

SPOOL OFF
