
-- Merge controlado de bairros e enderecos duplicados apos normalizacao.
-- Cliente/base: BANGTOYS / BANGTOYSPRD.SANKHYACLOUD.COM.BR
-- IMPORTANTE: executar primeiro em uma janela dedicada e conferir a conexao.
-- As tabelas BKP_MBE_* sao persistentes e permitem auditoria/reversao por ID_EXECUCAO.

SET SERVEROUTPUT ON SIZE UNLIMITED
SET SQLBLANKLINES ON
SET DEFINE ON
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

COLUMN RUN_ID NEW_VALUE RUN_ID NOPRINT
SELECT TO_CHAR(SYSTIMESTAMP, 'YYYYMMDDHH24MISSFF3') RUN_ID FROM DUAL;
PROMPT ID_EXECUCAO=BANGTOYS_20260902_084500

PROMPT === 01. CRIACAO DAS ESTRUTURAS DE BACKUP (SE NECESSARIO) ===
DECLARE
  PROCEDURE cria(p_nome VARCHAR2, p_sql VARCHAR2) IS
    v_qtd NUMBER;
  BEGIN
    SELECT COUNT(*) INTO v_qtd
      FROM ALL_TABLES
     WHERE OWNER = SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA')
       AND TABLE_NAME = UPPER(p_nome);
    IF v_qtd = 0 THEN EXECUTE IMMEDIATE p_sql; END IF;
  END;
BEGIN
  cria('BKP_MBE_MAP_BAI', 'CREATE TABLE BKP_MBE_MAP_BAI (ID_EXECUCAO VARCHAR2(30), COD_OBSOLETO NUMBER, COD_MANTIDO NUMBER)');
  cria('BKP_MBE_MAP_END', 'CREATE TABLE BKP_MBE_MAP_END (ID_EXECUCAO VARCHAR2(30), COD_OBSOLETO NUMBER, COD_MANTIDO NUMBER)');
  cria('BKP_MBE_TSIBAI',  'CREATE TABLE BKP_MBE_TSIBAI AS SELECT CAST(NULL AS VARCHAR2(30)) ID_EXECUCAO, t.* FROM TSIBAI t WHERE 1=0');
  cria('BKP_MBE_TSIEND',  'CREATE TABLE BKP_MBE_TSIEND AS SELECT CAST(NULL AS VARCHAR2(30)) ID_EXECUCAO, t.* FROM TSIEND t WHERE 1=0');
  cria('BKP_MBE_TGFPAR',  'CREATE TABLE BKP_MBE_TGFPAR AS SELECT CAST(NULL AS VARCHAR2(30)) ID_EXECUCAO, CAST(NULL AS VARCHAR2(30)) ROWID_ORIGINAL, t.* FROM TGFPAR t WHERE 1=0');
  cria('BKP_MBE_TGFPAR_BKP', 'CREATE TABLE BKP_MBE_TGFPAR_BKP AS SELECT CAST(NULL AS VARCHAR2(30)) ID_EXECUCAO, CAST(NULL AS VARCHAR2(30)) ROWID_ORIGINAL, t.* FROM TGFPAR_BKP t WHERE 1=0');
  cria('BKP_MBE_TSICEP',  'CREATE TABLE BKP_MBE_TSICEP AS SELECT CAST(NULL AS VARCHAR2(30)) ID_EXECUCAO, CAST(NULL AS VARCHAR2(30)) ROWID_ORIGINAL, t.* FROM TSICEP t WHERE 1=0');
  cria('BKP_MBE_TFPFUN',  'CREATE TABLE BKP_MBE_TFPFUN AS SELECT CAST(NULL AS VARCHAR2(30)) ID_EXECUCAO, CAST(NULL AS VARCHAR2(30)) ROWID_ORIGINAL, t.* FROM TFPFUN t WHERE 1=0');
END;
/

PROMPT === 02. MAPAS E BACKUP DAS LINHAS AFETADAS ===
DECLARE
  v_qtd NUMBER;
BEGIN
  SELECT (SELECT COUNT(*) FROM BKP_MBE_MAP_BAI WHERE ID_EXECUCAO='BANGTOYS_20260902_084500')
       + (SELECT COUNT(*) FROM BKP_MBE_MAP_END WHERE ID_EXECUCAO='BANGTOYS_20260902_084500')
    INTO v_qtd FROM DUAL;
  IF v_qtd <> 0 THEN
    RAISE_APPLICATION_ERROR(-20011, 'ID_EXECUCAO ja utilizado: BANGTOYS_20260902_084500');
  END IF;
END;
/

INSERT INTO BKP_MBE_MAP_BAI (ID_EXECUCAO, COD_OBSOLETO, COD_MANTIDO)
SELECT 'BANGTOYS_20260902_084500', CODBAI, KEEP_ID
  FROM (
    SELECT CODBAI,
           MIN(CODBAI) OVER (PARTITION BY REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEBAI),
             'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇáàâãäéèêëíìîïóòôõöúùûüçÃãÕõÂâÊêÎîÔôÛû',
             'AAAAAEEEEIIIIOOOOOUUUUCAAAAAEEEEIIIIOOOOOUUUUCAAAOOAAEIIOOUU')), ' {2,}', ' ')) KEEP_ID,
           COUNT(*) OVER (PARTITION BY REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEBAI),
             'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇáàâãäéèêëíìîïóòôõöúùûüçÃãÕõÂâÊêÎîÔôÛû',
             'AAAAAEEEEIIIIOOOOOUUUUCAAAAAEEEEIIIIOOOOOUUUUCAAAOOAAEIIOOUU')), ' {2,}', ' ')) CNT
      FROM TSIBAI
  ) WHERE CNT > 1 AND CODBAI <> KEEP_ID;

INSERT INTO BKP_MBE_MAP_END (ID_EXECUCAO, COD_OBSOLETO, COD_MANTIDO)
SELECT 'BANGTOYS_20260902_084500', CODEND, KEEP_ID
  FROM (
    SELECT CODEND,
           MIN(CODEND) OVER (PARTITION BY TIPO, REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEEND),
             'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇáàâãäéèêëíìîïóòôõöúùûüçÃãÕõÂâÊêÎîÔôÛû',
             'AAAAAEEEEIIIIOOOOOUUUUCAAAAAEEEEIIIIOOOOOUUUUCAAAOOAAEIIOOUU')), ' {2,}', ' ')) KEEP_ID,
           COUNT(*) OVER (PARTITION BY TIPO, REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEEND),
             'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇáàâãäéèêëíìîïóòôõöúùûüçÃãÕõÂâÊêÎîÔôÛû',
             'AAAAAEEEEIIIIOOOOOUUUUCAAAAAEEEEIIIIOOOOOUUUUCAAAOOAAEIIOOUU')), ' {2,}', ' ')) CNT
      FROM TSIEND
  ) WHERE CNT > 1 AND CODEND <> KEEP_ID;

DECLARE
  v_bai NUMBER;
  v_end NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_bai FROM BKP_MBE_MAP_BAI WHERE ID_EXECUCAO='BANGTOYS_20260902_084500';
  SELECT COUNT(*) INTO v_end FROM BKP_MBE_MAP_END WHERE ID_EXECUCAO='BANGTOYS_20260902_084500';
  IF v_bai <> 350 OR v_end <> 7289 THEN
    RAISE_APPLICATION_ERROR(-20012, 'Diagnostico divergiu: bairros=' || v_bai || ', enderecos=' || v_end);
  END IF;
  DBMS_OUTPUT.PUT_LINE('OK: mapas conferidos: bairros=' || v_bai || ', enderecos=' || v_end);
END;
/

INSERT INTO BKP_MBE_TSIBAI SELECT 'BANGTOYS_20260902_084500', b.* FROM TSIBAI b
 WHERE b.CODBAI IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_BAI WHERE ID_EXECUCAO='BANGTOYS_20260902_084500')
    OR b.CODBAI IN (SELECT COD_MANTIDO FROM BKP_MBE_MAP_BAI WHERE ID_EXECUCAO='BANGTOYS_20260902_084500');
INSERT INTO BKP_MBE_TSIEND SELECT 'BANGTOYS_20260902_084500', e.* FROM TSIEND e
 WHERE e.CODEND IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_END WHERE ID_EXECUCAO='BANGTOYS_20260902_084500')
    OR e.CODEND IN (SELECT COD_MANTIDO FROM BKP_MBE_MAP_END WHERE ID_EXECUCAO='BANGTOYS_20260902_084500');
INSERT INTO BKP_MBE_TGFPAR SELECT 'BANGTOYS_20260902_084500', ROWIDTOCHAR(ROWID), p.* FROM TGFPAR p
 WHERE p.CODBAI IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_BAI WHERE ID_EXECUCAO='BANGTOYS_20260902_084500')
    OR p.CODEND IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_END WHERE ID_EXECUCAO='BANGTOYS_20260902_084500');
INSERT INTO BKP_MBE_TGFPAR_BKP SELECT 'BANGTOYS_20260902_084500', ROWIDTOCHAR(ROWID), p.* FROM TGFPAR_BKP p
 WHERE p.CODBAI IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_BAI WHERE ID_EXECUCAO='BANGTOYS_20260902_084500')
    OR p.CODEND IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_END WHERE ID_EXECUCAO='BANGTOYS_20260902_084500');
INSERT INTO BKP_MBE_TSICEP SELECT 'BANGTOYS_20260902_084500', ROWIDTOCHAR(ROWID), c.* FROM TSICEP c
 WHERE c.CODBAI IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_BAI WHERE ID_EXECUCAO='BANGTOYS_20260902_084500')
    OR c.CODEND IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_END WHERE ID_EXECUCAO='BANGTOYS_20260902_084500');
INSERT INTO BKP_MBE_TFPFUN SELECT 'BANGTOYS_20260902_084500', ROWIDTOCHAR(ROWID), f.* FROM TFPFUN f
 WHERE f.CODBAI IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_BAI WHERE ID_EXECUCAO='BANGTOYS_20260902_084500');
COMMIT;

DECLARE
  v_par_bai NUMBER;
  v_par_end NUMBER;
  v_cep_bai NUMBER;
  v_cep_end NUMBER;
  v_par_bkp_bai NUMBER;
  v_par_bkp_end NUMBER;
  v_fun_bai NUMBER;
  v_bkp_bai NUMBER;
  v_bkp_end NUMBER;
  v_faltantes NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_par_bai FROM TGFPAR
   WHERE CODBAI IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_BAI WHERE ID_EXECUCAO='BANGTOYS_20260902_084500');
  SELECT COUNT(*) INTO v_par_end FROM TGFPAR
   WHERE CODEND IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_END WHERE ID_EXECUCAO='BANGTOYS_20260902_084500');
  SELECT COUNT(*) INTO v_cep_bai FROM TSICEP
   WHERE CODBAI IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_BAI WHERE ID_EXECUCAO='BANGTOYS_20260902_084500');
  SELECT COUNT(*) INTO v_cep_end FROM TSICEP
   WHERE CODEND IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_END WHERE ID_EXECUCAO='BANGTOYS_20260902_084500');
  SELECT COUNT(*) INTO v_par_bkp_bai FROM TGFPAR_BKP
   WHERE CODBAI IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_BAI WHERE ID_EXECUCAO='BANGTOYS_20260902_084500');
  SELECT COUNT(*) INTO v_par_bkp_end FROM TGFPAR_BKP
   WHERE CODEND IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_END WHERE ID_EXECUCAO='BANGTOYS_20260902_084500');
  SELECT COUNT(*) INTO v_fun_bai FROM TFPFUN
   WHERE CODBAI IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_BAI WHERE ID_EXECUCAO='BANGTOYS_20260902_084500');

  IF v_par_bai <> 451 OR v_par_end <> 1563 OR v_cep_bai <> 10717 OR v_cep_end <> 49746 THEN
    RAISE_APPLICATION_ERROR(-20013,
      'Referencias divergiram: TGFPAR.BAI=' || v_par_bai || ', TGFPAR.END=' || v_par_end ||
      ', TSICEP.BAI=' || v_cep_bai || ', TSICEP.END=' || v_cep_end);
  END IF;
  IF v_par_bkp_bai <> 1642 OR v_par_bkp_end <> 116 OR v_fun_bai <> 2 THEN
    RAISE_APPLICATION_ERROR(-20017,
      'Referencias adicionais divergiram: TGFPAR_BKP.BAI=' || v_par_bkp_bai ||
      ', TGFPAR_BKP.END=' || v_par_bkp_end || ', TFPFUN.BAI=' || v_fun_bai);
  END IF;

  SELECT COUNT(*) INTO v_bkp_bai FROM BKP_MBE_TSIBAI
   WHERE ID_EXECUCAO='BANGTOYS_20260902_084500';
  SELECT COUNT(*) INTO v_bkp_end FROM BKP_MBE_TSIEND
   WHERE ID_EXECUCAO='BANGTOYS_20260902_084500';
  IF v_bkp_bai <> 694 OR v_bkp_end <> 14238 THEN
    RAISE_APPLICATION_ERROR(-20014,
      'Backups dos cadastros divergiram: TSIBAI=' || v_bkp_bai || ', TSIEND=' || v_bkp_end);
  END IF;

  SELECT
    (SELECT COUNT(*) FROM TGFPAR p
      WHERE (p.CODBAI IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_BAI WHERE ID_EXECUCAO='BANGTOYS_20260902_084500')
         OR  p.CODEND IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_END WHERE ID_EXECUCAO='BANGTOYS_20260902_084500'))
        AND NOT EXISTS (SELECT 1 FROM BKP_MBE_TGFPAR b
                         WHERE b.ID_EXECUCAO='BANGTOYS_20260902_084500'
                           AND CHARTOROWID(b.ROWID_ORIGINAL)=p.ROWID))
    +
    (SELECT COUNT(*) FROM TSICEP c
      WHERE (c.CODBAI IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_BAI WHERE ID_EXECUCAO='BANGTOYS_20260902_084500')
         OR  c.CODEND IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_END WHERE ID_EXECUCAO='BANGTOYS_20260902_084500'))
        AND NOT EXISTS (SELECT 1 FROM BKP_MBE_TSICEP b
                         WHERE b.ID_EXECUCAO='BANGTOYS_20260902_084500'
                           AND CHARTOROWID(b.ROWID_ORIGINAL)=c.ROWID))
    +
    (SELECT COUNT(*) FROM TGFPAR_BKP p
      WHERE (p.CODBAI IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_BAI WHERE ID_EXECUCAO='BANGTOYS_20260902_084500')
         OR  p.CODEND IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_END WHERE ID_EXECUCAO='BANGTOYS_20260902_084500'))
        AND NOT EXISTS (SELECT 1 FROM BKP_MBE_TGFPAR_BKP b
                         WHERE b.ID_EXECUCAO='BANGTOYS_20260902_084500'
                           AND CHARTOROWID(b.ROWID_ORIGINAL)=p.ROWID))
    +
    (SELECT COUNT(*) FROM TFPFUN f
      WHERE f.CODBAI IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_BAI WHERE ID_EXECUCAO='BANGTOYS_20260902_084500')
        AND NOT EXISTS (SELECT 1 FROM BKP_MBE_TFPFUN b
                         WHERE b.ID_EXECUCAO='BANGTOYS_20260902_084500'
                           AND CHARTOROWID(b.ROWID_ORIGINAL)=f.ROWID))
    INTO v_faltantes FROM DUAL;
  IF v_faltantes <> 0 THEN
    RAISE_APPLICATION_ERROR(-20015, 'Existem linhas dependentes sem backup: ' || v_faltantes);
  END IF;
  DBMS_OUTPUT.PUT_LINE('OK: referencias e backups conferidos antes do merge.');
END;
/

PROMPT === 03. MERGE TRANSACIONAL ===
DECLARE
  v_restantes NUMBER;
  v_dup_bai NUMBER;
  v_dup_end NUMBER;
BEGIN
  UPDATE TGFPAR p
     SET CODBAI = NVL((SELECT m.COD_MANTIDO FROM BKP_MBE_MAP_BAI m WHERE m.ID_EXECUCAO='BANGTOYS_20260902_084500' AND m.COD_OBSOLETO=p.CODBAI), p.CODBAI),
         CODEND = NVL((SELECT m.COD_MANTIDO FROM BKP_MBE_MAP_END m WHERE m.ID_EXECUCAO='BANGTOYS_20260902_084500' AND m.COD_OBSOLETO=p.CODEND), p.CODEND)
   WHERE EXISTS (SELECT 1 FROM BKP_MBE_MAP_BAI m WHERE m.ID_EXECUCAO='BANGTOYS_20260902_084500' AND m.COD_OBSOLETO=p.CODBAI)
      OR EXISTS (SELECT 1 FROM BKP_MBE_MAP_END m WHERE m.ID_EXECUCAO='BANGTOYS_20260902_084500' AND m.COD_OBSOLETO=p.CODEND);

  UPDATE TSICEP c
     SET CODBAI = NVL((SELECT m.COD_MANTIDO FROM BKP_MBE_MAP_BAI m WHERE m.ID_EXECUCAO='BANGTOYS_20260902_084500' AND m.COD_OBSOLETO=c.CODBAI), c.CODBAI),
         CODEND = NVL((SELECT m.COD_MANTIDO FROM BKP_MBE_MAP_END m WHERE m.ID_EXECUCAO='BANGTOYS_20260902_084500' AND m.COD_OBSOLETO=c.CODEND), c.CODEND)
   WHERE EXISTS (SELECT 1 FROM BKP_MBE_MAP_BAI m WHERE m.ID_EXECUCAO='BANGTOYS_20260902_084500' AND m.COD_OBSOLETO=c.CODBAI)
      OR EXISTS (SELECT 1 FROM BKP_MBE_MAP_END m WHERE m.ID_EXECUCAO='BANGTOYS_20260902_084500' AND m.COD_OBSOLETO=c.CODEND);

  UPDATE TGFPAR_BKP p
     SET CODBAI = NVL((SELECT m.COD_MANTIDO FROM BKP_MBE_MAP_BAI m WHERE m.ID_EXECUCAO='BANGTOYS_20260902_084500' AND m.COD_OBSOLETO=p.CODBAI), p.CODBAI),
         CODEND = NVL((SELECT m.COD_MANTIDO FROM BKP_MBE_MAP_END m WHERE m.ID_EXECUCAO='BANGTOYS_20260902_084500' AND m.COD_OBSOLETO=p.CODEND), p.CODEND)
   WHERE EXISTS (SELECT 1 FROM BKP_MBE_MAP_BAI m WHERE m.ID_EXECUCAO='BANGTOYS_20260902_084500' AND m.COD_OBSOLETO=p.CODBAI)
      OR EXISTS (SELECT 1 FROM BKP_MBE_MAP_END m WHERE m.ID_EXECUCAO='BANGTOYS_20260902_084500' AND m.COD_OBSOLETO=p.CODEND);

  UPDATE TFPFUN f
     SET CODBAI = (SELECT m.COD_MANTIDO FROM BKP_MBE_MAP_BAI m WHERE m.ID_EXECUCAO='BANGTOYS_20260902_084500' AND m.COD_OBSOLETO=f.CODBAI)
   WHERE EXISTS (SELECT 1 FROM BKP_MBE_MAP_BAI m WHERE m.ID_EXECUCAO='BANGTOYS_20260902_084500' AND m.COD_OBSOLETO=f.CODBAI);

  SELECT (SELECT COUNT(*) FROM TGFPAR p WHERE p.CODBAI IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_BAI WHERE ID_EXECUCAO='BANGTOYS_20260902_084500') OR p.CODEND IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_END WHERE ID_EXECUCAO='BANGTOYS_20260902_084500'))
       + (SELECT COUNT(*) FROM TSICEP c WHERE c.CODBAI IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_BAI WHERE ID_EXECUCAO='BANGTOYS_20260902_084500') OR c.CODEND IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_END WHERE ID_EXECUCAO='BANGTOYS_20260902_084500'))
       + (SELECT COUNT(*) FROM TGFPAR_BKP p WHERE p.CODBAI IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_BAI WHERE ID_EXECUCAO='BANGTOYS_20260902_084500') OR p.CODEND IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_END WHERE ID_EXECUCAO='BANGTOYS_20260902_084500'))
       + (SELECT COUNT(*) FROM TFPFUN f WHERE f.CODBAI IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_BAI WHERE ID_EXECUCAO='BANGTOYS_20260902_084500'))
    INTO v_restantes FROM DUAL;
  IF v_restantes <> 0 THEN RAISE_APPLICATION_ERROR(-20001, 'Ainda existem referencias: ' || v_restantes); END IF;

  DELETE FROM TSIBAI WHERE CODBAI IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_BAI WHERE ID_EXECUCAO='BANGTOYS_20260902_084500');
  DELETE FROM TSIEND WHERE CODEND IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_END WHERE ID_EXECUCAO='BANGTOYS_20260902_084500');

  UPDATE TSIBAI SET NOMEBAI = REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEBAI),
    'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇáàâãäéèêëíìîïóòôõöúùûüçÃãÕõÂâÊêÎîÔôÛû',
    'AAAAAEEEEIIIIOOOOOUUUUCAAAAAEEEEIIIIOOOOOUUUUCAAAOOAAEIIOOUU')), ' {2,}', ' ')
   WHERE CODBAI IN (SELECT COD_MANTIDO FROM BKP_MBE_MAP_BAI WHERE ID_EXECUCAO='BANGTOYS_20260902_084500');
  UPDATE TSIEND SET NOMEEND = REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEEND),
    'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇáàâãäéèêëíìîïóòôõöúùûüçÃãÕõÂâÊêÎîÔôÛû',
    'AAAAAEEEEIIIIOOOOOUUUUCAAAAAEEEEIIIIOOOOOUUUUCAAAOOAAEIIOOUU')), ' {2,}', ' ')
   WHERE CODEND IN (SELECT COD_MANTIDO FROM BKP_MBE_MAP_END WHERE ID_EXECUCAO='BANGTOYS_20260902_084500');

  SELECT COUNT(*) INTO v_dup_bai
    FROM (
      SELECT 1
        FROM TSIBAI
       GROUP BY REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEBAI),
         'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇáàâãäéèêëíìîïóòôõöúùûüçÃãÕõÂâÊêÎîÔôÛû',
         'AAAAAEEEEIIIIOOOOOUUUUCAAAAAEEEEIIIIOOOOOUUUUCAAAOOAAEIIOOUU')), ' {2,}', ' ')
      HAVING COUNT(*) > 1
    );
  SELECT COUNT(*) INTO v_dup_end
    FROM (
      SELECT 1
        FROM TSIEND
       GROUP BY TIPO, REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEEND),
         'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇáàâãäéèêëíìîïóòôõöúùûüçÃãÕõÂâÊêÎîÔôÛû',
         'AAAAAEEEEIIIIOOOOOUUUUCAAAAAEEEEIIIIOOOOOUUUUCAAAOOAAEIIOOUU')), ' {2,}', ' ')
      HAVING COUNT(*) > 1
    );
  IF v_dup_bai <> 0 OR v_dup_end <> 0 THEN
    RAISE_APPLICATION_ERROR(-20016,
      'Duplicidades restantes antes do commit: bairros=' || v_dup_bai || ', enderecos=' || v_dup_end);
  END IF;

  COMMIT;
  DBMS_OUTPUT.PUT_LINE('OK: merge concluido. ID_EXECUCAO=BANGTOYS_20260902_084500');
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('ERRO: DML revertido; backups preservados. ' || SQLERRM);
    RAISE;
END;
/

PROMPT === FIM DO MERGE ===
