SET DEFINE ON
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
ACCEPT P_ID_EXECUCAO CHAR PROMPT 'ID da execucao RMD_MAT_: '
DECLARE
  v_bkp PLS_INTEGER;
  v_upd PLS_INTEGER;
BEGIN
  SELECT COUNT(*) INTO v_bkp FROM BKP_RMD_PAR_MATRIZ
   WHERE ID_EXECUCAO='&&P_ID_EXECUCAO';
  IF v_bkp=0 THEN RAISE_APPLICATION_ERROR(-20121,'Backup nao encontrado.'); END IF;
  MERGE INTO TGFPAR P
  USING (SELECT CODPARC,CODPARCMATRIZ_ANTES FROM BKP_RMD_PAR_MATRIZ
          WHERE ID_EXECUCAO='&&P_ID_EXECUCAO') B
     ON (P.CODPARC=B.CODPARC)
   WHEN MATCHED THEN UPDATE SET P.CODPARCMATRIZ=B.CODPARCMATRIZ_ANTES;
  v_upd:=SQL%ROWCOUNT;
  IF v_upd<>v_bkp THEN RAISE_APPLICATION_ERROR(-20122,'Rollback divergente.'); END IF;
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('PARCEIROS_REVERTIDOS='||v_upd);
EXCEPTION WHEN OTHERS THEN ROLLBACK; RAISE;
END;
/
UNDEFINE P_ID_EXECUCAO
