SET DEFINE ON
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
ACCEPT P_ID_EXECUCAO CHAR PROMPT 'ID da execucao RMD_DANF_: '
DECLARE v_b PLS_INTEGER; v_u PLS_INTEGER; BEGIN
 SELECT COUNT(*) INTO v_b FROM BKP_RMD_02_TGFEMP WHERE ID_EXECUCAO='&&P_ID_EXECUCAO';
 IF v_b=0 THEN RAISE_APPLICATION_ERROR(-20211,'Backup nao encontrado.'); END IF;
 MERGE INTO TGFEMP T USING (SELECT * FROM BKP_RMD_02_TGFEMP WHERE ID_EXECUCAO='&&P_ID_EXECUCAO') B
 ON (T.ROWID=CHARTOROWID(B.ROWID_ORIGINAL)) WHEN MATCHED THEN UPDATE SET T.CODMODDANFESIMPLIFNFE=B.CODMODDANFESIMPLIFNFE_ANTES, T.CONTINGENCIANFE=B.CONTINGENCIANFE_ANTES, T.ENVIOSINCRONONFE=B.ENVIOSINCRONONFE_ANTES, T.NURFE=B.NURFE_ANTES, T.NURFECARTACORR=B.NURFECARTACORR_ANTES, T.TIPODANFE=B.TIPODANFE_ANTES, T.NFE=B.NFE_ANTES, T.VERSAONFE=B.VERSAONFE_ANTES, T.VERSAONT=B.VERSAONT_ANTES, T.UTILIZAMDE=B.UTILIZAMDE_ANTES, T.LOGODANFE=B.LOGODANFE_ANTES;
 v_u:=SQL%ROWCOUNT; IF v_b<>v_u THEN RAISE_APPLICATION_ERROR(-20212,'Rollback divergente.'); END IF;
 COMMIT; DBMS_OUTPUT.PUT_LINE('REGISTROS_REVERTIDOS='||v_u);
EXCEPTION WHEN OTHERS THEN ROLLBACK; RAISE; END;
/
UNDEFINE P_ID_EXECUCAO

