CREATE OR REPLACE VIEW AD_NATTPOCFO2
AS 
    SELECT
        DISTINCT ITE.CODCFO,
        ITE.CODEMP,
        ITE.CODTRIB,
        CAB.CODNAT,
        CAB.CODPARC,
        CAB.CODTIPOPER,
        CAB.DTNEG,
        ITE.NUNOTA,
        CAB.VLRNOTA,
        CAB.NUMNOTA,
        CAB.OBSERVACAO,
        CAB.AD_ORIGDEPLOY,
        CAB.CHAVENFE
FROM TGFITE ITE
INNER JOIN TGFCAB CAB ON ITE.NUNOTA = CAB.NUNOTA