CREATE OR REPLACE VIEW AD_NATTPOCFO2
AS 
    SELECT
        DISTINCT ITE.CODCFO,
        ITE.CODEMP,
        CAB.CODNAT,
        CAB.CODPARC,
        CAB.CODTIPOPER,
        CAB.DTNEG,
        ITE.NUNOTA,
        CAB.VLRNOTA
FROM TGFITE ITE
INNER JOIN TGFCAB CAB ON ITE.NUNOTA = CAB.NUNOTA