-- Rollback explícito do Card 09 - função XML criada pelo ID informado.
-- Nao executar automaticamente. Nao contem senha.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET ECHO ON
WHENEVER OSERROR EXIT FAILURE ROLLBACK
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

PROMPT === ROLLBACK CARD 09 - FUNCAO XML ===
PROMPT ID_ORIGEM=RMD_ALH_FNC09_2026091701

DECLARE
  v_status VARCHAR2(30);
BEGIN
  SELECT MAX(STATUS)
    INTO v_status
    FROM ALL_OBJECTS
   WHERE OWNER = SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
     AND OBJECT_NAME = 'FNC_BUSCA_TAG_XML_GERAL'
     AND OBJECT_TYPE = 'FUNCTION';

  IF v_status IS NULL THEN
    DBMS_OUTPUT.PUT_LINE('ROLLBACK_NECESSARIO=NAO; FUNCAO_AUSENTE');
  ELSE
    DBMS_OUTPUT.PUT_LINE('ROLLBACK_PREPARADO; STATUS_ATUAL=' || v_status);
    EXECUTE IMMEDIATE 'DROP FUNCTION FNC_BUSCA_TAG_XML_GERAL';
    DBMS_OUTPUT.PUT_LINE('ROLLBACK_EXECUTADO=SIM; FUNCAO_REMOVIDA');
  END IF;
END;
/

SELECT OWNER, OBJECT_NAME, OBJECT_TYPE, STATUS
  FROM ALL_OBJECTS
 WHERE OBJECT_NAME = 'FNC_BUSCA_TAG_XML_GERAL';

PROMPT === ROLLBACK CARD 09 CONCLUIDO ===
