-- ============================================================================
-- Limpar_Objetos_Revisao.sql
-- Uso opcional APOS a entrega e somente quando os rollbacks nao forem mais
-- necessarios. Nao e chamado pelo Revisao_Master_Deploy.sql.
--
-- Remove exclusivamente:
--   * objetos com prefixo BKP_RMD_;
--   * objetos com prefixo BKP_MBE_ (merge de bairros e endereços);
--   * objetos com prefixo RMD_;
--   * BKP_AJNP_TGFPAR e BKP_CLASSICMS_TGFPAR, nomes tecnicos legados desta
--     mesma rotina de revisao.
--
-- DROP e DDL fazem COMMIT implicito no Oracle. Nao existe rollback deste script.
-- As tabelas nao usam PURGE, permitindo eventual recuperacao pela lixeira do
-- Oracle quando RECYCLEBIN estiver habilitado e houver privilegio.
-- ============================================================================
SET DEFINE ON
SET SERVEROUTPUT ON SIZE UNLIMITED
SET SQLBLANKLINES ON
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

COLUMN OBJECT_TYPE FORMAT A22
COLUMN OBJECT_NAME FORMAT A40
PROMPT Objetos exclusivos da revisao encontrados no CURRENT_SCHEMA:
SELECT OBJECT_TYPE,OBJECT_NAME
  FROM ALL_OBJECTS
 WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
   AND (OBJECT_NAME LIKE 'BKP\_RMD\_%' ESCAPE '\'
        OR OBJECT_NAME LIKE 'BKP\_MBE\_%' ESCAPE '\'
        OR OBJECT_NAME LIKE 'RMD\_%' ESCAPE '\'
        OR OBJECT_NAME IN ('BKP_AJNP_TGFPAR','BKP_CLASSICMS_TGFPAR'))
   AND OBJECT_TYPE IN ('TABLE','VIEW','MATERIALIZED VIEW','SEQUENCE',
                       'FUNCTION','PROCEDURE','PACKAGE','TYPE','TRIGGER')
 ORDER BY OBJECT_TYPE,OBJECT_NAME;

PROMPT ATENCAO: a exclusao elimina os backups e inviabiliza os rollbacks.
ACCEPT P_CONFIRMA CHAR PROMPT 'Digite EXCLUIR OBJETOS para confirmar: '

DECLARE
  v_excluidos PLS_INTEGER:=0;
  v_ddl VARCHAR2(1000);
BEGIN
  IF UPPER(TRIM('&&P_CONFIRMA'))<>'EXCLUIR OBJETOS' THEN
    RAISE_APPLICATION_ERROR(-20400,'Operacao cancelada: confirmacao diferente do texto exigido.');
  END IF;

  FOR R IN (
    SELECT OBJECT_NAME,OBJECT_TYPE
      FROM ALL_OBJECTS
     WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
       AND (OBJECT_NAME LIKE 'BKP\_RMD\_%' ESCAPE '\'
            OR OBJECT_NAME LIKE 'BKP\_MBE\_%' ESCAPE '\'
            OR OBJECT_NAME LIKE 'RMD\_%' ESCAPE '\'
            OR OBJECT_NAME IN ('BKP_AJNP_TGFPAR','BKP_CLASSICMS_TGFPAR'))
       AND OBJECT_TYPE IN ('TABLE','VIEW','MATERIALIZED VIEW','SEQUENCE',
                           'FUNCTION','PROCEDURE','PACKAGE','TYPE','TRIGGER')
     ORDER BY CASE OBJECT_TYPE
       WHEN 'TRIGGER' THEN 1 WHEN 'VIEW' THEN 2 WHEN 'MATERIALIZED VIEW' THEN 3
       WHEN 'FUNCTION' THEN 4 WHEN 'PROCEDURE' THEN 5 WHEN 'PACKAGE' THEN 6
       WHEN 'TYPE' THEN 7 WHEN 'SEQUENCE' THEN 8 WHEN 'TABLE' THEN 9 ELSE 10 END,
       OBJECT_NAME
  ) LOOP
    v_ddl:=CASE R.OBJECT_TYPE
      WHEN 'TABLE' THEN 'DROP TABLE '||DBMS_ASSERT.ENQUOTE_NAME(R.OBJECT_NAME,FALSE)||' CASCADE CONSTRAINTS'
      WHEN 'VIEW' THEN 'DROP VIEW '||DBMS_ASSERT.ENQUOTE_NAME(R.OBJECT_NAME,FALSE)
      WHEN 'MATERIALIZED VIEW' THEN 'DROP MATERIALIZED VIEW '||DBMS_ASSERT.ENQUOTE_NAME(R.OBJECT_NAME,FALSE)
      WHEN 'SEQUENCE' THEN 'DROP SEQUENCE '||DBMS_ASSERT.ENQUOTE_NAME(R.OBJECT_NAME,FALSE)
      WHEN 'FUNCTION' THEN 'DROP FUNCTION '||DBMS_ASSERT.ENQUOTE_NAME(R.OBJECT_NAME,FALSE)
      WHEN 'PROCEDURE' THEN 'DROP PROCEDURE '||DBMS_ASSERT.ENQUOTE_NAME(R.OBJECT_NAME,FALSE)
      WHEN 'PACKAGE' THEN 'DROP PACKAGE '||DBMS_ASSERT.ENQUOTE_NAME(R.OBJECT_NAME,FALSE)
      WHEN 'TYPE' THEN 'DROP TYPE '||DBMS_ASSERT.ENQUOTE_NAME(R.OBJECT_NAME,FALSE)||' FORCE'
      WHEN 'TRIGGER' THEN 'DROP TRIGGER '||DBMS_ASSERT.ENQUOTE_NAME(R.OBJECT_NAME,FALSE)
    END;
    EXECUTE IMMEDIATE v_ddl;
    v_excluidos:=v_excluidos+1;
    DBMS_OUTPUT.PUT_LINE('EXCLUIDO='||R.OBJECT_TYPE||':'||R.OBJECT_NAME);
  END LOOP;
  DBMS_OUTPUT.PUT_LINE('TOTAL_OBJETOS_EXCLUIDOS='||v_excluidos);
END;
/
UNDEFINE P_CONFIRMA
PROMPT === FIM LIMPEZA DOS OBJETOS DE REVISAO ===
