-- Modelo read-only para diagnosticar variacoes de nome da empresa.
-- Preencha o nome informado e pelo menos um token de busca antes de executar.
-- O resultado nao autoriza sozinho a execucao do Master: exige validacao do
-- solicitante quando a razao social exata nao for encontrada.

SET DEFINE ON
SET PAGESIZE 1000
SET TRIMSPOOL ON
WHENEVER OSERROR EXIT FAILURE ROLLBACK
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

DEFINE NOME_INFORMADO = 'NOME DA BASE INFORMADO'
DEFINE TOKEN_1 = 'TOKEN PRINCIPAL'
DEFINE TOKEN_2 = 'TOKEN SECUNDARIO'
DEFINE LOG_FILE = 'Logs/Identidade_Empresa_Variacoes_READONLY.log'

SPOOL "&LOG_FILE"
PROMPT === IDENTIDADE EMPRESA - VARIACOES READ-ONLY ===
PROMPT NOME_INFORMADO=&NOME_INFORMADO

SELECT CODEMP,
       TRIM(NOMEFANTASIA) AS NOMEFANTASIA,
       TRIM(RAZAOSOCIAL) AS RAZAOSOCIAL,
       CASE
         WHEN UPPER(TRIM(RAZAOSOCIAL))=UPPER(TRIM('&NOME_INFORMADO'))
           THEN 'RAZAO_SOCIAL_EXATA'
         ELSE 'VARIACAO_PARA_VALIDAR'
       END AS CLASSIFICACAO
  FROM TSIEMP
 WHERE UPPER(TRIM(RAZAOSOCIAL))=UPPER(TRIM('&NOME_INFORMADO'))
    OR UPPER(TRIM(NOMEFANTASIA)) LIKE '%'||UPPER(TRIM('&TOKEN_1'))||'%'
    OR UPPER(TRIM(RAZAOSOCIAL)) LIKE '%'||UPPER(TRIM('&TOKEN_1'))||'%'
    OR UPPER(TRIM(NOMEFANTASIA)) LIKE '%'||UPPER(TRIM('&TOKEN_2'))||'%'
    OR UPPER(TRIM(RAZAOSOCIAL)) LIKE '%'||UPPER(TRIM('&TOKEN_2'))||'%'
 ORDER BY CODEMP;

SELECT COUNT(*) AS QTD_RAZAO_EXATA
  FROM TSIEMP
 WHERE UPPER(TRIM(RAZAOSOCIAL))=UPPER(TRIM('&NOME_INFORMADO'));

SELECT COUNT(*) AS QTD_VARIACOES_LOCALIZADAS
  FROM TSIEMP
 WHERE UPPER(TRIM(NOMEFANTASIA)) LIKE '%'||UPPER(TRIM('&TOKEN_1'))||'%'
    OR UPPER(TRIM(RAZAOSOCIAL)) LIKE '%'||UPPER(TRIM('&TOKEN_1'))||'%'
    OR UPPER(TRIM(NOMEFANTASIA)) LIKE '%'||UPPER(TRIM('&TOKEN_2'))||'%'
    OR UPPER(TRIM(RAZAOSOCIAL)) LIKE '%'||UPPER(TRIM('&TOKEN_2'))||'%';

PROMPT Resultado read-only; manter divergencias, contagens e autorizacao em registro separado.
SPOOL OFF
