-- Precheck consolidado e somente leitura das etapas 18 a 31.
SET DEFINE OFF
SET ECHO ON
SET PAGESIZE 200
SET LINESIZE 240

PROMPT === IDENTIDADE ===
SELECT SYS_CONTEXT('USERENV','SESSION_USER') USUARIO,
       SYS_CONTEXT('USERENV','CURRENT_SCHEMA') SCHEMA_ATUAL,
       SYS_CONTEXT('USERENV','SERVICE_NAME') SERVICO FROM DUAL;

PROMPT === ETAPAS 18 A 23 ===
SELECT '18_TGFCGM_ORIGEM_EMP1_1900_1' ITEM,COUNT(*) QTD FROM TGFCGM WHERE CODEMP=1 AND ANO=1900 AND MES=1
UNION ALL SELECT '18_TGFCMV_CODCONFIG_1',COUNT(*) FROM TGFCMV WHERE CODCONFIG=1
UNION ALL SELECT '18_TGFCGM_DESTINOS',COUNT(*) FROM TGFCGM WHERE CODEMP<>1
UNION ALL SELECT '19_PARCEIROS_TOTAL',COUNT(*) FROM TGFPAR
UNION ALL SELECT '20_TTKINDAGT_SEQUENCIA_1',COUNT(*) FROM TTKINDAGT WHERE SEQUENCIA=1
UNION ALL SELECT '20_TTKNOT_TOTAL',COUNT(*) FROM TTKNOT
UNION ALL SELECT '20_TTKEVT_TOTAL',COUNT(*) FROM TTKEVT
UNION ALL SELECT '21_ICMS_DIVERGENTES',COUNT(*) FROM TGFPAR
 WHERE (TIPPESSOA='J' AND IDENTINSCESTAD IS NOT NULL AND UPPER(TRIM(IDENTINSCESTAD))<>'ISENTO' AND NVL(CLASSIFICMS,'Z')<>'R')
    OR (TIPPESSOA='F' AND IDENTINSCESTAD IS NOT NULL AND UPPER(TRIM(IDENTINSCESTAD))<>'ISENTO' AND NVL(CLASSIFICMS,'Z')<>'P')
    OR (NVL(UPPER(TRIM(IDENTINSCESTAD)),'ISENTO')='ISENTO' AND NVL(CLASSIFICMS,'Z')<>'C')
UNION ALL SELECT '22_PARCEIROS_A_ANALISAR',COUNT(*) FROM TGFPAR WHERE CGC_CPF IS NOT NULL
UNION ALL SELECT '23_OBJETOS_PENDENTES',COUNT(*) FROM RMD_CONTROLE_OBJETOS
 WHERE STATUS_ANTES='ENABLED' AND NVL(STATUS_DEPOIS,'PENDENTE')<>'ENABLED';

PROMPT === OBJETOS OBRIGATORIOS 18 A 31 ===
SELECT N.NOME OBJETO,N.TIPO_ESPERADO,
       NVL(O.OBJECT_TYPE,'AUSENTE') TIPO_ENCONTRADO,
       NVL(O.STATUS,'AUSENTE') STATUS
FROM (
 SELECT 'TGFCGM' NOME,'TABLE' TIPO_ESPERADO FROM DUAL UNION ALL SELECT 'TGFCMV','TABLE' FROM DUAL
 UNION ALL SELECT 'TTKINDAGT','TABLE' FROM DUAL UNION ALL SELECT 'TTKNOT','TABLE' FROM DUAL
 UNION ALL SELECT 'TTKEVT','TABLE' FROM DUAL UNION ALL SELECT 'TGFPAR','TABLE' FROM DUAL
 UNION ALL SELECT 'TGFPRO','TABLE' FROM DUAL UNION ALL SELECT 'TGFTIT','TABLE' FROM DUAL
 UNION ALL SELECT 'TSICID','TABLE' FROM DUAL UNION ALL SELECT 'TGFTPV','TABLE' FROM DUAL
 UNION ALL SELECT 'TSIBAI','TABLE' FROM DUAL UNION ALL SELECT 'TSIEND','TABLE' FROM DUAL
) N LEFT JOIN ALL_OBJECTS O
 ON O.OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND O.OBJECT_NAME=N.NOME AND O.OBJECT_TYPE=N.TIPO_ESPERADO
ORDER BY N.NOME;

PROMPT === VOLUMES DAS ETAPAS 24 A 28 ===
SELECT '24_TGFPAR_TOTAL' ITEM,COUNT(*) QTD FROM TGFPAR
UNION ALL SELECT '25_TGFPRO_TOTAL',COUNT(*) FROM TGFPRO
UNION ALL SELECT '26_TGFTIT_TOTAL',COUNT(*) FROM TGFTIT
UNION ALL SELECT '27_TSICID_TOTAL',COUNT(*) FROM TSICID
UNION ALL SELECT '28_TGFTPV_TOTAL',COUNT(*) FROM TGFTPV;

PROMPT === ETAPA 29 BAIRROS ===
SELECT 'TSIBAI_TOTAL' ITEM,COUNT(*) QTD FROM TSIBAI
UNION ALL
SELECT 'TSIBAI_GRUPOS_COLISAO',COUNT(*) FROM (
 SELECT REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEBAI),'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ','AAAAAEEEEIIIIOOOOOUUUUC')),' {2,}',' ') N
 FROM TSIBAI GROUP BY REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEBAI),'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ','AAAAAEEEEIIIIOOOOOUUUUC')),' {2,}',' ')
 HAVING COUNT(*)>1
);

PROMPT === ETAPA 30 ENDERECOS ===
SELECT 'TSIEND_TOTAL' ITEM,COUNT(*) QTD FROM TSIEND
UNION ALL
SELECT 'TSIEND_GRUPOS_COLISAO',COUNT(*) FROM (
 SELECT TIPO,REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEEND),'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ','AAAAAEEEEIIIIOOOOOUUUUC')),' {2,}',' ') N
 FROM TSIEND GROUP BY TIPO,REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEEND),'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ','AAAAAEEEEIIIIOOOOOUUUUC')),' {2,}',' ')
 HAVING COUNT(*)>1
);

PROMPT === ETAPA 31 OBJETOS INVALIDOS E PRIVILEGIO ===
SELECT 'OBJETOS_INVALIDOS' ITEM,COUNT(*) QTD FROM ALL_OBJECTS
 WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND STATUS='INVALID'
UNION ALL
SELECT 'ALTER_ANY_PROCEDURE',COUNT(*) FROM SESSION_PRIVS WHERE PRIVILEGE='ALTER ANY PROCEDURE';

PROMPT === FIM PRECHECK ETAPAS 18 A 31 ===
