-- Atividade 34 - Ajuste da empresa padrao (TSIUSU.CODEMP) de usuarios conforme o onboarding - MEDCHAP (MEDCHAPPRD).
-- Decisao do usuario em 25/09/2026 (chat da revisao), com base na evidencia do onboarding:
--   planilha de usuarios "FILIAL - CBS" = SPEDs "CBS" do cliente = CNPJ 00.577.604/0003-67 (Curitibanos/SC) = CODEMP 2.
-- Escopo fechado: CODUSU 81..92 (12 usuarios *.cbs@medchap.com.br), hoje com CODEMP 4 (PROWIN), para CODEMP 2.
-- ID_EXECUCAO=MEDCHAP_USUEMP_20260925_01; backup=BKP_RMD_MDCH_USUEMP01 (somente os 12 registros: ROWID, CODUSU, NOMEUSU, EMAIL, CODEMP).
-- Reversao: Artefatos_Revisao/Rollback/Reverter_34_Ajuste_Usuarios_Empresa_MEDCHAP.sql
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

DECLARE
  v_n NUMBER;
BEGIN
  IF SYS_CONTEXT('USERENV','SESSION_USER') <> 'FRANCISCO_JUNIOR'
     OR SYS_CONTEXT('USERENV','CURRENT_SCHEMA') <> 'SANKHYA'
     OR UPPER(SYS_CONTEXT('USERENV','SERVICE_NAME')) <> 'MEDCHAPPRD.SANKHYACLOUD.COM.BR' THEN
    RAISE_APPLICATION_ERROR(-20470,'Identidade MEDCHAPPRD divergente; atividade 34 bloqueada.');
  END IF;
  SELECT COUNT(*) INTO v_n FROM ALL_TABLES WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND TABLE_NAME='BKP_RMD_MDCH_USUEMP01';
  IF v_n > 0 THEN
    RAISE_APPLICATION_ERROR(-20471,'Backup da atividade 34 ja existe; gere novo ID antes de repetir.');
  END IF;
  SELECT COUNT(*) INTO v_n FROM TSIEMP WHERE CODEMP=2 AND REGEXP_REPLACE(TO_CHAR(CGC),'[^0-9]','')='00577604000367';
  IF v_n <> 1 THEN
    RAISE_APPLICATION_ERROR(-20472,'CODEMP 2 nao corresponde ao CNPJ 00.577.604/0003-67; atividade 34 bloqueada.');
  END IF;
  SELECT COUNT(*) INTO v_n FROM TSIUSU
   WHERE CODUSU BETWEEN 81 AND 92 AND CODEMP=4 AND LOWER(TRIM(EMAIL)) LIKE '%.cbs@medchap.com.br';
  IF v_n <> 12 THEN
    RAISE_APPLICATION_ERROR(-20473,'Estado dos usuarios CBS diverge do diagnostico (esperado 12 com CODEMP 4, encontrado '||v_n||').');
  END IF;
  SELECT COUNT(*) INTO v_n FROM TSIUSU WHERE CODUSU BETWEEN 81 AND 92;
  IF v_n <> 12 THEN
    RAISE_APPLICATION_ERROR(-20474,'Faixa CODUSU 81..92 contem usuarios fora do escopo; atividade 34 bloqueada.');
  END IF;
  DBMS_OUTPUT.PUT_LINE('IDENTIDADE_VALIDADA=FRANCISCO_JUNIOR/SANKHYA/MEDCHAPPRD; PRECONDICOES_OK=12');
END;
/

CREATE TABLE BKP_RMD_MDCH_USUEMP01 AS
SELECT 'MEDCHAP_USUEMP_20260925_01' ID_EXECUCAO, SYSDATE DT_BACKUP, ROWIDTOCHAR(U.ROWID) RID_ORIGINAL,
       U.CODUSU, U.NOMEUSU, U.EMAIL, U.CODEMP
  FROM TSIUSU U
 WHERE U.CODUSU BETWEEN 81 AND 92 AND U.CODEMP=4 AND LOWER(TRIM(U.EMAIL)) LIKE '%.cbs@medchap.com.br'
/

DECLARE
  v_bkp NUMBER; v_upd NUMBER; v_chk NUMBER;
BEGIN
  EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM BKP_RMD_MDCH_USUEMP01 WHERE ID_EXECUCAO=:1 AND CODEMP=4' INTO v_bkp USING 'MEDCHAP_USUEMP_20260925_01';
  IF v_bkp <> 12 THEN
    RAISE_APPLICATION_ERROR(-20475,'Backup com '||v_bkp||' registros (esperado 12); nada alterado.');
  END IF;
  EXECUTE IMMEDIATE 'UPDATE TSIUSU U SET U.CODEMP=2 WHERE U.CODEMP=4 AND ROWIDTOCHAR(U.ROWID) IN (SELECT B.RID_ORIGINAL FROM BKP_RMD_MDCH_USUEMP01 B WHERE B.ID_EXECUCAO=:1)'
    USING 'MEDCHAP_USUEMP_20260925_01';
  v_upd := SQL%ROWCOUNT;
  IF v_upd <> 12 THEN
    RAISE_APPLICATION_ERROR(-20476,'UPDATE afetou '||v_upd||' registros (esperado 12); lote revertido.');
  END IF;
  SELECT COUNT(*) INTO v_chk FROM TSIUSU WHERE CODUSU BETWEEN 81 AND 92 AND CODEMP=2;
  IF v_chk <> 12 THEN
    RAISE_APPLICATION_ERROR(-20477,'Pos-checagem interna divergente ('||v_chk||'); lote revertido.');
  END IF;
  DBMS_OUTPUT.PUT_LINE('ID_EXECUCAO=MEDCHAP_USUEMP_20260925_01; BACKUP=12; ALTERADOS='||v_upd||'; CODEMP 4 -> 2');
  DBMS_OUTPUT.PUT_LINE('STATUS=USUARIOS_EMPRESA_AJUSTADOS');
END;
/
