-- Diagnostico read-only MEDCHAP: colunas texto dos cadastros TGFPRO/TGFPAR/TGFVEN/TSIUSU + charset da base. Sem DML/DDL.
SELECT 'COLUNA' TIPO, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, CHAR_LENGTH, CHAR_USED
  FROM ALL_TAB_COLUMNS
 WHERE OWNER = SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
   AND TABLE_NAME IN ('TGFPRO','TGFPAR','TGFVEN','TSIUSU')
   AND DATA_TYPE IN ('VARCHAR2','CHAR','NVARCHAR2','NCHAR')
UNION ALL
SELECT 'NLS', PARAMETER, VALUE, NULL, NULL, NULL, NULL
  FROM NLS_DATABASE_PARAMETERS WHERE PARAMETER IN ('NLS_CHARACTERSET','NLS_NCHAR_CHARACTERSET','NLS_LENGTH_SEMANTICS')
 ORDER BY 1, 2, 3
