-- Diagnostico read-only MEDCHAP: contagem de caracteres corrompidos nos cadastros essenciais. Sem DML/DDL.
SELECT 'TGFPRO' TABELA, 'DESCRPROD' COLUNA, COUNT(*) TOTAL_PREENCHIDO,
       SUM(CASE WHEN INSTR(DESCRPROD,UNISTR('\00BF'))>0 THEN 1 ELSE 0 END) QTD_INTERROGACAO_INVERTIDA,
       SUM(CASE WHEN REGEXP_LIKE(DESCRPROD,'('||UNISTR('\00C3')||'['||UNISTR('\0080')||'-'||UNISTR('\00BF')||']|'||UNISTR('\00C2')||'['||UNISTR('\00A0')||'-'||UNISTR('\00BF')||'])') THEN 1 ELSE 0 END) QTD_MOJIBAKE_UTF8,
       SUM(CASE WHEN REGEXP_LIKE(DESCRPROD,'[A-Za-z]\?[A-Za-z]') THEN 1 ELSE 0 END) QTD_INTERROGACAO_ENTRE_LETRAS
  FROM TGFPRO WHERE DESCRPROD IS NOT NULL
UNION ALL
SELECT 'TGFPRO' TABELA, 'COMPLDESC' COLUNA, COUNT(*) TOTAL_PREENCHIDO,
       SUM(CASE WHEN INSTR(COMPLDESC,UNISTR('\00BF'))>0 THEN 1 ELSE 0 END) QTD_INTERROGACAO_INVERTIDA,
       SUM(CASE WHEN REGEXP_LIKE(COMPLDESC,'('||UNISTR('\00C3')||'['||UNISTR('\0080')||'-'||UNISTR('\00BF')||']|'||UNISTR('\00C2')||'['||UNISTR('\00A0')||'-'||UNISTR('\00BF')||'])') THEN 1 ELSE 0 END) QTD_MOJIBAKE_UTF8,
       SUM(CASE WHEN REGEXP_LIKE(COMPLDESC,'[A-Za-z]\?[A-Za-z]') THEN 1 ELSE 0 END) QTD_INTERROGACAO_ENTRE_LETRAS
  FROM TGFPRO WHERE COMPLDESC IS NOT NULL
UNION ALL
SELECT 'TGFPRO' TABELA, 'DESCRPRODNFE' COLUNA, COUNT(*) TOTAL_PREENCHIDO,
       SUM(CASE WHEN INSTR(DESCRPRODNFE,UNISTR('\00BF'))>0 THEN 1 ELSE 0 END) QTD_INTERROGACAO_INVERTIDA,
       SUM(CASE WHEN REGEXP_LIKE(DESCRPRODNFE,'('||UNISTR('\00C3')||'['||UNISTR('\0080')||'-'||UNISTR('\00BF')||']|'||UNISTR('\00C2')||'['||UNISTR('\00A0')||'-'||UNISTR('\00BF')||'])') THEN 1 ELSE 0 END) QTD_MOJIBAKE_UTF8,
       SUM(CASE WHEN REGEXP_LIKE(DESCRPRODNFE,'[A-Za-z]\?[A-Za-z]') THEN 1 ELSE 0 END) QTD_INTERROGACAO_ENTRE_LETRAS
  FROM TGFPRO WHERE DESCRPRODNFE IS NOT NULL
UNION ALL
SELECT 'TGFPRO' TABELA, 'CARACTERISTICAS' COLUNA, COUNT(*) TOTAL_PREENCHIDO,
       SUM(CASE WHEN INSTR(CARACTERISTICAS,UNISTR('\00BF'))>0 THEN 1 ELSE 0 END) QTD_INTERROGACAO_INVERTIDA,
       SUM(CASE WHEN REGEXP_LIKE(CARACTERISTICAS,'('||UNISTR('\00C3')||'['||UNISTR('\0080')||'-'||UNISTR('\00BF')||']|'||UNISTR('\00C2')||'['||UNISTR('\00A0')||'-'||UNISTR('\00BF')||'])') THEN 1 ELSE 0 END) QTD_MOJIBAKE_UTF8,
       SUM(CASE WHEN REGEXP_LIKE(CARACTERISTICAS,'[A-Za-z]\?[A-Za-z]') THEN 1 ELSE 0 END) QTD_INTERROGACAO_ENTRE_LETRAS
  FROM TGFPRO WHERE CARACTERISTICAS IS NOT NULL
UNION ALL
SELECT 'TGFPRO' TABELA, 'MARCA' COLUNA, COUNT(*) TOTAL_PREENCHIDO,
       SUM(CASE WHEN INSTR(MARCA,UNISTR('\00BF'))>0 THEN 1 ELSE 0 END) QTD_INTERROGACAO_INVERTIDA,
       SUM(CASE WHEN REGEXP_LIKE(MARCA,'('||UNISTR('\00C3')||'['||UNISTR('\0080')||'-'||UNISTR('\00BF')||']|'||UNISTR('\00C2')||'['||UNISTR('\00A0')||'-'||UNISTR('\00BF')||'])') THEN 1 ELSE 0 END) QTD_MOJIBAKE_UTF8,
       SUM(CASE WHEN REGEXP_LIKE(MARCA,'[A-Za-z]\?[A-Za-z]') THEN 1 ELSE 0 END) QTD_INTERROGACAO_ENTRE_LETRAS
  FROM TGFPRO WHERE MARCA IS NOT NULL
UNION ALL
SELECT 'TGFPRO' TABELA, 'FABRICANTE' COLUNA, COUNT(*) TOTAL_PREENCHIDO,
       SUM(CASE WHEN INSTR(FABRICANTE,UNISTR('\00BF'))>0 THEN 1 ELSE 0 END) QTD_INTERROGACAO_INVERTIDA,
       SUM(CASE WHEN REGEXP_LIKE(FABRICANTE,'('||UNISTR('\00C3')||'['||UNISTR('\0080')||'-'||UNISTR('\00BF')||']|'||UNISTR('\00C2')||'['||UNISTR('\00A0')||'-'||UNISTR('\00BF')||'])') THEN 1 ELSE 0 END) QTD_MOJIBAKE_UTF8,
       SUM(CASE WHEN REGEXP_LIKE(FABRICANTE,'[A-Za-z]\?[A-Za-z]') THEN 1 ELSE 0 END) QTD_INTERROGACAO_ENTRE_LETRAS
  FROM TGFPRO WHERE FABRICANTE IS NOT NULL
UNION ALL
SELECT 'TGFPRO' TABELA, 'CIENTIFICO' COLUNA, COUNT(*) TOTAL_PREENCHIDO,
       SUM(CASE WHEN INSTR(CIENTIFICO,UNISTR('\00BF'))>0 THEN 1 ELSE 0 END) QTD_INTERROGACAO_INVERTIDA,
       SUM(CASE WHEN REGEXP_LIKE(CIENTIFICO,'('||UNISTR('\00C3')||'['||UNISTR('\0080')||'-'||UNISTR('\00BF')||']|'||UNISTR('\00C2')||'['||UNISTR('\00A0')||'-'||UNISTR('\00BF')||'])') THEN 1 ELSE 0 END) QTD_MOJIBAKE_UTF8,
       SUM(CASE WHEN REGEXP_LIKE(CIENTIFICO,'[A-Za-z]\?[A-Za-z]') THEN 1 ELSE 0 END) QTD_INTERROGACAO_ENTRE_LETRAS
  FROM TGFPRO WHERE CIENTIFICO IS NOT NULL
UNION ALL
SELECT 'TGFPRO' TABELA, 'DESCRANP' COLUNA, COUNT(*) TOTAL_PREENCHIDO,
       SUM(CASE WHEN INSTR(DESCRANP,UNISTR('\00BF'))>0 THEN 1 ELSE 0 END) QTD_INTERROGACAO_INVERTIDA,
       SUM(CASE WHEN REGEXP_LIKE(DESCRANP,'('||UNISTR('\00C3')||'['||UNISTR('\0080')||'-'||UNISTR('\00BF')||']|'||UNISTR('\00C2')||'['||UNISTR('\00A0')||'-'||UNISTR('\00BF')||'])') THEN 1 ELSE 0 END) QTD_MOJIBAKE_UTF8,
       SUM(CASE WHEN REGEXP_LIKE(DESCRANP,'[A-Za-z]\?[A-Za-z]') THEN 1 ELSE 0 END) QTD_INTERROGACAO_ENTRE_LETRAS
  FROM TGFPRO WHERE DESCRANP IS NOT NULL
UNION ALL
SELECT 'TGFPRO' TABELA, 'OBSETIQUETA' COLUNA, COUNT(*) TOTAL_PREENCHIDO,
       SUM(CASE WHEN INSTR(OBSETIQUETA,UNISTR('\00BF'))>0 THEN 1 ELSE 0 END) QTD_INTERROGACAO_INVERTIDA,
       SUM(CASE WHEN REGEXP_LIKE(OBSETIQUETA,'('||UNISTR('\00C3')||'['||UNISTR('\0080')||'-'||UNISTR('\00BF')||']|'||UNISTR('\00C2')||'['||UNISTR('\00A0')||'-'||UNISTR('\00BF')||'])') THEN 1 ELSE 0 END) QTD_MOJIBAKE_UTF8,
       SUM(CASE WHEN REGEXP_LIKE(OBSETIQUETA,'[A-Za-z]\?[A-Za-z]') THEN 1 ELSE 0 END) QTD_INTERROGACAO_ENTRE_LETRAS
  FROM TGFPRO WHERE OBSETIQUETA IS NOT NULL
UNION ALL
SELECT 'TGFPAR' TABELA, 'NOMEPARC' COLUNA, COUNT(*) TOTAL_PREENCHIDO,
       SUM(CASE WHEN INSTR(NOMEPARC,UNISTR('\00BF'))>0 THEN 1 ELSE 0 END) QTD_INTERROGACAO_INVERTIDA,
       SUM(CASE WHEN REGEXP_LIKE(NOMEPARC,'('||UNISTR('\00C3')||'['||UNISTR('\0080')||'-'||UNISTR('\00BF')||']|'||UNISTR('\00C2')||'['||UNISTR('\00A0')||'-'||UNISTR('\00BF')||'])') THEN 1 ELSE 0 END) QTD_MOJIBAKE_UTF8,
       SUM(CASE WHEN REGEXP_LIKE(NOMEPARC,'[A-Za-z]\?[A-Za-z]') THEN 1 ELSE 0 END) QTD_INTERROGACAO_ENTRE_LETRAS
  FROM TGFPAR WHERE NOMEPARC IS NOT NULL
UNION ALL
SELECT 'TGFPAR' TABELA, 'RAZAOSOCIAL' COLUNA, COUNT(*) TOTAL_PREENCHIDO,
       SUM(CASE WHEN INSTR(RAZAOSOCIAL,UNISTR('\00BF'))>0 THEN 1 ELSE 0 END) QTD_INTERROGACAO_INVERTIDA,
       SUM(CASE WHEN REGEXP_LIKE(RAZAOSOCIAL,'('||UNISTR('\00C3')||'['||UNISTR('\0080')||'-'||UNISTR('\00BF')||']|'||UNISTR('\00C2')||'['||UNISTR('\00A0')||'-'||UNISTR('\00BF')||'])') THEN 1 ELSE 0 END) QTD_MOJIBAKE_UTF8,
       SUM(CASE WHEN REGEXP_LIKE(RAZAOSOCIAL,'[A-Za-z]\?[A-Za-z]') THEN 1 ELSE 0 END) QTD_INTERROGACAO_ENTRE_LETRAS
  FROM TGFPAR WHERE RAZAOSOCIAL IS NOT NULL
UNION ALL
SELECT 'TGFPAR' TABELA, 'COMPLEMENTO' COLUNA, COUNT(*) TOTAL_PREENCHIDO,
       SUM(CASE WHEN INSTR(COMPLEMENTO,UNISTR('\00BF'))>0 THEN 1 ELSE 0 END) QTD_INTERROGACAO_INVERTIDA,
       SUM(CASE WHEN REGEXP_LIKE(COMPLEMENTO,'('||UNISTR('\00C3')||'['||UNISTR('\0080')||'-'||UNISTR('\00BF')||']|'||UNISTR('\00C2')||'['||UNISTR('\00A0')||'-'||UNISTR('\00BF')||'])') THEN 1 ELSE 0 END) QTD_MOJIBAKE_UTF8,
       SUM(CASE WHEN REGEXP_LIKE(COMPLEMENTO,'[A-Za-z]\?[A-Za-z]') THEN 1 ELSE 0 END) QTD_INTERROGACAO_ENTRE_LETRAS
  FROM TGFPAR WHERE COMPLEMENTO IS NOT NULL
UNION ALL
SELECT 'TGFPAR' TABELA, 'OBSERVACOES' COLUNA, COUNT(*) TOTAL_PREENCHIDO,
       SUM(CASE WHEN INSTR(OBSERVACOES,UNISTR('\00BF'))>0 THEN 1 ELSE 0 END) QTD_INTERROGACAO_INVERTIDA,
       SUM(CASE WHEN REGEXP_LIKE(OBSERVACOES,'('||UNISTR('\00C3')||'['||UNISTR('\0080')||'-'||UNISTR('\00BF')||']|'||UNISTR('\00C2')||'['||UNISTR('\00A0')||'-'||UNISTR('\00BF')||'])') THEN 1 ELSE 0 END) QTD_MOJIBAKE_UTF8,
       SUM(CASE WHEN REGEXP_LIKE(OBSERVACOES,'[A-Za-z]\?[A-Za-z]') THEN 1 ELSE 0 END) QTD_INTERROGACAO_ENTRE_LETRAS
  FROM TGFPAR WHERE OBSERVACOES IS NOT NULL
UNION ALL
SELECT 'TGFVEN' TABELA, 'APELIDO' COLUNA, COUNT(*) TOTAL_PREENCHIDO,
       SUM(CASE WHEN INSTR(APELIDO,UNISTR('\00BF'))>0 THEN 1 ELSE 0 END) QTD_INTERROGACAO_INVERTIDA,
       SUM(CASE WHEN REGEXP_LIKE(APELIDO,'('||UNISTR('\00C3')||'['||UNISTR('\0080')||'-'||UNISTR('\00BF')||']|'||UNISTR('\00C2')||'['||UNISTR('\00A0')||'-'||UNISTR('\00BF')||'])') THEN 1 ELSE 0 END) QTD_MOJIBAKE_UTF8,
       SUM(CASE WHEN REGEXP_LIKE(APELIDO,'[A-Za-z]\?[A-Za-z]') THEN 1 ELSE 0 END) QTD_INTERROGACAO_ENTRE_LETRAS
  FROM TGFVEN WHERE APELIDO IS NOT NULL
UNION ALL
SELECT 'TSIUSU' TABELA, 'NOMEUSU' COLUNA, COUNT(*) TOTAL_PREENCHIDO,
       SUM(CASE WHEN INSTR(NOMEUSU,UNISTR('\00BF'))>0 THEN 1 ELSE 0 END) QTD_INTERROGACAO_INVERTIDA,
       SUM(CASE WHEN REGEXP_LIKE(NOMEUSU,'('||UNISTR('\00C3')||'['||UNISTR('\0080')||'-'||UNISTR('\00BF')||']|'||UNISTR('\00C2')||'['||UNISTR('\00A0')||'-'||UNISTR('\00BF')||'])') THEN 1 ELSE 0 END) QTD_MOJIBAKE_UTF8,
       SUM(CASE WHEN REGEXP_LIKE(NOMEUSU,'[A-Za-z]\?[A-Za-z]') THEN 1 ELSE 0 END) QTD_INTERROGACAO_ENTRE_LETRAS
  FROM TSIUSU WHERE NOMEUSU IS NOT NULL
UNION ALL
SELECT 'TSIUSU' TABELA, 'NOMEUSUCPLT' COLUNA, COUNT(*) TOTAL_PREENCHIDO,
       SUM(CASE WHEN INSTR(NOMEUSUCPLT,UNISTR('\00BF'))>0 THEN 1 ELSE 0 END) QTD_INTERROGACAO_INVERTIDA,
       SUM(CASE WHEN REGEXP_LIKE(NOMEUSUCPLT,'('||UNISTR('\00C3')||'['||UNISTR('\0080')||'-'||UNISTR('\00BF')||']|'||UNISTR('\00C2')||'['||UNISTR('\00A0')||'-'||UNISTR('\00BF')||'])') THEN 1 ELSE 0 END) QTD_MOJIBAKE_UTF8,
       SUM(CASE WHEN REGEXP_LIKE(NOMEUSUCPLT,'[A-Za-z]\?[A-Za-z]') THEN 1 ELSE 0 END) QTD_INTERROGACAO_ENTRE_LETRAS
  FROM TSIUSU WHERE NOMEUSUCPLT IS NOT NULL
