-- Diagnostico read-only MEDCHAP: registros com caracteres fora do conjunto esperado (ASCIISTR mostra o codigo do caractere). Sem DML/DDL.
-- R04: aspas simples/duplas e ponto e virgula via CHR().
SELECT * FROM (
SELECT 'TGFPRO' TABELA, 'DESCRPROD' COLUNA, TO_CHAR(CODPROD) CHAVE, DESCRPROD VALOR, ASCIISTR(DESCRPROD) VALOR_ASCIISTR FROM TGFPRO WHERE REGEXP_LIKE(DESCRPROD, '[^A-Za-z0-9 .,'||CHR(59)||':/()&+%#@!?*_=<>|$'||CHR(39)||CHR(34)||'\[\]{}~^`ºª°§ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇÑÝáàâãäéèêëíìîïóòôõöúùûüçñý-]') OR REGEXP_LIKE(DESCRPROD,'[A-Za-z]\?[A-Za-z]') OR INSTR(DESCRPROD,UNISTR('\00BF'))>0
UNION ALL
SELECT 'TGFPRO' TABELA, 'COMPLDESC' COLUNA, TO_CHAR(CODPROD) CHAVE, COMPLDESC VALOR, ASCIISTR(COMPLDESC) VALOR_ASCIISTR FROM TGFPRO WHERE REGEXP_LIKE(COMPLDESC, '[^A-Za-z0-9 .,'||CHR(59)||':/()&+%#@!?*_=<>|$'||CHR(39)||CHR(34)||'\[\]{}~^`ºª°§ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇÑÝáàâãäéèêëíìîïóòôõöúùûüçñý-]') OR REGEXP_LIKE(COMPLDESC,'[A-Za-z]\?[A-Za-z]') OR INSTR(COMPLDESC,UNISTR('\00BF'))>0
UNION ALL
SELECT 'TGFPRO' TABELA, 'DESCRANP' COLUNA, TO_CHAR(CODPROD) CHAVE, DESCRANP VALOR, ASCIISTR(DESCRANP) VALOR_ASCIISTR FROM TGFPRO WHERE REGEXP_LIKE(DESCRANP, '[^A-Za-z0-9 .,'||CHR(59)||':/()&+%#@!?*_=<>|$'||CHR(39)||CHR(34)||'\[\]{}~^`ºª°§ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇÑÝáàâãäéèêëíìîïóòôõöúùûüçñý-]') OR REGEXP_LIKE(DESCRANP,'[A-Za-z]\?[A-Za-z]') OR INSTR(DESCRANP,UNISTR('\00BF'))>0
UNION ALL
SELECT 'TGFPAR' TABELA, 'NOMEPARC' COLUNA, TO_CHAR(CODPARC) CHAVE, NOMEPARC VALOR, ASCIISTR(NOMEPARC) VALOR_ASCIISTR FROM TGFPAR WHERE REGEXP_LIKE(NOMEPARC, '[^A-Za-z0-9 .,'||CHR(59)||':/()&+%#@!?*_=<>|$'||CHR(39)||CHR(34)||'\[\]{}~^`ºª°§ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇÑÝáàâãäéèêëíìîïóòôõöúùûüçñý-]') OR REGEXP_LIKE(NOMEPARC,'[A-Za-z]\?[A-Za-z]') OR INSTR(NOMEPARC,UNISTR('\00BF'))>0
UNION ALL
SELECT 'TGFPAR' TABELA, 'RAZAOSOCIAL' COLUNA, TO_CHAR(CODPARC) CHAVE, RAZAOSOCIAL VALOR, ASCIISTR(RAZAOSOCIAL) VALOR_ASCIISTR FROM TGFPAR WHERE REGEXP_LIKE(RAZAOSOCIAL, '[^A-Za-z0-9 .,'||CHR(59)||':/()&+%#@!?*_=<>|$'||CHR(39)||CHR(34)||'\[\]{}~^`ºª°§ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇÑÝáàâãäéèêëíìîïóòôõöúùûüçñý-]') OR REGEXP_LIKE(RAZAOSOCIAL,'[A-Za-z]\?[A-Za-z]') OR INSTR(RAZAOSOCIAL,UNISTR('\00BF'))>0
UNION ALL
SELECT 'TGFPAR' TABELA, 'COMPLEMENTO' COLUNA, TO_CHAR(CODPARC) CHAVE, COMPLEMENTO VALOR, ASCIISTR(COMPLEMENTO) VALOR_ASCIISTR FROM TGFPAR WHERE REGEXP_LIKE(COMPLEMENTO, '[^A-Za-z0-9 .,'||CHR(59)||':/()&+%#@!?*_=<>|$'||CHR(39)||CHR(34)||'\[\]{}~^`ºª°§ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇÑÝáàâãäéèêëíìîïóòôõöúùûüçñý-]') OR REGEXP_LIKE(COMPLEMENTO,'[A-Za-z]\?[A-Za-z]') OR INSTR(COMPLEMENTO,UNISTR('\00BF'))>0
UNION ALL
SELECT 'TGFVEN' TABELA, 'APELIDO' COLUNA, TO_CHAR(CODVEND) CHAVE, APELIDO VALOR, ASCIISTR(APELIDO) VALOR_ASCIISTR FROM TGFVEN WHERE REGEXP_LIKE(APELIDO, '[^A-Za-z0-9 .,'||CHR(59)||':/()&+%#@!?*_=<>|$'||CHR(39)||CHR(34)||'\[\]{}~^`ºª°§ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇÑÝáàâãäéèêëíìîïóòôõöúùûüçñý-]') OR REGEXP_LIKE(APELIDO,'[A-Za-z]\?[A-Za-z]') OR INSTR(APELIDO,UNISTR('\00BF'))>0
UNION ALL
SELECT 'TSIUSU' TABELA, 'NOMEUSU' COLUNA, TO_CHAR(CODUSU) CHAVE, NOMEUSU VALOR, ASCIISTR(NOMEUSU) VALOR_ASCIISTR FROM TSIUSU WHERE REGEXP_LIKE(NOMEUSU, '[^A-Za-z0-9 .,'||CHR(59)||':/()&+%#@!?*_=<>|$'||CHR(39)||CHR(34)||'\[\]{}~^`ºª°§ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇÑÝáàâãäéèêëíìîïóòôõöúùûüçñý-]') OR REGEXP_LIKE(NOMEUSU,'[A-Za-z]\?[A-Za-z]') OR INSTR(NOMEUSU,UNISTR('\00BF'))>0
UNION ALL
SELECT 'TSIUSU' TABELA, 'NOMEUSUCPLT' COLUNA, TO_CHAR(CODUSU) CHAVE, NOMEUSUCPLT VALOR, ASCIISTR(NOMEUSUCPLT) VALOR_ASCIISTR FROM TSIUSU WHERE REGEXP_LIKE(NOMEUSUCPLT, '[^A-Za-z0-9 .,'||CHR(59)||':/()&+%#@!?*_=<>|$'||CHR(39)||CHR(34)||'\[\]{}~^`ºª°§ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇÑÝáàâãäéèêëíìîïóòôõöúùûüçñý-]') OR REGEXP_LIKE(NOMEUSUCPLT,'[A-Za-z]\?[A-Za-z]') OR INSTR(NOMEUSUCPLT,UNISTR('\00BF'))>0
) WHERE ROWNUM <= 500
