-- Read-only: conteudo do mapa da atividade 33 (MEDCHAP_CAR_20260925_02) e do backup.
SELECT M.TABELA, M.COLUNA, M.CHAVE, ASCIISTR(M.VALOR_ANTES) VALOR_ANTES, M.VALOR_DEPOIS, M.REGRA, M.STATUS, ASCIISTR(M.DETALHE) DETALHE,
       (SELECT ASCIISTR(B.NOMEUSU) FROM BKP_RMD_MDCH_CAR02_TSIUSU B WHERE B.RID_ORIGINAL=M.RID) BACKUP_NOMEUSU
  FROM RMD_MDCH_CAR_20260925_02 M WHERE M.ID_EXECUCAO='MEDCHAP_CAR_20260925_02'
