-- Read-only: teste do dicionario da atividade 33 (palavra com e sem acento nas fontes do corpus).
SELECT 'TSIEND_GONCALVES' ITEM, COUNT(*) QTD FROM TSIEND WHERE INSTR(' '||UPPER(REGEXP_REPLACE(NOMEEND,'[ .,/()-]',' '))||' ',' GONCALVES ')>0
UNION ALL SELECT 'TSIEND_GONCALVES_ACENTO', COUNT(*) FROM TSIEND WHERE INSTR(' '||UPPER(REGEXP_REPLACE(NOMEEND,'[ .,/()-]',' '))||' ',' GON'||TO_CHAR(UNISTR('\00C7'))||'ALVES ')>0
UNION ALL SELECT 'TGFPAR_GONCALVES', COUNT(*) FROM TGFPAR WHERE INSTR(' '||UPPER(REGEXP_REPLACE(NOMEPARC,'[ .,/()-]',' '))||' ',' GONCALVES ')>0
UNION ALL SELECT 'TGFPAR_GONCALVES_ACENTO', COUNT(*) FROM TGFPAR WHERE INSTR(' '||UPPER(REGEXP_REPLACE(NOMEPARC,'[ .,/()-]',' '))||' ',' GON'||TO_CHAR(UNISTR('\00C7'))||'ALVES ')>0
UNION ALL SELECT 'TGFPAR_COM_ACENTO', COUNT(*) FROM TGFPAR WHERE REGEXP_LIKE(NOMEPARC,'['||TO_CHAR(UNISTR('\00C0-\00FF'))||']')
UNION ALL SELECT 'TGFPRO_COM_ACENTO', COUNT(*) FROM TGFPRO WHERE REGEXP_LIKE(DESCRPROD,'['||TO_CHAR(UNISTR('\00C0-\00FF'))||']')
