-- Exclusao final somente apos a fase antifragil registrar referencias=0.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER OSERROR EXIT FAILURE ROLLBACK
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
DELETE FROM TSIBAI
 WHERE CODBAI IN (
   SELECT COD_OBSOLETO
     FROM RMD_JCLM_MRG_20260919
    WHERE ID_EXECUCAO='JCLM_MRG_20260919_01'
      AND TIPO='BAI'
 );
DELETE FROM TSIEND
 WHERE CODEND IN (
   SELECT COD_OBSOLETO
     FROM RMD_JCLM_MRG_20260919
    WHERE ID_EXECUCAO='JCLM_MRG_20260919_01'
      AND TIPO='END'
 );
COMMIT;
