-- Fase antifragil especifica da JCLM apos a normalizacao 29/30.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET SQLBLANKLINES ON
WHENEVER OSERROR EXIT FAILURE ROLLBACK
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
BEGIN
  DBMS_SESSION.SET_IDENTIFIER('JCLM_MERGE');
END;
/
@@../../Revisao Master Deploy/29_30_Merge_Antifragil.sql
