-- Exclusao final autorizada da JCLM.
-- O mapa e os backups persistentes foram validados antes deste lote.
-- A reversao pareada esta em 29_30_Merge_Antifragil_JCLM_Rollback.sql.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER OSERROR EXIT FAILURE ROLLBACK
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

SELECT 'PRE_DELETE_MAPA_BAI' AS INDICADOR, COUNT(*) AS QUANTIDADE
  FROM RMD_JCLM_MRG_20260919
 WHERE ID_EXECUCAO='JCLM_MRG_20260919_01' AND TIPO='BAI'
UNION ALL
SELECT 'PRE_DELETE_MAPA_END', COUNT(*)
  FROM RMD_JCLM_MRG_20260919
 WHERE ID_EXECUCAO='JCLM_MRG_20260919_01' AND TIPO='END'
UNION ALL
SELECT 'PRE_DELETE_BACKUP_BAI', COUNT(*)
  FROM RMD_JCLM_MRG_20260919_BAI
 WHERE ID_EXECUCAO='JCLM_MRG_20260919_01'
UNION ALL
SELECT 'PRE_DELETE_BACKUP_END', COUNT(*)
  FROM RMD_JCLM_MRG_20260919_END
 WHERE ID_EXECUCAO='JCLM_MRG_20260919_01'
UNION ALL
SELECT 'PRE_DELETE_DEPENDENCIAS', COUNT(*)
  FROM RMD_JCLM_MRG_20260919_DEP
 WHERE ID_EXECUCAO='JCLM_MRG_20260919_01'
UNION ALL
SELECT 'PRE_DELETE_EXCECOES', COUNT(*)
  FROM RMD_JCLM_MRG_20260919_EXC
 WHERE ID_EXECUCAO='JCLM_MRG_20260919_01'
UNION ALL
SELECT 'PRE_DELETE_PAI_BAI', COUNT(*)
  FROM TSIBAI
 WHERE CODBAI IN (
       SELECT COD_OBSOLETO
         FROM RMD_JCLM_MRG_20260919
        WHERE ID_EXECUCAO='JCLM_MRG_20260919_01' AND TIPO='BAI'
   )
UNION ALL
SELECT 'PRE_DELETE_PAI_END', COUNT(*)
  FROM TSIEND
 WHERE CODEND IN (
       SELECT COD_OBSOLETO
         FROM RMD_JCLM_MRG_20260919
        WHERE ID_EXECUCAO='JCLM_MRG_20260919_01' AND TIPO='END'
   )
ORDER BY 1;

DELETE FROM TSIBAI
 WHERE CODBAI IN (
       SELECT COD_OBSOLETO
         FROM RMD_JCLM_MRG_20260919
        WHERE ID_EXECUCAO='JCLM_MRG_20260919_01' AND TIPO='BAI'
   );

DELETE FROM TSIEND
 WHERE CODEND IN (
       SELECT COD_OBSOLETO
         FROM RMD_JCLM_MRG_20260919
        WHERE ID_EXECUCAO='JCLM_MRG_20260919_01' AND TIPO='END'
   );

COMMIT;
