-- Reversao pareada do merge antifragil da JCLM.
-- Restaura pais excluidos pelos backups persistentes e referencias pelas
-- linhas auditadas no mapa de dependencias. Os artefatos sao preservados.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER OSERROR EXIT FAILURE ROLLBACK
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

INSERT INTO TSIBAI
       (CODBAI,NOMEBAI,CODREG,DTALTER,DESCRICAOCORREIO,NUVERSAO,ATUNUVERSAO)
SELECT B.CODBAI,B.NOMEBAI,B.CODREG,B.DTALTER,B.DESCRICAOCORREIO,B.NUVERSAO,B.ATUNUVERSAO
  FROM RMD_JCLM_MRG_20260919_BAI B
 WHERE B.ID_EXECUCAO='JCLM_MRG_20260919_01'
   AND B.CODBAI IN (
       SELECT COD_OBSOLETO
         FROM RMD_JCLM_MRG_20260919
        WHERE ID_EXECUCAO='JCLM_MRG_20260919_01' AND TIPO='BAI'
   )
   AND NOT EXISTS (SELECT 1 FROM TSIBAI T WHERE T.CODBAI=B.CODBAI);

INSERT INTO TSIEND
       (CODEND,NOMEEND,TIPO,DTALTER,DESCRICAOCORREIO,CODLOGRADOURO,NUVERSAO,ATUNUVERSAO)
SELECT B.CODEND,B.NOMEEND,B.TIPO,B.DTALTER,B.DESCRICAOCORREIO,B.CODLOGRADOURO,B.NUVERSAO,B.ATUNUVERSAO
  FROM RMD_JCLM_MRG_20260919_END B
 WHERE B.ID_EXECUCAO='JCLM_MRG_20260919_01'
   AND B.CODEND IN (
       SELECT COD_OBSOLETO
         FROM RMD_JCLM_MRG_20260919
        WHERE ID_EXECUCAO='JCLM_MRG_20260919_01' AND TIPO='END'
   )
   AND NOT EXISTS (SELECT 1 FROM TSIEND T WHERE T.CODEND=B.CODEND);

UPDATE BKP_RMD_PAD_TGFPAR
   SET CODBAI=(SELECT D.OLD_VALUE FROM RMD_JCLM_MRG_20260919_DEP D
                WHERE D.ID_EXECUCAO='JCLM_MRG_20260919_01'
                  AND D.TABLE_NAME='BKP_RMD_PAD_TGFPAR'
                  AND D.COLUMN_NAME='CODBAI'
                  AND D.RID=ROWIDTOCHAR(BKP_RMD_PAD_TGFPAR.ROWID))
 WHERE EXISTS (SELECT 1 FROM RMD_JCLM_MRG_20260919_DEP D
                WHERE D.ID_EXECUCAO='JCLM_MRG_20260919_01'
                  AND D.TABLE_NAME='BKP_RMD_PAD_TGFPAR'
                  AND D.COLUMN_NAME='CODBAI'
                  AND D.RID=ROWIDTOCHAR(BKP_RMD_PAD_TGFPAR.ROWID));

UPDATE BKP_RMD_PAD_TGFPAR
   SET CODEND=(SELECT D.OLD_VALUE FROM RMD_JCLM_MRG_20260919_DEP D
                WHERE D.ID_EXECUCAO='JCLM_MRG_20260919_01'
                  AND D.TABLE_NAME='BKP_RMD_PAD_TGFPAR'
                  AND D.COLUMN_NAME='CODEND'
                  AND D.RID=ROWIDTOCHAR(BKP_RMD_PAD_TGFPAR.ROWID))
 WHERE EXISTS (SELECT 1 FROM RMD_JCLM_MRG_20260919_DEP D
                WHERE D.ID_EXECUCAO='JCLM_MRG_20260919_01'
                  AND D.TABLE_NAME='BKP_RMD_PAD_TGFPAR'
                  AND D.COLUMN_NAME='CODEND'
                  AND D.RID=ROWIDTOCHAR(BKP_RMD_PAD_TGFPAR.ROWID));

UPDATE BKP_RMD_PAD_TSIEND
   SET CODEND=(SELECT D.OLD_VALUE FROM RMD_JCLM_MRG_20260919_DEP D
                WHERE D.ID_EXECUCAO='JCLM_MRG_20260919_01'
                  AND D.TABLE_NAME='BKP_RMD_PAD_TSIEND'
                  AND D.COLUMN_NAME='CODEND'
                  AND D.RID=ROWIDTOCHAR(BKP_RMD_PAD_TSIEND.ROWID))
 WHERE EXISTS (SELECT 1 FROM RMD_JCLM_MRG_20260919_DEP D
                WHERE D.ID_EXECUCAO='JCLM_MRG_20260919_01'
                  AND D.TABLE_NAME='BKP_RMD_PAD_TSIEND'
                  AND D.COLUMN_NAME='CODEND'
                  AND D.RID=ROWIDTOCHAR(BKP_RMD_PAD_TSIEND.ROWID));

UPDATE BKP_TGFPAR_NOVO
   SET CODBAI=(SELECT D.OLD_VALUE FROM RMD_JCLM_MRG_20260919_DEP D
                WHERE D.ID_EXECUCAO='JCLM_MRG_20260919_01'
                  AND D.TABLE_NAME='BKP_TGFPAR_NOVO'
                  AND D.COLUMN_NAME='CODBAI'
                  AND D.RID=ROWIDTOCHAR(BKP_TGFPAR_NOVO.ROWID))
 WHERE EXISTS (SELECT 1 FROM RMD_JCLM_MRG_20260919_DEP D
                WHERE D.ID_EXECUCAO='JCLM_MRG_20260919_01'
                  AND D.TABLE_NAME='BKP_TGFPAR_NOVO'
                  AND D.COLUMN_NAME='CODBAI'
                  AND D.RID=ROWIDTOCHAR(BKP_TGFPAR_NOVO.ROWID));

UPDATE BKP_TGFPAR_NOVO
   SET CODEND=(SELECT D.OLD_VALUE FROM RMD_JCLM_MRG_20260919_DEP D
                WHERE D.ID_EXECUCAO='JCLM_MRG_20260919_01'
                  AND D.TABLE_NAME='BKP_TGFPAR_NOVO'
                  AND D.COLUMN_NAME='CODEND'
                  AND D.RID=ROWIDTOCHAR(BKP_TGFPAR_NOVO.ROWID))
 WHERE EXISTS (SELECT 1 FROM RMD_JCLM_MRG_20260919_DEP D
                WHERE D.ID_EXECUCAO='JCLM_MRG_20260919_01'
                  AND D.TABLE_NAME='BKP_TGFPAR_NOVO'
                  AND D.COLUMN_NAME='CODEND'
                  AND D.RID=ROWIDTOCHAR(BKP_TGFPAR_NOVO.ROWID));

UPDATE TGFPAR
   SET CODBAI=(SELECT D.OLD_VALUE FROM RMD_JCLM_MRG_20260919_DEP D
                WHERE D.ID_EXECUCAO='JCLM_MRG_20260919_01'
                  AND D.TABLE_NAME='TGFPAR'
                  AND D.COLUMN_NAME='CODBAI'
                  AND D.RID=ROWIDTOCHAR(TGFPAR.ROWID))
 WHERE EXISTS (SELECT 1 FROM RMD_JCLM_MRG_20260919_DEP D
                WHERE D.ID_EXECUCAO='JCLM_MRG_20260919_01'
                  AND D.TABLE_NAME='TGFPAR'
                  AND D.COLUMN_NAME='CODBAI'
                  AND D.RID=ROWIDTOCHAR(TGFPAR.ROWID));

UPDATE TGFPAR
   SET CODEND=(SELECT D.OLD_VALUE FROM RMD_JCLM_MRG_20260919_DEP D
                WHERE D.ID_EXECUCAO='JCLM_MRG_20260919_01'
                  AND D.TABLE_NAME='TGFPAR'
                  AND D.COLUMN_NAME='CODEND'
                  AND D.RID=ROWIDTOCHAR(TGFPAR.ROWID))
 WHERE EXISTS (SELECT 1 FROM RMD_JCLM_MRG_20260919_DEP D
                WHERE D.ID_EXECUCAO='JCLM_MRG_20260919_01'
                  AND D.TABLE_NAME='TGFPAR'
                  AND D.COLUMN_NAME='CODEND'
                  AND D.RID=ROWIDTOCHAR(TGFPAR.ROWID));

UPDATE TSICEP
   SET CODBAI=(SELECT D.OLD_VALUE FROM RMD_JCLM_MRG_20260919_DEP D
                WHERE D.ID_EXECUCAO='JCLM_MRG_20260919_01'
                  AND D.TABLE_NAME='TSICEP'
                  AND D.COLUMN_NAME='CODBAI'
                  AND D.RID=ROWIDTOCHAR(TSICEP.ROWID))
 WHERE EXISTS (SELECT 1 FROM RMD_JCLM_MRG_20260919_DEP D
                WHERE D.ID_EXECUCAO='JCLM_MRG_20260919_01'
                  AND D.TABLE_NAME='TSICEP'
                  AND D.COLUMN_NAME='CODBAI'
                  AND D.RID=ROWIDTOCHAR(TSICEP.ROWID));

UPDATE TSICEP
   SET CODEND=(SELECT D.OLD_VALUE FROM RMD_JCLM_MRG_20260919_DEP D
                WHERE D.ID_EXECUCAO='JCLM_MRG_20260919_01'
                  AND D.TABLE_NAME='TSICEP'
                  AND D.COLUMN_NAME='CODEND'
                  AND D.RID=ROWIDTOCHAR(TSICEP.ROWID))
 WHERE EXISTS (SELECT 1 FROM RMD_JCLM_MRG_20260919_DEP D
                WHERE D.ID_EXECUCAO='JCLM_MRG_20260919_01'
                  AND D.TABLE_NAME='TSICEP'
                  AND D.COLUMN_NAME='CODEND'
                  AND D.RID=ROWIDTOCHAR(TSICEP.ROWID));

COMMIT;

SELECT 'ROLLBACK_BAI_PRESENTES' AS INDICADOR, COUNT(*) AS QUANTIDADE
  FROM TSIBAI
 WHERE CODBAI IN (SELECT COD_OBSOLETO FROM RMD_JCLM_MRG_20260919 WHERE ID_EXECUCAO='JCLM_MRG_20260919_01' AND TIPO='BAI')
UNION ALL
SELECT 'ROLLBACK_END_PRESENTES', COUNT(*)
  FROM TSIEND
 WHERE CODEND IN (SELECT COD_OBSOLETO FROM RMD_JCLM_MRG_20260919 WHERE ID_EXECUCAO='JCLM_MRG_20260919_01' AND TIPO='END')
ORDER BY 1;
