-- Card 09 - mapa direto por XML, sem dependencia de function auxiliar.
-- O filtro de candidatos replica a volumetria do dashboard e limita a massa
-- antes da leitura de TGFNFE.XML. Esta etapa nao altera TGFFIN.

SET DEFINE ON
SET SERVEROUTPUT ON SIZE UNLIMITED
SET SQLBLANKLINES ON
SET PAGESIZE 1000
SET TRIMSPOOL ON
WHENEVER OSERROR EXIT FAILURE ROLLBACK
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

DEFINE ID_EXECUCAO = 'JCLM_FDUP_20260919_01'
DEFINE TBL_BASE = 'BKP_RMD_JCLM_FDUP_20260919'
DEFINE TBL_PPG = 'BKP_RMD_JCLM_FDUP_20260919_PPG'
DEFINE LOG_FILE = 'Card09_Mapa_Direto_XML_JCLM_20260919.log'

SPOOL "&LOG_FILE"
PROMPT === CARD 09 - MAPA DIRETO XML ===
PROMPT ID_EXECUCAO=&ID_EXECUCAO
PROMPT FONTE_XML=TGFNFE.XML; EXTRACAO=XMLTABLE; FUNCTION=NAO_USADA; TGFFIN_ALTERADO=NAO

DECLARE
  v_qtd NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_qtd
    FROM ALL_TABLES
   WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
     AND TABLE_NAME IN ('&TBL_BASE','&TBL_PPG');
  IF v_qtd > 0 THEN
    RAISE_APPLICATION_ERROR(-20340,'Uma tabela do mapa ja existe; gere novo ID antes de repetir.');
  END IF;
END;
/

-- Volumetria do dashboard: somente TOP financeiro, movimento diferente de Z
-- e notas sem TGFFIN entram na massa lida em TGFNFE.
CREATE TABLE &TBL_BASE AS
WITH CANDIDATES AS (
  SELECT C.NUNOTA,C.CODEMP,C.NUMNOTA,C.SERIENOTA,C.DTNEG,C.DTMOV,
         C.CODPARC,C.CODTIPOPER,T.DESCROPER,C.VLRNOTA
    FROM TGFCAB C
    JOIN TGFTOP T ON T.CODTIPOPER=C.CODTIPOPER AND T.DHALTER=C.DHTIPOPER
   WHERE T.ATUALFIN<>0
     AND C.TIPMOV<>'Z'
     AND NOT EXISTS (SELECT 1 FROM TGFFIN F WHERE F.NUNOTA=C.NUNOTA)
), N AS (
  SELECT N.NUNOTA,N.XML,
         COUNT(*) OVER (PARTITION BY N.NUNOTA) AS QTD_XML_NUNOTA,
         ROW_NUMBER() OVER (PARTITION BY N.NUNOTA ORDER BY N.ROWID) AS RN
    FROM TGFNFE N
    JOIN CANDIDATES C ON C.NUNOTA=N.NUNOTA
)
SELECT '&ID_EXECUCAO' AS ID_EXECUCAO,
       SYSTIMESTAMP AS DH_EXECUCAO,
       SYS_CONTEXT('USERENV','SESSION_USER') AS USUARIO_EXECUCAO,
       C.NUNOTA,C.CODEMP,C.NUMNOTA,C.SERIENOTA,C.DTNEG,C.DTMOV,
       C.CODPARC,C.CODTIPOPER,C.DESCROPER,C.VLRNOTA,
       NVL(N.QTD_XML_NUNOTA,0) AS QTD_XML_NUNOTA,
       X.VDUP_XML,X.DVENC_XML,X.NDUP_XML
  FROM CANDIDATES C
  LEFT JOIN N ON N.NUNOTA=C.NUNOTA AND N.RN=1
  OUTER APPLY XMLTABLE(
    '//*[local-name()="dup"][1]'
    PASSING XMLTYPE(N.XML)
    COLUMNS
      VDUP_XML VARCHAR2(4000) PATH '*[local-name()="vDup"][1]/text()',
      DVENC_XML VARCHAR2(4000) PATH '*[local-name()="dVenc"][1]/text()',
      NDUP_XML VARCHAR2(4000) PATH '*[local-name()="nDup"][1]/text()'
  ) X;

-- Classificacao persistente. Linhas inelegiveis permanecem no mapa para
-- auditoria, mas nunca entram no executor 32B.
CREATE TABLE &TBL_PPG AS
WITH C AS (
  SELECT B.ID_EXECUCAO,B.DH_EXECUCAO,B.USUARIO_EXECUCAO,
         B.NUNOTA,B.CODEMP,B.NUMNOTA,B.SERIENOTA,B.DTNEG,
         B.CODPARC,B.CODTIPOPER,B.DESCROPER,C.CODTIPVENDA,
         C.DHTIPOPER,C.DTENTSAI,C.DTMOV,C.DHTIPVENDA,C.CODVEND,
         C.CODNAT CODNAT_CAB,C.CODCENCUS CODCENCUS_CAB,
         C.CODPROJ CODPROJ_CAB,C.RATEADO RATEADO_CAB,
         B.VLRNOTA,B.QTD_XML_NUNOTA,B.VDUP_XML,B.DVENC_XML,B.NDUP_XML
    FROM &TBL_BASE B JOIN TGFCAB C ON C.NUNOTA=B.NUNOTA
   WHERE B.ID_EXECUCAO='&ID_EXECUCAO'
), P AS (
  SELECT C.*,P.TIPOEMP,P.CODEMP CODEMP_PPG,P.TIPOPAR,
         P.CODPARC CODPARC_PPG,P.SEQUENCIA SEQ_PPG,P.PRAZO,
         P.CODTIPTITPAD,P.CODBCOPAD,P.CODCTABCOINT,
         P.CODCENCUSPAD,P.CODNATPAD,P.CODPROJPAD,
         P.TIPRECDESP,P.TIPOFIN,P.PERCENTUAL,
         COUNT(P.CODTIPVENDA) OVER(PARTITION BY C.NUNOTA) QTD_PPG_ENCONTRADAS,
         COUNT(P.CODTIPVENDA) OVER(PARTITION BY C.NUNOTA,P.SEQUENCIA) QTD_PPG_MESMA_SEQ
    FROM C LEFT JOIN TGFPPG P ON P.CODTIPVENDA=C.CODTIPVENDA
)
SELECT P.*,
       (SELECT MAX(N.ULTCOD) FROM TGFNUM N WHERE N.ARQUIVO='TGFFIN') ULTCOD_TGFNUM_ATUAL,
       CASE
         WHEN P.QTD_PPG_ENCONTRADAS=0 THEN 'SEM_TGFPPG'
         WHEN P.QTD_PPG_MESMA_SEQ>1 THEN 'REVISAR_DUPLICIDADE_TGFPPG'
         WHEN P.QTD_XML_NUNOTA>1 THEN 'REVISAR_MULTIPLOS_XML'
         WHEN P.VDUP_XML IS NULL THEN 'SEM_VDUP_XML'
         WHEN NOT REGEXP_LIKE(P.DVENC_XML,'^[0-9]{4}-[0-9]{2}-[0-9]{2}$') THEN 'DVENC_XML_INVALIDO'
         WHEN P.CODTIPTITPAD IS NULL THEN 'SEM_CODTIPTITPAD'
         WHEN (SELECT COUNT(*) FROM TGFNUM N WHERE N.ARQUIVO='TGFFIN')<>1 THEN 'REVISAR_TGFNUM'
         ELSE 'APTO_PARA_VALIDACAO_FINAL'
       END STATUS_MAPA,
       CASE
         WHEN P.QTD_PPG_ENCONTRADAS=0 THEN 'Nao foi encontrada condicao em TGFPPG.'
         WHEN P.QTD_PPG_MESMA_SEQ>1 THEN 'Mais de uma TGFPPG para a mesma sequencia.'
         WHEN P.QTD_XML_NUNOTA>1 THEN 'Mais de um registro TGFNFE para a mesma NUNOTA; revisar origem XML.'
         WHEN P.VDUP_XML IS NULL THEN 'vDup nao foi localizado no XML.'
         WHEN P.DVENC_XML IS NULL THEN 'dVenc deve ser obtido do XML.'
         WHEN P.CODTIPTITPAD IS NULL THEN 'Tipo de titulo ausente na condicao de pagamento.'
         ELSE 'Revisar valores antes do INSERT.'
       END OBSERVACAO
  FROM P;

PROMPT === RESUMO DO MAPA ===
SELECT COUNT(*) CANDIDATOS_MAPA FROM &TBL_BASE WHERE ID_EXECUCAO='&ID_EXECUCAO';
SELECT STATUS_MAPA,COUNT(*) QTD FROM &TBL_PPG
 WHERE ID_EXECUCAO='&ID_EXECUCAO'
 GROUP BY STATUS_MAPA ORDER BY STATUS_MAPA;
PROMPT Este mapa usa a volumetria do dashboard e nao altera TGFCAB,TGFTOP,TGFPPG,TGFNUM ou TGFFIN.
SPOOL OFF
