-- Retomada isolada da atividade 13 da base JCLM.
-- Usa DML dinamico porque os grants da TGF TOP chegam pela role RLCONSULTOR.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
DECLARE
  v_tabela PLS_INTEGER;
  v_id VARCHAR2(30) := 'RMD_TOPG_'||TO_CHAR(SYSTIMESTAMP,'YYYYMMDDHH24MISSFF3');
  v_b PLS_INTEGER;
  v_u PLS_INTEGER;
BEGIN
  SELECT COUNT(*) INTO v_tabela
    FROM ALL_TABLES
   WHERE OWNER='SANKHYA'
     AND TABLE_NAME='BKP_RMD_12_TGFTOP';
  IF v_tabela=0 THEN
    RAISE_APPLICATION_ERROR(-20211,'Backup BKP_RMD_12_TGFTOP nao existe; atividade 13 interrompida.');
  END IF;

  EXECUTE IMMEDIATE q'[
    INSERT INTO SANKHYA.BKP_RMD_12_TGFTOP
    (ID_EXECUCAO,DH_EXECUCAO,USUARIO_EXECUCAO,ROWID_ORIGINAL,
     GOLSINAL_ANTES,GOLMPSINAL_ANTES,GOLDEV_ANTES,ANALISEGIRO_ANTES,
     ATUALULTIMAVEND_ANTES,ATUALULTIMACOMP_ANTES)
    SELECT :id_execucao,SYSTIMESTAMP,SYS_CONTEXT('USERENV','SESSION_USER'),ROWIDTOCHAR(ROWID),
           GOLSINAL,GOLMPSINAL,GOLDEV,ANALISEGIRO,ATUALULTIMAVEND,ATUALULTIMACOMP
      FROM SANKHYA.TGFTOP
  ]' USING v_id;
  v_b:=SQL%ROWCOUNT;

  EXECUTE IMMEDIATE q'[
    UPDATE SANKHYA.TGFTOP
       SET GOLSINAL=CASE WHEN ATUALEST='B' AND TIPMOV='V' AND ATUALFIN=1 AND TIPATUALFIN='I' AND CODMODDOC IN (55,59,65) THEN -1 WHEN ATUALEST='E' AND TIPMOV='D' AND ATUALFIN=-1 AND TIPATUALFIN='I' AND CODMODDOC IN (55,59,65) THEN -1 WHEN ATUALEST='E' AND TIPMOV='C' AND ATUALFIN=-1 AND TIPATUALFIN='I' AND CODMODDOC IN (55,59,65) THEN 1 WHEN ATUALEST='B' AND TIPMOV='E' AND ATUALFIN=1 AND TIPATUALFIN='I' AND CODMODDOC IN (55,59,65) THEN 1 ELSE 0 END,
           GOLMPSINAL=CASE WHEN ATUALEST='B' AND TIPMOV='V' AND ATUALFIN=1 AND TIPATUALFIN='I' AND CODMODDOC IN (55,59,65) THEN -1 WHEN ATUALEST='E' AND TIPMOV='D' AND ATUALFIN=-1 AND TIPATUALFIN='I' AND CODMODDOC IN (55,59,65) THEN -1 WHEN ATUALEST='E' AND TIPMOV='C' AND ATUALFIN=-1 AND TIPATUALFIN='I' AND CODMODDOC IN (55,59,65) THEN 1 WHEN ATUALEST='B' AND TIPMOV='E' AND ATUALFIN=1 AND TIPATUALFIN='I' AND CODMODDOC IN (55,59,65) THEN 1 ELSE 0 END,
           GOLDEV=CASE WHEN TIPMOV IN ('D','E') AND ATUALEST IN ('E','B') AND CODMODDOC IN (55,59,65) AND (ATUALFIN<>0 OR TIPATUALFIN<>'P') THEN -1 ELSE 1 END,
           ANALISEGIRO=CASE WHEN TIPMOV='V' AND ATUALEST='B' AND ATUALFIN=1 AND TIPATUALFIN='I' AND CODMODDOC IN (55,59,65) THEN -1 WHEN TIPMOV='D' AND ATUALEST='E' AND ATUALFIN=-1 AND TIPATUALFIN='I' AND CODMODDOC IN (55,59,65) THEN 1 ELSE 0 END,
           ATUALULTIMAVEND=CASE WHEN TIPMOV='V' AND ATUALEST='B' AND ATUALFIN=1 AND TIPATUALFIN='I' AND CODMODDOC IN (55,59,65) THEN 'G' ELSE 'N' END,
           ATUALULTIMACOMP=CASE WHEN TIPMOV='C' AND ATUALEST='E' AND ATUALFIN=-1 AND TIPATUALFIN='I' AND CODMODDOC IN (55,59,65) THEN 'E' ELSE 'N' END
     WHERE 1=1
  ]';
  v_u:=SQL%ROWCOUNT;
  IF v_b<>v_u THEN
    RAISE_APPLICATION_ERROR(-20210,'Backup e atualizacao divergiram na atividade 13.');
  END IF;
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('ATIVIDADE=13_CONFIGURAR_TOPS_GIRO_GOL');
  DBMS_OUTPUT.PUT_LINE('ID_EXECUCAO='||v_id);
  DBMS_OUTPUT.PUT_LINE('REGISTROS_BACKUP='||v_b);
  DBMS_OUTPUT.PUT_LINE('REGISTROS_ALTERADOS='||v_u);
  DBMS_OUTPUT.PUT_LINE('AVISO=Mapeamento de TOPs possui cobertura parcial aprovada.');
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END;
/
