-- Retomada isolada da atividade 12 da base JCLM.
-- O backup estrutural ja existe desde a tentativa parcial; o DML permanece dinamico.
-- A atualizacao remove a qualificacao do alvo no SET, que nao e aceita nesta base.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
DECLARE
  v_tabela PLS_INTEGER;
  v_id VARCHAR2(30) := 'RMD_RUPE_'||TO_CHAR(SYSTIMESTAMP,'YYYYMMDDHH24MISSFF3');
  v_b PLS_INTEGER;
  v_u PLS_INTEGER;
BEGIN
  SELECT COUNT(*) INTO v_tabela
    FROM ALL_TABLES
   WHERE OWNER='SANKHYA'
     AND TABLE_NAME='BKP_RMD_11_TGFEMP';
  IF v_tabela=0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE SANKHYA.BKP_RMD_11_TGFEMP AS
      SELECT CAST(NULL AS VARCHAR2(30)) ID_EXECUCAO,
             CAST(NULL AS TIMESTAMP) DH_EXECUCAO,
             CAST(NULL AS VARCHAR2(128)) USUARIO_EXECUCAO,
             CAST(NULL AS VARCHAR2(30)) ROWID_ORIGINAL,
             E.RUPTURAEST RUPTURAEST_ANTES
        FROM SANKHYA.TGFEMP E
       WHERE 1=0
    ]';
  END IF;

  EXECUTE IMMEDIATE q'[
    INSERT INTO SANKHYA.BKP_RMD_11_TGFEMP
    SELECT :id_execucao,SYSTIMESTAMP,SYS_CONTEXT('USERENV','SESSION_USER'),
           ROWIDTOCHAR(E.ROWID),E.RUPTURAEST
      FROM SANKHYA.TGFEMP E
     WHERE NVL(E.RUPTURAEST,'N')<>'S'
       AND EXISTS (
         SELECT 1
           FROM SANKHYA.AD_SEGMENTACAOEMPRESAS S
           JOIN SANKHYA.TSIEMP T ON T.CGC=S.CGC
          WHERE S.SEGMENTACAO<>'S'
            AND T.CODEMP=E.CODEMP
       )
  ]' USING v_id;
  v_b:=SQL%ROWCOUNT;

  EXECUTE IMMEDIATE q'[
    UPDATE SANKHYA.TGFEMP E
       SET RUPTURAEST='S'
     WHERE NVL(E.RUPTURAEST,'N')<>'S'
       AND EXISTS (
         SELECT 1
           FROM SANKHYA.AD_SEGMENTACAOEMPRESAS S
           JOIN SANKHYA.TSIEMP T ON T.CGC=S.CGC
          WHERE S.SEGMENTACAO<>'S'
            AND T.CODEMP=E.CODEMP
       )
  ]';
  v_u:=SQL%ROWCOUNT;
  IF v_b<>v_u THEN
    RAISE_APPLICATION_ERROR(-20230,'Backup e atualizacao de empresas divergiram na atividade 12.');
  END IF;
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('ATIVIDADE=12_HABILITAR_RUPTURA_EMPRESAS');
  DBMS_OUTPUT.PUT_LINE('ID_EXECUCAO='||v_id);
  DBMS_OUTPUT.PUT_LINE('REGISTROS_BACKUP='||v_b);
  DBMS_OUTPUT.PUT_LINE('REGISTROS_ALTERADOS='||v_u);
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END;
/
