-- Card 09 - somente mapeamento/classificacao direta por XML.
-- Nenhuma inclusao em TGFFIN nesta fase.
SET DEFINE ON
SET SERVEROUTPUT ON SIZE UNLIMITED
SET SQLBLANKLINES ON
WHENEVER OSERROR EXIT FAILURE ROLLBACK
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
@@32A_Card09_Mapear_Direto_XML.sql
