-- Diagnostico transitorio da atividade 14; todo DML e revertido no proprio bloco.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER OSERROR EXIT FAILURE ROLLBACK
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
DECLARE
  v_id VARCHAR2(30) := 'RMD_DIAG_14';
  v_b NUMBER;
  v_u NUMBER;
BEGIN
  EXECUTE IMMEDIATE q'~
    INSERT INTO SANKHYA.BKP_RMD_13_TSIIMP
      SELECT :id_execucao,SYSTIMESTAMP,SYS_CONTEXT('USERENV','SESSION_USER'),CODREL,LISTA1
        FROM SANKHYA.TSIIMP
       WHERE CODREL=848
  ~' USING v_id;
  v_b := SQL%ROWCOUNT;
  EXECUTE IMMEDIATE 'UPDATE SANKHYA.TSIIMP SET LISTA1=LISTA1 WHERE CODREL=848';
  v_u := SQL%ROWCOUNT;
  DBMS_OUTPUT.PUT_LINE('DIAG_BACKUP_ROWCOUNT='||v_b);
  DBMS_OUTPUT.PUT_LINE('DIAG_UPDATE_ROWCOUNT='||v_u);
  ROLLBACK;
END;
/
