-- Retomada isolada da atividade 17 da base JCLM.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER OSERROR EXIT FAILURE ROLLBACK
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
VARIABLE RMD_ID_MASTER VARCHAR2(30)
BEGIN
  :RMD_ID_MASTER := 'RMD_RUN_20260919211829041';
END;
/
@@../../Revisao Master Deploy/17_Normalizar_Unidades.sql
