-- Retomada isolada da atividade 16 da base JCLM.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET SQLBLANKLINES ON
WHENEVER OSERROR EXIT FAILURE ROLLBACK
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
VARIABLE RMD_ID_TSICFG VARCHAR2(30)
BEGIN
  :RMD_ID_TSICFG := 'RMD_CFG_' || TO_CHAR(SYSTIMESTAMP,'YYYYMMDDHH24MISSFF3');
END;
/
@@../../Revisao Master Deploy/16_Aplicar_Higienizacao_TSICFG.sql
