-- Remove somente o mapa de pre-validacao criado pela etapa 32A.
-- Nao remove nem altera registros da TGFFIN.

SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET SQLBLANKLINES ON
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

DECLARE
  v_qtd NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_qtd
    FROM ALL_TABLES
   WHERE OWNER = SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
     AND TABLE_NAME = 'BKP_RMD_FDUP_MCL_20260910_PPG';
  IF v_qtd = 0 THEN
    DBMS_OUTPUT.PUT_LINE('STATUS=MAPA_NAO_EXISTE');
    RETURN;
  END IF;

  EXECUTE IMMEDIATE 'DROP TABLE BKP_RMD_FDUP_MCL_20260910_PPG PURGE';
  DBMS_OUTPUT.PUT_LINE('STATUS=MAPA_REMOVIDO');
END;
/
