SET DEFINE ON
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
ACCEPT P_ID_EXECUCAO CHAR PROMPT 'ID da execucao RMD_GOL_: '
DECLARE v_total PLS_INTEGER:=0;v_rows PLS_INTEGER;BEGIN
 UPDATE TSIPAR P SET P.INTEIRO=(SELECT B.INTEIRO_ANTES FROM BKP_RMD_GOL_TSIPAR B
   WHERE B.ID_EXECUCAO='&&P_ID_EXECUCAO' AND B.CHAVE=P.CHAVE AND B.CODUSU=P.CODUSU)
 WHERE EXISTS(SELECT 1 FROM BKP_RMD_GOL_TSIPAR B WHERE B.ID_EXECUCAO='&&P_ID_EXECUCAO'
   AND B.CHAVE=P.CHAVE AND B.CODUSU=P.CODUSU);
 v_total:=v_total+SQL%ROWCOUNT;
 MERGE INTO TGFCGM C USING(SELECT * FROM BKP_RMD_GOL_TGFCGM WHERE ID_EXECUCAO='&&P_ID_EXECUCAO')B
 ON(C.ROWID=CHARTOROWID(B.ROWID_ORIGINAL)) WHEN MATCHED THEN UPDATE SET
 C.PERCCFFAB=B.PERCCFFAB,C.PERCCFOUTROS=B.PERCCFOUTROS,C.PERCCFSERVICO=B.PERCCFSERVICO,
 C.PERCCOFINS=B.PERCCOFINS,C.PERCCSL=B.PERCCSL,C.PERCCUSVAR=B.PERCCUSVAR,
 C.PERCCVARSEMST=B.PERCCVARSEMST,C.PERCMARGEM=B.PERCMARGEM,C.PERCPIS=B.PERCPIS,
 C.PERCIRPJ=B.PERCIRPJ,C.PERCCPP=B.PERCCPP;
 v_total:=v_total+SQL%ROWCOUNT;
 MERGE INTO TGFCMV C USING(SELECT * FROM BKP_RMD_GOL_TGFCMV WHERE ID_EXECUCAO='&&P_ID_EXECUCAO')B
 ON(C.ROWID=CHARTOROWID(B.ROWID_ORIGINAL)) WHEN MATCHED THEN UPDATE SET
 C.DHALTER=B.DHALTER,C.FORMGASTOFIX=B.FORMGASTOFIX,C.INTERVALOATUALIZACAO=B.INTERVALOATUALIZACAO,
 C.PERCUSTOFIX=B.PERCUSTOFIX,C.QTDMESESCONSOLIDAR=B.QTDMESESCONSOLIDAR,
 C.TEMCOMISSAO=B.TEMCOMISSAO,C.TIPDTGASTOFIX=B.TIPDTGASTOFIX,
 C.TIPFATPER=B.TIPFATPER,C.TIPOCUSTO=B.TIPOCUSTO;
 v_total:=v_total+SQL%ROWCOUNT;
 IF v_total=0 THEN RAISE_APPLICATION_ERROR(-20304,'Backup GOL nao encontrado.');END IF;
 COMMIT;DBMS_OUTPUT.PUT_LINE('REGISTROS_REVERTIDOS='||v_total);
EXCEPTION WHEN OTHERS THEN ROLLBACK;RAISE;END;
/
UNDEFINE P_ID_EXECUCAO
