-- Read-only: inventario final para o relatorio (objetos da revisao e unidades).
SELECT 'OBJETO' TIPO, OBJECT_NAME NOME, OBJECT_TYPE DETALHE, TO_CHAR(CREATED,'YYYY-MM-DD HH24:MI') CRIADO
  FROM ALL_OBJECTS WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND OBJECT_TYPE='TABLE'
   AND (OBJECT_NAME LIKE 'RMD\_%' ESCAPE '\' OR OBJECT_NAME LIKE 'BKP\_RMD\_%' ESCAPE '\' OR OBJECT_NAME LIKE 'BKP\_CLASSICMS%' ESCAPE '\' OR OBJECT_NAME LIKE 'BKP\_AJNP%' ESCAPE '\')
   AND CREATED >= TO_DATE('2026-09-25','YYYY-MM-DD')
UNION ALL SELECT 'TGFVOL', CODVOL, DESCRVOL, NULL FROM TGFVOL WHERE CODVOL IN ('KIT','KT')
UNION ALL SELECT 'TGFVOL_TOTAL', TO_CHAR(COUNT(*)), NULL, NULL FROM TGFVOL
UNION ALL SELECT 'CONTROLE', OBJECT_NAME, OBJECT_TYPE||' '||STATUS_ANTES||'->'||STATUS_DEPOIS, NULL FROM RMD_CONTROLE_OBJETOS
