-- Pos-validacao read-only do mapa Card 09 FOCUSFINTAXPRD.
SELECT SYS_CONTEXT('USERENV','SESSION_USER') AS SESSION_USER,
       SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AS CURRENT_SCHEMA,
       SYS_CONTEXT('USERENV','SERVICE_NAME') AS SERVICE_NAME,
       SYS_CONTEXT('USERENV','DB_NAME') AS DB_NAME
  FROM DUAL;

SELECT COUNT(*) AS BASE_TOTAL_MAPA
  FROM BKP_RMD_FDUP_FCS_20260923
 WHERE ID_EXECUCAO='FOCUS_FDUP_20260923_01';

SELECT STATUS_MAPA,COUNT(*) AS QTD_LINHAS,COUNT(DISTINCT NUNOTA) AS QTD_NOTAS
  FROM BKP_RMD_FDUP_FCS_20260923_PPG
 WHERE ID_EXECUCAO='FOCUS_FDUP_20260923_01'
 GROUP BY STATUS_MAPA
 ORDER BY STATUS_MAPA;

SELECT COUNT(*) AS APTOS_COM_TGFFIN_POS_MAPA
  FROM BKP_RMD_FDUP_FCS_20260923_PPG M
 WHERE M.ID_EXECUCAO='FOCUS_FDUP_20260923_01'
   AND M.STATUS_MAPA='APTO_PARA_VALIDACAO_FINAL'
   AND EXISTS (SELECT 1 FROM TGFFIN F WHERE F.NUNOTA=M.NUNOTA);

SELECT COUNT(*) AS NOTAS_SEM_FINANCEIRO_ESCOPO_DASHBOARD
  FROM TGFCAB C
  JOIN TGFTOP T ON T.CODTIPOPER=C.CODTIPOPER AND T.DHALTER=C.DHTIPOPER
 WHERE T.ATUALFIN<>0 AND C.TIPMOV<>'Z'
   AND NOT EXISTS (SELECT 1 FROM TGFFIN F WHERE F.NUNOTA=C.NUNOTA);

SELECT COUNT(*) AS LINHAS_TGFNUM_TGFFIN, MAX(ULTCOD) AS ULTCOD_TGFNUM_TGFFIN, (SELECT COUNT(*) FROM TGFFIN) AS TOTAL_TGFFIN
  FROM TGFNUM WHERE ARQUIVO='TGFFIN';
