-- Pos-validacao read-only R02 do mapa Card 09 FOCUSFINTAXPRD (FOCUS_FDUP_20260923_01).
-- Motivo: a 6a consulta do arquivo original falhou com ORA-00937 (subconsulta escalar junto de agregacao sem GROUP BY)
-- depois de COMMIT_LOTE=OK. Nao repete DDL/DML; apenas refaz a verificacao em uma instrucao unica.
SELECT 'BASE_TOTAL_MAPA' AS METRICA, TO_CHAR(COUNT(*)) AS VALOR FROM BKP_RMD_FDUP_FCS_20260923 WHERE ID_EXECUCAO='FOCUS_FDUP_20260923_01'
UNION ALL SELECT 'LINHAS_CLASSIFICACAO', TO_CHAR(COUNT(*)) FROM BKP_RMD_FDUP_FCS_20260923_PPG WHERE ID_EXECUCAO='FOCUS_FDUP_20260923_01'
UNION ALL SELECT 'APTO_PARA_VALIDACAO_FINAL', TO_CHAR(COUNT(*)) FROM BKP_RMD_FDUP_FCS_20260923_PPG WHERE ID_EXECUCAO='FOCUS_FDUP_20260923_01' AND STATUS_MAPA='APTO_PARA_VALIDACAO_FINAL'
UNION ALL SELECT 'SEM_VDUP_XML', TO_CHAR(COUNT(*)) FROM BKP_RMD_FDUP_FCS_20260923_PPG WHERE ID_EXECUCAO='FOCUS_FDUP_20260923_01' AND STATUS_MAPA='SEM_VDUP_XML'
UNION ALL SELECT 'TABELAS_MAPA_EXISTENTES', TO_CHAR(COUNT(*)) FROM ALL_TABLES WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND TABLE_NAME IN ('BKP_RMD_FDUP_FCS_20260923','BKP_RMD_FDUP_FCS_20260923_PPG')
UNION ALL SELECT 'ESCOPO_DASHBOARD_NOTAS_SEM_FIN', TO_CHAR(COUNT(*)) FROM TGFCAB C JOIN TGFTOP T ON T.CODTIPOPER=C.CODTIPOPER AND T.DHALTER=C.DHTIPOPER
 WHERE T.ATUALFIN<>0 AND C.TIPMOV<>'Z' AND NOT EXISTS (SELECT 1 FROM TGFFIN F WHERE F.NUNOTA=C.NUNOTA)
UNION ALL SELECT 'LINHAS_TGFNUM_TGFFIN', TO_CHAR(COUNT(*)) FROM TGFNUM WHERE ARQUIVO='TGFFIN'
UNION ALL SELECT 'ULTCOD_TGFNUM_TGFFIN', TO_CHAR(MAX(ULTCOD)) FROM TGFNUM WHERE ARQUIVO='TGFFIN'
UNION ALL SELECT 'TOTAL_TGFFIN', TO_CHAR(COUNT(*)) FROM TGFFIN
