-- Precheck somente leitura das etapas 01 a 16.
-- Nao cria backups, objetos ou altera dados.
SET DEFINE OFF
SET ECHO ON
SET SERVEROUTPUT ON
SET PAGESIZE 200
SET LINESIZE 240

PROMPT === IDENTIDADE ===
SELECT SYS_CONTEXT('USERENV','SESSION_USER') USUARIO,
       SYS_CONTEXT('USERENV','CURRENT_SCHEMA') SCHEMA_ATUAL,
       SYS_CONTEXT('USERENV','SERVICE_NAME') SERVICO FROM DUAL;

PROMPT === OBJETOS OBRIGATORIOS 01 A 16 ===
SELECT N.NOME,N.TIPO_ESPERADO,NVL(O.OBJECT_TYPE,'AUSENTE') TIPO_ENCONTRADO,NVL(O.STATUS,'AUSENTE') STATUS
FROM (
 SELECT 'TSIPAR' NOME,'TABLE' TIPO_ESPERADO FROM DUAL UNION ALL SELECT 'TGFEMP','TABLE' FROM DUAL
 UNION ALL SELECT 'TGFTOP','TABLE' FROM DUAL UNION ALL SELECT 'TGFPRO','TABLE' FROM DUAL
 UNION ALL SELECT 'TGFTPV','TABLE' FROM DUAL UNION ALL SELECT 'TGFCAB','TABLE' FROM DUAL
 UNION ALL SELECT 'TGFITE','TABLE' FROM DUAL UNION ALL SELECT 'TTKNOT','TABLE' FROM DUAL
 UNION ALL SELECT 'TTKINDAGT','TABLE' FROM DUAL UNION ALL SELECT 'TSIIMP','TABLE' FROM DUAL
 UNION ALL SELECT 'TSICFG','TABLE' FROM DUAL UNION ALL SELECT 'AD_SEGMENTACAOEMPRESAS','TABLE' FROM DUAL
 UNION ALL SELECT 'TRG_UPT_TGFITE','TRIGGER' FROM DUAL
) N LEFT JOIN ALL_OBJECTS O
 ON O.OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND O.OBJECT_NAME=N.NOME AND O.OBJECT_TYPE=N.TIPO_ESPERADO
ORDER BY N.NOME;

PROMPT === CANDIDATOS 02 A 11 E 15 ===
SELECT '02_FILTROS_PORTAIS' ITEM,COUNT(*) QTD FROM TSIPAR
 WHERE CHAVE IN ('MAXDIASPORTAIS','MAXDIASPORTVEND','MAXDIASPORTCOMP','MAXDIASMOVFIN') AND INTEIRO IS NOT NULL
UNION ALL SELECT '03_EMPRESAS_DANFE',COUNT(*) FROM TGFEMP WHERE CODEMP<>1
UNION ALL SELECT '04_TOP_DEVOLUCAO',COUNT(*) FROM TGFTOP WHERE TIPMOV='D' AND NVL(PRECIFICA,'?')<>'N'
UNION ALL SELECT '05_GIRO_PRODUTOS',COUNT(*) FROM TGFPRO WHERE USOPROD IN ('V','R') AND NVL(CALCULOGIRO,'?')<>'G'
UNION ALL SELECT '06_PARCELAS_TPV',COUNT(*) FROM TGFTPV WHERE NVL(NROPARCELAS,-1)<>0
UNION ALL SELECT '07_DTMOV_A_PREENCHER',COUNT(*) FROM TGFCAB WHERE DTMOV IS NULL AND TIPMOV<>'Z'
UNION ALL SELECT '08_PROTOCOLOS_LEGADOS',COUNT(*) FROM TGFCAB C WHERE EXISTS (SELECT 1 FROM TTKNOT N WHERE N.NUNOTA=C.NUNOTA)
 AND ((C.NUMPROTOC IS NULL AND EXISTS (SELECT 1 FROM TGFTOP T WHERE T.CODTIPOPER=C.CODTIPOPER AND T.DHALTER=C.DHTIPOPER AND T.CODMODDOC=55))
   OR (C.NUMPROTOCCTE IS NULL AND EXISTS (SELECT 1 FROM TGFTOP T WHERE T.CODTIPOPER=C.CODTIPOPER AND T.DHALTER=C.DHTIPOPER AND T.CODMODDOC=57)))
UNION ALL SELECT '09_ITENS_LEGADOS',COUNT(*) FROM TGFITE I WHERE NVL(STATUSNOTA,'?')<>'L' AND EXISTS (SELECT 1 FROM TTKNOT N WHERE N.NUNOTA=I.NUNOTA)
UNION ALL SELECT '10_ICMS_GERENCIAL',COUNT(*) FROM TGFPRO WHERE USOPROD IN ('V','R') AND NVL(ICMSGERENCIA,'?')<>'S'
UNION ALL SELECT '11_RUPTURA_PRODUTOS',COUNT(*) FROM TGFPRO WHERE USOPROD IN ('V','R') AND NVL(CALRUPTURAESTOQUE,'N')<>'S'
UNION ALL SELECT '15_RASTRO_SEM_CONTROLE',COUNT(*) FROM TGFPRO WHERE TEMRASTROLOTE='S' AND TIPCONTEST='N';

PROMPT === CONDICOES ESPECIAIS 12 A 16 ===
SELECT '12_TABELA_SEGMENTACAO' ITEM,COUNT(*) QTD FROM ALL_TABLES
 WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND TABLE_NAME='AD_SEGMENTACAOEMPRESAS'
UNION ALL SELECT '13_TOPS_AFETADAS',COUNT(*) FROM TGFTOP
UNION ALL SELECT '14_ANALISE_GIRO_848',COUNT(*) FROM TSIIMP WHERE CODREL=848
UNION ALL SELECT '16_TSICFG_ATUAL',COUNT(*) FROM TSICFG;

DECLARE
  v_tabela NUMBER;
  v_qtd NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_tabela FROM ALL_TABLES
   WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND TABLE_NAME='AD_SEGMENTACAOEMPRESAS';
  IF v_tabela=0 THEN
    DBMS_OUTPUT.PUT_LINE('12_EMPRESAS_RUPTURA=NAO_AVALIADO_TABELA_AUSENTE');
  ELSE
    EXECUTE IMMEDIATE q'[SELECT COUNT(*) FROM TGFEMP E
      WHERE NVL(E.RUPTURAEST,'N')<>'S' AND EXISTS (
        SELECT 1 FROM AD_SEGMENTACAOEMPRESAS S JOIN TSIEMP T ON T.CGC=S.CGC
         WHERE S.SEGMENTACAO<>'S' AND T.CODEMP=E.CODEMP)]' INTO v_qtd;
    DBMS_OUTPUT.PUT_LINE('12_EMPRESAS_RUPTURA='||v_qtd);
  END IF;
END;
/

PROMPT === ESTADO DA TRIGGER DA ETAPA 09 ===
SELECT TRIGGER_NAME,STATUS FROM ALL_TRIGGERS
 WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND TRIGGER_NAME='TRG_UPT_TGFITE';

PROMPT === FIM PRECHECK ETAPAS 01 A 16 ===
