-- Diagnostico somente leitura: localizacao dos backups das etapas 01 a 11.
SET PAGESIZE 100
SET LINESIZE 220
SELECT OWNER, TABLE_NAME
  FROM ALL_TABLES
 WHERE TABLE_NAME IN ('BKP_RMD_01_TSIPAR','BKP_RMD_02_TGFEMP','BKP_RMD_03_TGFTOP',
                      'BKP_RMD_04_TGFPRO','BKP_RMD_05_TGFTPV','BKP_RMD_06_TGFCAB',
                      'BKP_RMD_07_TGFCAB','BKP_RMD_08_TGFITE','BKP_RMD_09_TGFPRO',
                      'BKP_RMD_10_TGFPRO','BKP_RMD_11_TGFEMP')
 ORDER BY OWNER, TABLE_NAME;
