-- Diagnostico somente leitura da falha da etapa 12.
SET PAGESIZE 100
SET LINESIZE 220
SELECT SYS_CONTEXT('USERENV','SESSION_USER') USUARIO,
       SYS_CONTEXT('USERENV','CURRENT_SCHEMA') SCHEMA_ATUAL
  FROM DUAL;

SELECT OWNER, OBJECT_NAME, OBJECT_TYPE, STATUS
  FROM ALL_OBJECTS
 WHERE OBJECT_NAME = 'BKP_RMD_11_TGFEMP'
 ORDER BY OWNER, OBJECT_TYPE;

SELECT OWNER, TABLE_NAME
  FROM ALL_TABLES
 WHERE TABLE_NAME = 'BKP_RMD_11_TGFEMP'
 ORDER BY OWNER;

SELECT OWNER, SYNONYM_NAME, TABLE_OWNER, TABLE_NAME
  FROM ALL_SYNONYMS
 WHERE SYNONYM_NAME = 'BKP_RMD_11_TGFEMP'
 ORDER BY OWNER;

SELECT OWNER, TABLE_NAME
  FROM ALL_TABLES
 WHERE TABLE_NAME IN ('BKP_RMD_01_TSIPAR','BKP_RMD_02_TGFEMP','BKP_RMD_03_TGFTOP',
                      'BKP_RMD_04_TGFPRO','BKP_RMD_05_TGFTPV','BKP_RMD_06_TGFCAB',
                      'BKP_RMD_07_TGFCAB','BKP_RMD_08_TGFITE','BKP_RMD_09_TGFPRO',
                      'BKP_RMD_10_TGFPRO','BKP_RMD_11_TGFEMP')
 ORDER BY OWNER, TABLE_NAME;
