-- Tratamento isolado da pendencia da etapa 12.
SET DEFINE ON
SET SERVEROUTPUT ON SIZE UNLIMITED
SET ECHO ON
WHENEVER OSERROR EXIT FAILURE ROLLBACK
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
SPOOL "/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Clientes/PRODUTOS MACALE LTDA/Logs/Tratamento_Etapa_12_20260909.log"

ACCEPT P_CONFIRMA CHAR PROMPT 'Digite EXECUTAR PRODUTOS MACALE LTDA para tratar a etapa 12: '
BEGIN
  IF UPPER(TRIM('&&P_CONFIRMA')) <> 'EXECUTAR PRODUTOS MACALE LTDA' THEN
    RAISE_APPLICATION_ERROR(-20500,'Execucao cancelada: confirmacao da base divergente.');
  END IF;
  IF UPPER(SYS_CONTEXT('USERENV','SERVICE_NAME')) <> 'MACALEPRD.SANKHYACLOUD.COM.BR' THEN
    RAISE_APPLICATION_ERROR(-20501,'SERVICE_NAME diferente do esperado.');
  END IF;
END;
/
UNDEFINE P_CONFIRMA

DECLARE
  v_tab NUMBER;
  v_id VARCHAR2(30) := 'RMD_RUPE_'||TO_CHAR(SYSTIMESTAMP,'YYYYMMDDHH24MISSFF3');
  v_backup PLS_INTEGER;
  v_update PLS_INTEGER;
BEGIN
  SELECT COUNT(*) INTO v_tab FROM ALL_TABLES
   WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND TABLE_NAME='AD_SEGMENTACAOEMPRESAS';
  IF v_tab=0 THEN
    DBMS_OUTPUT.PUT_LINE('STATUS=IGNORADO_TABELA_AUSENTE');
    RETURN;
  END IF;
  BEGIN
    EXECUTE IMMEDIATE q'[CREATE TABLE BKP_RMD_11_TGFEMP AS
      SELECT CAST(NULL AS VARCHAR2(30)) ID_EXECUCAO,
             CAST(NULL AS TIMESTAMP) DH_EXECUCAO,
             CAST(NULL AS VARCHAR2(128)) USUARIO_EXECUCAO,
             CAST(NULL AS VARCHAR2(30)) ROWID_ORIGINAL,
             E.RUPTURAEST RUPTURAEST_ANTES
        FROM TGFEMP E WHERE 1=0]';
  EXCEPTION WHEN OTHERS THEN
    IF SQLCODE <> -955 THEN RAISE; END IF;
  END;
  EXECUTE IMMEDIATE q'[INSERT INTO BKP_RMD_11_TGFEMP
    SELECT :1,SYSTIMESTAMP,SYS_CONTEXT('USERENV','SESSION_USER'),ROWIDTOCHAR(E.ROWID),E.RUPTURAEST
      FROM TGFEMP E
     WHERE NVL(E.RUPTURAEST,'N')<>'S'
       AND EXISTS (SELECT 1 FROM AD_SEGMENTACAOEMPRESAS S JOIN TSIEMP T ON T.CGC=S.CGC
                    WHERE S.SEGMENTACAO<>'S' AND T.CODEMP=E.CODEMP)]' USING v_id;
  v_backup:=SQL%ROWCOUNT;
  UPDATE TGFEMP E SET E.RUPTURAEST='S'
   WHERE NVL(E.RUPTURAEST,'N')<>'S'
     AND EXISTS (SELECT 1 FROM AD_SEGMENTACAOEMPRESAS S JOIN TSIEMP T ON T.CGC=S.CGC
                  WHERE S.SEGMENTACAO<>'S' AND T.CODEMP=E.CODEMP);
  v_update:=SQL%ROWCOUNT;
  IF v_backup<>v_update THEN RAISE_APPLICATION_ERROR(-20230,'Backup e atualizacao divergiram.'); END IF;
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('STATUS=CONCLUIDO; ID_EXECUCAO='||v_id||'; EMPRESAS_ALTERADAS='||v_update);
EXCEPTION WHEN OTHERS THEN ROLLBACK; RAISE;
END;
/
SPOOL OFF
