-- Diagnostico read-only da variacao de nomes informada pelo solicitante.
-- Nao contem senha, DML, DDL ou alteracao de objeto.
SET DEFINE OFF
SET ECHO ON
SET FEEDBACK ON
SET HEADING ON
SET LINESIZE 240
SET PAGESIZE 200
SET TRIMSPOOL ON
SPOOL "/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Clientes/VITRINI DIRETA (ACM BRASIL)/Logs/Identidade_Empresas_ReadOnly_RMD_VDA_20260918080832.log"

PROMPT === COLUNAS DE IDENTIDADE DISPONIVEIS EM TSIEMP ===
SELECT OWNER, TABLE_NAME, COLUMN_ID, COLUMN_NAME, DATA_TYPE
  FROM ALL_TAB_COLUMNS
 WHERE TABLE_NAME='TSIEMP'
   AND UPPER(COLUMN_NAME) LIKE '%NOME%'
 ORDER BY OWNER, COLUMN_ID;

SELECT OWNER, TABLE_NAME, COLUMN_ID, COLUMN_NAME, DATA_TYPE
  FROM ALL_TAB_COLUMNS
 WHERE TABLE_NAME='TSIEMP'
   AND UPPER(COLUMN_NAME) LIKE '%RAZAO%'
 ORDER BY OWNER, COLUMN_ID;

PROMPT === EMPRESAS CADASTRADAS - CAMPOS DE IDENTIDADE ===
SELECT CODEMP, NOMEFANTASIA, RAZAOSOCIAL
  FROM TSIEMP
 ORDER BY CODEMP;

PROMPT === EMPRESAS RELACIONADAS A VITRIN/ACM ===
SELECT CODEMP, NOMEFANTASIA, RAZAOSOCIAL
  FROM TSIEMP
 WHERE UPPER(NVL(NOMEFANTASIA,' ')) LIKE '%VITRIN%'
    OR UPPER(NVL(NOMEFANTASIA,' ')) LIKE '%ACM%'
    OR UPPER(NVL(RAZAOSOCIAL,' ')) LIKE '%VITRIN%'
    OR UPPER(NVL(RAZAOSOCIAL,' ')) LIKE '%ACM%'
 ORDER BY CODEMP;

PROMPT === FIM DO DIAGNOSTICO READ-ONLY ===
SPOOL OFF
