-- Gate de preflight somente leitura - VITRINI DIRETA (ACM BRASIL).
-- ID da revisao: RMD_VDA_20260918080832
-- Nao contem senha, DML, DDL, COMMIT ou alteracao de objeto.
-- Executar conectado manualmente no VS Code como SCRIPT (F5), antes do Master.

SET DEFINE OFF
SET ECHO ON
SET FEEDBACK ON
SET HEADING ON
SET LINESIZE 240
SET LONG 4000
SET PAGESIZE 2000
SET TAB OFF
SET VERIFY OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
SPOOL "/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Clientes/VITRINI DIRETA (ACM BRASIL)/Logs/Preflight_RMD_VDA_20260918080832.log"

PROMPT ======================================================================
PROMPT RMD_VDA_20260918080832 - PREFLIGHT / IDENTIDADE DA SESSAO
PROMPT ======================================================================
SELECT SYS_CONTEXT('USERENV','SESSION_USER') AS SESSION_USER,
       SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AS CURRENT_SCHEMA,
       SYS_CONTEXT('USERENV','SERVICE_NAME') AS SERVICE_NAME,
       SYS_CONTEXT('USERENV','DB_NAME') AS DB_NAME,
       SYS_CONTEXT('USERENV','INSTANCE_NAME') AS INSTANCE_NAME,
       SYS_CONTEXT('USERENV','IP_ADDRESS') AS IP_ADDRESS
  FROM DUAL;

SELECT CASE WHEN UPPER(SYS_CONTEXT('USERENV','SESSION_USER'))='FRANCISCO_JUNIOR'
            THEN 'OK' ELSE 'BLOQUEAR_USUARIO' END AS STATUS_USUARIO,
       CASE WHEN UPPER(SYS_CONTEXT('USERENV','SERVICE_NAME'))='VITRINEDIRETAPRD.SANKHYACLOUD.COM.BR'
            THEN 'OK' ELSE 'BLOQUEAR_SERVICE_NAME' END AS STATUS_SERVICE,
       CASE WHEN UPPER(SYS_CONTEXT('USERENV','CURRENT_SCHEMA'))='FRANCISCO_JUNIOR'
            THEN 'OK' ELSE 'INFORMAR_SCHEMA_OPERACIONAL' END AS STATUS_SCHEMA
  FROM DUAL;

PROMPT ======================================================================
PROMPT EMPRESA ESPERADA - TSIEMP
PROMPT ======================================================================
SELECT CODEMP, RAZAOSOCIAL
  FROM TSIEMP
 WHERE UPPER(TRIM(RAZAOSOCIAL))='VITRINI DIRETA (ACM BRASIL)'
 ORDER BY CODEMP;

SELECT COUNT(*) AS QTD_EMPRESA_EXATA,
       CASE WHEN COUNT(*)=1 THEN 'OK' ELSE 'BLOQUEAR_IDENTIDADE_EMPRESA' END AS STATUS_EMPRESA
  FROM TSIEMP
 WHERE UPPER(TRIM(RAZAOSOCIAL))='VITRINI DIRETA (ACM BRASIL)';

PROMPT ======================================================================
PROMPT VERSAO DO SISTEMA - CONSULTA EXCLUSIVA TSIPAR
PROMPT ======================================================================
SELECT TEXTO
  FROM TSIPAR
 WHERE CHAVE='VERSAOSKWBIN';

PROMPT ======================================================================
PROMPT TABELAS E OBJETOS DE CONTROLE
PROMPT ======================================================================
SELECT OWNER, TABLE_NAME, NUM_ROWS
  FROM ALL_TABLES
 WHERE OWNER IN (UPPER(SYS_CONTEXT('USERENV','CURRENT_SCHEMA')),'SANKHYA')
   AND TABLE_NAME IN (
       'TSIEMP','TSIPAR','TTKINDAGT','TTKNOT','TTKEVT','TGFCAB','TGFTOP',
       'TGFPAR','TGFPRO','TGFITE','TGFVOL','TGFVOA','TGFPAP','TGFCOI2',
       'TGFGIR1','TSIIMP','TGFCGM','TGFCMV','TGFTPV','TGFTIT','TSICID',
       'TSIBAI','TSIEND','TGFPPG','TGFFIN','TGFNUM','TSICTA','TSICFG'
   )
 ORDER BY OWNER, TABLE_NAME;

PROMPT ======================================================================
PROMPT PRIVILEGIOS E QUOTA - SOMENTE LEITURA
PROMPT ======================================================================
SELECT PRIVILEGE
  FROM SESSION_PRIVS
 WHERE PRIVILEGE IN (
       'CREATE TABLE','CREATE PROCEDURE','ALTER ANY PROCEDURE',
       'ALTER ANY TRIGGER','CREATE ANY TABLE','DROP ANY TABLE'
   )
 ORDER BY PRIVILEGE;

SELECT TABLESPACE_NAME, BYTES, MAX_BYTES, BLOCKS, MAX_BLOCKS
  FROM USER_TS_QUOTAS
 ORDER BY TABLESPACE_NAME;

PROMPT ======================================================================
PROMPT TRIGGERS E OBJETOS TEMPORARIOS - ESTADO ATUAL
PROMPT ======================================================================
SELECT OWNER, TRIGGER_NAME, TABLE_NAME, STATUS, TRIGGERING_EVENT
  FROM ALL_TRIGGERS
 WHERE OWNER IN (UPPER(SYS_CONTEXT('USERENV','CURRENT_SCHEMA')),'SANKHYA')
   AND (TABLE_NAME IN ('TGFPRO','TGFITE','TGFCUS','TGFFIN','TSIBAI','TSIEND')
        OR TRIGGER_NAME LIKE 'TRG_RMD%')
 ORDER BY OWNER, TABLE_NAME, TRIGGER_NAME;

SELECT OWNER, OBJECT_NAME, OBJECT_TYPE, STATUS, CREATED, LAST_DDL_TIME
  FROM ALL_OBJECTS
 WHERE (OWNER IN (UPPER(SYS_CONTEXT('USERENV','CURRENT_SCHEMA')),'SANKHYA')
        AND (OBJECT_NAME LIKE 'BKP_RMD%'
             OR OBJECT_NAME LIKE 'MAP_RMD%'
             OR OBJECT_NAME LIKE 'AUD_RMD%'
             OR OBJECT_NAME LIKE 'RMD_%'))
 ORDER BY OWNER, OBJECT_TYPE, OBJECT_NAME;

PROMPT ======================================================================
PROMPT CARD 09 - FUNCAO XML, ASSINATURA, ERROS E DEPENDENCIAS
PROMPT ======================================================================
SELECT OWNER, OBJECT_NAME, OBJECT_TYPE, STATUS
  FROM ALL_OBJECTS
 WHERE OBJECT_NAME='FNC_BUSCA_TAG_XML_GERAL'
 ORDER BY OWNER, OBJECT_TYPE;

SELECT OWNER, OBJECT_NAME, PACKAGE_NAME, OBJECT_TYPE, POSITION,
       ARGUMENT_NAME, IN_OUT, DATA_TYPE, DATA_LENGTH
  FROM ALL_ARGUMENTS
 WHERE OBJECT_NAME='FNC_BUSCA_TAG_XML_GERAL'
 ORDER BY OWNER, OBJECT_NAME, NVL(PACKAGE_NAME,'-'), SEQUENCE;

SELECT OWNER, NAME, TYPE, SEQUENCE, LINE, POSITION, TEXT
  FROM ALL_ERRORS
 WHERE NAME='FNC_BUSCA_TAG_XML_GERAL'
 ORDER BY OWNER, TYPE, SEQUENCE;

SELECT OWNER, NAME, TYPE, REFERENCED_OWNER, REFERENCED_NAME, REFERENCED_TYPE
  FROM ALL_DEPENDENCIES
 WHERE NAME='FNC_BUSCA_TAG_XML_GERAL'
 ORDER BY OWNER, REFERENCED_OWNER, REFERENCED_NAME, REFERENCED_TYPE;

PROMPT ======================================================================
PROMPT CARDS 08, 13, 14 E 15 - CANDIDATOS SOMENTE LEITURA
PROMPT ======================================================================
SELECT COUNT(*) AS CANDIDATOS_CARD08_PROTOCOLAMENTO
  FROM TGFCAB C
 WHERE EXISTS (SELECT 1 FROM TTKNOT N WHERE N.NUNOTA=C.NUNOTA)
   AND ((C.NUMPROTOC IS NULL AND EXISTS (
          SELECT 1 FROM TGFTOP T
           WHERE T.CODTIPOPER=C.CODTIPOPER
             AND T.DHALTER=C.DHTIPOPER
             AND T.CODMODDOC=55))
     OR (C.NUMPROTOCCTE IS NULL AND EXISTS (
          SELECT 1 FROM TGFTOP T
           WHERE T.CODTIPOPER=C.CODTIPOPER
             AND T.DHALTER=C.DHTIPOPER
             AND T.CODMODDOC=57)));

SELECT COUNT(*) AS CANDIDATOS_CARD13_TOPS_GOL
  FROM TGFTOP T
 WHERE NVL(T.GOLSINAL,99999) <> NVL(
       CASE WHEN T.ATUALEST='B' AND T.TIPMOV='V' AND T.ATUALFIN=1
                  AND T.TIPATUALFIN='I' AND T.CODMODDOC IN (55,59,65) THEN -1
            WHEN T.ATUALEST='E' AND T.TIPMOV IN ('D','C') AND T.ATUALFIN=-1
                  AND T.TIPATUALFIN='I' AND T.CODMODDOC IN (55,59,65) THEN -1
            WHEN T.ATUALEST='B' AND T.TIPMOV='E' AND T.ATUALFIN=1
                  AND T.TIPATUALFIN='I' AND T.CODMODDOC IN (55,59,65) THEN 1
            ELSE 0 END,99999);

SELECT COUNT(*) AS CANDIDATOS_CARD14_ANALISE_848
  FROM TSIIMP
 WHERE CODREL=848;

SELECT COUNT(*) AS CANDIDATOS_CARD15_RASTRO
  FROM TGFPRO
 WHERE TEMRASTROLOTE='S'
   AND TIPCONTEST='N';

PROMPT ======================================================================
PROMPT CARDS 29 E 30 - COLISOES NORMALIZADAS
PROMPT ======================================================================
SELECT COUNT(*) AS GRUPOS_COLISAO_BAIRROS
  FROM (
    SELECT REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEBAI),
      'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ','AAAAAEEEEIIIIOOOOOUUUUC')),
      '[[:space:]]+',' ') AS NORM
      FROM TSIBAI
     GROUP BY REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEBAI),
      'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ','AAAAAEEEEIIIIOOOOOUUUUC')),
      '[[:space:]]+',' ')
    HAVING COUNT(*)>1
  );

SELECT COUNT(*) AS GRUPOS_COLISAO_ENDERECOS
  FROM (
    SELECT TIPO, REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEEND),
      'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ','AAAAAEEEEIIIIOOOOOUUUUC')),
      '[[:space:]]+',' ') AS NORM
      FROM TSIEND
     GROUP BY TIPO, REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEEND),
      'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ','AAAAAEEEEIIIIOOOOOUUUUC')),
      '[[:space:]]+',' ')
    HAVING COUNT(*)>1
  );

SELECT FK.OWNER AS FK_OWNER,
       FK.CONSTRAINT_NAME,
       FK.TABLE_NAME AS CHILD_TABLE,
       FKC.COLUMN_NAME AS CHILD_COLUMN,
       PK.OWNER AS PARENT_OWNER,
       PK.TABLE_NAME AS PARENT_TABLE,
       PKC.COLUMN_NAME AS PARENT_COLUMN,
       FKC.POSITION
  FROM ALL_CONSTRAINTS FK
  JOIN ALL_CONS_COLUMNS FKC
    ON FKC.OWNER=FK.OWNER AND FKC.CONSTRAINT_NAME=FK.CONSTRAINT_NAME
  JOIN ALL_CONSTRAINTS PK
    ON PK.OWNER=FK.R_OWNER AND PK.CONSTRAINT_NAME=FK.R_CONSTRAINT_NAME
  JOIN ALL_CONS_COLUMNS PKC
    ON PKC.OWNER=PK.OWNER AND PKC.CONSTRAINT_NAME=PK.CONSTRAINT_NAME
   AND PKC.POSITION=FKC.POSITION
 WHERE FK.CONSTRAINT_TYPE='R'
   AND PK.TABLE_NAME IN ('TSIBAI','TSIEND')
 ORDER BY PK.TABLE_NAME, FK.OWNER, FK.TABLE_NAME, FK.CONSTRAINT_NAME, FKC.POSITION;

SELECT COUNT(*) AS NOTAS_JA_COM_FINANCEIRO
  FROM TGFCAB C
 WHERE EXISTS (SELECT 1 FROM TGFFIN F WHERE F.NUNOTA=C.NUNOTA);

PROMPT ======================================================================
PROMPT CUSTOS E CONSOLIDACAO GOL - SOMENTE LEITURA
PROMPT ======================================================================
SELECT OWNER, OBJECT_NAME, OBJECT_TYPE, STATUS, CREATED, LAST_DDL_TIME
  FROM ALL_OBJECTS
 WHERE OBJECT_NAME IN (
       'STP_CALCCUSTOMEDIOPRODGENERICO','STP_CALCULARCUSTOMEDIODIA',
       'STP_CALCULARCUSTOMEDIOFAMILIA','STP_CALCULARCUSTOPRODGENERICO',
       'STP_PROCESSOATUALCUSTO','STP_EFETIVA_CONSOLIDACAO_GOL',
       'PFCM_CONSOLIDACAO','SNK_MATGIRCALCTOTAIS'
   )
 ORDER BY OWNER, OBJECT_NAME, OBJECT_TYPE;

PROMPT ======================================================================
PROMPT OBJETOS INVALIDOS - UM POR LINHA
PROMPT ======================================================================
SELECT OWNER, OBJECT_TYPE, OBJECT_NAME, STATUS
  FROM ALL_OBJECTS
 WHERE STATUS='INVALID'
 ORDER BY OWNER, OBJECT_TYPE, OBJECT_NAME;

PROMPT ======================================================================
PROMPT FIM DO PREFLIGHT - NENHUM DML/DDL EXECUTADO
PROMPT ======================================================================
SPOOL OFF
