-- Cards 29/30 - merge antifragil especifico de VITRINI DIRETA (ACM BRASIL).
-- Mapeia colisao, faz backup qualificado, corrige referencias CODBAI/CODEND
-- e FKs com nomes proprios; exclui pais somente com referencias=0.
-- Nao contem senha.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET SQLBLANKLINES ON
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
SET TRIMSPOOL ON
SPOOL "/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Clientes/VITRINI DIRETA (ACM BRASIL)/Logs/29_30_Merge_Antifragil_RMD_VDA_20260918080832.log"

DECLARE
  v_owner VARCHAR2(128):=SYS_CONTEXT('USERENV','CURRENT_SCHEMA');
  v_n NUMBER;
  PROCEDURE cria(p_nome VARCHAR2,p_ddl VARCHAR2) IS
  BEGIN
    SELECT COUNT(*) INTO v_n FROM ALL_TABLES WHERE OWNER=v_owner AND TABLE_NAME=p_nome;
    IF v_n=0 THEN EXECUTE IMMEDIATE p_ddl; END IF;
  END;
BEGIN
  cria('RMD_VDA_2930_MAP','CREATE TABLE RMD_VDA_2930_MAP (ID_EXECUCAO VARCHAR2(40) NOT NULL,TIPO VARCHAR2(4) NOT NULL,COD_OBSOLETO NUMBER NOT NULL,COD_MANTIDO NUMBER NOT NULL,CHAVE_NORM VARCHAR2(4000),DH_LOG TIMESTAMP NOT NULL)');
  cria('RMD_VDA_2930_BAI_BKP','CREATE TABLE RMD_VDA_2930_BAI_BKP AS SELECT CAST(NULL AS VARCHAR2(40)) ID_EXECUCAO,CAST(NULL AS TIMESTAMP) DH_EXECUCAO,CAST(NULL AS VARCHAR2(128)) USUARIO_EXECUCAO,B.* FROM TSIBAI B WHERE 1=0');
  cria('RMD_VDA_2930_END_BKP','CREATE TABLE RMD_VDA_2930_END_BKP AS SELECT CAST(NULL AS VARCHAR2(40)) ID_EXECUCAO,CAST(NULL AS TIMESTAMP) DH_EXECUCAO,CAST(NULL AS VARCHAR2(128)) USUARIO_EXECUCAO,E.* FROM TSIEND E WHERE 1=0');
  cria('RMD_VDA_2930_DEP','CREATE TABLE RMD_VDA_2930_DEP (ID_EXECUCAO VARCHAR2(40) NOT NULL,TABLE_NAME VARCHAR2(128) NOT NULL,COLUMN_NAME VARCHAR2(128) NOT NULL,RID VARCHAR2(30) NOT NULL,OLD_VALUE NUMBER,NEW_VALUE NUMBER,DH_LOG TIMESTAMP NOT NULL)');
  cria('RMD_VDA_2930_EXC','CREATE TABLE RMD_VDA_2930_EXC (ID_EXECUCAO VARCHAR2(40) NOT NULL,TABLE_NAME VARCHAR2(128) NOT NULL,COLUMN_NAME VARCHAR2(128) NOT NULL,MENSAGEM VARCHAR2(1000) NOT NULL,DH_LOG TIMESTAMP NOT NULL)');
  DBMS_OUTPUT.PUT_LINE('AUDITORIA_29_30=CRIADA_OU_EXISTENTE');
END;
/

DECLARE
  v_owner VARCHAR2(128):=SYS_CONTEXT('USERENV','CURRENT_SCHEMA');
  v_id VARCHAR2(40):='RMD_VDA_2930_'||TO_CHAR(SYSTIMESTAMP,'YYYYMMDDHH24MISSFF3');
  v_sql VARCHAR2(32767);
  v_n NUMBER:=0;
  v_refs NUMBER:=0;
  v_exc NUMBER:=0;
  v_map_bai NUMBER:=0;
  v_map_end NUMBER:=0;
  v_bkp_bai NUMBER:=0;
  v_bkp_end NUMBER:=0;
  v_del_bai NUMBER:=0;
  v_del_end NUMBER:=0;
  PROCEDURE excecao(p_tab VARCHAR2,p_col VARCHAR2,p_msg VARCHAR2) IS
  BEGIN
    INSERT INTO RMD_VDA_2930_EXC(ID_EXECUCAO,TABLE_NAME,COLUMN_NAME,MENSAGEM,DH_LOG)
    VALUES(v_id,p_tab,p_col,SUBSTR(p_msg,1,1000),SYSTIMESTAMP);
    v_exc:=v_exc+1;
  END;
BEGIN
  DBMS_OUTPUT.PUT_LINE('ID_EXECUCAO='||v_id);
  DBMS_OUTPUT.PUT_LINE('OWNER_OPERACIONAL='||v_owner);

  DELETE FROM RMD_VDA_2930_MAP WHERE ID_EXECUCAO=v_id;
  DELETE FROM RMD_VDA_2930_DEP WHERE ID_EXECUCAO=v_id;
  DELETE FROM RMD_VDA_2930_EXC WHERE ID_EXECUCAO=v_id;

  INSERT INTO RMD_VDA_2930_MAP(ID_EXECUCAO,TIPO,COD_OBSOLETO,COD_MANTIDO,CHAVE_NORM,DH_LOG)
  SELECT v_id,'BAI',CODBAI,KEEP_ID,NORM,SYSTIMESTAMP
    FROM (
      SELECT CODBAI,NORM,MIN(CODBAI) OVER(PARTITION BY NORM) KEEP_ID,COUNT(*) OVER(PARTITION BY NORM) QTD
        FROM (
          SELECT CODBAI,REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEBAI),
            'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ','AAAAAEEEEIIIIOOOOOUUUUC')),' {2,}',' ') NORM
            FROM TSIBAI
        ) WHERE NORM IS NOT NULL
    ) WHERE QTD>1 AND CODBAI<>KEEP_ID;
  v_map_bai:=SQL%ROWCOUNT;

  INSERT INTO RMD_VDA_2930_MAP(ID_EXECUCAO,TIPO,COD_OBSOLETO,COD_MANTIDO,CHAVE_NORM,DH_LOG)
  SELECT v_id,'END',CODEND,KEEP_ID,TO_CHAR(TIPO)||'|'||NORM,SYSTIMESTAMP
    FROM (
      SELECT CODEND,TIPO,NORM,MIN(CODEND) OVER(PARTITION BY TIPO,NORM) KEEP_ID,COUNT(*) OVER(PARTITION BY TIPO,NORM) QTD
        FROM (
          SELECT CODEND,TIPO,REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEEND),
            'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ','AAAAAEEEEIIIIOOOOOUUUUC')),' {2,}',' ') NORM
            FROM TSIEND
        ) WHERE NORM IS NOT NULL
    ) WHERE QTD>1 AND CODEND<>KEEP_ID;
  v_map_end:=SQL%ROWCOUNT;

  INSERT INTO RMD_VDA_2930_BAI_BKP
  SELECT v_id,SYSTIMESTAMP,SYS_CONTEXT('USERENV','SESSION_USER'),B.* FROM TSIBAI B
   WHERE EXISTS (SELECT 1 FROM RMD_VDA_2930_MAP M WHERE M.ID_EXECUCAO=v_id AND M.TIPO='BAI' AND (M.COD_OBSOLETO=B.CODBAI OR M.COD_MANTIDO=B.CODBAI));
  v_bkp_bai:=SQL%ROWCOUNT;
  INSERT INTO RMD_VDA_2930_END_BKP
  SELECT v_id,SYSTIMESTAMP,SYS_CONTEXT('USERENV','SESSION_USER'),E.* FROM TSIEND E
   WHERE EXISTS (SELECT 1 FROM RMD_VDA_2930_MAP M WHERE M.ID_EXECUCAO=v_id AND M.TIPO='END' AND (M.COD_OBSOLETO=E.CODEND OR M.COD_MANTIDO=E.CODEND));
  v_bkp_end:=SQL%ROWCOUNT;
  IF v_bkp_bai<v_map_bai OR v_bkp_end<v_map_end THEN
    RAISE_APPLICATION_ERROR(-20480,'Backup qualificado menor que mapa: BAI='||v_bkp_bai||'/'||v_map_bai||', END='||v_bkp_end||'/'||v_map_end);
  END IF;
  DBMS_OUTPUT.PUT_LINE('MAPA_BAI='||v_map_bai||'; BACKUP_BAI='||v_bkp_bai);
  DBMS_OUTPUT.PUT_LINE('MAPA_END='||v_map_end||'; BACKUP_END='||v_bkp_end);

  FOR r IN (
    SELECT DISTINCT C.TABLE_NAME,C.COLUMN_NAME
      FROM ALL_TAB_COLUMNS C JOIN ALL_TABLES T ON T.OWNER=C.OWNER AND T.TABLE_NAME=C.TABLE_NAME
     WHERE C.OWNER=v_owner AND C.COLUMN_NAME IN ('CODBAI','CODEND')
       AND C.TABLE_NAME NOT IN ('TSIBAI','TSIEND')
       AND C.TABLE_NAME NOT LIKE 'BKP_%' AND C.TABLE_NAME NOT LIKE 'RMD_VDA_2930%'
     ORDER BY C.TABLE_NAME,C.COLUMN_NAME
  ) LOOP
    SAVEPOINT RMD_VDA_BRANCH;
    BEGIN
      IF r.COLUMN_NAME='CODBAI' THEN
        v_sql:='INSERT INTO RMD_VDA_2930_DEP SELECT :1,:2,:3,ROWIDTOCHAR(T.ROWID),T.CODBAI,M.COD_MANTIDO,SYSTIMESTAMP FROM '||r.TABLE_NAME||' T JOIN RMD_VDA_2930_MAP M ON M.ID_EXECUCAO=:4 AND M.TIPO=''BAI'' AND M.COD_OBSOLETO=T.CODBAI';
        EXECUTE IMMEDIATE v_sql USING v_id,r.TABLE_NAME,r.COLUMN_NAME,v_id;
        v_sql:='UPDATE '||r.TABLE_NAME||' T SET CODBAI=(SELECT M.COD_MANTIDO FROM RMD_VDA_2930_MAP M WHERE M.ID_EXECUCAO=:1 AND M.TIPO=''BAI'' AND M.COD_OBSOLETO=T.CODBAI) WHERE EXISTS (SELECT 1 FROM RMD_VDA_2930_MAP M WHERE M.ID_EXECUCAO=:2 AND M.TIPO=''BAI'' AND M.COD_OBSOLETO=T.CODBAI)';
      ELSE
        v_sql:='INSERT INTO RMD_VDA_2930_DEP SELECT :1,:2,:3,ROWIDTOCHAR(T.ROWID),T.CODEND,M.COD_MANTIDO,SYSTIMESTAMP FROM '||r.TABLE_NAME||' T JOIN RMD_VDA_2930_MAP M ON M.ID_EXECUCAO=:4 AND M.TIPO=''END'' AND M.COD_OBSOLETO=T.CODEND';
        EXECUTE IMMEDIATE v_sql USING v_id,r.TABLE_NAME,r.COLUMN_NAME,v_id;
        v_sql:='UPDATE '||r.TABLE_NAME||' T SET CODEND=(SELECT M.COD_MANTIDO FROM RMD_VDA_2930_MAP M WHERE M.ID_EXECUCAO=:1 AND M.TIPO=''END'' AND M.COD_OBSOLETO=T.CODEND) WHERE EXISTS (SELECT 1 FROM RMD_VDA_2930_MAP M WHERE M.ID_EXECUCAO=:2 AND M.TIPO=''END'' AND M.COD_OBSOLETO=T.CODEND)';
      END IF;
      EXECUTE IMMEDIATE v_sql USING v_id,v_id;
      DBMS_OUTPUT.PUT_LINE('RAMO_OK|'||r.TABLE_NAME||'|'||r.COLUMN_NAME||'|'||SQL%ROWCOUNT);
    EXCEPTION WHEN OTHERS THEN
      ROLLBACK TO RMD_VDA_BRANCH;
      excecao(r.TABLE_NAME,r.COLUMN_NAME,SQLERRM);
      DBMS_OUTPUT.PUT_LINE('RAMO_EXCECAO|'||r.TABLE_NAME||'|'||r.COLUMN_NAME||'|'||SQLERRM);
    END;
  END LOOP;

  FOR r IN (
    SELECT DISTINCT C.TABLE_NAME,CC.COLUMN_NAME,P.TABLE_NAME PAI
      FROM ALL_CONSTRAINTS C
      JOIN ALL_CONS_COLUMNS CC ON CC.OWNER=C.OWNER AND CC.CONSTRAINT_NAME=C.CONSTRAINT_NAME
      JOIN ALL_CONSTRAINTS P ON P.OWNER=C.R_OWNER AND P.CONSTRAINT_NAME=C.R_CONSTRAINT_NAME
      JOIN ALL_CONS_COLUMNS PC ON PC.OWNER=P.OWNER AND PC.CONSTRAINT_NAME=P.CONSTRAINT_NAME AND PC.POSITION=CC.POSITION
     WHERE C.OWNER=v_owner AND C.CONSTRAINT_TYPE='R' AND P.OWNER=v_owner AND P.TABLE_NAME IN ('TSIBAI','TSIEND')
       AND PC.COLUMN_NAME IN ('CODBAI','CODEND') AND CC.COLUMN_NAME NOT IN ('CODBAI','CODEND')
       AND C.TABLE_NAME NOT IN ('TSIBAI','TSIEND')
       AND C.TABLE_NAME NOT LIKE 'BKP_%' AND C.TABLE_NAME NOT LIKE 'RMD_VDA_2930%'
     ORDER BY C.TABLE_NAME,CC.COLUMN_NAME
  ) LOOP
    SAVEPOINT RMD_VDA_FK_BRANCH;
    BEGIN
      IF r.PAI='TSIBAI' THEN
        v_sql:='INSERT INTO RMD_VDA_2930_DEP SELECT :1,:2,:3,ROWIDTOCHAR(T.ROWID),T.'||r.COLUMN_NAME||',M.COD_MANTIDO,SYSTIMESTAMP FROM '||r.TABLE_NAME||' T JOIN RMD_VDA_2930_MAP M ON M.ID_EXECUCAO=:4 AND M.TIPO=''BAI'' AND M.COD_OBSOLETO=T.'||r.COLUMN_NAME;
        EXECUTE IMMEDIATE v_sql USING v_id,r.TABLE_NAME,r.COLUMN_NAME,v_id;
        v_sql:='UPDATE '||r.TABLE_NAME||' T SET '||r.COLUMN_NAME||'=(SELECT M.COD_MANTIDO FROM RMD_VDA_2930_MAP M WHERE M.ID_EXECUCAO=:1 AND M.TIPO=''BAI'' AND M.COD_OBSOLETO=T.'||r.COLUMN_NAME||') WHERE EXISTS (SELECT 1 FROM RMD_VDA_2930_MAP M WHERE M.ID_EXECUCAO=:2 AND M.TIPO=''BAI'' AND M.COD_OBSOLETO=T.'||r.COLUMN_NAME||')';
      ELSE
        v_sql:='INSERT INTO RMD_VDA_2930_DEP SELECT :1,:2,:3,ROWIDTOCHAR(T.ROWID),T.'||r.COLUMN_NAME||',M.COD_MANTIDO,SYSTIMESTAMP FROM '||r.TABLE_NAME||' T JOIN RMD_VDA_2930_MAP M ON M.ID_EXECUCAO=:4 AND M.TIPO=''END'' AND M.COD_OBSOLETO=T.'||r.COLUMN_NAME;
        EXECUTE IMMEDIATE v_sql USING v_id,r.TABLE_NAME,r.COLUMN_NAME,v_id;
        v_sql:='UPDATE '||r.TABLE_NAME||' T SET '||r.COLUMN_NAME||'=(SELECT M.COD_MANTIDO FROM RMD_VDA_2930_MAP M WHERE M.ID_EXECUCAO=:1 AND M.TIPO=''END'' AND M.COD_OBSOLETO=T.'||r.COLUMN_NAME||') WHERE EXISTS (SELECT 1 FROM RMD_VDA_2930_MAP M WHERE M.ID_EXECUCAO=:2 AND M.TIPO=''END'' AND M.COD_OBSOLETO=T.'||r.COLUMN_NAME||')';
      END IF;
      EXECUTE IMMEDIATE v_sql USING v_id,v_id;
      DBMS_OUTPUT.PUT_LINE('FK_RAMO_OK|'||r.TABLE_NAME||'|'||r.COLUMN_NAME||'|'||SQL%ROWCOUNT);
    EXCEPTION WHEN OTHERS THEN
      ROLLBACK TO RMD_VDA_FK_BRANCH;
      excecao(r.TABLE_NAME,r.COLUMN_NAME,SQLERRM);
      DBMS_OUTPUT.PUT_LINE('FK_RAMO_EXCECAO|'||r.TABLE_NAME||'|'||r.COLUMN_NAME||'|'||SQLERRM);
    END;
  END LOOP;

  FOR r IN (
    SELECT DISTINCT C.TABLE_NAME,C.COLUMN_NAME
      FROM ALL_TAB_COLUMNS C JOIN ALL_TABLES T ON T.OWNER=C.OWNER AND T.TABLE_NAME=C.TABLE_NAME
     WHERE C.OWNER=v_owner AND C.COLUMN_NAME IN ('CODBAI','CODEND')
       AND C.TABLE_NAME NOT IN ('TSIBAI','TSIEND')
       AND C.TABLE_NAME NOT LIKE 'BKP_%' AND C.TABLE_NAME NOT LIKE 'RMD_VDA_2930%'
  ) LOOP
    IF r.COLUMN_NAME='CODBAI' THEN v_sql:='SELECT COUNT(*) FROM '||r.TABLE_NAME||' T WHERE EXISTS (SELECT 1 FROM RMD_VDA_2930_MAP M WHERE M.ID_EXECUCAO=:1 AND M.TIPO=''BAI'' AND M.COD_OBSOLETO=T.CODBAI)';
    ELSE v_sql:='SELECT COUNT(*) FROM '||r.TABLE_NAME||' T WHERE EXISTS (SELECT 1 FROM RMD_VDA_2930_MAP M WHERE M.ID_EXECUCAO=:1 AND M.TIPO=''END'' AND M.COD_OBSOLETO=T.CODEND)'; END IF;
    EXECUTE IMMEDIATE v_sql INTO v_n USING v_id; v_refs:=v_refs+v_n;
  END LOOP;
  FOR r IN (
    SELECT DISTINCT C.TABLE_NAME,CC.COLUMN_NAME,P.TABLE_NAME PAI
      FROM ALL_CONSTRAINTS C JOIN ALL_CONS_COLUMNS CC ON CC.OWNER=C.OWNER AND CC.CONSTRAINT_NAME=C.CONSTRAINT_NAME
      JOIN ALL_CONSTRAINTS P ON P.OWNER=C.R_OWNER AND P.CONSTRAINT_NAME=C.R_CONSTRAINT_NAME
      JOIN ALL_CONS_COLUMNS PC ON PC.OWNER=P.OWNER AND PC.CONSTRAINT_NAME=P.CONSTRAINT_NAME AND PC.POSITION=CC.POSITION
     WHERE C.OWNER=v_owner AND C.CONSTRAINT_TYPE='R' AND P.OWNER=v_owner AND P.TABLE_NAME IN ('TSIBAI','TSIEND')
       AND PC.COLUMN_NAME IN ('CODBAI','CODEND') AND CC.COLUMN_NAME NOT IN ('CODBAI','CODEND')
       AND C.TABLE_NAME NOT IN ('TSIBAI','TSIEND') AND C.TABLE_NAME NOT LIKE 'BKP_%' AND C.TABLE_NAME NOT LIKE 'RMD_VDA_2930%'
  ) LOOP
    IF r.PAI='TSIBAI' THEN v_sql:='SELECT COUNT(*) FROM '||r.TABLE_NAME||' T WHERE EXISTS (SELECT 1 FROM RMD_VDA_2930_MAP M WHERE M.ID_EXECUCAO=:1 AND M.TIPO=''BAI'' AND M.COD_OBSOLETO=T.'||r.COLUMN_NAME||')';
    ELSE v_sql:='SELECT COUNT(*) FROM '||r.TABLE_NAME||' T WHERE EXISTS (SELECT 1 FROM RMD_VDA_2930_MAP M WHERE M.ID_EXECUCAO=:1 AND M.TIPO=''END'' AND M.COD_OBSOLETO=T.'||r.COLUMN_NAME||')'; END IF;
    EXECUTE IMMEDIATE v_sql INTO v_n USING v_id; v_refs:=v_refs+v_n;
  END LOOP;

  IF v_exc>0 THEN
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('STATUS=ISOLADO_COM_EXCECOES; ID_EXECUCAO='||v_id||'; EXCECOES='||v_exc||'; REFERENCIAS_REMANESCENTES='||v_refs);
  ELSIF v_refs<>0 THEN
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('STATUS=ISOLADO_REFERENCIAS_REMANESCENTES; ID_EXECUCAO='||v_id||'; EXCECOES=0; REFERENCIAS_REMANESCENTES='||v_refs);
  ELSE
    DELETE FROM TSIBAI WHERE CODBAI IN (SELECT COD_OBSOLETO FROM RMD_VDA_2930_MAP WHERE ID_EXECUCAO=v_id AND TIPO='BAI'); v_del_bai:=SQL%ROWCOUNT;
    DELETE FROM TSIEND WHERE CODEND IN (SELECT COD_OBSOLETO FROM RMD_VDA_2930_MAP WHERE ID_EXECUCAO=v_id AND TIPO='END'); v_del_end:=SQL%ROWCOUNT;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('PAIS_BAI_EXCLUIDOS='||v_del_bai||'; PAIS_END_EXCLUIDOS='||v_del_end);
    DBMS_OUTPUT.PUT_LINE('STATUS=CONCLUIDO_COM_MAPA_BACKUP_FK; ID_EXECUCAO='||v_id||'; EXCECOES=0; REFERENCIAS_REMANESCENTES=0');
  END IF;
EXCEPTION WHEN OTHERS THEN ROLLBACK; RAISE;
END;
/

PROMPT === POS-VALIDACAO 29/30 ===
SELECT 'TSIBAI_GRUPOS_COLISAO_REMANESCENTES' ITEM,COUNT(*) QTD FROM (
 SELECT REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEBAI),'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ','AAAAAEEEEIIIIOOOOOUUUUC')),' {2,}',' ') N FROM TSIBAI WHERE NOMEBAI IS NOT NULL GROUP BY REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEBAI),'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ','AAAAAEEEEIIIIOOOOOUUUUC')),' {2,}',' ') HAVING COUNT(*)>1)
UNION ALL
SELECT 'TSIEND_GRUPOS_COLISAO_REMANESCENTES',COUNT(*) FROM (
 SELECT TIPO,REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEEND),'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ','AAAAAEEEEIIIIOOOOOUUUUCAAAAAEEEEIIIIOOOOOUUUUCAAAOOAAEIIOOUU')),' {2,}',' ') N FROM TSIEND WHERE NOMEEND IS NOT NULL GROUP BY TIPO,REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEEND),'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ','AAAAAEEEEIIIIOOOOOUUUUCAAAAAEEEEIIIIOOOOOUUUUCAAAOOAAEIIOOUU')),' {2,}',' ') HAVING COUNT(*)>1);

SELECT ID_EXECUCAO,TIPO,COUNT(*) QTD FROM RMD_VDA_2930_MAP GROUP BY ID_EXECUCAO,TIPO ORDER BY ID_EXECUCAO,TIPO;
SELECT ID_EXECUCAO,COUNT(*) QTD FROM RMD_VDA_2930_EXC GROUP BY ID_EXECUCAO ORDER BY ID_EXECUCAO;
PROMPT === FIM MERGE ANTIFRAGIL 29/30 VITRINI DIRETA ===
SPOOL OFF
