-- Preflight read-only dos Cards 29/30 depois do Master.
-- Nao contem DML, DDL, senha ou alteracao de objeto.
SET DEFINE OFF
SET ECHO ON
SET FEEDBACK ON
SET HEADING ON
SET LINESIZE 240
SET PAGESIZE 200
SET TRIMSPOOL ON
SPOOL "/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Clientes/VITRINI DIRETA (ACM BRASIL)/Logs/29_30_Preflight_FK_ReadOnly_RMD_VDA_20260918080832.log"

PROMPT === RESUMO DOS GRUPOS DE COLISAO ===
SELECT 'TSIBAI_GRUPOS_COLISAO' ITEM,COUNT(*) QTD
  FROM (
    SELECT REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEBAI),
      'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ','AAAAAEEEEIIIIOOOOOUUUUC')),' {2,}',' ') N
      FROM TSIBAI
     WHERE NOMEBAI IS NOT NULL
     GROUP BY REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEBAI),
      'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ','AAAAAEEEEIIIIOOOOOUUUUC')),' {2,}',' ')
    HAVING COUNT(*)>1
  )
UNION ALL
SELECT 'TSIEND_GRUPOS_COLISAO' ITEM,COUNT(*) QTD
  FROM (
    SELECT TIPO,REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEEND),
      'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ','AAAAAEEEEIIIIOOOOOUUUUC')),' {2,}',' ') N
      FROM TSIEND
     WHERE NOMEEND IS NOT NULL
     GROUP BY TIPO,REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEEND),
      'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ','AAAAAEEEEIIIIOOOOOUUUUC')),' {2,}',' ')
    HAVING COUNT(*)>1
  );

PROMPT === TABELAS FISICAS COM CODBAI/CODEND ===
SELECT C.OWNER,C.TABLE_NAME,C.COLUMN_NAME
  FROM ALL_TAB_COLUMNS C
  JOIN ALL_TABLES T ON T.OWNER=C.OWNER AND T.TABLE_NAME=C.TABLE_NAME
 WHERE C.OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
   AND C.COLUMN_NAME IN ('CODBAI','CODEND')
 ORDER BY C.TABLE_NAME,C.COLUMN_NAME;

PROMPT === FKS PARA TSIBAI/TSIEND, INCLUSIVE COMPOSTAS ===
SELECT C.OWNER,C.TABLE_NAME,C.CONSTRAINT_NAME,CC.POSITION,CC.COLUMN_NAME,
       P.TABLE_NAME REFERENCED_TABLE,PC.COLUMN_NAME REFERENCED_COLUMN
  FROM ALL_CONSTRAINTS C
  JOIN ALL_CONS_COLUMNS CC
    ON CC.OWNER=C.OWNER AND CC.CONSTRAINT_NAME=C.CONSTRAINT_NAME
  JOIN ALL_CONSTRAINTS P
    ON P.OWNER=C.R_OWNER AND P.CONSTRAINT_NAME=C.R_CONSTRAINT_NAME
  LEFT JOIN ALL_CONS_COLUMNS PC
    ON PC.OWNER=P.OWNER AND PC.CONSTRAINT_NAME=P.CONSTRAINT_NAME
   AND PC.POSITION=CC.POSITION
 WHERE C.OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
   AND C.CONSTRAINT_TYPE='R'
   AND P.OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
   AND P.TABLE_NAME IN ('TSIBAI','TSIEND')
 ORDER BY C.TABLE_NAME,C.CONSTRAINT_NAME,CC.POSITION;

PROMPT === QUOTA E OBJETOS DE AUDITORIA EXISTENTES ===
SELECT TABLESPACE_NAME,MAX_BYTES, BYTES FROM USER_TS_QUOTAS ORDER BY TABLESPACE_NAME;
SELECT TABLE_NAME FROM USER_TABLES
 WHERE TABLE_NAME IN ('RMD_VDA_2930_MAP','RMD_VDA_2930_BAI_BKP','RMD_VDA_2930_END_BKP','RMD_VDA_2930_DEP','RMD_VDA_2930_EXC')
 ORDER BY TABLE_NAME;

PROMPT === FIM PREFLIGHT 29/30 ===
SPOOL OFF
