-- Card 09 - preflight sem function instalada.
-- Extrai vDup, dVenc e nDup diretamente de TGFNFE.XML com XMLTABLE.
-- Nao cria/altera function e nao altera TGFCAB, TGFTOP ou TGFFIN.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET SQLBLANKLINES ON
SET ECHO ON
SET FEEDBACK ON
SET TRIMSPOOL ON
WHENEVER OSERROR EXIT FAILURE ROLLBACK
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

SPOOL "/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Clientes/VITRINI DIRETA (ACM BRASIL)/Logs/Card09_Preflight_Direto_XML_VDA_20260918_R02.log"

PROMPT === CARD 09 - PREFLIGHT DIRETO XML SEM FUNCTION ===
PROMPT ID_EXECUCAO=VDA_FDUP_20260918_01
PROMPT FONTE_XML=SANKHYA.TGFNFE.XML; EXTRACAO=XMLTABLE; TGFFIN_ALTERADO=NAO

DECLARE
  v_qtd NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_qtd
    FROM ALL_TABLES
   WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
     AND TABLE_NAME='BKP_VDA_FDUP_20260918';
  IF v_qtd>0 THEN
    RAISE_APPLICATION_ERROR(-20601,'Tabela BKP_VDA_FDUP_20260918 ja existe; use novo ID antes de repetir.');
  END IF;

  EXECUTE IMMEDIATE q'~
    CREATE TABLE BKP_VDA_FDUP_20260918 AS
    WITH CANDIDATES AS (
      SELECT
        C.NUNOTA, C.CODEMP, C.NUMNOTA, C.SERIENOTA, C.DTNEG, C.DTMOV,
        C.CODPARC, C.CODTIPOPER, T.DESCROPER, C.VLRNOTA
      FROM TGFCAB C
      JOIN TGFTOP T
        ON C.CODTIPOPER=T.CODTIPOPER
       AND C.DHTIPOPER=T.DHALTER
      WHERE T.ATUALFIN<>0
        AND C.TIPMOV<>'Z'
        AND NOT EXISTS (SELECT 1 FROM TGFFIN F WHERE F.NUNOTA=C.NUNOTA)
    ), N AS (
      SELECT N.NUNOTA, N.XML,
             ROW_NUMBER() OVER(PARTITION BY NUNOTA ORDER BY ROWID) AS RN
        FROM TGFNFE N
        JOIN CANDIDATES C
          ON C.NUNOTA=N.NUNOTA
    )
    SELECT
      CAST('VDA_FDUP_20260918_01' AS VARCHAR2(40)) AS ID_EXECUCAO,
      SYSTIMESTAMP AS DH_EXECUCAO,
      SYS_CONTEXT('USERENV','SESSION_USER') AS USUARIO_EXECUCAO,
      C.NUNOTA, C.CODEMP, C.NUMNOTA, C.SERIENOTA, C.DTNEG, C.DTMOV,
      C.CODPARC, C.CODTIPOPER, C.DESCROPER, C.VLRNOTA,
      X.VDUP_XML, X.DVENC_XML, X.NDUP_XML
    FROM CANDIDATES C
    LEFT JOIN N
      ON N.NUNOTA=C.NUNOTA
     AND N.RN=1
    OUTER APPLY XMLTABLE(
      '//*[local-name()="dup"][1]'
      PASSING XMLTYPE(N.XML)
      COLUMNS
        VDUP_XML  VARCHAR2(4000) PATH '*[local-name()="vDup"][1]/text()',
        DVENC_XML VARCHAR2(4000) PATH '*[local-name()="dVenc"][1]/text()',
        NDUP_XML  VARCHAR2(4000) PATH '*[local-name()="nDup"][1]/text()'
    ) X
  ~';
END;
/

PROMPT === RESUMO DO PREFLIGHT DIRETO XML ===
SELECT COUNT(*) AS NOTAS_SEM_FINANCEIRO_TOTAL
  FROM BKP_VDA_FDUP_20260918;

SELECT COUNT(*) AS CANDIDATOS_DUP_DVENC_VALIDOS
  FROM BKP_VDA_FDUP_20260918
 WHERE VDUP_XML IS NOT NULL
   AND REGEXP_LIKE(DVENC_XML,'^[0-9]{4}-[0-9]{2}-[0-9]{2}$');

SELECT COUNT(*) AS SEM_DUP_PARA_ANALISE
  FROM BKP_VDA_FDUP_20260918
 WHERE VDUP_XML IS NULL;

SELECT COUNT(*) AS DUP_COM_XML_INVALIDO
  FROM BKP_VDA_FDUP_20260918
 WHERE VDUP_XML IS NOT NULL
   AND NOT REGEXP_LIKE(DVENC_XML,'^[0-9]{4}-[0-9]{2}-[0-9]{2}$');

SELECT CODTIPOPER,DESCROPER,COUNT(*) AS CANDIDATOS
  FROM BKP_VDA_FDUP_20260918
 WHERE VDUP_XML IS NOT NULL
   AND REGEXP_LIKE(DVENC_XML,'^[0-9]{4}-[0-9]{2}-[0-9]{2}$')
 GROUP BY CODTIPOPER,DESCROPER
 ORDER BY CODTIPOPER;

PROMPT === VALIDACAO DA FUNCTION INSTALADA ===
SELECT OWNER,OBJECT_NAME,OBJECT_TYPE,STATUS
  FROM ALL_OBJECTS
 WHERE OBJECT_NAME='FNC_BUSCA_TAG_XML_GERAL'
 ORDER BY OWNER,OBJECT_TYPE;

PROMPT === CARD 09 - PREFLIGHT DIRETO XML CONCLUIDO; NENHUM TGFFIN FOI ALTERADO ===
SPOOL OFF
