-- Card 09 - verificacao somente leitura da extracao direta do XML.
-- Usa a mesma reducao do dashboard e nao cria objetos nem altera TGFFIN.
SET DEFINE OFF
SET ECHO ON
SET FEEDBACK ON
SET TRIMSPOOL ON
SET PAGESIZE 100
WHENEVER OSERROR EXIT FAILURE ROLLBACK
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

SPOOL "/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Clientes/VITRINI DIRETA (ACM BRASIL)/Logs/Card09_Verificacao_Direto_XML_ReadOnly_VDA_20260918_R03.log"

PROMPT === CARD 09 - VERIFICACAO DIRETA XML READ ONLY ===
PROMPT ID_EXECUCAO=VDA_FDUP_20260918_R03
PROMPT CANDIDATOS=QUERY_DASHBOARD; EXTRACAO=XMLTABLE; TGFFIN_ALTERADO=NAO

SELECT COUNT(*) AS CANDIDATOS_SEM_FINANCEIRO
  FROM TGFCAB C
  JOIN TGFTOP T
    ON C.CODTIPOPER=T.CODTIPOPER
   AND C.DHTIPOPER=T.DHALTER
 WHERE T.ATUALFIN<>0
   AND C.TIPMOV<>'Z'
   AND NOT EXISTS (SELECT 1 FROM TGFFIN F WHERE F.NUNOTA=C.NUNOTA);

WITH CANDIDATES AS (
  SELECT
    C.NUNOTA, C.CODEMP, C.NUMNOTA, C.SERIENOTA, C.DTNEG, C.DTMOV,
    C.CODPARC, C.CODTIPOPER, T.DESCROPER, C.VLRNOTA
  FROM TGFCAB C
  JOIN TGFTOP T
    ON C.CODTIPOPER=T.CODTIPOPER
   AND C.DHTIPOPER=T.DHALTER
  WHERE T.ATUALFIN<>0
    AND C.TIPMOV<>'Z'
    AND NOT EXISTS (SELECT 1 FROM TGFFIN F WHERE F.NUNOTA=C.NUNOTA)
), N AS (
  SELECT N.NUNOTA, N.XML,
         ROW_NUMBER() OVER(PARTITION BY N.NUNOTA ORDER BY N.ROWID) AS RN
  FROM TGFNFE N
  JOIN CANDIDATES C
    ON C.NUNOTA=N.NUNOTA
)
SELECT
  C.NUNOTA, C.CODEMP, C.NUMNOTA, C.SERIENOTA, C.CODTIPOPER,
  C.DESCROPER, C.VLRNOTA,
  X.VDUP_XML, X.DVENC_XML, X.NDUP_XML
FROM CANDIDATES C
LEFT JOIN N
  ON N.NUNOTA=C.NUNOTA
 AND N.RN=1
OUTER APPLY XMLTABLE(
  '//*[local-name()="dup"][1]'
  PASSING XMLTYPE(N.XML)
  COLUMNS
    VDUP_XML  VARCHAR2(4000) PATH '*[local-name()="vDup"][1]/text()',
    DVENC_XML VARCHAR2(4000) PATH '*[local-name()="dVenc"][1]/text()',
    NDUP_XML  VARCHAR2(4000) PATH '*[local-name()="nDup"][1]/text()'
) X
ORDER BY C.NUNOTA;

PROMPT === CARD 09 - VERIFICACAO DIRETA XML READ ONLY CONCLUIDA ===
PROMPT NENHUM OBJETO FOI CRIADO; TGFFIN NAO FOI ALTERADA
SPOOL OFF
