-- Card 09 - mapa persistente para inclusao controlada de financeiros.
-- Esta etapa usa XMLTABLE diretamente em TGFNFE.XML e nao altera TGFFIN.

SET DEFINE ON
SET SERVEROUTPUT ON SIZE UNLIMITED
SET SQLBLANKLINES ON
SET PAGESIZE 1000
SET TRIMSPOOL ON
WHENEVER OSERROR EXIT FAILURE ROLLBACK
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

DEFINE ID_EXECUCAO = 'VDA_ACM_FDUP_20260918_02'
DEFINE TBL_BASE = 'BKP_RMD_VDA_FDUP_20260918_02'
DEFINE TBL_PPG = 'BKP_RMD_VDA_FDUP_20260918_02_PPG'

SPOOL "/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Clientes/VITRINI DIRETA (ACM BRASIL)/Logs/Card09_Mapa_Direto_XML_VDA_20260918_02.log"

PROMPT === CARD 09 - MAPA DIRETO XML ===
PROMPT ID_EXECUCAO=&ID_EXECUCAO
PROMPT FONTE_XML=SANKHYA.TGFNFE.XML; EXTRACAO=XMLTABLE; TGFFIN_ALTERADO=NAO

DECLARE
  v_qtd NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_qtd
    FROM ALL_TABLES
   WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
     AND TABLE_NAME IN ('&TBL_BASE','&TBL_PPG');
  IF v_qtd > 0 THEN
    RAISE_APPLICATION_ERROR(-20340,'Uma tabela do mapa ja existe; use novo ID antes de repetir.');
  END IF;
END;
/

CREATE TABLE &TBL_BASE AS
WITH CANDIDATES AS (
  SELECT C.NUNOTA, C.CODEMP, C.NUMNOTA, C.SERIENOTA, C.DTNEG, C.DTMOV,
         C.CODPARC, C.CODTIPOPER, T.DESCROPER, C.VLRNOTA
    FROM TGFCAB C
    JOIN TGFTOP T
      ON C.CODTIPOPER=T.CODTIPOPER
     AND C.DHTIPOPER=T.DHALTER
   WHERE T.ATUALFIN<>0
     AND C.TIPMOV<>'Z'
     AND NOT EXISTS (SELECT 1 FROM TGFFIN F WHERE F.NUNOTA=C.NUNOTA)
), N AS (
  SELECT N.NUNOTA, N.XML,
         ROW_NUMBER() OVER(PARTITION BY N.NUNOTA ORDER BY N.ROWID) AS RN
    FROM TGFNFE N
    JOIN CANDIDATES C ON C.NUNOTA=N.NUNOTA
)
SELECT '&ID_EXECUCAO' AS ID_EXECUCAO,
       SYSTIMESTAMP AS DH_EXECUCAO,
       SYS_CONTEXT('USERENV','SESSION_USER') AS USUARIO_EXECUCAO,
       C.NUNOTA, C.CODEMP, C.NUMNOTA, C.SERIENOTA, C.DTNEG, C.DTMOV,
       C.CODPARC, C.CODTIPOPER, C.DESCROPER, C.VLRNOTA,
       X.VDUP_XML, X.DVENC_XML, X.NDUP_XML
  FROM CANDIDATES C
  LEFT JOIN N
    ON N.NUNOTA=C.NUNOTA
   AND N.RN=1
  OUTER APPLY XMLTABLE(
    '//*[local-name()="dup"][1]'
    PASSING XMLTYPE(N.XML)
    COLUMNS
      VDUP_XML  VARCHAR2(4000) PATH '*[local-name()="vDup"][1]/text()',
      DVENC_XML VARCHAR2(4000) PATH '*[local-name()="dVenc"][1]/text()',
      NDUP_XML  VARCHAR2(4000) PATH '*[local-name()="nDup"][1]/text()'
  ) X;

CREATE TABLE &TBL_PPG AS
WITH C AS (
    SELECT B.ID_EXECUCAO, B.DH_EXECUCAO, B.USUARIO_EXECUCAO,
           B.NUNOTA, B.CODEMP, B.NUMNOTA, B.SERIENOTA, B.DTNEG,
           B.CODPARC, B.CODTIPOPER, B.DESCROPER,
           C.CODTIPVENDA, C.DHTIPOPER, C.DTENTSAI, C.DTMOV,
           C.DHTIPVENDA, C.CODVEND,
           C.CODNAT AS CODNAT_CAB, C.CODCENCUS AS CODCENCUS_CAB,
           C.CODPROJ AS CODPROJ_CAB, C.RATEADO AS RATEADO_CAB,
           B.VLRNOTA, B.VDUP_XML, B.DVENC_XML, B.NDUP_XML
      FROM &TBL_BASE B
      JOIN TGFCAB C ON C.NUNOTA=B.NUNOTA
     WHERE B.ID_EXECUCAO='&ID_EXECUCAO'
  ), P AS (
    SELECT C.*,
           P.TIPOEMP, P.CODEMP AS CODEMP_PPG, P.TIPOPAR,
           P.CODPARC AS CODPARC_PPG, P.SEQUENCIA AS SEQ_PPG,
           P.PRAZO, P.CODTIPTITPAD, P.CODBCOPAD, P.CODCTABCOINT,
           P.CODCENCUSPAD, P.CODNATPAD, P.CODPROJPAD,
           P.TIPRECDESP, P.TIPOFIN, P.PERCENTUAL,
           COUNT(P.CODTIPVENDA) OVER (PARTITION BY C.NUNOTA) AS QTD_PPG_ENCONTRADAS,
           COUNT(P.CODTIPVENDA) OVER (PARTITION BY C.NUNOTA, P.SEQUENCIA) AS QTD_PPG_MESMA_SEQ,
           ROW_NUMBER() OVER (
             PARTITION BY C.NUNOTA
             ORDER BY P.SEQUENCIA, P.PRAZO, P.TIPOEMP,
                      P.CODEMP, P.TIPOPAR, P.CODPARC
           ) AS RN_PPG
      FROM C
      LEFT JOIN TGFPPG P ON P.CODTIPVENDA=C.CODTIPVENDA
  )
  SELECT P.ID_EXECUCAO, P.DH_EXECUCAO, P.USUARIO_EXECUCAO,
         P.NUNOTA, P.NUMNOTA, P.SERIENOTA, P.CODEMP, P.CODPARC,
         P.CODTIPOPER, P.DESCROPER, P.CODTIPVENDA, P.DHTIPOPER,
         P.DTNEG, P.DTENTSAI, P.DTMOV, P.DHTIPVENDA, P.CODVEND,
         P.CODNAT_CAB, P.CODCENCUS_CAB, P.CODPROJ_CAB, P.RATEADO_CAB,
         P.TIPOEMP, P.CODEMP_PPG, P.TIPOPAR, P.CODPARC_PPG,
         P.SEQ_PPG, P.PRAZO, P.CODTIPTITPAD, P.CODBCOPAD,
         P.CODCTABCOINT, P.CODCENCUSPAD, P.CODNATPAD, P.CODPROJPAD,
         P.TIPRECDESP, P.TIPOFIN, P.PERCENTUAL,
         P.VLRNOTA, P.VDUP_XML, P.DVENC_XML, P.NDUP_XML,
         (SELECT MAX(N.ULTCOD) FROM TGFNUM N WHERE N.ARQUIVO='TGFFIN') AS ULTCOD_TGFNUM_ATUAL,
         CASE
           WHEN P.QTD_PPG_ENCONTRADAS=0 THEN 'SEM_TGFPPG'
           WHEN P.QTD_PPG_MESMA_SEQ>1 THEN 'REVISAR_DUPLICIDADE_TGFPPG'
           WHEN P.VDUP_XML IS NULL THEN 'SEM_VDUP_XML'
           WHEN NOT REGEXP_LIKE(P.DVENC_XML,'^[0-9]{4}-[0-9]{2}-[0-9]{2}$') THEN 'DVENC_XML_INVALIDO'
           WHEN P.CODTIPTITPAD IS NULL THEN 'SEM_CODTIPTITPAD'
           WHEN (SELECT COUNT(*) FROM TGFNUM N WHERE N.ARQUIVO='TGFFIN')<>1 THEN 'REVISAR_TGFNUM'
           ELSE 'APTO_PARA_VALIDACAO_FINAL'
         END AS STATUS_MAPA,
         CASE
           WHEN P.QTD_PPG_ENCONTRADAS=0 THEN 'Nao foi encontrada condicao em TGFPPG.'
           WHEN P.QTD_PPG_MESMA_SEQ>1 THEN 'Mais de uma TGFPPG para a mesma sequencia.'
           WHEN P.VDUP_XML IS NULL THEN 'vDup nao foi localizado no XML.'
           WHEN P.DVENC_XML IS NULL THEN 'dVenc deve ser obtido do XML.'
           WHEN P.CODTIPTITPAD IS NULL THEN 'Tipo de titulo ausente na condicao de pagamento.'
           ELSE 'Revisar valores antes do INSERT.'
         END AS OBSERVACAO
    FROM P
);

PROMPT === RESUMO DO MAPA ===
SELECT COUNT(*) AS CANDIDATOS_MAPA FROM &TBL_BASE WHERE ID_EXECUCAO='&ID_EXECUCAO';
SELECT STATUS_MAPA, COUNT(*) AS QTD
  FROM &TBL_PPG
 WHERE ID_EXECUCAO='&ID_EXECUCAO'
 GROUP BY STATUS_MAPA
 ORDER BY STATUS_MAPA;

PROMPT === DETALHE PARA REVISAO ===
SELECT NUNOTA, CODEMP, NUMNOTA, CODTIPOPER, CODTIPVENDA, SEQ_PPG,
       VDUP_XML, DVENC_XML, NDUP_XML, CODTIPTITPAD, STATUS_MAPA, OBSERVACAO
  FROM &TBL_PPG
 WHERE ID_EXECUCAO='&ID_EXECUCAO'
 ORDER BY NUNOTA, SEQ_PPG;

PROMPT === CONTROLES ===
SELECT COUNT(*) AS TGFNUM_TGFFIN_ROWS,
       MAX(ULTCOD) AS ULTCOD_TGFFIN
  FROM TGFNUM
 WHERE ARQUIVO='TGFFIN';
PROMPT Este mapa nao altera TGFCAB, TGFTOP, TGFPPG, TGFNUM ou TGFFIN.
SPOOL OFF
