-- Card 09 - pos-validacao read-only do insert controlado.

SET DEFINE ON
SET PAGESIZE 1000
SET TRIMSPOOL ON
WHENEVER OSERROR EXIT FAILURE ROLLBACK
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

DEFINE ID_EXECUCAO = 'VDA_ACM_FDUP_20260918_02'
DEFINE TBL_PPG = 'BKP_RMD_VDA_FDUP_20260918_02_PPG'
DEFINE TBL_INS = 'BKP_RMD_VDA_FDUP_20260918_02_INS'

SPOOL "/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Clientes/VITRINI DIRETA (ACM BRASIL)/Logs/Card09_PosValidacao_VDA_20260918_02_FINAL.log"

PROMPT === CARD 09 - POS-VALIDACAO ===
PROMPT ID_EXECUCAO=&ID_EXECUCAO
SELECT COUNT(*) AS MAPA_TOTAL,
       COUNT(DISTINCT NUNOTA) AS MAPA_NOTAS
  FROM &TBL_PPG
 WHERE ID_EXECUCAO='&ID_EXECUCAO';
SELECT STATUS_MAPA, COUNT(*) AS QTD
  FROM &TBL_PPG
 WHERE ID_EXECUCAO='&ID_EXECUCAO'
 GROUP BY STATUS_MAPA
 ORDER BY STATUS_MAPA;
SELECT COUNT(*) AS AUDITORIA_TOTAL,
       MIN(NUFIN) AS NUFIN_MIN,
       MAX(NUFIN) AS NUFIN_MAX
  FROM &TBL_INS
 WHERE ID_EXECUCAO='&ID_EXECUCAO';
SELECT COUNT(*) AS TGFFIN_AUDITADOS
  FROM TGFFIN F
  JOIN &TBL_INS I ON I.NUFIN=F.NUFIN AND I.NUNOTA=F.NUNOTA
 WHERE I.ID_EXECUCAO='&ID_EXECUCAO';
SELECT COUNT(*) AS APTOS_SEM_FINANCEIRO
  FROM &TBL_PPG M
 WHERE M.ID_EXECUCAO='&ID_EXECUCAO'
   AND M.STATUS_MAPA='APTO_PARA_VALIDACAO_FINAL'
   AND NOT EXISTS (SELECT 1 FROM TGFFIN F WHERE F.NUNOTA=M.NUNOTA);
SELECT COUNT(*) AS FINANCEIROS_DUPLICADOS_POR_NUNOTA
  FROM (SELECT F.NUNOTA FROM TGFFIN F JOIN &TBL_INS I ON I.NUNOTA=F.NUNOTA
         WHERE I.ID_EXECUCAO='&ID_EXECUCAO'
         GROUP BY F.NUNOTA HAVING COUNT(*)>1);
SELECT COUNT(*) AS TGFNUM_ROWS, MIN(ULTCOD) AS ULTCOD_TGFFIN
  FROM TGFNUM WHERE ARQUIVO='TGFFIN';
SELECT F.NUFIN,F.NUNOTA,F.VLRDESDOB,F.DTVENC,F.CODTIPTIT,F.CODPARC,F.CODEMP
  FROM TGFFIN F
  JOIN &TBL_INS I ON I.NUFIN=F.NUFIN AND I.NUNOTA=F.NUNOTA
 WHERE I.ID_EXECUCAO='&ID_EXECUCAO'
 ORDER BY F.NUFIN;
PROMPT TGFFIN validada; nenhuma alteracao nesta pos-validacao.
SPOOL OFF
