-- Reversao autocontida da atividade 35 (MEDCHAP_SMTP_20260925_01): recoloca na TSISMTP a linha removida, a partir do backup
-- BKP_RMD_MDCH_SMTP01, somente se o CODSMTP ainda estiver livre. Nao e entrada do lote normal. Nao exibe nenhum valor.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

DECLARE
  v_cols VARCHAR2(4000); v_n NUMBER;
BEGIN
  IF SYS_CONTEXT('USERENV','SESSION_USER') <> 'FRANCISCO_JUNIOR'
     OR SYS_CONTEXT('USERENV','CURRENT_SCHEMA') <> 'SANKHYA'
     OR UPPER(SYS_CONTEXT('USERENV','SERVICE_NAME')) <> 'MEDCHAPPRD.SANKHYACLOUD.COM.BR' THEN
    RAISE_APPLICATION_ERROR(-20497,'Identidade MEDCHAPPRD divergente; reversao da atividade 35 bloqueada.');
  END IF;
  EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM BKP_RMD_MDCH_SMTP01 WHERE ID_EXECUCAO_RMD=:1' INTO v_n USING 'MEDCHAP_SMTP_20260925_01';
  IF v_n <> 1 THEN RAISE_APPLICATION_ERROR(-20498,'Backup ausente ou divergente; reversao bloqueada.'); END IF;
  SELECT COUNT(*) INTO v_n FROM TSISMTP WHERE CODSMTP=1;
  IF v_n <> 0 THEN RAISE_APPLICATION_ERROR(-20499,'CODSMTP=1 ja existe na TSISMTP; reversao bloqueada para analise.'); END IF;
  SELECT LISTAGG(COLUMN_NAME, ',') WITHIN GROUP (ORDER BY COLUMN_ID) INTO v_cols
    FROM ALL_TAB_COLUMNS WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND TABLE_NAME='TSISMTP';
  EXECUTE IMMEDIATE 'INSERT INTO TSISMTP ('||v_cols||') SELECT '||v_cols||' FROM BKP_RMD_MDCH_SMTP01 WHERE ID_EXECUCAO_RMD=:1'
    USING 'MEDCHAP_SMTP_20260925_01';
  IF SQL%ROWCOUNT <> 1 THEN RAISE_APPLICATION_ERROR(-20500,'Reinclusao divergente; nada revertido.'); END IF;
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('STATUS=REVERSAO_ATIVIDADE_35_CONCLUIDA; REINCLUIDOS=1');
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END;
/
