SET DEFINE ON
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
ACCEPT P_ID_EXECUCAO CHAR PROMPT 'ID da execucao RMD_ITEM_: '
DECLARE v_b PLS_INTEGER;v_u PLS_INTEGER;BEGIN
 SELECT COUNT(*) INTO v_b FROM BKP_RMD_08_TGFITE WHERE ID_EXECUCAO='&&P_ID_EXECUCAO';
 IF v_b=0 THEN RAISE_APPLICATION_ERROR(-20221,'Backup nao encontrado.');END IF;
 MERGE INTO TGFITE I USING(SELECT * FROM BKP_RMD_08_TGFITE WHERE ID_EXECUCAO='&&P_ID_EXECUCAO')B
 ON(I.ROWID=CHARTOROWID(B.ROWID_ORIGINAL)) WHEN MATCHED THEN UPDATE SET I.STATUSNOTA=B.STATUSNOTA_ANTES;
 v_u:=SQL%ROWCOUNT;IF v_b<>v_u THEN RAISE_APPLICATION_ERROR(-20222,'Rollback divergente.');END IF;
 COMMIT;DBMS_OUTPUT.PUT_LINE('ITENS_REVERTIDOS='||v_u);
EXCEPTION WHEN OTHERS THEN ROLLBACK;RAISE;END;
/
UNDEFINE P_ID_EXECUCAO
