-- Reversao autocontida da atividade 34 (MEDCHAP_USUEMP_20260925_01): devolve TSIUSU.CODEMP ao valor do backup
-- somente nos registros do backup que ainda estiverem com CODEMP 2. Nao e entrada do lote normal.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

DECLARE
  v_bkp NUMBER; v_upd NUMBER;
BEGIN
  IF SYS_CONTEXT('USERENV','SESSION_USER') <> 'FRANCISCO_JUNIOR'
     OR SYS_CONTEXT('USERENV','CURRENT_SCHEMA') <> 'SANKHYA'
     OR UPPER(SYS_CONTEXT('USERENV','SERVICE_NAME')) <> 'MEDCHAPPRD.SANKHYACLOUD.COM.BR' THEN
    RAISE_APPLICATION_ERROR(-20480,'Identidade MEDCHAPPRD divergente; reversao da atividade 34 bloqueada.');
  END IF;
  EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM BKP_RMD_MDCH_USUEMP01 WHERE ID_EXECUCAO=:1' INTO v_bkp USING 'MEDCHAP_USUEMP_20260925_01';
  IF v_bkp <> 12 THEN
    RAISE_APPLICATION_ERROR(-20481,'Backup ausente ou divergente ('||v_bkp||'); reversao bloqueada.');
  END IF;
  EXECUTE IMMEDIATE 'UPDATE TSIUSU U SET U.CODEMP=(SELECT B.CODEMP FROM BKP_RMD_MDCH_USUEMP01 B WHERE B.ID_EXECUCAO=:1 AND B.RID_ORIGINAL=ROWIDTOCHAR(U.ROWID)) '||
                    'WHERE U.CODEMP=2 AND ROWIDTOCHAR(U.ROWID) IN (SELECT B.RID_ORIGINAL FROM BKP_RMD_MDCH_USUEMP01 B WHERE B.ID_EXECUCAO=:2)'
    USING 'MEDCHAP_USUEMP_20260925_01','MEDCHAP_USUEMP_20260925_01';
  v_upd := SQL%ROWCOUNT;
  IF v_upd <> v_bkp THEN
    RAISE_APPLICATION_ERROR(-20482,'Reversao afetaria '||v_upd||' de '||v_bkp||' registros (algum foi alterado depois); nada revertido.');
  END IF;
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('STATUS=REVERSAO_ATIVIDADE_34_CONCLUIDA; REVERTIDOS='||v_upd);
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END;
/
