SET DEFINE OFF
SET ECHO ON
SET SERVEROUTPUT ON SIZE UNLIMITED
SET LINESIZE 240
SET PAGESIZE 200
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
SPOOL "/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Clientes/IMPORTUDO COMERCIO/Logs/00_Identidade_Precheck.log"
SELECT SYS_CONTEXT('USERENV','SESSION_USER') USUARIO, SYS_CONTEXT('USERENV','SERVICE_NAME') SERVICO FROM DUAL;
BEGIN
 IF UPPER(SYS_CONTEXT('USERENV','SERVICE_NAME')) <> 'IMPORTUDOPRD.SANKHYACLOUD.COM.BR' OR UPPER(SYS_CONTEXT('USERENV','SESSION_USER')) <> 'FRANCISCO_JUNIOR' THEN
 RAISE_APPLICATION_ERROR(-20501,'Conexao divergente'); END IF;
END;
/
ALTER SESSION SET CURRENT_SCHEMA=SANKHYA;
SELECT SYS_CONTEXT('USERENV','CURRENT_SCHEMA') SCHEMA_ATUAL FROM DUAL;
SELECT CODEMP, RAZAOSOCIAL FROM SANKHYA.TSIEMP WHERE CODEMP=1;
SELECT PRIVILEGE FROM SESSION_PRIVS ORDER BY PRIVILEGE;
@@"/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Clientes/IMPORTUDO COMERCIO/00_Precheck_Unidades.sql"
PROMPT IDENTIDADE_PRECHECK_CONCLUIDO
SPOOL OFF
