SPOOL OFF
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET SQLBLANKLINES ON
SET ECHO ON
WHENEVER OSERROR EXIT FAILURE ROLLBACK
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
SPOOL "/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Clientes/IMPORTUDO COMERCIO/Logs/Preflight_Backup13_T05.log"
PROMPT CONTINUIDADE IMPORTUDO COMERCIO - ETAPAS 13 A 31
SELECT SYS_CONTEXT('USERENV','SESSION_USER') USUARIO, SYS_CONTEXT('USERENV','CURRENT_SCHEMA') SCHEMA_ATUAL, SYS_CONTEXT('USERENV','SERVICE_NAME') SERVICO FROM DUAL;
ALTER SESSION SET CURRENT_SCHEMA=SANKHYA;
BEGIN
 IF UPPER(SYS_CONTEXT('USERENV','SERVICE_NAME')) <> 'IMPORTUDOPRD.SANKHYACLOUD.COM.BR' OR SYS_CONTEXT('USERENV','SESSION_USER') <> 'FRANCISCO_JUNIOR' THEN
 RAISE_APPLICATION_ERROR(-20501,'Conexao divergente'); END IF;
END;
/
PROMPT PREFLIGHT BACKUP 13 SEM ALTERAR REGISTROS
SELECT TABLE_SCHEMA,TABLE_NAME,GRANTEE,PRIVILEGE FROM ALL_TAB_PRIVS WHERE TABLE_NAME='BKP_RMD_12_TGFTOP';
DECLARE
 n NUMBER;
BEGIN
 SELECT COUNT(*) INTO n FROM SANKHYA.BKP_RMD_12_TGFTOP;
 DBMS_OUTPUT.PUT_LINE('BACKUP13_LINHAS='||n);
 EXECUTE IMMEDIATE 'INSERT INTO SANKHYA.BKP_RMD_12_TGFTOP SELECT * FROM SANKHYA.BKP_RMD_12_TGFTOP WHERE 1=0';
 DBMS_OUTPUT.PUT_LINE('BACKUP13_INSERT_ZERO_OK='||SQL%ROWCOUNT);
 ROLLBACK;
END;
/
PROMPT PREFLIGHT13_FIM
SPOOL OFF
