SPOOL OFF
SET DEFINE OFF
SET ECHO ON
SET SERVEROUTPUT ON SIZE UNLIMITED
SET LINESIZE 240
SET PAGESIZE 200
WHENEVER SQLERROR CONTINUE
SPOOL "/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Clientes/IMPORTUDO COMERCIO/Logs/01_Diagnostico_Privilegios.log"
SELECT SYS_CONTEXT('USERENV','SESSION_USER') USUARIO,SYS_CONTEXT('USERENV','CURRENT_SCHEMA') SCHEMA_ATUAL,SYS_CONTEXT('USERENV','SERVICE_NAME') SERVICO FROM DUAL;
SELECT TABLE_NAME, GRANTEE, PRIVILEGE FROM ALL_TAB_PRIVS WHERE TABLE_SCHEMA='SANKHYA' AND (TABLE_NAME LIKE 'BKP_RMD_%' OR TABLE_NAME LIKE 'RMD_%') ORDER BY TABLE_NAME,GRANTEE,PRIVILEGE;
SELECT ROLE FROM SESSION_ROLES ORDER BY ROLE;
SELECT OWNER,OBJECT_NAME,OBJECT_TYPE,STATUS FROM ALL_OBJECTS WHERE OWNER='SANKHYA' AND (OBJECT_NAME LIKE 'BKP_RMD_%' OR OBJECT_NAME LIKE 'RMD_%') ORDER BY OBJECT_NAME;
SELECT * FROM SANKHYA.RMD_CONTROLE_OBJETOS;
PROMPT DIAGNOSTICO_PRIVILEGIOS_FIM
SPOOL OFF
