SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET ECHO ON
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
ALTER SESSION SET CURRENT_SCHEMA=SANKHYA;
SPOOL "/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Clientes/IMPORTUDO COMERCIO/Logs/Card09_TOP_Restauracao_06.log"
PROMPT CARD09_RESTAURACAO_TOP
UPDATE TGFTOP T SET ATIVO=(SELECT B.ATIVO FROM SANKHYA.BKP_RMD_TOP_IMPORTUDO_06 B WHERE B.CODTIPOPER=T.CODTIPOPER AND B.DHALTER=T.DHALTER)
 WHERE EXISTS (SELECT 1 FROM SANKHYA.BKP_RMD_TOP_IMPORTUDO_06 B WHERE B.CODTIPOPER=T.CODTIPOPER AND B.DHALTER=T.DHALTER);
DBMS_OUTPUT.PUT_LINE('TOPS_RESTAURADAS='||SQL%ROWCOUNT);
COMMIT;
SELECT CODTIPOPER,DHALTER,ATIVO,ATUALFIN FROM TGFTOP WHERE CODTIPOPER IN (1164,1166) AND DHALTER=(SELECT MAX(T2.DHALTER) FROM TGFTOP T2 WHERE T2.CODTIPOPER=TGFTOP.CODTIPOPER);
PROMPT CARD09_RESTAURACAO_TOP_FIM
SPOOL OFF
