SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET ECHO ON
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
ALTER SESSION SET CURRENT_SCHEMA=SANKHYA;
SPOOL "/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Clientes/IMPORTUDO COMERCIO/Logs/Card09_TOP_Ativacao_Temporaria_06.log"
PROMPT CARD09_ATIVACAO_TEMPORARIA_TOP
DECLARE
  v_qtd NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_qtd FROM ALL_TABLES WHERE OWNER='SANKHYA' AND TABLE_NAME='BKP_RMD_TOP_IMPORTUDO_06';
  IF v_qtd=0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE SANKHYA.BKP_RMD_TOP_IMPORTUDO_06 (CODTIPOPER NUMBER,DHALTER DATE,ATIVO VARCHAR2(1),ATUALFIN NUMBER, DH_BACKUP TIMESTAMP)';
  END IF;
  INSERT INTO SANKHYA.BKP_RMD_TOP_IMPORTUDO_06(CODTIPOPER,DHALTER,ATIVO,ATUALFIN,DH_BACKUP)
  SELECT T.CODTIPOPER,T.DHALTER,T.ATIVO,T.ATUALFIN,SYSTIMESTAMP
    FROM TGFTOP T
   WHERE T.CODTIPOPER IN (1164,1166)
     AND T.DHALTER=(SELECT MAX(T2.DHALTER) FROM TGFTOP T2 WHERE T2.CODTIPOPER=T.CODTIPOPER)
     AND T.ATIVO<>'S'
     AND NOT EXISTS (SELECT 1 FROM SANKHYA.BKP_RMD_TOP_IMPORTUDO_06 B WHERE B.CODTIPOPER=T.CODTIPOPER AND B.DHALTER=T.DHALTER);
  UPDATE TGFTOP T SET ATIVO='S'
   WHERE T.CODTIPOPER IN (1164,1166)
     AND T.DHALTER=(SELECT MAX(T2.DHALTER) FROM TGFTOP T2 WHERE T2.CODTIPOPER=T.CODTIPOPER);
  DBMS_OUTPUT.PUT_LINE('TOPS_ATIVADAS_TEMPORARIAMENTE='||SQL%ROWCOUNT);
  COMMIT;
END;
/
SELECT CODTIPOPER,DHALTER,ATIVO,ATUALFIN FROM TGFTOP WHERE CODTIPOPER IN (1164,1166) AND DHALTER=(SELECT MAX(T2.DHALTER) FROM TGFTOP T2 WHERE T2.CODTIPOPER=TGFTOP.CODTIPOPER);
PROMPT CARD09_ATIVACAO_TEMPORARIA_FIM
SPOOL OFF
