SPOOL OFF
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET SQLBLANKLINES ON
SET ECHO ON
WHENEVER OSERROR EXIT FAILURE ROLLBACK
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
SPOOL "/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Clientes/IMPORTUDO COMERCIO/Logs/Prechecks_16_31_T08.log"
PROMPT CONTINUIDADE IMPORTUDO COMERCIO - ETAPAS 13 A 31
SELECT SYS_CONTEXT('USERENV','SESSION_USER') USUARIO, SYS_CONTEXT('USERENV','CURRENT_SCHEMA') SCHEMA_ATUAL, SYS_CONTEXT('USERENV','SERVICE_NAME') SERVICO FROM DUAL;
ALTER SESSION SET CURRENT_SCHEMA=SANKHYA;
BEGIN
 IF UPPER(SYS_CONTEXT('USERENV','SERVICE_NAME')) <> 'IMPORTUDOPRD.SANKHYACLOUD.COM.BR' OR SYS_CONTEXT('USERENV','SESSION_USER') <> 'FRANCISCO_JUNIOR' THEN
 RAISE_APPLICATION_ERROR(-20501,'Conexao divergente'); END IF;
END;
/
DECLARE n NUMBER; BEGIN
 SELECT COUNT(*) INTO n FROM ALL_TABLES WHERE OWNER='SANKHYA' AND TABLE_NAME='RMD_REF_TSICFG_MODELO';
 IF n=0 THEN EXECUTE IMMEDIATE 'CREATE TABLE SANKHYA.RMD_REF_TSICFG_MODELO AS SELECT * FROM SANKHYA.TSICFG WHERE 1=0'; END IF;
END;
/
@@"/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Clientes/IMPORTUDO COMERCIO/00_Precheck_Etapas_18_31.sql"
SPOOL OFF
