SPOOL OFF
SET DEFINE ON
SET SERVEROUTPUT ON SIZE UNLIMITED
SET SQLBLANKLINES ON
SET ECHO ON
WHENEVER OSERROR EXIT FAILURE ROLLBACK
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
SPOOL "/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Clientes/IMPORTUDO COMERCIO/Logs/Card09_Compilacao_Funcao_T14.log"
PROMPT CARD 09 - COMPILACAO AUTORIZADA DA FUNCAO DE LEITURA XML
SELECT SYS_CONTEXT('USERENV','SESSION_USER') USUARIO, SYS_CONTEXT('USERENV','CURRENT_SCHEMA') SCHEMA_ATUAL, SYS_CONTEXT('USERENV','SERVICE_NAME') SERVICO FROM DUAL;
ALTER SESSION SET CURRENT_SCHEMA=SANKHYA;
BEGIN
 IF UPPER(SYS_CONTEXT('USERENV','SERVICE_NAME')) <> 'IMPORTUDOPRD.SANKHYACLOUD.COM.BR' OR SYS_CONTEXT('USERENV','SESSION_USER') <> 'FRANCISCO_JUNIOR' THEN
 RAISE_APPLICATION_ERROR(-20501,'Conexao divergente'); END IF;
END;
/
VARIABLE RMD_ID_MASTER VARCHAR2(30)
BEGIN :RMD_ID_MASTER:='RMD_RUN_CONT_'||TO_CHAR(SYSTIMESTAMP,'YYYYMMDDHH24MISSFF3'); END;
/
CREATE OR REPLACE FUNCTION FNC_BUSCA_TAG_XML_GERAL (
  p_nunota IN NUMBER,
  p_tag IN VARCHAR2,
  p_parent_tag IN VARCHAR2 DEFAULT NULL
) RETURN VARCHAR2
IS
  v_val VARCHAR2(4000);
BEGIN
  SELECT valor INTO v_val FROM (
    SELECT xt.valor
      FROM TGFNFE n,
           XMLTABLE(
             '//*[ upper-case(local-name()) = upper-case($tag)
                  and ( string-length($parent) = 0
                        or upper-case(local-name(parent::*)) = upper-case($parent) )
                ][1]'
             PASSING XMLTYPE(n.XML), p_tag AS "tag", NVL(p_parent_tag,'') AS "parent"
             COLUMNS valor VARCHAR2(4000) PATH 'string(.)'
           ) xt
     WHERE n.nunota = p_nunota
  ) WHERE ROWNUM = 1;
  RETURN v_val;
EXCEPTION WHEN NO_DATA_FOUND THEN RETURN NULL;
END;
/
SELECT OWNER,OBJECT_NAME,OBJECT_TYPE,STATUS FROM ALL_OBJECTS WHERE OBJECT_NAME='FNC_BUSCA_TAG_XML_GERAL';
SELECT OWNER,OBJECT_NAME,ARGUMENT_NAME,POSITION,DATA_TYPE FROM ALL_ARGUMENTS WHERE OBJECT_NAME='FNC_BUSCA_TAG_XML_GERAL' ORDER BY OWNER,POSITION;
PROMPT CARD09_FUNCAO_COMPILADA_AUTORIZADA
SPOOL OFF

SPOOL "/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Clientes/IMPORTUDO COMERCIO/Logs/Card09_Preflight_Mapa_T15.log"
PROMPT CARD09_PREFLIGHT_MAPA_POS_COMPILACAO
DEFINE ID_EXECUCAO = 'IMPORTUDO_20260910_FDUP_02'
DEFINE TBL_BASE = 'BKP_RMD_FDUP_IMPORTUDO_02'
@"/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Clientes/IMPORTUDO COMERCIO/Artefatos_Revisao/Scripts/32_Card09_Preflight_Notas_Sem_Financeiro_DUP.sql"
PROMPT CARD09_PREFLIGHT_MAPA_FIM
SPOOL OFF
