SET DEFINE OFF
SET PAGESIZE 500
SET LINESIZE 240
SET LONG 100000
SET TRIMSPOOL ON
SET SERVEROUTPUT ON SIZE UNLIMITED
SET ECHO ON
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
ALTER SESSION SET CURRENT_SCHEMA=SANKHYA;
SPOOL "/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Clientes/IMPORTUDO COMERCIO/Logs/Diagnostico_Colisoes_29_30.log"
PROMPT IMPORTUDO COMERCIO - DIAGNOSTICO E MAPA DE COLISOES 29/30
WITH b AS (SELECT CODBAI,NOMEBAI,REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEBAI),'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇáàâãäéèêëíìîïóòôõöúùûüçÃãÕõÂâÊêÎîÔôÛû','AAAAAEEEEIIIIOOOOOUUUUCAAAAAEEEEIIIIOOOOOUUUUCAAAOOAAEIIOOUU')),' {2,}',' ') NORM FROM TSIBAI) SELECT NORM,COUNT(*) QTD,MIN(CODBAI) COD_MANTIDO,LISTAGG(CODBAI||'='||NOMEBAI,' | ') WITHIN GROUP(ORDER BY CODBAI) REGISTROS FROM b GROUP BY NORM HAVING COUNT(*)>1 ORDER BY NORM;
WITH e AS (SELECT CODEND,TIPO,NOMEEND,REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEEND),'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇáàâãäéèêëíìîïóòõöúùûüçÃãÕõÂâÊêÎîÔôÛû','AAAAAEEEEIIIIOOOOOUUUUCAAAAAEEEEIIIIOOOOOUUUUCAAAOOAAEIIOOUU')),' {2,}',' ') NORM FROM TSIEND) SELECT TIPO,NORM,COUNT(*) QTD,MIN(CODEND) COD_MANTIDO,LISTAGG(CODEND||'='||NOMEEND,' | ') WITHIN GROUP(ORDER BY CODEND) REGISTROS FROM e GROUP BY TIPO,NORM HAVING COUNT(*)>1 ORDER BY TIPO,NORM;
SELECT c.TABLE_NAME,cc.COLUMN_NAME,p.TABLE_NAME PARENT_TABLE,pc.COLUMN_NAME PARENT_COLUMN,c.CONSTRAINT_NAME FROM ALL_CONSTRAINTS c JOIN ALL_CONS_COLUMNS cc ON cc.OWNER=c.OWNER AND cc.CONSTRAINT_NAME=c.CONSTRAINT_NAME JOIN ALL_CONSTRAINTS p ON p.OWNER=c.R_OWNER AND p.CONSTRAINT_NAME=c.R_CONSTRAINT_NAME JOIN ALL_CONS_COLUMNS pc ON pc.OWNER=p.OWNER AND pc.CONSTRAINT_NAME=p.CONSTRAINT_NAME AND pc.POSITION=cc.POSITION WHERE c.OWNER='SANKHYA' AND c.CONSTRAINT_TYPE='R' AND p.TABLE_NAME IN ('TSIBAI','TSIEND') ORDER BY p.TABLE_NAME,c.TABLE_NAME,cc.POSITION;
SELECT TABLE_NAME,COLUMN_NAME FROM ALL_TAB_COLUMNS WHERE OWNER='SANKHYA' AND COLUMN_NAME IN ('CODBAI','CODEND','CODBAIENTREGA','CODENDENTREGA') ORDER BY TABLE_NAME,COLUMN_NAME;
PROMPT FIM_DIAGNOSTICO_COLISOES_29_30
SPOOL OFF
