SPOOL OFF
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET SQLBLANKLINES ON
SET ECHO ON
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
SPOOL "/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Clientes/IMPORTUDO COMERCIO/Logs/Preparar_Backups_T04.log"
BEGIN
 IF UPPER(SYS_CONTEXT('USERENV','SERVICE_NAME')) <> 'IMPORTUDOPRD.SANKHYACLOUD.COM.BR' OR SYS_CONTEXT('USERENV','SESSION_USER') <> 'FRANCISCO_JUNIOR' THEN RAISE_APPLICATION_ERROR(-20501,'Conexao divergente'); END IF;
END;
/
ALTER SESSION SET CURRENT_SCHEMA=SANKHYA;

PROMPT PREPARAR BACKUP 14_Configurar_Analise_Giro_848.sql
DECLARE v NUMBER;BEGIN
 SELECT COUNT(*) INTO v FROM ALL_TABLES WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND TABLE_NAME='BKP_RMD_13_TSIIMP';
 IF v=0 THEN EXECUTE IMMEDIATE q'[CREATE TABLE BKP_RMD_13_TSIIMP AS SELECT CAST(NULL AS VARCHAR2(30)) ID_EXECUCAO,
 CAST(NULL AS TIMESTAMP) DH_EXECUCAO,CAST(NULL AS VARCHAR2(128)) USUARIO_EXECUCAO,
 I.CODREL,I.LISTA1 LISTA1_ANTES FROM TSIIMP I WHERE 1=0]';END IF;
 SELECT COUNT(*) INTO v FROM TSIIMP WHERE CODREL=848;
 IF v<>1 THEN RAISE_APPLICATION_ERROR(-20340,'Esperada exatamente uma configuracao TSIIMP CODREL=848.');END IF;
END;
/

PROMPT PREPARAR BACKUP 15_Desativar_Rastro_Sem_Controle.sql
DECLARE v NUMBER; BEGIN
 SELECT COUNT(*) INTO v FROM ALL_TABLES WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND TABLE_NAME='BKP_RMD_14_TGFPRO';
 IF v=0 THEN EXECUTE IMMEDIATE q'[CREATE TABLE BKP_RMD_14_TGFPRO AS
 SELECT CAST(NULL AS VARCHAR2(30)) ID_EXECUCAO, CAST(NULL AS TIMESTAMP) DH_EXECUCAO,
 CAST(NULL AS VARCHAR2(128)) USUARIO_EXECUCAO, CAST(NULL AS VARCHAR2(30)) ROWID_ORIGINAL,
 T.TEMRASTROLOTE VALOR_ANTES, CAST('N' AS VARCHAR2(1)) VALOR_DEPOIS FROM TGFPRO T WHERE 1=0]'; END IF;
END;
/

PROMPT PREPARAR BACKUP 16_Aplicar_Higienizacao_TSICFG.sql
DECLARE
  v_existe NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_existe
    FROM ALL_TABLES
   WHERE OWNER = SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
     AND TABLE_NAME = 'BKP_RMD_TSICFG';
  IF v_existe = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE BKP_RMD_TSICFG AS
      SELECT CAST(NULL AS VARCHAR2(30)) ID_EXECUCAO,
             CAST(NULL AS TIMESTAMP) DH_EXECUCAO,
             CAST(NULL AS VARCHAR2(128)) USUARIO_EXECUCAO,
             T.*
        FROM TSICFG T
       WHERE 1=0
    ]';
  END IF;
END;
/

@@"/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Revisao Master Deploy/18_Preparar_Backups_18_30.sql"
PROMPT PREPARACAO_T04_FIM
SPOOL OFF
