SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET SQLBLANKLINES ON
SET ECHO ON
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
ALTER SESSION SET CURRENT_SCHEMA=SANKHYA;
SPOOL "/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Clientes/IMPORTUDO COMERCIO/Logs/Merge_Colisoes_29_30_06.log"
PROMPT IMPORTUDO COMERCIO - MERGE CONTROLADO COLISOES ETAPAS 29/30
@"/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Clientes/IMPORTUDO COMERCIO/Merge_Bairros_Enderecos_IMPORTUDO_06.sql"
PROMPT FIM_MERGE_COLISOES_29_30_06
SPOOL OFF
