SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET SQLBLANKLINES ON
SET ECHO ON
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
ALTER SESSION SET CURRENT_SCHEMA=FRANCISCO_JUNIOR;
PROMPT MODELO_ANTIFRAGIL_MERGE_29_30_IMPORTUDO
DECLARE
  v_n NUMBER;
  PROCEDURE ensure_table(p_name VARCHAR2,p_sql VARCHAR2) IS BEGIN SELECT COUNT(*) INTO v_n FROM ALL_TABLES WHERE OWNER='FRANCISCO_JUNIOR' AND TABLE_NAME=p_name; IF v_n=0 THEN EXECUTE IMMEDIATE p_sql; END IF; END;
BEGIN
 ensure_table('BKP_RMD_MERGE_BAI_07','CREATE TABLE FRANCISCO_JUNIOR.BKP_RMD_MERGE_BAI_07 (ID_EXECUCAO VARCHAR2(40),COD_OBSOLETO NUMBER,COD_MANTIDO NUMBER)');
 ensure_table('BKP_RMD_MERGE_END_07','CREATE TABLE FRANCISCO_JUNIOR.BKP_RMD_MERGE_END_07 (ID_EXECUCAO VARCHAR2(40),COD_OBSOLETO NUMBER,COD_MANTIDO NUMBER)');
 ensure_table('BKP_RMD_MERGE_REF_07','CREATE TABLE FRANCISCO_JUNIOR.BKP_RMD_MERGE_REF_07 (ID_EXECUCAO VARCHAR2(40),TABLE_NAME VARCHAR2(128),COLUMN_NAME VARCHAR2(128),ROWID_ORIGINAL VARCHAR2(30),VALOR_ANTES NUMBER,VALOR_DEPOIS NUMBER)');
 ensure_table('BKP_RMD_MERGE_BAI_07_ROWS_07','CREATE TABLE FRANCISCO_JUNIOR.BKP_RMD_MERGE_BAI_07_ROWS_07 AS SELECT * FROM SANKHYA.TSIBAI WHERE 1=0');
 ensure_table('BKP_RMD_MERGE_END_07_ROWS_07','CREATE TABLE FRANCISCO_JUNIOR.BKP_RMD_MERGE_END_07_ROWS_07 AS SELECT * FROM SANKHYA.TSIEND WHERE 1=0');
END;
/
ALTER SESSION SET CURRENT_SCHEMA=SANKHYA;
DECLARE v_id CONSTANT VARCHAR2(40):='IMPORTUDO_20260911_MERGE_07'; v_b NUMBER;v_e NUMBER;v_ref NUMBER;v_sql VARCHAR2(32767);v_rest NUMBER;v_dup NUMBER;v_used NUMBER;
BEGIN
 SELECT COUNT(*) INTO v_used FROM FRANCISCO_JUNIOR.BKP_RMD_MERGE_REF_07 WHERE ID_EXECUCAO=v_id;
 IF v_used<>0 THEN RAISE_APPLICATION_ERROR(-20550,'ID_EXECUCAO ja utilizado.'); END IF;
 INSERT INTO FRANCISCO_JUNIOR.BKP_RMD_MERGE_BAI_07
 SELECT v_id,CODBAI,KEEP_ID FROM (SELECT CODBAI,MIN(CODBAI) OVER(PARTITION BY NORM) KEEP_ID,COUNT(*) OVER(PARTITION BY NORM) QTD FROM (SELECT CODBAI,REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEBAI),'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇáàâãäéèëíìîïóòôõöúùû','AAAAAEEEEIIIIOOOOOUUUUCAAAAAEEEEIIIIOOOOOUUUUCAAAOOAAEIIOOUU')),' {2,}',' ') NORM FROM TSIBAI)) WHERE QTD>1 AND CODBAI<>KEEP_ID;
 INSERT INTO FRANCISCO_JUNIOR.BKP_RMD_MERGE_END_07
 SELECT v_id,CODEND,KEEP_ID FROM (SELECT CODEND,MIN(CODEND) OVER(PARTITION BY TIPO,NORM) KEEP_ID,COUNT(*) OVER(PARTITION BY TIPO,NORM) QTD FROM (SELECT CODEND,TIPO,REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEEND),'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇáàâãäéèëíìîïóòôõöúùû','AAAAAEEEEIIIIOOOOOUUUUCAAAAAEEEEIIIIOOOOOUUUUCAAAOOAAEIIOOUU')),' {2,}',' ') NORM FROM TSIEND)) WHERE QTD>1 AND CODEND<>KEEP_ID;
 INSERT INTO FRANCISCO_JUNIOR.BKP_RMD_MERGE_BAI_07_ROWS_07 SELECT b.* FROM TSIBAI b WHERE b.CODBAI IN (SELECT COD_OBSOLETO FROM FRANCISCO_JUNIOR.BKP_RMD_MERGE_BAI_07 WHERE ID_EXECUCAO=v_id) OR b.CODBAI IN (SELECT COD_MANTIDO FROM FRANCISCO_JUNIOR.BKP_RMD_MERGE_BAI_07 WHERE ID_EXECUCAO=v_id);
 INSERT INTO FRANCISCO_JUNIOR.BKP_RMD_MERGE_END_07_ROWS_07 SELECT e.* FROM TSIEND e WHERE e.CODEND IN (SELECT COD_OBSOLETO FROM FRANCISCO_JUNIOR.BKP_RMD_MERGE_END_07 WHERE ID_EXECUCAO=v_id) OR e.CODEND IN (SELECT COD_MANTIDO FROM FRANCISCO_JUNIOR.BKP_RMD_MERGE_END_07 WHERE ID_EXECUCAO=v_id);
 SELECT COUNT(*) INTO v_b FROM FRANCISCO_JUNIOR.BKP_RMD_MERGE_BAI_07 WHERE ID_EXECUCAO=v_id; SELECT COUNT(*) INTO v_e FROM FRANCISCO_JUNIOR.BKP_RMD_MERGE_END_07 WHERE ID_EXECUCAO=v_id; DBMS_OUTPUT.PUT_LINE('MAPA_BAI='||v_b||' MAPA_END='||v_e);
 IF v_b=0 AND v_e=0 THEN DBMS_OUTPUT.PUT_LINE('SEM_COLISOES'); RETURN; END IF;
 INSERT INTO FRANCISCO_JUNIOR.BKP_RMD_MERGE_REF_07(ID_EXECUCAO,TABLE_NAME,COLUMN_NAME,ROWID_ORIGINAL,VALOR_ANTES,VALOR_DEPOIS)
 SELECT v_id,'TSIBAI','CODBAI',ROWIDTOCHAR(b.ROWID),b.CODBAI,m.COD_MANTIDO FROM TSIBAI b JOIN FRANCISCO_JUNIOR.BKP_RMD_MERGE_BAI_07 m ON m.ID_EXECUCAO=v_id AND m.COD_OBSOLETO=b.CODBAI;
 INSERT INTO FRANCISCO_JUNIOR.BKP_RMD_MERGE_REF_07 SELECT v_id,'TSIEND','CODEND',ROWIDTOCHAR(e.ROWID),e.CODEND,m.COD_MANTIDO FROM TSIEND e JOIN FRANCISCO_JUNIOR.BKP_RMD_MERGE_END_07 m ON m.ID_EXECUCAO=v_id AND m.COD_OBSOLETO=e.CODEND;
 FOR c IN (SELECT c.TABLE_NAME,c.COLUMN_NAME FROM ALL_TAB_COLUMNS c JOIN ALL_TABLES t ON t.OWNER=c.OWNER AND t.TABLE_NAME=c.TABLE_NAME WHERE c.OWNER='SANKHYA' AND c.COLUMN_NAME IN ('CODBAI','CODEND','CODBAIENTREGA','CODENDENTREGA') AND c.TABLE_NAME NOT IN ('TSIBAI','TSIEND')) LOOP
   IF c.COLUMN_NAME IN ('CODBAI','CODBAIENTREGA') THEN
     v_sql:='INSERT INTO FRANCISCO_JUNIOR.BKP_RMD_MERGE_REF_07 SELECT '''||v_id||''','''||c.TABLE_NAME||''','''||c.COLUMN_NAME||''',ROWIDTOCHAR(t.ROWID),t.'||c.COLUMN_NAME||',m.COD_MANTIDO FROM SANKHYA.'||c.TABLE_NAME||' t JOIN FRANCISCO_JUNIOR.BKP_RMD_MERGE_BAI_07 m ON m.ID_EXECUCAO='''||v_id||''' AND m.COD_OBSOLETO=t.'||c.COLUMN_NAME; EXECUTE IMMEDIATE v_sql;
     v_sql:='UPDATE SANKHYA.'||c.TABLE_NAME||' t SET '||c.COLUMN_NAME||'=(SELECT m.COD_MANTIDO FROM FRANCISCO_JUNIOR.BKP_RMD_MERGE_BAI_07 m WHERE m.ID_EXECUCAO='''||v_id||''' AND m.COD_OBSOLETO=t.'||c.COLUMN_NAME||') WHERE EXISTS (SELECT 1 FROM FRANCISCO_JUNIOR.BKP_RMD_MERGE_BAI_07 m WHERE m.ID_EXECUCAO='''||v_id||''' AND m.COD_OBSOLETO=t.'||c.COLUMN_NAME||')'; EXECUTE IMMEDIATE v_sql;
   ELSE
     v_sql:='INSERT INTO FRANCISCO_JUNIOR.BKP_RMD_MERGE_REF_07 SELECT '''||v_id||''','''||c.TABLE_NAME||''','''||c.COLUMN_NAME||''',ROWIDTOCHAR(t.ROWID),t.'||c.COLUMN_NAME||',m.COD_MANTIDO FROM SANKHYA.'||c.TABLE_NAME||' t JOIN FRANCISCO_JUNIOR.BKP_RMD_MERGE_END_07 m ON m.ID_EXECUCAO='''||v_id||''' AND m.COD_OBSOLETO=t.'||c.COLUMN_NAME; EXECUTE IMMEDIATE v_sql;
     v_sql:='UPDATE SANKHYA.'||c.TABLE_NAME||' t SET '||c.COLUMN_NAME||'=(SELECT m.COD_MANTIDO FROM FRANCISCO_JUNIOR.BKP_RMD_MERGE_END_07 m WHERE m.ID_EXECUCAO='''||v_id||''' AND m.COD_OBSOLETO=t.'||c.COLUMN_NAME||') WHERE EXISTS (SELECT 1 FROM FRANCISCO_JUNIOR.BKP_RMD_MERGE_END_07 m WHERE m.ID_EXECUCAO='''||v_id||''' AND m.COD_OBSOLETO=t.'||c.COLUMN_NAME||')'; EXECUTE IMMEDIATE v_sql;
   END IF;
 END LOOP;
 SELECT COUNT(*) INTO v_rest FROM FRANCISCO_JUNIOR.BKP_RMD_MERGE_REF_07 WHERE ID_EXECUCAO=v_id; DBMS_OUTPUT.PUT_LINE('REFERENCIAS_RESPALDADAS_E_REDIRECIONADAS='||v_rest);
 DELETE FROM TSIBAI WHERE CODBAI IN (SELECT COD_OBSOLETO FROM FRANCISCO_JUNIOR.BKP_RMD_MERGE_BAI_07 WHERE ID_EXECUCAO=v_id);
 DELETE FROM TSIEND WHERE CODEND IN (SELECT COD_OBSOLETO FROM FRANCISCO_JUNIOR.BKP_RMD_MERGE_END_07 WHERE ID_EXECUCAO=v_id);
 SELECT COUNT(*) INTO v_dup FROM (SELECT 1 FROM TSIBAI GROUP BY REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEBAI),'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ','AAAAAEEEEIIIIOOOOOUUUUCA')),' {2,}',' ') HAVING COUNT(*)>1);
 IF v_dup>0 THEN RAISE_APPLICATION_ERROR(-20551,'Duplicidades de bairros restantes='||v_dup); END IF;
 SELECT COUNT(*) INTO v_dup FROM (SELECT 1 FROM TSIEND GROUP BY TIPO,REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEEND),'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ','AAAAAEEEEIIIIOOOOOUUUUCA')),' {2,}',' ') HAVING COUNT(*)>1);
 IF v_dup>0 THEN RAISE_APPLICATION_ERROR(-20552,'Duplicidades de enderecos restantes='||v_dup); END IF;
 COMMIT; DBMS_OUTPUT.PUT_LINE('STATUS=MERGE_COLISOES_CONCLUIDO; ID_EXECUCAO='||v_id||'; BAI='||v_b||'; END='||v_e);
EXCEPTION WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('ERRO_MERGE_REVERTIDO='||SQLERRM); RAISE;
END;
/
