SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET SQLBLANKLINES ON
SET ECHO ON
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
ALTER SESSION SET CURRENT_SCHEMA=SANKHYA;
SPOOL "/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Clientes/IMPORTUDO COMERCIO/Logs/Regularizar_TGFCGM_Empresas.log"
PROMPT ETAPA18_TGFCGM_UMA_LINHA_POR_EMPRESA_IMPORTUDO
DECLARE
  v_id CONSTANT VARCHAR2(40):='RMD_TGFCGM_IMPORTUDO_20260911_01';
  v_src NUMBER; v_emp NUMBER; v_missing NUMBER; v_ins NUMBER; v_cols VARCHAR2(32767); v_sel VARCHAR2(32767); v_sql VARCHAR2(32767); v_n NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_src FROM TGFCGM WHERE CODEMP=1 AND ANO=1900 AND MES=1;
  IF v_src<>1 THEN RAISE_APPLICATION_ERROR(-20310,'TGFCGM origem CODEMP=1/ANO=1900/MES=1 deve ter exatamente 1 linha.'); END IF;
  SELECT COUNT(*) INTO v_emp FROM TSIEMP;
  SELECT COUNT(*) INTO v_missing FROM TSIEMP e WHERE NOT EXISTS (SELECT 1 FROM TGFCGM g WHERE g.CODEMP=e.CODEMP AND g.ANO=1900 AND g.MES=1);
  DBMS_OUTPUT.PUT_LINE('EMPRESAS='||v_emp||'; AUSENTES='||v_missing);
  SELECT LISTAGG('"'||COLUMN_NAME||'"',',') WITHIN GROUP (ORDER BY COLUMN_ID), LISTAGG('s."'||COLUMN_NAME||'"',',') WITHIN GROUP (ORDER BY COLUMN_ID) INTO v_cols,v_sel
    FROM ALL_TAB_COLUMNS WHERE OWNER='SANKHYA' AND TABLE_NAME='TGFCGM' AND COLUMN_NAME<>'CODEMP';
  IF v_cols IS NULL THEN RAISE_APPLICATION_ERROR(-20311,'Nao foi possivel obter colunas de TGFCGM.'); END IF;
  BEGIN
    SELECT COUNT(*) INTO v_n FROM ALL_TABLES WHERE OWNER='SANKHYA' AND TABLE_NAME='BKP_RMD_TGFCGM_INS';
    IF v_n=0 THEN EXECUTE IMMEDIATE 'CREATE TABLE SANKHYA.BKP_RMD_TGFCGM_INS (ID_EXECUCAO VARCHAR2(40),ROWID_ORIGINAL VARCHAR2(30),CODEMP NUMBER,ANO NUMBER,MES NUMBER)'; END IF;
  END;
  DELETE FROM SANKHYA.BKP_RMD_TGFCGM_INS WHERE ID_EXECUCAO=v_id;
  INSERT INTO SANKHYA.BKP_RMD_TGFCGM_INS(ID_EXECUCAO,ROWID_ORIGINAL,CODEMP,ANO,MES)
    SELECT v_id,NULL,e.CODEMP,1900,1 FROM TSIEMP e
    WHERE NOT EXISTS (SELECT 1 FROM TGFCGM g WHERE g.CODEMP=e.CODEMP AND g.ANO=1900 AND g.MES=1);
  v_sql:='INSERT INTO TGFCGM (CODEMP,'||v_cols||') SELECT e.CODEMP,'||v_sel||' FROM TSIEMP e CROSS JOIN (SELECT '||v_cols||' FROM TGFCGM WHERE CODEMP=1 AND ANO=1900 AND MES=1) s WHERE NOT EXISTS (SELECT 1 FROM TGFCGM x WHERE x.CODEMP=e.CODEMP AND x.ANO=s.ANO AND x.MES=s.MES)';
  EXECUTE IMMEDIATE v_sql; v_ins:=SQL%ROWCOUNT;
  UPDATE SANKHYA.BKP_RMD_TGFCGM_INS b SET ROWID_ORIGINAL=(SELECT ROWIDTOCHAR(g.ROWID) FROM TGFCGM g WHERE g.CODEMP=b.CODEMP AND g.ANO=b.ANO AND g.MES=b.MES) WHERE b.ID_EXECUCAO=v_id;
  IF v_ins<>v_missing THEN RAISE_APPLICATION_ERROR(-20312,'Insercoes divergentes: esperadas='||v_missing||', realizadas='||v_ins); END IF;
  SELECT COUNT(*) INTO v_n FROM SANKHYA.BKP_RMD_TGFCGM_INS WHERE ID_EXECUCAO=v_id AND ROWID_ORIGINAL IS NULL;
  IF v_n<>0 THEN RAISE_APPLICATION_ERROR(-20314,'Mapa sem ROWID para insercoes='||v_n); END IF;
  SELECT COUNT(*) INTO v_n FROM TSIEMP e WHERE NOT EXISTS (SELECT 1 FROM TGFCGM g WHERE g.CODEMP=e.CODEMP AND g.ANO=1900 AND g.MES=1);
  IF v_n<>0 THEN RAISE_APPLICATION_ERROR(-20313,'Empresas ainda sem TGFCGM='||v_n); END IF;
  COMMIT; DBMS_OUTPUT.PUT_LINE('ID_EXECUCAO='||v_id||'; INSERIDAS='||v_ins||'; TGFCGM_TOTAL_EMPRESAS_OK='||v_emp);
EXCEPTION WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('ERRO_REVERTIDO='||SQLERRM); RAISE;
END;
/
SPOOL OFF
