SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET ECHO ON
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
ALTER SESSION SET CURRENT_SCHEMA=SANKHYA;
SPOOL "/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Clientes/IMPORTUDO COMERCIO/Logs/Reverter_TGFCGM_Empresas.log"
PROMPT ROLLBACK_AUTOCONTIDO_TGFCGM_IMPORTUDO
DECLARE v_id CONSTANT VARCHAR2(40):='RMD_TGFCGM_IMPORTUDO_20260911_01'; v_n NUMBER; v_del NUMBER;
BEGIN
 SELECT COUNT(*) INTO v_n FROM SANKHYA.BKP_RMD_TGFCGM_INS WHERE ID_EXECUCAO=v_id;
 IF v_n=0 THEN RAISE_APPLICATION_ERROR(-20320,'Backup de insercoes TGFCGM nao encontrado para o ID fixo.'); END IF;
 DELETE FROM TGFCGM g WHERE EXISTS (SELECT 1 FROM SANKHYA.BKP_RMD_TGFCGM_INS b WHERE b.ID_EXECUCAO=v_id AND b.ROWID_ORIGINAL=ROWIDTOCHAR(g.ROWID));
 v_del:=SQL%ROWCOUNT; IF v_del<>v_n THEN RAISE_APPLICATION_ERROR(-20321,'Rollback divergente: backup='||v_n||', removidos='||v_del); END IF;
 COMMIT; DBMS_OUTPUT.PUT_LINE('ID_EXECUCAO='||v_id||'; REGISTROS_REVERTIDOS='||v_del);
EXCEPTION WHEN OTHERS THEN ROLLBACK; RAISE;
END;
/
SPOOL OFF
