SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET ECHO ON
ALTER SESSION SET CURRENT_SCHEMA=SANKHYA;
SPOOL "/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Clientes/IMPORTUDO COMERCIO/Logs/Validar_Merge_Colisoes_SANKHYA_09.log"
PROMPT VALIDACAO_MERGE_COLISOES_29_30_IMPORTUDO
SELECT COUNT(*) MAPA_BAI FROM SANKHYA.BKP_RMD_MERGE_BAI_09 WHERE ID_EXECUCAO='IMPORTUDO_20260911_MERGE_09';
SELECT COUNT(*) MAPA_END FROM SANKHYA.BKP_RMD_MERGE_END_09 WHERE ID_EXECUCAO='IMPORTUDO_20260911_MERGE_09';
SELECT COUNT(*) REFERENCIAS FROM SANKHYA.BKP_RMD_MERGE_REF_09 WHERE ID_EXECUCAO='IMPORTUDO_20260911_MERGE_09';
SELECT COUNT(*) DUP_BAI FROM (SELECT 1 FROM TSIBAI GROUP BY REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEBAI),'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ','AAAAAEEEEIIIIOOOOOUUUUCA')),' {2,}',' ') HAVING COUNT(*)>1);
SELECT COUNT(*) DUP_END FROM (SELECT 1 FROM TSIEND GROUP BY TIPO,REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEEND),'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ','AAAAAEEEEIIIIOOOOOUUUUCA')),' {2,}',' ') HAVING COUNT(*)>1);
SELECT COUNT(*) OBS_BAI_RESTANTES FROM TSIBAI WHERE CODBAI IN (SELECT COD_OBSOLETO FROM SANKHYA.BKP_RMD_MERGE_BAI_09 WHERE ID_EXECUCAO='IMPORTUDO_20260911_MERGE_09');
SELECT COUNT(*) OBS_END_RESTANTES FROM TSIEND WHERE CODEND IN (SELECT COD_OBSOLETO FROM SANKHYA.BKP_RMD_MERGE_END_09 WHERE ID_EXECUCAO='IMPORTUDO_20260911_MERGE_09');
PROMPT FIM_VALIDACAO_MERGE_COLISOES_29_30
SPOOL OFF
