SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET SQLBLANKLINES ON
SET ECHO ON
WHENEVER SQLERROR CONTINUE
ALTER SESSION SET CURRENT_SCHEMA=SANKHYA;
SPOOL "/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Clientes/IMPORTUDO COMERCIO/Logs/Verificacao_Onboarding_Final_IMPORTUDO.log"
PROMPT VERIFICACAO_FINAL_ONBOARDING_IMPORTUDO
PROMPT DADOS_DA_EMPRESA_CONFERENCIA_MANUAL_COM_ARTEFATO_PDF
SELECT * FROM TSIEMP ORDER BY CODEMP;
PROMPT SMTP_VALOR_CADASTRADO
SELECT TEXTO FROM TSIPAR WHERE CHAVE='MSDSMTPPROP';
PROMPT PLANILHAS_CONTAS_BANCARIAS_CADASTRADAS
SELECT * FROM TSICTA ORDER BY CODCTABCOINT;
PROMPT PLANILHAS_USUARIOS_CADASTRADOS
SELECT * FROM TSIUSU ORDER BY CODUSU;
PROMPT PLANILHAS_VENDEDORES_COMPRADORES_CADASTRADOS
SELECT * FROM TGFVEN ORDER BY CODVEND;
PROMPT PLANILHAS_GRUPOS_PRODUTOS_CADASTRADOS
SELECT * FROM TGFGRU ORDER BY CODGRUPOPROD;
PROMPT PLANILHAS_CENTROS_RESULTADOS_CADASTRADOS
SELECT * FROM TSICUS ORDER BY CODCENCUS;
PROMPT PLANILHAS_NATUREZAS_CADASTRADAS
SELECT * FROM TGFNAT ORDER BY CODNAT;
PROMPT PLANILHAS_LOCAIS_ESTOQUE_CADASTRADOS
SELECT * FROM TGFLOC ORDER BY CODLOCAL;
PROMPT FIM_VERIFICACAO_FINAL_ONBOARDING_IMPORTUDO
SPOOL OFF
