-- HIGIEPAM - rollback autocontido da onda 29/30.
-- Nao executar automaticamente: exige validacao de estado e autorizacao propria.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

DECLARE
  v_merge_id VARCHAR2(50) := 'RMD_HIGIEPAM_2930_MERGE_20260922082832';
  v_excl_id VARCHAR2(50) := 'RMD_HIGIEPAM_2930_EXCL_20260922084148';
  v_sql VARCHAR2(32767);
  v_n NUMBER;

  PROCEDURE validate_dependencies IS
  BEGIN
    FOR r IN (
      SELECT DISTINCT TABLE_NAME,COLUMN_NAME
        FROM RMD_HIGIEPAM_2930_DEP
       WHERE ID_EXECUCAO=v_merge_id
       ORDER BY TABLE_NAME,COLUMN_NAME
    ) LOOP
      v_sql := 'SELECT COUNT(*) FROM RMD_HIGIEPAM_2930_DEP d WHERE d.ID_EXECUCAO=:1 '||
        'AND d.TABLE_NAME=:2 AND d.COLUMN_NAME=:3 AND NOT EXISTS ('||
        'SELECT 1 FROM '||r.TABLE_NAME||' t WHERE ROWIDTOCHAR(t.ROWID)=d.RID '||
        'AND t.'||r.COLUMN_NAME||'=d.NEW_VALUE)';
      EXECUTE IMMEDIATE v_sql INTO v_n USING v_merge_id,r.TABLE_NAME,r.COLUMN_NAME;
      IF v_n<>0 THEN
        RAISE_APPLICATION_ERROR(-20360,'Dependencia alterada desde o merge em '||r.TABLE_NAME||'.'||r.COLUMN_NAME);
      END IF;
    END LOOP;
  END;

  PROCEDURE restore_dependencies IS
  BEGIN
    FOR r IN (
      SELECT DISTINCT TABLE_NAME,COLUMN_NAME
        FROM RMD_HIGIEPAM_2930_DEP
       WHERE ID_EXECUCAO=v_merge_id
       ORDER BY TABLE_NAME,COLUMN_NAME
    ) LOOP
      v_sql := 'UPDATE '||r.TABLE_NAME||' t SET '||r.COLUMN_NAME||'=('||
        'SELECT d.OLD_VALUE FROM RMD_HIGIEPAM_2930_DEP d WHERE d.ID_EXECUCAO=:1 '||
        'AND d.TABLE_NAME=:2 AND d.COLUMN_NAME=:3 AND d.RID=ROWIDTOCHAR(t.ROWID) '||
        'AND d.NEW_VALUE=t.'||r.COLUMN_NAME||') WHERE EXISTS ('||
        'SELECT 1 FROM RMD_HIGIEPAM_2930_DEP d WHERE d.ID_EXECUCAO=:1 '||
        'AND d.TABLE_NAME=:2 AND d.COLUMN_NAME=:3 AND d.RID=ROWIDTOCHAR(t.ROWID) '||
        'AND d.NEW_VALUE=t.'||r.COLUMN_NAME||')';
      EXECUTE IMMEDIATE v_sql USING v_merge_id,r.TABLE_NAME,r.COLUMN_NAME,
        v_merge_id,r.TABLE_NAME,r.COLUMN_NAME;
      DBMS_OUTPUT.PUT_LINE('DEPENDENCIAS_REVERTIDAS|'||r.TABLE_NAME||'|'||r.COLUMN_NAME||'|'||SQL%ROWCOUNT);
    END LOOP;
  END;
BEGIN
  SELECT COUNT(*) INTO v_n FROM RMD_HIGIEPAM_2930_MAP WHERE ID_EXECUCAO=v_merge_id;
  IF v_n=0 THEN RAISE_APPLICATION_ERROR(-20361,'Mapa do merge inexistente.'); END IF;
  SELECT COUNT(*) INTO v_n FROM RMD_HIGIEPAM_2930_X_BAI WHERE ID_EXECUCAO=v_excl_id;
  IF v_n=0 THEN RAISE_APPLICATION_ERROR(-20362,'Backup de TSIBAI inexistente.'); END IF;
  SELECT COUNT(*) INTO v_n FROM RMD_HIGIEPAM_2930_X_END WHERE ID_EXECUCAO=v_excl_id;
  IF v_n=0 THEN RAISE_APPLICATION_ERROR(-20363,'Backup de TSIEND inexistente.'); END IF;

  validate_dependencies;

  INSERT INTO TSIBAI (CODBAI,NOMEBAI,CODREG,DTALTER,DESCRICAOCORREIO,NUVERSAO,ATUNUVERSAO)
  SELECT b.CODBAI,b.NOMEBAI,b.CODREG,b.DTALTER,b.DESCRICAOCORREIO,b.NUVERSAO,b.ATUNUVERSAO
    FROM RMD_HIGIEPAM_2930_X_BAI b
   WHERE b.ID_EXECUCAO=v_excl_id
     AND NOT EXISTS (SELECT 1 FROM TSIBAI x WHERE x.CODBAI=b.CODBAI);
  DBMS_OUTPUT.PUT_LINE('TSIBAI_PAIS_RESTAURADOS='||SQL%ROWCOUNT);

  INSERT INTO TSIEND (CODEND,NOMEEND,TIPO,DTALTER,DESCRICAOCORREIO,CODLOGRADOURO,NUVERSAO,ATUNUVERSAO)
  SELECT e.CODEND,e.NOMEEND,e.TIPO,e.DTALTER,e.DESCRICAOCORREIO,e.CODLOGRADOURO,e.NUVERSAO,e.ATUNUVERSAO
    FROM RMD_HIGIEPAM_2930_X_END e
   WHERE e.ID_EXECUCAO=v_excl_id
     AND NOT EXISTS (SELECT 1 FROM TSIEND x WHERE x.CODEND=e.CODEND);
  DBMS_OUTPUT.PUT_LINE('TSIEND_PAIS_RESTAURADOS='||SQL%ROWCOUNT);

  restore_dependencies;

  UPDATE TSIBAI b
     SET NOMEBAI=(SELECT x.NOMEBAI FROM RMD_HIGIEPAM_2930_X_BAI x
                   WHERE x.ID_EXECUCAO=v_excl_id AND x.CODBAI=b.CODBAI)
   WHERE EXISTS (SELECT 1 FROM RMD_HIGIEPAM_2930_X_BAI x
                  WHERE x.ID_EXECUCAO=v_excl_id AND x.CODBAI=b.CODBAI);
  DBMS_OUTPUT.PUT_LINE('TSIBAI_NOMES_RESTAURADOS='||SQL%ROWCOUNT);
  UPDATE TSIEND e
     SET NOMEEND=(SELECT x.NOMEEND FROM RMD_HIGIEPAM_2930_X_END x
                   WHERE x.ID_EXECUCAO=v_excl_id AND x.CODEND=e.CODEND)
   WHERE EXISTS (SELECT 1 FROM RMD_HIGIEPAM_2930_X_END x
                  WHERE x.ID_EXECUCAO=v_excl_id AND x.CODEND=e.CODEND);
  DBMS_OUTPUT.PUT_LINE('TSIEND_NOMES_RESTAURADOS='||SQL%ROWCOUNT);

  COMMIT;
  DBMS_OUTPUT.PUT_LINE('STATUS=ROLLBACK_29_30_HIGIEPAM_CONCLUIDO; MERGE_ORIGEM='||v_merge_id||'; EXCLUSAO_ORIGEM='||v_excl_id);
EXCEPTION WHEN OTHERS THEN
  ROLLBACK;
  RAISE;
END;
/
