-- Card 09 HIGIEPAM - pos-validacao read-only da fase 32A.

DEFINE ID_EXECUCAO = 'RMD_HIG_C09_2609220917'
DEFINE TBL_BASE = 'BKP_FD_HIG_2609220917'
DEFINE TBL_PPG = 'BKP_FD_HIG_2609220917_PPG'

SELECT COUNT(*) AS BASE_TOTAL,
       COUNT(DISTINCT NUNOTA) AS BASE_NOTAS
  FROM &TBL_BASE
 WHERE ID_EXECUCAO='&ID_EXECUCAO';

SELECT STATUS_MAPA, COUNT(*) AS QTD
  FROM &TBL_PPG
 WHERE ID_EXECUCAO='&ID_EXECUCAO'
 GROUP BY STATUS_MAPA
 ORDER BY STATUS_MAPA;

SELECT COUNT(*) AS APTO_PARA_VALIDACAO_FINAL
  FROM &TBL_PPG
 WHERE ID_EXECUCAO='&ID_EXECUCAO'
   AND STATUS_MAPA='APTO_PARA_VALIDACAO_FINAL';

SELECT COUNT(*) AS SEM_VDUP_XML
  FROM &TBL_PPG
 WHERE ID_EXECUCAO='&ID_EXECUCAO'
   AND STATUS_MAPA='SEM_VDUP_XML';

SELECT COUNT(*) AS REVISAR_MULTIPLOS_XML
  FROM &TBL_PPG
 WHERE ID_EXECUCAO='&ID_EXECUCAO'
   AND STATUS_MAPA='REVISAR_MULTIPLOS_XML';
