-- Reversao autocontida do mapa 32A do Card 09 HIGIEPAM.
-- Nao altera TGFFIN; por padrao somente diagnostica.

SET DEFINE ON
SET SERVEROUTPUT ON SIZE UNLIMITED
SET SQLBLANKLINES ON
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

DEFINE CONFIRMA_ROLLBACK = 'NAO'
DEFINE TBL_BASE = 'BKP_FD_HIG_2609220917'
DEFINE TBL_PPG = 'BKP_FD_HIG_2609220917_PPG'

DECLARE
  v_confirm VARCHAR2(3) := UPPER('&&CONFIRMA_ROLLBACK');
  v_base NUMBER;
  v_ppg NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_base
    FROM ALL_TABLES
   WHERE OWNER = SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
     AND TABLE_NAME = UPPER('&&TBL_BASE');
  SELECT COUNT(*) INTO v_ppg
    FROM ALL_TABLES
   WHERE OWNER = SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
     AND TABLE_NAME = UPPER('&&TBL_PPG');

  IF v_base = 0 AND v_ppg = 0 THEN
    DBMS_OUTPUT.PUT_LINE('STATUS=MAPA_NAO_EXISTE');
    RETURN;
  END IF;

  IF v_confirm <> 'SIM' THEN
    DBMS_OUTPUT.PUT_LINE('STATUS=NAO_EXECUTADO; altere CONFIRMA_ROLLBACK para SIM apos revisar.');
    RETURN;
  END IF;

  IF v_ppg = 1 THEN
    EXECUTE IMMEDIATE 'DROP TABLE &&TBL_PPG PURGE';
    DBMS_OUTPUT.PUT_LINE('MAPA_CLASSIFICACAO_REMOVIDO=SIM');
  END IF;
  IF v_base = 1 THEN
    EXECUTE IMMEDIATE 'DROP TABLE &&TBL_BASE PURGE';
    DBMS_OUTPUT.PUT_LINE('MAPA_BASE_REMOVIDO=SIM');
  END IF;
  DBMS_OUTPUT.PUT_LINE('STATUS=ROLLBACK_MAPA_EXECUTADO');
END;
/
