SELECT ITEM,
       VALOR,
       DETALHE,
       STATUS
  FROM (
        SELECT 'IDENTIDADE' AS ITEM,
               SYS_CONTEXT('USERENV','SESSION_USER') AS VALOR,
               SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AS DETALHE,
               SYS_CONTEXT('USERENV','SERVICE_NAME') AS STATUS
          FROM DUAL
        UNION ALL
        SELECT 'OBJETOS_INVALIDOS', TO_CHAR(COUNT(*)), 'ALL_OBJECTS', 'READ_ONLY'
          FROM ALL_OBJECTS
         WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND STATUS='INVALID'
        UNION ALL
        SELECT 'CONTROLE_OBJETOS_REVISAO', TO_CHAR(COUNT(*)), 'RMD_CONTROLE_OBJETOS', 'PERSISTENCIA'
          FROM RMD_CONTROLE_OBJETOS
        UNION ALL
        SELECT 'BACKUPS_RMD', TO_CHAR(COUNT(*)), 'ALL_TABLES', 'PERSISTENCIA'
          FROM ALL_TABLES
         WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
           AND (TABLE_NAME LIKE 'BKP_RMD_%' OR TABLE_NAME LIKE 'RMD_%')
        UNION ALL
        SELECT 'FINANCEIROS_SEM_NOTA', TO_CHAR(COUNT(*)), 'TGFFIN/TGFCAB', 'INTEGRIDADE'
          FROM (
                SELECT DISTINCT F.NUFIN
                  FROM TGFFIN F
                 WHERE NOT EXISTS (SELECT 1 FROM TGFCAB C WHERE C.NUNOTA=F.NUNOTA)
               )
        UNION ALL
        SELECT 'ITENS_SEM_CABECALHO', TO_CHAR(COUNT(*)), 'TGFITE/TGFCAB', 'INTEGRIDADE'
          FROM (
                SELECT DISTINCT I.NUNOTA
                  FROM TGFITE I
                 WHERE NOT EXISTS (SELECT 1 FROM TGFCAB C WHERE C.NUNOTA=I.NUNOTA)
               )
        UNION ALL
        SELECT 'CABECALHOS_SEM_ITENS', TO_CHAR(COUNT(*)), 'TGFCAB/TGFITE', 'INTEGRIDADE'
          FROM (
                SELECT DISTINCT C.NUNOTA
                  FROM TGFCAB C
                 WHERE C.TIPMOV <> 'Z'
                   AND NOT EXISTS (SELECT 1 FROM TGFITE I WHERE I.NUNOTA=C.NUNOTA)
               )
        UNION ALL
        SELECT 'CODIGOS_FISCAIS_CIDADES_DUPLICADOS', TO_CHAR(COUNT(*)), 'TSICID', 'INTEGRIDADE'
          FROM (
                SELECT CODMUNFIS
                  FROM TSICID
                 WHERE CODMUNFIS IS NOT NULL
                 GROUP BY CODMUNFIS
                HAVING COUNT(*) > 1
               )
       )
 ORDER BY ITEM;
