MERGE INTO TGFPRO PRO
USING (
    SELECT 
        P.CODPROD, 
        MAX(I_NOVO.CODIPI) AS NOVO_CODIPI,
        MAX(PITI.CSTIPI) AS NOVO_CST -- Usamos MAX para garantir valor único por CODPROD
    FROM TGFPRO P
    INNER JOIN TTKPITI PITI ON PITI.CODIGO = P.AD_IDEXTERNO
    INNER JOIN TGFIPI I_ATUAL ON I_ATUAL.CODIPI = P.CODIPI
    INNER JOIN TGFIPI I_NOVO ON I_NOVO.PERCENTUAL = PITI.ALIQIPI 
                             AND I_NOVO.CSTIPISAI = PITI.CSTIPI
    WHERE (I_ATUAL.PERCENTUAL <> PITI.ALIQIPI OR P.CSTIPISAI <> PITI.CSTIPI)
      AND PITI.ALIQIPI > 0
    GROUP BY P.CODPROD -- Agrupamos APENAS por CODPROD para eliminar a instabilidade
) DIVERGENTES
ON (PRO.CODPROD = DIVERGENTES.CODPROD)
WHEN MATCHED THEN
    UPDATE SET 
        PRO.CODIPI = DIVERGENTES.NOVO_CODIPI,
        PRO.CSTIPISAI = DIVERGENTES.NOVO_CST;