UPDATE TGFPAR
SET CLASSIFICMS = CASE 
    WHEN UPPER(TRIM(IDENTINSCESTAD)) = 'ISENTO' THEN 'I'

    WHEN TIPPESSOA = 'J' AND IDENTINSCESTAD IS NOT NULL THEN 'R'

    WHEN TIPPESSOA = 'J' AND IDENTINSCESTAD IS NULL THEN 'C'

    WHEN TIPPESSOA = 'F' AND IDENTINSCESTAD IS NOT NULL THEN 'P'

    WHEN TIPPESSOA = 'F' AND IDENTINSCESTAD IS NULL THEN 'C'

    ELSE CLASSIFICMS
END
WHERE CLASSIFICMS <> CASE 
    WHEN UPPER(TRIM(IDENTINSCESTAD)) = 'ISENTO' THEN 'I'
    WHEN TIPPESSOA = 'J' AND IDENTINSCESTAD IS NOT NULL THEN 'R'
    WHEN TIPPESSOA = 'J' AND IDENTINSCESTAD IS NULL THEN 'C'
    WHEN TIPPESSOA = 'F' AND IDENTINSCESTAD IS NOT NULL THEN 'P'
    WHEN TIPPESSOA = 'F' AND IDENTINSCESTAD IS NULL THEN 'C'
    ELSE CLASSIFICMS
END;