/* =========================================================
   INSERÇÃO DE REGISTRO EM TLFALIQCBS
   ========================================================= */
INSERT INTO TLFALIQCBS 
 (ATIVO, CCREDPRESCBS, CHAVEUNICA, CODCCLASTRIB, CODCID, CODCLASTRBREG, CODCNAE, CODCST, CODCSTREGULAR, CODEMP,
  CODNBS, CODNCM, CODREGTRIB, CODTIPOPER, CODUF, DHALTER, DTFIMVIG, DTINIVIG, IDCBS, NUFOP, OBSERVADFISCOIB,
  PALIQEFETCBS, PALIQREG, PCBS, PCREDPRESCBS, PDIFCBS, PFEDERALCBS, PREDALIQCBS, PREDUTORCBS, PREFCBS) 
  VALUES (
  'S', -- ATIVO
  NULL, -- CCREDPRESCBS
  '0;0;;0;0;3;0;0;0;19980101;20251001,20261231', -- CHAVEUNICA
  '000001', -- CODCCLASTRIB
  0, -- CODCID
  NULL, -- CODCLASTRBREG
  0, -- CODCNAE
  '000', -- CODCST
  NULL, -- CODCSTREGULAR
  NULL, -- CODEMP
  NULL, -- CODNBS
  0, -- CODNCM
  3, -- CODREGTRIB
  0, -- CODTIPOPER
  0, -- CODUF
  TO_DATE('1998-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), -- DHALTER
  TO_DATE('2026-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), -- DTFIMVIG
  TO_DATE('2025-10-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), -- DTINIVIG
  1, -- IDCBS
  NULL, -- NUFOP
  NULL, -- OBSERVADFISCOIB
  NULL, -- PALIQEFETCBS
  NULL, -- PALIQREG
  0.9, -- PCBS
  NULL, -- PCREDPRESCBS
  NULL, -- PDIFCBS
  100, -- PFEDERALCBS
  NULL, -- PREDALIQCBS
  NULL, -- PREDUTORCBS
  0.9 -- PREFCBS
);
COMMIT;

-- =========================================================
-- Inserção TLFALIQIBS
-- =========================================================
INSERT INTO TLFALIQIBS (
  ATIVO, CHAVEUNICA, CODCCLASTRIB, CODCID, CODCLASTRBREG, CODCNAE, CODCST, CODCSTREGULAR,
  CODEMP, CODNBS, CODNCM, CODREGTRIB, CODTIPOPER, CODUF, CREDPRESIBS, DHALTER, DTFIMVIG,
  DTINIVIG, IDIBS, NUFOP, OBSERVADFISCOIB, PALIQEFTMUIBS, PALIQEFTUFIBS, PALIQEST, PALIQMUN,
  PALIQREF, PALIQREGMUN, PALIQREGUF, PCREDPRESIBS, PDIFIBSMUN, PDIFIBSUF, PIBSMUN, PIBSUF,
  PREDALIQIBSMUN, PREDALIQIBSUF, PREDUTORIBS) 
  VALUES (
  'S',
  '0;0;;0;0;3;0;0;0;19980101;20251001,20261231',
  '000001',
  0,
  NULL,
  0,
  '000',
  NULL,
  NULL,
  NULL,
  0,
  3,
  0,
  0,
  NULL,
  TO_DATE('1998-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS'),
  TO_DATE('2026-12-31 00:00:00','YYYY-MM-DD HH24:MI:SS'),
  TO_DATE('2025-10-01 00:00:00','YYYY-MM-DD HH24:MI:SS'),
  1,
  NULL,
  NULL,
  NULL,
  NULL,
  100,
  NULL,
  0.1,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  0,
  0.1,
  NULL,
  NULL,
  NULL
);
COMMIT;

-- =========================================================
-- Atualizações complementares
-- =========================================================
UPDATE TGFNFENT T
   SET T.ATIVONT = 'S'
 WHERE EXISTS (SELECT 1 FROM TSIEMP E
                WHERE T.CODEMP = E.CODEMP
                AND E.CODREGTRIB = 3)
 AND T.VERSAONT = 13;
 COMMIT;

UPDATE TGFTOP
   SET TEMCBS = 'S',
       TEMIBS = 'S'
 WHERE TIPMOV = 'V';
COMMIT;

