SELECT 
    C.NUNOTA,
    C.CODTIPOPER,
    C.DTNEG,
    I.CODPROD,
    I.SEQUENCIA,
    P.NCM,
    XT.CFOP_TAG,
    XT.CST_IBS_CBS,
    XT.CLASSTRIB,
    XT.ALIQ_IBS_UF,
    XT.ALIQ_IBS_MUN,
    XT.ALIQ_CBS
FROM TGFNFE X
JOIN TGFCAB C ON C.CHAVENFE = X.CHAVENFE
JOIN TGFITE I ON I.NUNOTA = C.NUNOTA
JOIN TGFPRO P ON P.CODPROD = I.CODPROD
CROSS JOIN XMLTABLE(
    XMLNAMESPACES(DEFAULT 'http://www.portalfiscal.inf.br/nfe'),
    '//det'
    PASSING XMLTYPE(X.XML)
    COLUMNS 
        NITEM        VARCHAR2(10) PATH '@nItem',
        CFOP_TAG     VARCHAR2(10) PATH 'prod/CFOP',
        CST_IBS_CBS  VARCHAR2(3)  PATH 'imposto/IBSCBS/CST',
        CLASSTRIB    VARCHAR2(6)  PATH 'imposto/IBSCBS/cClassTrib',
        ALIQ_IBS_UF  VARCHAR2(10) PATH 'imposto/IBSCBS/gIBSCBS/gIBSUF/pIBSUF',
        ALIQ_IBS_MUN VARCHAR2(10) PATH 'imposto/IBSCBS/gIBSCBS/gIBSMun/pIBSMun',
        ALIQ_CBS     VARCHAR2(10) PATH 'imposto/IBSCBS/gIBSCBS/gCBS/pCBS'
) XT
WHERE C.DTNEG >= TO_DATE('01/01/2026', 'DD/MM/YYYY')
  AND TO_NUMBER(I.SEQUENCIA) = TO_NUMBER(XT.NITEM)
  AND XT.CFOP_TAG IS NOT NULL
ORDER BY C.DTNEG, C.NUNOTA