-- Cria o registro dos objetos temporariamente desabilitados pela revisao.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
VARIABLE RMD_ID_MASTER VARCHAR2(30)
BEGIN
 :RMD_ID_MASTER:='RMD_RUN_'||TO_CHAR(SYSTIMESTAMP,'YYYYMMDDHH24MISSFF3');
 DBMS_OUTPUT.PUT_LINE('ID_MASTER='||:RMD_ID_MASTER);
END;
/
DECLARE v NUMBER;BEGIN
 SELECT COUNT(*) INTO v FROM ALL_TABLES
  WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
    AND TABLE_NAME='RMD_CONTROLE_OBJETOS';
 IF v=0 THEN
  EXECUTE IMMEDIATE q'[CREATE TABLE RMD_CONTROLE_OBJETOS (
    ID_MASTER VARCHAR2(30) NOT NULL,
    ID_EXECUCAO VARCHAR2(30) NOT NULL,
    DH_REGISTRO TIMESTAMP NOT NULL,
    USUARIO_EXECUCAO VARCHAR2(128) NOT NULL,
    OBJECT_TYPE VARCHAR2(30) NOT NULL,
    OBJECT_NAME VARCHAR2(128) NOT NULL,
    STATUS_ANTES VARCHAR2(30),
    STATUS_DEPOIS VARCHAR2(30),
    DH_REABILITACAO TIMESTAMP
  )]';
  DBMS_OUTPUT.PUT_LINE('CONTROLE_CRIADO=RMD_CONTROLE_OBJETOS');
 ELSE
  DBMS_OUTPUT.PUT_LINE('CONTROLE_EXISTENTE=RMD_CONTROLE_OBJETOS');
 END IF;
END;
/
