-- Bloco 01_Liberar_Filtros_Portais; backup por execucao e atualizacao apenas de divergencias.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
DECLARE v NUMBER; BEGIN
 SELECT COUNT(*) INTO v FROM ALL_TABLES WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND TABLE_NAME='BKP_RMD_01_TSIPAR';
 IF v=0 THEN EXECUTE IMMEDIATE q'[CREATE TABLE BKP_RMD_01_TSIPAR AS
 SELECT CAST(NULL AS VARCHAR2(30)) ID_EXECUCAO, CAST(NULL AS TIMESTAMP) DH_EXECUCAO,
 CAST(NULL AS VARCHAR2(128)) USUARIO_EXECUCAO, CAST(NULL AS VARCHAR2(30)) ROWID_ORIGINAL,
 T.INTEIRO VALOR_ANTES, CAST(NULL AS NUMBER) VALOR_DEPOIS FROM TSIPAR T WHERE 1=0]'; END IF;
END;
/
DECLARE
 v_id VARCHAR2(30):='RMD_PORT_'||TO_CHAR(SYSTIMESTAMP,'YYYYMMDDHH24MISSFF3');
 v_id_trigger VARCHAR2(30):='RMD_TSPAR_'||TO_CHAR(SYSTIMESTAMP,'YYYYMMDDHH24MISSFF3');
 v_b PLS_INTEGER; v_u PLS_INTEGER;
 v_trigger_disabled PLS_INTEGER:=0;
BEGIN
 FOR R IN (
  SELECT TRIGGER_NAME
    FROM ALL_TRIGGERS
   WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
     AND TABLE_NAME='TSIPAR'
     AND STATUS='ENABLED'
     AND TRIGGER_NAME LIKE '%LOG%'
   ORDER BY TRIGGER_NAME
 ) LOOP
  INSERT INTO RMD_CONTROLE_OBJETOS
    (ID_MASTER,ID_EXECUCAO,DH_REGISTRO,USUARIO_EXECUCAO,OBJECT_TYPE,OBJECT_NAME,STATUS_ANTES)
  VALUES
    (:RMD_ID_MASTER,v_id_trigger,SYSTIMESTAMP,SYS_CONTEXT('USERENV','SESSION_USER'),'TRIGGER',R.TRIGGER_NAME,'ENABLED');
  EXECUTE IMMEDIATE 'ALTER TRIGGER '||DBMS_ASSERT.ENQUOTE_NAME(R.TRIGGER_NAME,FALSE)||' DISABLE';
  v_trigger_disabled:=v_trigger_disabled+1;
 END LOOP;
 BEGIN
  INSERT INTO BKP_RMD_01_TSIPAR
  SELECT v_id,SYSTIMESTAMP,SYS_CONTEXT('USERENV','SESSION_USER'),ROWIDTOCHAR(ROWID),INTEIRO,CAST(NULL AS NUMBER)
  FROM TSIPAR WHERE CHAVE IN ('MAXDIASPORTAIS','MAXDIASPORTVEND','MAXDIASPORTCOMP','MAXDIASMOVFIN') AND INTEIRO IS NOT NULL;
  v_b:=SQL%ROWCOUNT;
  UPDATE TSIPAR SET INTEIRO=NULL WHERE CHAVE IN ('MAXDIASPORTAIS','MAXDIASPORTVEND','MAXDIASPORTCOMP','MAXDIASMOVFIN') AND INTEIRO IS NOT NULL;
  v_u:=SQL%ROWCOUNT;
  IF v_b<>v_u THEN RAISE_APPLICATION_ERROR(-20201,'Backup e atualizacao divergiram em 01_Liberar_Filtros_Portais.'); END IF;
  COMMIT;
 EXCEPTION WHEN OTHERS THEN
  ROLLBACK;
  IF v_trigger_disabled>0 THEN
   FOR R IN (
    SELECT OBJECT_NAME
      FROM RMD_CONTROLE_OBJETOS
     WHERE ID_MASTER=:RMD_ID_MASTER AND ID_EXECUCAO=v_id_trigger AND STATUS_DEPOIS IS NULL
   ) LOOP
    EXECUTE IMMEDIATE 'ALTER TRIGGER '||DBMS_ASSERT.ENQUOTE_NAME(R.OBJECT_NAME,FALSE)||' ENABLE';
    UPDATE RMD_CONTROLE_OBJETOS
       SET STATUS_DEPOIS='ENABLED',DH_REABILITACAO=SYSTIMESTAMP
     WHERE ID_MASTER=:RMD_ID_MASTER AND ID_EXECUCAO=v_id_trigger AND OBJECT_NAME=R.OBJECT_NAME;
   END LOOP;
   COMMIT;
  END IF;
  RAISE;
 END;
 IF v_trigger_disabled>0 THEN
  FOR R IN (
   SELECT OBJECT_NAME
     FROM RMD_CONTROLE_OBJETOS
    WHERE ID_MASTER=:RMD_ID_MASTER AND ID_EXECUCAO=v_id_trigger AND STATUS_DEPOIS IS NULL
  ) LOOP
   EXECUTE IMMEDIATE 'ALTER TRIGGER '||DBMS_ASSERT.ENQUOTE_NAME(R.OBJECT_NAME,FALSE)||' ENABLE';
   UPDATE RMD_CONTROLE_OBJETOS
      SET STATUS_DEPOIS='ENABLED',DH_REABILITACAO=SYSTIMESTAMP
    WHERE ID_MASTER=:RMD_ID_MASTER AND ID_EXECUCAO=v_id_trigger AND OBJECT_NAME=R.OBJECT_NAME;
  END LOOP;
 END IF;
 COMMIT;
 DBMS_OUTPUT.PUT_LINE('ID_EXECUCAO='||v_id);
 DBMS_OUTPUT.PUT_LINE('REGISTROS_ALTERADOS='||v_u);
 DBMS_OUTPUT.PUT_LINE('TRIGGERS_LOG_TSIPAR='||v_trigger_disabled||'_DESABILITADOS_E_REABILITADOS');
EXCEPTION WHEN OTHERS THEN ROLLBACK; RAISE;
END;
/
