-- Bloco 02. Mantem a regra funcional aprovada com snapshot das linhas.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
DECLARE v NUMBER; BEGIN
 SELECT COUNT(*) INTO v FROM ALL_TABLES WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND TABLE_NAME='BKP_RMD_02_TGFEMP';
 IF v=0 THEN EXECUTE IMMEDIATE q'[CREATE TABLE BKP_RMD_02_TGFEMP AS SELECT CAST(NULL AS VARCHAR2(30)) ID_EXECUCAO,
 CAST(NULL AS TIMESTAMP) DH_EXECUCAO, CAST(NULL AS VARCHAR2(128)) USUARIO_EXECUCAO,
 CAST(NULL AS VARCHAR2(30)) ROWID_ORIGINAL, T.CODMODDANFESIMPLIFNFE CODMODDANFESIMPLIFNFE_ANTES, T.CONTINGENCIANFE CONTINGENCIANFE_ANTES, T.ENVIOSINCRONONFE ENVIOSINCRONONFE_ANTES, T.NURFE NURFE_ANTES, T.NURFECARTACORR NURFECARTACORR_ANTES, T.TIPODANFE TIPODANFE_ANTES, T.NFE NFE_ANTES, T.VERSAONFE VERSAONFE_ANTES, T.VERSAONT VERSAONT_ANTES, T.UTILIZAMDE UTILIZAMDE_ANTES, T.LOGODANFE LOGODANFE_ANTES FROM TGFEMP T WHERE 1=0]'; END IF;
END;
/
DECLARE v_id VARCHAR2(30):='RMD_DANF_'||TO_CHAR(SYSTIMESTAMP,'YYYYMMDDHH24MISSFF3'); v_b PLS_INTEGER; v_u PLS_INTEGER;
BEGIN
 INSERT INTO BKP_RMD_02_TGFEMP SELECT v_id,SYSTIMESTAMP,SYS_CONTEXT('USERENV','SESSION_USER'),ROWIDTOCHAR(ROWID),CODMODDANFESIMPLIFNFE,CONTINGENCIANFE,ENVIOSINCRONONFE,NURFE,NURFECARTACORR,TIPODANFE,NFE,VERSAONFE,VERSAONT,UTILIZAMDE,LOGODANFE FROM TGFEMP WHERE CODEMP<>1;
 v_b:=SQL%ROWCOUNT;
 UPDATE TGFEMP SET CODMODDANFESIMPLIFNFE=(SELECT CODMODDANFESIMPLIFNFE FROM TGFEMP WHERE CODEMP=1),
 CONTINGENCIANFE=(SELECT CONTINGENCIANFE FROM TGFEMP WHERE CODEMP=1),
 ENVIOSINCRONONFE=(SELECT ENVIOSINCRONONFE FROM TGFEMP WHERE CODEMP=1),
 NURFE=(SELECT NURFE FROM TGFEMP WHERE CODEMP=1), NURFECARTACORR=(SELECT NURFECARTACORR FROM TGFEMP WHERE CODEMP=1),
 TIPODANFE=(SELECT TIPODANFE FROM TGFEMP WHERE CODEMP=1), NFE=(SELECT NFE FROM TGFEMP WHERE CODEMP=1),
 VERSAONFE=(SELECT VERSAONFE FROM TGFEMP WHERE CODEMP=1), VERSAONT=(SELECT VERSAONT FROM TGFEMP WHERE CODEMP=1),
 UTILIZAMDE=(SELECT UTILIZAMDE FROM TGFEMP WHERE CODEMP=1),
 LOGODANFE=COALESCE(LOGODANFE,(SELECT LOGODANFE FROM TGFEMP WHERE CODEMP=1)) WHERE CODEMP<>1;
 v_u:=SQL%ROWCOUNT;
 IF v_b<>v_u THEN RAISE_APPLICATION_ERROR(-20210,'Backup e atualizacao divergiram em Padronizar_DANFE_Empresas.'); END IF;
 COMMIT; DBMS_OUTPUT.PUT_LINE('ID_EXECUCAO='||v_id); DBMS_OUTPUT.PUT_LINE('REGISTROS_ALTERADOS='||v_u);

EXCEPTION WHEN OTHERS THEN ROLLBACK; RAISE; END;
/

