-- Bloco 07. Mantem a regra funcional aprovada com snapshot das linhas.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
DECLARE v NUMBER; BEGIN
 SELECT COUNT(*) INTO v FROM ALL_TABLES WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND TABLE_NAME='BKP_RMD_07_TGFCAB';
 IF v=0 THEN EXECUTE IMMEDIATE q'[CREATE TABLE BKP_RMD_07_TGFCAB AS SELECT CAST(NULL AS VARCHAR2(30)) ID_EXECUCAO,
 CAST(NULL AS TIMESTAMP) DH_EXECUCAO, CAST(NULL AS VARCHAR2(128)) USUARIO_EXECUCAO,
 CAST(NULL AS VARCHAR2(30)) ROWID_ORIGINAL, T.NUMPROTOC NUMPROTOC_ANTES, T.NUMPROTOCCTE NUMPROTOCCTE_ANTES FROM TGFCAB T WHERE 1=0]'; END IF;
END;
/
DECLARE v_id VARCHAR2(30):='RMD_PROT_'||TO_CHAR(SYSTIMESTAMP,'YYYYMMDDHH24MISSFF3'); v_b PLS_INTEGER; v_u PLS_INTEGER;
BEGIN
 INSERT INTO BKP_RMD_07_TGFCAB SELECT v_id,SYSTIMESTAMP,SYS_CONTEXT('USERENV','SESSION_USER'),ROWIDTOCHAR(ROWID),NUMPROTOC,NUMPROTOCCTE FROM TGFCAB WHERE EXISTS (SELECT 1 FROM TTKNOT N WHERE N.NUNOTA=TGFCAB.NUNOTA)
 AND ((NUMPROTOC IS NULL AND EXISTS (SELECT 1 FROM TGFTOP T WHERE T.CODTIPOPER=TGFCAB.CODTIPOPER AND T.DHALTER=TGFCAB.DHTIPOPER AND T.CODMODDOC=55))
   OR (NUMPROTOCCTE IS NULL AND EXISTS (SELECT 1 FROM TGFTOP T WHERE T.CODTIPOPER=TGFCAB.CODTIPOPER AND T.DHALTER=TGFCAB.DHTIPOPER AND T.CODMODDOC=57)));
 v_b:=SQL%ROWCOUNT;
 UPDATE TGFCAB SET NUMPROTOC=CASE WHEN NUMPROTOC IS NULL AND EXISTS (SELECT 1 FROM TGFTOP T WHERE T.CODTIPOPER=TGFCAB.CODTIPOPER AND T.DHALTER=TGFCAB.DHTIPOPER AND T.CODMODDOC=55) THEN '0' ELSE NUMPROTOC END,
 NUMPROTOCCTE=CASE WHEN NUMPROTOCCTE IS NULL AND EXISTS (SELECT 1 FROM TGFTOP T WHERE T.CODTIPOPER=TGFCAB.CODTIPOPER AND T.DHALTER=TGFCAB.DHTIPOPER AND T.CODMODDOC=57) THEN '0' ELSE NUMPROTOCCTE END WHERE EXISTS (SELECT 1 FROM TTKNOT N WHERE N.NUNOTA=TGFCAB.NUNOTA)
 AND ((NUMPROTOC IS NULL AND EXISTS (SELECT 1 FROM TGFTOP T WHERE T.CODTIPOPER=TGFCAB.CODTIPOPER AND T.DHALTER=TGFCAB.DHTIPOPER AND T.CODMODDOC=55))
   OR (NUMPROTOCCTE IS NULL AND EXISTS (SELECT 1 FROM TGFTOP T WHERE T.CODTIPOPER=TGFCAB.CODTIPOPER AND T.DHALTER=TGFCAB.DHTIPOPER AND T.CODMODDOC=57)));
 v_u:=SQL%ROWCOUNT;
 IF v_b<>v_u THEN RAISE_APPLICATION_ERROR(-20210,'Backup e atualizacao divergiram em Preencher_Protocolos_Documentos_Legados.'); END IF;
 COMMIT; DBMS_OUTPUT.PUT_LINE('ID_EXECUCAO='||v_id); DBMS_OUTPUT.PUT_LINE('REGISTROS_ALTERADOS='||v_u);

EXCEPTION WHEN OTHERS THEN ROLLBACK; RAISE; END;
/
