-- Corrige STATUSNOTA preservando o estado inicial da trigger.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
DECLARE v NUMBER; BEGIN
 SELECT COUNT(*) INTO v FROM ALL_TABLES WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND TABLE_NAME='BKP_RMD_08_TGFITE';
 IF v=0 THEN EXECUTE IMMEDIATE q'[CREATE TABLE BKP_RMD_08_TGFITE AS SELECT
 CAST(NULL AS VARCHAR2(30)) ID_EXECUCAO,CAST(NULL AS TIMESTAMP) DH_EXECUCAO,
 CAST(NULL AS VARCHAR2(128)) USUARIO_EXECUCAO,CAST(NULL AS VARCHAR2(30)) ROWID_ORIGINAL,
 I.STATUSNOTA STATUSNOTA_ANTES FROM TGFITE I WHERE 1=0]'; END IF;
END;
/
DECLARE
 v_id VARCHAR2(30):='RMD_ITEM_'||TO_CHAR(SYSTIMESTAMP,'YYYYMMDDHH24MISSFF3');
 v_status VARCHAR2(8); v_b PLS_INTEGER; v_u PLS_INTEGER;
 PROCEDURE restaura_trigger IS BEGIN
   IF v_status='ENABLED' THEN EXECUTE IMMEDIATE 'ALTER TRIGGER TRG_UPT_TGFITE ENABLE'; END IF;
 EXCEPTION WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('ERRO_AO_RESTAURAR_TRIGGER='||SQLERRM); RAISE; END;
BEGIN
 SELECT STATUS INTO v_status FROM ALL_TRIGGERS
  WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND TRIGGER_NAME='TRG_UPT_TGFITE';
 INSERT INTO BKP_RMD_08_TGFITE SELECT v_id,SYSTIMESTAMP,SYS_CONTEXT('USERENV','SESSION_USER'),
        ROWIDTOCHAR(ROWID),STATUSNOTA FROM TGFITE I
  WHERE NVL(STATUSNOTA,'?')<>'L' AND EXISTS(SELECT 1 FROM TTKNOT N WHERE N.NUNOTA=I.NUNOTA);
 v_b:=SQL%ROWCOUNT;
 IF v_status='ENABLED' THEN
  INSERT INTO RMD_CONTROLE_OBJETOS
   (ID_MASTER,ID_EXECUCAO,DH_REGISTRO,USUARIO_EXECUCAO,OBJECT_TYPE,OBJECT_NAME,STATUS_ANTES)
  VALUES(:RMD_ID_MASTER,v_id,SYSTIMESTAMP,SYS_CONTEXT('USERENV','SESSION_USER'),
         'TRIGGER','TRG_UPT_TGFITE',v_status);
  EXECUTE IMMEDIATE 'ALTER TRIGGER TRG_UPT_TGFITE DISABLE';
 END IF;
 UPDATE TGFITE I SET STATUSNOTA='L'
  WHERE NVL(STATUSNOTA,'?')<>'L' AND EXISTS(SELECT 1 FROM TTKNOT N WHERE N.NUNOTA=I.NUNOTA);
 v_u:=SQL%ROWCOUNT;
 restaura_trigger;
 UPDATE RMD_CONTROLE_OBJETOS SET STATUS_DEPOIS='ENABLED',DH_REABILITACAO=SYSTIMESTAMP
  WHERE ID_MASTER=:RMD_ID_MASTER AND ID_EXECUCAO=v_id
    AND OBJECT_TYPE='TRIGGER' AND OBJECT_NAME='TRG_UPT_TGFITE';
 IF v_b<>v_u THEN RAISE_APPLICATION_ERROR(-20220,'Backup e atualizacao de itens divergiram.'); END IF;
 COMMIT; DBMS_OUTPUT.PUT_LINE('ID_EXECUCAO='||v_id); DBMS_OUTPUT.PUT_LINE('ITENS_ALTERADOS='||v_u);
EXCEPTION WHEN OTHERS THEN
 BEGIN restaura_trigger; EXCEPTION WHEN OTHERS THEN NULL; END;
 ROLLBACK; RAISE;
END;
/
