-- Bloco 09_Habilitar_ICMS_Gerencial; backup por execucao e atualizacao apenas de divergencias.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
DECLARE v NUMBER; BEGIN
 SELECT COUNT(*) INTO v FROM ALL_TABLES WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND TABLE_NAME='BKP_RMD_09_TGFPRO';
 IF v=0 THEN EXECUTE IMMEDIATE q'[CREATE TABLE BKP_RMD_09_TGFPRO AS
 SELECT CAST(NULL AS VARCHAR2(30)) ID_EXECUCAO, CAST(NULL AS TIMESTAMP) DH_EXECUCAO,
 CAST(NULL AS VARCHAR2(128)) USUARIO_EXECUCAO, CAST(NULL AS VARCHAR2(30)) ROWID_ORIGINAL,
 T.ICMSGERENCIA VALOR_ANTES, CAST('S' AS VARCHAR2(1)) VALOR_DEPOIS FROM TGFPRO T WHERE 1=0]'; END IF;
END;
/
DECLARE
 v_id VARCHAR2(30):='RMD_ICMG_'||TO_CHAR(SYSTIMESTAMP,'YYYYMMDDHH24MISSFF3');
 v_b PLS_INTEGER; v_u PLS_INTEGER;
BEGIN
 INSERT INTO BKP_RMD_09_TGFPRO
 SELECT v_id,SYSTIMESTAMP,SYS_CONTEXT('USERENV','SESSION_USER'),ROWIDTOCHAR(ROWID),ICMSGERENCIA,CAST('S' AS VARCHAR2(1))
 FROM TGFPRO WHERE USOPROD IN ('V','R') AND NVL(ICMSGERENCIA,'?')<>'S';
 v_b:=SQL%ROWCOUNT;
 UPDATE TGFPRO SET ICMSGERENCIA='S' WHERE USOPROD IN ('V','R') AND NVL(ICMSGERENCIA,'?')<>'S';
 v_u:=SQL%ROWCOUNT;
 IF v_b<>v_u THEN RAISE_APPLICATION_ERROR(-20201,'Backup e atualizacao divergiram em 09_Habilitar_ICMS_Gerencial.'); END IF;
 COMMIT;
 DBMS_OUTPUT.PUT_LINE('ID_EXECUCAO='||v_id);
 DBMS_OUTPUT.PUT_LINE('REGISTROS_ALTERADOS='||v_u);
EXCEPTION WHEN OTHERS THEN ROLLBACK; RAISE;
END;
/

