-- Bloco 14_Desativar_Rastro_Sem_Controle; backup por execucao e atualizacao apenas de divergencias.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
DECLARE v NUMBER; BEGIN
 SELECT COUNT(*) INTO v FROM ALL_TABLES WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND TABLE_NAME='BKP_RMD_14_TGFPRO';
 IF v=0 THEN EXECUTE IMMEDIATE q'[CREATE TABLE BKP_RMD_14_TGFPRO AS
 SELECT CAST(NULL AS VARCHAR2(30)) ID_EXECUCAO, CAST(NULL AS TIMESTAMP) DH_EXECUCAO,
 CAST(NULL AS VARCHAR2(128)) USUARIO_EXECUCAO, CAST(NULL AS VARCHAR2(30)) ROWID_ORIGINAL,
 T.TEMRASTROLOTE VALOR_ANTES, CAST('N' AS VARCHAR2(1)) VALOR_DEPOIS FROM TGFPRO T WHERE 1=0]'; END IF;
END;
/
DECLARE
 v_id VARCHAR2(30):='RMD_RAST_'||TO_CHAR(SYSTIMESTAMP,'YYYYMMDDHH24MISSFF3');
 v_b PLS_INTEGER; v_u PLS_INTEGER;
BEGIN
 EXECUTE IMMEDIATE q'~
  INSERT INTO SANKHYA.BKP_RMD_14_TGFPRO
  SELECT :id_execucao,SYSTIMESTAMP,SYS_CONTEXT('USERENV','SESSION_USER'),ROWIDTOCHAR(ROWID),TEMRASTROLOTE,CAST('N' AS VARCHAR2(1))
  FROM SANKHYA.TGFPRO WHERE TEMRASTROLOTE='S' AND TIPCONTEST='N'
 ~' USING v_id;
 v_b:=SQL%ROWCOUNT;
 EXECUTE IMMEDIATE q'~
  UPDATE SANKHYA.TGFPRO SET TEMRASTROLOTE='N' WHERE TEMRASTROLOTE='S' AND TIPCONTEST='N'
 ~';
 v_u:=SQL%ROWCOUNT;
 IF v_b<>v_u THEN RAISE_APPLICATION_ERROR(-20201,'Backup e atualizacao divergiram em 14_Desativar_Rastro_Sem_Controle.'); END IF;
 COMMIT;
 DBMS_OUTPUT.PUT_LINE('ID_EXECUCAO='||v_id);
 DBMS_OUTPUT.PUT_LINE('REGISTROS_ALTERADOS='||v_u);
EXCEPTION WHEN OTHERS THEN ROLLBACK; RAISE;
END;
/
