-------------------------------------------------------------------------------
-- NORMALIZAÇÃO DE UNIDADES (TGFPRO/TGFITE/TGFPAP/TGFCOI2/TGFGIR1 -> TGFVOA -> TGFVOL)
-- + USA RMD_MAP_UNIDADES, OBJETO EXCLUSIVO DESTA ROTINA DE REVISAO
-------------------------------------------------------------------------------

SET DEFINE OFF;
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
VARIABLE RMD_ID_MASTER VARCHAR2(30)
BEGIN
 :RMD_ID_MASTER:=NVL(:RMD_ID_MASTER,'RMD_RUN_'||TO_CHAR(SYSTIMESTAMP,'YYYYMMDDHH24MISSFF3'));
 DBMS_OUTPUT.PUT_LINE('ID_MASTER='||:RMD_ID_MASTER);
END;
/
VARIABLE RMD_ID_UNID VARCHAR2(30)
BEGIN :RMD_ID_UNID:='RMD_UNID_'||TO_CHAR(SYSTIMESTAMP,'YYYYMMDDHH24MISSFF3');END;
/

-------------------------------------------------------------------------------
-- 1) CRIA RMD_MAP_UNIDADES SE NÃO EXISTIR
-------------------------------------------------------------------------------
DECLARE
  v_exists NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO v_exists
    FROM ALL_TABLES
   WHERE OWNER = SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND TABLE_NAME = 'RMD_MAP_UNIDADES';

  IF v_exists = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE RMD_MAP_UNIDADES (
        FROM_CODE VARCHAR2(20) NOT NULL,
        TO_CODE   VARCHAR2(20) NOT NULL,
        CONSTRAINT PK_RMD_MAP_UNIDADES PRIMARY KEY (FROM_CODE)
      )';
    DBMS_OUTPUT.PUT_LINE('OK: Tabela RMD_MAP_UNIDADES criada.');
  ELSE
    DBMS_OUTPUT.PUT_LINE('OK: Tabela RMD_MAP_UNIDADES ja existe.');
  END IF;
END;
/
-------------------------------------------------------------------------------
-- 2) POPULA / ATUALIZA RMD_MAP_UNIDADES VIA MERGE (IDEMPOTENTE)
-------------------------------------------------------------------------------
DECLARE v NUMBER;BEGIN
 SELECT COUNT(*) INTO v FROM ALL_TABLES WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND TABLE_NAME='BKP_RMD_UNID_MAP';
 IF v=0 THEN EXECUTE IMMEDIATE q'[CREATE TABLE BKP_RMD_UNID_MAP AS SELECT
 CAST(NULL AS VARCHAR2(30)) ID_EXECUCAO,CAST(NULL AS TIMESTAMP) DH_EXECUCAO,
 CAST(NULL AS VARCHAR2(128)) USUARIO_EXECUCAO,M.* FROM RMD_MAP_UNIDADES M WHERE 1=0]';END IF;
END;
/
INSERT INTO BKP_RMD_UNID_MAP
SELECT :RMD_ID_UNID,SYSTIMESTAMP,SYS_CONTEXT('USERENV','SESSION_USER'),M.*
  FROM RMD_MAP_UNIDADES M;
MERGE INTO RMD_MAP_UNIDADES t
USING (
  SELECT 'CDA'    AS FROM_CODE, 'CD'  AS TO_CODE FROM dual UNION ALL
  SELECT 'CX5000','CX'  FROM dual UNION ALL
  SELECT 'CXA',   'CX'  FROM dual UNION ALL
  SELECT 'CX1',   'CX'  FROM dual UNION ALL
  SELECT 'CAIXA', 'CX'  FROM dual UNION ALL
  SELECT 'CX.',   'CX'  FROM dual UNION ALL
  SELECT 'CX,',   'CX'  FROM dual UNION ALL
  SELECT 'KLG',   'KG'  FROM dual UNION ALL
  SELECT 'KG/1',  'KG'  FROM dual UNION ALL
  SELECT 'KG1',   'KG'  FROM dual UNION ALL
  SELECT '1 KG',  'KG'  FROM dual UNION ALL
  SELECT 'KG.',   'KG'  FROM dual UNION ALL
  SELECT '.KG',   'KG'  FROM dual UNION ALL
  SELECT 'L',     'LT'  FROM dual UNION ALL
  SELECT 'LIT',   'LT'  FROM dual UNION ALL
  SELECT 'LTS',   'LT'  FROM dual UNION ALL
  SELECT 'LTRS',  'LT'  FROM dual UNION ALL
  SELECT 'LITRO', 'LT'  FROM dual UNION ALL
  SELECT 'LT1',   'LT'  FROM dual UNION ALL
  SELECT 'PEC',   'PC'  FROM dual UNION ALL
  SELECT 'PÇ',    'PC'  FROM dual UNION ALL
  SELECT 'PÇ.',   'PC'  FROM dual UNION ALL
  SELECT 'PÇ,',   'PC'  FROM dual UNION ALL
  SELECT 'PC,',   'PC'  FROM dual UNION ALL
  SELECT 'PECA',  'PC'  FROM dual UNION ALL
  SELECT 'PECAS', 'PC'  FROM dual UNION ALL
  SELECT 'PEÇAS', 'PC'  FROM dual UNION ALL
  SELECT 'PEÇA',  'PC'  FROM dual UNION ALL
  SELECT 'PC/1',  'PC'  FROM dual UNION ALL
  SELECT 'PC01PC','PC'  FROM dual UNION ALL
  SELECT 'PC1',   'PC'  FROM dual UNION ALL
  SELECT 'PCA',   'PC'  FROM dual UNION ALL
  SELECT 'PCS',   'PC'  FROM dual UNION ALL
  SELECT 'PÇS',   'PC'  FROM dual UNION ALL
  SELECT 'PEÇ',   'PC'  FROM dual UNION ALL
  SELECT 'PE',    'PC'  FROM dual UNION ALL
  SELECT 'PC.',   'PC'  FROM dual UNION ALL
  SELECT 'PC0',   'PC'  FROM dual UNION ALL
  SELECT 'PC0001','PC'  FROM dual UNION ALL
  SELECT 'PC01',  'PC'  FROM dual UNION ALL
  SELECT 'PÇS.',  'PC'  FROM dual UNION ALL  
  SELECT 'PC-',   'PC'  FROM dual UNION ALL  
  SELECT '..UN',  'UN'  FROM dual UNION ALL
  SELECT '1 UNID','UN'  FROM dual UNION ALL
  SELECT '1UN',   'UN'  FROM dual UNION ALL
  SELECT 'UND',   'UN'  FROM dual UNION ALL
  SELECT 'UNI',   'UN'  FROM dual UNION ALL
  SELECT 'UNIT.', 'UN'  FROM dual UNION ALL
  SELECT 'UNIT',  'UN'  FROM dual UNION ALL
  SELECT 'UNID',  'UN'  FROM dual UNION ALL
  SELECT 'UNIDA', 'UN'  FROM dual UNION ALL
  SELECT 'UNIDAD','UN'  FROM dual UNION ALL
  SELECT 'UN1',   'UN'  FROM dual UNION ALL
  SELECT 'UN.',   'UN'  FROM dual UNION ALL
  SELECT 'UN,',   'UN'  FROM dual UNION ALL
  SELECT 'U',     'UN'  FROM dual UNION ALL
  SELECT 'UD',    'UN'  FROM dual UNION ALL
  SELECT 'UN/1',  'UN'  FROM dual UNION ALL
  SELECT 'UND.',  'UN'  FROM dual UNION ALL
  SELECT 'UNID.', 'UN'  FROM dual UNION ALL
  SELECT 'UNN',   'UN'  FROM dual UNION ALL
  SELECT 'U.N',   'UN'  FROM dual UNION ALL
  SELECT 'UM',    'UN'  FROM dual UNION ALL
  SELECT 'UN0001','UN'  FROM dual UNION ALL
  SELECT 'UN0012','UN'  FROM dual UNION ALL
  SELECT 'UN9',   'UN'  FROM dual UNION ALL
  SELECT 'UND8',  'UN'  FROM dual UNION ALL
  SELECT 'UND9',  'UN'  FROM dual UNION ALL
  SELECT 'UNDI',  'UN'  FROM dual UNION ALL
  SELECT 'UN''',  'UN'  FROM dual UNION ALL
  SELECT 'U N',   'UN'  FROM dual UNION ALL
  SELECT 'UN000', 'UN'  FROM dual UNION ALL
  SELECT 'M',     'MT'  FROM dual UNION ALL
  SELECT '.MT',   'MT'  FROM dual UNION ALL
  SELECT 'MTR',   'MT'  FROM dual UNION ALL
  SELECT 'METRO', 'MT'  FROM dual UNION ALL
  SELECT 'MTS',   'MT'  FROM dual UNION ALL
  SELECT 'PCT',   'PT'  FROM dual UNION ALL
  SELECT 'PACOTE','PT'  FROM dual UNION ALL
  SELECT 'PAC',   'PT'  FROM dual UNION ALL
  SELECT 'PCT.',  'PT'  FROM dual UNION ALL
  SELECT 'PCOT',  'PT'  FROM dual UNION ALL
  SELECT 'PCTE',  'PT'  FROM dual UNION ALL
  SELECT 'TO',    'TN'  FROM dual UNION ALL
  SELECT 'T',     'TN'  FROM dual UNION ALL
  SELECT 'TON',   'TN'  FROM dual UNION ALL
  SELECT 'RLRL',  'RL'  FROM dual UNION ALL
  SELECT 'RLO',   'RL'  FROM dual UNION ALL
  SELECT 'ROL',   'RL'  FROM dual UNION ALL
  SELECT 'ROLO',  'RL'  FROM dual UNION ALL
  SELECT 'RL1',   'RL'  FROM dual UNION ALL
  SELECT 'RL01RL','RL'  FROM dual UNION ALL
  SELECT 'BLOCO', 'BL'  FROM dual UNION ALL
  SELECT 'FRASCO','FR'  FROM dual UNION ALL
  SELECT 'FR1',   'FR'  FROM dual UNION ALL
  SELECT 'FR/1',  'FR'  FROM dual UNION ALL
  SELECT 'JOGO',  'JG'  FROM dual UNION ALL
  SELECT 'JGO',   'JG'  FROM dual UNION ALL
  SELECT 'JG1',   'JG'  FROM dual UNION ALL
  SELECT 'JGO8',  'JG'  FROM dual UNION ALL
  SELECT 'JGO9',  'JG'  FROM dual UNION ALL
  SELECT 'JOG',   'JG'  FROM dual UNION ALL
  SELECT 'SC/1',  'SC'  FROM dual UNION ALL
  SELECT 'SA',    'SC'  FROM dual UNION ALL
  SELECT 'SAC',   'SC'  FROM dual UNION ALL
  SELECT 'SACO',  'SC'  FROM dual UNION ALL
  SELECT 'CJT',   'CJ'  FROM dual UNION ALL
  SELECT 'CONJ',  'CJ'  FROM dual UNION ALL
  SELECT 'CONJ.', 'CJ'  FROM dual UNION ALL
  SELECT 'FLH',   'FL'  FROM dual UNION ALL
  SELECT 'DUZIA', 'DZ'  FROM dual UNION ALL
  SELECT 'DZ12',  'DZ'  FROM dual UNION ALL
  SELECT 'KIT',   'KT'  FROM dual UNION ALL
  SELECT 'BALDE', 'BD'  FROM dual UNION ALL
  SELECT 'BAG',   'BG'  FROM dual UNION ALL
  SELECT 'M²',    'M2'  FROM dual UNION ALL
  SELECT 'M³',    'M3'  FROM dual UNION ALL
  SELECT 'GRAMAS','GR'  FROM dual UNION ALL
  SELECT 'FARDO', 'FD'  FROM dual UNION ALL
  SELECT 'FARDOS','FD'  FROM dual UNION ALL
  SELECT 'PA',    'PAR' FROM dual UNION ALL
  SELECT 'PARES', 'PAR' FROM dual
) s
ON (t.FROM_CODE = s.FROM_CODE)
WHEN MATCHED THEN UPDATE SET t.TO_CODE = s.TO_CODE
WHEN NOT MATCHED THEN INSERT (FROM_CODE, TO_CODE) VALUES (s.FROM_CODE, s.TO_CODE);

PROMPT OK: RMD_MAP_UNIDADES atualizado.

-------------------------------------------------------------------------------
-- 2.1) COMPLEMENTA O MAPA COM CANDIDATOS INEQUIVOCOS DA BASE
-- Regras: codigo que vira um destino canonico ao remover pontuacao; ou
-- descricao igual ao singular sem acentos. Codigos com numeros sao ignorados.
-- Somente candidatos com um unico destino possivel sao aplicados.
-------------------------------------------------------------------------------
MERGE INTO RMD_MAP_UNIDADES T
USING (
  WITH DESTINOS AS (
    SELECT DISTINCT M.TO_CODE,C.DESCRVOL
    FROM RMD_MAP_UNIDADES M
    JOIN TGFVOL C ON C.CODVOL=M.TO_CODE
  ), CANDIDATOS AS (
    SELECT S.CODVOL FROM_CODE,D.TO_CODE
    FROM TGFVOL S
    JOIN DESTINOS D
      ON REGEXP_REPLACE(
           TRANSLATE(UPPER(S.CODVOL),'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ','AAAAAEEEEIIIIOOOOOUUUUC'),
           '[^A-Z]','')=D.TO_CODE
    WHERE S.CODVOL<>D.TO_CODE
      AND NOT REGEXP_LIKE(S.CODVOL,'[0-9]')
    UNION ALL
    SELECT S.CODVOL,D.TO_CODE
    FROM TGFVOL S
    JOIN DESTINOS D
      ON REGEXP_REPLACE(REGEXP_REPLACE(
           TRANSLATE(UPPER(TRIM(S.DESCRVOL)),'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ','AAAAAEEEEIIIIOOOOOUUUUC'),
           '[^A-Z]',''),'S$','')
       = REGEXP_REPLACE(REGEXP_REPLACE(
           TRANSLATE(UPPER(TRIM(D.DESCRVOL)),'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ','AAAAAEEEEIIIIOOOOOUUUUC'),
           '[^A-Z]',''),'S$','')
    WHERE S.CODVOL<>D.TO_CODE
      AND NOT REGEXP_LIKE(S.CODVOL,'[0-9]')
  )
  SELECT FROM_CODE,MAX(TO_CODE) TO_CODE
  FROM CANDIDATOS
  GROUP BY FROM_CODE
  HAVING COUNT(DISTINCT TO_CODE)=1
) S
ON (T.FROM_CODE=S.FROM_CODE)
WHEN MATCHED THEN UPDATE SET T.TO_CODE=S.TO_CODE
WHEN NOT MATCHED THEN INSERT(FROM_CODE,TO_CODE) VALUES(S.FROM_CODE,S.TO_CODE);

PROMPT OK: candidatos inequivocos da base incorporados ao mapa.

-------------------------------------------------------------------------------
-- 3) REMOVE MAPEAMENTOS CUJO DESTINO NAO EXISTE
-------------------------------------------------------------------------------
DELETE FROM RMD_MAP_UNIDADES M
 WHERE M.TO_CODE IS NOT NULL
   AND NOT EXISTS(SELECT 1 FROM TGFVOL V WHERE V.CODVOL=TRIM(UPPER(M.TO_CODE)));

-------------------------------------------------------------------------------
-- 4) BACKUP POR EXECUCAO, NORMALIZACAO E LIMPEZA
-------------------------------------------------------------------------------
DECLARE
 PROCEDURE cria(p_tab VARCHAR2) IS v NUMBER;BEGIN
  SELECT COUNT(*) INTO v FROM ALL_TABLES WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND TABLE_NAME='BKP_RMD_UNID_'||p_tab;
  IF v=0 THEN EXECUTE IMMEDIATE 'CREATE TABLE BKP_RMD_UNID_'||p_tab||' AS SELECT CAST(NULL AS VARCHAR2(30)) ID_EXECUCAO,CAST(NULL AS TIMESTAMP) DH_EXECUCAO,CAST(NULL AS VARCHAR2(128)) USUARIO_EXECUCAO,CAST(NULL AS VARCHAR2(30)) ROWID_ORIGINAL,T.* FROM '||p_tab||' T WHERE 1=0';END IF;
 END;
BEGIN
 FOR T IN(SELECT 'TGFPRO' N FROM DUAL UNION ALL SELECT 'TGFITE' FROM DUAL UNION ALL SELECT 'TGFPAP' FROM DUAL UNION ALL SELECT 'TGFCOI2' FROM DUAL UNION ALL SELECT 'TGFGIR1' FROM DUAL UNION ALL SELECT 'TGFVOA' FROM DUAL UNION ALL SELECT 'TGFVOL' FROM DUAL)LOOP cria(T.N);END LOOP;
END;
/
INSERT INTO BKP_RMD_UNID_TGFPRO
SELECT :RMD_ID_UNID,SYSTIMESTAMP,SYS_CONTEXT('USERENV','SESSION_USER'),ROWIDTOCHAR(T.ROWID),T.*
  FROM TGFPRO T
 WHERE EXISTS(SELECT 1 FROM RMD_MAP_UNIDADES M WHERE M.FROM_CODE=T.CODVOL);
INSERT INTO BKP_RMD_UNID_TGFITE
SELECT :RMD_ID_UNID,SYSTIMESTAMP,SYS_CONTEXT('USERENV','SESSION_USER'),ROWIDTOCHAR(T.ROWID),T.*
  FROM TGFITE T
 WHERE EXISTS(SELECT 1 FROM RMD_MAP_UNIDADES M WHERE M.FROM_CODE=T.CODVOL);
INSERT INTO BKP_RMD_UNID_TGFPAP
SELECT :RMD_ID_UNID,SYSTIMESTAMP,SYS_CONTEXT('USERENV','SESSION_USER'),ROWIDTOCHAR(T.ROWID),T.*
  FROM TGFPAP T
 WHERE EXISTS(SELECT 1 FROM RMD_MAP_UNIDADES M WHERE M.FROM_CODE=T.UNIDADEPARC);
INSERT INTO BKP_RMD_UNID_TGFCOI2
SELECT :RMD_ID_UNID,SYSTIMESTAMP,SYS_CONTEXT('USERENV','SESSION_USER'),ROWIDTOCHAR(T.ROWID),T.*
  FROM TGFCOI2 T
 WHERE EXISTS(SELECT 1 FROM RMD_MAP_UNIDADES M WHERE M.FROM_CODE=T.CODVOL);
INSERT INTO BKP_RMD_UNID_TGFGIR1
SELECT :RMD_ID_UNID,SYSTIMESTAMP,SYS_CONTEXT('USERENV','SESSION_USER'),ROWIDTOCHAR(T.ROWID),T.*
  FROM TGFGIR1 T
 WHERE EXISTS(SELECT 1 FROM RMD_MAP_UNIDADES M WHERE M.FROM_CODE=T.CODVOL);
INSERT INTO BKP_RMD_UNID_TGFVOA
SELECT :RMD_ID_UNID,SYSTIMESTAMP,SYS_CONTEXT('USERENV','SESSION_USER'),ROWIDTOCHAR(T.ROWID),T.*
  FROM TGFVOA T
 WHERE EXISTS(SELECT 1 FROM RMD_MAP_UNIDADES M WHERE M.FROM_CODE=T.CODVOL);
INSERT INTO BKP_RMD_UNID_TGFVOL
SELECT :RMD_ID_UNID,SYSTIMESTAMP,SYS_CONTEXT('USERENV','SESSION_USER'),ROWIDTOCHAR(T.ROWID),T.*
  FROM TGFVOL T
 WHERE EXISTS(SELECT 1 FROM RMD_MAP_UNIDADES M WHERE M.FROM_CODE=T.CODVOL);
INSERT INTO BKP_RMD_UNID_TGFVOL
SELECT :RMD_ID_UNID,SYSTIMESTAMP,SYS_CONTEXT('USERENV','SESSION_USER'),ROWIDTOCHAR(T.ROWID),T.*
  FROM TGFVOL T
 WHERE T.DESCRVOL<>UPPER(T.DESCRVOL)
   AND NOT EXISTS(SELECT 1 FROM RMD_MAP_UNIDADES M WHERE M.FROM_CODE=T.CODVOL);

INSERT INTO RMD_CONTROLE_OBJETOS(ID_MASTER,ID_EXECUCAO,DH_REGISTRO,USUARIO_EXECUCAO,OBJECT_TYPE,OBJECT_NAME,STATUS_ANTES)
SELECT :RMD_ID_MASTER,:RMD_ID_UNID,SYSTIMESTAMP,SYS_CONTEXT('USERENV','SESSION_USER'),'TRIGGER',TRIGGER_NAME,STATUS
  FROM ALL_TRIGGERS
 WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
   AND TRIGGER_NAME IN ('TRG_INC_UPD_TGFITE','TRG_UPT_TGFITE')
   AND STATUS='ENABLED';
ALTER TRIGGER TRG_INC_UPD_TGFITE DISABLE;
ALTER TRIGGER TRG_UPT_TGFITE DISABLE;
UPDATE TGFPRO P SET CODVOL=(SELECT TO_CODE FROM RMD_MAP_UNIDADES WHERE FROM_CODE=P.CODVOL) WHERE EXISTS(SELECT 1 FROM RMD_MAP_UNIDADES WHERE FROM_CODE=P.CODVOL);
UPDATE TGFITE I SET CODVOL=(SELECT TO_CODE FROM RMD_MAP_UNIDADES WHERE FROM_CODE=I.CODVOL) WHERE EXISTS(SELECT 1 FROM RMD_MAP_UNIDADES WHERE FROM_CODE=I.CODVOL);
UPDATE TGFPAP P SET UNIDADEPARC=(SELECT TO_CODE FROM RMD_MAP_UNIDADES WHERE FROM_CODE=P.UNIDADEPARC) WHERE EXISTS(SELECT 1 FROM RMD_MAP_UNIDADES WHERE FROM_CODE=P.UNIDADEPARC);
UPDATE TGFCOI2 C SET CODVOL=(SELECT TO_CODE FROM RMD_MAP_UNIDADES WHERE FROM_CODE=C.CODVOL) WHERE EXISTS(SELECT 1 FROM RMD_MAP_UNIDADES WHERE FROM_CODE=C.CODVOL);
UPDATE TGFGIR1 G SET CODVOL=(SELECT TO_CODE FROM RMD_MAP_UNIDADES WHERE FROM_CODE=G.CODVOL) WHERE EXISTS(SELECT 1 FROM RMD_MAP_UNIDADES WHERE FROM_CODE=G.CODVOL);
DELETE FROM TGFVOA WHERE CODVOL IN(SELECT FROM_CODE FROM RMD_MAP_UNIDADES);
DELETE FROM TGFVOL WHERE CODVOL IN(SELECT FROM_CODE FROM RMD_MAP_UNIDADES);
UPDATE TGFVOL SET DESCRVOL=UPPER(DESCRVOL) WHERE DESCRVOL<>UPPER(DESCRVOL);
ALTER TRIGGER TRG_INC_UPD_TGFITE ENABLE;
ALTER TRIGGER TRG_UPT_TGFITE ENABLE;
UPDATE RMD_CONTROLE_OBJETOS SET STATUS_DEPOIS='ENABLED',DH_REABILITACAO=SYSTIMESTAMP
 WHERE ID_MASTER=:RMD_ID_MASTER AND ID_EXECUCAO=:RMD_ID_UNID
   AND OBJECT_TYPE='TRIGGER' AND STATUS_ANTES='ENABLED';
COMMIT;
PROMPT ID_EXECUCAO registrado na variavel RMD_ID_UNID.
PROMPT === FIM NORMALIZACAO DE UNIDADES ===
