-- Ajustes das preferencias e configuracoes do Gerente On-Line.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET SQLBLANKLINES ON
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

DECLARE
  PROCEDURE cria(p_nome VARCHAR2,p_sql CLOB) IS v NUMBER;
  BEGIN
    SELECT COUNT(*) INTO v FROM ALL_TABLES
     WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND TABLE_NAME=p_nome;
    IF v=0 THEN EXECUTE IMMEDIATE p_sql; END IF;
  END;
BEGIN
  cria('BKP_RMD_GOL_TSIPAR',q'[CREATE TABLE BKP_RMD_GOL_TSIPAR AS
    SELECT CAST(NULL AS VARCHAR2(30)) ID_EXECUCAO,CAST(NULL AS TIMESTAMP) DH_EXECUCAO,
           CAST(NULL AS VARCHAR2(128)) USUARIO_EXECUCAO,
           P.CHAVE,P.CODUSU,P.INTEIRO INTEIRO_ANTES
      FROM TSIPAR P WHERE 1=0]');
  cria('BKP_RMD_GOL_TGFCGM',q'[CREATE TABLE BKP_RMD_GOL_TGFCGM AS
    SELECT CAST(NULL AS VARCHAR2(30)) ID_EXECUCAO,CAST(NULL AS TIMESTAMP) DH_EXECUCAO,
           CAST(NULL AS VARCHAR2(128)) USUARIO_EXECUCAO,CAST(NULL AS VARCHAR2(30)) ROWID_ORIGINAL,
           C.PERCCFFAB,C.PERCCFOUTROS,C.PERCCFSERVICO,C.PERCCOFINS,C.PERCCSL,
           C.PERCCUSVAR,C.PERCCVARSEMST,C.PERCMARGEM,C.PERCPIS,C.PERCIRPJ,C.PERCCPP
      FROM TGFCGM C WHERE 1=0]');
  cria('BKP_RMD_GOL_TGFCMV',q'[CREATE TABLE BKP_RMD_GOL_TGFCMV AS
    SELECT CAST(NULL AS VARCHAR2(30)) ID_EXECUCAO,CAST(NULL AS TIMESTAMP) DH_EXECUCAO,
           CAST(NULL AS VARCHAR2(128)) USUARIO_EXECUCAO,CAST(NULL AS VARCHAR2(30)) ROWID_ORIGINAL,
           C.DHALTER,C.FORMGASTOFIX,C.INTERVALOATUALIZACAO,C.PERCUSTOFIX,
           C.QTDMESESCONSOLIDAR,C.TEMCOMISSAO,C.TIPDTGASTOFIX,C.TIPFATPER,C.TIPOCUSTO
      FROM TGFCMV C WHERE 1=0]');
END;
/

DECLARE
  v_id VARCHAR2(30):='RMD_GOL_'||TO_CHAR(SYSTIMESTAMP,'YYYYMMDDHH24MISSFF3');
  v_id_trigger VARCHAR2(30):='RMD_TSGOL_'||TO_CHAR(SYSTIMESTAMP,'YYYYMMDDHH24MISSFF3');
  v_origem NUMBER;
  v_b1 PLS_INTEGER;v_u1 PLS_INTEGER;v_b2 PLS_INTEGER;v_u2 PLS_INTEGER;
  v_b3 PLS_INTEGER;v_u3 PLS_INTEGER;
  v_trigger_disabled PLS_INTEGER:=0;
  PROCEDURE reabilita_triggers IS
  BEGIN
    IF v_trigger_disabled>0 THEN
      FOR R IN (
        SELECT OBJECT_NAME
          FROM RMD_CONTROLE_OBJETOS
         WHERE ID_MASTER=:RMD_ID_MASTER
           AND ID_EXECUCAO=v_id_trigger
           AND STATUS_DEPOIS IS NULL
      ) LOOP
        EXECUTE IMMEDIATE 'ALTER TRIGGER '||DBMS_ASSERT.ENQUOTE_NAME(R.OBJECT_NAME,FALSE)||' ENABLE';
        UPDATE RMD_CONTROLE_OBJETOS
           SET STATUS_DEPOIS='ENABLED',DH_REABILITACAO=SYSTIMESTAMP
         WHERE ID_MASTER=:RMD_ID_MASTER
           AND ID_EXECUCAO=v_id_trigger
           AND OBJECT_NAME=R.OBJECT_NAME;
      END LOOP;
    END IF;
  END;
BEGIN
  FOR R IN (
    SELECT TRIGGER_NAME
      FROM ALL_TRIGGERS
     WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
       AND TABLE_NAME='TSIPAR'
       AND STATUS='ENABLED'
       AND TRIGGER_NAME LIKE '%LOG%'
     ORDER BY TRIGGER_NAME
  ) LOOP
    INSERT INTO RMD_CONTROLE_OBJETOS
      (ID_MASTER,ID_EXECUCAO,DH_REGISTRO,USUARIO_EXECUCAO,OBJECT_TYPE,OBJECT_NAME,STATUS_ANTES)
    VALUES
      (:RMD_ID_MASTER,v_id_trigger,SYSTIMESTAMP,SYS_CONTEXT('USERENV','SESSION_USER'),'TRIGGER',R.TRIGGER_NAME,'ENABLED');
    EXECUTE IMMEDIATE 'ALTER TRIGGER '||DBMS_ASSERT.ENQUOTE_NAME(R.TRIGGER_NAME,FALSE)||' DISABLE';
    v_trigger_disabled:=v_trigger_disabled+1;
  END LOOP;

  BEGIN
  SELECT COUNT(*) INTO v_origem FROM TGFCGM WHERE CODEMP=1 AND ANO=1900 AND MES=1;
  IF v_origem<>1 THEN
    RAISE_APPLICATION_ERROR(-20301,'Esperada exatamente uma configuracao TGFCGM da empresa 1, ano 1900, mes 1.');
  END IF;

  INSERT INTO BKP_RMD_GOL_TSIPAR
  SELECT v_id,SYSTIMESTAMP,SYS_CONTEXT('USERENV','SESSION_USER'),CHAVE,CODUSU,INTEIRO
    FROM TSIPAR
   WHERE CODUSU=0 AND CHAVE IN
    ('GOL-QTDEPARC','GOL-QTDEPROD','GOL-QTDEMARC','GOL-QTDEGRUPOS',
     'GOL-QTDEVENDS','GOL-QTDEPERFIS','GOL-PERESTMED','GOL-TIPOCUSTO','PERCCUSFIXO')
     AND NVL(INTEIRO,-999)<>CASE
       WHEN CHAVE IN ('GOL-QTDEPARC','GOL-QTDEPROD','GOL-QTDEMARC','GOL-QTDEGRUPOS','GOL-QTDEVENDS','GOL-QTDEPERFIS') THEN 0
       WHEN CHAVE='GOL-PERESTMED' THEN 6 WHEN CHAVE='GOL-TIPOCUSTO' THEN 3 ELSE 10 END;
  v_b1:=SQL%ROWCOUNT;
  UPDATE TSIPAR SET INTEIRO=CASE
       WHEN CHAVE IN ('GOL-QTDEPARC','GOL-QTDEPROD','GOL-QTDEMARC','GOL-QTDEGRUPOS','GOL-QTDEVENDS','GOL-QTDEPERFIS') THEN 0
       WHEN CHAVE='GOL-PERESTMED' THEN 6 WHEN CHAVE='GOL-TIPOCUSTO' THEN 3 ELSE 10 END
   WHERE CODUSU=0 AND CHAVE IN
    ('GOL-QTDEPARC','GOL-QTDEPROD','GOL-QTDEMARC','GOL-QTDEGRUPOS',
     'GOL-QTDEVENDS','GOL-QTDEPERFIS','GOL-PERESTMED','GOL-TIPOCUSTO','PERCCUSFIXO')
     AND NVL(INTEIRO,-999)<>CASE
       WHEN CHAVE IN ('GOL-QTDEPARC','GOL-QTDEPROD','GOL-QTDEMARC','GOL-QTDEGRUPOS','GOL-QTDEVENDS','GOL-QTDEPERFIS') THEN 0
       WHEN CHAVE='GOL-PERESTMED' THEN 6 WHEN CHAVE='GOL-TIPOCUSTO' THEN 3 ELSE 10 END;
  v_u1:=SQL%ROWCOUNT;

  INSERT INTO BKP_RMD_GOL_TGFCGM
  SELECT v_id,SYSTIMESTAMP,SYS_CONTEXT('USERENV','SESSION_USER'),ROWIDTOCHAR(ROWID),
         PERCCFFAB,PERCCFOUTROS,PERCCFSERVICO,PERCCOFINS,PERCCSL,PERCCUSVAR,
         PERCCVARSEMST,PERCMARGEM,PERCPIS,PERCIRPJ,PERCCPP
    FROM TGFCGM WHERE CODEMP<>1;
  v_b2:=SQL%ROWCOUNT;
  UPDATE TGFCGM D SET
   (PERCCFFAB,PERCCFOUTROS,PERCCFSERVICO,PERCCOFINS,PERCCSL,PERCCUSVAR,
    PERCCVARSEMST,PERCMARGEM,PERCPIS,PERCIRPJ,PERCCPP)=
   (SELECT PERCCFFAB,PERCCFOUTROS,PERCCFSERVICO,PERCCOFINS,PERCCSL,PERCCUSVAR,
           PERCCVARSEMST,PERCMARGEM,PERCPIS,PERCIRPJ,PERCCPP
      FROM TGFCGM WHERE CODEMP=1 AND ANO=1900 AND MES=1)
   WHERE D.CODEMP<>1;
  v_u2:=SQL%ROWCOUNT;

  INSERT INTO BKP_RMD_GOL_TGFCMV
  SELECT v_id,SYSTIMESTAMP,SYS_CONTEXT('USERENV','SESSION_USER'),ROWIDTOCHAR(ROWID),
         DHALTER,FORMGASTOFIX,INTERVALOATUALIZACAO,PERCUSTOFIX,QTDMESESCONSOLIDAR,
         TEMCOMISSAO,TIPDTGASTOFIX,TIPFATPER,TIPOCUSTO
    FROM TGFCMV WHERE CODCONFIG=1;
  v_b3:=SQL%ROWCOUNT;
  IF v_b3<>1 THEN RAISE_APPLICATION_ERROR(-20302,'Esperada exatamente uma TGFCMV CODCONFIG=1.'); END IF;
  UPDATE TGFCMV SET DHALTER=SYSDATE,FORMGASTOFIX=0,INTERVALOATUALIZACAO=24,
         PERCUSTOFIX=10,QTDMESESCONSOLIDAR=24,TEMCOMISSAO=0,TIPDTGASTOFIX=0,
         TIPFATPER=0,TIPOCUSTO=3 WHERE CODCONFIG=1;
  v_u3:=SQL%ROWCOUNT;

  IF v_b1<>v_u1 OR v_b2<>v_u2 OR v_b3<>v_u3 THEN
    RAISE_APPLICATION_ERROR(-20303,'Quantidade de backup e atualizacao divergente nas preferencias GOL.');
  END IF;
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('ID_EXECUCAO='||v_id);
  DBMS_OUTPUT.PUT_LINE('TSIPAR='||v_u1||'; TGFCGM='||v_u2||'; TGFCMV='||v_u3);
  EXCEPTION WHEN OTHERS THEN
    ROLLBACK;
    reabilita_triggers;
    COMMIT;
    RAISE;
  END;

  reabilita_triggers;
  COMMIT;
EXCEPTION WHEN OTHERS THEN
  ROLLBACK;
  BEGIN
    reabilita_triggers;
    COMMIT;
  EXCEPTION WHEN OTHERS THEN
    ROLLBACK;
  END;
  RAISE;
END;
/
