-- Garante, antes da compilacao das etapas 18-30, todas as tabelas de backup.
-- Nao altera tabelas funcionais.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET SQLBLANKLINES ON
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
DECLARE
  PROCEDURE cria(p_nome VARCHAR2,p_sql CLOB) IS v NUMBER;
  BEGIN
    SELECT COUNT(*) INTO v FROM ALL_TABLES
    WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND TABLE_NAME=p_nome;
    IF v=0 THEN EXECUTE IMMEDIATE p_sql;DBMS_OUTPUT.PUT_LINE(p_nome||'=CRIADA');
    ELSE DBMS_OUTPUT.PUT_LINE(p_nome||'=EXISTENTE');END IF;
  END;
BEGIN
  cria('BKP_RMD_GOL_TSIPAR',q'[CREATE TABLE BKP_RMD_GOL_TSIPAR AS SELECT CAST(NULL AS VARCHAR2(30)) ID_EXECUCAO,CAST(NULL AS TIMESTAMP) DH_EXECUCAO,CAST(NULL AS VARCHAR2(128)) USUARIO_EXECUCAO,P.CHAVE,P.CODUSU,P.INTEIRO INTEIRO_ANTES FROM TSIPAR P WHERE 1=0]');
  cria('BKP_RMD_GOL_TGFCGM',q'[CREATE TABLE BKP_RMD_GOL_TGFCGM AS SELECT CAST(NULL AS VARCHAR2(30)) ID_EXECUCAO,CAST(NULL AS TIMESTAMP) DH_EXECUCAO,CAST(NULL AS VARCHAR2(128)) USUARIO_EXECUCAO,CAST(NULL AS VARCHAR2(30)) ROWID_ORIGINAL,C.PERCCFFAB,C.PERCCFOUTROS,C.PERCCFSERVICO,C.PERCCOFINS,C.PERCCSL,C.PERCCUSVAR,C.PERCCVARSEMST,C.PERCMARGEM,C.PERCPIS,C.PERCIRPJ,C.PERCCPP FROM TGFCGM C WHERE 1=0]');
  cria('BKP_RMD_GOL_TGFCMV',q'[CREATE TABLE BKP_RMD_GOL_TGFCMV AS SELECT CAST(NULL AS VARCHAR2(30)) ID_EXECUCAO,CAST(NULL AS TIMESTAMP) DH_EXECUCAO,CAST(NULL AS VARCHAR2(128)) USUARIO_EXECUCAO,CAST(NULL AS VARCHAR2(30)) ROWID_ORIGINAL,C.DHALTER,C.FORMGASTOFIX,C.INTERVALOATUALIZACAO,C.PERCUSTOFIX,C.QTDMESESCONSOLIDAR,C.TEMCOMISSAO,C.TIPDTGASTOFIX,C.TIPFATPER,C.TIPOCUSTO FROM TGFCMV C WHERE 1=0]');
  cria('BKP_RMD_PAR_MATRIZ',q'[CREATE TABLE BKP_RMD_PAR_MATRIZ(ID_EXECUCAO VARCHAR2(30) NOT NULL,DH_EXECUCAO TIMESTAMP NOT NULL,USUARIO_EXECUCAO VARCHAR2(128) NOT NULL,CODPARC NUMBER NOT NULL,CODPARCMATRIZ_ANTES NUMBER,CODPARCMATRIZ_DEPOIS NUMBER)]');
  cria('BKP_RMD_CARD_TTKINDAGT',q'[CREATE TABLE BKP_RMD_CARD_TTKINDAGT AS SELECT CAST(NULL AS VARCHAR2(30)) ID_EXECUCAO,CAST(NULL AS TIMESTAMP) DH_EXECUCAO,CAST(NULL AS VARCHAR2(128)) USUARIO_EXECUCAO,T.* FROM TTKINDAGT T WHERE 1=0]');
  cria('BKP_CLASSICMS_TGFPAR',q'[CREATE TABLE BKP_CLASSICMS_TGFPAR(ID_EXECUCAO VARCHAR2(30) NOT NULL,DH_EXECUCAO TIMESTAMP(6) NOT NULL,CODPARC NUMBER NOT NULL,CLASSIFICMS_ANTES VARCHAR2(1),CLASSIFICMS_DEPOIS VARCHAR2(1))]');
  cria('BKP_AJNP_TGFPAR',q'[CREATE TABLE BKP_AJNP_TGFPAR AS SELECT CAST(NULL AS VARCHAR2(30)) ID_EXECUCAO,CAST(NULL AS DATE) DH_EXECUCAO,CAST(NULL AS VARCHAR2(128)) USUARIO_EXECUCAO,P.CODPARC,P.NOMEPARC NOMEPARC_ANTES,P.RAZAOSOCIAL RAZAOSOCIAL_ANTES,P.NOMEPARC NOMEPARC_DEPOIS,P.RAZAOSOCIAL RAZAOSOCIAL_DEPOIS FROM TGFPAR P WHERE 1=0]');
  cria('BKP_RMD_PAD_TGFPAR',q'[CREATE TABLE BKP_RMD_PAD_TGFPAR AS SELECT CAST(NULL AS VARCHAR2(30)) ID_EXECUCAO,CAST(NULL AS TIMESTAMP) DH_EXECUCAO,CAST(NULL AS VARCHAR2(128)) USUARIO_EXECUCAO,CAST(NULL AS VARCHAR2(30)) ROWID_ORIGINAL,T.* FROM TGFPAR T WHERE 1=0]');
  cria('BKP_RMD_PAD_TGFPRO',q'[CREATE TABLE BKP_RMD_PAD_TGFPRO AS SELECT CAST(NULL AS VARCHAR2(30)) ID_EXECUCAO,CAST(NULL AS TIMESTAMP) DH_EXECUCAO,CAST(NULL AS VARCHAR2(128)) USUARIO_EXECUCAO,CAST(NULL AS VARCHAR2(30)) ROWID_ORIGINAL,T.* FROM TGFPRO T WHERE 1=0]');
  cria('BKP_RMD_PAD_TGFTIT',q'[CREATE TABLE BKP_RMD_PAD_TGFTIT AS SELECT CAST(NULL AS VARCHAR2(30)) ID_EXECUCAO,CAST(NULL AS TIMESTAMP) DH_EXECUCAO,CAST(NULL AS VARCHAR2(128)) USUARIO_EXECUCAO,CAST(NULL AS VARCHAR2(30)) ROWID_ORIGINAL,T.* FROM TGFTIT T WHERE 1=0]');
  cria('BKP_RMD_PAD_TSICID',q'[CREATE TABLE BKP_RMD_PAD_TSICID AS SELECT CAST(NULL AS VARCHAR2(30)) ID_EXECUCAO,CAST(NULL AS TIMESTAMP) DH_EXECUCAO,CAST(NULL AS VARCHAR2(128)) USUARIO_EXECUCAO,CAST(NULL AS VARCHAR2(30)) ROWID_ORIGINAL,T.* FROM TSICID T WHERE 1=0]');
  cria('BKP_RMD_PAD_TGFTPV',q'[CREATE TABLE BKP_RMD_PAD_TGFTPV AS SELECT CAST(NULL AS VARCHAR2(30)) ID_EXECUCAO,CAST(NULL AS TIMESTAMP) DH_EXECUCAO,CAST(NULL AS VARCHAR2(128)) USUARIO_EXECUCAO,CAST(NULL AS VARCHAR2(30)) ROWID_ORIGINAL,T.* FROM TGFTPV T WHERE 1=0]');
  cria('BKP_RMD_PAD_TSIBAI',q'[CREATE TABLE BKP_RMD_PAD_TSIBAI AS SELECT CAST(NULL AS VARCHAR2(30)) ID_EXECUCAO,CAST(NULL AS TIMESTAMP) DH_EXECUCAO,CAST(NULL AS VARCHAR2(128)) USUARIO_EXECUCAO,CAST(NULL AS VARCHAR2(30)) ROWID_ORIGINAL,T.* FROM TSIBAI T WHERE 1=0]');
  cria('BKP_RMD_PAD_TSIEND',q'[CREATE TABLE BKP_RMD_PAD_TSIEND AS SELECT CAST(NULL AS VARCHAR2(30)) ID_EXECUCAO,CAST(NULL AS TIMESTAMP) DH_EXECUCAO,CAST(NULL AS VARCHAR2(128)) USUARIO_EXECUCAO,CAST(NULL AS VARCHAR2(30)) ROWID_ORIGINAL,T.* FROM TSIEND T WHERE 1=0]');
END;
/
PROMPT === FIM PREPARACAO BACKUPS 18-30 ===
