-- Ultima barreira: reabilita somente objetos que estavam ENABLED quando uma
-- rotina desta revisao decidiu desabilita-los temporariamente.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
DECLARE
 v_status VARCHAR2(30);
 v_pendentes PLS_INTEGER:=0;
BEGIN
 FOR R IN (
  SELECT DISTINCT ID_MASTER,ID_EXECUCAO,OBJECT_TYPE,OBJECT_NAME
    FROM RMD_CONTROLE_OBJETOS
   WHERE STATUS_ANTES='ENABLED'
     AND NVL(STATUS_DEPOIS,'PENDENTE')<>'ENABLED'
 ) LOOP
  IF R.OBJECT_TYPE='TRIGGER' THEN
   SELECT STATUS INTO v_status FROM ALL_TRIGGERS
    WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
      AND TRIGGER_NAME=R.OBJECT_NAME;
   IF v_status<>'ENABLED' THEN
    EXECUTE IMMEDIATE 'ALTER TRIGGER '||DBMS_ASSERT.ENQUOTE_NAME(R.OBJECT_NAME,FALSE)||' ENABLE';
   END IF;
   SELECT STATUS INTO v_status FROM ALL_TRIGGERS
    WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
      AND TRIGGER_NAME=R.OBJECT_NAME;
   UPDATE RMD_CONTROLE_OBJETOS
      SET STATUS_DEPOIS=v_status,DH_REABILITACAO=SYSTIMESTAMP
    WHERE ID_MASTER=R.ID_MASTER
      AND ID_EXECUCAO=R.ID_EXECUCAO
      AND OBJECT_TYPE=R.OBJECT_TYPE AND OBJECT_NAME=R.OBJECT_NAME
      AND STATUS_ANTES='ENABLED';
   IF v_status<>'ENABLED' THEN
    v_pendentes:=v_pendentes+1;
    DBMS_OUTPUT.PUT_LINE('OBJETO_NAO_REABILITADO='||R.OBJECT_TYPE||':'||R.OBJECT_NAME);
   ELSE
    DBMS_OUTPUT.PUT_LINE('OBJETO_REABILITADO='||R.OBJECT_TYPE||':'||R.OBJECT_NAME);
   END IF;
  ELSE
   v_pendentes:=v_pendentes+1;
   DBMS_OUTPUT.PUT_LINE('TIPO_SEM_ROTINA_DE_REABILITACAO='||R.OBJECT_TYPE||':'||R.OBJECT_NAME);
  END IF;
 END LOOP;
 COMMIT;
 IF v_pendentes>0 THEN
  RAISE_APPLICATION_ERROR(-20500,'Existem objetos da revisao que nao foram reabilitados: '||v_pendentes);
 END IF;
 DBMS_OUTPUT.PUT_LINE('OBJETOS_DA_REVISAO_PENDENTES=0');
END;
/

PROMPT Triggers desabilitadas preexistentes ou externas a revisao (informativo):
SELECT TRIGGER_NAME,STATUS
  FROM ALL_TRIGGERS
 WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
   AND STATUS<>'ENABLED'
 ORDER BY TRIGGER_NAME;
PROMPT === FIM VALIDACAO DE REABILITACAO ===
