-- Reversao autocontida do merge 29/30 e da exclusao dos pais.
-- Restaura pais obsoletos a partir dos backups e depois devolve dependentes.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

DECLARE
  v_owner VARCHAR2(128) := SYS_CONTEXT('USERENV','CURRENT_SCHEMA');
  v_id VARCHAR2(40) := 'DCOMMERCE_20260911_MERGE_01';
  v_sql VARCHAR2(32767);
  v_cols VARCHAR2(32767);
  v_sel VARCHAR2(32767);
  v_n NUMBER;
  v_conf NUMBER;
  v_map VARCHAR2(128) := 'BKP_RMD_MRG_DCOM_20260911';
  v_bkp_bai VARCHAR2(128) := 'BKP_RMD_MRG_DCOM_20260911_BAI';
  v_bkp_end VARCHAR2(128) := 'BKP_RMD_MRG_DCOM_20260911_END';
  v_dep VARCHAR2(128) := 'BKP_RMD_MRG_DCOM_20260911_DEP';
  v_exc VARCHAR2(128) := 'BKP_RMD_MRG_DCOM_20260911_EXC';
  FUNCTION cols(p_table VARCHAR2,p_prefix VARCHAR2) RETURN VARCHAR2 IS
    v_out VARCHAR2(32767);
  BEGIN
    SELECT LISTAGG(p_prefix||column_name,',') WITHIN GROUP (ORDER BY column_id)
      INTO v_out
      FROM all_tab_columns
     WHERE owner=v_owner AND table_name=p_table AND column_name<>'ID_EXECUCAO';
    RETURN v_out;
  END;
BEGIN
  EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM '||v_map||' WHERE ID_EXECUCAO=:1' INTO v_n USING v_id;
  IF v_n=0 THEN RAISE_APPLICATION_ERROR(-20360,'Mapa persistente ausente'); END IF;
  EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM '||v_bkp_bai||' WHERE ID_EXECUCAO=:1' INTO v_n USING v_id;
  IF v_n=0 THEN RAISE_APPLICATION_ERROR(-20361,'Backup BAI ausente'); END IF;
  EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM '||v_bkp_end||' WHERE ID_EXECUCAO=:1' INTO v_n USING v_id;
  IF v_n=0 THEN RAISE_APPLICATION_ERROR(-20362,'Backup END ausente'); END IF;

  EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM '||v_bkp_bai||' b JOIN TSIBAI t ON t.CODBAI=b.CODBAI WHERE b.ID_EXECUCAO=:1 AND b.CODBAI IN (SELECT COD_OBSOLETO FROM '||v_map||' WHERE ID_EXECUCAO=:1 AND TIPO=''BAI'')' INTO v_conf USING v_id,v_id;
  IF v_conf<>0 THEN RAISE_APPLICATION_ERROR(-20363,'Conflito de CODBAI impede reversao'); END IF;
  EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM '||v_bkp_end||' b JOIN TSIEND t ON t.CODEND=b.CODEND WHERE b.ID_EXECUCAO=:1 AND b.CODEND IN (SELECT COD_OBSOLETO FROM '||v_map||' WHERE ID_EXECUCAO=:1 AND TIPO=''END'')' INTO v_conf USING v_id,v_id;
  IF v_conf<>0 THEN RAISE_APPLICATION_ERROR(-20364,'Conflito de CODEND impede reversao'); END IF;

  v_cols := cols('TSIBAI','');
  v_sel := cols('TSIBAI','b.');
  v_sql := 'INSERT INTO TSIBAI ('||v_cols||') SELECT '||v_sel||' FROM '||v_bkp_bai||' b WHERE b.ID_EXECUCAO=:1 AND b.CODBAI IN (SELECT COD_OBSOLETO FROM '||v_map||' WHERE ID_EXECUCAO=:1 AND TIPO=''BAI'')';
  EXECUTE IMMEDIATE v_sql USING v_id,v_id;
  DBMS_OUTPUT.PUT_LINE('PAIS_RESTAURADOS|TSIBAI|'||SQL%ROWCOUNT);

  v_cols := cols('TSIEND','');
  v_sel := cols('TSIEND','b.');
  v_sql := 'INSERT INTO TSIEND ('||v_cols||') SELECT '||v_sel||' FROM '||v_bkp_end||' b WHERE b.ID_EXECUCAO=:1 AND b.CODEND IN (SELECT COD_OBSOLETO FROM '||v_map||' WHERE ID_EXECUCAO=:1 AND TIPO=''END'')';
  EXECUTE IMMEDIATE v_sql USING v_id,v_id;
  DBMS_OUTPUT.PUT_LINE('PAIS_RESTAURADOS|TSIEND|'||SQL%ROWCOUNT);

  FOR r IN (SELECT DISTINCT c.TABLE_NAME,c.COLUMN_NAME FROM all_tab_columns c JOIN all_tables t ON t.owner=c.owner AND t.table_name=c.table_name WHERE c.owner=v_owner AND c.column_name IN ('CODBAI','CODEND') AND c.table_name NOT IN ('TSIBAI','TSIEND',v_map,v_bkp_bai,v_bkp_end,v_dep,v_exc)) LOOP
    IF r.COLUMN_NAME='CODBAI' THEN
      v_sql := 'UPDATE '||r.TABLE_NAME||' t SET t.CODBAI=(SELECT d.OLD_VALUE FROM '||v_dep||' d WHERE d.ID_EXECUCAO=:1 AND d.TABLE_NAME=:2 AND d.COLUMN_NAME=:3 AND d.RID=ROWIDTOCHAR(t.ROWID) AND d.NEW_VALUE=t.CODBAI) WHERE EXISTS (SELECT 1 FROM '||v_dep||' d WHERE d.ID_EXECUCAO=:1 AND d.TABLE_NAME=:2 AND d.COLUMN_NAME=:3 AND d.RID=ROWIDTOCHAR(t.ROWID) AND d.NEW_VALUE=t.CODBAI)';
    ELSE
      v_sql := 'UPDATE '||r.TABLE_NAME||' t SET t.CODEND=(SELECT d.OLD_VALUE FROM '||v_dep||' d WHERE d.ID_EXECUCAO=:1 AND d.TABLE_NAME=:2 AND d.COLUMN_NAME=:3 AND d.RID=ROWIDTOCHAR(t.ROWID) AND d.NEW_VALUE=t.CODEND) WHERE EXISTS (SELECT 1 FROM '||v_dep||' d WHERE d.ID_EXECUCAO=:1 AND d.TABLE_NAME=:2 AND d.COLUMN_NAME=:3 AND d.RID=ROWIDTOCHAR(t.ROWID) AND d.NEW_VALUE=t.CODEND)';
    END IF;
    EXECUTE IMMEDIATE v_sql USING v_id,r.TABLE_NAME,r.COLUMN_NAME,v_id,r.TABLE_NAME,r.COLUMN_NAME;
  END LOOP;
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('STATUS=ROLLBACK_29_30_EXECUTADO; ID_EXECUCAO='||v_id);
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END;
/
