-- Tratamento padronizado do card 09 - Notas sem Financeiro.
--
-- Este script faz o preflight e cria um mapa persistente dos candidatos.
-- A geração dos títulos deve ser executada pela rotina nativa de recálculo
-- em lote, após a confirmação do cliente. Não inserir TGFFIN manualmente.
-- LEGADO DA BASE MACALE; para novas bases use os modelos 32A/32B/32C na raiz de 7 - QA2.

SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET SQLBLANKLINES ON
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

PROMPT === CARD 09 - PREFLIGHT NOTAS SEM FINANCEIRO COM DUP ===

DECLARE
  v_qtd NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_qtd
    FROM ALL_TABLES
   WHERE OWNER = SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
     AND TABLE_NAME = 'BKP_RMD_FDUP_MCL_20260910';
  IF v_qtd > 0 THEN
    RAISE_APPLICATION_ERROR(-20320,
      'Mapa BKP_RMD_FDUP_MCL_20260910 já existe. Gere novo ID antes de repetir.');
  END IF;

  EXECUTE IMMEDIATE q'[
    CREATE TABLE BKP_RMD_FDUP_MCL_20260910 AS
    SELECT
      CAST('MACALE_20260910_FIN_DUP_01' AS VARCHAR2(40)) AS ID_EXECUCAO,
      SYSTIMESTAMP AS DH_EXECUCAO,
      SYS_CONTEXT('USERENV','SESSION_USER') AS USUARIO_EXECUCAO,
      C.NUNOTA, C.CODEMP, C.NUMNOTA, C.SERIENOTA, C.DTNEG, C.DTMOV,
      C.CODPARC, C.CODTIPOPER, T.DESCROPER, C.VLRNOTA,
      FNC_BUSCA_TAG_XML_GERAL(C.NUNOTA,'vDup','dup') AS VDUP_XML,
      FNC_BUSCA_TAG_XML_GERAL(C.NUNOTA,'dVenc','dup') AS DVENC_XML,
      FNC_BUSCA_TAG_XML_GERAL(C.NUNOTA,'nDup','dup') AS NDUP_XML
    FROM TGFCAB C
    JOIN TGFTOP T
      ON T.CODTIPOPER = C.CODTIPOPER
     AND T.DHALTER = (
       SELECT MAX(T2.DHALTER)
         FROM TGFTOP T2
        WHERE T2.CODTIPOPER = C.CODTIPOPER
          AND T2.DHALTER <= C.DHTIPOPER
     )
    WHERE T.ATUALFIN <> 0
      AND C.TIPMOV <> 'Z'
      AND NOT EXISTS (SELECT 1 FROM TGFFIN F WHERE F.NUNOTA = C.NUNOTA)
      AND FNC_BUSCA_TAG_XML_GERAL(C.NUNOTA,'vDup','dup') IS NOT NULL
      AND REGEXP_LIKE(
            FNC_BUSCA_TAG_XML_GERAL(C.NUNOTA,'dVenc','dup'),
            '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'
          )
  ]';
END;
/

DECLARE
  v_total NUMBER;
  v_eligible NUMBER;
  v_without_dup NUMBER;
  v_invalid_xml NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_total
    FROM TGFCAB C
    JOIN TGFTOP T
      ON T.CODTIPOPER = C.CODTIPOPER
     AND T.DHALTER = (
       SELECT MAX(T2.DHALTER) FROM TGFTOP T2
        WHERE T2.CODTIPOPER = C.CODTIPOPER AND T2.DHALTER <= C.DHTIPOPER
     )
   WHERE T.ATUALFIN <> 0 AND C.TIPMOV <> 'Z'
     AND NOT EXISTS (SELECT 1 FROM TGFFIN F WHERE F.NUNOTA = C.NUNOTA);

  SELECT COUNT(*) INTO v_eligible FROM BKP_RMD_FDUP_MCL_20260910;

  SELECT COUNT(*) INTO v_without_dup
    FROM TGFCAB C
    JOIN TGFTOP T
      ON T.CODTIPOPER = C.CODTIPOPER
     AND T.DHALTER = (
       SELECT MAX(T2.DHALTER) FROM TGFTOP T2
        WHERE T2.CODTIPOPER = C.CODTIPOPER AND T2.DHALTER <= C.DHTIPOPER
     )
   WHERE T.ATUALFIN <> 0 AND C.TIPMOV <> 'Z'
     AND NOT EXISTS (SELECT 1 FROM TGFFIN F WHERE F.NUNOTA = C.NUNOTA)
     AND FNC_BUSCA_TAG_XML_GERAL(C.NUNOTA,'vDup','dup') IS NULL;

  SELECT COUNT(*) INTO v_invalid_xml
    FROM TGFCAB C
    JOIN TGFTOP T
      ON T.CODTIPOPER = C.CODTIPOPER
     AND T.DHALTER = (
       SELECT MAX(T2.DHALTER) FROM TGFTOP T2
        WHERE T2.CODTIPOPER = C.CODTIPOPER AND T2.DHALTER <= C.DHTIPOPER
     )
   WHERE T.ATUALFIN <> 0 AND C.TIPMOV <> 'Z'
     AND NOT EXISTS (SELECT 1 FROM TGFFIN F WHERE F.NUNOTA = C.NUNOTA)
     AND FNC_BUSCA_TAG_XML_GERAL(C.NUNOTA,'vDup','dup') IS NOT NULL
     AND NOT REGEXP_LIKE(
           FNC_BUSCA_TAG_XML_GERAL(C.NUNOTA,'dVenc','dup'),
           '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'
         );

  DBMS_OUTPUT.PUT_LINE('ID_EXECUCAO=MACALE_20260910_FIN_DUP_01');
  DBMS_OUTPUT.PUT_LINE('NOTAS_SEM_FINANCEIRO_TOTAL='||v_total);
  DBMS_OUTPUT.PUT_LINE('CANDIDATOS_DUP_DVENC_VALIDOS='||v_eligible);
  DBMS_OUTPUT.PUT_LINE('SEM_DUP_PARA_ANALISE='||v_without_dup);
  DBMS_OUTPUT.PUT_LINE('DUP_COM_XML_INVALIDO='||v_invalid_xml);
  DBMS_OUTPUT.PUT_LINE('STATUS=AGUARDANDO_ROTINA_NATIVA_DE_RECALCULO');
END;
/

PROMPT === CANDIDATOS POR TOP ===
SELECT CODTIPOPER, DESCROPER, COUNT(*) AS CANDIDATOS
  FROM BKP_RMD_FDUP_MCL_20260910
 GROUP BY CODTIPOPER, DESCROPER
 ORDER BY CODTIPOPER;

PROMPT === PROXIMA ACAO ===
PROMPT Executar a rotina nativa de recálculo financeiro em lote para o mapa BKP_RMD_FDUP_MCL_20260910.
PROMPT Depois, executar novamente o preflight do card 09 e registrar processados e restantes.
PROMPT Este script nao altera TGFCAB, TGFTOP ou TGFFIN.

