SET SERVEROUTPUT ON SIZE UNLIMITED

SELECT TIPO, COUNT(*) QTD
FROM BKP_RMD_MRG_DCOM_20260911
WHERE ID_EXECUCAO='DCOMMERCE_20260911_MERGE_01'
GROUP BY TIPO
ORDER BY TIPO;

SELECT COUNT(*) QTD
FROM BKP_RMD_MRG_DCOM_20260911_DEP
WHERE ID_EXECUCAO='DCOMMERCE_20260911_MERGE_01';

SELECT COUNT(*) QTD
FROM BKP_RMD_MRG_DCOM_20260911_EXC
WHERE ID_EXECUCAO='DCOMMERCE_20260911_MERGE_01';

DECLARE
  v_sql VARCHAR2(32767);
  v_n NUMBER;
  v_id VARCHAR2(40) := 'DCOMMERCE_20260911_MERGE_01';
BEGIN
  FOR r IN (
    SELECT DISTINCT c.table_name, c.column_name
    FROM all_tab_columns c
    JOIN all_tables t ON t.owner=c.owner AND t.table_name=c.table_name
    WHERE c.owner=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
      AND c.column_name IN ('CODBAI','CODEND')
      AND c.table_name NOT IN (
        'TSIBAI','TSIEND','BKP_RMD_MRG_DCOM_20260911',
        'BKP_RMD_MRG_DCOM_20260911_BAI','BKP_RMD_MRG_DCOM_20260911_END',
        'BKP_RMD_MRG_DCOM_20260911_DEP','BKP_RMD_MRG_DCOM_20260911_EXC'
      )
    ORDER BY c.table_name,c.column_name
  ) LOOP
    IF r.column_name='CODBAI' THEN
      v_sql := 'SELECT COUNT(*) FROM '||r.table_name||' t WHERE EXISTS (SELECT 1 FROM BKP_RMD_MRG_DCOM_20260911 m WHERE m.ID_EXECUCAO=:1 AND m.TIPO=''BAI'' AND m.COD_OBSOLETO=t.CODBAI)';
    ELSE
      v_sql := 'SELECT COUNT(*) FROM '||r.table_name||' t WHERE EXISTS (SELECT 1 FROM BKP_RMD_MRG_DCOM_20260911 m WHERE m.ID_EXECUCAO=:1 AND m.TIPO=''END'' AND m.COD_OBSOLETO=t.CODEND)';
    END IF;
    EXECUTE IMMEDIATE v_sql INTO v_n USING v_id;
    IF v_n > 0 THEN
      DBMS_OUTPUT.PUT_LINE('REMANESCENTE|'||r.table_name||'|'||r.column_name||'|'||v_n);
    END IF;
  END LOOP;
END;
/
