-- AJUSTE ABA GERAL VENDAS/COMPRAS DAS PREFERENCIAS DO GOL.
UPDATE TSIPAR 
   SET INTEIRO = 0   
 WHERE (CHAVE = 'GOL-QTDEPARC' OR
        CHAVE = 'GOL-QTDEPROD' OR 
        CHAVE = 'GOL-QTDEMARC' OR 
        CHAVE = 'GOL-QTDEGRUPOS' OR 
        CHAVE = 'GOL-QTDEVENDS' OR 
        CHAVE = 'GOL-QTDEPERFIS')
   AND CODUSU = 0; COMMIT;

-- AJUSTE ABA GERAL CICLO OPERACIONAL FINANCEIRO DAS PREFERENCIAS DO GOL.   
UPDATE TSIPAR 
   SET INTEIRO  = 12 
 WHERE CHAVE    = 'GOL-PERESTMED' 
   AND CODUSU   = 0; COMMIT;

-- AJUSTE ABA MARGEM DE CONTRIBUIÇÃO (Custo a ser considerado) DAS PREFERENCIAS DO GOL.
UPDATE TSIPAR 
   SET INTEIRO  = 3 
 WHERE CHAVE    = 'GOL-TIPOCUSTO' 
   AND CODUSU   = 0; COMMIT;

-- AJUSTE ABA MARGEM DE CONTRIBUIÇÃO (% de Custo Fixo) DAS PREFERENCIAS DO GOL.
UPDATE TSIPAR 
   SET INTEIRO  = 10 
 WHERE CHAVE    = 'PERCCUSFIXO' 
   AND CODUSU   = 0; COMMIT;

-- COPIANDO GASTOS VARIAVEIS ATRIBUIDOS NA EMPRESA 1 PARA AS DEMAIS EMPRESAS.
UPDATE TGFCGM D
   SET (D.PERCCFFAB,
        D.PERCCFOUTROS,
        D.PERCCFSERVICO,
        D.PERCCOFINS,
        D.PERCCSL,
        D.PERCCUSVAR,
        D.PERCCVARSEMST,
        D.PERCMARGEM,
        D.PERCPIS,
        D.PERCIRPJ,
        D.PERCCPP) =
       (SELECT O.PERCCFFAB,
               O.PERCCFOUTROS,
               O.PERCCFSERVICO,
               O.PERCCOFINS,
               O.PERCCSL,
               O.PERCCUSVAR,
               O.PERCCVARSEMST,
               O.PERCMARGEM,
               O.PERCPIS,
               O.PERCIRPJ,
               O.PERCCPP
          FROM TGFCGM O
         WHERE O.CODEMP = 1
           AND O.ANO    = 1900
           AND O.MES    = 1)
 WHERE D.CODEMP <> 1; COMMIT;

-- AJUSTE ABA CONSOLIDACAO DE MOVIMENTOS (1 - Consolidação Padrão).
UPDATE TGFCMV 
   SET DHALTER = SYSDATE,
       FORMGASTOFIX = 0,
       INTERVALOATUALIZACAO = 24,
       PERCUSTOFIX = 10,
       QTDMESESCONSOLIDAR = 24,
       TEMCOMISSAO = 0,
       TIPDTGASTOFIX = 0,
       TIPFATPER = 0,
       TIPOCUSTO = 3 
 WHERE CODCONFIG = 1; COMMIT;