INSERT INTO TGFEXC (NUTAB, CODPROD, VLRVENDA, CODUSUALTREG, DHALTREG)
WITH LISTA AS
(   SELECT CAB.NUNOTA, CAB.DTNEG, ITE.CODPROD, ITE.VLRUNIT
    FROM TGFCAB CAB
    , TGFITE ITE
    , TGFPRO PRO
    , TGFTOP TPO
    WHERE ITE.NUNOTA = CAB.NUNOTA
    AND PRO.CODPROD = ITE.CODPROD
    AND TPO.CODTIPOPER = CAB.CODTIPOPER
    AND TPO.DHALTER = CAB.DHTIPOPER
    AND TPO.TIPATUALFIN = 'I'
    AND TPO.ATUALFIN = 1
--    AND (TPO.ATUALFIN = 1 OR TPO.CODTIPOPER = 9995)
    AND CAB.TIPMOV = 'V'
    AND ITE.VLRUNIT > 0
    AND ITE.USOPROD IN ('4','B','E','R','T','V')
    AND PRO.USOPROD NOT IN ('1','2','C','D','F','I','M','O','P')
    AND NOT EXISTS(SELECT 1 FROM TGFEXC EXC, TGFTAB TAB WHERE EXC.NUTAB = TAB.NUTAB AND TAB.CODTAB = 0 AND EXC.CODPROD = ITE.CODPROD)
)
SELECT
    *
FROM (
    SELECT (SELECT MAX(NUTAB) FROM TGFEXC), CODPROD, AVG(VLRUNIT), 0, SYSDATE
    FROM LISTA LIS
    WHERE DTNEG = (SELECT MAX(DTNEG) FROM LISTA LI1 WHERE LI1.CODPROD = LIS.CODPROD)
    GROUP BY CODPROD
) PRC