SELECT 'IDENTIDADE' TIPO,
       SYS_CONTEXT('USERENV','SESSION_USER') || '|' ||
       SYS_CONTEXT('USERENV','CURRENT_SCHEMA') || '|' ||
       SYS_CONTEXT('USERENV','SERVICE_NAME') || '|' ||
       SYS_CONTEXT('USERENV','DB_NAME') DETALHE
  FROM DUAL
UNION ALL
SELECT 'PRIVILEGIO', PRIVILEGE
  FROM SESSION_PRIVS
UNION ALL
SELECT 'ROLE', ROLE
  FROM SESSION_ROLES
UNION ALL
SELECT 'QUOTA', TABLESPACE_NAME || '|BYTES=' || TO_CHAR(BYTES) ||
       '|MAX_BYTES=' || TO_CHAR(MAX_BYTES)
  FROM USER_TS_QUOTAS
UNION ALL
SELECT 'OBJETO', OBJECT_NAME || '|' || OBJECT_TYPE || '|' || STATUS
  FROM ALL_OBJECTS
 WHERE OWNER = SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
   AND (STATUS = 'INVALID'
        OR OBJECT_NAME IN (
          'BKP_TGFPAR_NOVO','RMD_CONTROLE_OBJETOS','RMD_MAP_TSIBAI','RMD_MAP_TSIEND',
          'BKP_RMD_PAD_TSIBAI','BKP_RMD_PAD_TSIEND','BKP_RMD_GOL_TSIPAR',
          'BKP_RMD_GOL_TGFCGM','BKP_RMD_GOL_TGFCMV','BKP_RMD_PAR_MATRIZ',
          'BKP_RMD_CARD_TTKINDAGT','BKP_CLASSICMS_TGFPAR','BKP_AJNP_TGFPAR',
          'BKP_RMD_PAD_TGFPAR','BKP_RMD_PAD_TGFPRO','BKP_RMD_PAD_TGFTIT',
          'BKP_RMD_PAD_TSICID','BKP_RMD_PAD_TGFTPV'
        ))
UNION ALL
SELECT 'INVALID_SUMMARY', OBJECT_TYPE || '|QTD=' || TO_CHAR(COUNT(*))
  FROM ALL_OBJECTS
 WHERE OWNER = SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
   AND STATUS = 'INVALID'
 GROUP BY OBJECT_TYPE
UNION ALL
SELECT 'TRIGGER', TRIGGER_NAME || '|' || TABLE_NAME || '|' || STATUS || '|' || TRIGGERING_EVENT
  FROM ALL_TRIGGERS
 WHERE TABLE_OWNER = SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
   AND TABLE_NAME IN ('TSIBAI','TSIEND')
UNION ALL
SELECT 'PRIVILEGIO_OBJETO', TABLE_SCHEMA || '.' || TABLE_NAME || '|' || PRIVILEGE || '|' || GRANTEE
  FROM ALL_TAB_PRIVS
 WHERE GRANTEE IN (SYS_CONTEXT('USERENV','SESSION_USER'), SYS_CONTEXT('USERENV','CURRENT_SCHEMA'))
   AND TABLE_NAME IN ('TSIBAI','TSIEND','TGFPAR','TSICEP','TSIEMP')
 ORDER BY 1, 2
