SELECT 'PARAMETRO_HISTORICO', CHAVE || '|' || LOGICO || '|' || NVL(TO_CHAR(INTEIRO),'NULL')
  FROM TSIPAR
 WHERE CHAVE='FPUSAHISCADVINC'
UNION ALL
SELECT 'GTT', TABLE_NAME || '|TEMP=' || TEMPORARY || '|DURATION=' || NVL(DURATION,'NULL')
  FROM ALL_TABLES
 WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
   AND TABLE_NAME IN ('TEMP_TGLATS_V2','TGWENDVAZ')
UNION ALL
SELECT 'HISTORICO_TFPFGHA', 'LINHAS=' || TO_CHAR(COUNT(*)) ||
       '|MAX_NUFGHA=' || TO_CHAR(NVL(MAX(NUFGHA),0))
  FROM TFPFGHA
UNION ALL
SELECT 'ARTEFATO_EXISTENTE', OBJECT_NAME || '|' || OBJECT_TYPE || '|' || STATUS
  FROM ALL_OBJECTS
 WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
   AND OBJECT_NAME IN (
       'BKP_RMD_MVE0922_MAP','BKP_RMD_MVE0922_BAI','BKP_RMD_MVE0922_END',
       'BKP_RMD_MVE0922_DEP','BKP_RMD_MVE0922_EXC'
   )
ORDER BY 1,2
