SELECT 'TRIGGER_FILA', NAME || '|' || TYPE || '|LINHA=' || TO_CHAR(LINE) || '|' || TEXT
  FROM ALL_SOURCE
 WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
   AND NAME='TRG_TEMP_TGLATS_BI'
   AND TYPE='TRIGGER'
UNION ALL
SELECT 'DEPENDENCIA_CATALOGO', NAME || '|' || TYPE || '|' || REFERENCED_OWNER || '.' || REFERENCED_NAME || '|' || REFERENCED_TYPE
  FROM ALL_DEPENDENCIES
 WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
   AND REFERENCED_NAME='TEMP_TGLATS_V2'
   AND REFERENCED_OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
   AND TYPE<>'TRIGGER'
ORDER BY 1,2
