SELECT NAME || '|LINHA=' || TO_CHAR(LINE) || '|' || TEXT AS SOURCE_LINE
  FROM ALL_SOURCE
 WHERE OWNER = SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
   AND TYPE = 'TRIGGER'
   AND NAME IN (
       'TRG_DLT_TSIBAI','TRG_DLT_TSIEND',
       'TRG_FX_TSIBAI','TRG_FX_TSIEND',
       'TRG_TSIBAI_LOGTABOPER','TRG_TSIEND_LOGTABOPER',
       'TRG_UPD_TSIBAI_HIS_S2205','TRG_UPD_TSIEND_HIS_S2205'
   )
 ORDER BY NAME, LINE
