SELECT NAME || '|LINHA=' || TO_CHAR(LINE) || '|' || TEXT AS SOURCE_LINE
  FROM ALL_SOURCE
 WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
   AND TYPE='TRIGGER'
   AND NAME IN (
       'TRG_FX_TGFPAR','TRG_INS_UPD_TGFPAR_FLEX','TRG_TGFPAR_LOGTABOPER',
       'TRG_UPD_TGFPAR_LOG','TRG_UPD_TGFPAR',
       'TRG_FX_TSIEMP','TRG_TSIEMP_LOGTABOPER','TRG_UPD_TSIEMP_TFPRBR'
   )
 ORDER BY NAME, LINE
