SELECT DISTINCT tr.TABLE_NAME || '|' || tr.TRIGGER_NAME || '|' || tr.STATUS || '|' || tr.TRIGGERING_EVENT AS TRIGGER_INFO
  FROM ALL_TRIGGERS tr
 WHERE tr.TABLE_OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
   AND tr.STATUS='ENABLED'
   AND tr.TABLE_NAME IN (
       SELECT c.TABLE_NAME
         FROM ALL_TAB_COLUMNS c
         JOIN ALL_TABLES t ON t.OWNER=c.OWNER AND t.TABLE_NAME=c.TABLE_NAME
        WHERE c.OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
          AND c.COLUMN_NAME IN ('CODBAI','CODEND')
          AND c.TABLE_NAME NOT IN ('TSIBAI','TSIEND')
          AND t.TEMPORARY='N'
          AND SUBSTR(c.TABLE_NAME,1,4) NOT IN ('BKP_','RMD_')
       UNION
       SELECT c.TABLE_NAME
         FROM ALL_CONSTRAINTS c
         JOIN ALL_CONS_COLUMNS cc ON cc.OWNER=c.OWNER AND cc.CONSTRAINT_NAME=c.CONSTRAINT_NAME
         JOIN ALL_CONSTRAINTS p ON p.OWNER=c.R_OWNER AND p.CONSTRAINT_NAME=c.R_CONSTRAINT_NAME
         JOIN ALL_TABLES t ON t.OWNER=c.OWNER AND t.TABLE_NAME=c.TABLE_NAME
        WHERE c.OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
          AND c.CONSTRAINT_TYPE='R'
          AND p.OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
          AND p.TABLE_NAME IN ('TSIBAI','TSIEND')
          AND cc.COLUMN_NAME NOT IN ('CODBAI','CODEND')
          AND c.TABLE_NAME NOT IN ('TSIBAI','TSIEND')
          AND t.TEMPORARY='N'
          AND SUBSTR(c.TABLE_NAME,1,4) NOT IN ('BKP_','RMD_')
   )
 ORDER BY TRIGGER_INFO
