SELECT 'REFERENCIA_FONTE', OWNER || '.' || NAME || '|' || TYPE || '|LINHA=' || TO_CHAR(LINE) || '|' || TEXT
  FROM ALL_SOURCE
 WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
   AND UPPER(TEXT) LIKE '%TEMP_TGLATS_V2%'
UNION ALL
SELECT 'COLUNA_FILA', COLUMN_NAME || '|' || DATA_TYPE || '|NULLABLE=' || NULLABLE
  FROM ALL_TAB_COLUMNS
 WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
   AND TABLE_NAME='TEMP_TGLATS_V2'
UNION ALL
SELECT 'INDICE_FILA', INDEX_NAME || '|STATUS=' || STATUS || '|UNIQUE=' || UNIQUENESS
  FROM ALL_INDEXES
 WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
   AND TABLE_NAME='TEMP_TGLATS_V2'
ORDER BY 1,2
