SELECT 'FILA_ATUAL', 'LINHAS=' || TO_CHAR(COUNT(*)) FROM TEMP_TGLATS_V2
UNION ALL
SELECT 'ESTATISTICA_FILA', 'NUM_ROWS=' || NVL(TO_CHAR(NUM_ROWS),'NULL') ||
       '|BLOCKS=' || NVL(TO_CHAR(BLOCKS),'NULL') || '|LAST_ANALYZED=' ||
       NVL(TO_CHAR(LAST_ANALYZED,'YYYY-MM-DD HH24:MI:SS'),'NULL')
  FROM ALL_TABLES
 WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
   AND TABLE_NAME='TEMP_TGLATS_V2'
UNION ALL
SELECT 'FUNCAO_ATUALIZANDO', NAME || '|TIPO=' || TYPE || '|LINHA=' || TO_CHAR(LINE) || '|' || TEXT
  FROM ALL_SOURCE
 WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
   AND NAME='STP_GET_ATUALIZANDO'
   AND TYPE IN ('FUNCTION','PACKAGE','PACKAGE BODY')
UNION ALL
SELECT 'ESTADO_ATUALIZANDO', NAME || '|TIPO=' || TYPE || '|LINHA=' || TO_CHAR(LINE) || '|' || TEXT
  FROM ALL_SOURCE
 WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
   AND UPPER(TEXT) LIKE '%ATUALIZANDO%'
   AND NAME IN ('VARIAVEIS_PKG','STP_SET_ATUALIZANDO')
UNION ALL
SELECT 'USO_SETTER', NAME || '|TIPO=' || TYPE || '|LINHA=' || TO_CHAR(LINE) || '|' || TEXT
  FROM ALL_SOURCE
 WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
   AND UPPER(TEXT) LIKE '%STP_SET_ATUALIZANDO%'
   AND NAME<>'STP_SET_ATUALIZANDO'
ORDER BY 1,2
