WITH ESPERADOS(NOME) AS (
  SELECT 'RMD_MVE_MRG_20260922' FROM DUAL UNION ALL
  SELECT 'BKP_RMD_MVE_20260922_BAI' FROM DUAL UNION ALL
  SELECT 'BKP_RMD_MVE_20260922_END' FROM DUAL UNION ALL
  SELECT 'RMD_MVE_MRG_20260922_DEP' FROM DUAL UNION ALL
  SELECT 'RMD_MVE_MRG_20260922_EXC' FROM DUAL UNION ALL
  SELECT 'BKP_TGFPAR_NOVO' FROM DUAL UNION ALL
  SELECT 'BKP_TGFITE_NOVO' FROM DUAL UNION ALL
  SELECT 'TGWENDVAZ' FROM DUAL
)
SELECT e.NOME OBJETO,
       NVL(t.TEMPORARY,'AUSENTE') TEMPORARIO,
       NVL(o.STATUS,'AUSENTE') STATUS
  FROM ESPERADOS e
  LEFT JOIN ALL_TABLES t
    ON t.OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
   AND t.TABLE_NAME=e.NOME
  LEFT JOIN ALL_OBJECTS o
    ON o.OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
   AND o.OBJECT_NAME=e.NOME
   AND o.OBJECT_TYPE='TABLE'
 ORDER BY e.NOME
