SELECT 'CONTAGEM_DEPENDENCIAS',
       'COLUNAS_COD=' || TO_CHAR((
         SELECT COUNT(*) FROM ALL_TAB_COLUMNS c JOIN ALL_TABLES t
           ON t.OWNER=c.OWNER AND t.TABLE_NAME=c.TABLE_NAME
          WHERE c.OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
            AND c.COLUMN_NAME IN ('CODBAI','CODEND')
            AND c.TABLE_NAME NOT IN ('TSIBAI','TSIEND')
       )) || '|FK_PARA_PAI=' || TO_CHAR((
         SELECT COUNT(DISTINCT c.CONSTRAINT_NAME) FROM ALL_CONSTRAINTS c
         JOIN ALL_CONSTRAINTS p ON p.OWNER=c.R_OWNER AND p.CONSTRAINT_NAME=c.R_CONSTRAINT_NAME
          WHERE c.OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
            AND c.CONSTRAINT_TYPE='R' AND p.OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
            AND p.TABLE_NAME IN ('TSIBAI','TSIEND')
       ))
  FROM DUAL
UNION ALL
SELECT 'DEPENDENCIA_NAO_NUMERICA',
       c.TABLE_NAME || '.' || c.COLUMN_NAME || '|' || c.DATA_TYPE
  FROM ALL_TAB_COLUMNS c
  JOIN ALL_TABLES t ON t.OWNER=c.OWNER AND t.TABLE_NAME=c.TABLE_NAME
 WHERE c.OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
   AND c.COLUMN_NAME IN ('CODBAI','CODEND')
   AND c.TABLE_NAME NOT IN ('TSIBAI','TSIEND')
   AND c.DATA_TYPE NOT IN ('NUMBER','FLOAT','BINARY_FLOAT','BINARY_DOUBLE')
UNION ALL
SELECT 'FK_COMPOSTA', c.TABLE_NAME || '.' || c.CONSTRAINT_NAME || '|COLUNAS=' || TO_CHAR(COUNT(*))
  FROM ALL_CONSTRAINTS c
  JOIN ALL_CONS_COLUMNS cc ON cc.OWNER=c.OWNER AND cc.CONSTRAINT_NAME=c.CONSTRAINT_NAME
  JOIN ALL_CONSTRAINTS p ON p.OWNER=c.R_OWNER AND p.CONSTRAINT_NAME=c.R_CONSTRAINT_NAME
 WHERE c.OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
   AND c.CONSTRAINT_TYPE='R'
   AND p.OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
   AND p.TABLE_NAME IN ('TSIBAI','TSIEND')
 GROUP BY c.TABLE_NAME, c.CONSTRAINT_NAME
HAVING COUNT(*) > 1
UNION ALL
SELECT 'FK_OUTRO_SCHEMA', c.OWNER || '.' || c.TABLE_NAME || '.' || c.CONSTRAINT_NAME ||
       '|' || p.TABLE_NAME
  FROM ALL_CONSTRAINTS c
  JOIN ALL_CONSTRAINTS p ON p.OWNER=c.R_OWNER AND p.CONSTRAINT_NAME=c.R_CONSTRAINT_NAME
 WHERE c.CONSTRAINT_TYPE='R'
   AND p.OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
   AND p.TABLE_NAME IN ('TSIBAI','TSIEND')
   AND c.OWNER<>SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
UNION ALL
SELECT 'OBJETO_TEMPORARIO', t.TABLE_NAME || '.' || c.COLUMN_NAME || '|TEMPORARY=' || t.TEMPORARY
  FROM ALL_TAB_COLUMNS c
  JOIN ALL_TABLES t ON t.OWNER=c.OWNER AND t.TABLE_NAME=c.TABLE_NAME
 WHERE c.OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
   AND c.COLUMN_NAME IN ('CODBAI','CODEND')
   AND t.TEMPORARY='Y'
ORDER BY 1, 2
