SELECT 'OBJETO_INVALIDO' TIPO,
       OBJECT_TYPE || '|' || OBJECT_NAME || '|' || STATUS DETALHE
  FROM ALL_OBJECTS
 WHERE OWNER = SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
   AND STATUS = 'INVALID'
UNION ALL
SELECT 'ERRO_COMPILACAO',
       NAME || '|' || TYPE || '|LINHA=' || TO_CHAR(LINE) ||
       '|POS=' || TO_CHAR(POSITION) || '|' || TEXT
  FROM ALL_ERRORS
 WHERE OWNER = SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
   AND (NAME, TYPE) IN (
       SELECT OBJECT_NAME, OBJECT_TYPE
         FROM ALL_OBJECTS
        WHERE OWNER = SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
          AND STATUS = 'INVALID'
   )
UNION ALL
SELECT 'PRIVILEGIO_ATIVO', PRIVILEGE
  FROM SESSION_PRIVS
UNION ALL
SELECT 'VERSAO', PRODUCT || '|' || VERSION
  FROM PRODUCT_COMPONENT_VERSION
 WHERE PRODUCT LIKE 'Oracle Database%'
ORDER BY 1, 2
