WITH CANDIDATES AS (
  SELECT C.NUNOTA,C.CODEMP,C.NUMNOTA,C.SERIENOTA,C.DTNEG,C.DTMOV,
         C.CODPARC,C.CODTIPOPER,C.CODTIPVENDA,C.DHTIPVENDA,C.TIPMOV,T.DESCROPER,C.VLRNOTA
    FROM TGFCAB C
    JOIN TGFTOP T ON T.CODTIPOPER=C.CODTIPOPER AND T.DHALTER=C.DHTIPOPER
   WHERE T.ATUALFIN<>0
     AND C.TIPMOV<>'Z'
     AND NOT EXISTS (SELECT 1 FROM TGFFIN F WHERE F.NUNOTA=C.NUNOTA)
), N AS (
  SELECT N.NUNOTA,N.XML,
         COUNT(*) OVER(PARTITION BY N.NUNOTA) AS QTD_XML_NUNOTA,
         ROW_NUMBER() OVER(PARTITION BY N.NUNOTA ORDER BY N.ROWID) AS RN
    FROM TGFNFE N
    JOIN CANDIDATES C ON C.NUNOTA=N.NUNOTA
), X AS (
  SELECT N.NUNOTA,N.QTD_XML_NUNOTA,X.VDUP_XML,X.DVENC_XML,X.NDUP_XML
    FROM N
    OUTER APPLY XMLTABLE(
      '//*[local-name()="dup"][1]'
      PASSING XMLTYPE(N.XML)
      COLUMNS
        VDUP_XML VARCHAR2(4000) PATH '*[local-name()="vDup"][1]/text()',
        DVENC_XML VARCHAR2(4000) PATH '*[local-name()="dVenc"][1]/text()',
        NDUP_XML VARCHAR2(4000) PATH '*[local-name()="nDup"][1]/text()'
    ) X
   WHERE N.RN=1
), P AS (
  SELECT C.NUNOTA,C.CODTIPVENDA,C.DHTIPVENDA,C.TIPMOV,
         NVL(X.QTD_XML_NUNOTA,0) QTD_XML_NUNOTA,
         X.VDUP_XML,X.DVENC_XML,X.NDUP_XML,
         P.SEQUENCIA,P.CODTIPTITPAD,P.TIPRECDESP,
         COUNT(P.CODTIPVENDA) OVER(PARTITION BY C.NUNOTA) QTD_PPG_ENCONTRADAS,
         COUNT(P.CODTIPVENDA) OVER(PARTITION BY C.NUNOTA,P.SEQUENCIA) QTD_PPG_MESMA_SEQ
    FROM CANDIDATES C
    LEFT JOIN X ON X.NUNOTA=C.NUNOTA
    LEFT JOIN TGFPPG P ON P.CODTIPVENDA=C.CODTIPVENDA
), CLASSIFICADOS AS (
  SELECT P.*,
         CASE
           WHEN P.QTD_PPG_ENCONTRADAS=0 THEN 'SEM_TGFPPG'
           WHEN P.QTD_PPG_MESMA_SEQ>1 THEN 'REVISAR_DUPLICIDADE_TGFPPG'
           WHEN P.QTD_PPG_ENCONTRADAS>1 THEN 'REVISAR_MULTIPLAS_PARCELAS'
           WHEN P.QTD_XML_NUNOTA>1 THEN 'REVISAR_MULTIPLOS_XML'
           WHEN P.QTD_XML_NUNOTA=0 THEN 'SEM_VDUP_XML'
           WHEN P.VDUP_XML IS NULL THEN 'SEM_VDUP_XML'
           WHEN NOT REGEXP_LIKE(TRIM(P.VDUP_XML),'^[0-9]+([.][0-9]+)?$') THEN 'VDUP_XML_INVALIDO'
           WHEN P.NDUP_XML IS NULL THEN 'SEM_NDUP_XML'
           WHEN NOT REGEXP_LIKE(TRIM(P.NDUP_XML),'^[0-9]+$') THEN 'NDUP_XML_INVALIDO'
           WHEN NOT REGEXP_LIKE(TRIM(P.DVENC_XML),'^[0-9]{4}-[0-9]{2}-[0-9]{2}$') THEN 'DVENC_XML_INVALIDO'
           WHEN P.CODTIPTITPAD IS NULL THEN 'SEM_CODTIPTITPAD'
           WHEN P.TIPRECDESP IS NOT NULL AND UPPER(TRIM(P.TIPRECDESP)) NOT IN ('I','R','1','D','P','-1') THEN 'RECDESP_PPG_INVALIDO'
           WHEN NOT EXISTS (SELECT 1 FROM TGFTPV V WHERE V.CODTIPVENDA=P.CODTIPVENDA AND V.DHALTER=P.DHTIPVENDA) THEN 'SEM_TGFTPV_EXATA'
           WHEN NOT EXISTS (SELECT 1 FROM TGFTIT T WHERE T.CODTIPTIT=P.CODTIPTITPAD) THEN 'CODTIPTITPAD_SEM_TGFTIT'
           WHEN (SELECT COUNT(*) FROM TGFNUM N WHERE N.ARQUIVO='TGFFIN')<>1 THEN 'REVISAR_TGFNUM'
           ELSE 'APTO_PARA_VALIDACAO_FINAL'
         END AS STATUS_MAPA
    FROM P
), METRICAS AS (
  SELECT 'BASE_TOTAL' AS METRICA,TO_CHAR(COUNT(DISTINCT NUNOTA)) AS VALOR FROM CANDIDATES
  UNION ALL SELECT 'REGISTROS_TGFNFE_DOS_CANDIDATOS',TO_CHAR(COUNT(*)) FROM N
  UNION ALL SELECT 'CANDIDATOS_COM_MULTIPLOS_XML',TO_CHAR(COUNT(DISTINCT NUNOTA)) FROM N WHERE QTD_XML_NUNOTA>1
  UNION ALL SELECT 'CANDIDATOS_SEM_XML',TO_CHAR(COUNT(*)) FROM CANDIDATES C WHERE NOT EXISTS (SELECT 1 FROM N WHERE N.NUNOTA=C.NUNOTA)
  UNION ALL SELECT 'APTO_PARA_VALIDACAO_FINAL_NOTAS',TO_CHAR(COUNT(DISTINCT NUNOTA)) FROM CLASSIFICADOS WHERE STATUS_MAPA='APTO_PARA_VALIDACAO_FINAL'
  UNION ALL SELECT 'APTO_PARA_VALIDACAO_FINAL_LINHAS_MAPA',TO_CHAR(COUNT(*)) FROM CLASSIFICADOS WHERE STATUS_MAPA='APTO_PARA_VALIDACAO_FINAL'
  UNION ALL SELECT 'TGFNUM_TGFFIN_LINHAS',TO_CHAR(COUNT(*)) FROM TGFNUM WHERE ARQUIVO='TGFFIN'
  UNION ALL SELECT 'TGFNUM_TGFFIN_ULTCOD',NVL(TO_CHAR(MAX(ULTCOD)),'NULL') FROM TGFNUM WHERE ARQUIVO='TGFFIN'
  UNION ALL SELECT 'OBJETO_EXISTENTE:'||TABLE_NAME,TO_CHAR(COUNT(*))
    FROM ALL_TABLES
   WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
     AND TABLE_NAME IN ('BKP_RMD_FDUP_20260922','BKP_RMD_FDUP_20260922_PPG','BKP_RMD_FDUP_20260922_INS')
   GROUP BY TABLE_NAME
  UNION ALL SELECT 'STATUS:'||STATUS_MAPA,TO_CHAR(COUNT(*)) FROM CLASSIFICADOS GROUP BY STATUS_MAPA
)
SELECT METRICA,VALOR FROM METRICAS ORDER BY METRICA;
