WITH APTOS AS (
  SELECT M.*,
         TO_NUMBER(TRIM(M.VDUP_XML),
                   '999999999999999999D99999999',
                   'NLS_NUMERIC_CHARACTERS=''.,''') AS VLR_XML_NUM
    FROM BKP_RMD_FDUP_20260922_PPG M
   WHERE M.ID_EXECUCAO='MOVE_FDUP_20260922_01'
     AND M.STATUS_MAPA='APTO_PARA_VALIDACAO_FINAL'
), METRICAS AS (
  SELECT 'APTOS_LINHAS' AS METRICA,TO_CHAR(COUNT(*)) AS VALOR FROM APTOS
  UNION ALL SELECT 'APTOS_NOTAS_DISTINTAS',TO_CHAR(COUNT(DISTINCT NUNOTA)) FROM APTOS
  UNION ALL SELECT 'APTOS_COM_VLR_XML_NAO_POSITIVO',TO_CHAR(COUNT(*)) FROM APTOS WHERE VLR_XML_NUM<=0
  UNION ALL SELECT 'APTOS_COM_VLRNOTA_NULO',TO_CHAR(COUNT(*)) FROM APTOS WHERE VLRNOTA IS NULL
  UNION ALL SELECT 'APTOS_VLR_XML_DIVERGE_VLRNOTA_ACIMA_0_01',TO_CHAR(COUNT(*))
    FROM APTOS WHERE VLRNOTA IS NOT NULL AND ABS(VLR_XML_NUM-VLRNOTA)>0.01
  UNION ALL SELECT 'SOMA_VDUP_XML_APTOS',TO_CHAR(SUM(VLR_XML_NUM),'FM9999999999999999990D00','NLS_NUMERIC_CHARACTERS=''.,''') FROM APTOS
  UNION ALL SELECT 'SOMA_VLRNOTA_CAB_APTOS',TO_CHAR(SUM(VLRNOTA),'FM9999999999999999990D00','NLS_NUMERIC_CHARACTERS=''.,''') FROM APTOS
  UNION ALL SELECT 'APTOS_COM_TGFPPG_FORA_DE_LINHA_UNICA',TO_CHAR(COUNT(*))
    FROM APTOS WHERE QTD_PPG_ENCONTRADAS<>1 OR QTD_PPG_MESMA_SEQ<>1
  UNION ALL SELECT 'APTOS_TIPRECDESP_FORA_DOS_VALORES_ACEITOS',TO_CHAR(COUNT(*))
    FROM APTOS WHERE TIPRECDESP IS NOT NULL AND UPPER(TRIM(TIPRECDESP)) NOT IN ('I','R','1','D','P','-1')
  UNION ALL SELECT 'APTOS_CODTIPTITPAD_NULO',TO_CHAR(COUNT(*)) FROM APTOS WHERE CODTIPTITPAD IS NULL
  UNION ALL SELECT 'APTOS_TIPOVENDA_SEM_VERSAO_EXATA',TO_CHAR(COUNT(*))
    FROM APTOS M WHERE NOT EXISTS (
      SELECT 1 FROM TGFTPV V WHERE V.CODTIPVENDA=M.CODTIPVENDA AND V.DHALTER=M.DHTIPVENDA
    )
  UNION ALL SELECT 'APTOS_COM_TGFFIN_ATUAL',TO_CHAR(COUNT(*))
    FROM APTOS M WHERE EXISTS (SELECT 1 FROM TGFFIN F WHERE F.NUNOTA=M.NUNOTA)
  UNION ALL SELECT 'TGFNUM_TGFFIN_LINHAS_ATUAIS',TO_CHAR(COUNT(*)) FROM TGFNUM WHERE ARQUIVO='TGFFIN'
  UNION ALL SELECT 'TGFNUM_TGFFIN_ULTCOD_ATUAL',NVL(TO_CHAR(MAX(ULTCOD)),'NULL') FROM TGFNUM WHERE ARQUIVO='TGFFIN'
  UNION ALL SELECT 'APTOS_ULTCOD_MAPA_DIFERE_DO_ATUAL',TO_CHAR(COUNT(*))
    FROM APTOS M
   WHERE NVL(M.ULTCOD_TGFNUM_ATUAL,-1) <>
         NVL((SELECT MAX(N.ULTCOD) FROM TGFNUM N WHERE N.ARQUIVO='TGFFIN'),-1)
)
SELECT METRICA,VALOR FROM METRICAS ORDER BY METRICA;
