SELECT NUNOTA,CODEMP,NUMNOTA,SERIENOTA,CODPARC,CODTIPOPER,DESCROPER,
       QTD_XML_NUNOTA,VDUP_XML,DVENC_XML,NDUP_XML,STATUS_MAPA,OBSERVACAO
  FROM BKP_RMD_FDUP_20260922_PPG
 WHERE ID_EXECUCAO='MOVE_FDUP_20260922_01'
   AND STATUS_MAPA<>'APTO_PARA_VALIDACAO_FINAL'
 ORDER BY NUNOTA,SEQ_PPG;
