SELECT U.USERNAME AS OWNER_ATUAL,
       U.DEFAULT_TABLESPACE AS TABLESPACE_PADRAO,
       Q.TABLESPACE_NAME,
       Q.BYTES AS BYTES_UTILIZADOS,
       Q.MAX_BYTES,
       CASE
         WHEN Q.MAX_BYTES=-1 THEN 'ILIMITADA'
         WHEN Q.MAX_BYTES IS NULL THEN 'SEM_QUOTA_REGISTRADA'
         ELSE 'LIMITADA'
       END AS STATUS_QUOTA
  FROM USER_USERS U
  LEFT JOIN USER_TS_QUOTAS Q ON 1=1
 ORDER BY Q.TABLESPACE_NAME;
