SELECT USERNAME AS OWNER_OBJETOS,
       TABLESPACE_NAME,
       BYTES AS BYTES_UTILIZADOS,
       MAX_BYTES,
       CASE WHEN MAX_BYTES=-1 THEN 'ILIMITADA' ELSE 'LIMITADA' END AS STATUS_QUOTA
  FROM DBA_TS_QUOTAS
 WHERE USERNAME='SANKHYA'
 ORDER BY TABLESPACE_NAME;
