SELECT 'TGFFIN_COLUNA' AS EVIDENCIA,
       COLUMN_NAME AS CODIGO,
       NULLABLE AS STATUS,
       DATA_TYPE AS DETALHE,
       CAST(NULL AS VARCHAR2(100)) AS QTD
  FROM ALL_TAB_COLUMNS
 WHERE OWNER='SANKHYA'
   AND TABLE_NAME='TGFFIN'
   AND COLUMN_NAME='CODCTABCOINT'
UNION ALL
SELECT 'TSICTA_CODIGO_4',
       TO_CHAR(CODCTABCOINT),
       ATIVA,
       'CODEMP='||TO_CHAR(CODEMP)||', CODBCO='||TO_CHAR(CODBCO)||', '||DESCRICAO,
       CAST(NULL AS VARCHAR2(100))
  FROM TSICTA
 WHERE CODCTABCOINT=4
UNION ALL
SELECT 'TGFFIN_PADRAO_OP_1128',
       NVL(TO_CHAR(CODCTABCOINT),'NULL'),
       'CODEMP=2',
       'CODTIPOPER=1128',
       TO_CHAR(COUNT(*))
  FROM TGFFIN
 WHERE CODEMP=2
   AND CODTIPOPER=1128
 GROUP BY CODCTABCOINT
ORDER BY 1,2;
