SELECT C.OWNER AS OWNER_ORIGEM,
       C.TABLE_NAME AS TABELA_ORIGEM,
       CC.COLUMN_NAME AS COLUNA_ORIGEM,
       RC.OWNER AS OWNER_REFERENCIADO,
       RC.TABLE_NAME AS TABELA_REFERENCIADA,
       RCC.COLUMN_NAME AS COLUNA_REFERENCIADA
  FROM ALL_CONSTRAINTS C
  JOIN ALL_CONS_COLUMNS CC
    ON CC.OWNER=C.OWNER AND CC.CONSTRAINT_NAME=C.CONSTRAINT_NAME
  JOIN ALL_CONSTRAINTS RC
    ON RC.OWNER=C.R_OWNER AND RC.CONSTRAINT_NAME=C.R_CONSTRAINT_NAME
  JOIN ALL_CONS_COLUMNS RCC
    ON RCC.OWNER=RC.OWNER AND RCC.CONSTRAINT_NAME=RC.CONSTRAINT_NAME
 WHERE C.OWNER='SANKHYA'
   AND C.TABLE_NAME='TGFFIN'
   AND C.CONSTRAINT_TYPE='R'
   AND CC.COLUMN_NAME='CODCTABCOINT'
   AND RCC.POSITION=CC.POSITION
 ORDER BY C.CONSTRAINT_NAME;
