WITH CONTAS_MAPA AS (
  SELECT CODEMP, CODCTABCOINT, COUNT(*) AS QTD_NOTAS
    FROM BKP_RMD_FDUP_20260922_PPG
   WHERE ID_EXECUCAO='MOVE_FDUP_20260922_01'
     AND STATUS_MAPA='APTO_PARA_VALIDACAO_FINAL'
   GROUP BY CODEMP, CODCTABCOINT
)
SELECT 'MAPEADA' AS CATEGORIA,
       TO_CHAR(M.CODEMP) AS CODEMP,
       TO_CHAR(M.CODCTABCOINT) AS CODCTABCOINT,
       TO_CHAR(A.CODBCO) AS CODBCO,
       A.DESCRICAO,
       A.ATIVA,
       TO_CHAR(M.QTD_NOTAS) AS QTD_NOTAS
  FROM CONTAS_MAPA M
  LEFT JOIN TSICTA A ON A.CODCTABCOINT=M.CODCTABCOINT
UNION ALL
SELECT 'CONTA_ATIVA',
       TO_CHAR(A.CODEMP),
       TO_CHAR(A.CODCTABCOINT),
       TO_CHAR(A.CODBCO),
       A.DESCRICAO,
       A.ATIVA,
       CAST(NULL AS VARCHAR2(20))
  FROM TSICTA A
 WHERE A.ATIVA='S'
   AND A.CODEMP IN (1,2)
 ORDER BY 2,1,3;
