SELECT DISTINCT F.NUFIN,F.NUNOTA,F.CODTIPOPER,
       (SELECT MAX(T.DESCROPER) FROM TGFTOP T WHERE T.CODTIPOPER=F.CODTIPOPER) AS DESCROPER
  FROM TGFFIN F
 WHERE NOT EXISTS (
   SELECT 1 FROM TGFCAB C WHERE C.NUNOTA=F.NUNOTA
 )
 ORDER BY F.NUFIN,F.NUNOTA;
