SET DEFINE ON
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
ACCEPT P_ID_EXECUCAO CHAR PROMPT 'ID da execucao RMD_CARD_: '
DECLARE
 v_count NUMBER;v_cols CLOB;v_sql CLOB;
BEGIN
 SELECT COUNT(*) INTO v_count FROM BKP_RMD_CARD_TTKINDAGT WHERE ID_EXECUCAO='&&P_ID_EXECUCAO';
 IF v_count<>1 THEN RAISE_APPLICATION_ERROR(-20313,'Backup unico dos cards nao encontrado.');END IF;
 SELECT LISTAGG(COLUMN_NAME,',') WITHIN GROUP(ORDER BY COLUMN_ID) INTO v_cols
   FROM ALL_TAB_COLUMNS WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND TABLE_NAME='TTKINDAGT';
 DELETE FROM TTKINDAGT WHERE SEQUENCIA=1;
 v_sql:='INSERT INTO TTKINDAGT ('||v_cols||') SELECT '||v_cols||
       ||' FROM BKP_RMD_CARD_TTKINDAGT WHERE ID_EXECUCAO=:1';
 EXECUTE IMMEDIATE v_sql USING '&&P_ID_EXECUCAO';
 IF SQL%ROWCOUNT<>1 THEN RAISE_APPLICATION_ERROR(-20314,'Restauracao dos cards divergente.');END IF;
 COMMIT;DBMS_OUTPUT.PUT_LINE('CARDS_REVERTIDOS=1');
EXCEPTION WHEN OTHERS THEN ROLLBACK;RAISE;END;
/
UNDEFINE P_ID_EXECUCAO
