-- Reverte a padronizacao de TSICID da execucao informada.
SET DEFINE ON
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
ACCEPT P_ID_EXECUCAO CHAR PROMPT 'ID da execucao RMD_CID_: '
DECLARE v_bkp NUMBER;v_upd NUMBER;BEGIN SELECT COUNT(*) INTO v_bkp FROM BKP_RMD_PAD_TSICID WHERE ID_EXECUCAO='&&P_ID_EXECUCAO';IF v_bkp=0 THEN RAISE_APPLICATION_ERROR(-20346,'Backup de TSICID nao encontrado.');END IF;MERGE INTO TSICID T USING(SELECT * FROM BKP_RMD_PAD_TSICID WHERE ID_EXECUCAO='&&P_ID_EXECUCAO') B ON(T.ROWID=CHARTOROWID(B.ROWID_ORIGINAL)) WHEN MATCHED THEN UPDATE SET T.NOMECID=B.NOMECID,T.DESCRICAOCORREIO=B.DESCRICAOCORREIO;v_upd:=SQL%ROWCOUNT;IF v_upd<>v_bkp THEN RAISE_APPLICATION_ERROR(-20347,'Rollback TSICID divergente.');END IF;COMMIT;DBMS_OUTPUT.PUT_LINE('REGISTROS_REVERTIDOS='||v_upd);EXCEPTION WHEN OTHERS THEN ROLLBACK;RAISE;END;
/
UNDEFINE P_ID_EXECUCAO
