SET DEFINE ON
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
ACCEPT P_ID_EXECUCAO CHAR PROMPT 'ID da execucao RMD_G848_: '
DECLARE v NUMBER;BEGIN
 UPDATE TSIIMP I SET LISTA1=(SELECT B.LISTA1_ANTES FROM BKP_RMD_13_TSIIMP B WHERE B.ID_EXECUCAO='&&P_ID_EXECUCAO' AND B.CODREL=I.CODREL) WHERE I.CODREL=848 AND EXISTS(SELECT 1 FROM BKP_RMD_13_TSIIMP B WHERE B.ID_EXECUCAO='&&P_ID_EXECUCAO' AND B.CODREL=I.CODREL);
 v:=SQL%ROWCOUNT;IF v<>1 THEN RAISE_APPLICATION_ERROR(-20342,'Backup unico da Analise 848 nao encontrado.');END IF;
 COMMIT;DBMS_OUTPUT.PUT_LINE('ANALISE_GIRO_848_REVERTIDA=1');
EXCEPTION WHEN OTHERS THEN ROLLBACK;RAISE;END;
/
UNDEFINE P_ID_EXECUCAO
