-- Reversao autocontida da fase 29/30 RIOSLTDAPRD.
-- Restaura pais ausentes e todos os dependentes registrados na trilha.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

DECLARE
  v_owner VARCHAR2(128) := SYS_CONTEXT('USERENV','CURRENT_SCHEMA');
  v_id VARCHAR2(40) := 'RMD_RIO_2930_20260923_01';
  v_map VARCHAR2(128) := 'RMD_RIO_2930_MAP';
  v_bkp_bai VARCHAR2(128) := 'RMD_RIO_2930_BAI';
  v_bkp_end VARCHAR2(128) := 'RMD_RIO_2930_END';
  v_dep VARCHAR2(128) := 'RMD_RIO_2930_DEP';
  v_exc VARCHAR2(128) := 'RMD_RIO_2930_EXC';
  v_sql VARCHAR2(32767);
  v_cols VARCHAR2(32767);
  v_sel VARCHAR2(32767);
  v_n NUMBER;
  FUNCTION cols(p_table VARCHAR2,p_prefix VARCHAR2) RETURN VARCHAR2 IS v_out VARCHAR2(32767);
  BEGIN
    SELECT LISTAGG(p_prefix||column_name,',') WITHIN GROUP (ORDER BY column_id)
      INTO v_out FROM all_tab_columns
     WHERE owner=v_owner AND table_name=p_table AND column_name<>'ID_EXECUCAO';
    RETURN v_out;
  END;
BEGIN
  EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM '||v_map||' WHERE ID_EXECUCAO=:1' INTO v_n USING v_id;
  IF v_n=0 THEN RAISE_APPLICATION_ERROR(-20370,'Mapa persistente ausente'); END IF;
  EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM '||v_bkp_bai||' WHERE ID_EXECUCAO=:1' INTO v_n USING v_id;
  IF v_n=0 THEN RAISE_APPLICATION_ERROR(-20371,'Backup BAI ausente'); END IF;
  EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM '||v_bkp_end||' WHERE ID_EXECUCAO=:1' INTO v_n USING v_id;
  IF v_n=0 THEN RAISE_APPLICATION_ERROR(-20372,'Backup END ausente'); END IF;

  v_cols := cols('TSIBAI','');
  v_sel := cols('TSIBAI','b.');
  v_sql := 'INSERT INTO TSIBAI ('||v_cols||') SELECT '||v_sel||' FROM '||v_bkp_bai||' b WHERE b.ID_EXECUCAO=:1 AND NOT EXISTS (SELECT 1 FROM TSIBAI t WHERE t.CODBAI=b.CODBAI)';
  EXECUTE IMMEDIATE v_sql USING v_id;
  DBMS_OUTPUT.PUT_LINE('PAIS_RESTAURADOS|TSIBAI|'||SQL%ROWCOUNT);

  v_cols := cols('TSIEND','');
  v_sel := cols('TSIEND','b.');
  v_sql := 'INSERT INTO TSIEND ('||v_cols||') SELECT '||v_sel||' FROM '||v_bkp_end||' b WHERE b.ID_EXECUCAO=:1 AND NOT EXISTS (SELECT 1 FROM TSIEND t WHERE t.CODEND=b.CODEND)';
  EXECUTE IMMEDIATE v_sql USING v_id;
  DBMS_OUTPUT.PUT_LINE('PAIS_RESTAURADOS|TSIEND|'||SQL%ROWCOUNT);

  FOR r IN (
    SELECT DISTINCT TABLE_NAME,COLUMN_NAME
      FROM RMD_RIO_2930_DEP
     WHERE ID_EXECUCAO=v_id
     ORDER BY TABLE_NAME,COLUMN_NAME
  ) LOOP
    v_sql := 'UPDATE '||r.TABLE_NAME||' t SET t.'||r.COLUMN_NAME||'=(SELECT d.OLD_VALUE FROM '||v_dep||' d WHERE d.ID_EXECUCAO=:1 AND d.TABLE_NAME=:2 AND d.COLUMN_NAME=:3 AND d.RID=ROWIDTOCHAR(t.ROWID) AND d.NEW_VALUE=t.'||r.COLUMN_NAME||') WHERE EXISTS (SELECT 1 FROM '||v_dep||' d WHERE d.ID_EXECUCAO=:1 AND d.TABLE_NAME=:2 AND d.COLUMN_NAME=:3 AND d.RID=ROWIDTOCHAR(t.ROWID) AND d.NEW_VALUE=t.'||r.COLUMN_NAME||')';
    EXECUTE IMMEDIATE v_sql USING v_id,r.TABLE_NAME,r.COLUMN_NAME,v_id,r.TABLE_NAME,r.COLUMN_NAME;
    DBMS_OUTPUT.PUT_LINE('DEPENDENTES_RESTAURADOS|'||r.TABLE_NAME||'|'||r.COLUMN_NAME||'|'||SQL%ROWCOUNT);
  END LOOP;
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('STATUS=ROLLBACK_29_30_EXECUTADO; ID_EXECUCAO='||v_id);
EXCEPTION WHEN OTHERS THEN ROLLBACK; RAISE;
END;
/
