-- CASA DAS ESSENCIAS - objetos persistentes de auditoria da fase R03.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

DECLARE
  v_n NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_n FROM ALL_TABLES
   WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND TABLE_NAME='RMD_CASA_2930_R03_DEP';
  IF v_n=0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE RMD_CASA_2930_R03_DEP ('||
      'ID_EXECUCAO VARCHAR2(50),TABLE_NAME VARCHAR2(128),COLUMN_NAME VARCHAR2(128),'||
      'RID VARCHAR2(30),OLD_VALUE NUMBER,NEW_VALUE NUMBER,DTLOG TIMESTAMP)';
  END IF;
  SELECT COUNT(*) INTO v_n FROM ALL_TABLES
   WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND TABLE_NAME='RMD_CASA_2930_R03_EXC';
  IF v_n=0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE RMD_CASA_2930_R03_EXC ('||
      'ID_EXECUCAO VARCHAR2(50),TABLE_NAME VARCHAR2(128),COLUMN_NAME VARCHAR2(128),'||
      'MENSAGEM VARCHAR2(1000),DTLOG TIMESTAMP)';
  END IF;
  DBMS_OUTPUT.PUT_LINE('AUDITORIA_29_30_R03=CRIADA_OU_EXISTENTE');
END;
/
