-- CASA DAS ESSENCIAS - fase 29/30 R03: mapa e backups declarados.
-- Usa somente DDL explicito e DML dinamico; nao usa CTAS.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

DECLARE
  v_id VARCHAR2(50) := 'RMD_CASA_2930_MRG_20260923_R03';
  v_sql VARCHAR2(32767);
  v_map VARCHAR2(128) := 'RMD_CASA_2930_R03_MAP';
  v_bkp_bai VARCHAR2(128) := 'RMD_CASA_2930_R03_BAI_BKP';
  v_bkp_end VARCHAR2(128) := 'RMD_CASA_2930_R03_END_BKP';
  v_map_count NUMBER;
  v_bkp_bai_count NUMBER;
  v_bkp_end_count NUMBER;

  PROCEDURE ddl(p_sql VARCHAR2) IS
  BEGIN
    BEGIN
      EXECUTE IMMEDIATE p_sql;
    EXCEPTION
      WHEN OTHERS THEN
        IF SQLCODE <> -955 THEN RAISE; END IF;
    END;
  END;

  FUNCTION norm(p_col VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN 'REGEXP_REPLACE(TRIM(TRANSLATE(UPPER('||p_col||'),'||
      '''ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇáàâãäéèêëíìîïóòôõöúùûüçÃãÕõÂâÊêÎîÔôÛû'''||','||
      '''AAAAAEEEEIIIIOOOOOUUUUCAAAAAEEEEIIIIOOOOOUUUUCAAAOOAAEIIOOUU'''||
      ')),'' {2,}'','' '')';
  END;
BEGIN
  ddl('CREATE TABLE '||v_map||' ('||
      'ID_EXECUCAO VARCHAR2(50),TIPO VARCHAR2(4),COD_OBSOLETO NUMBER,'||
      'COD_MANTIDO NUMBER,CHAVE_NORM VARCHAR2(4000),CHAVE_CONTEXT VARCHAR2(4000),'||
      'CRITERIO VARCHAR2(100),DTLOG TIMESTAMP)');
  ddl('CREATE TABLE '||v_bkp_bai||' ('||
      'ID_EXECUCAO VARCHAR2(50),DT_BACKUP TIMESTAMP,CODBAI NUMBER(10),'||
      'NOMEBAI VARCHAR2(60),CODREG NUMBER(10),DTALTER DATE,'||
      'DESCRICAOCORREIO VARCHAR2(60),NUVERSAO NUMBER(19),ATUNUVERSAO CHAR(1))');
  ddl('CREATE TABLE '||v_bkp_end||' ('||
      'ID_EXECUCAO VARCHAR2(50),DT_BACKUP TIMESTAMP,CODEND NUMBER(10),'||
      'NOMEEND VARCHAR2(60),TIPO VARCHAR2(8),DTALTER DATE,'||
      'DESCRICAOCORREIO VARCHAR2(60),CODLOGRADOURO VARCHAR2(4),'||
      'NUVERSAO NUMBER(19),ATUNUVERSAO CHAR(1))');

  EXECUTE IMMEDIATE 'DELETE FROM '||v_map||' WHERE ID_EXECUCAO=:1' USING v_id;
  EXECUTE IMMEDIATE 'DELETE FROM '||v_bkp_bai||' WHERE ID_EXECUCAO=:1' USING v_id;
  EXECUTE IMMEDIATE 'DELETE FROM '||v_bkp_end||' WHERE ID_EXECUCAO=:1' USING v_id;

  v_sql := 'INSERT INTO '||v_map||
    '(ID_EXECUCAO,TIPO,COD_OBSOLETO,COD_MANTIDO,CHAVE_NORM,CHAVE_CONTEXT,CRITERIO,DTLOG) '||
    'SELECT :1,''BAI'',CODBAI,KEEP_ID,NORM,''CODREG=''||TO_CHAR(CODREG),'||
    '''MESMO_CODREG_E_MENOR_CODBAI'',SYSTIMESTAMP FROM ('||
    'SELECT CODBAI,CODREG,NORM,MIN(CODBAI) OVER(PARTITION BY CODREG,NORM) KEEP_ID,'||
    'COUNT(*) OVER(PARTITION BY CODREG,NORM) QTD FROM ('||
    'SELECT CODBAI,CODREG,'||norm('NOMEBAI')||' NORM FROM TSIBAI)) '||
    'WHERE QTD>1 AND CODBAI<>KEEP_ID';
  EXECUTE IMMEDIATE v_sql USING v_id;

  v_sql := 'INSERT INTO '||v_map||
    '(ID_EXECUCAO,TIPO,COD_OBSOLETO,COD_MANTIDO,CHAVE_NORM,CHAVE_CONTEXT,CRITERIO,DTLOG) '||
    'SELECT :1,''END'',CODEND,KEEP_ID,NORM,'||
    '''TIPO=''||NVL(TIPO,''<NULL>'')||'';CODLOGRADOURO=''||NVL(CODLOGRADOURO,''<NULL>''),'||
    '''MESMO_TIPO_CODLOGRADOURO_E_MENOR_CODEND'',SYSTIMESTAMP FROM ('||
    'SELECT CODEND,TIPO,CODLOGRADOURO,NORM,'||
    'MIN(CODEND) OVER(PARTITION BY TIPO,NORM,NVL(CODLOGRADOURO,''<NULL>'')) KEEP_ID,'||
    'COUNT(*) OVER(PARTITION BY TIPO,NORM,NVL(CODLOGRADOURO,''<NULL>'')) QTD FROM ('||
    'SELECT CODEND,TIPO,CODLOGRADOURO,'||norm('NOMEEND')||' NORM FROM TSIEND)) '||
    'WHERE QTD>1 AND CODEND<>KEEP_ID';
  EXECUTE IMMEDIATE v_sql USING v_id;

  EXECUTE IMMEDIATE 'INSERT INTO '||v_bkp_bai||
    '(ID_EXECUCAO,DT_BACKUP,CODBAI,NOMEBAI,CODREG,DTALTER,DESCRICAOCORREIO,NUVERSAO,ATUNUVERSAO) '||
    'SELECT :1,SYSTIMESTAMP,b.CODBAI,b.NOMEBAI,b.CODREG,b.DTALTER,b.DESCRICAOCORREIO,b.NUVERSAO,b.ATUNUVERSAO '||
    'FROM TSIBAI b WHERE b.CODBAI IN ('||
    'SELECT COD_MANTIDO FROM '||v_map||' WHERE ID_EXECUCAO=:1 AND TIPO=''BAI'' '||
    'UNION SELECT COD_OBSOLETO FROM '||v_map||' WHERE ID_EXECUCAO=:1 AND TIPO=''BAI'')'
    USING v_id,v_id,v_id;
  EXECUTE IMMEDIATE 'INSERT INTO '||v_bkp_end||
    '(ID_EXECUCAO,DT_BACKUP,CODEND,NOMEEND,TIPO,DTALTER,DESCRICAOCORREIO,CODLOGRADOURO,NUVERSAO,ATUNUVERSAO) '||
    'SELECT :1,SYSTIMESTAMP,e.CODEND,e.NOMEEND,e.TIPO,e.DTALTER,e.DESCRICAOCORREIO,e.CODLOGRADOURO,e.NUVERSAO,e.ATUNUVERSAO '||
    'FROM TSIEND e WHERE e.CODEND IN ('||
    'SELECT COD_MANTIDO FROM '||v_map||' WHERE ID_EXECUCAO=:1 AND TIPO=''END'' '||
    'UNION SELECT COD_OBSOLETO FROM '||v_map||' WHERE ID_EXECUCAO=:1 AND TIPO=''END'')'
    USING v_id,v_id,v_id;

  EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM '||v_map||' WHERE ID_EXECUCAO=:1' INTO v_map_count USING v_id;
  EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM '||v_bkp_bai||' WHERE ID_EXECUCAO=:1' INTO v_bkp_bai_count USING v_id;
  EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM '||v_bkp_end||' WHERE ID_EXECUCAO=:1' INTO v_bkp_end_count USING v_id;
  DBMS_OUTPUT.PUT_LINE('ID_EXECUCAO='||v_id);
  DBMS_OUTPUT.PUT_LINE('MAPA_LINHAS='||v_map_count||'; BACKUP_BAI='||v_bkp_bai_count||'; BACKUP_END='||v_bkp_end_count);
  DBMS_OUTPUT.PUT_LINE('STATUS=MAPA_E_BACKUPS_PERSISTIDOS_SEM_REDIRECIONAMENTO');
  COMMIT;
EXCEPTION WHEN OTHERS THEN
  ROLLBACK;
  RAISE;
END;
/
