-- CASA DAS ESSENCIAS - fase 1 de 29/30.
-- Merge controlado com contexto: bairros por CODREG; enderecos por TIPO,
-- CODLOGRADOURO e nome normalizado. Nao exclui pais obsoletos nesta fase.
-- Backups, mapa, auditoria de dependencias e excecoes sao persistentes.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

DECLARE
  v_owner VARCHAR2(128) := SYS_CONTEXT('USERENV','CURRENT_SCHEMA');
  v_id VARCHAR2(50) := 'RMD_CASA_2930_MRG_20260923_R01';
  v_sql VARCHAR2(32767);
  v_n NUMBER;
  v_ref NUMBER := 0;
  v_map VARCHAR2(128) := 'RMD_CASA_2930_R01_MAP';
  v_bkp_bai VARCHAR2(128) := 'RMD_CASA_2930_R01_BAI_BKP';
  v_bkp_end VARCHAR2(128) := 'RMD_CASA_2930_R01_END_BKP';
  v_dep VARCHAR2(128) := 'RMD_CASA_2930_R01_DEP';
  v_exc VARCHAR2(128) := 'RMD_CASA_2930_R01_EXC';
  v_map_count NUMBER;
  v_bkp_bai_count NUMBER;
  v_bkp_end_count NUMBER;
  v_dep_count NUMBER;
  v_exc_count NUMBER;
  v_composite_fk NUMBER;
  v_external_fk NUMBER;
  v_non_numeric NUMBER;

  PROCEDURE ddl(p_sql VARCHAR2) IS
  BEGIN
    BEGIN
      EXECUTE IMMEDIATE p_sql;
    EXCEPTION
      WHEN OTHERS THEN
        IF SQLCODE <> -955 THEN RAISE; END IF;
    END;
  END;

  FUNCTION norm(p_col VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN 'REGEXP_REPLACE(TRIM(TRANSLATE(UPPER('||p_col||'),'||
      '''ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇáàâãäéèêëíìîïóòôõöúùûüçÃãÕõÂâÊêÎîÔôÛû'''||','||
      '''AAAAAEEEEIIIIOOOOOUUUUCAAAAAEEEEIIIIOOOOOUUUUCAAAOOAAEIIOOUU'''||
      ')),'' {2,}'','' '')';
  END;

  PROCEDURE log_exc(p_tab VARCHAR2,p_col VARCHAR2,p_msg VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE 'INSERT INTO '||v_exc||
      '(ID_EXECUCAO,TABLE_NAME,COLUMN_NAME,MENSAGEM,DTLOG) VALUES (:1,:2,:3,:4,SYSTIMESTAMP)'
      USING v_id,p_tab,p_col,SUBSTR(p_msg,1,1000);
  END;
BEGIN
  SELECT COUNT(*) INTO v_composite_fk
    FROM (
      SELECT c.OWNER,c.CONSTRAINT_NAME
        FROM ALL_CONSTRAINTS c
        JOIN ALL_CONS_COLUMNS cc ON cc.OWNER=c.OWNER AND cc.CONSTRAINT_NAME=c.CONSTRAINT_NAME
        JOIN ALL_CONSTRAINTS p ON p.OWNER=c.R_OWNER AND p.CONSTRAINT_NAME=c.R_CONSTRAINT_NAME
       WHERE c.OWNER=v_owner AND c.CONSTRAINT_TYPE='R'
         AND p.OWNER=v_owner AND p.TABLE_NAME IN ('TSIBAI','TSIEND')
       GROUP BY c.OWNER,c.CONSTRAINT_NAME
      HAVING COUNT(*)>1
    );
  IF v_composite_fk<>0 THEN
    RAISE_APPLICATION_ERROR(-20380,'FK composta detectada; merge bloqueado.');
  END IF;

  SELECT COUNT(*) INTO v_external_fk
    FROM ALL_CONSTRAINTS c
    JOIN ALL_CONSTRAINTS p ON p.OWNER=c.R_OWNER AND p.CONSTRAINT_NAME=c.R_CONSTRAINT_NAME
   WHERE c.CONSTRAINT_TYPE='R'
     AND p.OWNER=v_owner AND p.TABLE_NAME IN ('TSIBAI','TSIEND')
     AND c.OWNER<>v_owner;
  IF v_external_fk<>0 THEN
    RAISE_APPLICATION_ERROR(-20381,'FK de outro schema detectada; merge bloqueado.');
  END IF;

  SELECT COUNT(*) INTO v_non_numeric
    FROM (
      SELECT c.TABLE_NAME,c.COLUMN_NAME
        FROM ALL_TAB_COLUMNS c
        JOIN ALL_TABLES t ON t.OWNER=c.OWNER AND t.TABLE_NAME=c.TABLE_NAME
       WHERE c.OWNER=v_owner AND t.TEMPORARY='N'
         AND c.COLUMN_NAME IN ('CODBAI','CODEND')
         AND c.TABLE_NAME NOT IN ('TSIBAI','TSIEND')
         AND c.TABLE_NAME NOT LIKE 'BKP\_%' ESCAPE '\'
         AND c.TABLE_NAME NOT LIKE 'RMD\_%' ESCAPE '\'
         AND c.DATA_TYPE NOT IN ('NUMBER','FLOAT','BINARY_FLOAT','BINARY_DOUBLE')
      UNION
      SELECT cc.TABLE_NAME,cc.COLUMN_NAME
        FROM ALL_CONSTRAINTS c
        JOIN ALL_CONS_COLUMNS cc ON cc.OWNER=c.OWNER AND cc.CONSTRAINT_NAME=c.CONSTRAINT_NAME
        JOIN ALL_CONSTRAINTS p ON p.OWNER=c.R_OWNER AND p.CONSTRAINT_NAME=c.R_CONSTRAINT_NAME
        JOIN ALL_TAB_COLUMNS x ON x.OWNER=cc.OWNER AND x.TABLE_NAME=cc.TABLE_NAME AND x.COLUMN_NAME=cc.COLUMN_NAME
        JOIN ALL_TABLES t ON t.OWNER=cc.OWNER AND t.TABLE_NAME=cc.TABLE_NAME
       WHERE c.OWNER=v_owner AND c.CONSTRAINT_TYPE='R'
         AND p.OWNER=v_owner AND p.TABLE_NAME IN ('TSIBAI','TSIEND')
         AND t.TEMPORARY='N'
         AND cc.COLUMN_NAME NOT IN ('CODBAI','CODEND')
         AND c.TABLE_NAME NOT LIKE 'BKP\_%' ESCAPE '\'
         AND c.TABLE_NAME NOT LIKE 'RMD\_%' ESCAPE '\'
         AND x.DATA_TYPE NOT IN ('NUMBER','FLOAT','BINARY_FLOAT','BINARY_DOUBLE')
    );
  IF v_non_numeric<>0 THEN
    RAISE_APPLICATION_ERROR(-20382,'Dependencia de bairro/endereco nao numerica detectada.');
  END IF;

  ddl('CREATE TABLE '||v_map||' ('||
      'ID_EXECUCAO VARCHAR2(50),TIPO VARCHAR2(4),COD_OBSOLETO NUMBER,'||
      'COD_MANTIDO NUMBER,CHAVE_NORM VARCHAR2(4000),CHAVE_CONTEXT VARCHAR2(4000),'||
      'CRITERIO VARCHAR2(100),DTLOG TIMESTAMP)');
  ddl('CREATE TABLE '||v_bkp_bai||' AS SELECT CAST(NULL AS VARCHAR2(50)) ID_EXECUCAO,'||
      'CAST(NULL AS TIMESTAMP) DT_BACKUP,b.* FROM TSIBAI b WHERE 1=0');
  ddl('CREATE TABLE '||v_bkp_end||' AS SELECT CAST(NULL AS VARCHAR2(50)) ID_EXECUCAO,'||
      'CAST(NULL AS TIMESTAMP) DT_BACKUP,e.* FROM TSIEND e WHERE 1=0');
  ddl('CREATE TABLE '||v_dep||' ('||
      'ID_EXECUCAO VARCHAR2(50),TABLE_NAME VARCHAR2(128),COLUMN_NAME VARCHAR2(128),'||
      'RID VARCHAR2(30),OLD_VALUE NUMBER,NEW_VALUE NUMBER,DTLOG TIMESTAMP)');
  ddl('CREATE TABLE '||v_exc||' ('||
      'ID_EXECUCAO VARCHAR2(50),TABLE_NAME VARCHAR2(128),COLUMN_NAME VARCHAR2(128),'||
      'MENSAGEM VARCHAR2(1000),DTLOG TIMESTAMP)');

  EXECUTE IMMEDIATE 'DELETE FROM '||v_map||' WHERE ID_EXECUCAO=:1' USING v_id;
  EXECUTE IMMEDIATE 'DELETE FROM '||v_dep||' WHERE ID_EXECUCAO=:1' USING v_id;
  EXECUTE IMMEDIATE 'DELETE FROM '||v_exc||' WHERE ID_EXECUCAO=:1' USING v_id;

  v_sql := 'INSERT INTO '||v_map||
    '(ID_EXECUCAO,TIPO,COD_OBSOLETO,COD_MANTIDO,CHAVE_NORM,CHAVE_CONTEXT,CRITERIO,DTLOG) '||
    'SELECT :1,''BAI'',CODBAI,KEEP_ID,NORM,''CODREG=''||TO_CHAR(CODREG),'||
    '''MESMO_CODREG_E_MENOR_CODBAI'',SYSTIMESTAMP FROM ('||
    'SELECT CODBAI,CODREG,NORM,MIN(CODBAI) OVER(PARTITION BY CODREG,NORM) KEEP_ID,'||
    'COUNT(*) OVER(PARTITION BY CODREG,NORM) QTD FROM ('||
    'SELECT CODBAI,CODREG,'||norm('NOMEBAI')||' NORM FROM TSIBAI)) '||
    'WHERE QTD>1 AND CODBAI<>KEEP_ID';
  EXECUTE IMMEDIATE v_sql USING v_id;

  v_sql := 'INSERT INTO '||v_map||
    '(ID_EXECUCAO,TIPO,COD_OBSOLETO,COD_MANTIDO,CHAVE_NORM,CHAVE_CONTEXT,CRITERIO,DTLOG) '||
    'SELECT :1,''END'',CODEND,KEEP_ID,NORM,'||
    '''TIPO=''||NVL(TIPO,''<NULL>'')||'';CODLOGRADOURO=''||NVL(CODLOGRADOURO,''<NULL>''),'||
    '''MESMO_TIPO_CODLOGRADOURO_E_MENOR_CODEND'',SYSTIMESTAMP FROM ('||
    'SELECT CODEND,TIPO,CODLOGRADOURO,NORM,'||
    'MIN(CODEND) OVER(PARTITION BY TIPO,NORM,NVL(CODLOGRADOURO,''<NULL>'')) KEEP_ID,'||
    'COUNT(*) OVER(PARTITION BY TIPO,NORM,NVL(CODLOGRADOURO,''<NULL>'')) QTD FROM ('||
    'SELECT CODEND,TIPO,CODLOGRADOURO,'||norm('NOMEEND')||' NORM FROM TSIEND)) '||
    'WHERE QTD>1 AND CODEND<>KEEP_ID';
  EXECUTE IMMEDIATE v_sql USING v_id;

  EXECUTE IMMEDIATE 'INSERT INTO '||v_bkp_bai||
    ' SELECT :1,SYSTIMESTAMP,b.* FROM TSIBAI b WHERE b.CODBAI IN ('||
    'SELECT COD_MANTIDO FROM '||v_map||' WHERE ID_EXECUCAO=:1 AND TIPO=''BAI'' '||
    'UNION SELECT COD_OBSOLETO FROM '||v_map||' WHERE ID_EXECUCAO=:1 AND TIPO=''BAI'')'
    USING v_id,v_id,v_id;
  EXECUTE IMMEDIATE 'INSERT INTO '||v_bkp_end||
    ' SELECT :1,SYSTIMESTAMP,e.* FROM TSIEND e WHERE e.CODEND IN ('||
    'SELECT COD_MANTIDO FROM '||v_map||' WHERE ID_EXECUCAO=:1 AND TIPO=''END'' '||
    'UNION SELECT COD_OBSOLETO FROM '||v_map||' WHERE ID_EXECUCAO=:1 AND TIPO=''END'')'
    USING v_id,v_id,v_id;

  FOR r IN (
    SELECT DISTINCT c.TABLE_NAME,c.COLUMN_NAME
      FROM ALL_TAB_COLUMNS c
      JOIN ALL_TABLES t ON t.OWNER=c.OWNER AND t.TABLE_NAME=c.TABLE_NAME
     WHERE c.OWNER=v_owner AND t.TEMPORARY='N'
       AND c.COLUMN_NAME IN ('CODBAI','CODEND')
       AND c.DATA_TYPE IN ('NUMBER','FLOAT','BINARY_FLOAT','BINARY_DOUBLE')
       AND c.TABLE_NAME NOT IN ('TSIBAI','TSIEND',v_map,v_bkp_bai,v_bkp_end,v_dep,v_exc)
       AND c.TABLE_NAME NOT LIKE 'BKP\_%' ESCAPE '\'
       AND c.TABLE_NAME NOT LIKE 'RMD\_%' ESCAPE '\'
     ORDER BY c.TABLE_NAME,c.COLUMN_NAME
  ) LOOP
    SAVEPOINT RMD_CASA_2930_COL;
    BEGIN
      IF r.COLUMN_NAME='CODBAI' THEN
        v_sql := 'INSERT INTO '||v_dep||
          '(ID_EXECUCAO,TABLE_NAME,COLUMN_NAME,RID,OLD_VALUE,NEW_VALUE,DTLOG) '||
          'SELECT :1,:2,:3,ROWIDTOCHAR(t.ROWID),t.CODBAI,m.COD_MANTIDO,SYSTIMESTAMP '||
          'FROM '||r.TABLE_NAME||' t JOIN '||v_map||' m ON m.ID_EXECUCAO=:1 '||
          'AND m.TIPO=''BAI'' AND m.COD_OBSOLETO=t.CODBAI';
        EXECUTE IMMEDIATE v_sql USING v_id,r.TABLE_NAME,r.COLUMN_NAME,v_id;
        v_sql := 'UPDATE '||r.TABLE_NAME||' t SET CODBAI=('||
          'SELECT m.COD_MANTIDO FROM '||v_map||' m WHERE m.ID_EXECUCAO=:1 '||
          'AND m.TIPO=''BAI'' AND m.COD_OBSOLETO=t.CODBAI) WHERE EXISTS ('||
          'SELECT 1 FROM '||v_map||' m WHERE m.ID_EXECUCAO=:1 AND m.TIPO=''BAI'' '||
          'AND m.COD_OBSOLETO=t.CODBAI)';
      ELSE
        v_sql := 'INSERT INTO '||v_dep||
          '(ID_EXECUCAO,TABLE_NAME,COLUMN_NAME,RID,OLD_VALUE,NEW_VALUE,DTLOG) '||
          'SELECT :1,:2,:3,ROWIDTOCHAR(t.ROWID),t.CODEND,m.COD_MANTIDO,SYSTIMESTAMP '||
          'FROM '||r.TABLE_NAME||' t JOIN '||v_map||' m ON m.ID_EXECUCAO=:1 '||
          'AND m.TIPO=''END'' AND m.COD_OBSOLETO=t.CODEND';
        EXECUTE IMMEDIATE v_sql USING v_id,r.TABLE_NAME,r.COLUMN_NAME,v_id;
        v_sql := 'UPDATE '||r.TABLE_NAME||' t SET CODEND=('||
          'SELECT m.COD_MANTIDO FROM '||v_map||' m WHERE m.ID_EXECUCAO=:1 '||
          'AND m.TIPO=''END'' AND m.COD_OBSOLETO=t.CODEND) WHERE EXISTS ('||
          'SELECT 1 FROM '||v_map||' m WHERE m.ID_EXECUCAO=:1 AND m.TIPO=''END'' '||
          'AND m.COD_OBSOLETO=t.CODEND)';
      END IF;
      EXECUTE IMMEDIATE v_sql USING v_id,v_id;
      DBMS_OUTPUT.PUT_LINE('RAMO_OK|'||r.TABLE_NAME||'|'||r.COLUMN_NAME||'|'||SQL%ROWCOUNT);
    EXCEPTION WHEN OTHERS THEN
      ROLLBACK TO RMD_CASA_2930_COL;
      log_exc(r.TABLE_NAME,r.COLUMN_NAME,SQLERRM);
      DBMS_OUTPUT.PUT_LINE('RAMO_EXCECAO|'||r.TABLE_NAME||'|'||r.COLUMN_NAME||'|'||SQLERRM);
    END;
  END LOOP;

  FOR r IN (
    SELECT DISTINCT c.TABLE_NAME,cc.COLUMN_NAME,p.TABLE_NAME REFERENCED_TABLE
      FROM ALL_CONSTRAINTS c
      JOIN ALL_CONS_COLUMNS cc ON cc.OWNER=c.OWNER AND cc.CONSTRAINT_NAME=c.CONSTRAINT_NAME
      JOIN ALL_CONSTRAINTS p ON p.OWNER=c.R_OWNER AND p.CONSTRAINT_NAME=c.R_CONSTRAINT_NAME
      JOIN ALL_TABLES t ON t.OWNER=c.OWNER AND t.TABLE_NAME=c.TABLE_NAME
     WHERE c.OWNER=v_owner AND c.CONSTRAINT_TYPE='R'
       AND p.OWNER=v_owner AND p.TABLE_NAME IN ('TSIBAI','TSIEND')
       AND t.TEMPORARY='N' AND cc.COLUMN_NAME NOT IN ('CODBAI','CODEND')
       AND c.TABLE_NAME NOT IN ('TSIBAI','TSIEND',v_map,v_bkp_bai,v_bkp_end,v_dep,v_exc)
       AND c.TABLE_NAME NOT LIKE 'BKP\_%' ESCAPE '\'
       AND c.TABLE_NAME NOT LIKE 'RMD\_%' ESCAPE '\'
     ORDER BY c.TABLE_NAME,cc.COLUMN_NAME
  ) LOOP
    SAVEPOINT RMD_CASA_2930_FK;
    BEGIN
      IF r.REFERENCED_TABLE='TSIBAI' THEN
        v_sql := 'INSERT INTO '||v_dep||
          '(ID_EXECUCAO,TABLE_NAME,COLUMN_NAME,RID,OLD_VALUE,NEW_VALUE,DTLOG) '||
          'SELECT :1,:2,:3,ROWIDTOCHAR(t.ROWID),t.'||r.COLUMN_NAME||',m.COD_MANTIDO,SYSTIMESTAMP '||
          'FROM '||r.TABLE_NAME||' t JOIN '||v_map||' m ON m.ID_EXECUCAO=:1 '||
          'AND m.TIPO=''BAI'' AND m.COD_OBSOLETO=t.'||r.COLUMN_NAME;
        EXECUTE IMMEDIATE v_sql USING v_id,r.TABLE_NAME,r.COLUMN_NAME,v_id;
        v_sql := 'UPDATE '||r.TABLE_NAME||' t SET '||r.COLUMN_NAME||'=('||
          'SELECT m.COD_MANTIDO FROM '||v_map||' m WHERE m.ID_EXECUCAO=:1 '||
          'AND m.TIPO=''BAI'' AND m.COD_OBSOLETO=t.'||r.COLUMN_NAME||') WHERE EXISTS ('||
          'SELECT 1 FROM '||v_map||' m WHERE m.ID_EXECUCAO=:1 AND m.TIPO=''BAI'' '||
          'AND m.COD_OBSOLETO=t.'||r.COLUMN_NAME||')';
      ELSE
        v_sql := 'INSERT INTO '||v_dep||
          '(ID_EXECUCAO,TABLE_NAME,COLUMN_NAME,RID,OLD_VALUE,NEW_VALUE,DTLOG) '||
          'SELECT :1,:2,:3,ROWIDTOCHAR(t.ROWID),t.'||r.COLUMN_NAME||',m.COD_MANTIDO,SYSTIMESTAMP '||
          'FROM '||r.TABLE_NAME||' t JOIN '||v_map||' m ON m.ID_EXECUCAO=:1 '||
          'AND m.TIPO=''END'' AND m.COD_OBSOLETO=t.'||r.COLUMN_NAME;
        EXECUTE IMMEDIATE v_sql USING v_id,r.TABLE_NAME,r.COLUMN_NAME,v_id;
        v_sql := 'UPDATE '||r.TABLE_NAME||' t SET '||r.COLUMN_NAME||'=('||
          'SELECT m.COD_MANTIDO FROM '||v_map||' m WHERE m.ID_EXECUCAO=:1 '||
          'AND m.TIPO=''END'' AND m.COD_OBSOLETO=t.'||r.COLUMN_NAME||') WHERE EXISTS ('||
          'SELECT 1 FROM '||v_map||' m WHERE m.ID_EXECUCAO=:1 AND m.TIPO=''END'' '||
          'AND m.COD_OBSOLETO=t.'||r.COLUMN_NAME||')';
      END IF;
      EXECUTE IMMEDIATE v_sql USING v_id,v_id;
      DBMS_OUTPUT.PUT_LINE('FK_RAMO_OK|'||r.TABLE_NAME||'|'||r.COLUMN_NAME||'|'||SQL%ROWCOUNT);
    EXCEPTION WHEN OTHERS THEN
      ROLLBACK TO RMD_CASA_2930_FK;
      log_exc(r.TABLE_NAME,r.COLUMN_NAME,SQLERRM);
      DBMS_OUTPUT.PUT_LINE('FK_RAMO_EXCECAO|'||r.TABLE_NAME||'|'||r.COLUMN_NAME||'|'||SQLERRM);
    END;
  END LOOP;

  FOR r IN (
    SELECT DISTINCT c.TABLE_NAME,c.COLUMN_NAME
      FROM ALL_TAB_COLUMNS c
      JOIN ALL_TABLES t ON t.OWNER=c.OWNER AND t.TABLE_NAME=c.TABLE_NAME
     WHERE c.OWNER=v_owner AND t.TEMPORARY='N'
       AND c.COLUMN_NAME IN ('CODBAI','CODEND')
       AND c.DATA_TYPE IN ('NUMBER','FLOAT','BINARY_FLOAT','BINARY_DOUBLE')
       AND c.TABLE_NAME NOT IN ('TSIBAI','TSIEND',v_map,v_bkp_bai,v_bkp_end,v_dep,v_exc)
       AND c.TABLE_NAME NOT LIKE 'BKP\_%' ESCAPE '\'
       AND c.TABLE_NAME NOT LIKE 'RMD\_%' ESCAPE '\'
  ) LOOP
    BEGIN
      IF r.COLUMN_NAME='CODBAI' THEN
        v_sql:='SELECT COUNT(*) FROM '||r.TABLE_NAME||' t WHERE EXISTS ('||
          'SELECT 1 FROM '||v_map||' m WHERE m.ID_EXECUCAO=:1 AND m.TIPO=''BAI'' '||
          'AND m.COD_OBSOLETO=t.CODBAI)';
      ELSE
        v_sql:='SELECT COUNT(*) FROM '||r.TABLE_NAME||' t WHERE EXISTS ('||
          'SELECT 1 FROM '||v_map||' m WHERE m.ID_EXECUCAO=:1 AND m.TIPO=''END'' '||
          'AND m.COD_OBSOLETO=t.CODEND)';
      END IF;
      EXECUTE IMMEDIATE v_sql INTO v_n USING v_id;
      v_ref:=v_ref+v_n;
    EXCEPTION WHEN OTHERS THEN
      log_exc(r.TABLE_NAME,r.COLUMN_NAME,SQLERRM);
    END;
  END LOOP;

  FOR r IN (
    SELECT DISTINCT c.TABLE_NAME,cc.COLUMN_NAME,p.TABLE_NAME REFERENCED_TABLE
      FROM ALL_CONSTRAINTS c
      JOIN ALL_CONS_COLUMNS cc ON cc.OWNER=c.OWNER AND cc.CONSTRAINT_NAME=c.CONSTRAINT_NAME
      JOIN ALL_CONSTRAINTS p ON p.OWNER=c.R_OWNER AND p.CONSTRAINT_NAME=c.R_CONSTRAINT_NAME
      JOIN ALL_TABLES t ON t.OWNER=c.OWNER AND t.TABLE_NAME=c.TABLE_NAME
     WHERE c.OWNER=v_owner AND c.CONSTRAINT_TYPE='R'
       AND p.OWNER=v_owner AND p.TABLE_NAME IN ('TSIBAI','TSIEND')
       AND t.TEMPORARY='N' AND cc.COLUMN_NAME NOT IN ('CODBAI','CODEND')
       AND c.TABLE_NAME NOT IN ('TSIBAI','TSIEND',v_map,v_bkp_bai,v_bkp_end,v_dep,v_exc)
       AND c.TABLE_NAME NOT LIKE 'BKP\_%' ESCAPE '\'
       AND c.TABLE_NAME NOT LIKE 'RMD\_%' ESCAPE '\'
  ) LOOP
    BEGIN
      IF r.REFERENCED_TABLE='TSIBAI' THEN
        v_sql:='SELECT COUNT(*) FROM '||r.TABLE_NAME||' t WHERE EXISTS ('||
          'SELECT 1 FROM '||v_map||' m WHERE m.ID_EXECUCAO=:1 AND m.TIPO=''BAI'' '||
          'AND m.COD_OBSOLETO=t.'||r.COLUMN_NAME||')';
      ELSE
        v_sql:='SELECT COUNT(*) FROM '||r.TABLE_NAME||' t WHERE EXISTS ('||
          'SELECT 1 FROM '||v_map||' m WHERE m.ID_EXECUCAO=:1 AND m.TIPO=''END'' '||
          'AND m.COD_OBSOLETO=t.'||r.COLUMN_NAME||')';
      END IF;
      EXECUTE IMMEDIATE v_sql INTO v_n USING v_id;
      v_ref:=v_ref+v_n;
    EXCEPTION WHEN OTHERS THEN
      log_exc(r.TABLE_NAME,r.COLUMN_NAME,SQLERRM);
    END;
  END LOOP;

  EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM '||v_map||' WHERE ID_EXECUCAO=:1' INTO v_map_count USING v_id;
  EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM '||v_bkp_bai||' WHERE ID_EXECUCAO=:1' INTO v_bkp_bai_count USING v_id;
  EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM '||v_bkp_end||' WHERE ID_EXECUCAO=:1' INTO v_bkp_end_count USING v_id;
  EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM '||v_dep||' WHERE ID_EXECUCAO=:1' INTO v_dep_count USING v_id;
  EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM '||v_exc||' WHERE ID_EXECUCAO=:1' INTO v_exc_count USING v_id;
  DBMS_OUTPUT.PUT_LINE('ID_EXECUCAO='||v_id);
  DBMS_OUTPUT.PUT_LINE('MAPA_LINHAS='||v_map_count||'; BACKUP_BAI='||v_bkp_bai_count||'; BACKUP_END='||v_bkp_end_count);
  DBMS_OUTPUT.PUT_LINE('REFERENCIAS_AUDITADAS='||v_dep_count||'; EXCECOES='||v_exc_count||'; REFERENCIAS_REMANESCENTES='||v_ref);
  COMMIT;
  IF v_ref=0 AND v_exc_count=0 THEN
    DBMS_OUTPUT.PUT_LINE('STATUS=MERGE_REDIRECIONADO_REFERENCIAS_ZERO_SEM_EXCLUSAO');
  ELSE
    DBMS_OUTPUT.PUT_LINE('STATUS=MERGE_PARCIAL_EXIGE_ANALISE_SEM_EXCLUSAO');
  END IF;
EXCEPTION WHEN OTHERS THEN
  ROLLBACK;
  RAISE;
END;
/
