-- CASA DAS ESSENCIAS - auditoria persistente da exclusao dos pais obsoletos.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

DECLARE
  v_n NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_n FROM ALL_TABLES
   WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND TABLE_NAME='RMD_CASA_2930_R03_DEL';
  IF v_n=0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE RMD_CASA_2930_R03_DEL ('||
      'ID_EXECUCAO VARCHAR2(50),TABLE_NAME VARCHAR2(128),CODIGO NUMBER,DTLOG TIMESTAMP)';
  END IF;
  DBMS_OUTPUT.PUT_LINE('AUDITORIA_EXCLUSAO_29_30_R03=CRIADA_OU_EXISTENTE');
END;
/
