-- Retomada isolada da atividade 03 da base CASA DAS ESSENCIAS.
-- O bloco original parou por ORA-01031 em DML estatico com grants na role RLCONSULTOR.
-- Esta retomada usa DML dinamico, preserva o backup persistente e aborta em divergencia.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
DECLARE
  v_tabela PLS_INTEGER;
  v_id VARCHAR2(30) := 'RMD_DANF_'||TO_CHAR(SYSTIMESTAMP,'YYYYMMDDHH24MISSFF3');
  v_b PLS_INTEGER;
  v_u PLS_INTEGER;
BEGIN
  SELECT COUNT(*) INTO v_tabela
    FROM ALL_TABLES
   WHERE OWNER='SANKHYA'
     AND TABLE_NAME='BKP_RMD_02_TGFEMP';
  IF v_tabela=0 THEN
    RAISE_APPLICATION_ERROR(-20211,'Backup BKP_RMD_02_TGFEMP nao existe; atividade 03 interrompida.');
  END IF;

  EXECUTE IMMEDIATE q'[
    INSERT INTO SANKHYA.BKP_RMD_02_TGFEMP
    SELECT :1,SYSTIMESTAMP,SYS_CONTEXT('USERENV','SESSION_USER'),ROWIDTOCHAR(ROWID),
           CODMODDANFESIMPLIFNFE,CONTINGENCIANFE,ENVIOSINCRONONFE,NURFE,
           NURFECARTACORR,TIPODANFE,NFE,VERSAONFE,VERSAONT,UTILIZAMDE,LOGODANFE
      FROM SANKHYA.TGFEMP
     WHERE CODEMP<>1
  ]' USING v_id;
  v_b:=SQL%ROWCOUNT;

  EXECUTE IMMEDIATE q'[
    UPDATE SANKHYA.TGFEMP
       SET CODMODDANFESIMPLIFNFE=(SELECT CODMODDANFESIMPLIFNFE FROM SANKHYA.TGFEMP WHERE CODEMP=1),
           CONTINGENCIANFE=(SELECT CONTINGENCIANFE FROM SANKHYA.TGFEMP WHERE CODEMP=1),
           ENVIOSINCRONONFE=(SELECT ENVIOSINCRONONFE FROM SANKHYA.TGFEMP WHERE CODEMP=1),
           NURFE=(SELECT NURFE FROM SANKHYA.TGFEMP WHERE CODEMP=1),
           NURFECARTACORR=(SELECT NURFECARTACORR FROM SANKHYA.TGFEMP WHERE CODEMP=1),
           TIPODANFE=(SELECT TIPODANFE FROM SANKHYA.TGFEMP WHERE CODEMP=1),
           NFE=(SELECT NFE FROM SANKHYA.TGFEMP WHERE CODEMP=1),
           VERSAONFE=(SELECT VERSAONFE FROM SANKHYA.TGFEMP WHERE CODEMP=1),
           VERSAONT=(SELECT VERSAONT FROM SANKHYA.TGFEMP WHERE CODEMP=1),
           UTILIZAMDE=(SELECT UTILIZAMDE FROM SANKHYA.TGFEMP WHERE CODEMP=1),
           LOGODANFE=COALESCE(LOGODANFE,(SELECT LOGODANFE FROM SANKHYA.TGFEMP WHERE CODEMP=1))
     WHERE CODEMP<>1
  ]';
  v_u:=SQL%ROWCOUNT;
  IF v_b<>v_u THEN
    RAISE_APPLICATION_ERROR(-20210,'Backup e atualizacao divergiram na atividade 03.');
  END IF;
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('ATIVIDADE=03_PADRONIZAR_DANFE_EMPRESAS');
  DBMS_OUTPUT.PUT_LINE('ID_EXECUCAO='||v_id);
  DBMS_OUTPUT.PUT_LINE('REGISTROS_BACKUP='||v_b);
  DBMS_OUTPUT.PUT_LINE('REGISTROS_ALTERADOS='||v_u);
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END;
/
