-- Rollback da etapa 32B - somente os financeiros criados pelo ID informado.
-- Exige confirmacao explicita e usa a tabela de auditoria criada pela etapa.

SET DEFINE ON
SET SERVEROUTPUT ON SIZE UNLIMITED
SET SQLBLANKLINES ON
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

DEFINE CONFIRMA_ROLLBACK = 'NAO'

DECLARE
  v_confirm VARCHAR2(3) := UPPER('&&CONFIRMA_ROLLBACK');
  v_qtd NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_qtd
    FROM ALL_TABLES
   WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
     AND TABLE_NAME='BKP_RMD_FDUP_MCL_20260910_INS';
  IF v_qtd=0 THEN
    RAISE_APPLICATION_ERROR(-20328,'Tabela de auditoria da etapa 32B nao encontrada.');
  END IF;

  IF v_confirm <> 'SIM' THEN
    DBMS_OUTPUT.PUT_LINE('STATUS=NAO_EXECUTADO; altere CONFIRMA_ROLLBACK para SIM apos revisar.');
    RETURN;
  END IF;

  DELETE FROM TGFFIN F
   WHERE EXISTS (
     SELECT 1
       FROM BKP_RMD_FDUP_MCL_20260910_INS A
      WHERE A.ID_EXECUCAO='MACALE_20260910_FIN_DUP_01'
        AND A.NUFIN=F.NUFIN
        AND A.NUNOTA=F.NUNOTA
   );
  DBMS_OUTPUT.PUT_LINE('FINANCEIROS_REMOVIDOS='||SQL%ROWCOUNT);
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('STATUS=ROLLBACK_EXECUTADO');
END;
/
