-- Aplica somente as diferenças entre o original Andorinha e a referência Eletrika.
-- Pré-condição: TSICFG deve estar restaurada com as 861 linhas originais.
-- Referência: BKP_RMD_TSICFG_ELETRIKA (994 linhas).
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET ECHO ON
WHENEVER OSERROR EXIT FAILURE ROLLBACK
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

PROMPT === APLICACAO SELETIVA TSICFG ===

DECLARE
  v_atual NUMBER;
  v_ref NUMBER;
  v_del NUMBER;
  v_upd NUMBER;
  v_ins NUMBER;
  v_final NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_atual FROM TSICFG;
  SELECT COUNT(*) INTO v_ref FROM BKP_RMD_TSICFG_ELETRIKA;
  IF v_atual <> 861 THEN
    RAISE_APPLICATION_ERROR(-20721,
      'Pre-condicao invalida: TSICFG atual='||v_atual||'; esperado=861. Restaure o original antes.');
  END IF;
  IF v_ref <> 994 THEN
    RAISE_APPLICATION_ERROR(-20722,
      'Referencia Eletrika divergente: esperado=994; obtido='||v_ref);
  END IF;
END;
/

-- Remove somente chaves que existem no original e não existem na referência.
DELETE FROM TSICFG E
WHERE NOT EXISTS (
  SELECT 1 FROM BKP_RMD_TSICFG_ELETRIKA R
  WHERE R.CHAVE=E.CHAVE AND R.CODUSU=E.CODUSU AND R.TIPO=E.TIPO
    AND NVL(R.CHAVEPAI,CHR(0))=NVL(E.CHAVEPAI,CHR(0))
);
VARIABLE V_DEL NUMBER
BEGIN :V_DEL := SQL%ROWCOUNT; END;
/

-- Atualiza somente configurações cujo conteúdo mudou.
UPDATE TSICFG E
SET E.CONFIG = (
  SELECT R.CONFIG FROM BKP_RMD_TSICFG_ELETRIKA R
  WHERE R.CHAVE=E.CHAVE AND R.CODUSU=E.CODUSU AND R.TIPO=E.TIPO
    AND NVL(R.CHAVEPAI,CHR(0))=NVL(E.CHAVEPAI,CHR(0))
)
WHERE EXISTS (
  SELECT 1 FROM BKP_RMD_TSICFG_ELETRIKA R
  WHERE R.CHAVE=E.CHAVE AND R.CODUSU=E.CODUSU AND R.TIPO=E.TIPO
    AND NVL(R.CHAVEPAI,CHR(0))=NVL(E.CHAVEPAI,CHR(0))
    AND ((E.CONFIG IS NULL AND R.CONFIG IS NOT NULL)
      OR (E.CONFIG IS NOT NULL AND R.CONFIG IS NULL)
      OR (E.CONFIG IS NOT NULL AND R.CONFIG IS NOT NULL
          AND DBMS_LOB.COMPARE(E.CONFIG,R.CONFIG)<>0))
);
VARIABLE V_UPD NUMBER
BEGIN :V_UPD := SQL%ROWCOUNT; END;
/

-- Insere somente chaves existentes na referência e ausentes no original.
INSERT INTO TSICFG (CHAVE,CODUSU,TIPO,CONFIG,CHAVEPAI)
SELECT R.CHAVE,R.CODUSU,R.TIPO,R.CONFIG,R.CHAVEPAI
FROM BKP_RMD_TSICFG_ELETRIKA R
WHERE NOT EXISTS (
  SELECT 1 FROM TSICFG E
  WHERE E.CHAVE=R.CHAVE AND E.CODUSU=R.CODUSU AND E.TIPO=R.TIPO
    AND NVL(E.CHAVEPAI,CHR(0))=NVL(R.CHAVEPAI,CHR(0))
);
VARIABLE V_INS NUMBER
BEGIN :V_INS := SQL%ROWCOUNT; END;
/

SELECT COUNT(*) V_FINAL FROM TSICFG;
COMMIT;

PROMPT === RESULTADO APLICACAO SELETIVA ===
PRINT V_DEL
PRINT V_UPD
PRINT V_INS
PROMPT === FIM APLICACAO SELETIVA ===
