-- Aplicação seletiva sem parâmetros interativos.
-- Pré-condição: TSICFG restaurada com 861 linhas.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET ECHO ON
WHENEVER OSERROR EXIT FAILURE ROLLBACK
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

DECLARE
  v_atual NUMBER;
  v_ref NUMBER;
  v_del NUMBER;
  v_upd NUMBER;
  v_ins NUMBER;
  v_final NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_atual FROM TSICFG;
  SELECT COUNT(*) INTO v_ref FROM BKP_RMD_TSICFG_ELETRIKA;
  IF v_atual <> 861 THEN
    RAISE_APPLICATION_ERROR(-20721,'Pre-condicao invalida: TSICFG atual='||v_atual||'; esperado=861.');
  END IF;
  IF v_ref <> 994 THEN
    RAISE_APPLICATION_ERROR(-20722,'Referencia Eletrika divergente: esperado=994; obtido='||v_ref);
  END IF;

  DELETE FROM TSICFG E
  WHERE NOT EXISTS (
    SELECT 1 FROM BKP_RMD_TSICFG_ELETRIKA R
    WHERE R.CHAVE=E.CHAVE AND R.CODUSU=E.CODUSU AND R.TIPO=E.TIPO
      AND NVL(R.CHAVEPAI,CHR(0))=NVL(E.CHAVEPAI,CHR(0))
  );
  v_del:=SQL%ROWCOUNT;

  UPDATE TSICFG E
  SET E.CONFIG=(
    SELECT R.CONFIG FROM BKP_RMD_TSICFG_ELETRIKA R
    WHERE R.CHAVE=E.CHAVE AND R.CODUSU=E.CODUSU AND R.TIPO=E.TIPO
      AND NVL(R.CHAVEPAI,CHR(0))=NVL(E.CHAVEPAI,CHR(0))
  )
  WHERE EXISTS (
    SELECT 1 FROM BKP_RMD_TSICFG_ELETRIKA R
    WHERE R.CHAVE=E.CHAVE AND R.CODUSU=E.CODUSU AND R.TIPO=E.TIPO
      AND NVL(R.CHAVEPAI,CHR(0))=NVL(E.CHAVEPAI,CHR(0))
      AND ((E.CONFIG IS NULL AND R.CONFIG IS NOT NULL)
        OR (E.CONFIG IS NOT NULL AND R.CONFIG IS NULL)
        OR (E.CONFIG IS NOT NULL AND R.CONFIG IS NOT NULL
            AND DBMS_LOB.COMPARE(E.CONFIG,R.CONFIG)<>0))
  );
  v_upd:=SQL%ROWCOUNT;

  INSERT INTO TSICFG (CHAVE,CODUSU,TIPO,CONFIG,CHAVEPAI)
  SELECT R.CHAVE,R.CODUSU,R.TIPO,R.CONFIG,R.CHAVEPAI
  FROM BKP_RMD_TSICFG_ELETRIKA R
  WHERE NOT EXISTS (
    SELECT 1 FROM TSICFG E
    WHERE E.CHAVE=R.CHAVE AND E.CODUSU=R.CODUSU AND E.TIPO=R.TIPO
      AND NVL(E.CHAVEPAI,CHR(0))=NVL(R.CHAVEPAI,CHR(0))
  );
  v_ins:=SQL%ROWCOUNT;

  SELECT COUNT(*) INTO v_final FROM TSICFG;
  IF v_final <> v_ref THEN
    RAISE_APPLICATION_ERROR(-20723,'Resultado divergente: final='||v_final||'; referencia='||v_ref);
  END IF;

  COMMIT;
  DBMS_OUTPUT.PUT_LINE('TSICFG_EXCLUIDAS='||v_del);
  DBMS_OUTPUT.PUT_LINE('TSICFG_ATUALIZADAS='||v_upd);
  DBMS_OUTPUT.PUT_LINE('TSICFG_INSERIDAS='||v_ins);
  DBMS_OUTPUT.PUT_LINE('TSICFG_FINAL='||v_final);
END;
/
