-- Somente leitura: comprova quais backups e resultados foram materializados.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
DECLARE
  v_n NUMBER;
  v_t VARCHAR2(128);
  TYPE t_names IS TABLE OF VARCHAR2(128);
  v_names t_names := t_names(
    'BKP_RMD_06_TGFCAB','BKP_RMD_07_TGFCAB','BKP_RMD_08_TGFITE',
    'BKP_RMD_09_TGFPRO','BKP_RMD_10_TGFPRO','BKP_RMD_11_TGFEMP',
    'BKP_RMD_12_TGFTOP','BKP_RMD_13_TSIIMP','BKP_RMD_14_TGFPRO',
    'BKP_RMD_TSICFG','BKP_RMD_GOL_TGFCGM','BKP_RMD_GOL_TGFCMV',
    'BKP_RMD_GOL_TSIPAR','BKP_RMD_PAR_MATRIZ','BKP_RMD_CARD_TTKINDAGT',
    'BKP_RMD_PAD_TGFPAR','BKP_RMD_PAD_TGFPRO','BKP_RMD_PAD_TGFTIT',
    'BKP_RMD_PAD_TSICID','BKP_RMD_PAD_TGFTPV','BKP_RMD_PAD_TSIBAI',
    'BKP_RMD_PAD_TSIEND');
BEGIN
  FOR i IN 1..v_names.COUNT LOOP
    v_t:=v_names(i);
    SELECT COUNT(*) INTO v_n FROM USER_TABLES WHERE TABLE_NAME=v_t;
    IF v_n=0 THEN
      DBMS_OUTPUT.PUT_LINE(v_t||'|TABELA_AUSENTE');
    ELSE
      EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM '||v_t INTO v_n;
      DBMS_OUTPUT.PUT_LINE(v_t||'|REGISTROS='||v_n);
    END IF;
  END LOOP;
END;
/
SELECT 'TSICFG_ATUAL' OBJETO, COUNT(*) QTD FROM TSICFG;
SELECT 'TSIBAI_ATUAL' OBJETO, COUNT(*) QTD FROM TSIBAI;
SELECT 'TSIEND_ATUAL' OBJETO, COUNT(*) QTD FROM TSIEND;
DECLARE
  v_n NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_n
    FROM USER_TABLES
   WHERE TABLE_NAME='RMD_MAP_UNIDADES';
  IF v_n=0 THEN
    DBMS_OUTPUT.PUT_LINE('RMD_MAP_UNIDADES|TABELA_AUSENTE_NO_SCHEMA_ATUAL');
  ELSE
    EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM RMD_MAP_UNIDADES' INTO v_n;
    DBMS_OUTPUT.PUT_LINE('RMD_MAP_UNIDADES|REGISTROS='||v_n);
  END IF;
END;
/
