-- Backup persistente do estado atual de TSICFG para comparação com a referência Eletrika.
-- Somente backup; não apaga nem altera TSICFG.
-- Execute conectado à ANDORINHA COMERCIAL como SCRIPT (F5).
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET SQLBLANKLINES ON
SET ECHO ON
WHENEVER OSERROR EXIT FAILURE ROLLBACK
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

PROMPT === BACKUP ATUAL TSICFG ===
SELECT SYS_CONTEXT('USERENV','SESSION_USER') USUARIO,
       SYS_CONTEXT('USERENV','CURRENT_SCHEMA') SCHEMA_ATUAL,
       SYS_CONTEXT('USERENV','SERVICE_NAME') SERVICO
FROM DUAL;

DECLARE
  v_existe NUMBER;
  v_origem NUMBER;
  v_backup NUMBER;
  v_id VARCHAR2(30) := 'RMD_CFG_ATUAL_20260908';
BEGIN
  SELECT COUNT(*) INTO v_existe
  FROM ALL_TABLES
  WHERE OWNER = SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
    AND TABLE_NAME = 'BKP_RMD_TSICFG_ATUAL';

  IF v_existe > 0 THEN
    RAISE_APPLICATION_ERROR(-20701,
      'BKP_RMD_TSICFG_ATUAL ja existe. Nao sobrescrito por seguranca.');
  END IF;

  EXECUTE IMMEDIATE q'[
    CREATE TABLE BKP_RMD_TSICFG_ATUAL AS
    SELECT CAST(NULL AS VARCHAR2(30)) ID_EXECUCAO,
           CAST(NULL AS TIMESTAMP) DH_EXECUCAO,
           CAST(NULL AS VARCHAR2(128)) USUARIO_EXECUCAO,
           T.*
      FROM TSICFG T
     WHERE 1=0
  ]';

  SELECT COUNT(*) INTO v_origem FROM TSICFG;

  INSERT INTO BKP_RMD_TSICFG_ATUAL
  SELECT v_id,
         SYSTIMESTAMP,
         SYS_CONTEXT('USERENV','SESSION_USER'),
         T.*
    FROM TSICFG T;

  v_backup := SQL%ROWCOUNT;

  IF v_backup <> v_origem THEN
    RAISE_APPLICATION_ERROR(-20702,
      'Backup divergente: origem='||v_origem||', backup='||v_backup);
  END IF;

  COMMIT;
  DBMS_OUTPUT.PUT_LINE('ID_EXECUCAO='||v_id);
  DBMS_OUTPUT.PUT_LINE('TSICFG_ORIGEM='||v_origem);
  DBMS_OUTPUT.PUT_LINE('TSICFG_BACKUP='||v_backup);
  DBMS_OUTPUT.PUT_LINE('TABELA_BACKUP=BKP_RMD_TSICFG_ATUAL');
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END;
/

PROMPT === VALIDACAO BACKUP ===
SELECT COUNT(*) TSICFG_ATUAL FROM TSICFG;
SELECT COUNT(*) BKP_RMD_TSICFG_ATUAL FROM BKP_RMD_TSICFG_ATUAL;
PROMPT === FIM BACKUP ATUAL TSICFG ===
