-- Comparação somente leitura entre o backup original da Andorinha e a referência Eletrika.
-- TSICFG = referência Eletrika atualmente carregada.
-- BKP_RMD_TSICFG_ATUAL = estado original preservado da Andorinha.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET ECHO ON
SET LONG 200
SET PAGESIZE 100
SPOOL "/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Clientes/ANDORINHA COMERCIAL/Logs/Comparacao_TSICFG_Andorinha_Eletrika.log"

PROMPT === IDENTIDADE ===
SELECT SYS_CONTEXT('USERENV','SESSION_USER') USUARIO,
       SYS_CONTEXT('USERENV','CURRENT_SCHEMA') SCHEMA_ATUAL,
       SYS_CONTEXT('USERENV','SERVICE_NAME') SERVICO
FROM DUAL;

PROMPT === CONTAGENS ===
SELECT 'ANDORINHA_ORIGINAL' FONTE, COUNT(*) QTD FROM BKP_RMD_TSICFG_ATUAL
UNION ALL
SELECT 'ELETRIKA_ATUAL', COUNT(*) FROM TSICFG;

PROMPT === DUPLICIDADES DE CHAVE ===
SELECT CHAVE, CODUSU, TIPO, NVL(CHAVEPAI,'<NULL>') CHAVEPAI, COUNT(*) QTD
FROM BKP_RMD_TSICFG_ATUAL
GROUP BY CHAVE, CODUSU, TIPO, NVL(CHAVEPAI,'<NULL>')
HAVING COUNT(*) > 1
ORDER BY QTD DESC, CHAVE;

SELECT CHAVE, CODUSU, TIPO, NVL(CHAVEPAI,'<NULL>') CHAVEPAI, COUNT(*) QTD
FROM TSICFG
GROUP BY CHAVE, CODUSU, TIPO, NVL(CHAVEPAI,'<NULL>')
HAVING COUNT(*) > 1
ORDER BY QTD DESC, CHAVE;

PROMPT === SOMENTE NA ANDORINHA ORIGINAL ===
SELECT B.CHAVE, B.CODUSU, B.TIPO, B.CHAVEPAI
FROM BKP_RMD_TSICFG_ATUAL B
WHERE NOT EXISTS (
  SELECT 1 FROM TSICFG E
  WHERE E.CHAVE=B.CHAVE AND E.CODUSU=B.CODUSU AND E.TIPO=B.TIPO
    AND NVL(E.CHAVEPAI,CHR(0))=NVL(B.CHAVEPAI,CHR(0))
)
ORDER BY B.CHAVE;

PROMPT === SOMENTE NA ELETRIKA ===
SELECT E.CHAVE, E.CODUSU, E.TIPO, E.CHAVEPAI
FROM TSICFG E
WHERE NOT EXISTS (
  SELECT 1 FROM BKP_RMD_TSICFG_ATUAL B
  WHERE B.CHAVE=E.CHAVE AND B.CODUSU=E.CODUSU AND B.TIPO=E.TIPO
    AND NVL(B.CHAVEPAI,CHR(0))=NVL(E.CHAVEPAI,CHR(0))
)
ORDER BY E.CHAVE;

PROMPT === MESMA CHAVE, CONFIGURACAO DIFERENTE ===
SELECT B.CHAVE, B.CODUSU, B.TIPO, B.CHAVEPAI,
       DBMS_LOB.GETLENGTH(B.CONFIG) CONFIG_ORIGINAL,
       DBMS_LOB.GETLENGTH(E.CONFIG) CONFIG_ELETRIKA
FROM BKP_RMD_TSICFG_ATUAL B
JOIN TSICFG E
  ON E.CHAVE=B.CHAVE AND E.CODUSU=B.CODUSU AND E.TIPO=B.TIPO
 AND NVL(E.CHAVEPAI,CHR(0))=NVL(B.CHAVEPAI,CHR(0))
WHERE (B.CONFIG IS NULL AND E.CONFIG IS NOT NULL)
   OR (B.CONFIG IS NOT NULL AND E.CONFIG IS NULL)
   OR (B.CONFIG IS NOT NULL AND E.CONFIG IS NOT NULL
       AND DBMS_LOB.COMPARE(B.CONFIG,E.CONFIG)<>0)
ORDER BY B.CHAVE;

PROMPT === FIM COMPARACAO ===
SPOOL OFF
