SET DEFINE OFF
SET ECHO ON
PROMPT === PRIVILEGIOS DOS BACKUPS ===
SELECT GRANTEE, TABLE_SCHEMA, TABLE_NAME, PRIVILEGE
FROM ALL_TAB_PRIVS
WHERE TABLE_NAME IN ('BKP_RMD_07_TGFCAB','BKP_RMD_08_TGFITE','BKP_RMD_09_TGFPRO')
ORDER BY TABLE_NAME, GRANTEE, PRIVILEGE;

PROMPT === OBJETOS E PROPRIETARIOS ===
SELECT OWNER, OBJECT_NAME, OBJECT_TYPE, STATUS
FROM ALL_OBJECTS
WHERE OBJECT_NAME IN ('BKP_RMD_07_TGFCAB','BKP_RMD_08_TGFITE','BKP_RMD_09_TGFPRO')
ORDER BY OBJECT_NAME;
