-- Complemento da etapa 17: .MT/MTR -> MT e DESCRVOL em maiusculas.

SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET SQLBLANKLINES ON
SET ECHO ON
WHENEVER OSERROR EXIT FAILURE ROLLBACK
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

PROMPT === CORRIGIR METROS E DESCRICOES TGFVOL ===

DECLARE
  v_id CONSTANT VARCHAR2(30):='RMD_UNID_20260908133000000';
  v_destino NUMBER;v_reexec NUMBER;v_ite NUMBER;
  v_b_pap NUMBER;v_b_voa NUMBER;v_b_vol NUMBER;
  v_u_pap NUMBER;v_d_voa NUMBER;v_d_vol NUMBER;v_u_descr NUMBER;
  v_restantes NUMBER;v_minusculas NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_destino FROM TGFVOL WHERE CODVOL='MT';
  IF v_destino<>1 THEN RAISE_APPLICATION_ERROR(-20761,'Esperada exatamente uma unidade destino MT; encontrada='||v_destino);END IF;

  SELECT COUNT(*) INTO v_ite FROM TGFITE WHERE CODVOL IN ('.MT','MTR');
  IF v_ite<>0 THEN RAISE_APPLICATION_ERROR(-20762,'Existem itens usando .MT/MTR; revisar tratamento de trigger. QTD='||v_ite);END IF;

  SELECT
    (SELECT COUNT(*) FROM BKP_RMD_UNID_TGFPAP WHERE ID_EXECUCAO=v_id)+
    (SELECT COUNT(*) FROM BKP_RMD_UNID_TGFVOA WHERE ID_EXECUCAO=v_id)+
    (SELECT COUNT(*) FROM BKP_RMD_UNID_TGFVOL WHERE ID_EXECUCAO=v_id)
  INTO v_reexec FROM DUAL;
  IF v_reexec<>0 THEN RAISE_APPLICATION_ERROR(-20763,'O ID ja possui backups; execucao cancelada.');END IF;

  INSERT INTO BKP_RMD_UNID_TGFPAP
  SELECT v_id,SYSTIMESTAMP,SYS_CONTEXT('USERENV','SESSION_USER'),ROWIDTOCHAR(T.ROWID),T.*
  FROM TGFPAP T WHERE T.UNIDADEPARC IN ('.MT','MTR');
  v_b_pap:=SQL%ROWCOUNT;

  INSERT INTO BKP_RMD_UNID_TGFVOA
  SELECT v_id,SYSTIMESTAMP,SYS_CONTEXT('USERENV','SESSION_USER'),ROWIDTOCHAR(T.ROWID),T.*
  FROM TGFVOA T WHERE T.CODVOL IN ('.MT','MTR');
  v_b_voa:=SQL%ROWCOUNT;

  INSERT INTO BKP_RMD_UNID_TGFVOL
  SELECT v_id,SYSTIMESTAMP,SYS_CONTEXT('USERENV','SESSION_USER'),ROWIDTOCHAR(T.ROWID),T.*
  FROM TGFVOL T
  WHERE T.CODVOL IN ('.MT','MTR') OR T.DESCRVOL<>UPPER(T.DESCRVOL);
  v_b_vol:=SQL%ROWCOUNT;

  UPDATE TGFPAP SET UNIDADEPARC='MT' WHERE UNIDADEPARC IN ('.MT','MTR');
  v_u_pap:=SQL%ROWCOUNT;
  DELETE FROM TGFVOA WHERE CODVOL IN ('.MT','MTR');
  v_d_voa:=SQL%ROWCOUNT;
  DELETE FROM TGFVOL WHERE CODVOL IN ('.MT','MTR');
  v_d_vol:=SQL%ROWCOUNT;
  UPDATE TGFVOL SET DESCRVOL=UPPER(DESCRVOL) WHERE DESCRVOL<>UPPER(DESCRVOL);
  v_u_descr:=SQL%ROWCOUNT;

  IF v_b_pap<>v_u_pap OR v_b_voa<>v_d_voa OR v_b_vol<>(v_d_vol+v_u_descr) THEN
    RAISE_APPLICATION_ERROR(-20764,'Contagens de backup e alteracao divergiram.');
  END IF;

  SELECT
    (SELECT COUNT(*) FROM TGFPRO WHERE CODVOL IN ('.MT','MTR'))+
    (SELECT COUNT(*) FROM TGFITE WHERE CODVOL IN ('.MT','MTR'))+
    (SELECT COUNT(*) FROM TGFPAP WHERE UNIDADEPARC IN ('.MT','MTR'))+
    (SELECT COUNT(*) FROM TGFCOI2 WHERE CODVOL IN ('.MT','MTR'))+
    (SELECT COUNT(*) FROM TGFGIR1 WHERE CODVOL IN ('.MT','MTR'))+
    (SELECT COUNT(*) FROM TGFVOA WHERE CODVOL IN ('.MT','MTR'))+
    (SELECT COUNT(*) FROM TGFVOL WHERE CODVOL IN ('.MT','MTR'))
  INTO v_restantes FROM DUAL;
  SELECT COUNT(*) INTO v_minusculas FROM TGFVOL WHERE DESCRVOL<>UPPER(DESCRVOL);
  IF v_restantes<>0 OR v_minusculas<>0 THEN
    RAISE_APPLICATION_ERROR(-20765,'Validacao falhou: referencias='||v_restantes||'; descricoes='||v_minusculas);
  END IF;

  MERGE INTO RMD_MAP_UNIDADES M
  USING (
    SELECT '.MT' FROM_CODE,'MT' TO_CODE FROM DUAL
    UNION ALL SELECT 'MTR','MT' FROM DUAL
  ) R ON (M.FROM_CODE=R.FROM_CODE)
  WHEN MATCHED THEN UPDATE SET M.TO_CODE=R.TO_CODE
  WHEN NOT MATCHED THEN INSERT (FROM_CODE,TO_CODE) VALUES(R.FROM_CODE,R.TO_CODE);

  COMMIT;
  DBMS_OUTPUT.PUT_LINE('ID_EXECUCAO='||v_id);
  DBMS_OUTPUT.PUT_LINE('TGFPAP_BACKUP='||v_b_pap||'; ATUALIZADOS='||v_u_pap);
  DBMS_OUTPUT.PUT_LINE('TGFVOA_BACKUP='||v_b_voa||'; EXCLUIDOS='||v_d_voa);
  DBMS_OUTPUT.PUT_LINE('TGFVOL_BACKUP='||v_b_vol||'; UNIDADES_EXCLUIDAS='||v_d_vol||'; DESCRICOES_ATUALIZADAS='||v_u_descr);
  DBMS_OUTPUT.PUT_LINE('REFERENCIAS_RESTANTES='||v_restantes||'; DESCRICOES_FORA_PADRAO='||v_minusculas);
EXCEPTION WHEN OTHERS THEN
  ROLLBACK;
  RAISE;
END;
/

PROMPT === FIM CORRIGIR METROS E DESCRICOES TGFVOL ===
