-- Correcao complementar da etapa 17: PEÇAS -> PC.
-- Backup persistente, sem parametros interativos e sem alteracao de triggers.

SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET SQLBLANKLINES ON
SET ECHO ON
WHENEVER OSERROR EXIT FAILURE ROLLBACK
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

PROMPT === CORRECAO COMPLEMENTAR PEÇAS -> PC ===

DECLARE
  v_id CONSTANT VARCHAR2(30):='RMD_UNID_20260908130000000';
  v_pc NUMBER;v_origem NUMBER;v_anterior NUMBER;
  v_b_pap NUMBER;v_b_voa NUMBER;v_b_vol NUMBER;
  v_u_pap NUMBER;v_d_voa NUMBER;v_d_vol NUMBER;v_restantes NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_pc FROM TGFVOL WHERE CODVOL='PC';
  SELECT COUNT(*) INTO v_origem FROM TGFVOL WHERE CODVOL='PEÇAS';
  IF v_pc<>1 THEN RAISE_APPLICATION_ERROR(-20751,'Esperada exatamente uma unidade destino PC; encontrada='||v_pc);END IF;
  IF v_origem<>1 THEN RAISE_APPLICATION_ERROR(-20752,'Esperada exatamente uma unidade origem PEÇAS; encontrada='||v_origem);END IF;

  SELECT
    (SELECT COUNT(*) FROM BKP_RMD_UNID_TGFPAP WHERE ID_EXECUCAO=v_id)+
    (SELECT COUNT(*) FROM BKP_RMD_UNID_TGFVOA WHERE ID_EXECUCAO=v_id)+
    (SELECT COUNT(*) FROM BKP_RMD_UNID_TGFVOL WHERE ID_EXECUCAO=v_id)
  INTO v_anterior FROM DUAL;
  IF v_anterior<>0 THEN RAISE_APPLICATION_ERROR(-20753,'O ID de correcao ja possui backups; execucao cancelada.');END IF;

  INSERT INTO BKP_RMD_UNID_TGFPAP
  SELECT v_id,SYSTIMESTAMP,SYS_CONTEXT('USERENV','SESSION_USER'),ROWIDTOCHAR(T.ROWID),T.*
  FROM TGFPAP T WHERE T.UNIDADEPARC='PEÇAS';
  v_b_pap:=SQL%ROWCOUNT;

  INSERT INTO BKP_RMD_UNID_TGFVOA
  SELECT v_id,SYSTIMESTAMP,SYS_CONTEXT('USERENV','SESSION_USER'),ROWIDTOCHAR(T.ROWID),T.*
  FROM TGFVOA T WHERE T.CODVOL='PEÇAS';
  v_b_voa:=SQL%ROWCOUNT;

  INSERT INTO BKP_RMD_UNID_TGFVOL
  SELECT v_id,SYSTIMESTAMP,SYS_CONTEXT('USERENV','SESSION_USER'),ROWIDTOCHAR(T.ROWID),T.*
  FROM TGFVOL T WHERE T.CODVOL='PEÇAS';
  v_b_vol:=SQL%ROWCOUNT;

  UPDATE TGFPAP SET UNIDADEPARC='PC' WHERE UNIDADEPARC='PEÇAS';
  v_u_pap:=SQL%ROWCOUNT;
  DELETE FROM TGFVOA WHERE CODVOL='PEÇAS';
  v_d_voa:=SQL%ROWCOUNT;
  DELETE FROM TGFVOL WHERE CODVOL='PEÇAS';
  v_d_vol:=SQL%ROWCOUNT;

  IF v_b_pap<>v_u_pap OR v_b_voa<>v_d_voa OR v_b_vol<>v_d_vol THEN
    RAISE_APPLICATION_ERROR(-20754,'Contagens de backup e alteracao divergiram.');
  END IF;

  SELECT
    (SELECT COUNT(*) FROM TGFPRO WHERE CODVOL='PEÇAS')+
    (SELECT COUNT(*) FROM TGFITE WHERE CODVOL='PEÇAS')+
    (SELECT COUNT(*) FROM TGFPAP WHERE UNIDADEPARC='PEÇAS')+
    (SELECT COUNT(*) FROM TGFCOI2 WHERE CODVOL='PEÇAS')+
    (SELECT COUNT(*) FROM TGFGIR1 WHERE CODVOL='PEÇAS')+
    (SELECT COUNT(*) FROM TGFVOA WHERE CODVOL='PEÇAS')+
    (SELECT COUNT(*) FROM TGFVOL WHERE CODVOL='PEÇAS')
  INTO v_restantes FROM DUAL;
  IF v_restantes<>0 THEN RAISE_APPLICATION_ERROR(-20755,'Ainda existem referencias a PEÇAS='||v_restantes);END IF;

  MERGE INTO RMD_MAP_UNIDADES M
  USING (SELECT 'PEÇAS' FROM_CODE,'PC' TO_CODE FROM DUAL) R
  ON (M.FROM_CODE=R.FROM_CODE)
  WHEN MATCHED THEN UPDATE SET M.TO_CODE=R.TO_CODE
  WHEN NOT MATCHED THEN INSERT (FROM_CODE,TO_CODE) VALUES(R.FROM_CODE,R.TO_CODE);

  COMMIT;
  DBMS_OUTPUT.PUT_LINE('ID_EXECUCAO='||v_id);
  DBMS_OUTPUT.PUT_LINE('TGFPAP_BACKUP='||v_b_pap||'; ATUALIZADOS='||v_u_pap);
  DBMS_OUTPUT.PUT_LINE('TGFVOA_BACKUP='||v_b_voa||'; EXCLUIDOS='||v_d_voa);
  DBMS_OUTPUT.PUT_LINE('TGFVOL_BACKUP='||v_b_vol||'; EXCLUIDOS='||v_d_vol);
  DBMS_OUTPUT.PUT_LINE('REFERENCIAS_PECAS_RESTANTES='||v_restantes);
EXCEPTION WHEN OTHERS THEN
  ROLLBACK;
  RAISE;
END;
/

PROMPT === FIM CORRECAO COMPLEMENTAR PEÇAS -> PC ===
