-- Diagnostico somente leitura dos objetos usados pela etapa 17.
-- Execute como script na conexao da Andorinha.

SET DEFINE OFF
SET ECHO ON
SET PAGESIZE 100
SET LINESIZE 220

PROMPT === OBJETOS DA ETAPA 17 ===

SELECT N.NOME OBJETO,
       NVL(O.OBJECT_TYPE, 'AUSENTE') TIPO,
       NVL(O.STATUS, 'AUSENTE') STATUS
FROM (
    SELECT 'RMD_MAP_UNIDADES' NOME FROM DUAL
    UNION ALL SELECT 'BKP_RMD_UNID_MAP' FROM DUAL
    UNION ALL SELECT 'BKP_RMD_UNID_TGFPRO' FROM DUAL
    UNION ALL SELECT 'BKP_RMD_UNID_TGFITE' FROM DUAL
    UNION ALL SELECT 'BKP_RMD_UNID_TGFPAP' FROM DUAL
    UNION ALL SELECT 'BKP_RMD_UNID_TGFCOI2' FROM DUAL
    UNION ALL SELECT 'BKP_RMD_UNID_TGFGIR1' FROM DUAL
    UNION ALL SELECT 'BKP_RMD_UNID_TGFVOA' FROM DUAL
    UNION ALL SELECT 'BKP_RMD_UNID_TGFVOL' FROM DUAL
) N
LEFT JOIN ALL_OBJECTS O
  ON O.OWNER = SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
 AND O.OBJECT_NAME = N.NOME
 AND O.OBJECT_TYPE = 'TABLE'
ORDER BY N.NOME;

PROMPT === TRIGGERS PROTEGIDAS PELA ETAPA 17 ===

SELECT N.NOME NOME_TRIGGER,
       NVL(T.STATUS, 'AUSENTE') STATUS
FROM (
    SELECT 'TRG_INC_UPD_TGFITE' NOME FROM DUAL
    UNION ALL SELECT 'TRG_UPT_TGFITE' FROM DUAL
) N
LEFT JOIN ALL_TRIGGERS T
  ON T.OWNER = SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
 AND T.TRIGGER_NAME = N.NOME
ORDER BY N.NOME;

PROMPT === EXECUCAO DA ETAPA 17 REGISTRADA ===

SELECT COUNT(*) REGISTROS_CONTROLE
FROM RMD_CONTROLE_OBJETOS
WHERE ID_MASTER = 'RMD_RUN_20260908102607051'
  AND ID_EXECUCAO = 'RMD_UNID_20260908113000000';

PROMPT === FIM DIAGNOSTICO ETAPA 17 ===
