SET DEFINE OFF
SET ECHO ON
PROMPT === PRIVILEGIOS TGFPRO ===
SELECT GRANTEE, TABLE_SCHEMA, TABLE_NAME, PRIVILEGE
FROM ALL_TAB_PRIVS
WHERE TABLE_NAME='TGFPRO'
ORDER BY GRANTEE, PRIVILEGE;

PROMPT === PRIVILEGIOS DE COLUNA ===
SELECT GRANTEE, TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, PRIVILEGE
FROM ALL_COL_PRIVS
WHERE TABLE_NAME='TGFPRO'
  AND COLUMN_NAME='ICMSGERENCIA'
ORDER BY GRANTEE, PRIVILEGE;

PROMPT === POLITICAS TGFPRO ===
SELECT OBJECT_OWNER, OBJECT_NAME, POLICY_NAME, PF_OWNER, PACKAGE, FUNCTION
FROM ALL_POLICIES
WHERE OBJECT_NAME='TGFPRO';

PROMPT === COLUNA ICMSGERENCIA ===
SELECT OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH
FROM ALL_TAB_COLUMNS
WHERE TABLE_NAME='TGFPRO'
  AND COLUMN_NAME='ICMSGERENCIA';
