-- Diagnostico somente leitura antes das etapas 29 a 31.
-- Mede o que pode ser padronizado sem colisao e lista dependencias dos codigos.
SET DEFINE OFF
SET ECHO ON
SET PAGESIZE 300
SET LINESIZE 240
SET LONG 100000
SET LONGCHUNKSIZE 100000

PROMPT === ESCOPO SEGURO E COLISOES DE BAIRROS ===
WITH B AS (
  SELECT CODBAI,NOMEBAI,
         REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEBAI),
           'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇáàâãäéèêëíìîïóòôõöúùûüçÃãÕõÂâÊêÎîÔôÛû',
           'AAAAAEEEEIIIIOOOOOUUUUCAAAAAEEEEIIIIOOOOOUUUUCAAAOOAAEIIOOUU')),' {2,}',' ') NORM
  FROM TSIBAI
), G AS (
  SELECT NORM,COUNT(*) QTD FROM B GROUP BY NORM
)
SELECT 'TOTAL_LINHAS' ITEM,COUNT(*) QTD FROM B
UNION ALL SELECT 'LINHAS_EM_COLISAO',COUNT(*) FROM B JOIN G ON G.NORM=B.NORM WHERE G.QTD>1
UNION ALL SELECT 'LINHAS_SEGURAS_A_ATUALIZAR',COUNT(*) FROM B JOIN G ON G.NORM=B.NORM
 WHERE G.QTD=1 AND DECODE(B.NOMEBAI,B.NORM,0,1)=1
UNION ALL SELECT 'GRUPOS_COLISAO',COUNT(*) FROM G WHERE QTD>1;

PROMPT === MAIORES COLISOES DE BAIRROS ===
WITH B AS (
  SELECT CODBAI,NOMEBAI,
         REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEBAI),
           'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇáàâãäéèêëíìîïóòôõöúùûüçÃãÕõÂâÊêÎîÔôÛû',
           'AAAAAEEEEIIIIOOOOOUUUUCAAAAAEEEEIIIIOOOOOUUUUCAAAOOAAEIIOOUU')),' {2,}',' ') NORM
  FROM TSIBAI
)
SELECT * FROM (
  SELECT NORM,COUNT(*) QTD,LISTAGG(CODBAI||':'||NOMEBAI,' | ' ON OVERFLOW TRUNCATE) WITHIN GROUP (ORDER BY CODBAI) EXEMPLOS
  FROM B GROUP BY NORM HAVING COUNT(*)>1 ORDER BY COUNT(*) DESC,NORM
) WHERE ROWNUM<=30;

PROMPT === ESCOPO SEGURO E COLISOES DE ENDERECOS ===
WITH E AS (
  SELECT CODEND,TIPO,NOMEEND,
         REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEEND),
           'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇáàâãäéèêëíìîïóòôõöúùûüçÃãÕõÂâÊêÎîÔôÛû',
           'AAAAAEEEEIIIIOOOOOUUUUCAAAAAEEEEIIIIOOOOOUUUUCAAAOOAAEIIOOUU')),' {2,}',' ') NORM
  FROM TSIEND
), G AS (
  SELECT TIPO,NORM,COUNT(*) QTD FROM E GROUP BY TIPO,NORM
)
SELECT 'TOTAL_LINHAS' ITEM,COUNT(*) QTD FROM E
UNION ALL SELECT 'LINHAS_EM_COLISAO',COUNT(*) FROM E JOIN G ON G.TIPO=E.TIPO AND G.NORM=E.NORM WHERE G.QTD>1
UNION ALL SELECT 'LINHAS_SEGURAS_A_ATUALIZAR',COUNT(*) FROM E JOIN G ON G.TIPO=E.TIPO AND G.NORM=E.NORM
 WHERE G.QTD=1 AND DECODE(E.NOMEEND,E.NORM,0,1)=1
UNION ALL SELECT 'GRUPOS_COLISAO',COUNT(*) FROM G WHERE QTD>1;

PROMPT === MAIORES COLISOES DE ENDERECOS ===
WITH E AS (
  SELECT CODEND,TIPO,NOMEEND,
         REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEEND),
           'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇáàâãäéèêëíìîïóòôõöúùûüçÃãÕõÂâÊêÎîÔôÛû',
           'AAAAAEEEEIIIIOOOOOUUUUCAAAAAEEEEIIIIOOOOOUUUUCAAAOOAAEIIOOUU')),' {2,}',' ') NORM
  FROM TSIEND
)
SELECT * FROM (
  SELECT TIPO,NORM,COUNT(*) QTD,LISTAGG(CODEND||':'||NOMEEND,' | ' ON OVERFLOW TRUNCATE) WITHIN GROUP (ORDER BY CODEND) EXEMPLOS
  FROM E GROUP BY TIPO,NORM HAVING COUNT(*)>1 ORDER BY COUNT(*) DESC,TIPO,NORM
) WHERE ROWNUM<=30;

PROMPT === CHAVES ESTRANGEIRAS QUE REFERENCIAM TSIBAI OU TSIEND ===
SELECT C_PK.TABLE_NAME TABELA_PAI,CC_PK.COLUMN_NAME COLUNA_PAI,
       C_FK.TABLE_NAME TABELA_FILHA,CC_FK.COLUMN_NAME COLUNA_FILHA,C_FK.CONSTRAINT_NAME
FROM ALL_CONSTRAINTS C_FK
JOIN ALL_CONSTRAINTS C_PK
  ON C_PK.OWNER=C_FK.R_OWNER AND C_PK.CONSTRAINT_NAME=C_FK.R_CONSTRAINT_NAME
JOIN ALL_CONS_COLUMNS CC_FK
  ON CC_FK.OWNER=C_FK.OWNER AND CC_FK.CONSTRAINT_NAME=C_FK.CONSTRAINT_NAME
JOIN ALL_CONS_COLUMNS CC_PK
  ON CC_PK.OWNER=C_PK.OWNER AND CC_PK.CONSTRAINT_NAME=C_PK.CONSTRAINT_NAME
 AND CC_PK.POSITION=CC_FK.POSITION
WHERE C_FK.CONSTRAINT_TYPE='R'
  AND C_PK.OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
  AND C_PK.TABLE_NAME IN ('TSIBAI','TSIEND')
ORDER BY C_PK.TABLE_NAME,C_FK.TABLE_NAME,CC_FK.POSITION;

PROMPT === OBJETOS INVALIDOS POR TIPO ===
SELECT OBJECT_TYPE,COUNT(*) QTD
FROM ALL_OBJECTS
WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND STATUS='INVALID'
GROUP BY OBJECT_TYPE
ORDER BY OBJECT_TYPE;

PROMPT === OBJETOS INVALIDOS ===
SELECT OBJECT_TYPE,OBJECT_NAME
FROM ALL_OBJECTS
WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND STATUS='INVALID'
ORDER BY OBJECT_TYPE,OBJECT_NAME;

PROMPT === FIM DIAGNOSTICO ETAPAS 29 A 31 ===
