-- Diagnostico somente leitura da continuidade da Revisao Master Deploy.
-- Executar conectado a ANDORINHA COMERCIAL como Script (F5).
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

PROMPT === DIAGNOSTICO OBJETOS REVISAO ANDORINHA ===
SELECT SYS_CONTEXT('USERENV','SESSION_USER') USUARIO,
       SYS_CONTEXT('USERENV','CURRENT_SCHEMA') SCHEMA_ATUAL,
       SYS_CONTEXT('USERENV','SERVICE_NAME') SERVICO
  FROM DUAL;

SELECT TABLE_NAME,
       NUM_ROWS,
       LAST_ANALYZED
  FROM USER_TABLES
 WHERE TABLE_NAME LIKE 'BKP_RMD%'
    OR TABLE_NAME LIKE 'RMD_%'
 ORDER BY TABLE_NAME;

DECLARE
  v_n NUMBER;
  v_name VARCHAR2(128);
  TYPE t_names IS TABLE OF VARCHAR2(128);
  v_names t_names := t_names(
    'RMD_CONTROLE_OBJETOS','BKP_RMD_01_TSIPAR','BKP_RMD_02_TGFEMP',
    'BKP_RMD_03_TGFTOP','BKP_RMD_04_TGFPRO','BKP_RMD_05_TGFTPV',
    'BKP_RMD_06_TGFCAB','BKP_RMD_07_TGFCAB','BKP_RMD_08_TGFITE',
    'BKP_RMD_09_TGFPRO','BKP_RMD_10_TGFPRO','BKP_RMD_11_TGFEMP',
    'BKP_RMD_12_TGFTOP','BKP_RMD_13_TSIIMP','BKP_RMD_14_TGFPRO',
    'RMD_MAP_UNIDADES');
BEGIN
  FOR i IN 1..v_names.COUNT LOOP
    v_name := v_names(i);
    SELECT COUNT(*) INTO v_n FROM USER_TABLES WHERE TABLE_NAME=v_name;
    IF v_n=0 THEN
      DBMS_OUTPUT.PUT_LINE(v_name||'|TABELA_AUSENTE');
    ELSE
      EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM '||v_name INTO v_n;
      DBMS_OUTPUT.PUT_LINE(v_name||'|REGISTROS='||v_n);
    END IF;
  END LOOP;
END;
/ 

SELECT 'TSICFG' OBJETO, COUNT(*) QTD FROM TSICFG
UNION ALL
SELECT 'TSIBAI', COUNT(*) FROM TSIBAI
UNION ALL
SELECT 'TSIEND', COUNT(*) FROM TSIEND
ORDER BY 1;

PROMPT === FIM DIAGNOSTICO ===
