-- Diagnostico somente leitura da unidade PEÇAS antes da correcao complementar.

SET DEFINE OFF
SET ECHO ON
SET PAGESIZE 100
SET LINESIZE 220

PROMPT === DIAGNOSTICO UNIDADE PEÇAS ===

SELECT CODVOL,DESCRVOL
FROM TGFVOL
WHERE CODVOL IN ('PC','PEÇAS')
ORDER BY CODVOL;

SELECT 'TGFPRO.CODVOL' ORIGEM,COUNT(*) QTD FROM TGFPRO WHERE CODVOL='PEÇAS'
UNION ALL SELECT 'TGFITE.CODVOL',COUNT(*) FROM TGFITE WHERE CODVOL='PEÇAS'
UNION ALL SELECT 'TGFPAP.UNIDADEPARC',COUNT(*) FROM TGFPAP WHERE UNIDADEPARC='PEÇAS'
UNION ALL SELECT 'TGFCOI2.CODVOL',COUNT(*) FROM TGFCOI2 WHERE CODVOL='PEÇAS'
UNION ALL SELECT 'TGFGIR1.CODVOL',COUNT(*) FROM TGFGIR1 WHERE CODVOL='PEÇAS'
UNION ALL SELECT 'TGFVOA.CODVOL',COUNT(*) FROM TGFVOA WHERE CODVOL='PEÇAS'
UNION ALL SELECT 'TGFVOL.CODVOL',COUNT(*) FROM TGFVOL WHERE CODVOL='PEÇAS';

PROMPT === FIM DIAGNOSTICO UNIDADE PEÇAS ===
