-- Diagnóstico somente leitura da falha na etapa 10.
-- Execute conectado à ANDORINHA COMERCIAL como SCRIPT (F5).
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET ECHO ON

PROMPT === IDENTIDADE ===
SELECT SYS_CONTEXT('USERENV','SESSION_USER') USUARIO,
       SYS_CONTEXT('USERENV','CURRENT_SCHEMA') SCHEMA_ATUAL,
       SYS_CONTEXT('USERENV','SERVICE_NAME') SERVICO
FROM DUAL;

PROMPT === OBJETO BKP_RMD_09_TGFPRO ===
SELECT OWNER, OBJECT_NAME, OBJECT_TYPE, STATUS
FROM ALL_OBJECTS
WHERE OBJECT_NAME='BKP_RMD_09_TGFPRO';

SELECT OWNER, TABLE_NAME, TABLESPACE_NAME, NUM_ROWS
FROM ALL_TABLES
WHERE TABLE_NAME='BKP_RMD_09_TGFPRO';

PROMPT === COLUNAS ===
SELECT OWNER, TABLE_NAME, COLUMN_ID, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, DATA_PRECISION, DATA_SCALE
FROM ALL_TAB_COLUMNS
WHERE TABLE_NAME='BKP_RMD_09_TGFPRO'
ORDER BY OWNER, COLUMN_ID;

PROMPT === PRIVILEGIOS EXPLICITOS ===
SELECT GRANTEE, TABLE_SCHEMA, TABLE_NAME, GRANTOR, PRIVILEGE, GRANTABLE
FROM ALL_TAB_PRIVS
WHERE TABLE_NAME='BKP_RMD_09_TGFPRO';

PROMPT === TRIGGERS ===
SELECT OWNER, TRIGGER_NAME, STATUS, TRIGGERING_EVENT
FROM ALL_TRIGGERS
WHERE TABLE_NAME='BKP_RMD_09_TGFPRO';

PROMPT === POLITICAS DE SEGURANCA ===
SELECT OBJECT_OWNER, OBJECT_NAME, POLICY_NAME, ENABLED, SEL, INS, UPD, DEL
FROM ALL_POLICIES
WHERE OBJECT_NAME='BKP_RMD_09_TGFPRO';

PROMPT === CONTAGEM ===
DECLARE
  v_n NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_n FROM SANKHYA.BKP_RMD_09_TGFPRO;
  DBMS_OUTPUT.PUT_LINE('REGISTROS='||v_n);
END;
/

PROMPT === FIM DIAGNOSTICO ===
