-- Somente leitura. Executar na conexão ANDORINHA COMERCIAL.
SELECT SYS_CONTEXT('USERENV','SESSION_USER') USUARIO,
       SYS_CONTEXT('USERENV','CURRENT_SCHEMA') SCHEMA_ATUAL,
       SYS_CONTEXT('USERENV','SERVICE_NAME') SERVICO FROM DUAL;
SELECT OWNER, OBJECT_NAME, OBJECT_TYPE FROM ALL_OBJECTS
 WHERE OBJECT_NAME IN ('BKP_RMD_01_TSIPAR','BKP_RMD_02_TGFEMP','BKP_RMD_03_TGFTOP','RMD_CONTROLE_OBJETOS')
 ORDER BY OBJECT_NAME,OWNER;
SELECT GRANTEE, TABLE_SCHEMA, TABLE_NAME, PRIVILEGE FROM ALL_TAB_PRIVS
 WHERE TABLE_NAME IN ('BKP_RMD_01_TSIPAR','BKP_RMD_02_TGFEMP','BKP_RMD_03_TGFTOP','RMD_CONTROLE_OBJETOS','TGFTOP','TGFEMP')
 ORDER BY TABLE_NAME,GRANTEE,PRIVILEGE;
SELECT OWNER, TABLE_NAME, PRIVILEGE, GRANTABLE
  FROM USER_TAB_PRIVS
 WHERE TABLE_NAME IN ('TGFTOP','TGFEMP','BKP_RMD_02_TGFEMP','BKP_RMD_03_TGFTOP')
 ORDER BY TABLE_NAME, PRIVILEGE;
SELECT PRIVILEGE FROM SESSION_PRIVS ORDER BY PRIVILEGE;
