-- Diagnostico somente leitura para preparar o merge controlado.
SET DEFINE OFF
SET ECHO ON
SET PAGESIZE 300
SET LINESIZE 240
SET LONG 100000

PROMPT === EXEMPLO ZUMBI DOS PALMARES ===
SELECT CODBAI,NOMEBAI,CODREG FROM TSIBAI WHERE CODBAI IN (3982,506) ORDER BY CODBAI;
SELECT 'TGFPAR' TABELA,COUNT(*) QTD FROM TGFPAR WHERE CODBAI IN (3982,506)
UNION ALL SELECT 'TSICEP',COUNT(*) FROM TSICEP WHERE CODBAI IN (3982,506)
UNION ALL SELECT 'TSIEMP',COUNT(*) FROM TSIEMP WHERE CODBAI IN (3982,506)
UNION ALL SELECT 'TFPALTERFUN',COUNT(*) FROM TFPALTERFUN WHERE CODBAI IN (3982,506)
UNION ALL SELECT 'TFPFUN',COUNT(*) FROM TFPFUN WHERE CODBAI IN (3982,506);

PROMPT === MAPA DE BAIRROS ===
WITH B AS (
  SELECT CODBAI,NOMEBAI,CODREG,
    REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEBAI),
      'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇáàâãäéèêëíìîïóòôõöúùûüçÃãÕõÂâÊêÎîÔôÛû',
      'AAAAAEEEEIIIIOOOOOUUUUCAAAAAEEEEIIIIOOOOOUUUUCAAAOOAAEIIOOUU')),' {2,}',' ') NORM
  FROM TSIBAI
), M AS (
  SELECT CODBAI,NOMEBAI,CODREG,NORM,
         MIN(CODBAI) OVER(PARTITION BY NORM) CODBAI_MANTIDO,
         COUNT(*) OVER(PARTITION BY NORM) QTD
  FROM B
)
SELECT NORM,NOMEBAI CODBAI_OBSOLETO,CODBAI,CODREG,CODBAI_MANTIDO
FROM M WHERE QTD>1 AND CODBAI<>CODBAI_MANTIDO
ORDER BY NORM,CODBAI;

PROMPT === MAPA DE ENDERECOS ===
WITH E AS (
  SELECT CODEND,TIPO,NOMEEND,
    REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEEND),
      'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇáàâãäéèêëíìîïóòôõöúùûüçÃãÕõÂâÊêÎîÔôÛû',
      'AAAAAEEEEIIIIOOOOOUUUUCAAAAAEEEEIIIIOOOOOUUUUCAAAOOAAEIIOOUU')),' {2,}',' ') NORM
  FROM TSIEND
), M AS (
  SELECT CODEND,TIPO,NOMEEND,NORM,
         MIN(CODEND) OVER(PARTITION BY TIPO,NORM) CODEND_MANTIDO,
         COUNT(*) OVER(PARTITION BY TIPO,NORM) QTD
  FROM E
)
SELECT TIPO,NORM,NOMEEND CODEND_OBSOLETO,CODEND,CODEND_MANTIDO
FROM M WHERE QTD>1 AND CODEND<>CODEND_MANTIDO
ORDER BY TIPO,NORM,CODEND;

PROMPT === TABELAS COM COLUNAS CODBAI/CODEND ===
SELECT OWNER,TABLE_NAME,COLUMN_NAME
FROM ALL_TAB_COLUMNS
WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
  AND COLUMN_NAME IN ('CODBAI','CODEND')
ORDER BY COLUMN_NAME,TABLE_NAME;

PROMPT === FIM DIAGNOSTICO MAPA MERGE ===
