-- Diagnostico somente leitura antes da etapa 18 - Preferencias GOL.

SET DEFINE OFF
SET ECHO ON
SET PAGESIZE 100
SET LINESIZE 220

PROMPT === OBJETOS DA ETAPA 18 ===

SELECT N.NOME OBJETO,
       NVL(O.OBJECT_TYPE,'AUSENTE') TIPO,
       NVL(O.STATUS,'AUSENTE') STATUS
FROM (
    SELECT 'BKP_RMD_GOL_TSIPAR' NOME FROM DUAL
    UNION ALL SELECT 'BKP_RMD_GOL_TGFCGM' FROM DUAL
    UNION ALL SELECT 'BKP_RMD_GOL_TGFCMV' FROM DUAL
) N
LEFT JOIN ALL_OBJECTS O
  ON O.OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
 AND O.OBJECT_NAME=N.NOME
 AND O.OBJECT_TYPE='TABLE'
ORDER BY N.NOME;

PROMPT === PRE-CONDICOES DA ETAPA 18 ===

SELECT 'TGFCGM_ORIGEM_EMP1_1900_1' ITEM,COUNT(*) QTD
FROM TGFCGM WHERE CODEMP=1 AND ANO=1900 AND MES=1
UNION ALL
SELECT 'TGFCMV_CODCONFIG_1',COUNT(*)
FROM TGFCMV WHERE CODCONFIG=1
UNION ALL
SELECT 'TSIPAR_GOL_DIVERGENTES',COUNT(*)
FROM TSIPAR
WHERE CODUSU=0
  AND CHAVE IN ('GOL-QTDEPARC','GOL-QTDEPROD','GOL-QTDEMARC','GOL-QTDEGRUPOS',
                'GOL-QTDEVENDS','GOL-QTDEPERFIS','GOL-PERESTMED','GOL-TIPOCUSTO','PERCCUSFIXO')
  AND NVL(INTEIRO,-999)<>CASE
      WHEN CHAVE IN ('GOL-QTDEPARC','GOL-QTDEPROD','GOL-QTDEMARC','GOL-QTDEGRUPOS',
                     'GOL-QTDEVENDS','GOL-QTDEPERFIS') THEN 0
      WHEN CHAVE='GOL-PERESTMED' THEN 6
      WHEN CHAVE='GOL-TIPOCUSTO' THEN 3
      ELSE 10
  END
UNION ALL
SELECT 'TGFCGM_DESTINOS',COUNT(*) FROM TGFCGM WHERE CODEMP<>1;

PROMPT === FIM DIAGNOSTICO ETAPA 18 ===
