-- Execucao isolada da etapa 30 apos validacao do mesmo modelo na etapa 29.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET SQLBLANKLINES ON
SET ECHO ON
WHENEVER OSERROR EXIT FAILURE ROLLBACK
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

SPOOL "/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Clientes/ANDORINHA COMERCIAL/Logs/Etapa_30_Isolada.log"

PROMPT === ETAPA 30 ISOLADA ===
@@"/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Revisao Master Deploy/30_Padronizar_Enderecos.sql"

PROMPT === VALIDACAO ETAPA 30 ===
WITH E AS (
  SELECT TIPO,NOMEEND,NORM,COUNT(*) OVER(PARTITION BY TIPO,NORM) QTD_GRUPO FROM (
    SELECT TIPO,NOMEEND,REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEEND),
      'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇáàâãäéèêëíìîïóòôõöúùûüçÃãÕõÂâÊêÎîÔôÛû',
      'AAAAAEEEEIIIIOOOOOUUUUCAAAAAEEEEIIIIOOOOOUUUUCAAAOOAAEIIOOUU')),' {2,}',' ') NORM FROM TSIEND
  )
)
SELECT 'TSIEND_SEGUROS_PENDENTES' ITEM,COUNT(*) QTD FROM E
WHERE QTD_GRUPO=1 AND DECODE(NOMEEND,NORM,0,1)=1
UNION ALL
SELECT 'TSIEND_GRUPOS_COLISAO',COUNT(*) FROM (SELECT TIPO,NORM FROM E GROUP BY TIPO,NORM HAVING COUNT(*)>1);

PROMPT === FIM ETAPA 30 ISOLADA ===
SPOOL OFF
