-- Execucao isolada da etapa 29 apos validacao das colisoes.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET SQLBLANKLINES ON
SET ECHO ON
WHENEVER OSERROR EXIT FAILURE ROLLBACK
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

PROMPT === ETAPA 29 ISOLADA ===
@@"/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Revisao Master Deploy/29_Padronizar_Bairros.sql"

PROMPT === VALIDACAO ETAPA 29 ===
WITH B AS (
  SELECT NOMEBAI,NORM,COUNT(*) OVER(PARTITION BY NORM) QTD_GRUPO FROM (
    SELECT NOMEBAI,REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEBAI),
      'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇáàâãäéèêëíìîïóòôõöúùûüçÃãÕõÂâÊêÎîÔôÛû',
      'AAAAAEEEEIIIIOOOOOUUUUCAAAAAEEEEIIIIOOOOOUUUUCAAAOOAAEIIOOUU')),' {2,}',' ') NORM FROM TSIBAI
  )
)
SELECT 'TSIBAI_SEGUROS_PENDENTES' ITEM,COUNT(*) QTD FROM B
WHERE QTD_GRUPO=1 AND DECODE(NOMEBAI,NORM,0,1)=1
UNION ALL
SELECT 'TSIBAI_GRUPOS_COLISAO',COUNT(*) FROM (SELECT NORM FROM B GROUP BY NORM HAVING COUNT(*)>1);

PROMPT === FIM ETAPA 29 ISOLADA ===
