-- Finalizacao da revisao Andorinha: etapas 29 a 31.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET SQLBLANKLINES ON
SET ECHO ON
SET PAGESIZE 200
SET LINESIZE 240
WHENEVER OSERROR EXIT FAILURE ROLLBACK
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

SPOOL "/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Clientes/ANDORINHA COMERCIAL/Logs/Etapas_29_31_Estrito.log"

PROMPT === IDENTIDADE DA CONEXAO ===
SELECT SYS_CONTEXT('USERENV','SESSION_USER') USUARIO,
       SYS_CONTEXT('USERENV','CURRENT_SCHEMA') SCHEMA_ATUAL,
       SYS_CONTEXT('USERENV','SERVICE_NAME') SERVICO
FROM DUAL;

PROMPT === ETAPA 29: BAIRROS ===
@@"/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Revisao Master Deploy/29_Padronizar_Bairros.sql"

PROMPT === ETAPA 30: ENDERECOS ===
@@"/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Revisao Master Deploy/30_Padronizar_Enderecos.sql"

PROMPT === ETAPA 31: OBJETOS INVALIDOS ===
@@"/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Revisao Master Deploy/31_Recompilar_Objetos_Invalidos.sql"

PROMPT === VALIDACAO FINAL 29 A 31 ===
WITH B AS (
  SELECT NOMEBAI,NORM,COUNT(*) OVER(PARTITION BY NORM) QTD_GRUPO FROM (
    SELECT NOMEBAI,REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEBAI),
      'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇáàâãäéèêëíìîïóòôõöúùûüçÃãÕõÂâÊêÎîÔôÛû',
      'AAAAAEEEEIIIIOOOOOUUUUCAAAAAEEEEIIIIOOOOOUUUUCAAAOOAAEIIOOUU')),' {2,}',' ') NORM FROM TSIBAI
  )
)
SELECT 'TSIBAI_SEGUROS_PENDENTES' ITEM,COUNT(*) QTD FROM B
WHERE QTD_GRUPO=1 AND DECODE(NOMEBAI,NORM,0,1)=1
UNION ALL
SELECT 'TSIBAI_GRUPOS_COLISAO',COUNT(*) FROM (SELECT NORM FROM B GROUP BY NORM HAVING COUNT(*)>1)
UNION ALL
SELECT 'OBJETOS_INVALIDOS',COUNT(*) FROM ALL_OBJECTS
WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND STATUS='INVALID';

WITH E AS (
  SELECT TIPO,NOMEEND,NORM,COUNT(*) OVER(PARTITION BY TIPO,NORM) QTD_GRUPO FROM (
    SELECT TIPO,NOMEEND,REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEEND),
      'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇáàâãäéèêëíìîïóòôõöúùûüçÃãÕõÂâÊêÎîÔôÛû',
      'AAAAAEEEEIIIIOOOOOUUUUCAAAAAEEEEIIIIOOOOOUUUUCAAAOOAAEIIOOUU')),' {2,}',' ') NORM FROM TSIEND
  )
)
SELECT 'TSIEND_SEGUROS_PENDENTES' ITEM,COUNT(*) QTD FROM E
WHERE QTD_GRUPO=1 AND DECODE(NOMEEND,NORM,0,1)=1
UNION ALL
SELECT 'TSIEND_GRUPOS_COLISAO',COUNT(*) FROM (SELECT TIPO,NORM FROM E GROUP BY TIPO,NORM HAVING COUNT(*)>1);

PROMPT === LOTE 29 A 31 FINALIZADO ===
SPOOL OFF
