-- Execução isolada da etapa 17.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET SQLBLANKLINES ON
SET ECHO ON
WHENEVER OSERROR EXIT FAILURE ROLLBACK
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

PROMPT === ETAPA 17 ISOLADA ===
SELECT SYS_CONTEXT('USERENV','SESSION_USER') USUARIO,
       SYS_CONTEXT('USERENV','CURRENT_SCHEMA') SCHEMA_ATUAL,
       SYS_CONTEXT('USERENV','SERVICE_NAME') SERVICO
FROM DUAL;

VARIABLE RMD_ID_MASTER VARCHAR2(30)
BEGIN :RMD_ID_MASTER := 'RMD_RUN_20260908102607051'; END;
/

@@"/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Clientes/ANDORINHA COMERCIAL/17_Normalizar_Unidades_Andorinha.sql"

PROMPT === FIM ETAPA 17 ISOLADA ===
