-- Merge completo dos duplicados de bairros e enderecos.
-- Mantem o menor codigo e atualiza tabelas fisicas com referencias numericas.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET ECHO ON
SET SQLBLANKLINES ON
WHENEVER OSERROR EXIT FAILURE ROLLBACK
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
DECLARE
  v_id CONSTANT VARCHAR2(30):='RMD_MBE_20260908170000000';
  v_n NUMBER;v_upd NUMBER;v_left NUMBER;v_del_bai NUMBER;v_del_end NUMBER;
  v_sql VARCHAR2(32767);
BEGIN
  INSERT INTO BKP_MBE_MAP_BAI_ANDORINHA
  SELECT v_id,CODBAI,KEEP_ID FROM (
    SELECT CODBAI,MIN(CODBAI) OVER(PARTITION BY NORM) KEEP_ID,COUNT(*) OVER(PARTITION BY NORM) QTD
    FROM (SELECT CODBAI,REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEBAI),
      'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇáàâãäéèêëíìîïóòôõöúùûüçÃãÕõÂâÊêÎîÔôÛû',
      'AAAAAEEEEIIIIOOOOOUUUUCAAAAAEEEEIIIIOOOOOUUUUCAAAOOAAEIIOOUU')),' {2,}',' ') NORM FROM TSIBAI)
  ) WHERE QTD>1 AND CODBAI<>KEEP_ID;
  INSERT INTO BKP_MBE_MAP_END_ANDORINHA
  SELECT v_id,CODEND,KEEP_ID FROM (
    SELECT CODEND,MIN(CODEND) OVER(PARTITION BY TIPO,NORM) KEEP_ID,COUNT(*) OVER(PARTITION BY TIPO,NORM) QTD
    FROM (SELECT CODEND,TIPO,REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEEND),
      'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇáàâãäéèêëíìîïóòôõöúùûüçÃãÕõÂâÊêÎîÔôÛû',
      'AAAAAEEEEIIIIOOOOOUUUUCAAAAAEEEEIIIIOOOOOUUUUCAAAOOAAEIIOOUU')),' {2,}',' ') NORM FROM TSIEND)
  ) WHERE QTD>1 AND CODEND<>KEEP_ID;
  SELECT COUNT(*) INTO v_n FROM BKP_MBE_MAP_BAI_ANDORINHA WHERE ID_EXECUCAO=v_id;
  DBMS_OUTPUT.PUT_LINE('BAIRROS_OBSOLETOS='||v_n);
  SELECT COUNT(*) INTO v_n FROM BKP_MBE_MAP_END_ANDORINHA WHERE ID_EXECUCAO=v_id;
  DBMS_OUTPUT.PUT_LINE('ENDERECOS_OBSOLETOS='||v_n);
  INSERT INTO BKP_RMD_PAD_TSIBAI
  SELECT v_id,SYSTIMESTAMP,SYS_CONTEXT('USERENV','SESSION_USER'),ROWIDTOCHAR(B.ROWID),B.*
  FROM TSIBAI B
  WHERE B.CODBAI IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_BAI_ANDORINHA WHERE ID_EXECUCAO=v_id)
     OR B.CODBAI IN (SELECT COD_MANTIDO FROM BKP_MBE_MAP_BAI_ANDORINHA WHERE ID_EXECUCAO=v_id);
  INSERT INTO BKP_RMD_PAD_TSIEND
  SELECT v_id,SYSTIMESTAMP,SYS_CONTEXT('USERENV','SESSION_USER'),ROWIDTOCHAR(E.ROWID),E.*
  FROM TSIEND E
  WHERE E.CODEND IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_END_ANDORINHA WHERE ID_EXECUCAO=v_id)
     OR E.CODEND IN (SELECT COD_MANTIDO FROM BKP_MBE_MAP_END_ANDORINHA WHERE ID_EXECUCAO=v_id);
  INSERT INTO BKP_MBE_REF_ANDORINHA
  SELECT v_id,'TGFCPL','CODBAIENTREGA',ROWIDTOCHAR(T.ROWID),TO_CHAR(T.CODBAIENTREGA),TO_CHAR(M.COD_MANTIDO)
  FROM TGFCPL T JOIN BKP_MBE_MAP_BAI_ANDORINHA M
    ON M.ID_EXECUCAO=v_id AND T.CODBAIENTREGA=M.COD_OBSOLETO;
  UPDATE TGFCPL T SET T.CODBAIENTREGA=(SELECT M.COD_MANTIDO FROM BKP_MBE_MAP_BAI_ANDORINHA M
    WHERE M.ID_EXECUCAO=v_id AND M.COD_OBSOLETO=T.CODBAIENTREGA)
  WHERE EXISTS (SELECT 1 FROM BKP_MBE_MAP_BAI_ANDORINHA M
    WHERE M.ID_EXECUCAO=v_id AND M.COD_OBSOLETO=T.CODBAIENTREGA);
  DBMS_OUTPUT.PUT_LINE('REFERENCIA_ATUALIZADA=TGFCPL.CODBAIENTREGA; QTD='||SQL%ROWCOUNT);
  INSERT INTO BKP_MBE_REF_ANDORINHA
  SELECT v_id,'TGFCPL','CODENDENTREGA',ROWIDTOCHAR(T.ROWID),TO_CHAR(T.CODENDENTREGA),TO_CHAR(M.COD_MANTIDO)
  FROM TGFCPL T JOIN BKP_MBE_MAP_END_ANDORINHA M
    ON M.ID_EXECUCAO=v_id AND T.CODENDENTREGA=M.COD_OBSOLETO;
  UPDATE TGFCPL T SET T.CODENDENTREGA=(SELECT M.COD_MANTIDO FROM BKP_MBE_MAP_END_ANDORINHA M
    WHERE M.ID_EXECUCAO=v_id AND M.COD_OBSOLETO=T.CODENDENTREGA)
  WHERE EXISTS (SELECT 1 FROM BKP_MBE_MAP_END_ANDORINHA M
    WHERE M.ID_EXECUCAO=v_id AND M.COD_OBSOLETO=T.CODENDENTREGA);
  DBMS_OUTPUT.PUT_LINE('REFERENCIA_ATUALIZADA=TGFCPL.CODENDENTREGA; QTD='||SQL%ROWCOUNT);

  FOR r IN (
    SELECT C.TABLE_NAME,C.COLUMN_NAME
    FROM ALL_TAB_COLUMNS C JOIN ALL_OBJECTS O ON O.OWNER=C.OWNER AND O.OBJECT_NAME=C.TABLE_NAME AND O.OBJECT_TYPE='TABLE'
    WHERE C.OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND C.COLUMN_NAME IN ('CODBAI','CODEND')
      AND C.TABLE_NAME NOT LIKE 'BKP\_%' ESCAPE '\' AND C.TABLE_NAME NOT LIKE 'RMD\_%' ESCAPE '\'
      AND C.TABLE_NAME NOT IN ('TSIBAI','TSIEND')
    ORDER BY C.TABLE_NAME,C.COLUMN_NAME
  ) LOOP
    IF r.COLUMN_NAME='CODBAI' THEN
      v_sql:='INSERT INTO BKP_MBE_REF_ANDORINHA SELECT :1,:2,:3,ROWIDTOCHAR(T.ROWID),TO_CHAR(T.'||r.COLUMN_NAME||'),TO_CHAR(M.COD_MANTIDO) FROM '||r.TABLE_NAME||' T JOIN BKP_MBE_MAP_BAI_ANDORINHA M ON M.ID_EXECUCAO=:1 AND T.'||r.COLUMN_NAME||'=M.COD_OBSOLETO';
      EXECUTE IMMEDIATE v_sql USING v_id,r.TABLE_NAME,r.COLUMN_NAME,v_id;
      v_sql:='UPDATE '||r.TABLE_NAME||' T SET T.'||r.COLUMN_NAME||'=(SELECT M.COD_MANTIDO FROM BKP_MBE_MAP_BAI_ANDORINHA M WHERE M.ID_EXECUCAO=:1 AND M.COD_OBSOLETO=T.'||r.COLUMN_NAME||') WHERE EXISTS (SELECT 1 FROM BKP_MBE_MAP_BAI_ANDORINHA M WHERE M.ID_EXECUCAO=:1 AND M.COD_OBSOLETO=T.'||r.COLUMN_NAME||')';
    ELSE
      v_sql:='INSERT INTO BKP_MBE_REF_ANDORINHA SELECT :1,:2,:3,ROWIDTOCHAR(T.ROWID),TO_CHAR(T.'||r.COLUMN_NAME||'),TO_CHAR(M.COD_MANTIDO) FROM '||r.TABLE_NAME||' T JOIN BKP_MBE_MAP_END_ANDORINHA M ON M.ID_EXECUCAO=:1 AND T.'||r.COLUMN_NAME||'=M.COD_OBSOLETO';
      EXECUTE IMMEDIATE v_sql USING v_id,r.TABLE_NAME,r.COLUMN_NAME,v_id;
      v_sql:='UPDATE '||r.TABLE_NAME||' T SET T.'||r.COLUMN_NAME||'=(SELECT M.COD_MANTIDO FROM BKP_MBE_MAP_END_ANDORINHA M WHERE M.ID_EXECUCAO=:1 AND M.COD_OBSOLETO=T.'||r.COLUMN_NAME||') WHERE EXISTS (SELECT 1 FROM BKP_MBE_MAP_END_ANDORINHA M WHERE M.ID_EXECUCAO=:1 AND M.COD_OBSOLETO=T.'||r.COLUMN_NAME||')';
    END IF;
    EXECUTE IMMEDIATE v_sql USING v_id,v_id;
    DBMS_OUTPUT.PUT_LINE('REFERENCIA_ATUALIZADA='||r.TABLE_NAME||'.'||r.COLUMN_NAME||'; QTD='||SQL%ROWCOUNT);
  END LOOP;
  SELECT COUNT(*) INTO v_left FROM TGFCPL T
   WHERE T.CODBAIENTREGA IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_BAI_ANDORINHA WHERE ID_EXECUCAO=v_id);
  IF v_left>0 THEN RAISE_APPLICATION_ERROR(-20820,'Ainda existem referencias em TGFCPL.CODBAIENTREGA='||v_left);END IF;
  SELECT COUNT(*) INTO v_left FROM TGFCPL T
   WHERE T.CODENDENTREGA IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_END_ANDORINHA WHERE ID_EXECUCAO=v_id);
  IF v_left>0 THEN RAISE_APPLICATION_ERROR(-20820,'Ainda existem referencias em TGFCPL.CODENDENTREGA='||v_left);END IF;
  FOR r IN (
    SELECT C.TABLE_NAME,C.COLUMN_NAME
    FROM ALL_TAB_COLUMNS C JOIN ALL_OBJECTS O ON O.OWNER=C.OWNER AND O.OBJECT_NAME=C.TABLE_NAME AND O.OBJECT_TYPE='TABLE'
    WHERE C.OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND C.COLUMN_NAME IN ('CODBAI','CODEND')
      AND C.TABLE_NAME NOT LIKE 'BKP\_%' ESCAPE '\' AND C.TABLE_NAME NOT LIKE 'RMD\_%' ESCAPE '\'
      AND C.TABLE_NAME NOT IN ('TSIBAI','TSIEND')
  ) LOOP
    IF r.COLUMN_NAME='CODBAI' THEN
      v_sql:='SELECT COUNT(*) FROM '||r.TABLE_NAME||' T WHERE T.'||r.COLUMN_NAME||' IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_BAI_ANDORINHA WHERE ID_EXECUCAO=:1)';
    ELSE
      v_sql:='SELECT COUNT(*) FROM '||r.TABLE_NAME||' T WHERE T.'||r.COLUMN_NAME||' IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_END_ANDORINHA WHERE ID_EXECUCAO=:1)';
    END IF;
    EXECUTE IMMEDIATE v_sql INTO v_left USING v_id;
    IF v_left>0 THEN RAISE_APPLICATION_ERROR(-20820,'Ainda existem referencias em '||r.TABLE_NAME||'.'||r.COLUMN_NAME||'='||v_left);END IF;
  END LOOP;
  DELETE FROM TSIBAI WHERE CODBAI IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_BAI_ANDORINHA WHERE ID_EXECUCAO=v_id);
  v_del_bai:=SQL%ROWCOUNT;
  DELETE FROM TSIEND WHERE CODEND IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_END_ANDORINHA WHERE ID_EXECUCAO=v_id);
  v_del_end:=SQL%ROWCOUNT;
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('BAIRROS_EXCLUIDOS='||v_del_bai||'; ENDERECOS_EXCLUIDOS='||v_del_end);
  DBMS_OUTPUT.PUT_LINE('STATUS=CONCLUIDO; ID_EXECUCAO='||v_id);
EXCEPTION WHEN OTHERS THEN ROLLBACK;RAISE;
END;
/
