-- Merge controlado do bairro CODBAI 3982 para 506.
-- Atualiza somente TSICEP, que possui 27 referencias ao codigo obsoleto 3982.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET ECHO ON
WHENEVER OSERROR EXIT FAILURE ROLLBACK
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

PROMPT === MERGE ZUMBI 3982 -> 506 ===
DECLARE
  v_id CONSTANT VARCHAR2(30):='RMD_ZUMBI_20260908160000000';
  v_bai NUMBER;v_ref NUMBER;v_upd NUMBER;v_del NUMBER;v_rest NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_bai FROM TSIBAI WHERE CODBAI=3982 AND NOMEBAI='Zumbí dos Palmares' AND CODREG=0;
  IF v_bai<>1 THEN RAISE_APPLICATION_ERROR(-20801,'Bairro origem 3982 divergente.');END IF;
  SELECT COUNT(*) INTO v_bai FROM TSIBAI WHERE CODBAI=506 AND NOMEBAI='Zumbi dos Palmares' AND CODREG=0;
  IF v_bai<>1 THEN RAISE_APPLICATION_ERROR(-20802,'Bairro destino 506 divergente.');END IF;
  SELECT COUNT(*) INTO v_ref FROM TSICEP WHERE CODBAI=3982;
  IF v_ref<>27 THEN RAISE_APPLICATION_ERROR(-20803,'Referencias TSICEP divergentes: esperado=27; obtido='||v_ref);END IF;

  INSERT INTO BKP_RMD_PAD_TSIBAI
  SELECT v_id,SYSTIMESTAMP,SYS_CONTEXT('USERENV','SESSION_USER'),ROWIDTOCHAR(ROWID),B.*
  FROM TSIBAI B WHERE CODBAI IN (3982,506);
  IF SQL%ROWCOUNT<>2 THEN RAISE_APPLICATION_ERROR(-20804,'Backup TSIBAI divergente.');END IF;

  INSERT INTO BKP_MBE_ZUMBI_TSICEP
  SELECT v_id,ROWIDTOCHAR(ROWID),T.* FROM TSICEP T WHERE CODBAI=3982;
  IF SQL%ROWCOUNT<>27 THEN RAISE_APPLICATION_ERROR(-20805,'Backup TSICEP divergente.');END IF;

  UPDATE TSICEP SET CODBAI=506 WHERE CODBAI=3982;
  v_upd:=SQL%ROWCOUNT;
  DELETE FROM TSIBAI WHERE CODBAI=3982;
  v_del:=SQL%ROWCOUNT;
  UPDATE TSIBAI SET NOMEBAI='ZUMBI DOS PALMARES' WHERE CODBAI=506;

  SELECT COUNT(*) INTO v_rest FROM TSICEP WHERE CODBAI=3982;
  IF v_upd<>27 OR v_del<>1 OR v_rest<>0 THEN
    RAISE_APPLICATION_ERROR(-20806,'Validacao do merge divergente.');
  END IF;
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('STATUS=CONCLUIDO; ID_EXECUCAO='||v_id||'; TSICEP_ATUALIZADOS='||v_upd||'; TSIBAI_EXCLUIDO='||v_del||'; REFERENCIAS_RESTANTES='||v_rest);
EXCEPTION WHEN OTHERS THEN ROLLBACK;RAISE;
END;
/

SELECT CODBAI,NOMEBAI,CODREG FROM TSIBAI WHERE CODBAI IN (3982,506);
SELECT COUNT(*) TSICEP_RESTANTES_3982 FROM TSICEP WHERE CODBAI=3982;
PROMPT === FIM MERGE ZUMBI ===
