-- Diagnóstico isolado da etapa 08 da nova revisão.
-- Execute conectado à ANDORINHA COMERCIAL como SCRIPT (F5).
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET SQLBLANKLINES ON
SET ECHO ON
WHENEVER OSERROR EXIT FAILURE ROLLBACK
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

PROMPT === ETAPA 08 ISOLADA ===
SELECT SYS_CONTEXT('USERENV','SESSION_USER') USUARIO,
       SYS_CONTEXT('USERENV','CURRENT_SCHEMA') SCHEMA_ATUAL,
       SYS_CONTEXT('USERENV','SERVICE_NAME') SERVICO,
       SYS_CONTEXT('USERENV','DB_NAME') DB_NAME,
       SYS_CONTEXT('USERENV','INSTANCE_NAME') INSTANCE_NAME
FROM DUAL;

SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, DATA_PRECISION, DATA_SCALE
FROM ALL_TAB_COLUMNS
WHERE OWNER = SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
  AND TABLE_NAME = 'TGFCAB'
  AND COLUMN_NAME IN ('NUMPROTOC','NUMPROTOCCTE')
ORDER BY COLUMN_NAME;

VARIABLE RMD_ID_MASTER VARCHAR2(30)
BEGIN :RMD_ID_MASTER := 'RMD_RUN_20260908102607051'; END;
/

PROMPT === EXECUTANDO 08_PREENCHER_PROTOCOLOS_DOCUMENTOS_LEGADOS ===
@@"/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Revisao Master Deploy/08_Preencher_Protocolos_Documentos_Legados.sql"

PROMPT === OBJETO GERADO E CONTAGEM ===
SELECT OWNER, TABLE_NAME
FROM ALL_TABLES
WHERE OWNER = SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
  AND TABLE_NAME = 'BKP_RMD_07_TGFCAB';

DECLARE
  v_n NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_n FROM BKP_RMD_07_TGFCAB;
  DBMS_OUTPUT.PUT_LINE('BKP_RMD_07_TGFCAB_REGISTROS='||v_n);
END;
/

PROMPT === FIM ETAPA 08 ISOLADA ===
