-- Pre-check somente leitura antes de uma nova Revisao Master Deploy.
-- Nao cria objetos e nao altera dados.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

PROMPT === PRE-CHECK NOVA REVISAO ANDORINHA ===
SELECT SYS_CONTEXT('USERENV','SESSION_USER') USUARIO,
       SYS_CONTEXT('USERENV','CURRENT_SCHEMA') SCHEMA_ATUAL,
       SYS_CONTEXT('USERENV','SERVICE_NAME') SERVICO
  FROM DUAL;

SELECT CODEMP, RAZAOSOCIAL FROM TSIEMP WHERE CODEMP=1;

SELECT 'TSIPAR_FILTROS_PORTAIS_NAO_NULOS' ITEM, COUNT(*) QTD
  FROM TSIPAR
 WHERE CHAVE IN ('MAXDIASPORTAIS','MAXDIASPORTVEND','MAXDIASPORTCOMP','MAXDIASMOVFIN')
   AND INTEIRO IS NOT NULL
UNION ALL
SELECT 'TGFEMP_FILIAIS_DANFE_DIVERGENTES', COUNT(*)
  FROM TGFEMP F JOIN TGFEMP M ON M.CODEMP=1
 WHERE F.CODEMP<>1
   AND (NVL(F.CODMODDANFESIMPLIFNFE,-1)<>NVL(M.CODMODDANFESIMPLIFNFE,-1)
     OR NVL(F.CONTINGENCIANFE,'?')<>NVL(M.CONTINGENCIANFE,'?')
     OR NVL(F.ENVIOSINCRONONFE,'?')<>NVL(M.ENVIOSINCRONONFE,'?'))
UNION ALL
SELECT 'TGFTOP_DEVOLUCAO_PRECIFICA_DIFERENTE', COUNT(*)
  FROM TGFTOP WHERE TIPMOV='D' AND NVL(PRECIFICA,'?')<>'N'
UNION ALL
SELECT 'TGFPRO_GIRO_DIFERENTE', COUNT(*)
  FROM TGFPRO WHERE USOPROD IN ('V','R') AND NVL(CALCULOGIRO,'?')<>'G'
UNION ALL
SELECT 'TGFTPV_PARCELAS_DIFERENTES', COUNT(*)
  FROM TGFTPV WHERE NVL(NROPARCELAS,-1)<>0
UNION ALL
SELECT 'TSICFG_TOTAL', COUNT(*) FROM TSICFG
UNION ALL
SELECT 'TSIBAI_TOTAL', COUNT(*) FROM TSIBAI
UNION ALL
SELECT 'TSIEND_TOTAL', COUNT(*) FROM TSIEND
ORDER BY 1;

PROMPT === FIM PRE-CHECK ===
