-- Preparacao somente estrutural do merge 3982 -> 506.
SET DEFINE OFF
SET ECHO ON
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

CREATE TABLE BKP_MBE_ZUMBI_TSICEP AS
SELECT CAST(NULL AS VARCHAR2(30)) ID_EXECUCAO,
       CAST(NULL AS VARCHAR2(30)) ROWID_ORIGINAL,
       T.*
FROM TSICEP T WHERE 1=0;

SELECT TABLE_NAME FROM USER_TABLES WHERE TABLE_NAME='BKP_MBE_ZUMBI_TSICEP';
PROMPT === PREPARACAO BACKUP ZUMBI CONCLUIDA ===
