-- Preparacao pontual da etapa 17 na Andorinha.
-- O diagnostico confirmou que somente BKP_RMD_UNID_MAP esta ausente.

SET DEFINE OFF
SET ECHO ON

PROMPT === CRIAR BKP_RMD_UNID_MAP ===

CREATE TABLE BKP_RMD_UNID_MAP AS
SELECT CAST(NULL AS VARCHAR2(30))  ID_EXECUCAO,
       CAST(NULL AS TIMESTAMP)     DH_EXECUCAO,
       CAST(NULL AS VARCHAR2(128)) USUARIO_EXECUCAO,
       M.*
FROM RMD_MAP_UNIDADES M
WHERE 1=0;

SELECT TABLE_NAME, STATUS
FROM ALL_TABLES
WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
  AND TABLE_NAME='BKP_RMD_UNID_MAP';

PROMPT === FIM PREPARACAO ETAPA 17 ===
