-- Cria estruturas persistentes para o merge completo.
SET DEFINE OFF
SET ECHO ON
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
CREATE TABLE BKP_MBE_MAP_BAI_ANDORINHA (ID_EXECUCAO VARCHAR2(30),COD_OBSOLETO NUMBER,COD_MANTIDO NUMBER);
CREATE TABLE BKP_MBE_MAP_END_ANDORINHA (ID_EXECUCAO VARCHAR2(30),COD_OBSOLETO NUMBER,COD_MANTIDO NUMBER);
CREATE TABLE BKP_MBE_REF_ANDORINHA (
 ID_EXECUCAO VARCHAR2(30),TABLE_NAME VARCHAR2(128),COLUMN_NAME VARCHAR2(128),
 ROWID_ORIGINAL VARCHAR2(30),VALOR_ANTES VARCHAR2(100),VALOR_DEPOIS VARCHAR2(100));
SELECT TABLE_NAME FROM USER_TABLES WHERE TABLE_NAME LIKE 'BKP_MBE%ANDORINHA';
PROMPT === PREPARACAO MERGE COMPLETO CONCLUIDA ===
