-- Preserva a referência Eletrika atualmente carregada em TSICFG.
-- Somente cópia; não altera TSICFG.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET ECHO ON
WHENEVER OSERROR EXIT FAILURE ROLLBACK
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

DECLARE
  v_existe NUMBER;
  v_n NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_existe
  FROM ALL_TABLES
  WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
    AND TABLE_NAME='BKP_RMD_TSICFG_ELETRIKA';
  IF v_existe = 0 THEN
    EXECUTE IMMEDIATE q'[
    CREATE TABLE BKP_RMD_TSICFG_ELETRIKA AS
    SELECT T.* FROM TSICFG T WHERE 1=0
    ]';
  ELSE
    EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM BKP_RMD_TSICFG_ELETRIKA' INTO v_n;
    IF v_n > 0 THEN
      RAISE_APPLICATION_ERROR(-20711,'BKP_RMD_TSICFG_ELETRIKA ja possui dados. Nao sobrescrito.');
    END IF;
  END IF;

END;
/

INSERT INTO BKP_RMD_TSICFG_ELETRIKA SELECT T.* FROM TSICFG T;
COMMIT;
DBMS_OUTPUT.PUT_LINE('TSICFG_ELETRIKA_BACKUP='||SQL%ROWCOUNT);

SELECT COUNT(*) TSICFG_ELETRIKA_BACKUP FROM BKP_RMD_TSICFG_ELETRIKA;
