-- Diagnostico somente leitura para resolver divergencia de schema/instancia.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
PROMPT === RASTREIO OBJETOS REVISAO ===
SELECT SYS_CONTEXT('USERENV','SESSION_USER') USUARIO,
       SYS_CONTEXT('USERENV','CURRENT_SCHEMA') SCHEMA_ATUAL,
       SYS_CONTEXT('USERENV','SERVICE_NAME') SERVICO,
       SYS_CONTEXT('USERENV','DB_NAME') DB_NAME,
       SYS_CONTEXT('USERENV','INSTANCE_NAME') INSTANCE_NAME
  FROM DUAL;

SELECT OWNER, TABLE_NAME
  FROM ALL_TABLES
 WHERE TABLE_NAME LIKE 'BKP_RMD%'
    OR TABLE_NAME IN ('RMD_CONTROLE_OBJETOS','RMD_MAP_UNIDADES')
 ORDER BY OWNER, TABLE_NAME;

SELECT OWNER, OBJECT_TYPE, OBJECT_NAME, STATUS
  FROM ALL_OBJECTS
 WHERE (OBJECT_NAME LIKE 'BKP_RMD%' OR OBJECT_NAME IN ('RMD_CONTROLE_OBJETOS','RMD_MAP_UNIDADES'))
 ORDER BY OWNER, OBJECT_TYPE, OBJECT_NAME;
PROMPT === FIM RASTREIO ===
