-- Restaura o estado original da Andorinha antes do teste seletivo.
-- ID confirmado: RMD_CFG_20260908110650288 (861 registros).
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET ECHO ON
WHENEVER OSERROR EXIT FAILURE ROLLBACK
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

DECLARE
  v_backup NUMBER;
  v_atual NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_backup
  FROM BKP_RMD_TSICFG
  WHERE ID_EXECUCAO='RMD_CFG_20260908110650288';

  IF v_backup <> 861 THEN
    RAISE_APPLICATION_ERROR(-20731,'Backup esperado de 861 registros nao encontrado.');
  END IF;

  DELETE FROM TSICFG;

  INSERT INTO TSICFG (CHAVE,CODUSU,TIPO,CONFIG,CHAVEPAI)
  SELECT B.CHAVE,B.CODUSU,B.TIPO,B.CONFIG,B.CHAVEPAI
  FROM BKP_RMD_TSICFG B
  WHERE B.ID_EXECUCAO='RMD_CFG_20260908110650288';

  v_atual:=SQL%ROWCOUNT;
  IF v_atual <> v_backup THEN
    RAISE_APPLICATION_ERROR(-20732,'Restauracao divergente: backup='||v_backup||', atual='||v_atual);
  END IF;

  COMMIT;
  DBMS_OUTPUT.PUT_LINE('TSICFG_RESTAURADA='||v_atual);
END;
/

SELECT COUNT(*) TSICFG_ATUAL FROM TSICFG;
