-- Teste mínimo, somente diagnóstico; termina com ROLLBACK.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET ECHO ON
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

PROMPT === TESTE LEITURA TGFPRO ===
DECLARE v_n NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_n
  FROM TGFPRO
  WHERE USOPROD IN ('V','R') AND NVL(ICMSGERENCIA,'?')<>'S';
  DBMS_OUTPUT.PUT_LINE('TGFPRO_DIVERGENTES='||v_n);
END;
/

PROMPT === TESTE INSERT BACKUP SEM REGISTROS ===
INSERT INTO BKP_RMD_09_TGFPRO
  (ID_EXECUCAO,DH_EXECUCAO,USUARIO_EXECUCAO,ROWID_ORIGINAL,VALOR_ANTES,VALOR_DEPOIS)
SELECT 'RMD_TESTE',SYSTIMESTAMP,SYS_CONTEXT('USERENV','SESSION_USER'),ROWIDTOCHAR(ROWID),ICMSGERENCIA,'S'
FROM TGFPRO
WHERE 1=0;

PROMPT === TESTE INSERT BACKUP COM UMA LINHA ===
INSERT INTO BKP_RMD_09_TGFPRO
  (ID_EXECUCAO,DH_EXECUCAO,USUARIO_EXECUCAO,ROWID_ORIGINAL,VALOR_ANTES,VALOR_DEPOIS)
SELECT 'RMD_TESTE',SYSTIMESTAMP,SYS_CONTEXT('USERENV','SESSION_USER'),ROWIDTOCHAR(ROWID),ICMSGERENCIA,'S'
FROM TGFPRO
WHERE USOPROD IN ('V','R') AND NVL(ICMSGERENCIA,'?')<>'S'
  AND ROWNUM=1;

DBMS_OUTPUT.PUT_LINE('TESTE_INSERT_OK');
ROLLBACK;
PROMPT === FIM TESTE ===
