-- Diagnóstico mínimo da etapa 13; termina com ROLLBACK.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET ECHO ON
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

PROMPT === LEITURA TGFTOP ===
DECLARE v_n NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_n FROM TGFTOP;
  DBMS_OUTPUT.PUT_LINE('TGFTOP_TOTAL='||v_n);
END;
/

PROMPT === INSERT BACKUP SEM LINHAS ===
INSERT INTO BKP_RMD_12_TGFTOP
 (ID_EXECUCAO,DH_EXECUCAO,USUARIO_EXECUCAO,ROWID_ORIGINAL,GOLSINAL_ANTES,GOLMPSINAL_ANTES,GOLDEV_ANTES,ANALISEGIRO_ANTES,ATUALULTIMAVEND_ANTES,ATUALULTIMACOMP_ANTES)
SELECT 'RMD_TESTE',SYSTIMESTAMP,SYS_CONTEXT('USERENV','SESSION_USER'),ROWIDTOCHAR(ROWID),GOLSINAL,GOLMPSINAL,GOLDEV,ANALISEGIRO,ATUALULTIMAVEND,ATUALULTIMACOMP
FROM TGFTOP WHERE 1=0;

PROMPT === INSERT BACKUP UMA LINHA ===
INSERT INTO BKP_RMD_12_TGFTOP
 (ID_EXECUCAO,DH_EXECUCAO,USUARIO_EXECUCAO,ROWID_ORIGINAL,GOLSINAL_ANTES,GOLMPSINAL_ANTES,GOLDEV_ANTES,ANALISEGIRO_ANTES,ATUALULTIMAVEND_ANTES,ATUALULTIMACOMP_ANTES)
SELECT 'RMD_TESTE',SYSTIMESTAMP,SYS_CONTEXT('USERENV','SESSION_USER'),ROWIDTOCHAR(ROWID),GOLSINAL,GOLMPSINAL,GOLDEV,ANALISEGIRO,ATUALULTIMAVEND,ATUALULTIMACOMP
FROM TGFTOP WHERE ROWNUM=1;

DBMS_OUTPUT.PUT_LINE('TESTE_INSERT_OK');
ROLLBACK;
PROMPT === FIM TESTE ===
