-- Corrige somente DTVENC dos financeiros da TOP 1128 usando a tag dVenc do XML.
-- Nao cria financeiros e nao altera notas sem dVenc valido.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET ECHO ON
SET SQLBLANKLINES ON
WHENEVER OSERROR EXIT FAILURE ROLLBACK
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
DECLARE
  v_id CONSTANT VARCHAR2(30):='RMD_FIN1128_20260908180000000';
  v_exists NUMBER; v_bkp NUMBER; v_upd NUMBER; v_owner VARCHAR2(128); v_sql VARCHAR2(32767);
BEGIN
  SELECT COUNT(*) INTO v_exists FROM ALL_TABLES
   WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
     AND TABLE_NAME='BKP_RMD_FIN_1128';
  IF v_exists=0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE BKP_RMD_FIN_1128 ('||
      'ID_EXECUCAO VARCHAR2(30),NUFIN NUMBER,NUNOTA NUMBER,'||
      'DTVENC_ANTES DATE,DTVENC_XML DATE)';
  END IF;
  SELECT OWNER INTO v_owner FROM ALL_TABLES WHERE TABLE_NAME='BKP_RMD_FIN_1128' AND ROWNUM=1;
  v_sql:='INSERT INTO '||v_owner||'.BKP_RMD_FIN_1128 SELECT :1,F.NUFIN,F.NUNOTA,F.DTVENC,TO_DATE(FNC_BUSCA_TAG_XML_GERAL(F.NUNOTA,''dVenc''),''YYYY-MM-DD'') FROM TGFFIN F WHERE F.CODTIPOPER=1128 AND REGEXP_LIKE(FNC_BUSCA_TAG_XML_GERAL(F.NUNOTA,''dVenc''),''^[0-9]{4}-[0-9]{2}-[0-9]{2}$'') AND (F.DTVENC IS NULL OR F.DTVENC<>TO_DATE(FNC_BUSCA_TAG_XML_GERAL(F.NUNOTA,''dVenc''),''YYYY-MM-DD''))';
  EXECUTE IMMEDIATE v_sql USING v_id;
  v_bkp:=SQL%ROWCOUNT;
  UPDATE TGFFIN F SET F.DTVENC=TO_DATE(FNC_BUSCA_TAG_XML_GERAL(F.NUNOTA,'dVenc'),'YYYY-MM-DD')
   WHERE F.CODTIPOPER=1128
     AND REGEXP_LIKE(FNC_BUSCA_TAG_XML_GERAL(F.NUNOTA,'dVenc'),'^[0-9]{4}-[0-9]{2}-[0-9]{2}$')
     AND (F.DTVENC IS NULL OR F.DTVENC<>TO_DATE(FNC_BUSCA_TAG_XML_GERAL(F.NUNOTA,'dVenc'),'YYYY-MM-DD'));
  v_upd:=SQL%ROWCOUNT;
  IF v_bkp<>v_upd THEN RAISE_APPLICATION_ERROR(-20901,'Backup e update divergiram: backup='||v_bkp||'; update='||v_upd); END IF;
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('STATUS=CONCLUIDO; ID_EXECUCAO='||v_id||'; BACKUP='||v_bkp||'; ATUALIZADOS='||v_upd);
EXCEPTION WHEN OTHERS THEN ROLLBACK; RAISE;
END;
/
SELECT COUNT(*) AS FINANCEIROS_TOP_1128_SEM_DVENC_XML
  FROM TGFFIN F
 WHERE F.CODTIPOPER=1128
   AND NOT REGEXP_LIKE(FNC_BUSCA_TAG_XML_GERAL(F.NUNOTA,'dVenc'),'^[0-9]{4}-[0-9]{2}-[0-9]{2}$');
