-- Validação somente leitura após o lote 11-31.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET ECHO ON

PROMPT === IDENTIDADE ===
SELECT SYS_CONTEXT('USERENV','SESSION_USER') USUARIO,
       SYS_CONTEXT('USERENV','CURRENT_SCHEMA') SCHEMA_ATUAL,
       SYS_CONTEXT('USERENV','SERVICE_NAME') SERVICO
FROM DUAL;

PROMPT === CONTROLE E BACKUPS ===
SELECT OWNER, OBJECT_NAME, OBJECT_TYPE, STATUS
FROM ALL_OBJECTS
WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
  AND (OBJECT_NAME LIKE 'RMD%' OR OBJECT_NAME LIKE 'BKP_RMD%')
ORDER BY OBJECT_NAME;

PROMPT === CONTAGENS PRINCIPAIS ===
SELECT 'TSICFG' OBJETO, COUNT(*) QTD FROM TSICFG
UNION ALL SELECT 'TGFPRO', COUNT(*) FROM TGFPRO
UNION ALL SELECT 'TGFTOP', COUNT(*) FROM TGFTOP
UNION ALL SELECT 'TGFPAR', COUNT(*) FROM TGFPAR
UNION ALL SELECT 'TSIBAI', COUNT(*) FROM TSIBAI
UNION ALL SELECT 'TSIEND', COUNT(*) FROM TSIEND
ORDER BY 1;

PROMPT === FIM VALIDACAO ===
