-- Validação somente leitura da etapa 16.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET ECHO ON

PROMPT === VALIDACAO ETAPA 16 ===
SELECT SYS_CONTEXT('USERENV','SESSION_USER') USUARIO,
       SYS_CONTEXT('USERENV','CURRENT_SCHEMA') SCHEMA_ATUAL,
       SYS_CONTEXT('USERENV','SERVICE_NAME') SERVICO
FROM DUAL;

SELECT 'TSICFG_ATUAL' OBJETO, COUNT(*) QTD FROM TSICFG
UNION ALL
SELECT 'BKP_RMD_TSICFG', COUNT(*) FROM BKP_RMD_TSICFG;

SELECT ID_EXECUCAO, COUNT(*) QTD
FROM BKP_RMD_TSICFG
GROUP BY ID_EXECUCAO
ORDER BY ID_EXECUCAO;

PROMPT === FIM VALIDACAO ETAPA 16 ===
