-- Preflight somente leitura da Revisao Master Deploy - PRODUTOS ALHEIRO LTDA.
-- Nao contem senha, credenciais ou comandos de alteracao.
SET DEFINE OFF
SET ECHO OFF
SET FEEDBACK ON
SET HEADING ON
SET LINESIZE 160
SET LONG 1000
SET PAGESIZE 500
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

PROMPT === PRECHECK RMD / IDENTIDADE DA SESSAO ===
SELECT SYS_CONTEXT('USERENV','SESSION_USER') USUARIO_SESSAO,
       SYS_CONTEXT('USERENV','CURRENT_SCHEMA') SCHEMA_ATUAL,
       SYS_CONTEXT('USERENV','SERVICE_NAME') SERVICE_NAME,
       SYS_CONTEXT('USERENV','DB_NAME') DB_NAME,
       SYS_CONTEXT('USERENV','INSTANCE_NAME') INSTANCE_NAME,
       SYS_CONTEXT('USERENV','IP_ADDRESS') IP_ORIGEM
  FROM DUAL;

SELECT CASE WHEN UPPER(SYS_CONTEXT('USERENV','SESSION_USER'))='FRANCISCO_JUNIOR'
            THEN 'OK' ELSE 'BLOQUEAR' END USUARIO_ESPERADO,
       CASE WHEN UPPER(SYS_CONTEXT('USERENV','SERVICE_NAME'))='ALHEIROPRD.SANKHYACLOUD.COM.BR'
            THEN 'OK' ELSE 'BLOQUEAR' END SERVICE_ESPERADO,
       CASE WHEN UPPER(SYS_CONTEXT('USERENV','CURRENT_SCHEMA'))='FRANCISCO_JUNIOR'
            THEN 'OK' ELSE 'INFORMAR_OWNER_OPERACIONAL' END SCHEMA_ESPERADO
  FROM DUAL;
SELECT BANNER VERSAO_ORACLE
  FROM V$VERSION
 WHERE BANNER LIKE 'Oracle%';

PROMPT === EMPRESA ESPERADA ===
SELECT CODEMP, RAZAOSOCIAL
  FROM TSIEMP
 WHERE UPPER(TRIM(RAZAOSOCIAL))='PRODUTOS ALHEIRO LTDA'
 ORDER BY CODEMP;
SELECT COUNT(*) QTD_EMPRESA_EXATA,
       CASE WHEN COUNT(*)=1 THEN 'OK' ELSE 'BLOQUEAR_IDENTIDADE_EMPRESA' END STATUS_EMPRESA
  FROM TSIEMP
 WHERE UPPER(TRIM(RAZAOSOCIAL))='PRODUTOS ALHEIRO LTDA';

PROMPT === VERSAO_SISTEMA_CURTA ===
SELECT REGEXP_SUBSTR(TEXTO,'[0-9]+\.[0-9]+[[:alpha:]][0-9]+') VERSAO_SISTEMA_CURTA
  FROM TSIPAR
 WHERE CHAVE='VERSAOSKWBIN';

PROMPT === TABELAS_CORE_NO_OWNER_OPERACIONAL ===
SELECT TABLE_NAME, OWNER, NUM_ROWS
  FROM ALL_TABLES
 WHERE OWNER=UPPER(SYS_CONTEXT('USERENV','CURRENT_SCHEMA'))
   AND TABLE_NAME IN (
     'TSIEMP','TSIPAR','TTKINDAGT','TTKNOT','TTKEVT','TGFCAB','TGFTOP','TGFPAR',
     'TGFPRO','TGFITE','TGFVOL','TGFVOA','TGFPAP','TGFCOI2','TGFGIR1','TSIIMP',
     'TGFCGM','TGFCMV','TGFTPV','TGFTIT','TSICID','TSIBAI','TSIEND','TGFPPG',
     'TGFFIN','TGFNUM','TSICTA','TSICFG'
   )
 ORDER BY TABLE_NAME;

PROMPT === PRIVILEGIOS E QUOTA ===
SELECT PRIVILEGE
  FROM SESSION_PRIVS
 WHERE PRIVILEGE IN (
   'CREATE TABLE','CREATE PROCEDURE','ALTER ANY PROCEDURE','ALTER ANY TRIGGER',
   'CREATE ANY TABLE','DROP ANY TABLE'
 )
 ORDER BY PRIVILEGE;
SELECT TABLESPACE_NAME, BYTES, MAX_BYTES, BLOCKS, MAX_BLOCKS
  FROM USER_TS_QUOTAS
 ORDER BY TABLESPACE_NAME;

PROMPT === TRIGGERS RELEVANTES E ESTADO ATUAL ===
SELECT TABLE_NAME,
       STATUS,
       TRIGGERING_EVENT,
       COUNT(*) QTD_TRIGGERS
  FROM ALL_TRIGGERS
 WHERE OWNER=UPPER(SYS_CONTEXT('USERENV','CURRENT_SCHEMA'))
   AND (TRIGGER_NAME IN ('TRG_INC_UPD_TGFITE','TRG_UPT_TGFITE')
        OR TABLE_NAME IN ('TGFPRO','TGFITE','TGFCUS'))
 GROUP BY TABLE_NAME, STATUS, TRIGGERING_EVENT
 ORDER BY TABLE_NAME, STATUS, TRIGGERING_EVENT;

PROMPT === CANDIDATOS DOS CARDS BLOQUEANTES ===
SELECT COUNT(*) CANDIDATOS_CARD08_PROTOCOLAMENTO
  FROM TGFCAB C
 WHERE EXISTS (SELECT 1 FROM TTKNOT N WHERE N.NUNOTA=C.NUNOTA)
   AND ((C.NUMPROTOC IS NULL AND EXISTS (
          SELECT 1 FROM TGFTOP T
           WHERE T.CODTIPOPER=C.CODTIPOPER
             AND T.DHALTER=C.DHTIPOPER
             AND T.CODMODDOC=55))
     OR (C.NUMPROTOCCTE IS NULL AND EXISTS (
          SELECT 1 FROM TGFTOP T
           WHERE T.CODTIPOPER=C.CODTIPOPER
             AND T.DHALTER=C.DHTIPOPER
             AND T.CODMODDOC=57)));

SELECT COUNT(*) CANDIDATOS_CARD13_TOPS_GOL
  FROM TGFTOP T
 WHERE DECODE(NVL(T.GOLSINAL,99999),
              NVL(CASE WHEN T.ATUALEST='B' AND T.TIPMOV='V' AND T.ATUALFIN=1 AND T.TIPATUALFIN='I' AND T.CODMODDOC IN (55,59,65) THEN -1
                       WHEN T.ATUALEST='E' AND T.TIPMOV='D' AND T.ATUALFIN=-1 AND T.TIPATUALFIN='I' AND T.CODMODDOC IN (55,59,65) THEN -1
                       WHEN T.ATUALEST='E' AND T.TIPMOV='C' AND T.ATUALFIN=-1 AND T.TIPATUALFIN='I' AND T.CODMODDOC IN (55,59,65) THEN 1
                       WHEN T.ATUALEST='B' AND T.TIPMOV='E' AND T.ATUALFIN=1 AND T.TIPATUALFIN='I' AND T.CODMODDOC IN (55,59,65) THEN 1
                       ELSE 0 END,99999),0,1)
       + DECODE(NVL(T.GOLMPSINAL,99999),
              NVL(CASE WHEN T.ATUALEST='B' AND T.TIPMOV='V' AND T.ATUALFIN=1 AND T.TIPATUALFIN='I' AND T.CODMODDOC IN (55,59,65) THEN -1
                       WHEN T.ATUALEST='E' AND T.TIPMOV='D' AND T.ATUALFIN=-1 AND T.TIPATUALFIN='I' AND T.CODMODDOC IN (55,59,65) THEN -1
                       WHEN T.ATUALEST='E' AND T.TIPMOV='C' AND T.ATUALFIN=-1 AND T.TIPATUALFIN='I' AND T.CODMODDOC IN (55,59,65) THEN 1
                       WHEN T.ATUALEST='B' AND T.TIPMOV='E' AND T.ATUALFIN=1 AND T.TIPATUALFIN='I' AND T.CODMODDOC IN (55,59,65) THEN 1
                       ELSE 0 END,99999),0,1)
       + DECODE(NVL(T.GOLDEV,99999),
              NVL(CASE WHEN T.TIPMOV IN ('D','E') AND T.ATUALEST IN ('E','B') AND T.CODMODDOC IN (55,59,65) AND (T.ATUALFIN<>0 OR T.TIPATUALFIN<>'P') THEN -1 ELSE 1 END,99999),0,1)
       + DECODE(NVL(T.ANALISEGIRO,99999),
              NVL(CASE WHEN T.TIPMOV='V' AND T.ATUALEST='B' AND T.ATUALFIN=1 AND T.TIPATUALFIN='I' AND T.CODMODDOC IN (55,59,65) THEN -1
                       WHEN T.TIPMOV='D' AND T.ATUALEST='E' AND T.ATUALFIN=-1 AND T.TIPATUALFIN='I' AND T.CODMODDOC IN (55,59,65) THEN 1
                       ELSE 0 END,99999),0,1)
       + DECODE(NVL(T.ATUALULTIMAVEND,'#'),
              NVL(CASE WHEN T.TIPMOV='V' AND T.ATUALEST='B' AND T.ATUALFIN=1 AND T.TIPATUALFIN='I' AND T.CODMODDOC IN (55,59,65) THEN 'G' ELSE 'N' END,'#'),0,1)
       + DECODE(NVL(T.ATUALULTIMACOMP,'#'),
              NVL(CASE WHEN T.TIPMOV='C' AND T.ATUALEST='E' AND T.ATUALFIN=-1 AND T.TIPATUALFIN='I' AND T.CODMODDOC IN (55,59,65) THEN 'E' ELSE 'N' END,'#'),0,1) > 0;

SELECT COUNT(*) CANDIDATOS_CARD14_ANALISE_848 FROM TSIIMP WHERE CODREL=848;
SELECT COUNT(*) CANDIDATOS_CARD15_RASTRO
  FROM TGFPRO WHERE TEMRASTROLOTE='S' AND TIPCONTEST='N';

PROMPT === COLISOES NORMALIZADAS DOS CARDS 29 E 30 ===
SELECT COUNT(*) GRUPOS_COLISAO_BAIRROS
  FROM (
    SELECT REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEBAI),
      'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ','AAAAAEEEEIIIIOOOOOUUUUC')),'[[:space:]]+',' ') NORM
      FROM TSIBAI
     GROUP BY REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEBAI),
      'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ','AAAAAEEEEIIIIOOOOOUUUUC')),'[[:space:]]+',' ')
    HAVING COUNT(*)>1
  );
SELECT COUNT(*) GRUPOS_COLISAO_ENDERECOS
  FROM (
    SELECT TIPO, REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEEND),
      'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ','AAAAAEEEEIIIIOOOOOUUUUC')),'[[:space:]]+',' ') NORM
      FROM TSIEND
     GROUP BY TIPO, REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEEND),
      'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ','AAAAAEEEEIIIIOOOOOUUUUC')),'[[:space:]]+',' ')
    HAVING COUNT(*)>1
  );

PROMPT === FUNCAO XML DO CARD 09 ===
SELECT OWNER, OBJECT_NAME, OBJECT_TYPE, STATUS
  FROM ALL_OBJECTS
 WHERE OBJECT_NAME='FNC_BUSCA_TAG_XML_GERAL'
 ORDER BY OWNER, OBJECT_TYPE;

PROMPT === OBJETOS DE RECALCULO DE CUSTOS E CONSOLIDACAO GOL ===
SELECT OWNER, OBJECT_NAME, OBJECT_TYPE, STATUS, CREATED, LAST_DDL_TIME
  FROM ALL_OBJECTS
 WHERE OBJECT_NAME IN (
   'STP_CALCCUSTOMEDIOPRODGENERICO','STP_CALCULARCUSTOMEDIODIA',
   'STP_CALCULARCUSTOMEDIOFAMILIA','STP_CALCULARCUSTOPRODGENERICO',
   'STP_PROCESSOATUALCUSTO','STP_EFETIVA_CONSOLIDACAO_GOL',
   'PFCM_CONSOLIDACAO','SNK_MATGIRCALCTOTAIS'
 )
 ORDER BY OWNER, OBJECT_NAME, OBJECT_TYPE;
SELECT COUNT(*) QTD_OBJETOS_CUSTO_GOL_VALIDOS
  FROM ALL_OBJECTS
 WHERE STATUS='VALID'
   AND OBJECT_NAME IN (
   'STP_CALCCUSTOMEDIOPRODGENERICO','STP_CALCULARCUSTOMEDIODIA',
   'STP_CALCULARCUSTOMEDIOFAMILIA','STP_CALCULARCUSTOPRODGENERICO',
   'STP_PROCESSOATUALCUSTO','STP_EFETIVA_CONSOLIDACAO_GOL',
   'PFCM_CONSOLIDACAO','SNK_MATGIRCALCTOTAIS'
 );

PROMPT === OBJETOS INVALIDOS - UM POR LINHA ===
SELECT OWNER, OBJECT_TYPE, OBJECT_NAME, STATUS
  FROM ALL_OBJECTS
 WHERE STATUS='INVALID'
 ORDER BY OWNER, OBJECT_TYPE, OBJECT_NAME;
SELECT COUNT(*) QTD_OBJETOS_INVALIDOS FROM ALL_OBJECTS WHERE STATUS='INVALID';

PROMPT === VALIDACAO FINAL DO PREFLIGHT ===
DECLARE
  v_user VARCHAR2(128) := UPPER(SYS_CONTEXT('USERENV','SESSION_USER'));
  v_service VARCHAR2(128) := UPPER(SYS_CONTEXT('USERENV','SERVICE_NAME'));
  v_emp NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_emp FROM TSIEMP
   WHERE UPPER(TRIM(RAZAOSOCIAL))='PRODUTOS ALHEIRO LTDA';
  IF v_user<>'FRANCISCO_JUNIOR' THEN
    RAISE_APPLICATION_ERROR(-20400,'PREFLIGHT_BLOQUEADO_USUARIO_SESSAO='||v_user);
  END IF;
  IF v_service<>'ALHEIROPRD.SANKHYACLOUD.COM.BR' THEN
    RAISE_APPLICATION_ERROR(-20401,'PREFLIGHT_BLOQUEADO_SERVICE_NAME='||v_service);
  END IF;
  IF v_emp<>1 THEN
    RAISE_APPLICATION_ERROR(-20402,'PREFLIGHT_BLOQUEADO_EMPRESA_QTD='||v_emp);
  END IF;
  DBMS_OUTPUT.PUT_LINE('PREFLIGHT_STATUS=APROVADO_PARA_ANALISE_COM_BACKUP');
  DBMS_OUTPUT.PUT_LINE('OWNER_OPERACIONAL='||SYS_CONTEXT('USERENV','CURRENT_SCHEMA'));
  DBMS_OUTPUT.PUT_LINE('USUARIO_AUDITORIA='||SYS_CONTEXT('USERENV','SESSION_USER'));
END;
/
