-- Preflight da Revisao Master Deploy - somente leitura.
-- A quota e informada, mas o bloqueio preventivo foi dispensado por aprovacao formal.
SET DEFINE OFF
SET ECHO OFF
SET FEEDBACK ON
SET HEADING ON
SET LINESIZE 160
SET PAGESIZE 100
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

PROMPT === PREFLIGHT GATE - IDENTIDADE DA SESSAO ===
SELECT CAST(SYS_CONTEXT('USERENV','SESSION_USER') AS VARCHAR2(128)) USUARIO_SESSAO
  FROM DUAL;
SELECT CAST(SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AS VARCHAR2(128)) SCHEMA_ATUAL
  FROM DUAL;
SELECT CAST(SYS_CONTEXT('USERENV','SERVICE_NAME') AS VARCHAR2(128)) SERVICE_NAME
  FROM DUAL;
SELECT CAST(SYS_CONTEXT('USERENV','DB_NAME') AS VARCHAR2(128)) DB_NAME
  FROM DUAL;
SELECT CAST(SYS_CONTEXT('USERENV','INSTANCE_NAME') AS VARCHAR2(128)) INSTANCE_NAME
  FROM DUAL;

SELECT CASE WHEN UPPER(SYS_CONTEXT('USERENV','SESSION_USER'))='FRANCISCO_JUNIOR'
            THEN 'OK' ELSE 'BLOQUEAR_USUARIO' END USUARIO_ESPERADO,
       CASE WHEN UPPER(SYS_CONTEXT('USERENV','SERVICE_NAME'))='ALHEIROPRD.SANKHYACLOUD.COM.BR'
            THEN 'OK' ELSE 'BLOQUEAR_SERVICE_NAME' END SERVICE_ESPERADO
  FROM DUAL;

PROMPT === PREFLIGHT GATE - EMPRESA E VERSAO ===
SELECT COUNT(*) QTD_EMPRESA_EXATA,
       CASE WHEN COUNT(*)=1 THEN 'OK' ELSE 'BLOQUEAR_IDENTIDADE_EMPRESA' END STATUS_EMPRESA
  FROM TSIEMP
 WHERE UPPER(TRIM(RAZAOSOCIAL))='PRODUTOS ALHEIRO LTDA';

SELECT CAST(REGEXP_SUBSTR(TEXTO,'[0-9]+\.[0-9]+[[:alpha:]][0-9]+') AS VARCHAR2(30)) VERSAO_SISTEMA_CURTA
  FROM TSIPAR
 WHERE CHAVE='VERSAOSKWBIN';

SELECT CAST(BANNER AS VARCHAR2(120)) VERSAO_ORACLE
  FROM V$VERSION
 WHERE BANNER LIKE 'Oracle%';

PROMPT === PREFLIGHT GATE - QUOTA E INVALIDOS ===
SELECT COUNT(*) QTD_LINHAS_USER_TS_QUOTAS
  FROM USER_TS_QUOTAS;

SELECT COUNT(*) QTD_OBJETOS_INVALIDOS
  FROM ALL_OBJECTS
 WHERE STATUS='INVALID';

DECLARE
  v_user VARCHAR2(128) := UPPER(SYS_CONTEXT('USERENV','SESSION_USER'));
  v_service VARCHAR2(128) := UPPER(SYS_CONTEXT('USERENV','SERVICE_NAME'));
  v_emp NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_emp
    FROM TSIEMP
   WHERE UPPER(TRIM(RAZAOSOCIAL))='PRODUTOS ALHEIRO LTDA';
  IF v_user<>'FRANCISCO_JUNIOR' THEN
    RAISE_APPLICATION_ERROR(-20400,'PREFLIGHT_BLOQUEADO_USUARIO_SESSAO='||v_user);
  END IF;
  IF v_service<>'ALHEIROPRD.SANKHYACLOUD.COM.BR' THEN
    RAISE_APPLICATION_ERROR(-20401,'PREFLIGHT_BLOQUEADO_SERVICE_NAME='||v_service);
  END IF;
  IF v_emp<>1 THEN
    RAISE_APPLICATION_ERROR(-20402,'PREFLIGHT_BLOQUEADO_EMPRESA_QTD='||v_emp);
  END IF;
  DBMS_OUTPUT.PUT_LINE('PREFLIGHT_GATE_STATUS=APROVADO_IDENTIDADE_EMPRESA; QUOTA=INFORMADA_SEM_BLOQUEIO_PREVENTIVO');
  DBMS_OUTPUT.PUT_LINE('OWNER_OPERACIONAL='||SYS_CONTEXT('USERENV','CURRENT_SCHEMA'));
END;
/

PROMPT === FIM PREFLIGHT GATE - SOMENTE LEITURA ===
