-- Card 29/30 - mapa persistente e merge antifragil especifico de PRODUTOS ALHEIRO LTDA.
-- Nao contem senha. Executar somente pelo runner de retomada, no VS Code conectado.
-- O mapa e os backups sao persistentes e nao devem ser removidos apos a execucao.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET SQLBLANKLINES ON
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

-- As tabelas de auditoria precisam existir antes da compilacao do bloco
-- principal, pois ele usa SQL estatico contra esses objetos.
DECLARE
  v_owner VARCHAR2(128):=SYS_CONTEXT('USERENV','CURRENT_SCHEMA');
  PROCEDURE cria_se_ausente(p_nome VARCHAR2,p_ddl VARCHAR2) IS
    v_existe NUMBER;
  BEGIN
    SELECT COUNT(*) INTO v_existe FROM ALL_TABLES
     WHERE OWNER=v_owner AND TABLE_NAME=p_nome;
    IF v_existe=0 THEN EXECUTE IMMEDIATE p_ddl; END IF;
  END;
BEGIN
  cria_se_ausente('RMD_ALH_2930_MAP',
    'CREATE TABLE RMD_ALH_2930_MAP (ID_EXECUCAO VARCHAR2(40) NOT NULL,TIPO VARCHAR2(4) NOT NULL,COD_OBSOLETO NUMBER NOT NULL,COD_MANTIDO NUMBER NOT NULL,CHAVE_NORM VARCHAR2(4000),DH_LOG TIMESTAMP NOT NULL)');
  cria_se_ausente('RMD_ALH_2930_BAI_BKP',
    'CREATE TABLE RMD_ALH_2930_BAI_BKP AS SELECT CAST(NULL AS VARCHAR2(40)) ID_EXECUCAO,CAST(NULL AS TIMESTAMP) DH_EXECUCAO,CAST(NULL AS VARCHAR2(128)) USUARIO_EXECUCAO,B.* FROM TSIBAI B WHERE 1=0');
  cria_se_ausente('RMD_ALH_2930_END_BKP',
    'CREATE TABLE RMD_ALH_2930_END_BKP AS SELECT CAST(NULL AS VARCHAR2(40)) ID_EXECUCAO,CAST(NULL AS TIMESTAMP) DH_EXECUCAO,CAST(NULL AS VARCHAR2(128)) USUARIO_EXECUCAO,E.* FROM TSIEND E WHERE 1=0');
  cria_se_ausente('RMD_ALH_2930_DEP',
    'CREATE TABLE RMD_ALH_2930_DEP (ID_EXECUCAO VARCHAR2(40) NOT NULL,TABLE_NAME VARCHAR2(128) NOT NULL,COLUMN_NAME VARCHAR2(128) NOT NULL,RID VARCHAR2(30) NOT NULL,OLD_VALUE NUMBER,NEW_VALUE NUMBER,DH_LOG TIMESTAMP NOT NULL)');
  cria_se_ausente('RMD_ALH_2930_EXC',
    'CREATE TABLE RMD_ALH_2930_EXC (ID_EXECUCAO VARCHAR2(40) NOT NULL,TABLE_NAME VARCHAR2(128) NOT NULL,COLUMN_NAME VARCHAR2(128) NOT NULL,MENSAGEM VARCHAR2(1000) NOT NULL,DH_LOG TIMESTAMP NOT NULL)');
  DBMS_OUTPUT.PUT_LINE('TABELAS_AUDITORIA_29_30=CRIADAS_OU_EXISTENTES');
END;
/

DECLARE
  v_owner       VARCHAR2(128) := SYS_CONTEXT('USERENV','CURRENT_SCHEMA');
  v_id          VARCHAR2(40) := 'RMD_ALH_2930_'||TO_CHAR(SYSTIMESTAMP,'YYYYMMDDHH24MISSFF3');
  v_sql         VARCHAR2(32767);
  v_n           NUMBER := 0;
  v_refs        NUMBER := 0;
  v_exc         NUMBER := 0;
  v_map_bai     NUMBER := 0;
  v_map_end     NUMBER := 0;
  v_bkp_bai     NUMBER := 0;
  v_bkp_end     NUMBER := 0;
  v_del_bai     NUMBER := 0;
  v_del_end     NUMBER := 0;
  c_map         CONSTANT VARCHAR2(30) := 'RMD_ALH_2930_MAP';
  c_bkp_bai     CONSTANT VARCHAR2(30) := 'RMD_ALH_2930_BAI_BKP';
  c_bkp_end     CONSTANT VARCHAR2(30) := 'RMD_ALH_2930_END_BKP';
  c_dep         CONSTANT VARCHAR2(30) := 'RMD_ALH_2930_DEP';
  c_exc         CONSTANT VARCHAR2(30) := 'RMD_ALH_2930_EXC';

  PROCEDURE cria_se_ausente(p_nome VARCHAR2,p_ddl VARCHAR2) IS
    v_existe NUMBER;
  BEGIN
    SELECT COUNT(*) INTO v_existe
      FROM ALL_TABLES
     WHERE OWNER=v_owner AND TABLE_NAME=p_nome;
    IF v_existe=0 THEN
      EXECUTE IMMEDIATE p_ddl;
    END IF;
  END;

  PROCEDURE registra_excecao(p_tabela VARCHAR2,p_coluna VARCHAR2,p_msg VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE
      'INSERT INTO '||c_exc||
      '(ID_EXECUCAO,TABLE_NAME,COLUMN_NAME,MENSAGEM,DH_LOG) VALUES (:1,:2,:3,:4,SYSTIMESTAMP)'
      USING v_id,p_tabela,p_coluna,SUBSTR(p_msg,1,1000);
  END;
BEGIN
  cria_se_ausente(c_map,
    'CREATE TABLE '||c_map||' ('||
    'ID_EXECUCAO VARCHAR2(40) NOT NULL,TIPO VARCHAR2(4) NOT NULL,'||
    'COD_OBSOLETO NUMBER NOT NULL,COD_MANTIDO NUMBER NOT NULL,'||
    'CHAVE_NORM VARCHAR2(4000),DH_LOG TIMESTAMP NOT NULL)');
  cria_se_ausente(c_bkp_bai,
    'CREATE TABLE '||c_bkp_bai||' AS SELECT '||
    'CAST(NULL AS VARCHAR2(40)) ID_EXECUCAO,'||
    'CAST(NULL AS TIMESTAMP) DH_EXECUCAO,'||
    'CAST(NULL AS VARCHAR2(128)) USUARIO_EXECUCAO,'||
    'B.* FROM TSIBAI B WHERE 1=0');
  cria_se_ausente(c_bkp_end,
    'CREATE TABLE '||c_bkp_end||' AS SELECT '||
    'CAST(NULL AS VARCHAR2(40)) ID_EXECUCAO,'||
    'CAST(NULL AS TIMESTAMP) DH_EXECUCAO,'||
    'CAST(NULL AS VARCHAR2(128)) USUARIO_EXECUCAO,'||
    'E.* FROM TSIEND E WHERE 1=0');
  cria_se_ausente(c_dep,
    'CREATE TABLE '||c_dep||' ('||
    'ID_EXECUCAO VARCHAR2(40) NOT NULL,TABLE_NAME VARCHAR2(128) NOT NULL,'||
    'COLUMN_NAME VARCHAR2(128) NOT NULL,RID VARCHAR2(30) NOT NULL,'||
    'OLD_VALUE NUMBER,NEW_VALUE NUMBER,DH_LOG TIMESTAMP NOT NULL)');
  cria_se_ausente(c_exc,
    'CREATE TABLE '||c_exc||' ('||
    'ID_EXECUCAO VARCHAR2(40) NOT NULL,TABLE_NAME VARCHAR2(128) NOT NULL,'||
    'COLUMN_NAME VARCHAR2(128) NOT NULL,MENSAGEM VARCHAR2(1000) NOT NULL,'||
    'DH_LOG TIMESTAMP NOT NULL)');

  DBMS_OUTPUT.PUT_LINE('ID_EXECUCAO='||v_id);
  DBMS_OUTPUT.PUT_LINE('OWNER_OPERACIONAL='||v_owner);
  SELECT COUNT(*) INTO v_n FROM USER_TS_QUOTAS;
  DBMS_OUTPUT.PUT_LINE('QTD_LINHAS_USER_TS_QUOTAS='||v_n||'; GATE_PREVENTIVO_DISPENSADO=SIM');

  DELETE FROM RMD_ALH_2930_MAP WHERE ID_EXECUCAO=v_id;
  DELETE FROM RMD_ALH_2930_DEP WHERE ID_EXECUCAO=v_id;
  DELETE FROM RMD_ALH_2930_EXC WHERE ID_EXECUCAO=v_id;

  INSERT INTO RMD_ALH_2930_MAP
    (ID_EXECUCAO,TIPO,COD_OBSOLETO,COD_MANTIDO,CHAVE_NORM,DH_LOG)
  SELECT v_id,'BAI',CODBAI,KEEP_ID,NORM,SYSTIMESTAMP
    FROM (
      SELECT CODBAI,NORM,
             MIN(CODBAI) OVER(PARTITION BY NORM) KEEP_ID,
             COUNT(*) OVER(PARTITION BY NORM) QTD
        FROM (
          SELECT CODBAI,
                 REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEBAI),
                   'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ',
                   'AAAAAEEEEIIIIOOOOOUUUUC')),' {2,}',' ') NORM
            FROM TSIBAI
        )
       WHERE NORM IS NOT NULL
    )
   WHERE QTD>1 AND CODBAI<>KEEP_ID;
  v_map_bai:=SQL%ROWCOUNT;

  INSERT INTO RMD_ALH_2930_MAP
    (ID_EXECUCAO,TIPO,COD_OBSOLETO,COD_MANTIDO,CHAVE_NORM,DH_LOG)
  SELECT v_id,'END',CODEND,KEEP_ID,TO_CHAR(TIPO)||'|'||NORM,SYSTIMESTAMP
    FROM (
      SELECT CODEND,TIPO,NORM,
             MIN(CODEND) OVER(PARTITION BY TIPO,NORM) KEEP_ID,
             COUNT(*) OVER(PARTITION BY TIPO,NORM) QTD
        FROM (
          SELECT CODEND,TIPO,
                 REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEEND),
                   'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ',
                   'AAAAAEEEEIIIIOOOOOUUUUC')),' {2,}',' ') NORM
            FROM TSIEND
        )
       WHERE NORM IS NOT NULL
    )
   WHERE QTD>1 AND CODEND<>KEEP_ID;
  v_map_end:=SQL%ROWCOUNT;

  INSERT INTO RMD_ALH_2930_BAI_BKP
  SELECT v_id,SYSTIMESTAMP,SYS_CONTEXT('USERENV','SESSION_USER'),B.*
    FROM TSIBAI B
   WHERE EXISTS (
     SELECT 1 FROM RMD_ALH_2930_MAP M
      WHERE M.ID_EXECUCAO=v_id AND M.TIPO='BAI'
        AND (M.COD_OBSOLETO=B.CODBAI OR M.COD_MANTIDO=B.CODBAI));
  v_bkp_bai:=SQL%ROWCOUNT;

  INSERT INTO RMD_ALH_2930_END_BKP
  SELECT v_id,SYSTIMESTAMP,SYS_CONTEXT('USERENV','SESSION_USER'),E.*
    FROM TSIEND E
   WHERE EXISTS (
     SELECT 1 FROM RMD_ALH_2930_MAP M
      WHERE M.ID_EXECUCAO=v_id AND M.TIPO='END'
        AND (M.COD_OBSOLETO=E.CODEND OR M.COD_MANTIDO=E.CODEND));
  v_bkp_end:=SQL%ROWCOUNT;

  IF v_bkp_bai<v_map_bai OR v_bkp_end<v_map_end THEN
    RAISE_APPLICATION_ERROR(-20380,'Backup qualificado menor que o mapa: BAI='||v_bkp_bai||'/'||v_map_bai||', END='||v_bkp_end||'/'||v_map_end);
  END IF;
  DBMS_OUTPUT.PUT_LINE('MAPA_BAI='||v_map_bai||'; BACKUP_BAI='||v_bkp_bai);
  DBMS_OUTPUT.PUT_LINE('MAPA_END='||v_map_end||'; BACKUP_END='||v_bkp_end);

  -- Primeiro ramo: colunas convencionais CODBAI/CODEND em tabelas fisicas.
  FOR r IN (
    SELECT DISTINCT C.TABLE_NAME,C.COLUMN_NAME
      FROM ALL_TAB_COLUMNS C
      JOIN ALL_TABLES T ON T.OWNER=C.OWNER AND T.TABLE_NAME=C.TABLE_NAME
     WHERE C.OWNER=v_owner
       AND C.COLUMN_NAME IN ('CODBAI','CODEND')
       AND C.TABLE_NAME NOT IN ('TSIBAI','TSIEND')
       AND C.TABLE_NAME NOT LIKE 'BKP_RMD%'
       AND C.TABLE_NAME NOT LIKE 'RMD_ALH_2930%'
     ORDER BY C.TABLE_NAME,C.COLUMN_NAME
  ) LOOP
    SAVEPOINT RMD_ALH_2930_RAMO;
    BEGIN
      IF r.COLUMN_NAME='CODBAI' THEN
        v_sql:='INSERT INTO RMD_ALH_2930_DEP '||
          '(ID_EXECUCAO,TABLE_NAME,COLUMN_NAME,RID,OLD_VALUE,NEW_VALUE,DH_LOG) '||
          'SELECT :1,:2,:3,ROWIDTOCHAR(T.ROWID),T.CODBAI,M.COD_MANTIDO,SYSTIMESTAMP '||
          'FROM '||r.TABLE_NAME||' T JOIN RMD_ALH_2930_MAP M '||
          'ON M.ID_EXECUCAO=:4 AND M.TIPO=''BAI'' AND M.COD_OBSOLETO=T.CODBAI';
        EXECUTE IMMEDIATE v_sql USING v_id,r.TABLE_NAME,r.COLUMN_NAME,v_id;
        v_sql:='UPDATE '||r.TABLE_NAME||' T SET CODBAI='||
          '(SELECT M.COD_MANTIDO FROM RMD_ALH_2930_MAP M WHERE M.ID_EXECUCAO=:1 AND M.TIPO=''BAI'' AND M.COD_OBSOLETO=T.CODBAI) '||
          'WHERE EXISTS (SELECT 1 FROM RMD_ALH_2930_MAP M WHERE M.ID_EXECUCAO=:2 AND M.TIPO=''BAI'' AND M.COD_OBSOLETO=T.CODBAI)';
        EXECUTE IMMEDIATE v_sql USING v_id,v_id;
      ELSE
        v_sql:='INSERT INTO RMD_ALH_2930_DEP '||
          '(ID_EXECUCAO,TABLE_NAME,COLUMN_NAME,RID,OLD_VALUE,NEW_VALUE,DH_LOG) '||
          'SELECT :1,:2,:3,ROWIDTOCHAR(T.ROWID),T.CODEND,M.COD_MANTIDO,SYSTIMESTAMP '||
          'FROM '||r.TABLE_NAME||' T JOIN RMD_ALH_2930_MAP M '||
          'ON M.ID_EXECUCAO=:4 AND M.TIPO=''END'' AND M.COD_OBSOLETO=T.CODEND';
        EXECUTE IMMEDIATE v_sql USING v_id,r.TABLE_NAME,r.COLUMN_NAME,v_id;
        v_sql:='UPDATE '||r.TABLE_NAME||' T SET CODEND='||
          '(SELECT M.COD_MANTIDO FROM RMD_ALH_2930_MAP M WHERE M.ID_EXECUCAO=:1 AND M.TIPO=''END'' AND M.COD_OBSOLETO=T.CODEND) '||
          'WHERE EXISTS (SELECT 1 FROM RMD_ALH_2930_MAP M WHERE M.ID_EXECUCAO=:2 AND M.TIPO=''END'' AND M.COD_OBSOLETO=T.CODEND)';
        EXECUTE IMMEDIATE v_sql USING v_id,v_id;
      END IF;
      DBMS_OUTPUT.PUT_LINE('RAMO_OK|'||r.TABLE_NAME||'|'||r.COLUMN_NAME||'|'||SQL%ROWCOUNT);
    EXCEPTION WHEN OTHERS THEN
      ROLLBACK TO RMD_ALH_2930_RAMO;
      registra_excecao(r.TABLE_NAME,r.COLUMN_NAME,SQLERRM);
      v_exc:=v_exc+1;
      DBMS_OUTPUT.PUT_LINE('RAMO_EXCECAO|'||r.TABLE_NAME||'|'||r.COLUMN_NAME||'|'||SQLERRM);
    END;
  END LOOP;

  -- Segundo ramo: FKs que apontam para TSIBAI/TSIEND, inclusive nomes proprios.
  FOR r IN (
    SELECT DISTINCT C.TABLE_NAME,CC.COLUMN_NAME,P.TABLE_NAME PAI
      FROM ALL_CONSTRAINTS C
      JOIN ALL_CONS_COLUMNS CC
        ON CC.OWNER=C.OWNER AND CC.CONSTRAINT_NAME=C.CONSTRAINT_NAME
       AND CC.POSITION IS NOT NULL
      JOIN ALL_CONSTRAINTS P
        ON P.OWNER=C.R_OWNER AND P.CONSTRAINT_NAME=C.R_CONSTRAINT_NAME
      JOIN ALL_CONS_COLUMNS PC
        ON PC.OWNER=P.OWNER AND PC.CONSTRAINT_NAME=P.CONSTRAINT_NAME
       AND PC.POSITION=CC.POSITION
     WHERE C.OWNER=v_owner
       AND C.CONSTRAINT_TYPE='R'
       AND P.OWNER=v_owner
       AND P.TABLE_NAME IN ('TSIBAI','TSIEND')
       AND PC.COLUMN_NAME IN ('CODBAI','CODEND')
       AND CC.COLUMN_NAME NOT IN ('CODBAI','CODEND')
       AND C.TABLE_NAME NOT IN ('TSIBAI','TSIEND')
       AND C.TABLE_NAME NOT LIKE 'BKP_RMD%'
       AND C.TABLE_NAME NOT LIKE 'RMD_ALH_2930%'
     ORDER BY C.TABLE_NAME,CC.COLUMN_NAME
  ) LOOP
    SAVEPOINT RMD_ALH_2930_FK;
    BEGIN
      IF r.PAI='TSIBAI' THEN
        v_sql:='INSERT INTO RMD_ALH_2930_DEP '||
          '(ID_EXECUCAO,TABLE_NAME,COLUMN_NAME,RID,OLD_VALUE,NEW_VALUE,DH_LOG) '||
          'SELECT :1,:2,:3,ROWIDTOCHAR(T.ROWID),T.'||r.COLUMN_NAME||',M.COD_MANTIDO,SYSTIMESTAMP '||
          'FROM '||r.TABLE_NAME||' T JOIN RMD_ALH_2930_MAP M '||
          'ON M.ID_EXECUCAO=:4 AND M.TIPO=''BAI'' AND M.COD_OBSOLETO=T.'||r.COLUMN_NAME;
        EXECUTE IMMEDIATE v_sql USING v_id,r.TABLE_NAME,r.COLUMN_NAME,v_id;
        v_sql:='UPDATE '||r.TABLE_NAME||' T SET '||r.COLUMN_NAME||'='||
          '(SELECT M.COD_MANTIDO FROM RMD_ALH_2930_MAP M WHERE M.ID_EXECUCAO=:1 AND M.TIPO=''BAI'' AND M.COD_OBSOLETO=T.'||r.COLUMN_NAME||') '||
          'WHERE EXISTS (SELECT 1 FROM RMD_ALH_2930_MAP M WHERE M.ID_EXECUCAO=:2 AND M.TIPO=''BAI'' AND M.COD_OBSOLETO=T.'||r.COLUMN_NAME||')';
        EXECUTE IMMEDIATE v_sql USING v_id,v_id;
      ELSE
        v_sql:='INSERT INTO RMD_ALH_2930_DEP '||
          '(ID_EXECUCAO,TABLE_NAME,COLUMN_NAME,RID,OLD_VALUE,NEW_VALUE,DH_LOG) '||
          'SELECT :1,:2,:3,ROWIDTOCHAR(T.ROWID),T.'||r.COLUMN_NAME||',M.COD_MANTIDO,SYSTIMESTAMP '||
          'FROM '||r.TABLE_NAME||' T JOIN RMD_ALH_2930_MAP M '||
          'ON M.ID_EXECUCAO=:4 AND M.TIPO=''END'' AND M.COD_OBSOLETO=T.'||r.COLUMN_NAME;
        EXECUTE IMMEDIATE v_sql USING v_id,r.TABLE_NAME,r.COLUMN_NAME,v_id;
        v_sql:='UPDATE '||r.TABLE_NAME||' T SET '||r.COLUMN_NAME||'='||
          '(SELECT M.COD_MANTIDO FROM RMD_ALH_2930_MAP M WHERE M.ID_EXECUCAO=:1 AND M.TIPO=''END'' AND M.COD_OBSOLETO=T.'||r.COLUMN_NAME||') '||
          'WHERE EXISTS (SELECT 1 FROM RMD_ALH_2930_MAP M WHERE M.ID_EXECUCAO=:2 AND M.TIPO=''END'' AND M.COD_OBSOLETO=T.'||r.COLUMN_NAME||')';
        EXECUTE IMMEDIATE v_sql USING v_id,v_id;
      END IF;
      DBMS_OUTPUT.PUT_LINE('FK_RAMO_OK|'||r.TABLE_NAME||'|'||r.COLUMN_NAME||'|'||SQL%ROWCOUNT);
    EXCEPTION WHEN OTHERS THEN
      ROLLBACK TO RMD_ALH_2930_FK;
      registra_excecao(r.TABLE_NAME,r.COLUMN_NAME,SQLERRM);
      v_exc:=v_exc+1;
      DBMS_OUTPUT.PUT_LINE('FK_RAMO_EXCECAO|'||r.TABLE_NAME||'|'||r.COLUMN_NAME||'|'||SQLERRM);
    END;
  END LOOP;

  IF v_exc>0 THEN
    RAISE_APPLICATION_ERROR(-20381,'Foram encontradas excecoes em ramos 29/30; nenhuma exclusao de pais sera realizada. QTD='||v_exc);
  END IF;

  -- Pos-validacao de referencias antes de qualquer exclusao de pai.
  FOR r IN (
    SELECT DISTINCT C.TABLE_NAME,C.COLUMN_NAME
      FROM ALL_TAB_COLUMNS C
      JOIN ALL_TABLES T ON T.OWNER=C.OWNER AND T.TABLE_NAME=C.TABLE_NAME
     WHERE C.OWNER=v_owner
       AND C.COLUMN_NAME IN ('CODBAI','CODEND')
       AND C.TABLE_NAME NOT IN ('TSIBAI','TSIEND')
       AND C.TABLE_NAME NOT LIKE 'BKP_RMD%'
       AND C.TABLE_NAME NOT LIKE 'RMD_ALH_2930%'
  ) LOOP
    IF r.COLUMN_NAME='CODBAI' THEN
      v_sql:='SELECT COUNT(*) FROM '||r.TABLE_NAME||' T WHERE EXISTS (SELECT 1 FROM RMD_ALH_2930_MAP M WHERE M.ID_EXECUCAO=:1 AND M.TIPO=''BAI'' AND M.COD_OBSOLETO=T.CODBAI)';
    ELSE
      v_sql:='SELECT COUNT(*) FROM '||r.TABLE_NAME||' T WHERE EXISTS (SELECT 1 FROM RMD_ALH_2930_MAP M WHERE M.ID_EXECUCAO=:1 AND M.TIPO=''END'' AND M.COD_OBSOLETO=T.CODEND)';
    END IF;
    EXECUTE IMMEDIATE v_sql INTO v_n USING v_id;
    v_refs:=v_refs+v_n;
  END LOOP;

  FOR r IN (
    SELECT DISTINCT C.TABLE_NAME,CC.COLUMN_NAME,P.TABLE_NAME PAI
      FROM ALL_CONSTRAINTS C
      JOIN ALL_CONS_COLUMNS CC
        ON CC.OWNER=C.OWNER AND CC.CONSTRAINT_NAME=C.CONSTRAINT_NAME
       AND CC.POSITION IS NOT NULL
      JOIN ALL_CONSTRAINTS P
        ON P.OWNER=C.R_OWNER AND P.CONSTRAINT_NAME=C.R_CONSTRAINT_NAME
      JOIN ALL_CONS_COLUMNS PC
        ON PC.OWNER=P.OWNER AND PC.CONSTRAINT_NAME=P.CONSTRAINT_NAME
       AND PC.POSITION=CC.POSITION
     WHERE C.OWNER=v_owner AND C.CONSTRAINT_TYPE='R'
       AND P.OWNER=v_owner AND P.TABLE_NAME IN ('TSIBAI','TSIEND')
       AND PC.COLUMN_NAME IN ('CODBAI','CODEND')
       AND CC.COLUMN_NAME NOT IN ('CODBAI','CODEND')
       AND C.TABLE_NAME NOT IN ('TSIBAI','TSIEND')
       AND C.TABLE_NAME NOT LIKE 'BKP_RMD%'
       AND C.TABLE_NAME NOT LIKE 'RMD_ALH_2930%'
  ) LOOP
    IF r.PAI='TSIBAI' THEN
      v_sql:='SELECT COUNT(*) FROM '||r.TABLE_NAME||' T WHERE EXISTS (SELECT 1 FROM RMD_ALH_2930_MAP M WHERE M.ID_EXECUCAO=:1 AND M.TIPO=''BAI'' AND M.COD_OBSOLETO=T.'||r.COLUMN_NAME||')';
    ELSE
      v_sql:='SELECT COUNT(*) FROM '||r.TABLE_NAME||' T WHERE EXISTS (SELECT 1 FROM RMD_ALH_2930_MAP M WHERE M.ID_EXECUCAO=:1 AND M.TIPO=''END'' AND M.COD_OBSOLETO=T.'||r.COLUMN_NAME||')';
    END IF;
    EXECUTE IMMEDIATE v_sql INTO v_n USING v_id;
    v_refs:=v_refs+v_n;
  END LOOP;

  IF v_refs<>0 THEN
    RAISE_APPLICATION_ERROR(-20382,'Referencias remanescentes impedem exclusao qualificada. QTD='||v_refs);
  END IF;

  DELETE FROM TSIBAI
   WHERE CODBAI IN (SELECT COD_OBSOLETO FROM RMD_ALH_2930_MAP WHERE ID_EXECUCAO=v_id AND TIPO='BAI');
  v_del_bai:=SQL%ROWCOUNT;
  DELETE FROM TSIEND
   WHERE CODEND IN (SELECT COD_OBSOLETO FROM RMD_ALH_2930_MAP WHERE ID_EXECUCAO=v_id AND TIPO='END');
  v_del_end:=SQL%ROWCOUNT;
  COMMIT;

  DBMS_OUTPUT.PUT_LINE('PAIS_BAI_EXCLUIDOS='||v_del_bai);
  DBMS_OUTPUT.PUT_LINE('PAIS_END_EXCLUIDOS='||v_del_end);
  DBMS_OUTPUT.PUT_LINE('REFERENCIAS_REMANESCENTES='||v_refs);
  DBMS_OUTPUT.PUT_LINE('STATUS=CONCLUIDO_COM_MAPA_BACKUP_FK; ID_EXECUCAO='||v_id);
EXCEPTION WHEN OTHERS THEN
  ROLLBACK;
  RAISE;
END;
/

PROMPT === POS-VALIDACAO 29/30 - DUPLICIDADES ===
SELECT 'TSIBAI_GRUPOS_COLISAO_REMANESCENTES' ITEM,COUNT(*) QTD
  FROM (
    SELECT REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEBAI),
      'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ','AAAAAEEEEIIIIOOOOOUUUUC')),' {2,}',' ') N
      FROM TSIBAI
     WHERE NOMEBAI IS NOT NULL
     GROUP BY REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEBAI),
      'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ','AAAAAEEEEIIIIOOOOOUUUUC')),' {2,}',' ')
    HAVING COUNT(*)>1
  )
UNION ALL
SELECT 'TSIEND_GRUPOS_COLISAO_REMANESCENTES',COUNT(*)
  FROM (
    SELECT TIPO,REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEEND),
      'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ','AAAAAEEEEIIIIOOOOOUUUUC')),' {2,}',' ') N
      FROM TSIEND
     WHERE NOMEEND IS NOT NULL
     GROUP BY TIPO,REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEEND),
      'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ','AAAAAEEEEIIIIOOOOOUUUUC')),' {2,}',' ')
    HAVING COUNT(*)>1
  );

PROMPT === FIM MERGE ANTIFRAGIL ALHEIRO 29/30 ===
