-- Card 09 - preflight somente leitura da funcao XML.
-- Nao contem senha. Executar no VS Code como SCRIPT (F5), na conexao da base.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET SQLBLANKLINES ON
SET ECHO ON
SET FEEDBACK ON
WHENEVER OSERROR EXIT FAILURE ROLLBACK
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

SPOOL "/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Clientes/PRODUTOS ALHEIRO LTDA/Logs/Card09_Preflight_Funcao_XML_20260917.log"

PROMPT === CARD 09 - PREFLIGHT DA FUNCAO XML - SOMENTE LEITURA ===
SELECT SYS_CONTEXT('USERENV','SESSION_USER') AS SESSION_USER,
       SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AS CURRENT_SCHEMA,
       SYS_CONTEXT('USERENV','SERVICE_NAME') AS SERVICE_NAME,
       SYS_CONTEXT('USERENV','DB_NAME') AS DB_NAME
  FROM DUAL;

PROMPT === OBJETO FNC_BUSCA_TAG_XML_GERAL ===
SELECT OWNER, OBJECT_NAME, OBJECT_TYPE, STATUS, LAST_DDL_TIME
  FROM ALL_OBJECTS
 WHERE OBJECT_NAME = 'FNC_BUSCA_TAG_XML_GERAL'
 ORDER BY OWNER, OBJECT_TYPE;

PROMPT === ARGUMENTOS DA FUNCAO ===
SELECT OWNER, OBJECT_NAME, PACKAGE_NAME, POSITION, ARGUMENT_NAME,
       DATA_TYPE, IN_OUT, DEFAULTED
  FROM ALL_ARGUMENTS
 WHERE OBJECT_NAME = 'FNC_BUSCA_TAG_XML_GERAL'
 ORDER BY OWNER, POSITION;

PROMPT === ERROS ATUAIS DO OBJETO ===
SELECT OWNER, NAME, TYPE, LINE, POSITION, TEXT
  FROM ALL_ERRORS
 WHERE NAME = 'FNC_BUSCA_TAG_XML_GERAL'
 ORDER BY OWNER, SEQUENCE;

PROMPT === PRIVILEGIOS RELEVANTES DA SESSAO ===
SELECT PRIVILEGE
  FROM SESSION_PRIVS
 WHERE PRIVILEGE IN ('CREATE PROCEDURE', 'CREATE ANY PROCEDURE', 'ALTER ANY PROCEDURE')
 ORDER BY PRIVILEGE;

PROMPT === QUOTA DA SESSAO ===
SELECT TABLESPACE_NAME, BYTES, MAX_BYTES
  FROM USER_TS_QUOTAS
 ORDER BY TABLESPACE_NAME;

PROMPT === PREFLIGHT DA FUNCAO XML CONCLUIDO; NENHUM DDL OU DML EXECUTADO ===

SPOOL OFF
