-- Card 09 - preflight e backup persistente dos candidatos XML.
-- Somente cria a tabela de preflight; nao insere, atualiza ou remove TGFFIN.
-- Nao contem senha. Executar no VS Code como SCRIPT (F5).
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET SQLBLANKLINES ON
SET ECHO ON
SET FEEDBACK ON
WHENEVER OSERROR EXIT FAILURE ROLLBACK
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

SPOOL "/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Clientes/PRODUTOS ALHEIRO LTDA/Logs/Card09_Preflight_20260917.log"

PROMPT === CARD 09 - PREFLIGHT E BACKUP PERSISTENTE ===
PROMPT ID_EXECUCAO=RMD_FDUP_ALH_2026091701

DECLARE
  v_exists NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_exists
    FROM ALL_TABLES
   WHERE OWNER = SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
     AND TABLE_NAME = 'BKP_RMD_ALH_DUP_20260917';
  IF v_exists > 0 THEN
    RAISE_APPLICATION_ERROR(-20320,
      'BKP_RMD_ALH_DUP_20260917 ja existe; nao repetir sem novo ID.');
  END IF;

  EXECUTE IMMEDIATE q'~
    CREATE TABLE BKP_RMD_ALH_DUP_20260917 AS
    WITH X AS (
      SELECT C.NUNOTA, C.CODEMP, C.NUMNOTA, C.SERIENOTA, C.DTNEG, C.DTMOV,
             C.DTENTSAI, C.CODPARC, C.CODTIPOPER, C.CODTIPVENDA,
             C.DHTIPOPER, C.CODVEND, C.CODNAT, C.CODCENCUS, C.CODPROJ,
             C.RATEADO, C.TIPMOV, C.VLRNOTA,
             T.ATUALFIN,
             FNC_BUSCA_TAG_XML_GERAL(C.NUNOTA,'vDup','dup') AS VDUP_XML,
             FNC_BUSCA_TAG_XML_GERAL(C.NUNOTA,'dVenc','dup') AS DVENC_XML,
             FNC_BUSCA_TAG_XML_GERAL(C.NUNOTA,'nDup','dup') AS NDUP_XML
        FROM TGFCAB C
        JOIN TGFTOP T
          ON T.CODTIPOPER = C.CODTIPOPER
         AND T.DHALTER = (
               SELECT MAX(T2.DHALTER)
                 FROM TGFTOP T2
                WHERE T2.CODTIPOPER = C.CODTIPOPER
                  AND T2.DHALTER <= C.DHTIPOPER
             )
       WHERE T.ATUALFIN <> 0
         AND C.TIPMOV <> 'Z'
         AND NOT EXISTS (SELECT 1 FROM TGFFIN F WHERE F.NUNOTA = C.NUNOTA)
    )
    SELECT 'RMD_FDUP_ALH_2026091701' AS ID_EXECUCAO,
           SYSTIMESTAMP AS DH_EXECUCAO,
           SYS_CONTEXT('USERENV','SESSION_USER') AS USUARIO_EXECUCAO,
           X.*,
           CASE
             WHEN X.VDUP_XML IS NULL THEN 'SEM_DUP_XML'
             WHEN X.DVENC_XML IS NULL THEN 'SEM_DVENC_XML'
             WHEN NOT REGEXP_LIKE(TRIM(X.VDUP_XML), '^[0-9]+([.][0-9]+)?$')
               THEN 'VDUP_XML_INVALIDO'
             WHEN NOT REGEXP_LIKE(TRIM(X.DVENC_XML), '^[0-9]{4}-[0-9]{2}-[0-9]{2}$')
               THEN 'DVENC_XML_INVALIDO'
             ELSE 'CANDIDATO_XML_VALIDO'
           END AS STATUS_PREFLIGHT
      FROM X
  ~';
  COMMIT;
END;
/

PROMPT === IDENTIDADE E QUANTIDADES DO BACKUP ===
SELECT SYS_CONTEXT('USERENV','SESSION_USER') AS SESSION_USER,
       SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AS CURRENT_SCHEMA,
       SYS_CONTEXT('USERENV','SERVICE_NAME') AS SERVICE_NAME,
       SYS_CONTEXT('USERENV','DB_NAME') AS DB_NAME
  FROM DUAL;

SELECT STATUS_PREFLIGHT, COUNT(*) AS QTD
  FROM BKP_RMD_ALH_DUP_20260917
 GROUP BY STATUS_PREFLIGHT
 ORDER BY STATUS_PREFLIGHT;

SELECT COUNT(*) AS LINHAS_BACKUP,
       COUNT(DISTINCT NUNOTA) AS NOTAS_BACKUP,
       SUM(CASE WHEN STATUS_PREFLIGHT='CANDIDATO_XML_VALIDO' THEN 1 ELSE 0 END) AS CANDIDATOS_XML_VALIDOS,
       SUM(CASE WHEN VDUP_XML IS NOT NULL THEN 1 ELSE 0 END) AS NOTAS_COM_VDUP,
       SUM(CASE WHEN DVENC_XML IS NOT NULL THEN 1 ELSE 0 END) AS NOTAS_COM_DVENC
  FROM BKP_RMD_ALH_DUP_20260917;

PROMPT === AMOSTRA AUDITAVEL XML ===
SELECT NUNOTA, CODEMP, NUMNOTA, SERIENOTA, CODTIPOPER, CODTIPVENDA,
       VDUP_XML, DVENC_XML, NDUP_XML, STATUS_PREFLIGHT
  FROM BKP_RMD_ALH_DUP_20260917
 ORDER BY NUNOTA
 FETCH FIRST 100 ROWS ONLY;

PROMPT === CARD 09 - PREFLIGHT CONCLUIDO; NENHUM TGFFIN FOI ALTERADO ===
SPOOL OFF
