-- Card 09 - compilacao controlada da funcao XML.
-- Nao contem senha. Executar no VS Code como SCRIPT (F5), na conexao da base.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET SQLBLANKLINES ON
SET ECHO ON
SET FEEDBACK ON
WHENEVER OSERROR EXIT FAILURE ROLLBACK
WHENEVER SQLERROR CONTINUE

SPOOL "/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Clientes/PRODUTOS ALHEIRO LTDA/Logs/Card09_Compilacao_Funcao_XML_20260917.log"

PROMPT === CARD 09 - COMPILACAO AUTOMATICA DA FUNCAO XML ===
PROMPT ID_EXECUCAO=RMD_ALH_FNC09_2026091701
PROMPT FONTE_SHA256=53f52da7455e3717e6d7a5e991d792921136c671cb1d2ceb2516d8618df0de0b

SELECT SYS_CONTEXT('USERENV','SESSION_USER') AS SESSION_USER,
       SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AS CURRENT_SCHEMA,
       SYS_CONTEXT('USERENV','SERVICE_NAME') AS SERVICE_NAME,
       SYS_CONTEXT('USERENV','DB_NAME') AS DB_NAME
  FROM DUAL;

PROMPT === ESTADO ANTES ===
SELECT OWNER, OBJECT_NAME, OBJECT_TYPE, STATUS, LAST_DDL_TIME
  FROM ALL_OBJECTS
 WHERE OBJECT_NAME = 'FNC_BUSCA_TAG_XML_GERAL'
 ORDER BY OWNER, OBJECT_TYPE;

PROMPT === FONTE VERSIONADA APROVADA ===
@"/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Scripts Originais/FNC_BUSCA_TAG_XML_GERAL.sql"

PROMPT === ESTADO APOS CREATE OR REPLACE ===
SELECT OWNER, OBJECT_NAME, OBJECT_TYPE, STATUS, LAST_DDL_TIME
  FROM ALL_OBJECTS
 WHERE OBJECT_NAME = 'FNC_BUSCA_TAG_XML_GERAL'
 ORDER BY OWNER, OBJECT_TYPE;

PROMPT === ERROS DE COMPILACAO ===
SELECT OWNER, NAME, TYPE, LINE, POSITION, TEXT
  FROM ALL_ERRORS
 WHERE NAME = 'FNC_BUSCA_TAG_XML_GERAL'
 ORDER BY OWNER, SEQUENCE;

PROMPT === ARGUMENTOS VALIDOS ===
SELECT OWNER, OBJECT_NAME, POSITION, ARGUMENT_NAME, DATA_TYPE, IN_OUT, DEFAULTED
  FROM ALL_ARGUMENTS
 WHERE OBJECT_NAME = 'FNC_BUSCA_TAG_XML_GERAL'
 ORDER BY OWNER, POSITION;

PROMPT === VALIDACAO FINAL DA FUNCAO ===
DECLARE
  v_status VARCHAR2(30);
  v_errors NUMBER;
BEGIN
  SELECT MAX(STATUS)
    INTO v_status
    FROM ALL_OBJECTS
   WHERE OWNER = SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
     AND OBJECT_NAME = 'FNC_BUSCA_TAG_XML_GERAL'
     AND OBJECT_TYPE = 'FUNCTION';

  SELECT COUNT(*)
    INTO v_errors
    FROM ALL_ERRORS
   WHERE OWNER = SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
     AND NAME = 'FNC_BUSCA_TAG_XML_GERAL'
     AND TYPE = 'FUNCTION';

  DBMS_OUTPUT.PUT_LINE('FUNCAO_STATUS=' || NVL(v_status,'AUSENTE'));
  DBMS_OUTPUT.PUT_LINE('FUNCAO_ERROS=' || v_errors);

  IF v_status <> 'VALID' OR v_errors <> 0 THEN
    RAISE_APPLICATION_ERROR(-20509, 'Card 09 isolado: funcao XML nao ficou VALID ou possui erros.');
  END IF;
END;
/

PROMPT === CARD 09 - FUNCAO XML VALIDADA; NENHUM TGFFIN FOI ALTERADO ===
SPOOL OFF
