-- Card 09 - mapa persistente de TGFPPG e validacoes para TGFFIN.
-- Nao executa INSERT em TGFFIN e nao atualiza TGFNUM.
-- Nao contem senha. Executar no VS Code como SCRIPT (F5).
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET SQLBLANKLINES ON
SET ECHO ON
SET FEEDBACK ON
WHENEVER OSERROR EXIT FAILURE ROLLBACK
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

SPOOL "/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Clientes/PRODUTOS ALHEIRO LTDA/Logs/Card09_Mapa_20260917.log"

PROMPT === CARD 09 - MAPA PERSISTENTE ALHEIRO ===
PROMPT ID_EXECUCAO_MAPA=RMD_FDUP_ALH_2026091701

DECLARE
  v_exists NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_exists
    FROM ALL_TABLES
   WHERE OWNER = SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
     AND TABLE_NAME = 'BKP_RMD_ALH_DUP_PPG_20260917';
  IF v_exists > 0 THEN
    RAISE_APPLICATION_ERROR(-20322,
      'BKP_RMD_ALH_DUP_PPG_20260917 ja existe; nao repetir sem novo ID.');
  END IF;

  EXECUTE IMMEDIATE q'~
    CREATE TABLE BKP_RMD_ALH_DUP_PPG_20260917 AS
    WITH R AS (
      SELECT
        'RMD_FDUP_ALH_2026091701' AS ID_EXECUCAO_MAPA,
        SYSTIMESTAMP AS DH_MAPA,
        SYS_CONTEXT('USERENV','SESSION_USER') AS USUARIO_MAPA,
        B.ID_EXECUCAO AS ID_PREFLIGHT,
        B.DH_EXECUCAO AS DH_PREFLIGHT,
        B.USUARIO_EXECUCAO AS USUARIO_PREFLIGHT,
        B.NUNOTA, B.CODEMP, B.NUMNOTA, B.SERIENOTA, B.DTNEG, B.DTMOV,
        B.DTENTSAI, B.CODPARC, B.CODTIPOPER, B.CODTIPVENDA, B.DHTIPOPER,
        B.CODVEND, B.CODNAT AS CODNAT_CAB, B.CODCENCUS AS CODCENCUS_CAB,
        B.CODPROJ AS CODPROJ_CAB, B.RATEADO AS RATEADO_CAB, B.TIPMOV,
        B.VLRNOTA, B.VDUP_XML, B.DVENC_XML, B.NDUP_XML,
        C.DHTIPVENDA AS DHTIPVENDA,
        B.STATUS_PREFLIGHT,
        P.TIPOEMP, P.CODEMP AS CODEMP_PPG, P.TIPOPAR,
        P.CODPARC AS CODPARC_PPG, P.SEQUENCIA AS SEQ_PPG,
        P.PRAZO, P.CODTIPTITPAD, P.CODBCOPAD, P.CODCTABCOINT,
        P.CODCENCUSPAD, P.CODNATPAD, P.CODPROJPAD, P.TIPRECDESP,
        P.TIPOFIN, P.PERCENTUAL,
        COUNT(P.CODTIPVENDA) OVER (PARTITION BY B.NUNOTA) AS QTD_PPG,
        COUNT(P.SEQUENCIA) OVER (PARTITION BY B.NUNOTA, P.SEQUENCIA) AS QTD_PPG_SEQ,
        (SELECT COUNT(*) FROM TGFTPV V
          WHERE V.CODTIPVENDA=B.CODTIPVENDA AND V.DHALTER=C.DHTIPVENDA) AS QTD_TGFTPV_EXATA,
        (SELECT COUNT(*) FROM TGFFIN F WHERE F.NUNOTA=B.NUNOTA) AS QTD_TGFFIN_ATUAL,
        (SELECT COUNT(*) FROM TGFNUM N WHERE N.ARQUIVO='TGFFIN') AS QTD_TGFNUM_TGFFIN,
        (SELECT MAX(N.ULTCOD) FROM TGFNUM N WHERE N.ARQUIVO='TGFFIN') AS ULTCOD_TGFNUM_ATUAL,
        (SELECT MIN(A.CODCTABCOINT) FROM TSICTA A
          WHERE A.ATIVA='S' AND A.CODEMP=B.CODEMP) AS CODCTABCOINT_ATIVA
      FROM BKP_RMD_ALH_DUP_20260917 B
      JOIN TGFCAB C ON C.NUNOTA=B.NUNOTA
      LEFT JOIN TGFPPG P ON P.CODTIPVENDA=B.CODTIPVENDA
     WHERE B.ID_EXECUCAO='RMD_FDUP_ALH_2026091701'
    ), R2 AS (
      SELECT R.*,
             NVL(R.CODCTABCOINT,R.CODCTABCOINT_ATIVA) AS CODCTABCOINT_RESOLVIDO,
             NVL(R.CODBCOPAD,0) AS CODBCO_RESOLVIDO,
             CASE
               WHEN UPPER(TRIM(R.TIPRECDESP)) IN ('I','R','1') THEN 1
               WHEN UPPER(TRIM(R.TIPRECDESP)) IN ('D','P','-1') THEN -1
               WHEN R.TIPMOV='V' THEN 1
               WHEN R.TIPMOV='C' THEN -1
               ELSE 0
             END AS RECDESP_RESOLVIDO,
             CASE WHEN UPPER(TRIM(R.TIPJURO_TPV))='I' THEN 1 ELSE 0 END AS TIPJURO_RESOLVIDO,
             NVL(R.CODCENCUSPAD,R.CODCENCUS_CAB) AS CODCENCUS_RESOLVIDO,
             NVL(R.CODNATPAD,R.CODNAT_CAB) AS CODNAT_RESOLVIDO,
             NVL(R.CODPROJPAD,R.CODPROJ_CAB) AS CODPROJ_RESOLVIDO
        FROM (
          SELECT R0.*,
                 (SELECT MAX(V.TIPJURO) FROM TGFTPV V
                   WHERE V.CODTIPVENDA=R0.CODTIPVENDA AND V.DHALTER=R0.DHTIPVENDA) AS TIPJURO_TPV
            FROM R R0
        ) R
    )
    SELECT R2.*,
           CASE
             WHEN R2.STATUS_PREFLIGHT <> 'CANDIDATO_XML_VALIDO' THEN R2.STATUS_PREFLIGHT
             WHEN R2.QTD_PPG=0 THEN 'SEM_TGFPPG'
             WHEN R2.QTD_PPG<>1 THEN 'REVISAR_MULTIPLAS_PARCELAS'
             WHEN R2.QTD_PPG_SEQ<>1 THEN 'REVISAR_DUPLICIDADE_TGFPPG'
             WHEN R2.CODTIPTITPAD IS NULL THEN 'SEM_CODTIPTITPAD'
             WHEN NOT EXISTS (SELECT 1 FROM TGFTIT T WHERE T.CODTIPTIT=R2.CODTIPTITPAD)
               THEN 'CODTIPTITPAD_INVALIDO'
             WHEN R2.QTD_TGFTPV_EXATA<>1 THEN 'REVISAR_TGFTPV_EXATA'
             WHEN R2.QTD_TGFNUM_TGFFIN<>1 THEN 'REVISAR_TGFNUM'
             WHEN R2.QTD_TGFFIN_ATUAL<>0 THEN 'TGFFIN_JA_EXISTE'
             WHEN R2.CODCTABCOINT_RESOLVIDO IS NULL THEN 'SEM_CONTA_ATIVA'
             WHEN R2.RECDESP_RESOLVIDO=0 THEN 'SEM_RECDESP'
             ELSE 'APTO_PARA_INSERCAO_CONTROLADA'
           END AS STATUS_MAPA,
           CASE
             WHEN R2.QTD_PPG=0 THEN 'TGFPPG ausente para CODTIPVENDA.'
             WHEN R2.QTD_PPG<>1 THEN 'Mais de uma condicao TGFPPG; nao inserir genericamente.'
             WHEN R2.CODTIPTITPAD IS NULL THEN 'CODTIPTIT deve ser derivado de TGFPPG.CODTIPTITPAD.'
             WHEN R2.QTD_TGFNUM_TGFFIN<>1 THEN 'TGFNUM deve ter exatamente uma linha TGFFIN.'
             ELSE 'Revisar candidato e validar antes do INSERT.'
           END AS OBSERVACAO
      FROM R2
  ~';
  COMMIT;
END;
/

PROMPT === RESUMO DO MAPA ===
SELECT STATUS_MAPA, COUNT(*) AS QTD
  FROM BKP_RMD_ALH_DUP_PPG_20260917
 GROUP BY STATUS_MAPA
 ORDER BY STATUS_MAPA;

PROMPT === CONTROLES DE UNICIDADE E SEGURANCA ===
SELECT COUNT(*) AS LINHAS_MAPA,
       COUNT(DISTINCT NUNOTA) AS NOTAS_MAPA,
       SUM(CASE WHEN STATUS_MAPA='APTO_PARA_INSERCAO_CONTROLADA' THEN 1 ELSE 0 END) AS LINHAS_APTAS,
       COUNT(DISTINCT CASE WHEN STATUS_MAPA='APTO_PARA_INSERCAO_CONTROLADA' THEN NUNOTA END) AS NOTAS_APTAS,
       SUM(QTD_TGFFIN_ATUAL) AS TGFFIN_EXISTENTE_NO_MAPA,
       MIN(QTD_TGFNUM_TGFFIN) AS TGFNUM_LINHAS,
       MIN(ULTCOD_TGFNUM_ATUAL) AS ULTCOD_TGFNUM
  FROM BKP_RMD_ALH_DUP_PPG_20260917;

SELECT NUNOTA, COUNT(*) AS LINHAS_APTAS_POR_NOTA
  FROM BKP_RMD_ALH_DUP_PPG_20260917
 WHERE STATUS_MAPA='APTO_PARA_INSERCAO_CONTROLADA'
 GROUP BY NUNOTA
HAVING COUNT(*)<>1
 ORDER BY NUNOTA;

PROMPT === CANDIDATOS APTOS; NENHUM TGFFIN FOI INSERIDO ===
SELECT NUNOTA, CODEMP, NUMNOTA, SERIENOTA, CODTIPOPER, CODTIPVENDA,
       VDUP_XML, DVENC_XML, NDUP_XML, CODTIPTITPAD,
       CODBCO_RESOLVIDO, CODCTABCOINT_RESOLVIDO,
       RECDESP_RESOLVIDO, TIPJURO_RESOLVIDO, STATUS_MAPA
  FROM BKP_RMD_ALH_DUP_PPG_20260917
 WHERE STATUS_MAPA='APTO_PARA_INSERCAO_CONTROLADA'
 ORDER BY NUNOTA, SEQ_PPG;

PROMPT === CARD 09 - MAPA CONCLUIDO; NENHUM TGFFIN FOI ALTERADO ===
SPOOL OFF
