-- Card 09 - pos-validacao independente para PRODUTOS ALHEIRO LTDA.
-- Somente leitura. Nao contem senha.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET SQLBLANKLINES ON
SET ECHO ON
SET FEEDBACK ON
WHENEVER OSERROR EXIT FAILURE ROLLBACK
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

SPOOL "/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Clientes/PRODUTOS ALHEIRO LTDA/Logs/Card09_Posvalidacao_20260917.log"

PROMPT === CARD 09 - POS-VALIDACAO INDEPENDENTE ===
PROMPT ID_EXECUCAO=RMD_FDUP_ALH_2026091701

SELECT SYS_CONTEXT('USERENV','SESSION_USER') AS SESSION_USER,
       SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AS CURRENT_SCHEMA,
       SYS_CONTEXT('USERENV','SERVICE_NAME') AS SERVICE_NAME,
       SYS_CONTEXT('USERENV','DB_NAME') AS DB_NAME
  FROM DUAL;

PROMPT === FUNCAO XML ===
SELECT OWNER, OBJECT_NAME, OBJECT_TYPE, STATUS
  FROM ALL_OBJECTS
 WHERE OBJECT_NAME='FNC_BUSCA_TAG_XML_GERAL'
 ORDER BY OWNER, OBJECT_TYPE;

SELECT OWNER, NAME, TYPE, LINE, POSITION, TEXT
  FROM ALL_ERRORS
 WHERE NAME='FNC_BUSCA_TAG_XML_GERAL'
 ORDER BY OWNER, SEQUENCE;

PROMPT === BACKUP E MAPA ===
SELECT COUNT(*) AS BACKUP_LINHAS,
       COUNT(DISTINCT NUNOTA) AS BACKUP_NOTAS,
       SUM(CASE WHEN STATUS_PREFLIGHT='CANDIDATO_XML_VALIDO' THEN 1 ELSE 0 END) AS BACKUP_XML_VALIDOS,
       SUM(CASE WHEN STATUS_PREFLIGHT='SEM_DUP_XML' THEN 1 ELSE 0 END) AS BACKUP_SEM_DUP
  FROM BKP_RMD_ALH_DUP_20260917
 WHERE ID_EXECUCAO='RMD_FDUP_ALH_2026091701';

SELECT STATUS_MAPA, COUNT(*) AS QTD
  FROM BKP_RMD_ALH_DUP_PPG_20260917
 WHERE ID_EXECUCAO_MAPA='RMD_FDUP_ALH_2026091701'
 GROUP BY STATUS_MAPA
 ORDER BY STATUS_MAPA;

SELECT COUNT(*) AS LINHAS_APTAS,
       COUNT(DISTINCT NUNOTA) AS NOTAS_APTAS,
       SUM(QTD_TGFFIN_ATUAL) AS TGFFIN_EXISTENTE_NO_MAPA,
       MIN(QTD_TGFNUM_TGFFIN) AS TGFNUM_LINHAS_MAPA,
       MIN(ULTCOD_TGFNUM_ATUAL) AS ULTCOD_TGFNUM_NO_MAPA
  FROM BKP_RMD_ALH_DUP_PPG_20260917
 WHERE ID_EXECUCAO_MAPA='RMD_FDUP_ALH_2026091701'
   AND STATUS_MAPA='APTO_PARA_INSERCAO_CONTROLADA';

PROMPT === AUDITORIA E ESTADO ATUAL ===
SELECT COUNT(*) AS AUDITORIA_INSERCOES
  FROM BKP_RMD_ALH_DUP_INS_20260917
 WHERE ID_EXECUCAO='RMD_FDUP_ALH_2026091701';

SELECT COUNT(*) AS TGFFIN_ATUAL_NOTAS_ESCUPO
  FROM TGFFIN F
 WHERE EXISTS (
       SELECT 1 FROM BKP_RMD_ALH_DUP_20260917 B
        WHERE B.ID_EXECUCAO='RMD_FDUP_ALH_2026091701'
          AND B.NUNOTA=F.NUNOTA);

SELECT COUNT(*) AS TGFNUM_LINHAS_ATUAIS,
       MIN(ULTCOD) AS ULTCOD_TGFNUM_ATUAL
  FROM TGFNUM
 WHERE ARQUIVO='TGFFIN';

PROMPT === VALIDACAO AUTOMATIZADA ===
DECLARE
  v_status VARCHAR2(30);
  v_errors NUMBER;
  v_backup NUMBER;
  v_map NUMBER;
  v_aptas NUMBER;
  v_audit NUMBER;
  v_fin NUMBER;
  v_num NUMBER;
  v_ultcod NUMBER;
  v_map_num NUMBER;
  v_map_ultcod NUMBER;
BEGIN
  SELECT MAX(STATUS) INTO v_status
    FROM ALL_OBJECTS
   WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
     AND OBJECT_NAME='FNC_BUSCA_TAG_XML_GERAL'
     AND OBJECT_TYPE='FUNCTION';
  SELECT COUNT(*) INTO v_errors
    FROM ALL_ERRORS
   WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
     AND NAME='FNC_BUSCA_TAG_XML_GERAL'
     AND TYPE='FUNCTION';
  SELECT COUNT(*) INTO v_backup
    FROM BKP_RMD_ALH_DUP_20260917
   WHERE ID_EXECUCAO='RMD_FDUP_ALH_2026091701';
  SELECT COUNT(*) INTO v_map
    FROM BKP_RMD_ALH_DUP_PPG_20260917
   WHERE ID_EXECUCAO_MAPA='RMD_FDUP_ALH_2026091701';
  SELECT COUNT(*) INTO v_aptas
    FROM BKP_RMD_ALH_DUP_PPG_20260917
   WHERE ID_EXECUCAO_MAPA='RMD_FDUP_ALH_2026091701'
     AND STATUS_MAPA='APTO_PARA_INSERCAO_CONTROLADA';
  SELECT COUNT(*) INTO v_audit
    FROM BKP_RMD_ALH_DUP_INS_20260917
   WHERE ID_EXECUCAO='RMD_FDUP_ALH_2026091701';
  SELECT COUNT(*) INTO v_fin
    FROM TGFFIN F
   WHERE EXISTS (SELECT 1 FROM BKP_RMD_ALH_DUP_PPG_20260917 M
                  WHERE M.ID_EXECUCAO_MAPA='RMD_FDUP_ALH_2026091701'
                    AND M.NUNOTA=F.NUNOTA);
  SELECT COUNT(*), NVL(MAX(ULTCOD),-1)
    INTO v_num, v_ultcod
    FROM TGFNUM WHERE ARQUIVO='TGFFIN';
  SELECT NVL(MIN(QTD_TGFNUM_TGFFIN),-1), NVL(MIN(ULTCOD_TGFNUM_ATUAL),-1)
    INTO v_map_num, v_map_ultcod
    FROM BKP_RMD_ALH_DUP_PPG_20260917
   WHERE ID_EXECUCAO_MAPA='RMD_FDUP_ALH_2026091701';

  DBMS_OUTPUT.PUT_LINE('FUNCAO_STATUS='||NVL(v_status,'AUSENTE'));
  DBMS_OUTPUT.PUT_LINE('FUNCAO_ERROS='||v_errors);
  DBMS_OUTPUT.PUT_LINE('BACKUP_LINHAS='||v_backup||'; MAPA_LINHAS='||v_map);
  DBMS_OUTPUT.PUT_LINE('LINHAS_APTAS='||v_aptas||'; AUDITORIA_INSERCOES='||v_audit);
  DBMS_OUTPUT.PUT_LINE('TGFFIN_ATUAL_NOTAS_ESCUPO='||v_fin);
  DBMS_OUTPUT.PUT_LINE('TGFNUM_ATUAL='||v_num||'; ULTCOD_ATUAL='||v_ultcod||
                       '; TGFNUM_MAPA='||v_map_num||'; ULTCOD_MAPA='||v_map_ultcod);

  IF v_status<>'VALID' OR v_errors<>0 OR v_backup<>1 OR v_map<>1 OR
     v_aptas<>0 OR v_audit<>0 OR v_fin<>0 OR v_num<>1 OR v_ultcod<>v_map_ultcod THEN
    RAISE_APPLICATION_ERROR(-20539,
      'Pos-validacao do Card 09 falhou; revisar log antes de concluir.');
  END IF;
  DBMS_OUTPUT.PUT_LINE('ERROS_VALIDACAO=0');
  DBMS_OUTPUT.PUT_LINE('STATUS=CONCLUIDA_SEM_DML_TGFFIN');
END;
/

PROMPT === CARD 09 - POS-VALIDACAO CONCLUIDA ===
SPOOL OFF
