-- Card 09 - executor controlado para PRODUTOS ALHEIRO LTDA.
-- Este ID possui zero candidatos aptos; o script cria somente a auditoria
-- persistente e encerra sem alterar TGFFIN ou TGFNUM.
-- Nao contem senha. Executar no VS Code como SCRIPT (F5).
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET SQLBLANKLINES ON
SET ECHO ON
SET FEEDBACK ON
WHENEVER OSERROR EXIT FAILURE ROLLBACK
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

SPOOL "/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Clientes/PRODUTOS ALHEIRO LTDA/Logs/Card09_32B_Insert_20260917.log"

PROMPT === CARD 09 - ATIVIDADE 32B CONTROLADA ===
PROMPT ID_EXECUCAO=RMD_FDUP_ALH_2026091701

DECLARE
  v_exists NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_exists
    FROM ALL_TABLES
   WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
     AND TABLE_NAME='BKP_RMD_ALH_DUP_INS_20260917';
  IF v_exists=0 THEN
    EXECUTE IMMEDIATE q'~
      CREATE TABLE BKP_RMD_ALH_DUP_INS_20260917 (
        ID_EXECUCAO VARCHAR2(40) NOT NULL,
        DH_EXECUCAO TIMESTAMP NOT NULL,
        NUNOTA NUMBER NOT NULL,
        NUFIN NUMBER NOT NULL,
        VLRDESDOB NUMBER,
        DTVENC DATE,
        CODCTABCOINT NUMBER,
        CODTIPTIT NUMBER,
        NDUP_XML VARCHAR2(4000)
      )~';
    DBMS_OUTPUT.PUT_LINE('AUDITORIA_CRIADA=BKP_RMD_ALH_DUP_INS_20260917');
  ELSE
    DBMS_OUTPUT.PUT_LINE('AUDITORIA_EXISTENTE=BKP_RMD_ALH_DUP_INS_20260917');
  END IF;
END;
/

DECLARE
  v_qtd NUMBER;
  v_notas NUMBER;
  v_audit NUMBER;
BEGIN
  SELECT COUNT(*), COUNT(DISTINCT NUNOTA)
    INTO v_qtd, v_notas
    FROM BKP_RMD_ALH_DUP_PPG_20260917
   WHERE ID_EXECUCAO_MAPA='RMD_FDUP_ALH_2026091701'
     AND STATUS_MAPA='APTO_PARA_INSERCAO_CONTROLADA';
  SELECT COUNT(*) INTO v_audit
    FROM BKP_RMD_ALH_DUP_INS_20260917
   WHERE ID_EXECUCAO='RMD_FDUP_ALH_2026091701';

  DBMS_OUTPUT.PUT_LINE('LINHAS_APTAS='||v_qtd||'; NOTAS_APTAS='||v_notas||
                       '; AUDITORIA_EXISTENTE='||v_audit);
  IF v_audit<>0 THEN
    RAISE_APPLICATION_ERROR(-20327,
      'Auditoria ja contem linhas para este ID; atividade nao repetida.');
  END IF;
  IF v_qtd<>0 OR v_notas<>0 THEN
    RAISE_APPLICATION_ERROR(-20325,
      'Mapa mudou e possui candidato apto; inclusao generica bloqueada.');
  END IF;

  DBMS_OUTPUT.PUT_LINE('STATUS=SEM_CANDIDATOS_APTOS');
  DBMS_OUTPUT.PUT_LINE('TGFFIN_ALTERADO=NAO');
  DBMS_OUTPUT.PUT_LINE('TGFNUM_ALTERADO=NAO');
  COMMIT;
END;
/

SELECT COUNT(*) AS TGFFIN_AUDITADOS
  FROM BKP_RMD_ALH_DUP_INS_20260917
 WHERE ID_EXECUCAO='RMD_FDUP_ALH_2026091701';

PROMPT === CARD 09 - ATIVIDADE 32B CONCLUIDA SEM DML DE NEGOCIO ===
SPOOL OFF
