
-- Somente leitura. Nao contem senha.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET ECHO ON
SET FEEDBACK ON
WHENEVER OSERROR EXIT FAILURE ROLLBACK
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
SPOOL "/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Clientes/PRODUTOS ALHEIRO LTDA/Logs/Pos_Validacao_Retomada_20260916.log"

PROMPT === POS-VALIDACAO INDEPENDENTE SOMENTE LEITURA ===
@@Pos_Validacao_Retomada_20260916.sql

SPOOL OFF
