-- Gerado automaticamente. Nao contem senha.
-- Abra este arquivo conectado a base correta e execute como SCRIPT (F5).
SET DEFINE ON
SET SERVEROUTPUT ON SIZE UNLIMITED
SET SQLBLANKLINES ON
WHENEVER OSERROR EXIT FAILURE ROLLBACK
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
SPOOL "/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Clientes/PRODUTOS ALHEIRO LTDA/Logs/Revisao_Master_20260916_1358.log"

PROMPT === PREFLIGHT SOMENTE LEITURA ===
@@"/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Clientes/PRODUTOS ALHEIRO LTDA/00_Preflight_Gate_ALHEIRO.sql"

PROMPT === QUOTA: CRITERIO PREVENTIVO DISPENSADO POR APROVACAO DO USUARIO ===
PROMPT O MASTER TENTARA CRIAR/PREENCHER OS BACKUPS PREVISTOS NOS INCLUDES.
PROMPT FALHA DE GRAVACAO DE BACKUP SERA TRATADA COMO ERRO DE ATIVIDADE.

PROMPT === CONFIRMACAO FORMAL: EXECUTAR PRODUTOS ALHEIRO LTDA ===
BEGIN
  IF UPPER(TRIM('EXECUTAR PRODUTOS ALHEIRO LTDA')) <> 'EXECUTAR PRODUTOS ALHEIRO LTDA' THEN
    RAISE_APPLICATION_ERROR(-20500,'Execucao cancelada: confirmacao da base divergente.');
  END IF;
  IF UPPER(SYS_CONTEXT('USERENV','SERVICE_NAME')) <> 'ALHEIROPRD.SANKHYACLOUD.COM.BR' THEN
    RAISE_APPLICATION_ERROR(-20501,'Execucao cancelada: SERVICE_NAME diferente do esperado (ALHEIROPRD.SANKHYACLOUD.COM.BR).');
  END IF;
END;
/

PROMPT === MASTER DEPLOY ATIVO - ATIVIDADES 01 A 31 ===
@@"/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Revisao Master Deploy/Revisao_Master_Deploy.sql"

SPOOL OFF
