-- Pos-validacao independente, somente leitura, da retomada 29-31.
-- Nao contem senha e nao executa DML/DDL.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET PAGESIZE 200
SET LINESIZE 240
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

PROMPT === IDENTIDADE FINAL ===
SELECT SYS_CONTEXT('USERENV','SESSION_USER') SESSION_USER,
       SYS_CONTEXT('USERENV','CURRENT_SCHEMA') CURRENT_SCHEMA,
       SYS_CONTEXT('USERENV','SERVICE_NAME') SERVICE_NAME,
       SYS_CONTEXT('USERENV','DB_NAME') DB_NAME
  FROM DUAL;

SELECT CODEMP,RAZAOSOCIAL
  FROM TSIEMP
 WHERE UPPER(TRIM(RAZAOSOCIAL))='PRODUTOS ALHEIRO LTDA';

SELECT REGEXP_SUBSTR(TEXTO,'[0-9]+\.[0-9]+[[:alpha:]][0-9]+') VERSAO_CURTA
  FROM TSIPAR
 WHERE CHAVE='VERSAOSKWBIN';

PROMPT === BACKUPS, MAPA E EXCECOES ===
SELECT 'BKP_RMD_PAD_TSIBAI' OBJETO,COUNT(*) QTD FROM BKP_RMD_PAD_TSIBAI
UNION ALL
SELECT 'BKP_RMD_PAD_TSIEND',COUNT(*) FROM BKP_RMD_PAD_TSIEND
UNION ALL
SELECT 'RMD_ALH_2930_MAP_ID',COUNT(*) FROM RMD_ALH_2930_MAP
 WHERE ID_EXECUCAO='RMD_ALH_2930_20260916161842236'
UNION ALL
SELECT 'RMD_ALH_2930_BAI_BKP_ID',COUNT(*) FROM RMD_ALH_2930_BAI_BKP
 WHERE ID_EXECUCAO='RMD_ALH_2930_20260916161842236'
UNION ALL
SELECT 'RMD_ALH_2930_END_BKP_ID',COUNT(*) FROM RMD_ALH_2930_END_BKP
 WHERE ID_EXECUCAO='RMD_ALH_2930_20260916161842236'
UNION ALL
SELECT 'RMD_ALH_2930_DEP_ID',COUNT(*) FROM RMD_ALH_2930_DEP
 WHERE ID_EXECUCAO='RMD_ALH_2930_20260916161842236'
UNION ALL
SELECT 'RMD_ALH_2930_EXC_ID',COUNT(*) FROM RMD_ALH_2930_EXC
 WHERE ID_EXECUCAO='RMD_ALH_2930_20260916161842236';

PROMPT === PAIS OBSOLETOS E DUPLICIDADES ===
SELECT 'TSIBAI_OBSOLETOS_REMANESCENTES' ITEM,COUNT(*) QTD
  FROM TSIBAI
 WHERE CODBAI IN (SELECT COD_OBSOLETO FROM RMD_ALH_2930_MAP WHERE ID_EXECUCAO='RMD_ALH_2930_20260916161842236' AND TIPO='BAI')
UNION ALL
SELECT 'TSIEND_OBSOLETOS_REMANESCENTES',COUNT(*)
  FROM TSIEND
 WHERE CODEND IN (SELECT COD_OBSOLETO FROM RMD_ALH_2930_MAP WHERE ID_EXECUCAO='RMD_ALH_2930_20260916161842236' AND TIPO='END')
UNION ALL
SELECT 'TSIBAI_GRUPOS_COLISAO_REMANESCENTES',COUNT(*)
  FROM (
    SELECT REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEBAI),
      'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ','AAAAAEEEEIIIIOOOOOUUUUC')),' {2,}',' ') N
      FROM TSIBAI WHERE NOMEBAI IS NOT NULL
     GROUP BY REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEBAI),
      'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ','AAAAAEEEEIIIIOOOOOUUUUC')),' {2,}',' ')
    HAVING COUNT(*)>1
  )
UNION ALL
SELECT 'TSIEND_GRUPOS_COLISAO_REMANESCENTES',COUNT(*)
  FROM (
    SELECT TIPO,REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEEND),
      'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ','AAAAAEEEEIIIIOOOOOUUUUC')),' {2,}',' ') N
      FROM TSIEND WHERE NOMEEND IS NOT NULL
     GROUP BY TIPO,REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEEND),
      'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ','AAAAAEEEEIIIIOOOOOUUUUC')),' {2,}',' ')
    HAVING COUNT(*)>1
  );

PROMPT === REFERENCIAS FISICAS REMANESCENTES ===
DECLARE
  v_owner VARCHAR2(128):=SYS_CONTEXT('USERENV','CURRENT_SCHEMA');
  v_id VARCHAR2(40):='RMD_ALH_2930_20260916161842236';
  v_sql VARCHAR2(32767);
  v_n NUMBER;
  v_refs NUMBER:=0;
  v_erros NUMBER:=0;
BEGIN
  FOR r IN (
    SELECT DISTINCT C.TABLE_NAME,C.COLUMN_NAME
      FROM ALL_TAB_COLUMNS C
      JOIN ALL_TABLES T ON T.OWNER=C.OWNER AND T.TABLE_NAME=C.TABLE_NAME
     WHERE C.OWNER=v_owner
       AND C.COLUMN_NAME IN ('CODBAI','CODEND')
       AND C.TABLE_NAME NOT IN ('TSIBAI','TSIEND')
       AND C.TABLE_NAME NOT LIKE 'BKP_RMD%'
       AND C.TABLE_NAME NOT LIKE 'RMD_ALH_2930%'
  ) LOOP
    BEGIN
      IF r.COLUMN_NAME='CODBAI' THEN
        v_sql:='SELECT COUNT(*) FROM '||r.TABLE_NAME||' T WHERE EXISTS (SELECT 1 FROM RMD_ALH_2930_MAP M WHERE M.ID_EXECUCAO=:1 AND M.TIPO=''BAI'' AND M.COD_OBSOLETO=T.CODBAI)';
      ELSE
        v_sql:='SELECT COUNT(*) FROM '||r.TABLE_NAME||' T WHERE EXISTS (SELECT 1 FROM RMD_ALH_2930_MAP M WHERE M.ID_EXECUCAO=:1 AND M.TIPO=''END'' AND M.COD_OBSOLETO=T.CODEND)';
      END IF;
      EXECUTE IMMEDIATE v_sql INTO v_n USING v_id;
      v_refs:=v_refs+v_n;
    EXCEPTION WHEN OTHERS THEN
      v_erros:=v_erros+1;
      DBMS_OUTPUT.PUT_LINE('ERRO_VALIDACAO_RAMO|'||r.TABLE_NAME||'|'||r.COLUMN_NAME||'|'||SQLERRM);
    END;
  END LOOP;

  FOR r IN (
    SELECT DISTINCT C.TABLE_NAME,CC.COLUMN_NAME,P.TABLE_NAME PAI
      FROM ALL_CONSTRAINTS C
      JOIN ALL_CONS_COLUMNS CC
        ON CC.OWNER=C.OWNER AND CC.CONSTRAINT_NAME=C.CONSTRAINT_NAME
       AND CC.POSITION IS NOT NULL
      JOIN ALL_CONSTRAINTS P
        ON P.OWNER=C.R_OWNER AND P.CONSTRAINT_NAME=C.R_CONSTRAINT_NAME
      JOIN ALL_CONS_COLUMNS PC
        ON PC.OWNER=P.OWNER AND PC.CONSTRAINT_NAME=P.CONSTRAINT_NAME
       AND PC.POSITION=CC.POSITION
     WHERE C.OWNER=v_owner AND C.CONSTRAINT_TYPE='R'
       AND P.OWNER=v_owner AND P.TABLE_NAME IN ('TSIBAI','TSIEND')
       AND PC.COLUMN_NAME IN ('CODBAI','CODEND')
       AND CC.COLUMN_NAME NOT IN ('CODBAI','CODEND')
       AND C.TABLE_NAME NOT IN ('TSIBAI','TSIEND')
       AND C.TABLE_NAME NOT LIKE 'BKP_RMD%'
       AND C.TABLE_NAME NOT LIKE 'RMD_ALH_2930%'
  ) LOOP
    BEGIN
      IF r.PAI='TSIBAI' THEN
        v_sql:='SELECT COUNT(*) FROM '||r.TABLE_NAME||' T WHERE EXISTS (SELECT 1 FROM RMD_ALH_2930_MAP M WHERE M.ID_EXECUCAO=:1 AND M.TIPO=''BAI'' AND M.COD_OBSOLETO=T.'||r.COLUMN_NAME||')';
      ELSE
        v_sql:='SELECT COUNT(*) FROM '||r.TABLE_NAME||' T WHERE EXISTS (SELECT 1 FROM RMD_ALH_2930_MAP M WHERE M.ID_EXECUCAO=:1 AND M.TIPO=''END'' AND M.COD_OBSOLETO=T.'||r.COLUMN_NAME||')';
      END IF;
      EXECUTE IMMEDIATE v_sql INTO v_n USING v_id;
      v_refs:=v_refs+v_n;
    EXCEPTION WHEN OTHERS THEN
      v_erros:=v_erros+1;
      DBMS_OUTPUT.PUT_LINE('ERRO_VALIDACAO_FK|'||r.TABLE_NAME||'|'||r.COLUMN_NAME||'|'||SQLERRM);
    END;
  END LOOP;
  DBMS_OUTPUT.PUT_LINE('REFERENCIAS_REMANESCENTES_FINAL='||v_refs||'; ERROS_VALIDACAO='||v_erros);
END;
/

PROMPT === OBJETOS TEMPORARIOS E INVALIDOS ===
SELECT ID_MASTER,ID_EXECUCAO,OBJECT_TYPE,OBJECT_NAME,STATUS_ANTES,STATUS_DEPOIS,DH_REABILITACAO
  FROM RMD_CONTROLE_OBJETOS
 WHERE ID_MASTER='RMD_RUN_20260916135606162'
 ORDER BY DH_REGISTRO;

SELECT OWNER,OBJECT_TYPE,OBJECT_NAME,STATUS
  FROM ALL_OBJECTS
 WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
   AND STATUS='INVALID'
 ORDER BY OBJECT_TYPE,OBJECT_NAME;

SELECT 'USER_TS_QUOTAS' ITEM,COUNT(*) QTD FROM USER_TS_QUOTAS
UNION ALL
SELECT 'ALTER_ANY_PROCEDURE',COUNT(*) FROM SESSION_PRIVS WHERE PRIVILEGE='ALTER ANY PROCEDURE';

PROMPT === FIM POS-VALIDACAO RETOMADA 29-31 ===
