-- Pos-validacao somente leitura da execucao RMD_RUN_20260916135606162.
-- Nao contem senha e nao executa DML/DDL.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET PAGESIZE 200
SET LINESIZE 240

SELECT SYS_CONTEXT('USERENV','SESSION_USER') SESSION_USER,
       SYS_CONTEXT('USERENV','CURRENT_SCHEMA') CURRENT_SCHEMA,
       SYS_CONTEXT('USERENV','SERVICE_NAME') SERVICE_NAME
FROM DUAL;

SELECT CODEMP,RAZAOSOCIAL
FROM TSIEMP
WHERE UPPER(TRIM(RAZAOSOCIAL))='PRODUTOS ALHEIRO LTDA';

SELECT REGEXP_SUBSTR(TEXTO,'[0-9]+\.[0-9]+b[0-9]+') VERSAO_CURTA
FROM TSIPAR
WHERE CHAVE='VERSAOSKWBIN';

SELECT OWNER,OBJECT_TYPE,OBJECT_NAME,STATUS
FROM ALL_OBJECTS
WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
  AND STATUS='INVALID'
ORDER BY OBJECT_TYPE,OBJECT_NAME;

SELECT 'RMD_CONTROLE_OBJETOS' OBJETO,COUNT(*) QTD
FROM RMD_CONTROLE_OBJETOS
WHERE ID_MASTER='RMD_RUN_20260916135606162'
UNION ALL
SELECT 'RMD_MAP_UNIDADES',COUNT(*)
FROM RMD_MAP_UNIDADES
UNION ALL
SELECT 'BKP_RMD_UNID_MAP',COUNT(*)
FROM BKP_RMD_UNID_MAP
UNION ALL
SELECT 'BKP_RMD_TSICFG',COUNT(*)
FROM BKP_RMD_TSICFG
UNION ALL
SELECT 'BKP_RMD_PAD_TGFTPV_EXEC_28',COUNT(*)
FROM BKP_RMD_PAD_TGFTPV
WHERE ID_EXECUCAO='RMD_TPV_20260916140020711';

SELECT TABLE_NAME
FROM ALL_TABLES
WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
  AND TABLE_NAME IN (
    'BKP_RMD_GOL_TSIPAR','BKP_RMD_GOL_TGFCGM','BKP_RMD_GOL_TGFCMV',
    'BKP_RMD_PAR_MATRIZ','BKP_RMD_CARD_TTKINDAGT','BKP_CLASSICMS_TGFPAR',
    'BKP_AJNP_TGFPAR','BKP_RMD_PAD_TGFPAR','BKP_RMD_PAD_TGFPRO',
    'BKP_RMD_PAD_TGFTIT','BKP_RMD_PAD_TSICID','BKP_RMD_PAD_TGFTPV',
    'BKP_RMD_PAD_TSIBAI','BKP_RMD_PAD_TSIEND'
  )
ORDER BY TABLE_NAME;

SELECT ID_MASTER,ID_EXECUCAO,OBJECT_TYPE,OBJECT_NAME,STATUS_ANTES,STATUS_DEPOIS,DH_REABILITACAO
FROM RMD_CONTROLE_OBJETOS
WHERE ID_MASTER='RMD_RUN_20260916135606162'
ORDER BY DH_REGISTRO;
