-- Rollback explicito do merge antifragil especifico de PRODUTOS ALHEIRO LTDA.
-- Nao contem senha e nao executa nada sem a substituicao consciente do ID abaixo.
-- Manter mapa, dependencias e backups persistentes apos o rollback para auditoria.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET SQLBLANKLINES ON
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

DECLARE
  v_owner VARCHAR2(128):=SYS_CONTEXT('USERENV','CURRENT_SCHEMA');
  v_id VARCHAR2(40):='INFORMAR_ID_EXECUCAO_NO_LOG';
  v_sql VARCHAR2(32767);
  v_cols VARCHAR2(32767);
  v_n NUMBER;
  v_i NUMBER:=0;

  FUNCTION colunas(p_tabela VARCHAR2) RETURN VARCHAR2 IS
    v_ret VARCHAR2(32767);
  BEGIN
    SELECT LISTAGG(COLUMN_NAME,',') WITHIN GROUP(ORDER BY COLUMN_ID)
      INTO v_ret
      FROM ALL_TAB_COLUMNS
     WHERE OWNER=v_owner AND TABLE_NAME=p_tabela;
    RETURN v_ret;
  END;
BEGIN
  IF v_id='INFORMAR_ID_EXECUCAO_NO_LOG' THEN
    RAISE_APPLICATION_ERROR(-20590,'Rollback protegido: informe o ID_EXECUCAO exato do log.');
  END IF;

  SELECT COUNT(*) INTO v_n FROM RMD_ALH_2930_MAP WHERE ID_EXECUCAO=v_id;
  IF v_n=0 THEN
    RAISE_APPLICATION_ERROR(-20591,'Rollback protegido: mapa ausente para o ID_EXECUCAO informado.');
  END IF;

  v_cols:=colunas('TSIBAI');
  v_sql:='INSERT INTO TSIBAI ('||v_cols||') SELECT B.'||REPLACE(v_cols,',',',B.')||
    ' FROM RMD_ALH_2930_BAI_BKP B WHERE B.ID_EXECUCAO=:1 '||
    'AND B.CODBAI IN (SELECT COD_OBSOLETO FROM RMD_ALH_2930_MAP WHERE ID_EXECUCAO=:2 AND TIPO=''BAI'') '||
    'AND NOT EXISTS (SELECT 1 FROM TSIBAI T WHERE T.CODBAI=B.CODBAI)';
  EXECUTE IMMEDIATE v_sql USING v_id,v_id;
  DBMS_OUTPUT.PUT_LINE('TSIBAI_REINSERIDOS='||SQL%ROWCOUNT);

  v_cols:=colunas('TSIEND');
  v_sql:='INSERT INTO TSIEND ('||v_cols||') SELECT B.'||REPLACE(v_cols,',',',B.')||
    ' FROM RMD_ALH_2930_END_BKP B WHERE B.ID_EXECUCAO=:1 '||
    'AND B.CODEND IN (SELECT COD_OBSOLETO FROM RMD_ALH_2930_MAP WHERE ID_EXECUCAO=:2 AND TIPO=''END'') '||
    'AND NOT EXISTS (SELECT 1 FROM TSIEND T WHERE T.CODEND=B.CODEND)';
  EXECUTE IMMEDIATE v_sql USING v_id,v_id;
  DBMS_OUTPUT.PUT_LINE('TSIEND_REINSERIDOS='||SQL%ROWCOUNT);

  FOR r IN (
    SELECT DISTINCT TABLE_NAME,COLUMN_NAME
      FROM RMD_ALH_2930_DEP
     WHERE ID_EXECUCAO=v_id
     ORDER BY TABLE_NAME,COLUMN_NAME
  ) LOOP
    v_sql:='UPDATE '||r.TABLE_NAME||' T SET '||r.COLUMN_NAME||
      '=(SELECT D.OLD_VALUE FROM RMD_ALH_2930_DEP D WHERE D.ID_EXECUCAO=:1 '||
      'AND D.TABLE_NAME=:2 AND D.COLUMN_NAME=:3 AND D.RID=ROWIDTOCHAR(T.ROWID)) '||
      'WHERE EXISTS (SELECT 1 FROM RMD_ALH_2930_DEP D WHERE D.ID_EXECUCAO=:4 '||
      'AND D.TABLE_NAME=:5 AND D.COLUMN_NAME=:6 AND D.RID=ROWIDTOCHAR(T.ROWID))';
    EXECUTE IMMEDIATE v_sql USING v_id,r.TABLE_NAME,r.COLUMN_NAME,v_id,r.TABLE_NAME,r.COLUMN_NAME;
    v_i:=v_i+SQL%ROWCOUNT;
  END LOOP;
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('DEPENDENCIAS_RESTAURADAS='||v_i);
  DBMS_OUTPUT.PUT_LINE('STATUS=ROLLBACK_CONCLUIDO_MAPA_E_BACKUPS_PRESERVADOS; ID_EXECUCAO='||v_id);
EXCEPTION WHEN OTHERS THEN
  ROLLBACK;
  RAISE;
END;
/
