SET DEFINE ON
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
ACCEPT P_ID_EXECUCAO CHAR PROMPT 'ID da execucao RMD_UNID_: '
DECLARE
 v_total NUMBER:=0;v_s1 VARCHAR2(8);v_s2 VARCHAR2(8);
 PROCEDURE reinsere(p_tab VARCHAR2) IS v_cols CLOB;v_sql CLOB;BEGIN
  SELECT LISTAGG(COLUMN_NAME,',') WITHIN GROUP(ORDER BY COLUMN_ID) INTO v_cols FROM ALL_TAB_COLUMNS
   WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND TABLE_NAME=p_tab;
  v_sql:='INSERT INTO '||p_tab||' ('||v_cols||') SELECT '||v_cols||' FROM BKP_RMD_UNID_'||p_tab||' WHERE ID_EXECUCAO=:1';
  EXECUTE IMMEDIATE v_sql USING '&&P_ID_EXECUCAO';v_total:=v_total+SQL%ROWCOUNT;
 END;
 PROCEDURE restaura IS BEGIN
  IF v_s1='ENABLED' THEN EXECUTE IMMEDIATE 'ALTER TRIGGER TRG_INC_UPD_TGFITE ENABLE';END IF;
  IF v_s2='ENABLED' THEN EXECUTE IMMEDIATE 'ALTER TRIGGER TRG_UPT_TGFITE ENABLE';END IF;
 END;
BEGIN
 SELECT STATUS INTO v_s1 FROM ALL_TRIGGERS WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND TRIGGER_NAME='TRG_INC_UPD_TGFITE';
 SELECT STATUS INTO v_s2 FROM ALL_TRIGGERS WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND TRIGGER_NAME='TRG_UPT_TGFITE';
 IF v_s1='ENABLED' THEN EXECUTE IMMEDIATE 'ALTER TRIGGER TRG_INC_UPD_TGFITE DISABLE';END IF;
 IF v_s2='ENABLED' THEN EXECUTE IMMEDIATE 'ALTER TRIGGER TRG_UPT_TGFITE DISABLE';END IF;
 reinsere('TGFVOL');reinsere('TGFVOA');
 MERGE INTO TGFPRO T USING(SELECT * FROM BKP_RMD_UNID_TGFPRO WHERE ID_EXECUCAO='&&P_ID_EXECUCAO')B ON(T.ROWID=CHARTOROWID(B.ROWID_ORIGINAL)) WHEN MATCHED THEN UPDATE SET T.CODVOL=B.CODVOL;v_total:=v_total+SQL%ROWCOUNT;
 MERGE INTO TGFITE T USING(SELECT * FROM BKP_RMD_UNID_TGFITE WHERE ID_EXECUCAO='&&P_ID_EXECUCAO')B ON(T.ROWID=CHARTOROWID(B.ROWID_ORIGINAL)) WHEN MATCHED THEN UPDATE SET T.CODVOL=B.CODVOL;v_total:=v_total+SQL%ROWCOUNT;
 MERGE INTO TGFPAP T USING(SELECT * FROM BKP_RMD_UNID_TGFPAP WHERE ID_EXECUCAO='&&P_ID_EXECUCAO')B ON(T.ROWID=CHARTOROWID(B.ROWID_ORIGINAL)) WHEN MATCHED THEN UPDATE SET T.UNIDADEPARC=B.UNIDADEPARC;v_total:=v_total+SQL%ROWCOUNT;
 MERGE INTO TGFCOI2 T USING(SELECT * FROM BKP_RMD_UNID_TGFCOI2 WHERE ID_EXECUCAO='&&P_ID_EXECUCAO')B ON(T.ROWID=CHARTOROWID(B.ROWID_ORIGINAL)) WHEN MATCHED THEN UPDATE SET T.CODVOL=B.CODVOL;v_total:=v_total+SQL%ROWCOUNT;
 MERGE INTO TGFGIR1 T USING(SELECT * FROM BKP_RMD_UNID_TGFGIR1 WHERE ID_EXECUCAO='&&P_ID_EXECUCAO')B ON(T.ROWID=CHARTOROWID(B.ROWID_ORIGINAL)) WHEN MATCHED THEN UPDATE SET T.CODVOL=B.CODVOL;v_total:=v_total+SQL%ROWCOUNT;
 DELETE FROM RMD_MAP_UNIDADES;
 INSERT INTO RMD_MAP_UNIDADES(FROM_CODE,TO_CODE)
 SELECT FROM_CODE,TO_CODE FROM BKP_RMD_UNID_MAP WHERE ID_EXECUCAO='&&P_ID_EXECUCAO';
 restaura;
 IF v_total=0 THEN RAISE_APPLICATION_ERROR(-20331,'Backup de unidades nao encontrado.');END IF;
 COMMIT;DBMS_OUTPUT.PUT_LINE('REGISTROS_REVERTIDOS='||v_total);
EXCEPTION WHEN OTHERS THEN BEGIN restaura;EXCEPTION WHEN OTHERS THEN NULL;END;ROLLBACK;RAISE;END;
/
UNDEFINE P_ID_EXECUCAO
