SET DEFINE ON
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
ACCEPT P_ID_EXECUCAO CHAR PROMPT 'ID da execucao RMD_TOPG_: '
DECLARE v_b PLS_INTEGER; v_u PLS_INTEGER; BEGIN
 SELECT COUNT(*) INTO v_b FROM BKP_RMD_12_TGFTOP WHERE ID_EXECUCAO='&&P_ID_EXECUCAO';
 IF v_b=0 THEN RAISE_APPLICATION_ERROR(-20211,'Backup nao encontrado.'); END IF;
 MERGE INTO TGFTOP T USING (SELECT * FROM BKP_RMD_12_TGFTOP WHERE ID_EXECUCAO='&&P_ID_EXECUCAO') B
 ON (T.ROWID=CHARTOROWID(B.ROWID_ORIGINAL)) WHEN MATCHED THEN UPDATE SET T.GOLSINAL=B.GOLSINAL_ANTES, T.GOLMPSINAL=B.GOLMPSINAL_ANTES, T.GOLDEV=B.GOLDEV_ANTES, T.ANALISEGIRO=B.ANALISEGIRO_ANTES, T.ATUALULTIMAVEND=B.ATUALULTIMAVEND_ANTES, T.ATUALULTIMACOMP=B.ATUALULTIMACOMP_ANTES;
 v_u:=SQL%ROWCOUNT; IF v_b<>v_u THEN RAISE_APPLICATION_ERROR(-20212,'Rollback divergente.'); END IF;
 COMMIT; DBMS_OUTPUT.PUT_LINE('REGISTROS_REVERTIDOS='||v_u);
EXCEPTION WHEN OTHERS THEN ROLLBACK; RAISE; END;
/
UNDEFINE P_ID_EXECUCAO

