-- Reverte a padronizacao de TSIEND da execucao informada.
SET DEFINE ON
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
ACCEPT P_ID_EXECUCAO CHAR PROMPT 'ID da execucao RMD_END_: '
DECLARE v_bkp NUMBER;v_upd NUMBER;BEGIN SELECT COUNT(*) INTO v_bkp FROM BKP_RMD_PAD_TSIEND WHERE ID_EXECUCAO='&&P_ID_EXECUCAO';IF v_bkp=0 THEN RAISE_APPLICATION_ERROR(-20352,'Backup de TSIEND nao encontrado.');END IF;MERGE INTO TSIEND T USING(SELECT * FROM BKP_RMD_PAD_TSIEND WHERE ID_EXECUCAO='&&P_ID_EXECUCAO') B ON(T.ROWID=CHARTOROWID(B.ROWID_ORIGINAL)) WHEN MATCHED THEN UPDATE SET T.NOMEEND=B.NOMEEND;v_upd:=SQL%ROWCOUNT;IF v_upd<>v_bkp THEN RAISE_APPLICATION_ERROR(-20353,'Rollback TSIEND divergente.');END IF;COMMIT;DBMS_OUTPUT.PUT_LINE('REGISTROS_REVERTIDOS='||v_upd);EXCEPTION WHEN OTHERS THEN ROLLBACK;RAISE;END;
/
UNDEFINE P_ID_EXECUCAO
