SET DEFINE ON
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
ACCEPT P_ID_EXECUCAO CHAR PROMPT 'ID da execucao RMD_RUPE_: '
DECLARE v_b PLS_INTEGER;v_u PLS_INTEGER;BEGIN
 SELECT COUNT(*) INTO v_b FROM BKP_RMD_11_TGFEMP WHERE ID_EXECUCAO='&&P_ID_EXECUCAO';
 IF v_b=0 THEN RAISE_APPLICATION_ERROR(-20231,'Backup nao encontrado.');END IF;
 MERGE INTO TGFEMP E USING(SELECT * FROM BKP_RMD_11_TGFEMP WHERE ID_EXECUCAO='&&P_ID_EXECUCAO')B
 ON(E.ROWID=CHARTOROWID(B.ROWID_ORIGINAL)) WHEN MATCHED THEN UPDATE SET E.RUPTURAEST=B.RUPTURAEST_ANTES;
 v_u:=SQL%ROWCOUNT;IF v_b<>v_u THEN RAISE_APPLICATION_ERROR(-20232,'Rollback divergente.');END IF;
 COMMIT;DBMS_OUTPUT.PUT_LINE('EMPRESAS_REVERTIDAS='||v_u);
EXCEPTION WHEN OTHERS THEN ROLLBACK;RAISE;END;
/
UNDEFINE P_ID_EXECUCAO
