-- Pos-validacao read-only do Master 01-31 (MEDCHAP DISTRIBUIDORA DE MEDICAMENTOS CHAPECO LTDA). Somente SELECT. Usada como --post-script do lote.
-- Linha de base: 9 triggers ja estavam DISABLED antes da revisao (Logs/P15_Triggers_Desabilitados_20260925_075545.json);
-- o Master so reabilita o que estava ENABLED antes (RMD_CONTROLE_OBJETOS).
SELECT METRICA, VALOR
  FROM (
    SELECT 'SESSION_USER' METRICA, SYS_CONTEXT('USERENV','SESSION_USER') VALOR FROM DUAL
    UNION ALL SELECT 'CURRENT_SCHEMA', SYS_CONTEXT('USERENV','CURRENT_SCHEMA') FROM DUAL
    UNION ALL SELECT 'SERVICE_NAME', SYS_CONTEXT('USERENV','SERVICE_NAME') FROM DUAL
    UNION ALL SELECT 'DB_NAME', SYS_CONTEXT('USERENV','DB_NAME') FROM DUAL
    UNION ALL SELECT 'CONTROLE_TOTAL', TO_CHAR(COUNT(*)) FROM RMD_CONTROLE_OBJETOS
    UNION ALL SELECT 'CONTROLE_PENDENTE', TO_CHAR(COUNT(*)) FROM RMD_CONTROLE_OBJETOS
      WHERE STATUS_ANTES='ENABLED' AND NVL(STATUS_DEPOIS,'PENDENTE')<>'ENABLED'
    UNION ALL SELECT 'TRIGGERS_NAO_ENABLED', TO_CHAR(COUNT(*)) FROM ALL_TRIGGERS
      WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND STATUS<>'ENABLED'
    UNION ALL SELECT 'TRIGGERS_NAO_ENABLED_FORA_LINHA_BASE', TO_CHAR(COUNT(*)) FROM ALL_TRIGGERS
      WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND STATUS<>'ENABLED'
        AND TRIGGER_NAME NOT IN ('TRG_UPD_TFPBSU','TRG_UPD_TGFCAB_EST','TRG_UPT_TGFFIN_NUBCO','TRG_INC_UPD_TGFIPI',
                                 'TRG_INC_TGFITE','TRG_INC_UPD_DLT_TGFITE_ESE','TRG_INC_UPD_TGFPAR_AFTER',
                                 'TRG_INC_UPD_TGFPRO','TRG_INC_TGFVOL')
    UNION ALL SELECT 'OBJETOS_INVALIDOS', TO_CHAR(COUNT(*)) FROM ALL_OBJECTS
      WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND STATUS='INVALID'
    UNION ALL SELECT 'TSIBAI_TOTAL', TO_CHAR(COUNT(*)) FROM TSIBAI
    UNION ALL SELECT 'TSIEND_TOTAL', TO_CHAR(COUNT(*)) FROM TSIEND
    UNION ALL SELECT 'UNIDADES_MAPEADAS', TO_CHAR(COUNT(*)) FROM RMD_MAP_UNIDADES
    UNION ALL SELECT 'BACKUPS_RMD', TO_CHAR(COUNT(*)) FROM ALL_TABLES
      WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND TABLE_NAME LIKE 'BKP\_RMD\_%' ESCAPE '\'
    UNION ALL SELECT 'INTEG_ITENS_SEM_CAB', TO_CHAR(COUNT(*)) FROM TGFITE I
      WHERE NOT EXISTS (SELECT 1 FROM TGFCAB C WHERE C.NUNOTA=I.NUNOTA)
    UNION ALL SELECT 'INTEG_CAB_SEM_ITENS', TO_CHAR(COUNT(*)) FROM TGFCAB C
      WHERE NOT EXISTS (SELECT 1 FROM TGFITE I WHERE I.NUNOTA=C.NUNOTA)
    UNION ALL SELECT 'INTEG_FIN_SEM_NOTA', TO_CHAR(COUNT(*)) FROM TGFFIN F
      WHERE F.NUNOTA IS NOT NULL AND NOT EXISTS (SELECT 1 FROM TGFCAB C WHERE C.NUNOTA=F.NUNOTA)
  )
 ORDER BY METRICA;
