-- Pos-validacao read-only da fase 2 (exclusao dos pais obsoletos) MEDCHAP DISTRIBUIDORA DE MEDICAMENTOS CHAPECO LTDA.
SELECT 'SESSION_USER' AS METRICA, SYS_CONTEXT('USERENV','SESSION_USER') AS VALOR FROM DUAL
UNION ALL SELECT 'CURRENT_SCHEMA', SYS_CONTEXT('USERENV','CURRENT_SCHEMA') FROM DUAL
UNION ALL SELECT 'SERVICE_NAME', SYS_CONTEXT('USERENV','SERVICE_NAME') FROM DUAL
UNION ALL SELECT 'MAPA_BAI', TO_CHAR(COUNT(*)) FROM RMD_MDCH_MRG_20260925
  WHERE ID_EXECUCAO='MEDCHAP_MRG_20260925_01' AND TIPO='BAI'
UNION ALL SELECT 'MAPA_END', TO_CHAR(COUNT(*)) FROM RMD_MDCH_MRG_20260925
  WHERE ID_EXECUCAO='MEDCHAP_MRG_20260925_01' AND TIPO='END'
UNION ALL SELECT 'BACKUP_BAI_OBSOLETO', TO_CHAR(COUNT(*)) FROM BKP_RMD_MDCH_20260925_BAI
  WHERE ID_EXECUCAO='MEDCHAP_MRG_20260925_01'
UNION ALL SELECT 'BACKUP_END_OBSOLETO', TO_CHAR(COUNT(*)) FROM BKP_RMD_MDCH_20260925_END
  WHERE ID_EXECUCAO='MEDCHAP_MRG_20260925_01'
UNION ALL SELECT 'AUDITORIA_REFERENCIAS', TO_CHAR(COUNT(*)) FROM RMD_MDCH_MRG_20260925_DEP
  WHERE ID_EXECUCAO='MEDCHAP_MRG_20260925_01'
UNION ALL SELECT 'EXCECOES', TO_CHAR(COUNT(*)) FROM RMD_MDCH_MRG_20260925_EXC
  WHERE ID_EXECUCAO='MEDCHAP_MRG_20260925_01'
UNION ALL SELECT 'PAIS_BAI_OBSOLETO_REMANESCENTE', TO_CHAR(COUNT(*)) FROM TSIBAI p
  WHERE EXISTS (SELECT 1 FROM RMD_MDCH_MRG_20260925 m
    WHERE m.ID_EXECUCAO='MEDCHAP_MRG_20260925_01' AND m.TIPO='BAI' AND m.COD_OBSOLETO=p.CODBAI)
UNION ALL SELECT 'PAIS_END_OBSOLETO_REMANESCENTE', TO_CHAR(COUNT(*)) FROM TSIEND p
  WHERE EXISTS (SELECT 1 FROM RMD_MDCH_MRG_20260925 m
    WHERE m.ID_EXECUCAO='MEDCHAP_MRG_20260925_01' AND m.TIPO='END' AND m.COD_OBSOLETO=p.CODEND);
