-- Pos-validacao read-only da fase 3 29/30 MEDCHAP (sem consulta a fila de eventos: estrutura nao verificada nesta base).
WITH BAI AS (
  SELECT NOME,NORM,COUNT(*) OVER(PARTITION BY NORM) QTD
    FROM (SELECT NOMEBAI NOME,
          REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEBAI),
            'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇáàâãäéèêëíìîïóòôõöúùûüçÃãÕõÂâÊêÎîÔôÛû',
            'AAAAAEEEEIIIIOOOOOUUUUCAAAAAEEEEIIIIOOOOOUUUUCAAAOOAAEIIOOUU')),
            ' {2,}',' ') NORM FROM TSIBAI)
), ENDERECOS AS (
  SELECT TIPO,NOME,NORM,COUNT(*) OVER(PARTITION BY TIPO,NORM) QTD
    FROM (SELECT TIPO,NOMEEND NOME,
          REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEEND),
            'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇáàâãäéèêëíìîïóòôõöúùûüçÃãÕõÂâÊêÎîÔôÛû',
            'AAAAAEEEEIIIIOOOOOUUUUCAAAAAEEEEIIIIOOOOOUUUUCAAAOOAAEIIOOUU')),
            ' {2,}',' ') NORM FROM TSIEND)
)
SELECT 'SESSION_USER' AS METRICA,SYS_CONTEXT('USERENV','SESSION_USER') AS VALOR FROM DUAL
UNION ALL SELECT 'CURRENT_SCHEMA',SYS_CONTEXT('USERENV','CURRENT_SCHEMA') FROM DUAL
UNION ALL SELECT 'SERVICE_NAME',SYS_CONTEXT('USERENV','SERVICE_NAME') FROM DUAL
UNION ALL SELECT 'ID_EXECUCAO', 'MEDCHAP_NORM2930_20260925_01' FROM DUAL
UNION ALL SELECT 'BACKUP_BAIRROS',TO_CHAR(COUNT(*)) FROM BKP_RMD_PAD_TSIBAI
  WHERE ID_EXECUCAO='MEDCHAP_NORM2930_20260925_01'
UNION ALL SELECT 'BACKUP_ENDERECOS',TO_CHAR(COUNT(*)) FROM BKP_RMD_PAD_TSIEND
  WHERE ID_EXECUCAO='MEDCHAP_NORM2930_20260925_01'
UNION ALL SELECT 'CANDIDATOS_NAO_NORMALIZADOS_BAIRROS',TO_CHAR(COUNT(*)) FROM BAI
  WHERE QTD=1 AND DECODE(NOME,NORM,0,1)=1
UNION ALL SELECT 'COLISOES_BAIRROS',TO_CHAR(COUNT(*)) FROM (
  SELECT NORM FROM BAI GROUP BY NORM HAVING COUNT(*)>1
)
UNION ALL SELECT 'CANDIDATOS_NAO_NORMALIZADOS_ENDERECOS',TO_CHAR(COUNT(*)) FROM ENDERECOS
  WHERE QTD=1 AND DECODE(NOME,NORM,0,1)=1
UNION ALL SELECT 'COLISOES_ENDERECOS',TO_CHAR(COUNT(*)) FROM (
  SELECT TIPO,NORM FROM ENDERECOS GROUP BY TIPO,NORM HAVING COUNT(*)>1
);
