-- Pos-validacao read-only do mapa Card 09 MEDCHAP (MEDCHAP_FDUP_20260925_01).
-- Origem: versao R02 da FOCUSFINTAXPRD (instrucao unica, sem ORA-00937). Linha de base P19 25/09: TGFNUM TGFFIN 1 linha, ULTCOD 1354826, TOTAL_TGFFIN 1329720.
SELECT 'BASE_TOTAL_MAPA' AS METRICA, TO_CHAR(COUNT(*)) AS VALOR FROM BKP_RMD_FDUP_MDC_20260925 WHERE ID_EXECUCAO='MEDCHAP_FDUP_20260925_01'
UNION ALL SELECT 'LINHAS_CLASSIFICACAO', TO_CHAR(COUNT(*)) FROM BKP_RMD_FDUP_MDC_20260925_PPG WHERE ID_EXECUCAO='MEDCHAP_FDUP_20260925_01'
UNION ALL SELECT 'APTO_PARA_VALIDACAO_FINAL', TO_CHAR(COUNT(*)) FROM BKP_RMD_FDUP_MDC_20260925_PPG WHERE ID_EXECUCAO='MEDCHAP_FDUP_20260925_01' AND STATUS_MAPA='APTO_PARA_VALIDACAO_FINAL'
UNION ALL SELECT 'SEM_VDUP_XML', TO_CHAR(COUNT(*)) FROM BKP_RMD_FDUP_MDC_20260925_PPG WHERE ID_EXECUCAO='MEDCHAP_FDUP_20260925_01' AND STATUS_MAPA='SEM_VDUP_XML'
UNION ALL SELECT 'TABELAS_MAPA_EXISTENTES', TO_CHAR(COUNT(*)) FROM ALL_TABLES WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND TABLE_NAME IN ('BKP_RMD_FDUP_MDC_20260925','BKP_RMD_FDUP_MDC_20260925_PPG')
UNION ALL SELECT 'ESCOPO_DASHBOARD_NOTAS_SEM_FIN', TO_CHAR(COUNT(*)) FROM TGFCAB C JOIN TGFTOP T ON T.CODTIPOPER=C.CODTIPOPER AND T.DHALTER=C.DHTIPOPER
 WHERE T.ATUALFIN<>0 AND C.TIPMOV<>'Z' AND NOT EXISTS (SELECT 1 FROM TGFFIN F WHERE F.NUNOTA=C.NUNOTA)
UNION ALL SELECT 'LINHAS_TGFNUM_TGFFIN', TO_CHAR(COUNT(*)) FROM TGFNUM WHERE ARQUIVO='TGFFIN'
UNION ALL SELECT 'ULTCOD_TGFNUM_TGFFIN', TO_CHAR(MAX(ULTCOD)) FROM TGFNUM WHERE ARQUIVO='TGFFIN'
UNION ALL SELECT 'TOTAL_TGFFIN', TO_CHAR(COUNT(*)) FROM TGFFIN;
