-- Pos-validacao read-only da atividade 33 (MEDCHAP_CAR_20260925_02).
SELECT 'MAPA_'||STATUS AS METRICA, TO_CHAR(COUNT(*)) AS VALOR FROM RMD_MDCH_CAR_20260925_02 WHERE ID_EXECUCAO='MEDCHAP_CAR_20260925_02' GROUP BY STATUS
UNION ALL SELECT 'BACKUP_TSIUSU', TO_CHAR(COUNT(*)) FROM ALL_TABLES WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND TABLE_NAME='BKP_RMD_MDCH_CAR02_TSIUSU'
UNION ALL SELECT 'TSIUSU_102_NOMEUSU', NOMEUSU FROM TSIUSU WHERE CODUSU=102
UNION ALL SELECT 'TSIUSU_NOMEUSU_COM_INTERROGACAO_INVERTIDA', TO_CHAR(COUNT(*)) FROM TSIUSU WHERE INSTR(NOMEUSU,UNISTR('\00BF'))>0
UNION ALL SELECT 'TGFPAR_COM_INTERROGACAO_INVERTIDA', TO_CHAR(COUNT(*)) FROM TGFPAR WHERE INSTR(NOMEPARC||RAZAOSOCIAL||COMPLEMENTO,UNISTR('\00BF'))>0
UNION ALL SELECT 'TGFPRO_COM_INTERROGACAO_INVERTIDA', TO_CHAR(COUNT(*)) FROM TGFPRO WHERE INSTR(DESCRPROD||COMPLDESC||DESCRANP,UNISTR('\00BF'))>0
UNION ALL SELECT 'TSIUSU_LOGIN_JOAO_GONCALVES_QTD', TO_CHAR(COUNT(*)) FROM TSIUSU WHERE UPPER(NOMEUSU)='JOAO.GONCALVES';
