-- Pos-validacao read-only da atividade 34 (MEDCHAP_USUEMP_20260925_01).
SELECT 'BACKUP_REGISTROS' METRICA, TO_CHAR(COUNT(*)) VALOR FROM BKP_RMD_MDCH_USUEMP01 WHERE ID_EXECUCAO='MEDCHAP_USUEMP_20260925_01'
UNION ALL SELECT 'BACKUP_CODEMP_ORIGINAL_4', TO_CHAR(COUNT(*)) FROM BKP_RMD_MDCH_USUEMP01 WHERE CODEMP=4
UNION ALL SELECT 'CBS_COM_CODEMP_2', TO_CHAR(COUNT(*)) FROM TSIUSU WHERE LOWER(TRIM(EMAIL)) LIKE '%.cbs@medchap.com.br' AND CODEMP=2
UNION ALL SELECT 'CBS_FORA_CODEMP_2', TO_CHAR(COUNT(*)) FROM TSIUSU WHERE LOWER(TRIM(EMAIL)) LIKE '%.cbs@medchap.com.br' AND NVL(CODEMP,-1)<>2
UNION ALL SELECT 'USUARIOS_CODEMP_4', TO_CHAR(COUNT(*)) FROM TSIUSU WHERE CODEMP=4 AND NVL(CODGRUPO,0)>0
UNION ALL SELECT 'SJP_COM_CODEMP_3', TO_CHAR(COUNT(*)) FROM TSIUSU WHERE LOWER(TRIM(EMAIL)) LIKE '%.sjp@medchap.com.br' AND CODEMP=3;
