-- Pos-validacao read-only da atividade 35 (MEDCHAP_SMTP_20260925_01). Nenhuma coluna secreta e selecionada.
SELECT 'BACKUP_REGISTROS' METRICA, TO_CHAR(COUNT(*)) VALOR FROM BKP_RMD_MDCH_SMTP01 WHERE ID_EXECUCAO_RMD='MEDCHAP_SMTP_20260925_01'
UNION ALL SELECT 'TSISMTP_TOTAL', TO_CHAR(COUNT(*)) FROM TSISMTP
UNION ALL SELECT 'TSISMTP_CONTA_TESTE_DEPLOY', TO_CHAR(COUNT(*)) FROM TSISMTP WHERE LOWER(TRIM(SERVIDOR))='email-smtp.us-east-1.amazonaws.com' OR LOWER(TRIM(REMETENTE))='noreply@sankhya.com.br'
UNION ALL SELECT 'MSDSMTPPROP_CONTA_TESTE_DEPLOY', TO_CHAR(COUNT(*)) FROM TSIPAR WHERE CHAVE='MSDSMTPPROP' AND (INSTR(LOWER(TEXTO),'email-smtp.us-east-1.amazonaws.com')>0 OR INSTR(LOWER(TEXTO),'noreply@sankhya.com.br')>0)
UNION ALL SELECT 'MSDSMTPPROP_SERVIDOR', REGEXP_SUBSTR(TEXTO,'[^'||CHR(59)||']+',1,1) FROM TSIPAR WHERE CHAVE='MSDSMTPPROP'
UNION ALL SELECT 'MSDSMTPPROP_REMETENTE', REGEXP_SUBSTR(TEXTO,'[^'||CHR(59)||']+',1,4) FROM TSIPAR WHERE CHAVE='MSDSMTPPROP';
