-- Rollback persistente do merge definitivo 29/30 do Instituto Moreira Salles.
-- Restaura primeiro os pais excluidos a partir do backup integral e depois
-- repoe cada referencia filha pelo valor anterior auditado por ROWID.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET LINESIZE 300
SET PAGESIZE 500
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

SPOOL "/Users/spadarojr/Documents/Trabalho/Sankhya/Deploy Agent/Scripts-Deploy/7 - QA2/Clientes/INSTITUTO MOREIRA SALLES/Logs/29_30_Rollback_20260914.log"

PROMPT === ROLLBACK CARD 29/30 - INSTITUTO MOREIRA SALLES ===

DECLARE
  v_owner VARCHAR2(128) := SYS_CONTEXT('USERENV','CURRENT_SCHEMA');
  v_id VARCHAR2(40) := 'RMD_2930_IMS_20260914154001';
  v_sql VARCHAR2(32767);
  v_cols VARCHAR2(32767);
  v_n NUMBER;
  v_restored NUMBER := 0;
  v_map VARCHAR2(128) := 'BKP_RMD_MRG_IMS_20260914';
  v_bkp_bai VARCHAR2(128) := 'BKP_RMD_MRG_IMS_20260914_BAI';
  v_bkp_end VARCHAR2(128) := 'BKP_RMD_MRG_IMS_20260914_END';
  v_dep VARCHAR2(128) := 'BKP_RMD_MRG_IMS_20260914_DEP';
  v_exc VARCHAR2(128) := 'BKP_RMD_MRG_IMS_20260914_EXC';
BEGIN
  EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM '||v_map||' WHERE ID_EXECUCAO=:1' INTO v_n USING v_id;
  IF v_n=0 THEN RAISE_APPLICATION_ERROR(-20410,'Mapa ausente para o ID_EXECUCAO'); END IF;

  EXECUTE IMMEDIATE 'SELECT LISTAGG(''"''||COLUMN_NAME||''"'', '','') WITHIN GROUP (ORDER BY COLUMN_ID) FROM ALL_TAB_COLUMNS WHERE OWNER=:1 AND TABLE_NAME=''TSIBAI''' INTO v_cols USING v_owner;
  v_sql := 'INSERT INTO TSIBAI('||v_cols||') SELECT '||v_cols||' FROM '||v_bkp_bai||' b WHERE b.ID_EXECUCAO=:1 AND NOT EXISTS (SELECT 1 FROM TSIBAI t WHERE t.CODBAI=b.CODBAI)';
  EXECUTE IMMEDIATE v_sql USING v_id;
  v_restored := v_restored + SQL%ROWCOUNT;

  EXECUTE IMMEDIATE 'SELECT LISTAGG(''"''||COLUMN_NAME||''"'', '','') WITHIN GROUP (ORDER BY COLUMN_ID) FROM ALL_TAB_COLUMNS WHERE OWNER=:1 AND TABLE_NAME=''TSIEND''' INTO v_cols USING v_owner;
  v_sql := 'INSERT INTO TSIEND('||v_cols||') SELECT '||v_cols||' FROM '||v_bkp_end||' b WHERE b.ID_EXECUCAO=:1 AND NOT EXISTS (SELECT 1 FROM TSIEND t WHERE t.CODEND=b.CODEND)';
  EXECUTE IMMEDIATE v_sql USING v_id;
  v_restored := v_restored + SQL%ROWCOUNT;

  FOR r IN (
    SELECT OWNER_NAME,TABLE_NAME,COLUMN_NAME,RID,OLD_VALUE
      FROM BKP_RMD_MRG_IMS_20260914_DEP
     WHERE ID_EXECUCAO=v_id
     ORDER BY DTLOG DESC
  ) LOOP
    v_sql := 'UPDATE '||r.OWNER_NAME||'.'||r.TABLE_NAME||
      ' SET '||r.COLUMN_NAME||'=:1 WHERE ROWID=CHARTOROWID(:2)';
    EXECUTE IMMEDIATE v_sql USING r.OLD_VALUE,r.RID;
    IF SQL%ROWCOUNT<>1 THEN
      RAISE_APPLICATION_ERROR(-20411,'ROWID nao localizado em '||r.TABLE_NAME||'.'||r.COLUMN_NAME||'|'||r.RID);
    END IF;
    v_restored := v_restored + 1;
  END LOOP;

  COMMIT;
  DBMS_OUTPUT.PUT_LINE('STATUS=ROLLBACK_CONCLUIDO; ID_EXECUCAO='||v_id||'; REGISTROS_RESTAURADOS='||v_restored);
EXCEPTION WHEN OTHERS THEN
  ROLLBACK;
  RAISE;
END;
/

SELECT 'MAPA' TIPO, COUNT(*) QTD FROM BKP_RMD_MRG_IMS_20260914 WHERE ID_EXECUCAO='RMD_2930_IMS_20260914154001'
UNION ALL
SELECT 'AUDITORIA_DEP', COUNT(*) FROM BKP_RMD_MRG_IMS_20260914_DEP WHERE ID_EXECUCAO='RMD_2930_IMS_20260914154001'
UNION ALL
SELECT 'EXCECOES', COUNT(*) FROM BKP_RMD_MRG_IMS_20260914_EXC WHERE ID_EXECUCAO='RMD_2930_IMS_20260914154001';

SPOOL OFF
