-- Reverte 09_Habilitar_ICMS_Gerencial pelo ID exibido na execucao.
SET DEFINE ON
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
ACCEPT P_ID_EXECUCAO CHAR PROMPT 'ID da execucao RMD_ICMG_: '
DECLARE v_b PLS_INTEGER; v_u PLS_INTEGER; BEGIN
 SELECT COUNT(*) INTO v_b FROM BKP_RMD_09_TGFPRO WHERE ID_EXECUCAO='&&P_ID_EXECUCAO';
 IF v_b=0 THEN RAISE_APPLICATION_ERROR(-20202,'Backup nao encontrado.'); END IF;
 MERGE INTO TGFPRO T USING (SELECT ROWID_ORIGINAL,VALOR_ANTES FROM BKP_RMD_09_TGFPRO WHERE ID_EXECUCAO='&&P_ID_EXECUCAO') B
 ON (T.ROWID=CHARTOROWID(B.ROWID_ORIGINAL))
 WHEN MATCHED THEN UPDATE SET T.ICMSGERENCIA=B.VALOR_ANTES;
 v_u:=SQL%ROWCOUNT;
 IF v_b<>v_u THEN RAISE_APPLICATION_ERROR(-20203,'Rollback divergente em 09_Habilitar_ICMS_Gerencial.'); END IF;
 COMMIT; DBMS_OUTPUT.PUT_LINE('REGISTROS_REVERTIDOS='||v_u);
EXCEPTION WHEN OTHERS THEN ROLLBACK; RAISE; END;
/
UNDEFINE P_ID_EXECUCAO

