-- Preflight/estado read-only do Card 09 FOCUSFINTAXPRD antes do mapa FOCUS_FDUP_20260923_01.
SELECT 'ESCOPO_DASHBOARD_NOTAS_SEM_FIN' AS METRICA, TO_CHAR(COUNT(*)) AS VALOR
  FROM TGFCAB C JOIN TGFTOP T ON T.CODTIPOPER=C.CODTIPOPER AND T.DHALTER=C.DHTIPOPER
 WHERE T.ATUALFIN<>0 AND C.TIPMOV<>'Z' AND NOT EXISTS (SELECT 1 FROM TGFFIN F WHERE F.NUNOTA=C.NUNOTA)
UNION ALL SELECT 'TABELAS_MAPA_EXISTENTES', TO_CHAR(COUNT(*)) FROM ALL_TABLES
 WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND TABLE_NAME IN ('BKP_RMD_FDUP_FCS_20260923','BKP_RMD_FDUP_FCS_20260923_PPG')
UNION ALL SELECT 'TABELAS_FDUP_ANTERIORES', TO_CHAR(COUNT(*)) FROM ALL_TABLES
 WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND TABLE_NAME LIKE 'BKP\_RMD\_FDUP%' ESCAPE '\'
UNION ALL SELECT 'LINHAS_TGFNUM_TGFFIN', TO_CHAR(COUNT(*)) FROM TGFNUM WHERE ARQUIVO='TGFFIN'
UNION ALL SELECT 'ULTCOD_TGFNUM_TGFFIN', TO_CHAR(MAX(ULTCOD)) FROM TGFNUM WHERE ARQUIVO='TGFFIN'
UNION ALL SELECT 'TOTAL_TGFFIN', TO_CHAR(COUNT(*)) FROM TGFFIN
UNION ALL SELECT 'TGFNFE_COM_XML', TO_CHAR(COUNT(*)) FROM TGFNFE WHERE XML IS NOT NULL;
