-- Preflight read-only FOCUSFINTAXPRD. Somente SELECT/WITH via oracle_direct.py query. Sem DML/DDL.
SELECT 'PRIVILEGIO' AS TIPO, PRIVILEGE AS NOME FROM SESSION_PRIVS
UNION ALL
SELECT 'ROLE', ROLE FROM SESSION_ROLES
 ORDER BY 1, 2
