-- Preflight read-only FOCUSFINTAXPRD. Somente SELECT/WITH via oracle_direct.py query. Sem DML/DDL.
SELECT U.USERNAME, U.DEFAULT_TABLESPACE, Q.TABLESPACE_NAME, Q.BYTES, Q.MAX_BYTES
  FROM USER_USERS U
  LEFT JOIN USER_TS_QUOTAS Q ON 1 = 1
