-- Preflight read-only FOCUSFINTAXPRD. Somente SELECT/WITH via oracle_direct.py query. Sem DML/DDL.
SELECT CODEMP,
       TRIM(NOMEFANTASIA) AS NOMEFANTASIA,
       TRIM(RAZAOSOCIAL) AS RAZAOSOCIAL,
       REGEXP_REPLACE(TO_CHAR(CGC), '[^0-9]', '') AS CNPJ,
       CASE
         WHEN UPPER(TRIM(RAZAOSOCIAL)) = 'FOCUSFINTAXPRD' THEN 'RAZAO_SOCIAL_EXATA'
         WHEN UPPER(REPLACE(RAZAOSOCIAL, ' ', '')) LIKE '%FOCUSFINTAX%'
           OR UPPER(REPLACE(NOMEFANTASIA, ' ', '')) LIKE '%FOCUSFINTAX%' THEN 'VARIACAO_FOCUS_FINTAX'
         WHEN UPPER(RAZAOSOCIAL) LIKE '%FINTAX%' OR UPPER(NOMEFANTASIA) LIKE '%FINTAX%'
           OR UPPER(RAZAOSOCIAL) LIKE '%FOCUS%' OR UPPER(NOMEFANTASIA) LIKE '%FOCUS%' THEN 'VARIACAO_TOKEN'
         ELSE 'SEM_TOKEN'
       END AS CLASSIFICACAO
  FROM TSIEMP
 ORDER BY CODEMP
