-- Preflight read-only FOCUSFINTAXPRD. Somente SELECT/WITH via oracle_direct.py query. Sem DML/DDL.
SELECT OWNER, OBJECT_NAME, OBJECT_TYPE, STATUS, CREATED, LAST_DDL_TIME
  FROM ALL_OBJECTS
 WHERE OWNER IN ('FRANCISCO_JUNIOR', 'SANKHYA')
   AND (OBJECT_NAME LIKE 'RMD\_%' ESCAPE '\' OR OBJECT_NAME LIKE 'BKP\_%' ESCAPE '\')
 ORDER BY CREATED, OWNER, OBJECT_NAME
