-- Preflight read-only FOCUSFINTAXPRD. Somente SELECT/WITH via oracle_direct.py query. Sem DML/DDL.
SELECT CODVOL,DESCRVOL,UPPER(DESCRVOL) DESCRVOL_DEPOIS
FROM TGFVOL
WHERE DESCRVOL<>UPPER(DESCRVOL)
ORDER BY CODVOL
