-- Preflight read-only FOCUSFINTAXPRD. Somente SELECT/WITH via oracle_direct.py query. Sem DML/DDL.
SELECT N.NOME OBJETO,N.TIPO_ESPERADO,
       NVL(O.OBJECT_TYPE,'AUSENTE') TIPO_ENCONTRADO,
       NVL(O.STATUS,'AUSENTE') STATUS
FROM (
 SELECT 'TGFCGM' NOME,'TABLE' TIPO_ESPERADO FROM DUAL UNION ALL SELECT 'TGFCMV','TABLE' FROM DUAL
 UNION ALL SELECT 'TTKINDAGT','TABLE' FROM DUAL UNION ALL SELECT 'TTKNOT','TABLE' FROM DUAL
 UNION ALL SELECT 'TTKEVT','TABLE' FROM DUAL UNION ALL SELECT 'TGFPAR','TABLE' FROM DUAL
 UNION ALL SELECT 'TGFPRO','TABLE' FROM DUAL UNION ALL SELECT 'TGFTIT','TABLE' FROM DUAL
 UNION ALL SELECT 'TSICID','TABLE' FROM DUAL UNION ALL SELECT 'TGFTPV','TABLE' FROM DUAL
 UNION ALL SELECT 'TSIBAI','TABLE' FROM DUAL UNION ALL SELECT 'TSIEND','TABLE' FROM DUAL
) N LEFT JOIN ALL_OBJECTS O
 ON O.OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND O.OBJECT_NAME=N.NOME AND O.OBJECT_TYPE=N.TIPO_ESPERADO
ORDER BY N.NOME
