-- Preflight read-only FOCUSFINTAXPRD. Somente SELECT/WITH via oracle_direct.py query. Sem DML/DDL.
SELECT 'TSIBAI_TOTAL' ITEM,COUNT(*) QTD FROM TSIBAI
UNION ALL
SELECT 'TSIBAI_GRUPOS_COLISAO',COUNT(*) FROM (
 SELECT REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEBAI),'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ','AAAAAEEEEIIIIOOOOOUUUUC')),' {2,}',' ') N
 FROM TSIBAI GROUP BY REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEBAI),'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ','AAAAAEEEEIIIIOOOOOUUUUC')),' {2,}',' ')
 HAVING COUNT(*)>1
)
