-- Preflight read-only FOCUSFINTAXPRD. Somente SELECT/WITH via oracle_direct.py query. Sem DML/DDL.
SELECT OBJECT_TYPE, OBJECT_NAME, STATUS, LAST_DDL_TIME
  FROM ALL_OBJECTS
 WHERE OWNER = SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND STATUS = 'INVALID'
 ORDER BY OBJECT_TYPE, OBJECT_NAME
