-- Preflight read-only FOCUSFINTAXPRD. Somente SELECT/WITH via oracle_direct.py query. Sem DML/DDL.
SELECT STATUS, COUNT(*) AS QTD
  FROM ALL_TRIGGERS
 WHERE OWNER = SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
 GROUP BY STATUS
 ORDER BY STATUS
