-- Preflight read-only FOCUSFINTAXPRD. Somente SELECT/WITH via oracle_direct.py query. Sem DML/DDL.
SELECT N.NOME AS OBJETO, N.TIPO_ESPERADO,
       NVL(O.OBJECT_TYPE, 'AUSENTE') AS TIPO_ENCONTRADO,
       NVL(O.STATUS, 'AUSENTE') AS STATUS
  FROM (
        SELECT 'TGFCAB' NOME, 'TABLE' TIPO_ESPERADO FROM DUAL UNION ALL SELECT 'TGFTOP', 'TABLE' FROM DUAL
        UNION ALL SELECT 'TGFFIN', 'TABLE' FROM DUAL UNION ALL SELECT 'TGFNFE', 'TABLE' FROM DUAL
        UNION ALL SELECT 'TGFPPG', 'TABLE' FROM DUAL UNION ALL SELECT 'TGFTPV', 'TABLE' FROM DUAL
        UNION ALL SELECT 'TGFTIT', 'TABLE' FROM DUAL UNION ALL SELECT 'TGFNUM', 'TABLE' FROM DUAL
        UNION ALL SELECT 'TSICTA', 'TABLE' FROM DUAL
        UNION ALL SELECT 'FNC_BUSCA_TAG_XML_GERAL', 'FUNCTION' FROM DUAL
       ) N
  LEFT JOIN ALL_OBJECTS O
    ON O.OWNER = SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
   AND O.OBJECT_NAME = N.NOME AND O.OBJECT_TYPE = N.TIPO_ESPERADO
 ORDER BY N.NOME
