-- Onboarding read-only MEDCHAP: colunas disponiveis para a comparacao (sem dados de negocio).
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE
  FROM ALL_TAB_COLUMNS
 WHERE OWNER = SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
   AND TABLE_NAME IN ('TSIEMP','TSICID','TSIUFS','TSIUSU','TSIGRU','TSICTA','TSIAGE','TSIBCO')
   AND COLUMN_NAME IN ('CODEMP','RAZAOSOCIAL','NOMEFANTASIA','CGC','INSCESTAD','CODCID','NOMECID','UF','CODUF','DESCRICAO',
                       'CODUSU','NOMEUSU','EMAIL','CODGRUPO','NOMEGRUPO','DTLIMACESSO','ATIVO',
                       'CODCTABCOINT','CODCTABCO','CODBCO','CODAGE','ATIVA','CLASSE','NOMEAGE','NOMEBCO')
 ORDER BY TABLE_NAME, COLUMN_NAME
