-- Onboarding read-only MEDCHAP. Somente SELECT via oracle_direct.py query. Sem DML/DDL.
SELECT E.CODEMP, TRIM(E.RAZAOSOCIAL) RAZAOSOCIAL, TRIM(E.NOMEFANTASIA) NOMEFANTASIA,
       REGEXP_REPLACE(TO_CHAR(E.CGC),'[^0-9]','') CNPJ, TRIM(E.INSCESTAD) IE, C.NOMECID, U.UF
  FROM TSIEMP E LEFT JOIN TSICID C ON C.CODCID=E.CODCID LEFT JOIN TSIUFS U ON U.CODUF=C.UF
 ORDER BY E.CODEMP
