-- Onboarding read-only MEDCHAP. Somente SELECT via oracle_direct.py query. Sem DML/DDL.
SELECT U.CODUSU, TRIM(U.NOMEUSU) NOMEUSU, LOWER(TRIM(U.EMAIL)) EMAIL, U.CODGRUPO, TRIM(G.NOMEGRUPO) NOMEGRUPO,
       U.CODEMP, TO_CHAR(U.DTLIMACESSO,'YYYY-MM-DD') DTLIMACESSO
  FROM TSIUSU U LEFT JOIN TSIGRU G ON G.CODGRUPO=U.CODGRUPO
 ORDER BY LOWER(TRIM(U.EMAIL)), U.CODUSU
