-- Onboarding read-only MEDCHAP. Somente SELECT via oracle_direct.py query. Sem DML/DDL.
-- Agencia/conta nunca saem em claro: somente SHA-256 dos digitos e os 2 ultimos digitos.
SELECT T.CODCTABCOINT, T.CODEMP, REGEXP_REPLACE(TO_CHAR(E.CGC),'[^0-9]','') CNPJ_EMP, T.CODBCO, TRIM(B.NOMEBCO) NOMEBCO,
       T.ATIVA, T.CLASSE,
       RAWTOHEX(STANDARD_HASH(NVL(REGEXP_REPLACE(T.CODAGE,'[^0-9]',''),'-'),'SHA256')) AG_HASH,
       RAWTOHEX(STANDARD_HASH(NVL(REGEXP_REPLACE(T.CODCTABCO,'[^0-9]',''),'-'),'SHA256')) CONTA_HASH,
       RAWTOHEX(STANDARD_HASH(NVL(SUBSTR(REGEXP_REPLACE(T.CODCTABCO,'[^0-9]',''),1,LENGTH(REGEXP_REPLACE(T.CODCTABCO,'[^0-9]',''))-1),'-'),'SHA256')) CONTA_SEM_DV_HASH,
       SUBSTR(REGEXP_REPLACE(T.CODCTABCO,'[^0-9]',''),-2) CONTA_FINAL2
  FROM TSICTA T LEFT JOIN TSIEMP E ON E.CODEMP=T.CODEMP LEFT JOIN TSIBCO B ON B.CODBCO=T.CODBCO
 ORDER BY T.CODEMP, T.CODCTABCOINT
