-- Onboarding read-only MEDCHAP: onde a base guarda SMTP (somente metadados de colunas, sem valores).
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE FROM ALL_TAB_COLUMNS
 WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND TABLE_NAME IN ('TSIEMP','TGFEMP','TSIPAR','TSISMTP','TGFSMTP','TSICSM')
   AND (COLUMN_NAME LIKE '%SMTP%' OR COLUMN_NAME LIKE '%EMAIL%' OR COLUMN_NAME IN ('CHAVE','TEXTO'))
 ORDER BY TABLE_NAME, COLUMN_NAME
