-- Onboarding read-only MEDCHAP: SMTP cadastrado por empresa (sem colunas de senha).
SELECT E.CODEMP, LOWER(TRIM(E.EMAIL)) EMAIL, TRIM(E.SERVIDORSMTP) SERVIDORSMTP, E.PORTASMTP, E.SEGURANCASMTP, E.TIPOSMTP,
       LOWER(TRIM(E.USUARIOSMTP)) USUARIOSMTP, G.CODSMTP, TRIM(G.SERVIDORSMTPXML) SERVIDORSMTPXML, G.PORTASMTPXML, G.TIPCONEXSMTPXML,
       (SELECT COUNT(*) FROM TSISMTP) QTD_TSISMTP
  FROM TSIEMP E LEFT JOIN TGFEMP G ON G.CODEMP=E.CODEMP
 ORDER BY E.CODEMP
