WITH objetos(nome, grupo) AS (
    SELECT 'BKP_RMD_FDUP_RIO_20260923_BASE', 'MAPA_BASE' FROM DUAL
    UNION ALL SELECT 'BKP_RMD_FDUP_RIO_20260923_PPG', 'MAPA_CLASSIFICACAO' FROM DUAL
    UNION ALL SELECT 'BKP_RMD_FDUP_RIO_20260923_INS', 'AUDITORIA_FINANCEIRA' FROM DUAL
    UNION ALL SELECT 'TGFNFE', 'FONTE_XML' FROM DUAL
    UNION ALL SELECT 'TGFFIN', 'FINANCEIROS' FROM DUAL
    UNION ALL SELECT 'TGFCAB', 'CABECALHOS' FROM DUAL
    UNION ALL SELECT 'TGFPPG', 'CONDICOES' FROM DUAL
    UNION ALL SELECT 'TGFNUM', 'NUMERACAO' FROM DUAL
)
SELECT O.GRUPO,
       O.NOME,
       CASE WHEN T.TABLE_NAME IS NULL THEN 'NAO_LOCALIZADO' ELSE 'LOCALIZADO' END AS ESTADO,
       NVL(T.NUM_ROWS,0) AS NUM_ROWS_ESTATISTICO
  FROM OBJETOS O
  LEFT JOIN ALL_TABLES T
    ON T.OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
   AND T.TABLE_NAME=O.NOME
 ORDER BY O.GRUPO
