SELECT U.CODUSU,
       LOWER(TRIM(U.EMAIL)) AS EMAIL,
       TRIM(U.NOMEUSU) AS NOMEUSU,
       U.CODEMP,
       TRIM(E.RAZAOSOCIAL) AS RAZAOSOCIAL_EMPRESA,
       U.CODGRUPO
  FROM TSIUSU U
  LEFT JOIN TSIEMP E ON E.CODEMP = U.CODEMP
 ORDER BY U.CODUSU
