WITH metricas(item, qtd, detalhe) AS (
    SELECT 'BASE_TOTAL', COUNT(*), 'RMD_FDUP_RIO_BASE_260923'
      FROM RMD_FDUP_RIO_BASE_260923
     WHERE ID_EXECUCAO='RMD_FDUP_RIO_260923_01'
    UNION ALL
    SELECT 'MAPA_CLASSIFICACAO_TOTAL', COUNT(*), 'RMD_FDUP_RIO_PPG_260923'
      FROM RMD_FDUP_RIO_PPG_260923
     WHERE ID_EXECUCAO='RMD_FDUP_RIO_260923_01'
    UNION ALL
    SELECT 'APTO_PARA_VALIDACAO_FINAL', COUNT(*), 'RMD_FDUP_RIO_PPG_260923'
      FROM RMD_FDUP_RIO_PPG_260923
     WHERE ID_EXECUCAO='RMD_FDUP_RIO_260923_01'
       AND STATUS_MAPA='APTO_PARA_VALIDACAO_FINAL'
    UNION ALL
    SELECT 'SEM_VDUP_XML', COUNT(*), 'RMD_FDUP_RIO_PPG_260923'
      FROM RMD_FDUP_RIO_PPG_260923
     WHERE ID_EXECUCAO='RMD_FDUP_RIO_260923_01'
       AND STATUS_MAPA='SEM_VDUP_XML'
    UNION ALL
    SELECT 'MULTIPLOS_XML', COUNT(*), 'RMD_FDUP_RIO_PPG_260923'
      FROM RMD_FDUP_RIO_PPG_260923
     WHERE ID_EXECUCAO='RMD_FDUP_RIO_260923_01'
       AND STATUS_MAPA='REVISAR_MULTIPLOS_XML'
    UNION ALL
    SELECT 'AUDITORIA_FINANCEIRA_EXISTE', COUNT(*), 'ALL_TABLES'
      FROM ALL_TABLES
     WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
       AND TABLE_NAME='RMD_FDUP_RIO_INS_260923'
    UNION ALL
    SELECT 'FINANCEIROS_ATUAIS', COUNT(*), 'TGFFIN'
      FROM TGFFIN
    UNION ALL
    SELECT 'XMLS_NFE_ATUAIS', COUNT(*), 'TGFNFE'
      FROM TGFNFE
)
SELECT item, qtd, detalhe
  FROM metricas
 ORDER BY item
