WITH metricas(item, qtd, detalhe) AS (
    SELECT 'MAPA_LINHAS', COUNT(*), 'RMD_RIO_2930_MAP'
      FROM RMD_RIO_2930_MAP
     WHERE ID_EXECUCAO='RMD_RIO_2930_20260923_01'
    UNION ALL
    SELECT 'BACKUP_BAIRROS_LINHAS', COUNT(*), 'RMD_RIO_2930_BAI'
      FROM RMD_RIO_2930_BAI
     WHERE ID_EXECUCAO='RMD_RIO_2930_20260923_01'
    UNION ALL
    SELECT 'BACKUP_ENDERECOS_LINHAS', COUNT(*), 'RMD_RIO_2930_END'
      FROM RMD_RIO_2930_END
     WHERE ID_EXECUCAO='RMD_RIO_2930_20260923_01'
    UNION ALL
    SELECT 'REFERENCIAS_AUDITADAS', COUNT(*), 'RMD_RIO_2930_DEP'
      FROM RMD_RIO_2930_DEP
     WHERE ID_EXECUCAO='RMD_RIO_2930_20260923_01'
    UNION ALL
    SELECT 'EXCECOES', COUNT(*), 'RMD_RIO_2930_EXC'
      FROM RMD_RIO_2930_EXC
     WHERE ID_EXECUCAO='RMD_RIO_2930_20260923_01'
    UNION ALL
    SELECT 'BAIRROS_OBSOLETOS_PRESENTES', COUNT(*), 'TSIBAI'
      FROM TSIBAI T
      JOIN RMD_RIO_2930_MAP M ON M.ID_EXECUCAO='RMD_RIO_2930_20260923_01'
       AND M.TIPO='BAI' AND M.COD_OBSOLETO=T.CODBAI
    UNION ALL
    SELECT 'ENDERECOS_OBSOLETOS_PRESENTES', COUNT(*), 'TSIEND'
      FROM TSIEND T
      JOIN RMD_RIO_2930_MAP M ON M.ID_EXECUCAO='RMD_RIO_2930_20260923_01'
       AND M.TIPO='END' AND M.COD_OBSOLETO=T.CODEND
    UNION ALL
    SELECT 'BAIRROS_ATUAIS', COUNT(*), 'TSIBAI'
      FROM TSIBAI
    UNION ALL
    SELECT 'ENDERECOS_ATUAIS', COUNT(*), 'TSIEND'
      FROM TSIEND
    UNION ALL
    SELECT 'BAIRROS_DUPLICADOS_NORMALIZADOS', COUNT(*), 'TSIBAI'
      FROM (
        SELECT REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEBAI),'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇáàâãäéèêëíìîïóòôõöúùûüçÃãÕõÂâÊêÎîÔôÛû','AAAAAEEEEIIIIOOOOOUUUUCAAAAAEEEEIIIIOOOOOUUUUCAAAOOAAEIIOOUU')),' {2,}',' ') NORM
          FROM TSIBAI
         GROUP BY REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEBAI),'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇáàâãäéèêëíìîïóòôõöúùûüçÃãÕõÂâÊêÎîÔôÛû','AAAAAEEEEIIIIOOOOOUUUUCAAAAAEEEEIIIIOOOOOUUUUCAAAOOAAEIIOOUU')),' {2,}',' ')
        HAVING COUNT(*)>1
      )
    UNION ALL
    SELECT 'ENDERECOS_DUPLICADOS_NORMALIZADOS', COUNT(*), 'TSIEND'
      FROM (
        SELECT TIPO,NORM
          FROM (
            SELECT TIPO,REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEEND),'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇáàâãäéèêëíìîïóòôõöúùûüçÃãÕõÂâÊêÎîÔôÛû','AAAAAEEEEIIIIOOOOOUUUUCAAAAAEEEEIIIIOOOOOUUUUCAAAOOAAEIIOOUU')),' {2,}',' ') NORM
              FROM TSIEND
          )
         GROUP BY TIPO,NORM
        HAVING COUNT(*)>1
      )
)
SELECT item, qtd, detalhe
  FROM metricas
 ORDER BY item
