WITH metricas(item, qtd, detalhe) AS (
    SELECT 'IDENTIDADE', 1,
           SYS_CONTEXT('USERENV','SESSION_USER')||'|'||
           SYS_CONTEXT('USERENV','CURRENT_SCHEMA')||'|'||
           SYS_CONTEXT('USERENV','SERVICE_NAME')||'|'||
           SYS_CONTEXT('USERENV','DB_NAME')
      FROM DUAL
    UNION ALL
    SELECT 'OBJETOS_CONTROLE_NAO_RETORNADOS', COUNT(*), 'RMD_CONTROLE_OBJETOS'
      FROM RMD_CONTROLE_OBJETOS
     WHERE STATUS_ANTES='ENABLED'
       AND NVL(STATUS_DEPOIS,'PENDENTE')<>'ENABLED'
    UNION ALL
    SELECT 'OBJETOS_INVALIDOS', COUNT(*), 'ALL_OBJECTS_CURRENT_SCHEMA'
      FROM ALL_OBJECTS
     WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
       AND STATUS='INVALID'
    UNION ALL
    SELECT 'MAPA_UNIDADES_LINHAS', COUNT(*), 'RMD_MAP_UNIDADES'
      FROM RMD_MAP_UNIDADES
    UNION ALL
    SELECT 'BAIRROS_ATUAIS', COUNT(*), 'TSIBAI'
      FROM TSIBAI
    UNION ALL
    SELECT 'ENDERECOS_ATUAIS', COUNT(*), 'TSIEND'
      FROM TSIEND
    UNION ALL
    SELECT 'BACKUP_BAIRROS_LINHAS', COUNT(*), 'BKP_RMD_PAD_TSIBAI'
      FROM BKP_RMD_PAD_TSIBAI
    UNION ALL
    SELECT 'BACKUP_ENDERECOS_LINHAS', COUNT(*), 'BKP_RMD_PAD_TSIEND'
      FROM BKP_RMD_PAD_TSIEND
    UNION ALL
    SELECT 'BACKUP_PARCEIROS_LINHAS', COUNT(*), 'BKP_RMD_PAD_TGFPAR'
      FROM BKP_RMD_PAD_TGFPAR
    UNION ALL
    SELECT 'BACKUP_PRODUTOS_LINHAS', COUNT(*), 'BKP_RMD_PAD_TGFPRO'
      FROM BKP_RMD_PAD_TGFPRO
    UNION ALL
    SELECT 'BACKUP_TITULOS_LINHAS', COUNT(*), 'BKP_RMD_PAD_TGFTIT'
      FROM BKP_RMD_PAD_TGFTIT
    UNION ALL
    SELECT 'BACKUP_CIDADES_LINHAS', COUNT(*), 'BKP_RMD_PAD_TSICID'
      FROM BKP_RMD_PAD_TSICID
    UNION ALL
    SELECT 'BACKUP_TIPOS_VENDA_LINHAS', COUNT(*), 'BKP_RMD_PAD_TGFTPV'
      FROM BKP_RMD_PAD_TGFTPV
)
SELECT item, qtd, detalhe
  FROM metricas
 ORDER BY item
