/* Preflight consolidado somente leitura da base RIOSLTDAPRD. */
WITH objetos_requeridos (nome) AS (
    SELECT 'TGFCGM' FROM DUAL UNION ALL SELECT 'TGFCMV' FROM DUAL
    UNION ALL SELECT 'TTKINDAGT' FROM DUAL UNION ALL SELECT 'TTKNOT' FROM DUAL
    UNION ALL SELECT 'TTKEVT' FROM DUAL UNION ALL SELECT 'TGFPAR' FROM DUAL
    UNION ALL SELECT 'TGFPRO' FROM DUAL UNION ALL SELECT 'TGFTIT' FROM DUAL
    UNION ALL SELECT 'TSICID' FROM DUAL UNION ALL SELECT 'TGFTPV' FROM DUAL
    UNION ALL SELECT 'TSIBAI' FROM DUAL UNION ALL SELECT 'TSIEND' FROM DUAL
    UNION ALL SELECT 'TGFNFE' FROM DUAL UNION ALL SELECT 'TGFFIN' FROM DUAL
    UNION ALL SELECT 'TGFPPG' FROM DUAL UNION ALL SELECT 'TGFNUM' FROM DUAL
    UNION ALL SELECT 'TSICTA' FROM DUAL UNION ALL SELECT 'TGFCAB' FROM DUAL
    UNION ALL SELECT 'TGFVOL' FROM DUAL UNION ALL SELECT 'TSIEMP' FROM DUAL
), metricas (item, qtd, detalhe) AS (
    SELECT 'IDENTIDADE', CAST(NULL AS NUMBER),
           'SESSION_USER='||SYS_CONTEXT('USERENV','SESSION_USER')||
           '|CURRENT_SCHEMA='||SYS_CONTEXT('USERENV','CURRENT_SCHEMA')||
           '|SERVICE_NAME='||SYS_CONTEXT('USERENV','SERVICE_NAME')||
           '|DB_NAME='||SYS_CONTEXT('USERENV','DB_NAME')
      FROM DUAL
    UNION ALL
    SELECT 'EMPRESAS_TSIEMP', COUNT(*),
           LISTAGG(TO_CHAR(CODEMP)||':'||TRIM(RAZAOSOCIAL),' | ')
             WITHIN GROUP (ORDER BY CODEMP)
      FROM TSIEMP
    UNION ALL
    SELECT 'OBJETOS_REQUERIDOS_AUSENTES', COUNT(*),
           LISTAGG(NOME,' | ') WITHIN GROUP (ORDER BY NOME)
      FROM objetos_requeridos R
     WHERE NOT EXISTS (
           SELECT 1 FROM ALL_OBJECTS O
            WHERE O.OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
              AND O.OBJECT_NAME=R.NOME
              AND O.OBJECT_TYPE='TABLE')
    UNION ALL
    SELECT 'OBJETOS_INVALIDOS', COUNT(*), NULL
      FROM ALL_OBJECTS
     WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
       AND STATUS='INVALID'
    UNION ALL
    SELECT 'ALTER_ANY_PROCEDURE', COUNT(*), NULL
      FROM SESSION_PRIVS WHERE PRIVILEGE='A'||'LTER ANY PROCEDURE'
    UNION ALL
    SELECT 'USER_TS_QUOTAS_LINHAS', COUNT(*),
           LISTAGG(TABLESPACE_NAME,' | ') WITHIN GROUP (ORDER BY TABLESPACE_NAME)
      FROM USER_TS_QUOTAS
    UNION ALL
    SELECT 'TGFVOL_TOTAL', COUNT(*), NULL FROM TGFVOL
    UNION ALL
    SELECT 'TGFVOL_DESCRICAO_MINUSCULA', COUNT(*), NULL
      FROM TGFVOL WHERE DESCRVOL<>UPPER(DESCRVOL)
    UNION ALL
    SELECT 'TGFCGM_ORIGEM_EMP1_1900_1', COUNT(*), NULL
      FROM TGFCGM WHERE CODEMP=1 AND ANO=1900 AND MES=1
    UNION ALL
    SELECT 'TGFCMV_CODCONFIG_1', COUNT(*), NULL FROM TGFCMV WHERE CODCONFIG=1
    UNION ALL
    SELECT 'TGFCGM_DESTINOS', COUNT(*), NULL FROM TGFCGM WHERE CODEMP<>1
    UNION ALL
    SELECT 'TGFPAR_TOTAL', COUNT(*), NULL FROM TGFPAR
    UNION ALL
    SELECT 'TGFPRO_TOTAL', COUNT(*), NULL FROM TGFPRO
    UNION ALL
    SELECT 'TGFTIT_TOTAL', COUNT(*), NULL FROM TGFTIT
    UNION ALL
    SELECT 'TSICID_TOTAL', COUNT(*), NULL FROM TSICID
    UNION ALL
    SELECT 'TGFTPV_TOTAL', COUNT(*), NULL FROM TGFTPV
    UNION ALL
    SELECT 'TSIBAI_TOTAL', COUNT(*), NULL FROM TSIBAI
    UNION ALL
    SELECT 'TSIEND_TOTAL', COUNT(*), NULL FROM TSIEND
)
SELECT item, qtd, detalhe
  FROM metricas
 ORDER BY item
