WITH PROD_HASH AS (
    SELECT CODPROD,
           ORA_HASH(UPPER(REGEXP_REPLACE(DESCRPROD, '[^A-Z0-9 ]', '')), 999999) HASH_DESCR,
           UPPER(REGEXP_REPLACE(DESCRPROD, '[^A-Z0-9 ]', '')) DESCRNORM
      FROM TGFPRO
), COMPLEMENTOS AS (
    SELECT 'Produtos vendidos sem tabela de preço' INDICADOR,
           COUNT(DISTINCT P.CODPROD) QTD
      FROM TGFITE I
      JOIN TGFCAB C ON C.NUNOTA = I.NUNOTA
      JOIN TGFPRO P ON P.CODPROD = I.CODPROD
     WHERE C.TIPMOV = 'V'
       AND NOT EXISTS (SELECT 1 FROM TGFEXC E WHERE E.CODPROD = P.CODPROD)
    UNION ALL
    SELECT 'Pares de produtos com descrições similares' INDICADOR,
           COUNT(*) QTD
      FROM PROD_HASH A
      JOIN PROD_HASH B ON A.HASH_DESCR = B.HASH_DESCR AND A.CODPROD < B.CODPROD
     WHERE UTL_MATCH.JARO_WINKLER_SIMILARITY(A.DESCRNORM, B.DESCRNORM) > 85
    UNION ALL
    SELECT 'CNPJs matriz com filiais cadastradas' INDICADOR,
           COUNT(*) QTD
      FROM TGFPAR P
     WHERE SUBSTR(P.CGC_CPF, 9, 4) = '0001'
       AND LENGTH(P.CGC_CPF) = 14
       AND SUBSTR(P.CGC_CPF, 1, 8) <> '00000000'
       AND EXISTS (
           SELECT 1
             FROM TGFPAR F
            WHERE SUBSTR(F.CGC_CPF, 1, 8) = SUBSTR(P.CGC_CPF, 1, 8)
              AND SUBSTR(F.CGC_CPF, 9, 4) <> '0001'
              AND LENGTH(F.CGC_CPF) = 14
       )
    UNION ALL
    SELECT 'Produtos comprados sem registro de saída' INDICADOR,
           COUNT(DISTINCT I.CODPROD) QTD
      FROM TGFITE I
      JOIN TGFCAB C ON C.NUNOTA = I.NUNOTA
     WHERE C.TIPMOV = 'C'
       AND NOT EXISTS (
           SELECT 1
             FROM TGFITE IC
             JOIN TGFCAB CC ON CC.NUNOTA = IC.NUNOTA AND CC.TIPMOV = 'V'
            WHERE IC.CODPROD = I.CODPROD
       )
)
SELECT INDICADOR, QTD
  FROM COMPLEMENTOS
 ORDER BY INDICADOR
