SELECT 'COLUMN' TIPO,
       TABLE_NAME OBJETO,
       COLUMN_NAME ATRIBUTO,
       DATA_TYPE DETALHE,
       TO_CHAR(DATA_LENGTH) TAMANHO
  FROM ALL_TAB_COLUMNS
 WHERE OWNER = SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
   AND TABLE_NAME IN ('TSIPAR','TSISMTP','TSICTA','TSIEMP')
UNION ALL
SELECT 'NLS' TIPO,
       PARAMETER OBJETO,
       VALUE ATRIBUTO,
       CAST(NULL AS VARCHAR2(30)) DETALHE,
       CAST(NULL AS VARCHAR2(30)) TAMANHO
  FROM NLS_DATABASE_PARAMETERS
 WHERE PARAMETER = 'NLS_CHARACTERSET'
ORDER BY 1, 2, 3
