WITH CONTA AS (
    SELECT CODEMP,
           CODBCO,
           ATIVA,
           REGEXP_REPLACE(NVL(CODAGE, ' '), '[^0-9]', '') AGENCIA_DIGITOS,
           REGEXP_REPLACE(NVL(CODCTABCO, ' '), '[^0-9]', '') CONTA_DIGITOS,
           REGEXP_REPLACE(REPLACE(UPPER(NVL(CODAGE, ' ')), 'X', '0'), '[^0-9]', '') AGENCIA_X_ZERO
      FROM TSICTA
     WHERE CODEMP = 1
       AND CODAGE IS NOT NULL
       AND CODCTABCO IS NOT NULL
)
SELECT CODEMP,
       CODBCO,
       ATIVA,
       RAWTOHEX(STANDARD_HASH(
           'A' || LENGTH(AGENCIA_DIGITOS) || ':' || AGENCIA_DIGITOS ||
           '|C' || LENGTH(CONTA_DIGITOS) || ':' || CONTA_DIGITOS,
           'SHA256')) HASH_AGENCIA_CONTA,
       RAWTOHEX(STANDARD_HASH(
           'A' || LENGTH(AGENCIA_X_ZERO) || ':' || AGENCIA_X_ZERO ||
           '|C' || LENGTH(CONTA_DIGITOS) || ':' || CONTA_DIGITOS,
           'SHA256')) HASH_AGENCIA_X_ZERO_CONTA
  FROM CONTA
 ORDER BY CODBCO, ATIVA
