SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH
  FROM ALL_TAB_COLUMNS
 WHERE OWNER = SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
   AND TABLE_NAME = 'TSICTA'
   AND (COLUMN_NAME LIKE '%AG%' OR COLUMN_NAME LIKE '%CTA%'
        OR COLUMN_NAME LIKE '%DIG%' OR COLUMN_NAME LIKE '%DV%'
        OR COLUMN_NAME LIKE '%BCO%')
 ORDER BY COLUMN_ID
