SELECT
    SYS_CONTEXT('USERENV','SESSION_USER') AS SESSION_USER,
    SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AS CURRENT_SCHEMA,
    SYS_CONTEXT('USERENV','SERVICE_NAME') AS SERVICE_NAME,
    SYS_CONTEXT('USERENV','DB_NAME') AS DB_NAME,
    (SELECT BANNER FROM V$VERSION WHERE ROWNUM = 1) AS ORACLE_VERSION
FROM DUAL
