SELECT 'PRIVILEGIO' AS TIPO,
       PRIVILEGE AS ITEM,
       CAST(NULL AS NUMBER) AS BYTES,
       CAST(NULL AS NUMBER) AS MAX_BYTES
  FROM SESSION_PRIVS
UNION ALL
SELECT 'QUOTA' AS TIPO,
       TABLESPACE_NAME AS ITEM,
       BYTES,
       MAX_BYTES
  FROM USER_TS_QUOTAS
ORDER BY TIPO, ITEM
