SELECT OWNER,
       OBJECT_TYPE,
       OBJECT_NAME,
       STATUS,
       LAST_DDL_TIME
  FROM ALL_OBJECTS
 WHERE STATUS <> 'VALID'
   AND OWNER IN ('SANKHYA', 'FRANCISCO_JUNIOR')
 ORDER BY OWNER, OBJECT_TYPE, OBJECT_NAME
