SELECT OWNER,
       OBJECT_TYPE,
       OBJECT_NAME,
       STATUS,
       LAST_DDL_TIME
  FROM ALL_OBJECTS
 WHERE OWNER IN ('SANKHYA', 'FRANCISCO_JUNIOR')
   AND REGEXP_LIKE(OBJECT_NAME, '^(RMD_|BKP_RMD_)')
 ORDER BY OWNER, OBJECT_TYPE, OBJECT_NAME
