SELECT 'FINANCEIROS_SEM_NOTA' AS METRICA, COUNT(*) AS QUANTIDADE
  FROM TGFFIN F
 WHERE F.NUNOTA IS NULL
UNION ALL
SELECT 'ITENS_SEM_CABECALHO' AS METRICA, COUNT(*) AS QUANTIDADE
  FROM TGFITE I
 WHERE NOT EXISTS (SELECT 1 FROM TGFCAB C WHERE C.NUNOTA = I.NUNOTA)
UNION ALL
SELECT 'CABECALHOS_SEM_ITENS' AS METRICA, COUNT(*) AS QUANTIDADE
  FROM TGFCAB C
 WHERE NOT EXISTS (SELECT 1 FROM TGFITE I WHERE I.NUNOTA = C.NUNOTA)
UNION ALL
SELECT 'CODIGOS_FISCAIS_CIDADES_DUPLICADOS' AS METRICA, COUNT(*) AS QUANTIDADE
  FROM (
       SELECT CODCID, CODMUNFIS, COUNT(*) AS QTD
         FROM TSICID
        GROUP BY CODCID, CODMUNFIS
       HAVING COUNT(*) > 1
  ) D
