SELECT 'EMPRESAS_TSIEMP' AS METRICA, COUNT(*) AS QUANTIDADE FROM TSIEMP
UNION ALL
SELECT 'USUARIOS_TSIUSU_TOTAL', COUNT(*) FROM TSIUSU
UNION ALL
SELECT 'USUARIOS_TSIUSU_COM_GRUPO', COUNT(*) FROM TSIUSU WHERE CODGRUPO>0
UNION ALL
SELECT 'USUARIOS_MODELO_SEM_GRUPO', COUNT(*) FROM TSIUSU WHERE NVL(CODGRUPO,0)<=0
UNION ALL
SELECT 'CONTAS_TSICTA', COUNT(*) FROM TSICTA
UNION ALL
SELECT 'VENDEDORES_TGFVEN', COUNT(*) FROM TGFVEN
UNION ALL
SELECT 'GRUPOS_TGFGRU', COUNT(*) FROM TGFGRU
UNION ALL
SELECT 'CENTROS_TSICUS', COUNT(*) FROM TSICUS
UNION ALL
SELECT 'NATUREZAS_TGFNAT', COUNT(*) FROM TGFNAT
UNION ALL
SELECT 'LOCAIS_TGFLOC', COUNT(*) FROM TGFLOC
UNION ALL
SELECT 'SMTP_GLOBAL_METADADO', COUNT(*) FROM TSIPAR WHERE CHAVE='MSDSMTPPROP'
UNION ALL
SELECT 'SMTP_EMPRESAS_CONFIGURADO', COUNT(*) FROM TSIEMP WHERE SERVIDORSMTP IS NOT NULL
