SELECT O.OWNER,
       O.OBJECT_TYPE,
       O.OBJECT_NAME,
       O.STATUS,
       COUNT(E.LINE) AS ERROS_COMPILACAO
  FROM ALL_OBJECTS O
  LEFT JOIN ALL_ERRORS E
    ON E.OWNER=O.OWNER
   AND E.NAME=O.OBJECT_NAME
   AND E.TYPE=O.OBJECT_TYPE
 WHERE O.STATUS<>'VALID'
   AND O.OWNER='SANKHYA'
 GROUP BY O.OWNER,O.OBJECT_TYPE,O.OBJECT_NAME,O.STATUS
 ORDER BY O.OBJECT_TYPE,O.OBJECT_NAME
