SELECT 'RMD_CONTROLE_OBJETOS_ROWS' AS METRICA, COUNT(*) AS QUANTIDADE
  FROM RMD_CONTROLE_OBJETOS
 WHERE ID_MASTER='RMD_RUN_20260923100203833'
UNION ALL
SELECT 'BKP_RMD_01_TSIPAR_ROWS_ID', COUNT(*)
  FROM BKP_RMD_01_TSIPAR
 WHERE ID_EXECUCAO='RMD_PORT_20260923100205325'
UNION ALL
SELECT 'BKP_RMD_02_TGFEMP_ROWS', COUNT(*)
  FROM BKP_RMD_02_TGFEMP
UNION ALL
SELECT 'TGFEMP_ROWS', COUNT(*)
  FROM TGFEMP
UNION ALL
SELECT 'TSIPAR_PORTAL_KEYS_WITH_VALUE', COUNT(*)
  FROM TSIPAR
 WHERE CHAVE IN ('MAXDIASPORTAIS','MAXDIASPORTVEND','MAXDIASPORTCOMP','MAXDIASMOVFIN')
   AND INTEIRO IS NOT NULL
UNION ALL
SELECT 'TSIPAR_PORTAL_KEYS_TOTAL', COUNT(*)
  FROM TSIPAR
 WHERE CHAVE IN ('MAXDIASPORTAIS','MAXDIASPORTVEND','MAXDIASPORTCOMP','MAXDIASMOVFIN')
