-- Pos-validacao read-only da retomada da atividade 03.
SELECT 'BKP_RMD_02_TGFEMP' AS OBJETO,
       COUNT(*) AS QTD_REGISTROS,
       COUNT(DISTINCT ID_EXECUCAO) AS QTD_EXECUCOES,
       MIN(ID_EXECUCAO) AS PRIMEIRO_ID,
       MAX(ID_EXECUCAO) AS ULTIMO_ID
  FROM SANKHYA.BKP_RMD_02_TGFEMP
 WHERE ID_EXECUCAO LIKE 'RMD_DANF_%'
UNION ALL
SELECT 'TGFEMP_FORA_CODEMP_1',
       COUNT(*),
       CAST(NULL AS NUMBER),
       CAST(NULL AS VARCHAR2(30)),
       CAST(NULL AS VARCHAR2(30))
  FROM SANKHYA.TGFEMP
 WHERE CODEMP<>1;
