-- Contagens read-only dos backups criados durante a tentativa 04-31.
SELECT 'BKP_RMD_03_TGFTOP' AS OBJETO, COUNT(*) AS QTD, COUNT(DISTINCT ID_EXECUCAO) AS EXECUCOES, MIN(ID_EXECUCAO) AS PRIMEIRO_ID, MAX(ID_EXECUCAO) AS ULTIMO_ID FROM SANKHYA.BKP_RMD_03_TGFTOP
UNION ALL
SELECT 'BKP_RMD_04_TGFPRO', COUNT(*), COUNT(DISTINCT ID_EXECUCAO), MIN(ID_EXECUCAO), MAX(ID_EXECUCAO) FROM SANKHYA.BKP_RMD_04_TGFPRO
UNION ALL
SELECT 'BKP_RMD_05_TGFTPV', COUNT(*), COUNT(DISTINCT ID_EXECUCAO), MIN(ID_EXECUCAO), MAX(ID_EXECUCAO) FROM SANKHYA.BKP_RMD_05_TGFTPV
UNION ALL
SELECT 'BKP_RMD_06_TGFCAB', COUNT(*), COUNT(DISTINCT ID_EXECUCAO), MIN(ID_EXECUCAO), MAX(ID_EXECUCAO) FROM SANKHYA.BKP_RMD_06_TGFCAB
UNION ALL
SELECT 'BKP_RMD_07_TGFCAB', COUNT(*), COUNT(DISTINCT ID_EXECUCAO), MIN(ID_EXECUCAO), MAX(ID_EXECUCAO) FROM SANKHYA.BKP_RMD_07_TGFCAB
UNION ALL
SELECT 'BKP_RMD_08_TGFITE', COUNT(*), COUNT(DISTINCT ID_EXECUCAO), MIN(ID_EXECUCAO), MAX(ID_EXECUCAO) FROM SANKHYA.BKP_RMD_08_TGFITE;
