-- Controle read-only de objetos persistido pelo lote parcial.
SELECT ID_MASTER,
       ID_EXECUCAO,
       OBJECT_TYPE,
       OBJECT_NAME,
       STATUS_ANTES,
       STATUS_DEPOIS,
       DH_REGISTRO,
       DH_REABILITACAO
  FROM SANKHYA.RMD_CONTROLE_OBJETOS
 WHERE ID_MASTER='RMD_RUN_20260923100203833'
 ORDER BY DH_REGISTRO, ID_EXECUCAO, OBJECT_NAME;
