-- Saldos funcionais read-only das atividades que avancaram na tentativa parcial.
SELECT 'ATIVIDADE_04_TOP' AS ITEM,
       (SELECT COUNT(*) FROM SANKHYA.TGFTOP WHERE TIPMOV='D' AND NVL(PRECIFICA,'?')<>'N') AS SALDO,
       (SELECT COUNT(*) FROM SANKHYA.BKP_RMD_03_TGFTOP) AS BACKUP
  FROM DUAL
UNION ALL
SELECT 'ATIVIDADE_05_GIRO_PRODUTOS',
       (SELECT COUNT(*) FROM SANKHYA.TGFPRO WHERE USOPROD IN ('V','R') AND NVL(CALCULOGIRO,'?')<>'G'),
       (SELECT COUNT(*) FROM SANKHYA.BKP_RMD_04_TGFPRO)
  FROM DUAL
UNION ALL
SELECT 'ATIVIDADE_06_PARCELAS',
       (SELECT COUNT(*) FROM SANKHYA.TGFTPV WHERE NVL(NROPARCELAS,-1)<>0),
       (SELECT COUNT(*) FROM SANKHYA.BKP_RMD_05_TGFTPV)
  FROM DUAL
UNION ALL
SELECT 'ATIVIDADE_07_DATA_MOVIMENTO',
       (SELECT COUNT(*) FROM SANKHYA.TGFCAB WHERE DTMOV IS NULL AND TIPMOV<>'Z'),
       (SELECT COUNT(*) FROM SANKHYA.BKP_RMD_06_TGFCAB)
  FROM DUAL
UNION ALL
SELECT 'ATIVIDADE_08_PROTOCOLOS',
       (SELECT COUNT(*) FROM SANKHYA.TGFCAB C WHERE EXISTS (SELECT 1 FROM SANKHYA.TTKNOT N WHERE N.NUNOTA=C.NUNOTA)
          AND ((C.NUMPROTOC IS NULL AND EXISTS (SELECT 1 FROM SANKHYA.TGFTOP T WHERE T.CODTIPOPER=C.CODTIPOPER AND T.DHALTER=C.DHTIPOPER AND T.CODMODDOC=55))
            OR (C.NUMPROTOCCTE IS NULL AND EXISTS (SELECT 1 FROM SANKHYA.TGFTOP T WHERE T.CODTIPOPER=C.CODTIPOPER AND T.DHALTER=C.DHTIPOPER AND T.CODMODDOC=57)))),
       (SELECT COUNT(*) FROM SANKHYA.BKP_RMD_07_TGFCAB)
  FROM DUAL
UNION ALL
SELECT 'ATIVIDADE_09_ITENS',
       (SELECT COUNT(*) FROM SANKHYA.TGFITE I WHERE NVL(I.STATUSNOTA,'?')<>'L' AND EXISTS (SELECT 1 FROM SANKHYA.TTKNOT N WHERE N.NUNOTA=I.NUNOTA)),
       (SELECT COUNT(*) FROM SANKHYA.BKP_RMD_08_TGFITE)
  FROM DUAL;
