-- Diagnostico read-only da atividade 12 apos ORA-01031.
SELECT 'BKP_RMD_09_TGFPRO' AS OBJETO, COUNT(*) AS QTD, COUNT(DISTINCT ID_EXECUCAO) AS EXECUCOES FROM SANKHYA.BKP_RMD_09_TGFPRO
UNION ALL
SELECT 'BKP_RMD_10_TGFPRO', COUNT(*), COUNT(DISTINCT ID_EXECUCAO) FROM SANKHYA.BKP_RMD_10_TGFPRO
UNION ALL
SELECT 'BKP_RMD_11_TGFEMP', COUNT(*), COUNT(DISTINCT ID_EXECUCAO) FROM SANKHYA.BKP_RMD_11_TGFEMP
UNION ALL
SELECT 'AD_SEGMENTACAOEMPRESAS', COUNT(*), CAST(NULL AS NUMBER) FROM SANKHYA.AD_SEGMENTACAOEMPRESAS;
