-- Pos-validacao consolidada read-only das atividades executadas.
SELECT 'CONTROLES_PENDENTES' AS METRICA,
       COUNT(*) AS QUANTIDADE
  FROM SANKHYA.RMD_CONTROLE_OBJETOS
 WHERE ID_MASTER='RMD_RUN_20260923100203833'
   AND STATUS_ANTES='ENABLED'
   AND NVL(STATUS_DEPOIS,'PENDENTE')<>'ENABLED'
UNION ALL
SELECT 'OBJETOS_INVALIDOS_FUNCTION_SANKHYA', COUNT(*)
  FROM ALL_OBJECTS
 WHERE OWNER='SANKHYA' AND OBJECT_TYPE='FUNCTION' AND STATUS<>'VALID'
UNION ALL
SELECT 'PRIVILEGIO_ALTER_ANY_PROCEDURE', COUNT(*)
  FROM SESSION_PRIVS
 WHERE PRIVILEGE=CHR(65)||CHR(76)||CHR(84)||CHR(69)||CHR(82)||' ANY PROCEDURE'
UNION ALL
SELECT 'ATIVIDADE_10_ICMS_SALDO', COUNT(*)
  FROM SANKHYA.TGFPRO
 WHERE USOPROD IN ('V','R') AND NVL(ICMSGERENCIA,'?')<>'S'
UNION ALL
SELECT 'ATIVIDADE_11_RUPTURA_SALDO', COUNT(*)
  FROM SANKHYA.TGFPRO
 WHERE USOPROD IN ('V','R') AND NVL(CALRUPTURAESTOQUE,'N')<>'S'
UNION ALL
SELECT 'ATIVIDADE_12_SEGMENTACAO_TOTAL', COUNT(*)
  FROM SANKHYA.AD_SEGMENTACAOEMPRESAS
UNION ALL
SELECT 'ATIVIDADE_14_ANALISE_848', COUNT(*)
  FROM SANKHYA.TSIIMP
 WHERE CODREL=848
UNION ALL
SELECT 'ATIVIDADE_15_RASTRO_SALDO', COUNT(*)
  FROM SANKHYA.TGFPRO
 WHERE TEMRASTROLOTE='S' AND TIPCONTEST='N'
UNION ALL
SELECT 'TSICFG_TOTAL', COUNT(*)
  FROM SANKHYA.TSICFG
UNION ALL
SELECT 'RMD_MAP_UNIDADES_TOTAL', COUNT(*)
  FROM SANKHYA.RMD_MAP_UNIDADES
UNION ALL
SELECT 'BKP_RMD_11_TGFEMP', COUNT(*)
  FROM SANKHYA.BKP_RMD_11_TGFEMP;
