-- Diagnostico read-only dos gatilhos dos artefatos e das tabelas afetadas.
SELECT OWNER, TRIGGER_NAME, TABLE_NAME, STATUS, TRIGGER_TYPE, TRIGGERING_EVENT
  FROM ALL_TRIGGERS
 WHERE OWNER = 'SANKHYA'
   AND TABLE_NAME IN (
     'RMD_CASA_2930_R01_MAP',
     'RMD_CASA_2930_R01_BAI_BKP',
     'RMD_CASA_2930_R01_END_BKP',
     'RMD_CASA_2930_R01_DEP',
     'RMD_CASA_2930_R01_EXC',
     'TSIBAI', 'TSIEND', 'TSICEP', 'TGFPAR', 'TGFCPL'
   )
 ORDER BY TABLE_NAME, TRIGGER_NAME;

SELECT OWNER, NAME, TYPE, REFERENCED_OWNER, REFERENCED_NAME, REFERENCED_TYPE
  FROM ALL_DEPENDENCIES
 WHERE OWNER = 'SANKHYA'
   AND NAME IN (
     'RMD_CASA_2930_R01_MAP',
     'RMD_CASA_2930_R01_BAI_BKP',
     'RMD_CASA_2930_R01_END_BKP',
     'RMD_CASA_2930_R01_DEP',
     'RMD_CASA_2930_R01_EXC'
   )
 ORDER BY NAME, REFERENCED_OWNER, REFERENCED_NAME;

SELECT OWNER, TABLE_NAME, NUM_ROWS, LAST_ANALYZED
  FROM ALL_TABLES
 WHERE OWNER = 'SANKHYA'
   AND TABLE_NAME IN (
     'RMD_CASA_2930_R01_MAP',
     'RMD_CASA_2930_R01_BAI_BKP',
     'RMD_CASA_2930_R01_END_BKP',
     'RMD_CASA_2930_R01_DEP',
     'RMD_CASA_2930_R01_EXC'
   )
 ORDER BY TABLE_NAME;
