SELECT OWNER, TABLE_NAME, NUM_ROWS, LAST_ANALYZED
  FROM ALL_TABLES
 WHERE OWNER = 'SANKHYA'
   AND TABLE_NAME IN ('RMD_CASA_2930_R02_MAP','RMD_CASA_2930_R02_BAI_BKP','RMD_CASA_2930_R02_END_BKP')
 ORDER BY TABLE_NAME
