SELECT TABLE_NAME, COLUMN_ID, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE
  FROM ALL_TAB_COLUMNS
 WHERE OWNER = 'SANKHYA'
   AND TABLE_NAME IN ('TSIBAI','TSIEND')
 ORDER BY TABLE_NAME, COLUMN_ID
