SELECT OWNER, TRIGGER_NAME, TABLE_NAME, STATUS, TRIGGER_TYPE, TRIGGERING_EVENT
  FROM ALL_TRIGGERS
 WHERE OWNER = 'SANKHYA'
   AND TABLE_NAME IN (
     'RMD_CASA_2930_R01_MAP',
     'RMD_CASA_2930_R01_BAI_BKP',
     'RMD_CASA_2930_R01_END_BKP',
     'RMD_CASA_2930_R01_DEP',
     'RMD_CASA_2930_R01_EXC',
     'TSIBAI', 'TSIEND', 'TSICEP', 'TGFPAR', 'TGFCPL'
   )
 ORDER BY TABLE_NAME, TRIGGER_NAME
