-- Confirma os contextos funcionais usados para separar colisoes.
SELECT TABLE_NAME,
       COLUMN_NAME,
       DATA_TYPE,
       DATA_LENGTH,
       NULLABLE
  FROM ALL_TAB_COLUMNS
 WHERE OWNER='SANKHYA'
   AND ((TABLE_NAME='TSIBAI' AND COLUMN_NAME IN ('CODBAI','NOMEBAI','CODREG'))
     OR (TABLE_NAME='TSIEND' AND COLUMN_NAME IN ('CODEND','NOMEEND','TIPO','CODLOGRADOURO')))
 ORDER BY TABLE_NAME, COLUMN_ID;
