-- Diagnostico reutilizavel para o piloto de classificacao de parceiros por CNAE.
-- Somente leitura: nao cria objetos e nao altera TGFPAR/TGFTPP.

SET DEFINE OFF;

PROMPT === UNIVERSO DE PARCEIROS COM VENDAS ===

WITH ELEGIVEIS AS (
    SELECT DISTINCT P.CODPARC,
           P.CGC_CPF,
           P.TIPPESSOA,
           P.CODTIPPARC,
           P.ATIVO
      FROM TGFPAR P
     WHERE EXISTS (
               SELECT 1
                 FROM TGFCAB C
                WHERE C.CODPARC = P.CODPARC
                  AND C.TIPMOV = 'V'
           )
),
BASE AS (
    SELECT E.*,
           REGEXP_REPLACE(E.CGC_CPF, '[^0-9]', '') AS DOCUMENTO
      FROM ELEGIVEIS E
)
SELECT 'PARCEIROS_COM_VENDA' AS INDICADOR, COUNT(*) AS QTD FROM BASE
UNION ALL
SELECT 'PESSOA_JURIDICA', COUNT(*) FROM BASE WHERE TIPPESSOA = 'J'
UNION ALL
SELECT 'CNPJ_COM_14_DIGITOS', COUNT(*)
  FROM BASE
 WHERE TIPPESSOA = 'J' AND LENGTH(DOCUMENTO) = 14
UNION ALL
SELECT 'CNPJ_DISTINTOS', COUNT(DISTINCT DOCUMENTO)
  FROM BASE
 WHERE TIPPESSOA = 'J' AND LENGTH(DOCUMENTO) = 14
UNION ALL
SELECT 'SEM_PERFIL', COUNT(*)
  FROM BASE
 WHERE TIPPESSOA = 'J'
   AND LENGTH(DOCUMENTO) = 14
   AND NVL(CODTIPPARC, 0) = 0
ORDER BY 1;

PROMPT === ARVORE DE SEGMENTO DE ATUACAO ===

SELECT LEVEL AS NIVEL,
       CODTIPPARC,
       CODTIPPARCPAI,
       LPAD(' ', (LEVEL - 1) * 2) || DESCRTIPPARC AS PERFIL,
       GRAU,
       ANALITICO,
       ATIVO,
       SEGATUA
  FROM TGFTPP
 START WITH CODTIPPARC = 10100000
CONNECT BY NOCYCLE PRIOR CODTIPPARC = CODTIPPARCPAI
 ORDER SIBLINGS BY CODTIPPARC;

PROMPT === AMOSTRA DIVERSIFICADA POR RAIZ DO CNPJ ===

WITH VENDAS AS (
    SELECT P.CODPARC,
           REGEXP_REPLACE(P.CGC_CPF, '[^0-9]', '') AS CNPJ,
           P.NOMEPARC,
           COUNT(*) AS QTD_VENDAS
      FROM TGFPAR P
      JOIN TGFCAB C ON C.CODPARC = P.CODPARC
     WHERE C.TIPMOV = 'V'
       AND P.TIPPESSOA = 'J'
       AND LENGTH(REGEXP_REPLACE(P.CGC_CPF, '[^0-9]', '')) = 14
     GROUP BY P.CODPARC, P.CGC_CPF, P.NOMEPARC
),
RANQUEADA AS (
    SELECT V.*,
           ROW_NUMBER() OVER (
               PARTITION BY SUBSTR(CNPJ, 1, 8)
               ORDER BY QTD_VENDAS DESC, CODPARC
           ) AS ORDEM_RAIZ
      FROM VENDAS V
)
SELECT CODPARC,
       CNPJ,
       NOMEPARC,
       QTD_VENDAS
  FROM RANQUEADA
 WHERE ORDEM_RAIZ = 1
 ORDER BY QTD_VENDAS DESC, CODPARC
 FETCH FIRST 10 ROWS ONLY;
