INSERT INTO TGFCGM
SELECT EMP.CODEMP,
        CGM.ANO,
        CGM.MES,
        CGM.DTREF,
        CGM.PERCCFFAB,
        CGM.PERCCFOUTROS,
        CGM.PERCCFSERVICO,
        CGM.PERCCOFINS,
        CGM.PERCCSL,
        CGM.PERCCUSVAR,
        CGM.PERCCVARSEMST,
        CGM.PERCMARGEM,
        CGM.PERCPIS,
        CGM.PERCCFFABCALC,
        CGM.PERCCFOUTROSCALC,
        CGM.PERCCFSERVICOCALC,
        CGM.TEMPERCPARTSIMP,
        CGM.PERCIRPJ,
        CGM.PERCCPP
FROM TGFCGM CGM
JOIN TSIEMP EMP ON EMP.CODEMP <> 1;