-- Merge controlado de bairros e enderecos duplicados apos normalizacao.
-- Cliente/base: MEGANET RJ / MEGANETRJPRD.SANKHYACLOUD.COM.BR
-- IMPORTANTE: executar primeiro em uma janela dedicada e conferir a conexao.
-- As tabelas BKP_MBE_* sao persistentes e permitem auditoria/reversao por ID_EXECUCAO.

SET SERVEROUTPUT ON SIZE UNLIMITED
SET SQLBLANKLINES ON
SET DEFINE ON
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

COLUMN RUN_ID NEW_VALUE RUN_ID NOPRINT
SELECT TO_CHAR(SYSTIMESTAMP, 'YYYYMMDDHH24MISSFF3') RUN_ID FROM DUAL;
PROMPT ID_EXECUCAO=MEGANETRJ_20260828_085408

PROMPT === 01. CRIACAO DAS ESTRUTURAS DE BACKUP (SE NECESSARIO) ===
DECLARE
  PROCEDURE cria(p_nome VARCHAR2, p_sql VARCHAR2) IS
    v_qtd NUMBER;
  BEGIN
    SELECT COUNT(*) INTO v_qtd FROM USER_TABLES WHERE TABLE_NAME = UPPER(p_nome);
    IF v_qtd = 0 THEN EXECUTE IMMEDIATE p_sql; END IF;
  END;
BEGIN
  cria('BKP_MBE_MAP_BAI', 'CREATE TABLE BKP_MBE_MAP_BAI (ID_EXECUCAO VARCHAR2(30), COD_OBSOLETO NUMBER, COD_MANTIDO NUMBER)');
  cria('BKP_MBE_MAP_END', 'CREATE TABLE BKP_MBE_MAP_END (ID_EXECUCAO VARCHAR2(30), COD_OBSOLETO NUMBER, COD_MANTIDO NUMBER)');
  cria('BKP_MBE_TSIBAI',  'CREATE TABLE BKP_MBE_TSIBAI AS SELECT CAST(NULL AS VARCHAR2(30)) ID_EXECUCAO, t.* FROM TSIBAI t WHERE 1=0');
  cria('BKP_MBE_TSIEND',  'CREATE TABLE BKP_MBE_TSIEND AS SELECT CAST(NULL AS VARCHAR2(30)) ID_EXECUCAO, t.* FROM TSIEND t WHERE 1=0');
  cria('BKP_MBE_TGFPAR',  'CREATE TABLE BKP_MBE_TGFPAR AS SELECT CAST(NULL AS VARCHAR2(30)) ID_EXECUCAO, CAST(NULL AS VARCHAR2(30)) ROWID_ORIGINAL, t.* FROM TGFPAR t WHERE 1=0');
  cria('BKP_MBE_TSICEP',  'CREATE TABLE BKP_MBE_TSICEP AS SELECT CAST(NULL AS VARCHAR2(30)) ID_EXECUCAO, CAST(NULL AS VARCHAR2(30)) ROWID_ORIGINAL, t.* FROM TSICEP t WHERE 1=0');
  cria('BKP_MBE_TSIEMP',  'CREATE TABLE BKP_MBE_TSIEMP AS SELECT CAST(NULL AS VARCHAR2(30)) ID_EXECUCAO, CAST(NULL AS VARCHAR2(30)) ROWID_ORIGINAL, t.* FROM TSIEMP t WHERE 1=0');
  cria('BKP_MBE_TFPALTERFUN', 'CREATE TABLE BKP_MBE_TFPALTERFUN AS SELECT CAST(NULL AS VARCHAR2(30)) ID_EXECUCAO, CAST(NULL AS VARCHAR2(30)) ROWID_ORIGINAL, t.* FROM TFPALTERFUN t WHERE 1=0');
  cria('BKP_MBE_TFPFUN', 'CREATE TABLE BKP_MBE_TFPFUN AS SELECT CAST(NULL AS VARCHAR2(30)) ID_EXECUCAO, CAST(NULL AS VARCHAR2(30)) ROWID_ORIGINAL, t.* FROM TFPFUN t WHERE 1=0');
END;
/

PROMPT === 02. MAPAS E BACKUP DAS LINHAS AFETADAS ===
DECLARE
  v_qtd NUMBER;
BEGIN
  SELECT (SELECT COUNT(*) FROM BKP_MBE_MAP_BAI WHERE ID_EXECUCAO='MEGANETRJ_20260828_085408')
       + (SELECT COUNT(*) FROM BKP_MBE_MAP_END WHERE ID_EXECUCAO='MEGANETRJ_20260828_085408')
    INTO v_qtd FROM DUAL;
  IF v_qtd <> 0 THEN
    RAISE_APPLICATION_ERROR(-20011, 'ID_EXECUCAO ja utilizado: MEGANETRJ_20260828_085408');
  END IF;
END;
/

INSERT INTO BKP_MBE_MAP_BAI (ID_EXECUCAO, COD_OBSOLETO, COD_MANTIDO)
SELECT 'MEGANETRJ_20260828_085408', CODBAI, KEEP_ID
  FROM (
    SELECT CODBAI,
           MIN(CODBAI) OVER (PARTITION BY REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEBAI),
             'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇáàâãäéèêëíìîïóòôõöúùûüçÃãÕõÂâÊêÎîÔôÛû',
             'AAAAAEEEEIIIIOOOOOUUUUCAAAAAEEEEIIIIOOOOOUUUUCAAAOOAAEIIOOUU')), ' {2,}', ' ')) KEEP_ID,
           COUNT(*) OVER (PARTITION BY REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEBAI),
             'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇáàâãäéèêëíìîïóòôõöúùûüçÃãÕõÂâÊêÎîÔôÛû',
             'AAAAAEEEEIIIIOOOOOUUUUCAAAAAEEEEIIIIOOOOOUUUUCAAAOOAAEIIOOUU')), ' {2,}', ' ')) CNT
      FROM TSIBAI
  ) WHERE CNT > 1 AND CODBAI <> KEEP_ID;

INSERT INTO BKP_MBE_MAP_END (ID_EXECUCAO, COD_OBSOLETO, COD_MANTIDO)
SELECT 'MEGANETRJ_20260828_085408', CODEND, KEEP_ID
  FROM (
    SELECT CODEND,
           MIN(CODEND) OVER (PARTITION BY TIPO, REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEEND),
             'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇáàâãäéèêëíìîïóòôõöúùûüçÃãÕõÂâÊêÎîÔôÛû',
             'AAAAAEEEEIIIIOOOOOUUUUCAAAAAEEEEIIIIOOOOOUUUUCAAAOOAAEIIOOUU')), ' {2,}', ' ')) KEEP_ID,
           COUNT(*) OVER (PARTITION BY TIPO, REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEEND),
             'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇáàâãäéèêëíìîïóòôõöúùûüçÃãÕõÂâÊêÎîÔôÛû',
             'AAAAAEEEEIIIIOOOOOUUUUCAAAAAEEEEIIIIOOOOOUUUUCAAAOOAAEIIOOUU')), ' {2,}', ' ')) CNT
      FROM TSIEND
  ) WHERE CNT > 1 AND CODEND <> KEEP_ID;

DECLARE
  v_bai NUMBER;
  v_end NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_bai FROM BKP_MBE_MAP_BAI WHERE ID_EXECUCAO='MEGANETRJ_20260828_085408';
  SELECT COUNT(*) INTO v_end FROM BKP_MBE_MAP_END WHERE ID_EXECUCAO='MEGANETRJ_20260828_085408';
  IF v_bai <> 463 OR v_end <> 7285 THEN
    RAISE_APPLICATION_ERROR(-20012, 'Diagnostico divergiu: bairros=' || v_bai || ', enderecos=' || v_end);
  END IF;
  DBMS_OUTPUT.PUT_LINE('OK: mapas conferidos: bairros=' || v_bai || ', enderecos=' || v_end);
END;
/

INSERT INTO BKP_MBE_TSIBAI SELECT 'MEGANETRJ_20260828_085408', b.* FROM TSIBAI b
 WHERE b.CODBAI IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_BAI WHERE ID_EXECUCAO='MEGANETRJ_20260828_085408')
    OR b.CODBAI IN (SELECT COD_MANTIDO FROM BKP_MBE_MAP_BAI WHERE ID_EXECUCAO='MEGANETRJ_20260828_085408');
INSERT INTO BKP_MBE_TSIEND SELECT 'MEGANETRJ_20260828_085408', e.* FROM TSIEND e
 WHERE e.CODEND IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_END WHERE ID_EXECUCAO='MEGANETRJ_20260828_085408')
    OR e.CODEND IN (SELECT COD_MANTIDO FROM BKP_MBE_MAP_END WHERE ID_EXECUCAO='MEGANETRJ_20260828_085408');
INSERT INTO BKP_MBE_TGFPAR SELECT 'MEGANETRJ_20260828_085408', ROWIDTOCHAR(ROWID), p.* FROM TGFPAR p
 WHERE p.CODBAI IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_BAI WHERE ID_EXECUCAO='MEGANETRJ_20260828_085408')
    OR p.CODEND IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_END WHERE ID_EXECUCAO='MEGANETRJ_20260828_085408');
INSERT INTO BKP_MBE_TSICEP SELECT 'MEGANETRJ_20260828_085408', ROWIDTOCHAR(ROWID), c.* FROM TSICEP c
 WHERE c.CODBAI IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_BAI WHERE ID_EXECUCAO='MEGANETRJ_20260828_085408')
    OR c.CODEND IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_END WHERE ID_EXECUCAO='MEGANETRJ_20260828_085408');
INSERT INTO BKP_MBE_TSIEMP SELECT 'MEGANETRJ_20260828_085408', ROWIDTOCHAR(ROWID), e.* FROM TSIEMP e
 WHERE e.CODBAI IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_BAI WHERE ID_EXECUCAO='MEGANETRJ_20260828_085408')
    OR e.CODEND IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_END WHERE ID_EXECUCAO='MEGANETRJ_20260828_085408');
INSERT INTO BKP_MBE_TFPALTERFUN SELECT 'MEGANETRJ_20260828_085408', ROWIDTOCHAR(ROWID), f.* FROM TFPALTERFUN f
 WHERE f.CODBAI IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_BAI WHERE ID_EXECUCAO='MEGANETRJ_20260828_085408')
    OR f.CODEND IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_END WHERE ID_EXECUCAO='MEGANETRJ_20260828_085408');
INSERT INTO BKP_MBE_TFPFUN SELECT 'MEGANETRJ_20260828_085408', ROWIDTOCHAR(ROWID), f.* FROM TFPFUN f
 WHERE f.CODBAI IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_BAI WHERE ID_EXECUCAO='MEGANETRJ_20260828_085408')
    OR f.CODEND IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_END WHERE ID_EXECUCAO='MEGANETRJ_20260828_085408');
COMMIT;

PROMPT === 03. MERGE TRANSACIONAL ===
DECLARE
  v_restantes NUMBER;
BEGIN
  UPDATE TGFPAR p
     SET CODBAI = NVL((SELECT m.COD_MANTIDO FROM BKP_MBE_MAP_BAI m WHERE m.ID_EXECUCAO='MEGANETRJ_20260828_085408' AND m.COD_OBSOLETO=p.CODBAI), p.CODBAI),
         CODEND = NVL((SELECT m.COD_MANTIDO FROM BKP_MBE_MAP_END m WHERE m.ID_EXECUCAO='MEGANETRJ_20260828_085408' AND m.COD_OBSOLETO=p.CODEND), p.CODEND)
   WHERE EXISTS (SELECT 1 FROM BKP_MBE_MAP_BAI m WHERE m.ID_EXECUCAO='MEGANETRJ_20260828_085408' AND m.COD_OBSOLETO=p.CODBAI)
      OR EXISTS (SELECT 1 FROM BKP_MBE_MAP_END m WHERE m.ID_EXECUCAO='MEGANETRJ_20260828_085408' AND m.COD_OBSOLETO=p.CODEND);

  UPDATE TSICEP c
     SET CODBAI = NVL((SELECT m.COD_MANTIDO FROM BKP_MBE_MAP_BAI m WHERE m.ID_EXECUCAO='MEGANETRJ_20260828_085408' AND m.COD_OBSOLETO=c.CODBAI), c.CODBAI),
         CODEND = NVL((SELECT m.COD_MANTIDO FROM BKP_MBE_MAP_END m WHERE m.ID_EXECUCAO='MEGANETRJ_20260828_085408' AND m.COD_OBSOLETO=c.CODEND), c.CODEND)
   WHERE EXISTS (SELECT 1 FROM BKP_MBE_MAP_BAI m WHERE m.ID_EXECUCAO='MEGANETRJ_20260828_085408' AND m.COD_OBSOLETO=c.CODBAI)
      OR EXISTS (SELECT 1 FROM BKP_MBE_MAP_END m WHERE m.ID_EXECUCAO='MEGANETRJ_20260828_085408' AND m.COD_OBSOLETO=c.CODEND);

  UPDATE TSIEMP e
     SET CODBAI = NVL((SELECT m.COD_MANTIDO FROM BKP_MBE_MAP_BAI m WHERE m.ID_EXECUCAO='MEGANETRJ_20260828_085408' AND m.COD_OBSOLETO=e.CODBAI), e.CODBAI),
         CODEND = NVL((SELECT m.COD_MANTIDO FROM BKP_MBE_MAP_END m WHERE m.ID_EXECUCAO='MEGANETRJ_20260828_085408' AND m.COD_OBSOLETO=e.CODEND), e.CODEND)
   WHERE EXISTS (SELECT 1 FROM BKP_MBE_MAP_BAI m WHERE m.ID_EXECUCAO='MEGANETRJ_20260828_085408' AND m.COD_OBSOLETO=e.CODBAI)
      OR EXISTS (SELECT 1 FROM BKP_MBE_MAP_END m WHERE m.ID_EXECUCAO='MEGANETRJ_20260828_085408' AND m.COD_OBSOLETO=e.CODEND);

  UPDATE TFPALTERFUN f
     SET CODBAI = NVL((SELECT m.COD_MANTIDO FROM BKP_MBE_MAP_BAI m WHERE m.ID_EXECUCAO='MEGANETRJ_20260828_085408' AND m.COD_OBSOLETO=f.CODBAI), f.CODBAI),
         CODEND = NVL((SELECT m.COD_MANTIDO FROM BKP_MBE_MAP_END m WHERE m.ID_EXECUCAO='MEGANETRJ_20260828_085408' AND m.COD_OBSOLETO=f.CODEND), f.CODEND)
   WHERE EXISTS (SELECT 1 FROM BKP_MBE_MAP_BAI m WHERE m.ID_EXECUCAO='MEGANETRJ_20260828_085408' AND m.COD_OBSOLETO=f.CODBAI)
      OR EXISTS (SELECT 1 FROM BKP_MBE_MAP_END m WHERE m.ID_EXECUCAO='MEGANETRJ_20260828_085408' AND m.COD_OBSOLETO=f.CODEND);

  UPDATE TFPFUN f
     SET CODBAI = NVL((SELECT m.COD_MANTIDO FROM BKP_MBE_MAP_BAI m WHERE m.ID_EXECUCAO='MEGANETRJ_20260828_085408' AND m.COD_OBSOLETO=f.CODBAI), f.CODBAI),
         CODEND = NVL((SELECT m.COD_MANTIDO FROM BKP_MBE_MAP_END m WHERE m.ID_EXECUCAO='MEGANETRJ_20260828_085408' AND m.COD_OBSOLETO=f.CODEND), f.CODEND)
   WHERE EXISTS (SELECT 1 FROM BKP_MBE_MAP_BAI m WHERE m.ID_EXECUCAO='MEGANETRJ_20260828_085408' AND m.COD_OBSOLETO=f.CODBAI)
      OR EXISTS (SELECT 1 FROM BKP_MBE_MAP_END m WHERE m.ID_EXECUCAO='MEGANETRJ_20260828_085408' AND m.COD_OBSOLETO=f.CODEND);

  SELECT (SELECT COUNT(*) FROM TGFPAR p WHERE p.CODBAI IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_BAI WHERE ID_EXECUCAO='MEGANETRJ_20260828_085408') OR p.CODEND IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_END WHERE ID_EXECUCAO='MEGANETRJ_20260828_085408'))
       + (SELECT COUNT(*) FROM TSICEP c WHERE c.CODBAI IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_BAI WHERE ID_EXECUCAO='MEGANETRJ_20260828_085408') OR c.CODEND IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_END WHERE ID_EXECUCAO='MEGANETRJ_20260828_085408'))
       + (SELECT COUNT(*) FROM TSIEMP e WHERE e.CODBAI IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_BAI WHERE ID_EXECUCAO='MEGANETRJ_20260828_085408') OR e.CODEND IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_END WHERE ID_EXECUCAO='MEGANETRJ_20260828_085408'))
       + (SELECT COUNT(*) FROM TFPALTERFUN f WHERE f.CODBAI IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_BAI WHERE ID_EXECUCAO='MEGANETRJ_20260828_085408') OR f.CODEND IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_END WHERE ID_EXECUCAO='MEGANETRJ_20260828_085408'))
       + (SELECT COUNT(*) FROM TFPFUN f WHERE f.CODBAI IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_BAI WHERE ID_EXECUCAO='MEGANETRJ_20260828_085408') OR f.CODEND IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_END WHERE ID_EXECUCAO='MEGANETRJ_20260828_085408'))
    INTO v_restantes FROM DUAL;
  IF v_restantes <> 0 THEN RAISE_APPLICATION_ERROR(-20001, 'Ainda existem referencias: ' || v_restantes); END IF;

  DELETE FROM TSIBAI WHERE CODBAI IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_BAI WHERE ID_EXECUCAO='MEGANETRJ_20260828_085408');
  DELETE FROM TSIEND WHERE CODEND IN (SELECT COD_OBSOLETO FROM BKP_MBE_MAP_END WHERE ID_EXECUCAO='MEGANETRJ_20260828_085408');

  UPDATE TSIBAI SET NOMEBAI = REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEBAI),
    'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇáàâãäéèêëíìîïóòôõöúùûüçÃãÕõÂâÊêÎîÔôÛû',
    'AAAAAEEEEIIIIOOOOOUUUUCAAAAAEEEEIIIIOOOOOUUUUCAAAOOAAEIIOOUU')), ' {2,}', ' ')
   WHERE CODBAI IN (SELECT COD_MANTIDO FROM BKP_MBE_MAP_BAI WHERE ID_EXECUCAO='MEGANETRJ_20260828_085408');
  UPDATE TSIEND SET NOMEEND = REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEEND),
    'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇáàâãäéèêëíìîïóòôõöúùûüçÃãÕõÂâÊêÎîÔôÛû',
    'AAAAAEEEEIIIIOOOOOUUUUCAAAAAEEEEIIIIOOOOOUUUUCAAAOOAAEIIOOUU')), ' {2,}', ' ')
   WHERE CODEND IN (SELECT COD_MANTIDO FROM BKP_MBE_MAP_END WHERE ID_EXECUCAO='MEGANETRJ_20260828_085408');

  COMMIT;
  DBMS_OUTPUT.PUT_LINE('OK: merge concluido. ID_EXECUCAO=MEGANETRJ_20260828_085408');
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('ERRO: DML revertido; backups preservados. ' || SQLERRM);
    RAISE;
END;
/

PROMPT === FIM DO MERGE ===
