-- Pure PL/SQL transactional normalization (no SET/with; compatible with stricter parsers)
DECLARE
  e_msg   VARCHAR2(4000);
  e_code  NUMBER;
  v_rows  NUMBER;

  PROCEDURE log(p VARCHAR2) IS BEGIN DBMS_OUTPUT.PUT_LINE(p); END;

  PROCEDURE try_enable_trigger IS
  BEGIN
    EXECUTE IMMEDIATE 'ALTER TRIGGER TRG_INC_UPD_TGFITE ENABLE';
    log('Trigger TRG_INC_UPD_TGFITE reabilitada.');
  EXCEPTION WHEN OTHERS THEN
    log('Aviso: falha ao reabilitar TRG_INC_UPD_TGFITE: '||SQLERRM);
  END;
BEGIN
  DBMS_OUTPUT.ENABLE(NULL);

  log('Passo 0: desabilitando trigger de itens (se existir)...');
  BEGIN
    EXECUTE IMMEDIATE 'ALTER TRIGGER TRG_INC_UPD_TGFITE DISABLE';
    log('Trigger TRG_INC_UPD_TGFITE desabilitada.');
  EXCEPTION WHEN OTHERS THEN
    log('Aviso: não foi possível desabilitar TRG_INC_UPD_TGFITE: '||SQLERRM||'. Prosseguindo.');
  END;

  log('Iniciando normalização transacional...');

  -- 0) TGFPRO
  UPDATE TGFPRO p
     SET p.CODVOL = (SELECT m.to_code FROM (
  SELECT 'CDA' AS from_code, 'CD' AS to_code FROM dual UNION ALL
  SELECT 'CX5000','CX' FROM dual UNION ALL
  SELECT 'CXA','CX' FROM dual UNION ALL
  SELECT 'KLG','KG' FROM dual UNION ALL
  SELECT 'L','LT' FROM dual UNION ALL
  SELECT 'PEC','PC' FROM dual UNION ALL
  SELECT 'PÇ','PC' FROM dual UNION ALL
  SELECT 'PÇ.','PC' FROM dual UNION ALL
  SELECT 'PECA','PC' FROM dual UNION ALL
  SELECT 'PEÇA','PC' FROM dual UNION ALL
  SELECT '1 UNID','UN' FROM dual UNION ALL
  SELECT 'UND','UN' FROM dual UNION ALL
  SELECT 'UNI','UN' FROM dual UNION ALL
  SELECT 'UNID','UN' FROM dual UNION ALL
  SELECT 'UNIDA','UN' FROM dual UNION ALL
  SELECT 'UNIDAD','UN' FROM dual UNION ALL
  SELECT 'UN1','UN' FROM dual UNION ALL
  SELECT 'M','MT' FROM dual UNION ALL
  SELECT 'PCT','PT' FROM dual UNION ALL
  SELECT 'PACOTE','PT' FROM dual UNION ALL
  SELECT 'TO','TN' FROM dual UNION ALL
  SELECT 'RLRL','RL' FROM dual UNION ALL
  SELECT 'BLOCO','BL' FROM dual UNION ALL
  SELECT 'FRASCO','FR' FROM dual UNION ALL
  SELECT 'JOGO','JG' FROM dual
) m WHERE m.from_code = p.CODVOL)
   WHERE EXISTS (SELECT 1 FROM (
  SELECT 'CDA' AS from_code, 'CD' AS to_code FROM dual UNION ALL
  SELECT 'CX5000','CX' FROM dual UNION ALL
  SELECT 'CXA','CX' FROM dual UNION ALL
  SELECT 'KLG','KG' FROM dual UNION ALL
  SELECT 'L','LT' FROM dual UNION ALL
  SELECT 'PEC','PC' FROM dual UNION ALL
  SELECT 'PÇ','PC' FROM dual UNION ALL
  SELECT 'PÇ.','PC' FROM dual UNION ALL
  SELECT 'PECA','PC' FROM dual UNION ALL
  SELECT 'PEÇA','PC' FROM dual UNION ALL
  SELECT '1 UNID','UN' FROM dual UNION ALL
  SELECT 'UND','UN' FROM dual UNION ALL
  SELECT 'UNI','UN' FROM dual UNION ALL
  SELECT 'UNID','UN' FROM dual UNION ALL
  SELECT 'UNIDA','UN' FROM dual UNION ALL
  SELECT 'UNIDAD','UN' FROM dual UNION ALL
  SELECT 'UN1','UN' FROM dual UNION ALL
  SELECT 'M','MT' FROM dual UNION ALL
  SELECT 'PCT','PT' FROM dual UNION ALL
  SELECT 'PACOTE','PT' FROM dual UNION ALL
  SELECT 'TO','TN' FROM dual UNION ALL
  SELECT 'RLRL','RL' FROM dual UNION ALL
  SELECT 'BLOCO','BL' FROM dual UNION ALL
  SELECT 'FRASCO','FR' FROM dual UNION ALL
  SELECT 'JOGO','JG' FROM dual
) m WHERE m.from_code = p.CODVOL)
     AND NOT EXISTS (SELECT 1 FROM (
  SELECT DISTINCT ITE.CODVOL
    FROM TGFITE ITE
    JOIN TGFCAB CAB ON CAB.NUNOTA = ITE.NUNOTA 
    JOIN TGFTOP TOP ON TOP.CODTIPOPER = CAB.CODTIPOPER
                   AND TOP.DHALTER   = CAB.DHTIPOPER
   WHERE NVL(TOP.ATUALLIVFIS,'N') <> 'E'
     AND NVL(TOP.ATUALLIVISS,'N') <> 'E'
) s WHERE s.CODVOL = p.CODVOL);
  v_rows := SQL%ROWCOUNT; log('Linhas afetadas TGFPRO: '||v_rows); COMMIT;

  -- 1) TGFITE
  UPDATE TGFITE i
     SET i.CODVOL = (SELECT m.to_code FROM (
  SELECT 'CDA' AS from_code, 'CD' AS to_code FROM dual UNION ALL
  SELECT 'CX5000','CX' FROM dual UNION ALL
  SELECT 'CXA','CX' FROM dual UNION ALL
  SELECT 'KLG','KG' FROM dual UNION ALL
  SELECT 'L','LT' FROM dual UNION ALL
  SELECT 'PEC','PC' FROM dual UNION ALL
  SELECT 'PÇ','PC' FROM dual UNION ALL
  SELECT 'PÇ.','PC' FROM dual UNION ALL
  SELECT 'PECA','PC' FROM dual UNION ALL
  SELECT 'PEÇA','PC' FROM dual UNION ALL
  SELECT '1 UNID','UN' FROM dual UNION ALL
  SELECT 'UND','UN' FROM dual UNION ALL
  SELECT 'UNI','UN' FROM dual UNION ALL
  SELECT 'UNID','UN' FROM dual UNION ALL
  SELECT 'UNIDA','UN' FROM dual UNION ALL
  SELECT 'UNIDAD','UN' FROM dual UNION ALL
  SELECT 'UN1','UN' FROM dual UNION ALL
  SELECT 'M','MT' FROM dual UNION ALL
  SELECT 'PCT','PT' FROM dual UNION ALL
  SELECT 'PACOTE','PT' FROM dual UNION ALL
  SELECT 'TO','TN' FROM dual UNION ALL
  SELECT 'RLRL','RL' FROM dual UNION ALL
  SELECT 'BLOCO','BL' FROM dual UNION ALL
  SELECT 'FRASCO','FR' FROM dual UNION ALL
  SELECT 'JOGO','JG' FROM dual
) m WHERE m.from_code = i.CODVOL)
   WHERE EXISTS (SELECT 1 FROM (
  SELECT 'CDA' AS from_code, 'CD' AS to_code FROM dual UNION ALL
  SELECT 'CX5000','CX' FROM dual UNION ALL
  SELECT 'CXA','CX' FROM dual UNION ALL
  SELECT 'KLG','KG' FROM dual UNION ALL
  SELECT 'L','LT' FROM dual UNION ALL
  SELECT 'PEC','PC' FROM dual UNION ALL
  SELECT 'PÇ','PC' FROM dual UNION ALL
  SELECT 'PÇ.','PC' FROM dual UNION ALL
  SELECT 'PECA','PC' FROM dual UNION ALL
  SELECT 'PEÇA','PC' FROM dual UNION ALL
  SELECT '1 UNID','UN' FROM dual UNION ALL
  SELECT 'UND','UN' FROM dual UNION ALL
  SELECT 'UNI','UN' FROM dual UNION ALL
  SELECT 'UNID','UN' FROM dual UNION ALL
  SELECT 'UNIDA','UN' FROM dual UNION ALL
  SELECT 'UNIDAD','UN' FROM dual UNION ALL
  SELECT 'UN1','UN' FROM dual UNION ALL
  SELECT 'M','MT' FROM dual UNION ALL
  SELECT 'PCT','PT' FROM dual UNION ALL
  SELECT 'PACOTE','PT' FROM dual UNION ALL
  SELECT 'TO','TN' FROM dual UNION ALL
  SELECT 'RLRL','RL' FROM dual UNION ALL
  SELECT 'BLOCO','BL' FROM dual UNION ALL
  SELECT 'FRASCO','FR' FROM dual UNION ALL
  SELECT 'JOGO','JG' FROM dual
) m WHERE m.from_code = i.CODVOL)
     AND NOT EXISTS (SELECT 1 FROM (
  SELECT DISTINCT ITE.CODVOL
    FROM TGFITE ITE
    JOIN TGFCAB CAB ON CAB.NUNOTA = ITE.NUNOTA 
    JOIN TGFTOP TOP ON TOP.CODTIPOPER = CAB.CODTIPOPER
                   AND TOP.DHALTER   = CAB.DHTIPOPER
   WHERE NVL(TOP.ATUALLIVFIS,'N') <> 'E'
     AND NVL(TOP.ATUALLIVISS,'N') <> 'E'
) s WHERE s.CODVOL = i.CODVOL);
  v_rows := SQL%ROWCOUNT; log('Linhas afetadas TGFITE: '||v_rows); COMMIT;

  -- 2) TGFVOA (CODVOL)
  DELETE FROM TGFVOA v
   WHERE EXISTS (SELECT 1 FROM (
  SELECT 'CDA' AS from_code, 'CD' AS to_code FROM dual UNION ALL
  SELECT 'CX5000','CX' FROM dual UNION ALL
  SELECT 'CXA','CX' FROM dual UNION ALL
  SELECT 'KLG','KG' FROM dual UNION ALL
  SELECT 'L','LT' FROM dual UNION ALL
  SELECT 'PEC','PC' FROM dual UNION ALL
  SELECT 'PÇ','PC' FROM dual UNION ALL
  SELECT 'PÇ.','PC' FROM dual UNION ALL
  SELECT 'PECA','PC' FROM dual UNION ALL
  SELECT 'PEÇA','PC' FROM dual UNION ALL
  SELECT '1 UNID','UN' FROM dual UNION ALL
  SELECT 'UND','UN' FROM dual UNION ALL
  SELECT 'UNI','UN' FROM dual UNION ALL
  SELECT 'UNID','UN' FROM dual UNION ALL
  SELECT 'UNIDA','UN' FROM dual UNION ALL
  SELECT 'UNIDAD','UN' FROM dual UNION ALL
  SELECT 'UN1','UN' FROM dual UNION ALL
  SELECT 'M','MT' FROM dual UNION ALL
  SELECT 'PCT','PT' FROM dual UNION ALL
  SELECT 'PACOTE','PT' FROM dual UNION ALL
  SELECT 'TO','TN' FROM dual UNION ALL
  SELECT 'RLRL','RL' FROM dual UNION ALL
  SELECT 'BLOCO','BL' FROM dual UNION ALL
  SELECT 'FRASCO','FR' FROM dual UNION ALL
  SELECT 'JOGO','JG' FROM dual
) m WHERE m.from_code = v.CODVOL)
     AND NOT EXISTS (SELECT 1 FROM (
  SELECT DISTINCT ITE.CODVOL
    FROM TGFITE ITE
    JOIN TGFCAB CAB ON CAB.NUNOTA = ITE.NUNOTA 
    JOIN TGFTOP TOP ON TOP.CODTIPOPER = CAB.CODTIPOPER
                   AND TOP.DHALTER   = CAB.DHTIPOPER
   WHERE NVL(TOP.ATUALLIVFIS,'N') <> 'E'
     AND NVL(TOP.ATUALLIVISS,'N') <> 'E'
) s WHERE s.CODVOL = v.CODVOL);
  v_rows := SQL%ROWCOUNT; log('Linhas removidas TGFVOA(CODVOL): '||v_rows); COMMIT;

  -- 2,1) TGFGIR1 (CODVOL)
  DELETE FROM TGFGIR1 v
   WHERE EXISTS (SELECT 1 FROM (
  SELECT 'CDA' AS from_code, 'CD' AS to_code FROM dual UNION ALL
  SELECT 'CX5000','CX' FROM dual UNION ALL
  SELECT 'CXA','CX' FROM dual UNION ALL
  SELECT 'KLG','KG' FROM dual UNION ALL
  SELECT 'L','LT' FROM dual UNION ALL
  SELECT 'PEC','PC' FROM dual UNION ALL
  SELECT 'PÇ','PC' FROM dual UNION ALL
  SELECT 'PÇ.','PC' FROM dual UNION ALL
  SELECT 'PECA','PC' FROM dual UNION ALL
  SELECT 'PEÇA','PC' FROM dual UNION ALL
  SELECT '1 UNID','UN' FROM dual UNION ALL
  SELECT 'UND','UN' FROM dual UNION ALL
  SELECT 'UNI','UN' FROM dual UNION ALL
  SELECT 'UNID','UN' FROM dual UNION ALL
  SELECT 'UNIDA','UN' FROM dual UNION ALL
  SELECT 'UNIDAD','UN' FROM dual UNION ALL
  SELECT 'UN1','UN' FROM dual UNION ALL
  SELECT 'M','MT' FROM dual UNION ALL
  SELECT 'PCT','PT' FROM dual UNION ALL
  SELECT 'PACOTE','PT' FROM dual UNION ALL
  SELECT 'TO','TN' FROM dual UNION ALL
  SELECT 'RLRL','RL' FROM dual UNION ALL
  SELECT 'BLOCO','BL' FROM dual UNION ALL
  SELECT 'FRASCO','FR' FROM dual UNION ALL
  SELECT 'JOGO','JG' FROM dual
) m WHERE m.from_code = v.CODVOL)
     AND NOT EXISTS (SELECT 1 FROM (
  SELECT DISTINCT ITE.CODVOL
    FROM TGFITE ITE
    JOIN TGFCAB CAB ON CAB.NUNOTA = ITE.NUNOTA 
    JOIN TGFTOP TOP ON TOP.CODTIPOPER = CAB.CODTIPOPER
                   AND TOP.DHALTER   = CAB.DHTIPOPER
   WHERE NVL(TOP.ATUALLIVFIS,'N') <> 'E'
     AND NVL(TOP.ATUALLIVISS,'N') <> 'E'
) s WHERE s.CODVOL = v.CODVOL);
  v_rows := SQL%ROWCOUNT; log('Linhas removidas TGFGIR1(CODVOL): '||v_rows); COMMIT;

  -- 2) TGFVOA (CODVOL)
  DELETE FROM TGFVOA v
   WHERE EXISTS (SELECT 1 FROM (
  SELECT 'CDA' AS from_code, 'CD' AS to_code FROM dual UNION ALL
  SELECT 'CX5000','CX' FROM dual UNION ALL
  SELECT 'CXA','CX' FROM dual UNION ALL
  SELECT 'KLG','KG' FROM dual UNION ALL
  SELECT 'L','LT' FROM dual UNION ALL
  SELECT 'PEC','PC' FROM dual UNION ALL
  SELECT 'PÇ','PC' FROM dual UNION ALL
  SELECT 'PÇ.','PC' FROM dual UNION ALL
  SELECT 'PECA','PC' FROM dual UNION ALL
  SELECT 'PEÇA','PC' FROM dual UNION ALL
  SELECT '1 UNID','UN' FROM dual UNION ALL
  SELECT 'UND','UN' FROM dual UNION ALL
  SELECT 'UNI','UN' FROM dual UNION ALL
  SELECT 'UNID','UN' FROM dual UNION ALL
  SELECT 'UNIDA','UN' FROM dual UNION ALL
  SELECT 'UNIDAD','UN' FROM dual UNION ALL
  SELECT 'UN1','UN' FROM dual UNION ALL
  SELECT 'M','MT' FROM dual UNION ALL
  SELECT 'PCT','PT' FROM dual UNION ALL
  SELECT 'PACOTE','PT' FROM dual UNION ALL
  SELECT 'TO','TN' FROM dual UNION ALL
  SELECT 'RLRL','RL' FROM dual UNION ALL
  SELECT 'BLOCO','BL' FROM dual UNION ALL
  SELECT 'FRASCO','FR' FROM dual UNION ALL
  SELECT 'JOGO','JG' FROM dual
) m WHERE m.from_code = v.CODVOL)
     AND NOT EXISTS (SELECT 1 FROM (
  SELECT DISTINCT ITE.CODVOL
    FROM TGFITE ITE
    JOIN TGFCAB CAB ON CAB.NUNOTA = ITE.NUNOTA 
    JOIN TGFTOP TOP ON TOP.CODTIPOPER = CAB.CODTIPOPER
                   AND TOP.DHALTER   = CAB.DHTIPOPER
   WHERE NVL(TOP.ATUALLIVFIS,'N') <> 'E'
     AND NVL(TOP.ATUALLIVISS,'N') <> 'E'
) s WHERE s.CODVOL = v.CODVOL);
  v_rows := SQL%ROWCOUNT; log('Linhas removidas TGFVOA(CODVOL): '||v_rows); COMMIT;

  -- 2.5) TGFPAP set UNIDADE a partir de UNIDADEPARC quando for NULL
  UPDATE TGFPAP
     SET UNIDADE = UNIDADEPARC
   WHERE UNIDADE IS NULL;
  v_rows := SQL%ROWCOUNT; log('Linhas atualizadas TGFPAP (UNIDADE <- UNIDADEPARC): '||v_rows); COMMIT;

  -- 2.6) TGFPAP deletar registros com UNIDADEPARC mapeada e não protegida
  DELETE FROM TGFPAP p
   WHERE EXISTS (SELECT 1 FROM (
  SELECT 'CDA' AS from_code, 'CD' AS to_code FROM dual UNION ALL
  SELECT 'CX5000','CX' FROM dual UNION ALL
  SELECT 'CXA','CX' FROM dual UNION ALL
  SELECT 'KLG','KG' FROM dual UNION ALL
  SELECT 'L','LT' FROM dual UNION ALL
  SELECT 'PEC','PC' FROM dual UNION ALL
  SELECT 'PÇ','PC' FROM dual UNION ALL
  SELECT 'PÇ.','PC' FROM dual UNION ALL
  SELECT 'PECA','PC' FROM dual UNION ALL
  SELECT 'PEÇA','PC' FROM dual UNION ALL
  SELECT '1 UNID','UN' FROM dual UNION ALL
  SELECT 'UND','UN' FROM dual UNION ALL
  SELECT 'UNI','UN' FROM dual UNION ALL
  SELECT 'UNID','UN' FROM dual UNION ALL
  SELECT 'UNIDA','UN' FROM dual UNION ALL
  SELECT 'UNIDAD','UN' FROM dual UNION ALL
  SELECT 'UN1','UN' FROM dual UNION ALL
  SELECT 'M','MT' FROM dual UNION ALL
  SELECT 'PCT','PT' FROM dual UNION ALL
  SELECT 'PACOTE','PT' FROM dual UNION ALL
  SELECT 'TO','TN' FROM dual UNION ALL
  SELECT 'RLRL','RL' FROM dual UNION ALL
  SELECT 'BLOCO','BL' FROM dual UNION ALL
  SELECT 'FRASCO','FR' FROM dual UNION ALL
  SELECT 'JOGO','JG' FROM dual
) m WHERE m.from_code = p.UNIDADEPARC)
     AND NOT EXISTS (SELECT 1 FROM (
  SELECT DISTINCT ITE.CODVOL
    FROM TGFITE ITE
    JOIN TGFCAB CAB ON CAB.NUNOTA = ITE.NUNOTA 
    JOIN TGFTOP TOP ON TOP.CODTIPOPER = CAB.CODTIPOPER
                   AND TOP.DHALTER   = CAB.DHTIPOPER
   WHERE NVL(TOP.ATUALLIVFIS,'N') <> 'E'
     AND NVL(TOP.ATUALLIVISS,'N') <> 'E'
) s WHERE s.CODVOL = p.UNIDADEPARC);
  v_rows := SQL%ROWCOUNT; log('Linhas removidas TGFPAP: '||v_rows); COMMIT;

  -- 3) TGFVOL
  DELETE FROM TGFVOL t
   WHERE EXISTS (SELECT 1 FROM (
  SELECT 'CDA' AS from_code, 'CD' AS to_code FROM dual UNION ALL
  SELECT 'CX5000','CX' FROM dual UNION ALL
  SELECT 'CXA','CX' FROM dual UNION ALL
  SELECT 'KLG','KG' FROM dual UNION ALL
  SELECT 'L','LT' FROM dual UNION ALL
  SELECT 'PEC','PC' FROM dual UNION ALL
  SELECT 'PÇ','PC' FROM dual UNION ALL
  SELECT 'PÇ.','PC' FROM dual UNION ALL
  SELECT 'PECA','PC' FROM dual UNION ALL
  SELECT 'PEÇA','PC' FROM dual UNION ALL
  SELECT '1 UNID','UN' FROM dual UNION ALL
  SELECT 'UND','UN' FROM dual UNION ALL
  SELECT 'UNI','UN' FROM dual UNION ALL
  SELECT 'UNID','UN' FROM dual UNION ALL
  SELECT 'UNIDA','UN' FROM dual UNION ALL
  SELECT 'UNIDAD','UN' FROM dual UNION ALL
  SELECT 'UN1','UN' FROM dual UNION ALL
  SELECT 'M','MT' FROM dual UNION ALL
  SELECT 'PCT','PT' FROM dual UNION ALL
  SELECT 'PACOTE','PT' FROM dual UNION ALL
  SELECT 'TO','TN' FROM dual UNION ALL
  SELECT 'RLRL','RL' FROM dual UNION ALL
  SELECT 'BLOCO','BL' FROM dual UNION ALL
  SELECT 'FRASCO','FR' FROM dual UNION ALL
  SELECT 'JOGO','JG' FROM dual
) m WHERE m.from_code = t.CODVOL)
     AND NOT EXISTS (SELECT 1 FROM (
  SELECT DISTINCT ITE.CODVOL
    FROM TGFITE ITE
    JOIN TGFCAB CAB ON CAB.NUNOTA = ITE.NUNOTA 
    JOIN TGFTOP TOP ON TOP.CODTIPOPER = CAB.CODTIPOPER
                   AND TOP.DHALTER   = CAB.DHTIPOPER
   WHERE NVL(TOP.ATUALLIVFIS,'N') <> 'E'
     AND NVL(TOP.ATUALLIVISS,'N') <> 'E'
) s WHERE s.CODVOL = t.CODVOL);
  v_rows := SQL%ROWCOUNT; log('Linhas removidas TGFVOL: '||v_rows); COMMIT;

  --COMMIT;
  log('COMMIT realizado com sucesso.');
  try_enable_trigger;

EXCEPTION
  WHEN OTHERS THEN
    e_msg  := SQLERRM;
    e_code := SQLCODE;
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('ROLLBACK executado devido a erro.');
    try_enable_trigger;
    DBMS_OUTPUT.PUT_LINE('ERRO durante a normalização: '||e_msg||' (SQLCODE='||e_code||')');
    RAISE;
END;
/
