-- Somente leitura. Nao executa os comandos exibidos na coluna DML_PREVISTO.

SET DEFINE ON;
ACCEPT ID_CARGA CHAR PROMPT 'Informe o ID_CARGA a simular: '

PROMPT === INCONSISTENCIAS DA CARGA ===

SELECT TIPO, CHAVE, MOTIVO
  FROM (
        SELECT 'PARCEIRO' AS TIPO, TO_CHAR(S.CODPARC) AS CHAVE,
               'Parceiro inexistente' AS MOTIVO
          FROM STG_PPC_PARCEIRO S
         WHERE S.ID_CARGA = '&ID_CARGA'
           AND NOT EXISTS (SELECT 1 FROM TGFPAR P WHERE P.CODPARC = S.CODPARC)
        UNION ALL
        SELECT 'PARCEIRO', TO_CHAR(S.CODPARC), 'CNPJ divergente do cadastro'
          FROM STG_PPC_PARCEIRO S
          JOIN TGFPAR P ON P.CODPARC = S.CODPARC
         WHERE S.ID_CARGA = '&ID_CARGA'
           AND REGEXP_REPLACE(P.CGC_CPF, '[^0-9]', '') <> S.CNPJ
        UNION ALL
        SELECT 'PARCEIRO', TO_CHAR(S.CODPARC), 'Parceiro ja possui perfil'
          FROM STG_PPC_PARCEIRO S
          JOIN TGFPAR P ON P.CODPARC = S.CODPARC
         WHERE S.ID_CARGA = '&ID_CARGA'
           AND NVL(P.CODTIPPARC, 0) <> 0
        UNION ALL
        SELECT 'PARCEIRO', TO_CHAR(S.CODPARC), 'Perfil de destino inexistente ou nao aprovado para criacao'
          FROM STG_PPC_PARCEIRO S
         WHERE S.ID_CARGA = '&ID_CARGA'
           AND NOT EXISTS (
                 SELECT 1 FROM TGFTPP T WHERE T.CODTIPPARC = S.CODTIPPARC_SUGERIDO
                 UNION ALL
                 SELECT 1 FROM STG_PPC_PERFIL N
                  WHERE N.ID_CARGA = S.ID_CARGA
                    AND N.CODTIPPARC = S.CODTIPPARC_SUGERIDO
                    AND N.STATUS_VALIDACAO = 'APROVADO'
               )
        UNION ALL
        SELECT 'PERFIL', TO_CHAR(N.CODTIPPARC), 'Codigo ja existe com outra descricao'
          FROM STG_PPC_PERFIL N
          JOIN TGFTPP T ON T.CODTIPPARC = N.CODTIPPARC
         WHERE N.ID_CARGA = '&ID_CARGA'
           AND UPPER(TRIM(T.DESCRTIPPARC)) <> UPPER(TRIM(N.DESCRTIPPARC))
       )
 ORDER BY TIPO, CHAVE;

PROMPT === RESUMO DA SIMULACAO ===

SELECT STATUS_VALIDACAO, CONFIANCA, CODTIPPARC_SUGERIDO, COUNT(*) AS QTD
  FROM STG_PPC_PARCEIRO
 WHERE ID_CARGA = '&ID_CARGA'
 GROUP BY STATUS_VALIDACAO, CONFIANCA, CODTIPPARC_SUGERIDO
 ORDER BY STATUS_VALIDACAO, CONFIANCA, CODTIPPARC_SUGERIDO;

PROMPT === DML PREVISTO PARA CONFERENCIA ===

SELECT 'UPDATE TGFPAR SET CODTIPPARC = ' || TO_CHAR(S.CODTIPPARC_SUGERIDO) ||
       ' WHERE CODPARC = ' || TO_CHAR(S.CODPARC) ||
       ' AND NVL(CODTIPPARC,0) = 0;' AS DML_PREVISTO
  FROM STG_PPC_PARCEIRO S
 WHERE S.ID_CARGA = '&ID_CARGA'
   AND S.STATUS_VALIDACAO = 'APROVADO'
 ORDER BY S.CODPARC;

