-- Reverte uma execucao concluida por ID_EXECUCAO.

SET SERVEROUTPUT ON SIZE UNLIMITED;
SET DEFINE ON;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

ACCEPT ID_EXECUCAO CHAR PROMPT 'Informe o ID_EXECUCAO a reverter: '
ACCEPT CONFIRMACAO CHAR PROMPT 'Digite REVERTER PERFIS CNAE para continuar: '

DECLARE
  c_id_execucao CONSTANT VARCHAR2(30) := '&ID_EXECUCAO';
  c_confirmacao CONSTANT VARCHAR2(40) := '&CONFIRMACAO';
  v_restaurados PLS_INTEGER := 0;
  v_removidos   PLS_INTEGER := 0;
  v_refs        PLS_INTEGER;
BEGIN
  SAVEPOINT PPC_REVERTE_INICIO;

  IF c_confirmacao <> 'REVERTER PERFIS CNAE' THEN
    RAISE_APPLICATION_ERROR(-20110, 'Confirmacao invalida. Nenhuma alteracao realizada.');
  END IF;

  MERGE INTO TGFPAR P
  USING (
      SELECT B.CODPARC, B.CODTIPPARC_ANTES, B.CODTIPPARC_DEPOIS
        FROM BKP_PPC_TGFPAR B
       WHERE B.ID_EXECUCAO = c_id_execucao
  ) B
     ON (P.CODPARC = B.CODPARC)
   WHEN MATCHED THEN UPDATE
        SET P.CODTIPPARC = B.CODTIPPARC_ANTES
      WHERE P.CODTIPPARC = B.CODTIPPARC_DEPOIS;
  v_restaurados := SQL%ROWCOUNT;

  FOR R IN (
      SELECT B.CODTIPPARC, B.GRAU
        FROM BKP_PPC_TGFTPP B
       WHERE B.ID_EXECUCAO = c_id_execucao
       ORDER BY B.GRAU DESC, B.CODTIPPARC DESC
  ) LOOP
    SELECT (SELECT COUNT(*) FROM TGFPAR P WHERE P.CODTIPPARC = R.CODTIPPARC) +
           (SELECT COUNT(*) FROM TGFTPP F WHERE F.CODTIPPARCPAI = R.CODTIPPARC)
      INTO v_refs
      FROM DUAL;

    IF v_refs > 0 THEN
      RAISE_APPLICATION_ERROR(-20111,
        'Perfil ' || R.CODTIPPARC || ' ainda possui referencias e nao pode ser removido.');
    END IF;

    DELETE FROM TGFTPP WHERE CODTIPPARC = R.CODTIPPARC;
    v_removidos := v_removidos + SQL%ROWCOUNT;
  END LOOP;

  COMMIT;
  DBMS_OUTPUT.PUT_LINE('PARCEIROS_RESTAURADOS=' || v_restaurados);
  DBMS_OUTPUT.PUT_LINE('PERFIS_REMOVIDOS=' || v_removidos);
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK TO PPC_REVERTE_INICIO;
    DBMS_OUTPUT.PUT_LINE('ERRO=' || SQLERRM);
    RAISE;
END;
/
