 INSERT INTO TGFNUM (ARQUIVO, CODEMP, SERIE, NOMEARQ, AUTOMATICO, ULTCOD, TIPOIMPRESSORA, IMPNOTA, TOTITENSNOTA,
                     TOTSERVNOTA, ULTNOTATALAO, MODNOTAFIS, QTDAVISO, CODMAQ, CODMODDOC, DIASAVISO, DTVAL) 
  SELECT DISTINCT 
         'SEMNUM'       AS ARQUIVO,
         C.CODEMP,
         C.SERIENOTA    AS SERIE, 
         NULL           AS NOMEARQ,
         'N'            AS AUTOMATICO,
         0              AS ULTCOD,
         1              AS TIPOIMPRESSORA,
         NULL           AS IMPNOTA,
         NULL           AS TOTITENSNOTA,
         NULL           AS TOTSERVNOTA,
         999999999      AS ULTNOTATALAO,
         NULL           AS MODNOTAFIS,
         0              AS QTDAVISO,
         NULL           AS CODMAQ,
         0              AS CODMODDOC,
         NULL           AS DIASAVISO,
         NULL           AS DTVAL
    FROM TGFCAB C
   WHERE C.TIPMOV = 'C'
     AND NOT EXISTS (SELECT 1 FROM TGFNUM WHERE ARQUIVO = 'SEMNUM' 
                                            AND  CODEMP = C.CODEMP 
                                            AND SERIE = C.SERIENOTA 
                                            AND CODMODDOC = 0);


-- INSERT DE CONTROLE DE NUMERACAO PARA PEDIDOS PARA TODAS AS EMPRESAS FALTANTES
 INSERT INTO TGFNUM (ARQUIVO, CODEMP, SERIE, NOMEARQ, AUTOMATICO, ULTCOD, TIPOIMPRESSORA, IMPNOTA, TOTITENSNOTA,
                     TOTSERVNOTA, ULTNOTATALAO, MODNOTAFIS, QTDAVISO, CODMAQ, CODMODDOC, DIASAVISO, DTVAL) 
SELECT NRO.ARQUIVO,
       EMP.CODEMP,
       NRO.SERIE,
       NOMEARQ,
       NRO.AUTOMATICO,
       NRO.ULTCOD,
       NRO.TIPOIMPRESSORA,
       NRO.IMPNOTA,
       NRO.TOTITENSNOTA,
       NRO.TOTSERVNOTA,
       NRO.ULTNOTATALAO,
       NRO.MODNOTAFIS,
       NRO.QTDAVISO,
       NRO.CODMAQ,
       NRO.CODMODDOC,
       NRO.DIASAVISO,
       NRO.DTVAL
FROM TGFNUM NRO
JOIN TSIEMP EMP ON EMP.CODEMP <> NRO.CODEMP
WHERE NRO.ARQUIVO = 'PEDVEN';