ALTER TRIGGER TRG_UPD_TGFCAB DISABLE;

UPDATE TGFCAB C
   SET C.CODTIPOPER = (CASE WHEN C.CODTIPOPER = 1101 THEN 1116 
                            WHEN C.CODTIPOPER = 1201 THEN 1216 
                            WHEN C.CODTIPOPER = 1401 THEN 1494 
                            ELSE NULL 
                        END),
       C.DHTIPOPER  = (CASE WHEN C.CODTIPOPER = 1101 THEN (SELECT MIN(DHALTER) FROM TGFTOP WHERE CODTIPOPER = 1116) 
                            WHEN C.CODTIPOPER = 1201 THEN (SELECT MIN(DHALTER) FROM TGFTOP WHERE CODTIPOPER = 1216) 
                            WHEN C.CODTIPOPER = 1401 THEN (SELECT MIN(DHALTER) FROM TGFTOP WHERE CODTIPOPER = 1494) 
                            ELSE NULL 
                        END)
 WHERE NOT EXISTS (SELECT 1 FROM TGFFIN WHERE NUNOTA = C.NUNOTA)
   --AND C.NUNOTA IN (616)
   AND (UPPER(C.OBSERVACAO) LIKE '%COMPLEMENT%' OR UPPER(C.OBSERVACAO) LIKE '%CORREC%O%')
   AND C.VLRNOTA = 0
   AND C.CODTIPOPER IN (1101);

ALTER TRIGGER TRG_UPD_TGFCAB ENABLE;

-- IDENTIFICAR SE XML TEM TAG vDup
--SELECT C.NUNOTA, C.TIPMOV, C.CODTIPOPER, C.VLRNOTA, C.CHAVENFE, FNC_BUSCA_TAG_XML_GERAL (C.NUNOTA, 'vDup', 'dup') AS XML
--FROM TGFCAB C
--JOIN TGFTOP T ON T.CODTIPOPER = C.CODTIPOPER AND 
--                 T.DHALTER = C.DHTIPOPER AND 
--                 ABS(T.ATUALFIN) = 1 AND 
--                 T.TIPATUALFIN = 'I'
--WHERE C.TIPMOV <> 'Z'
--AND NOT EXISTS (SELECT 1 FROM TGFFIN WHERE NUNOTA = C.NUNOTA)
--ORDER BY 6;



--REM INSERTING into TGFTOP 1216
--SET DEFINE OFF;
--Insert into TGFTOP (CODTIPOPER,DHALTER,DESCROPER,TIPMOV,ATUALFIN,TIPATUALFIN,ATUALCOM,ATUALEST,PRECIFICA,CALCICMS,BASENUMERACAO,TIPONUMERACAO,TRAVAFIMIMP,EMITENOTA,VALIDADATA,NUMSOMAUT,DENTROESTADO,ATUALLIVFIS,TIPICMS,CODCFO_ENTRADA,CODCFO_SAIDA,CODCFO_ENTRADA_FORA,CODCFO_SAIDA_FORA,CODTRIB,TIPIPI,ARMAZENAGEM,ATUALCTB,ATIVO,ATUALIZARATEIO,PENDENTE,IMPNOTAADICIONAL,EMITEBOLETA,VALNUM,EXIGETRANSP,ALTNFCONF,CODMODNF,USARPRECOCUSTO,VENDITE,EXECITE,ATUALLIVISS,EXPTES,EXPGRS,CUPOMFISCAL,ATUALESTMP,EXIGECOTACAO,EXPORTA,SOMASUBST,CALCDIFICMS,CODTIPOPERDESTINO,TEMIPI,TEMICMS,TEMPIS,TEMCOFINS,EXIGECONF,ATUALPRECOFAT,VALIDAATRASO,VALIDAAGRUPMIN,CODUSU,COMPLEMENTO,TEMCSL,CODMODDOC,EXIGELIB,ATUALBEM,INFCONTRATO,ADIARATUALEST,CODTIPOPERSEPARACAO,USOPRODSEPARACAO,IPIPROPFRETE,IPIPROPSEG,IPIPROPDESTAQUE,IPIPROPEMBALAGEM,IPIPROPJURO,ICMSPROPFRETE,ICMSPROPSEG,ICMSPROPDESTAQUE,ICMSPROPEMBALAGEM,ICMSPROPJURO,STPROPFRETE,STPROPSEG,STPROPDESTAQUE,STPROPEMBALAGEM,STPROPJURO,RATAUTPROD,TIPIVASUBST,GOLSINAL,CONSIGNACAO,BONIFICACAO,STPROPFRETEEXT,VLRBASEPGTO,VLRMINAP,PRODREP,GOLMPSINAL,GOLDEV,SOMARIPI,EXIGELAUDO,VALIDAMEDIANEGOC,TEMFUNRURAL,IMPNAOCONF,IPIINCICMS,CLASSIFICMS,OC,TIPFATSERV,TEMIRF,BASEICMSFRETECALCST,FATESTCONF,SOLCOMPRA,EDITANALISERENTAB,EXIGEGAR,USARCONFCEGA,EXIGEDTVAL,EXIGEPEDFRET,PEDFRETE,ATUALCOMOS,CODMODDOCISS,CODCFPS,OBTERVLRMOEDAFAT,EXIGANALITENS,ATUALESTTERC,TEMISS,BUSCMPTERC,CODCFO_TERC,ATUALFINTERC,ATUALULTIMACOMP,ATUALULTIMAVEND,ANALISEGIRO,GERAGNRE,ATUALACDC,IPIEMBUT,UTILIZAWMS,NFE,CSTIPIENT,CSTIPISAI,PODEFIXAR,PODETRANSFENT,REFNFE,VALEST,INTEGSERCON,EXIGELIBSEMPRE,ENVIARWMSCONF,TIPATUALWMS,EXIGEAGENDAWMS,ATUALDATRECWMS,TEMFINORIGEM,AUTDIGITAL,CODMODDAD,MPNUMAUTLOTE,NULAYOUT,SOMARPISST,SOMARCOFINSST,PISPROPFRETE,PISPROPSEG,PISPROPDESTAQUE,PISPROPEMBALAGEM,PISPROPJURO,PISSTPROPFRETE,PISSTPROPSEG,PISSTPROPDESTAQUE,PISSTPROPEMBALAGEM,PISSTPROPJURO,COFINSPROPFRETE,COFINSPROPSEG,COFINSPROPDESTAQUE,COFINSPROPEMBALAGEM,COFINSPROPJURO,COFINSSTPROPFRETE,COFINSSTPROPSEG,COFINSSTPROPDESTAQUE,COFINSSTPROPEMBALAGEM,COFINSSTPROPJURO,ATUALTRANSG,VDADIRCONSUM,PODEPESAGEM,EMPFUNCDIF,FATENTPROD,DIGINFIMPORTA,NFESEMDTENTSAI,ATUALINDENIZ,TEMREAICMS,AVISARCOMP,GERARTAGJNFE,CONTLAUDOSINT,CODMODNFSE,CODMODRPS,NFSE,CODNATOPERISS,CONFIMPOSTO,CONFCFOP,NFSEPORNAT,CODTIPOPERPENRET,CODTIPOPERDENEG,COPIARLIBER,NAOINCCONF,PESAITEM,CAMINHOEDI,CODREMEDI,CODTIPOPERREM,GERARPARCDEST,NUNOTAMODELO,PROVISENTREGA,TEMII,DIGPUREZA,LAUDOITEM,TIPOIMPKIT,TRANSFWMS,TIPMOVBEMSPED,PODEAJUSTARORIGPRODWMS,TEMVAVTCON,STATUSLOTE,STATUSBAIXAEST,BLOQESTVENC,VALVCTLAUDOEST,GRUPO,GERABONPRE,FATCONTPORPESO,TEMINDEX,NATOPERSPED,VALTOTNOTAGERLIV,IMPETIQCONFIR,TIPCALCEAN13,MODETQIMPCAF,ENVGARANTIA,VALTIPNEGOCCONF,NATBCCRED,INDNATFRT,LIGORIGORIG,VALTBCOMPCR,VALCST,VALPRZMEDCPA,DIASTOLPRZMED,QTDPENDCALC,QTDPENDVAL,PERCTOLVARQTD,USACUSMEDBASEST,SUGERELOCALPARC,EMITELAUDOLOTE,SEPBALCAO,ATUALTRANSPNFOC,VALORICMSFRETECALCST,USAALIQNATRATF100,GERAPLANPROD,COPIADTPREVORIG,AGRUPASERVFAT,GERARTRANSF,RESERVASEMLOTE,AGRUPAPRODNFE,MARCARNAOPENDENTE,GERAAMOSTRALAUDO,EMITEREGVOL,PARTICIPACALCFRETE,INTEGRAEVENTO,TRANSFCBGLOBAL,REMESSAFUTURA,PRODUETLOC,CODCFO_COMBUST_LUBRIF,ACEITAFATACIMA,TIPALTDTVENC,DESCPROMQTDGDP,REGLOGIMPRESSAO,NUCCO,EXIGRECAGRO,CODTIPOPERPRODUZAUT,VALESTMAXIMO,GERAR1400SPED,NFEESTORNO,VALVARIACVLRUNIT,PARTAUTEMBARQ,EXIGECALCFRETE,GRAHISALTPED,ALTITEMPARCFAT,GERAENDENTRNFE,DESCQTDGRUDESCPRO,VALSITCADSEFAZ,CAMGEREDICONF,CAT1799SPCCO,PERMCONFPARCIALWMS,ENVWMSCONFIRMADA,PERCMINBASEINSS,INDPRESNFCE,AJUSTAVP,CODMOEDAVP,TOPBACKORDER,TOPATENDIMENTO,CONFVALEVENT58,CONFVALEVENT68,PERCTOLVARVLRUNIT,HABSUGVEND,OPERCOMMOEDA,CTE,TIPSERVCTE,CODTOPDENEGCTE,TIPOCTE,APLICLEITRANSP,VALIDARUNMIN,VALEVENTO71,ARREDQTDUNALT,CODENQIPIENT,CODENQIPISAI,USATABALTEMP,PERMFINMENORVLRNOTA,FATFORAPLANENT,CALCDIFALPART,NATEFDCONTM410M810,CALCICMSCOMPL,INDTERC,EXIGECONFIRMACAOMDE,DESCREMAIL,MOVENDFLUTUANTE,DESCONNFSE,USASERVTABIRFINSS,APLICTABIRFINSS,FORMRECISS,ORCAMENTO,NUFOP,SIMULACAUTOFRETE,DISTSTVLRUNITFAT,ICMSORIGESTPED,CALCPESOCONFIRM,CALCFCPINT,CONSAUXILIAR,INDTIPREC,EXIGEANALISECRED,CODCTACTBEFD,IGNORARAGRUPMINDEV,TIPMODALCTE,USARECPARCIAL,GERADEMANDAMPS,VALSITCADRF,SEMMOEDAFIN,VLRLIQITEMNFE,CONSVLRREMRETIND,SALVARCONFSEMPERG,GERCORAPON,SEMCREDIPIST,REDICMSBCPISCONFINS,DEVSEMDESTAQUEST,DEVSEMDESTAQUEIPI,DATARETROFAT,ESTOQUEMPTERCEIRO,REDPISBCPISCOFINS,IGNORACOMPLITEM,PERMITECNAEDIFNOTA,CODMODRO,OUTDESPSTEXTNOTA,CODLOCALIMPXML,CODCONTARURAL,DESCONSLCDPR,IMPXMLMANTDESPACES,IGNOBSORIGREM,OPERACAOAMOSTRA,DESCONSIDNFEORIGEM,ATUALESTWMSTERC,ARMTIPAPU,DESCONSIDPEDXML,TROCADEPOSITANTE,DEDFCPBCPISCOFINS,CONFVLREVENT68,CALCPISCFSFIN,CODINTERM,INTERMED,CALCSTFRTXTNOTPROP,TIPCOMPLCUST,DESTOPADRCST1400,CALCFUSTTOP,CALCFUNTTELTOP,IGNORAMPPVPA,TOPPISCOFREDAQUIS,NULAYOUTCVR,CONFCOMPCRED,TOPAPI,CODMODCFECANC,REDSTBCPISCOFINS,CONSTOPAPURSIMP,IGNEXPAUTLOT,NUMPROCESSO,PERMDESTVBATPREBCUS,GERINFOEFDPAG,CONSNFERELCANCEFD,RECBRUTACIAP,CALCICMSREGTTS,VALDISPESTDEV,AD_LOTECTB,CALCFETHAB,ATUSALDOCONT,DESCCSTBCPISCF,USAVENDAMAIS,PERMTRANSGALPAO,NFCOM,TIPOEMISSAONFCOM,TIPOEMISSAO,OPERESSACOMP,TPNFDEB,TPNFCRED,CONSDISBAIXEST,TEMIBS,TEMCBS,TEMIBSCBSMONO,TEMIS,TPOPERGOV) 
--values ('1216',to_date('23/10/25','DD/MM/RR'),'DEV. VENDA - COMPLEMENTAR NF-E','D','0','I','N','N','N','B','V','S','N','S','N','S','A','E','1','0','5102','0','6102',null,'3',null,'N','N','N','N','N','S','N','N','N',null,'P','N','N','N','N','0','N','0','N','N','S','N','0','S','S','S','S','N','N','N','S','0','S','N','55','N','N','O','N','0',' ','N','N','N','N','N','N','N','S','N','S','N','N','N','N','N','N',null,'0','N','N','N','0','0',null,'0','1','S','N','N','N','N','A','A','A','N','N','N','N','N','N','N','N','N','N','N','N',null,'0','N','N','N','N','N','0','N','N','N','0','N','N','N','N','C','49','99','N','N','S','S','N','N','N','E','N','N','N','N',null,'N',null,'S','S','N','N','N','N','N','N','N','N','N','S','N','N','N','N','N','N','N','N','N','S','0',null,'N','N','N','N','N','0','N','N','N','N',null,null,'M',null,'N','N','N','0','0','S','N','N',null,null,'0','N',null,'N','N','N','N','K','O',null,'N','N','N','N','N','N','Vendas','N','N','N','NFE COMPLEMENTAR','S','N','N',null,'N','N',null,null,'N','N','N','N',null,'N','N',null,'N','N','N','N','N','S','N','N','N',null,'N','N','N','N','N','N','S','N','N','N','N','0','N','R','N','N',null,'N',null,'N','N','N','N','N','N','N','N','N','N','N',null,'-1','N','P',null,'0','N',null,null,null,'0','0',null,'N','N',null,null,null,null,'P','N','N','N',null,null,null,'N','N','N',null,'N','N',null,null,'N','N','N','N',null,null,null,null,'N',null,'N','N',null,'0',null,null,'N',null,'N','N','N','N',null,null,'N',null,null,null,null,null,null,'N',null,null,null,null,'N',null,null,null,'N',null,null,null,'N',null,null,'S',null,null,null,null,null,null,null,null,null,null,null,null,null,null,'N',null,null,'N','N',null,'N',null,'N',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,'N',null,null,null,null,null);
--


--UPDATE TGFCAB C
--SET C.STATUSNFE = 'R'
----WHERE C.CODTIPOPER = 1101
--WHERE NUNOTA IN (90381,
--31672,
--53492);
----AND NOT EXISTS (SELECT 1 FROM TGFFIN WHERE NUNOTA = C.NUNOTA);


--UPDATE TGFCAB C
--SET C.STATUSNFE = 'A'
--WHERE C.STATUSNFE = 'R'
--AND C.CODTIPOPER = 1101;
--
--
--SELECT *
--FROM TGFCAB C
--WHERE C.CODTIPOPER = 1101
--AND NOT EXISTS (SELECT 1 FROM TGFFIN WHERE NUNOTA = C.NUNOTA);