-- Rollback das atividades 29/30 R03 - CASA DAS ESSENCIAS.
-- Restaura pais excluidos a partir dos backups e referencias a partir da auditoria.
-- Executar somente com decisao de reversao e identidade Oracle confirmada.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

DECLARE
  v_id VARCHAR2(50) := 'RMD_CASA_2930_MRG_20260923_R03';
  v_sql VARCHAR2(32767);
  v_del_count NUMBER;
  v_rest_pais NUMBER;
  v_rest_refs NUMBER := 0;
BEGIN
  EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM RMD_CASA_2930_R03_DEL WHERE ID_EXECUCAO=:1' INTO v_del_count USING v_id;
  IF v_del_count=0 THEN
    RAISE_APPLICATION_ERROR(-20410,'Auditoria de exclusao R03 vazia; rollback nao iniciado.');
  END IF;

  EXECUTE IMMEDIATE 'INSERT INTO TSIBAI (CODBAI,NOMEBAI,CODREG,DTALTER,DESCRICAOCORREIO,NUVERSAO,ATUNUVERSAO) '||
    'SELECT b.CODBAI,b.NOMEBAI,b.CODREG,b.DTALTER,b.DESCRICAOCORREIO,b.NUVERSAO,b.ATUNUVERSAO '||
    'FROM RMD_CASA_2930_R03_BAI_BKP b WHERE b.ID_EXECUCAO=:1 AND EXISTS ('||
    'SELECT 1 FROM RMD_CASA_2930_R03_MAP m WHERE m.ID_EXECUCAO=:1 AND m.TIPO=''BAI'' AND m.COD_OBSOLETO=b.CODBAI) '||
    'AND NOT EXISTS (SELECT 1 FROM TSIBAI x WHERE x.CODBAI=b.CODBAI)' USING v_id,v_id;
  v_rest_pais := SQL%ROWCOUNT;
  EXECUTE IMMEDIATE 'INSERT INTO TSIEND (CODEND,NOMEEND,TIPO,DTALTER,DESCRICAOCORREIO,CODLOGRADOURO,NUVERSAO,ATUNUVERSAO) '||
    'SELECT b.CODEND,b.NOMEEND,b.TIPO,b.DTALTER,b.DESCRICAOCORREIO,b.CODLOGRADOURO,b.NUVERSAO,b.ATUNUVERSAO '||
    'FROM RMD_CASA_2930_R03_END_BKP b WHERE b.ID_EXECUCAO=:1 AND EXISTS ('||
    'SELECT 1 FROM RMD_CASA_2930_R03_MAP m WHERE m.ID_EXECUCAO=:1 AND m.TIPO=''END'' AND m.COD_OBSOLETO=b.CODEND) '||
    'AND NOT EXISTS (SELECT 1 FROM TSIEND x WHERE x.CODEND=b.CODEND)' USING v_id,v_id;
  v_rest_pais := v_rest_pais + SQL%ROWCOUNT;

  FOR r IN (
    SELECT TABLE_NAME,COLUMN_NAME,RID,OLD_VALUE,NEW_VALUE
      FROM RMD_CASA_2930_R03_DEP
     WHERE ID_EXECUCAO=v_id
     ORDER BY TABLE_NAME,COLUMN_NAME,RID
  ) LOOP
    v_sql := 'UPDATE '||r.TABLE_NAME||' SET '||r.COLUMN_NAME||'=:1 WHERE ROWID=CHARTOROWID(:2) AND '||r.COLUMN_NAME||'=:3';
    EXECUTE IMMEDIATE v_sql USING r.OLD_VALUE,r.RID,r.NEW_VALUE;
    v_rest_refs := v_rest_refs + SQL%ROWCOUNT;
  END LOOP;

  DBMS_OUTPUT.PUT_LINE('ID_EXECUCAO='||v_id);
  DBMS_OUTPUT.PUT_LINE('PAIS_RESTAURADOS='||v_rest_pais||'; REFERENCIAS_RESTAURADAS='||v_rest_refs);
  DBMS_OUTPUT.PUT_LINE('STATUS=ROLLBACK_29_30_R03_CONCLUIDO');
  COMMIT;
EXCEPTION WHEN OTHERS THEN
  ROLLBACK;
  RAISE;
END;
/
