-- Bloco 01_Liberar_Filtros_Portais; backup por execucao e atualizacao apenas de divergencias.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
DECLARE v NUMBER; BEGIN
 SELECT COUNT(*) INTO v FROM ALL_TABLES WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND TABLE_NAME='BKP_RMD_01_TSIPAR';
 IF v=0 THEN EXECUTE IMMEDIATE q'[CREATE TABLE BKP_RMD_01_TSIPAR AS
 SELECT CAST(NULL AS VARCHAR2(30)) ID_EXECUCAO, CAST(NULL AS TIMESTAMP) DH_EXECUCAO,
 CAST(NULL AS VARCHAR2(128)) USUARIO_EXECUCAO, CAST(NULL AS VARCHAR2(30)) ROWID_ORIGINAL,
 T.INTEIRO VALOR_ANTES, CAST(NULL AS NUMBER) VALOR_DEPOIS FROM TSIPAR T WHERE 1=0]'; END IF;
END;
/
DECLARE
 v_id VARCHAR2(30):='RMD_PORT_'||TO_CHAR(SYSTIMESTAMP,'YYYYMMDDHH24MISSFF3');
 v_b PLS_INTEGER; v_u PLS_INTEGER;
BEGIN
 INSERT INTO BKP_RMD_01_TSIPAR
 SELECT v_id,SYSTIMESTAMP,SYS_CONTEXT('USERENV','SESSION_USER'),ROWIDTOCHAR(ROWID),INTEIRO,CAST(NULL AS NUMBER)
 FROM TSIPAR WHERE CHAVE IN ('MAXDIASPORTAIS','MAXDIASPORTVEND','MAXDIASPORTCOMP','MAXDIASMOVFIN') AND INTEIRO IS NOT NULL;
 v_b:=SQL%ROWCOUNT;
 UPDATE TSIPAR SET INTEIRO=NULL WHERE CHAVE IN ('MAXDIASPORTAIS','MAXDIASPORTVEND','MAXDIASPORTCOMP','MAXDIASMOVFIN') AND INTEIRO IS NOT NULL;
 v_u:=SQL%ROWCOUNT;
 IF v_b<>v_u THEN RAISE_APPLICATION_ERROR(-20201,'Backup e atualizacao divergiram em 01_Liberar_Filtros_Portais.'); END IF;
 COMMIT;
 DBMS_OUTPUT.PUT_LINE('ID_EXECUCAO='||v_id);
 DBMS_OUTPUT.PUT_LINE('REGISTROS_ALTERADOS='||v_u);
EXCEPTION WHEN OTHERS THEN ROLLBACK; RAISE;
END;
/

