-- Executa somente quando AD_SEGMENTACAOEMPRESAS existe no CURRENT_SCHEMA.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
DECLARE
 v_tab NUMBER;v_id VARCHAR2(30):='RMD_RUPE_'||TO_CHAR(SYSTIMESTAMP,'YYYYMMDDHH24MISSFF3');
 v_b PLS_INTEGER;v_u PLS_INTEGER;
BEGIN
 SELECT COUNT(*) INTO v_tab FROM ALL_TABLES WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND TABLE_NAME='AD_SEGMENTACAOEMPRESAS';
 IF v_tab=0 THEN DBMS_OUTPUT.PUT_LINE('BLOCO_IGNORADO=AD_SEGMENTACAOEMPRESAS inexistente');RETURN;END IF;
 BEGIN
  EXECUTE IMMEDIATE q'[CREATE TABLE BKP_RMD_11_TGFEMP AS SELECT CAST(NULL AS VARCHAR2(30)) ID_EXECUCAO,
  CAST(NULL AS TIMESTAMP) DH_EXECUCAO,CAST(NULL AS VARCHAR2(128)) USUARIO_EXECUCAO,
  CAST(NULL AS VARCHAR2(30)) ROWID_ORIGINAL,E.RUPTURAEST RUPTURAEST_ANTES FROM TGFEMP E WHERE 1=0]';
 EXCEPTION WHEN OTHERS THEN
  IF SQLCODE <> -955 THEN RAISE; END IF;
 END;
 INSERT INTO BKP_RMD_11_TGFEMP
 SELECT v_id,SYSTIMESTAMP,SYS_CONTEXT('USERENV','SESSION_USER'),
 ROWIDTOCHAR(E.ROWID),E.RUPTURAEST FROM TGFEMP E WHERE NVL(E.RUPTURAEST,'N')<>'S' AND EXISTS(
 SELECT 1 FROM AD_SEGMENTACAOEMPRESAS S JOIN TSIEMP T ON T.CGC=S.CGC WHERE S.SEGMENTACAO<>'S' AND T.CODEMP=E.CODEMP);
 v_b:=SQL%ROWCOUNT;
 UPDATE TGFEMP E SET E.RUPTURAEST='S' WHERE NVL(E.RUPTURAEST,'N')<>'S' AND EXISTS(
 SELECT 1 FROM AD_SEGMENTACAOEMPRESAS S JOIN TSIEMP T ON T.CGC=S.CGC WHERE S.SEGMENTACAO<>'S' AND T.CODEMP=E.CODEMP);
 v_u:=SQL%ROWCOUNT;
 IF v_b<>v_u THEN RAISE_APPLICATION_ERROR(-20230,'Backup e atualizacao de empresas divergiram.');END IF;
 COMMIT;DBMS_OUTPUT.PUT_LINE('ID_EXECUCAO='||v_id);DBMS_OUTPUT.PUT_LINE('EMPRESAS_ALTERADAS='||v_u);
EXCEPTION WHEN OTHERS THEN ROLLBACK;RAISE;END;
/
