-- Bloco 12. Mantem a regra funcional aprovada com snapshot das linhas.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
DECLARE v NUMBER; BEGIN
 SELECT COUNT(*) INTO v FROM ALL_TABLES WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND TABLE_NAME='BKP_RMD_12_TGFTOP';
 IF v=0 THEN EXECUTE IMMEDIATE q'[CREATE TABLE BKP_RMD_12_TGFTOP AS SELECT CAST(NULL AS VARCHAR2(30)) ID_EXECUCAO,
 CAST(NULL AS TIMESTAMP) DH_EXECUCAO, CAST(NULL AS VARCHAR2(128)) USUARIO_EXECUCAO,
 CAST(NULL AS VARCHAR2(30)) ROWID_ORIGINAL, T.GOLSINAL GOLSINAL_ANTES, T.GOLMPSINAL GOLMPSINAL_ANTES, T.GOLDEV GOLDEV_ANTES, T.ANALISEGIRO ANALISEGIRO_ANTES, T.ATUALULTIMAVEND ATUALULTIMAVEND_ANTES, T.ATUALULTIMACOMP ATUALULTIMACOMP_ANTES FROM TGFTOP T WHERE 1=0]'; END IF;
END;
/
DECLARE v_id VARCHAR2(30):='RMD_TOPG_'||TO_CHAR(SYSTIMESTAMP,'YYYYMMDDHH24MISSFF3'); v_b PLS_INTEGER; v_u PLS_INTEGER;
BEGIN
 INSERT INTO BKP_RMD_12_TGFTOP
 (ID_EXECUCAO,DH_EXECUCAO,USUARIO_EXECUCAO,ROWID_ORIGINAL,
  GOLSINAL_ANTES,GOLMPSINAL_ANTES,GOLDEV_ANTES,ANALISEGIRO_ANTES,
  ATUALULTIMAVEND_ANTES,ATUALULTIMACOMP_ANTES)
 SELECT v_id,SYSTIMESTAMP,SYS_CONTEXT('USERENV','SESSION_USER'),ROWIDTOCHAR(ROWID),
        GOLSINAL,GOLMPSINAL,GOLDEV,ANALISEGIRO,ATUALULTIMAVEND,ATUALULTIMACOMP
 FROM TGFTOP WHERE 1=1;
 v_b:=SQL%ROWCOUNT;
 UPDATE TGFTOP SET GOLSINAL=CASE WHEN ATUALEST='B' AND TIPMOV='V' AND ATUALFIN=1 AND TIPATUALFIN='I' AND CODMODDOC IN (55,59,65) THEN -1 WHEN ATUALEST='E' AND TIPMOV='D' AND ATUALFIN=-1 AND TIPATUALFIN='I' AND CODMODDOC IN (55,59,65) THEN -1 WHEN ATUALEST='E' AND TIPMOV='C' AND ATUALFIN=-1 AND TIPATUALFIN='I' AND CODMODDOC IN (55,59,65) THEN 1 WHEN ATUALEST='B' AND TIPMOV='E' AND ATUALFIN=1 AND TIPATUALFIN='I' AND CODMODDOC IN (55,59,65) THEN 1 ELSE 0 END,
 GOLMPSINAL=CASE WHEN ATUALEST='B' AND TIPMOV='V' AND ATUALFIN=1 AND TIPATUALFIN='I' AND CODMODDOC IN (55,59,65) THEN -1 WHEN ATUALEST='E' AND TIPMOV='D' AND ATUALFIN=-1 AND TIPATUALFIN='I' AND CODMODDOC IN (55,59,65) THEN -1 WHEN ATUALEST='E' AND TIPMOV='C' AND ATUALFIN=-1 AND TIPATUALFIN='I' AND CODMODDOC IN (55,59,65) THEN 1 WHEN ATUALEST='B' AND TIPMOV='E' AND ATUALFIN=1 AND TIPATUALFIN='I' AND CODMODDOC IN (55,59,65) THEN 1 ELSE 0 END,
 GOLDEV=CASE WHEN TIPMOV IN ('D','E') AND ATUALEST IN ('E','B') AND CODMODDOC IN (55,59,65) AND (ATUALFIN<>0 OR TIPATUALFIN<>'P') THEN -1 ELSE 1 END,
 ANALISEGIRO=CASE WHEN TIPMOV='V' AND ATUALEST='B' AND ATUALFIN=1 AND TIPATUALFIN='I' AND CODMODDOC IN (55,59,65) THEN -1 WHEN TIPMOV='D' AND ATUALEST='E' AND ATUALFIN=-1 AND TIPATUALFIN='I' AND CODMODDOC IN (55,59,65) THEN 1 ELSE 0 END,
 ATUALULTIMAVEND=CASE WHEN TIPMOV='V' AND ATUALEST='B' AND ATUALFIN=1 AND TIPATUALFIN='I' AND CODMODDOC IN (55,59,65) THEN 'G' ELSE 'N' END,
 ATUALULTIMACOMP=CASE WHEN TIPMOV='C' AND ATUALEST='E' AND ATUALFIN=-1 AND TIPATUALFIN='I' AND CODMODDOC IN (55,59,65) THEN 'E' ELSE 'N' END WHERE 1=1;
 v_u:=SQL%ROWCOUNT;
 IF v_b<>v_u THEN RAISE_APPLICATION_ERROR(-20210,'Backup e atualizacao divergiram em Configurar_TOPs_Giro_GOL.'); END IF;
 COMMIT; DBMS_OUTPUT.PUT_LINE('ID_EXECUCAO='||v_id); DBMS_OUTPUT.PUT_LINE('REGISTROS_ALTERADOS='||v_u);
 DBMS_OUTPUT.PUT_LINE('AVISO=Mapeamento de TOPs possui cobertura parcial aprovada.');
EXCEPTION WHEN OTHERS THEN ROLLBACK; RAISE; END;
/
