-- Define CODPARCMATRIZ pela raiz do CNPJ e o proprio parceiro para pessoa fisica.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET SQLBLANKLINES ON
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

DECLARE
  v_existe NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_existe
    FROM ALL_TABLES
   WHERE OWNER = SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
     AND TABLE_NAME = 'BKP_RMD_PAR_MATRIZ';
  IF v_existe = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE BKP_RMD_PAR_MATRIZ (
        ID_EXECUCAO VARCHAR2(30) NOT NULL,
        DH_EXECUCAO TIMESTAMP NOT NULL,
        USUARIO_EXECUCAO VARCHAR2(128) NOT NULL,
        CODPARC NUMBER NOT NULL,
        CODPARCMATRIZ_ANTES NUMBER,
        CODPARCMATRIZ_DEPOIS NUMBER
      )]';
  END IF;
END;
/

DECLARE
  v_id VARCHAR2(30) := 'RMD_MAT_'||TO_CHAR(SYSTIMESTAMP,'YYYYMMDDHH24MISSFF3');
  v_backup PLS_INTEGER;
  v_update PLS_INTEGER;
BEGIN
  INSERT INTO BKP_RMD_PAR_MATRIZ
    (ID_EXECUCAO,DH_EXECUCAO,USUARIO_EXECUCAO,CODPARC,
     CODPARCMATRIZ_ANTES,CODPARCMATRIZ_DEPOIS)
  WITH MATRIZ AS (
    SELECT SUBSTR(LPAD(CGC_CPF,14,'0'),1,8) RAIZ_CNPJ,
           MIN(CODPARC) KEEP
             (DENSE_RANK FIRST ORDER BY SUBSTR(LPAD(CGC_CPF,14,'0'),9,4),CODPARC)
             CODPARC_MATRIZ
      FROM TGFPAR
     WHERE TIPPESSOA='J' AND CGC_CPF IS NOT NULL
     GROUP BY SUBSTR(LPAD(CGC_CPF,14,'0'),1,8)
  ), PROPOSTA AS (
    SELECT P.CODPARC,P.CODPARCMATRIZ,
           CASE WHEN P.TIPPESSOA='F' THEN P.CODPARC ELSE M.CODPARC_MATRIZ END NOVA_MATRIZ
      FROM TGFPAR P
      LEFT JOIN MATRIZ M
        ON M.RAIZ_CNPJ=SUBSTR(LPAD(P.CGC_CPF,14,'0'),1,8)
     WHERE P.TIPPESSOA='F'
        OR (P.TIPPESSOA='J' AND P.CGC_CPF IS NOT NULL)
  )
  SELECT v_id,SYSTIMESTAMP,SYS_CONTEXT('USERENV','SESSION_USER'),
         CODPARC,CODPARCMATRIZ,NOVA_MATRIZ
    FROM PROPOSTA
   WHERE DECODE(CODPARCMATRIZ,NOVA_MATRIZ,1,0)=0;
  v_backup := SQL%ROWCOUNT;

  MERGE INTO TGFPAR P
  USING (SELECT CODPARC,CODPARCMATRIZ_DEPOIS
           FROM BKP_RMD_PAR_MATRIZ WHERE ID_EXECUCAO=v_id) B
     ON (P.CODPARC=B.CODPARC)
   WHEN MATCHED THEN UPDATE SET P.CODPARCMATRIZ=B.CODPARCMATRIZ_DEPOIS;
  v_update := SQL%ROWCOUNT;

  IF v_update <> v_backup THEN
    RAISE_APPLICATION_ERROR(-20120,'Backup e ajuste de matriz divergiram.');
  END IF;
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('ID_EXECUCAO='||v_id);
  DBMS_OUTPUT.PUT_LINE('PARCEIROS_AJUSTADOS='||v_update);
EXCEPTION WHEN OTHERS THEN ROLLBACK; RAISE;
END;
/
