-- Padroniza descricoes dos tipos de titulo, com backup pontual.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
DECLARE v_existe NUMBER;v_id VARCHAR2(30):='RMD_TIT_'||TO_CHAR(SYSTIMESTAMP,'YYYYMMDDHH24MISSFF3');v_bkp NUMBER;v_upd NUMBER;
BEGIN
 SELECT COUNT(*) INTO v_existe FROM ALL_TABLES WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND TABLE_NAME='BKP_RMD_PAD_TGFTIT';
 IF v_existe=0 THEN EXECUTE IMMEDIATE 'CREATE TABLE BKP_RMD_PAD_TGFTIT AS SELECT CAST(NULL AS VARCHAR2(30)) ID_EXECUCAO,CAST(NULL AS TIMESTAMP) DH_EXECUCAO,CAST(NULL AS VARCHAR2(128)) USUARIO_EXECUCAO,CAST(NULL AS VARCHAR2(30)) ROWID_ORIGINAL,T.* FROM TGFTIT T WHERE 1=0';END IF;
 INSERT INTO BKP_RMD_PAD_TGFTIT SELECT v_id,SYSTIMESTAMP,SYS_CONTEXT('USERENV','SESSION_USER'),ROWIDTOCHAR(ROWID),T.* FROM TGFTIT T WHERE DECODE(DESCRTIPTIT,REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(DESCRTIPTIT),'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇáàâãäéèêëíìîïóòôõöúùûüçÃãÕõÂâÊêÎîÔôÛû','AAAAAEEEEIIIIOOOOOUUUUCAAAAAEEEEIIIIOOOOOUUUUCAAAOOAAEIIOOUU')),' {2,}',' '),0,1)=1;v_bkp:=SQL%ROWCOUNT;
 UPDATE TGFTIT SET DESCRTIPTIT=REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(DESCRTIPTIT),'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇáàâãäéèêëíìîïóòôõöúùûüçÃãÕõÂâÊêÎîÔôÛû','AAAAAEEEEIIIIOOOOOUUUUCAAAAAEEEEIIIIOOOOOUUUUCAAAOOAAEIIOOUU')),' {2,}',' ') WHERE DECODE(DESCRTIPTIT,REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(DESCRTIPTIT),'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇáàâãäéèêëíìîïóòôõöúùûüçÃãÕõÂâÊêÎîÔôÛû','AAAAAEEEEIIIIOOOOOUUUUCAAAAAEEEEIIIIOOOOOUUUUCAAAOOAAEIIOOUU')),' {2,}',' '),0,1)=1;v_upd:=SQL%ROWCOUNT;
 IF v_bkp<>v_upd THEN RAISE_APPLICATION_ERROR(-20326,'Backup e atualizacao de TGFTIT divergiram.');END IF;COMMIT;DBMS_OUTPUT.PUT_LINE('ID_EXECUCAO='||v_id||'; REGISTROS='||v_upd);EXCEPTION WHEN OTHERS THEN ROLLBACK;RAISE;END;
/
