-- Regra historica Etapa de Revisao: manter o menor CODBAI por nome normalizado,
-- redirecionar referencias e excluir os CODBAI obsoletos com mapa persistente.
-- A tabela de backup define exatamente o conjunto que sera atualizado.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
DECLARE
  v_id VARCHAR2(30):='RMD_BAI_'||TO_CHAR(SYSTIMESTAMP,'YYYYMMDDHH24MISSFF3');
  v_bkp NUMBER;v_upd NUMBER;v_col NUMBER;
BEGIN
  INSERT INTO BKP_RMD_PAD_TSIBAI
  SELECT v_id,SYSTIMESTAMP,SYS_CONTEXT('USERENV','SESSION_USER'),ROWIDTOCHAR(B.ROWID),B.*
  FROM TSIBAI B
  JOIN (
    SELECT RID FROM (
      SELECT RID,NOMEBAI,NORM,COUNT(*) OVER(PARTITION BY NORM) QTD_GRUPO FROM (
        SELECT ROWIDTOCHAR(ROWID) RID,NOMEBAI,
          REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEBAI),
            'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇáàâãäéèêëíìîïóòôõöúùûüçÃãÕõÂâÊêÎîÔôÛû',
            'AAAAAEEEEIIIIOOOOOUUUUCAAAAAEEEEIIIIOOOOOUUUUCAAAOOAAEIIOOUU')),' {2,}',' ') NORM
        FROM TSIBAI
      )
    ) WHERE QTD_GRUPO=1 AND DECODE(NOMEBAI,NORM,0,1)=1
  ) X ON X.RID=ROWIDTOCHAR(B.ROWID);
  v_bkp:=SQL%ROWCOUNT;

  MERGE INTO TSIBAI B USING (
    SELECT ROWID_ORIGINAL,
      REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEBAI),
        'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇáàâãäéèêëíìîïóòôõöúùûüçÃãÕõÂâÊêÎîÔôÛû',
        'AAAAAEEEEIIIIOOOOOUUUUCAAAAAEEEEIIIIOOOOOUUUUCAAAOOAAEIIOOUU')),' {2,}',' ') NORM
    FROM BKP_RMD_PAD_TSIBAI WHERE ID_EXECUCAO=v_id
  ) M ON (ROWIDTOCHAR(B.ROWID)=M.ROWID_ORIGINAL)
  WHEN MATCHED THEN UPDATE SET B.NOMEBAI=M.NORM;
  v_upd:=SQL%ROWCOUNT;

  IF v_bkp<>v_upd THEN RAISE_APPLICATION_ERROR(-20330,'Backup e atualizacao de TSIBAI divergiram.');END IF;
  SELECT COUNT(*) INTO v_col FROM (
    SELECT REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEBAI),
      'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ','AAAAAEEEEIIIIOOOOOUUUUC')),' {2,}',' ') N
    FROM TSIBAI GROUP BY REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEBAI),
      'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ','AAAAAEEEEIIIIOOOOOUUUUC')),' {2,}',' ')
    HAVING COUNT(*)>1
  );
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('STATUS=CONCLUIDO_PARCIAL; ID_EXECUCAO='||v_id||'; REGISTROS='||v_upd||'; GRUPOS_COLISAO_PRESERVADOS='||v_col);
EXCEPTION WHEN OTHERS THEN ROLLBACK;RAISE;
END;
/
