-- Regra historica Etapa de Revisao: manter o menor CODEND por TIPO e nome normalizado,
-- redirecionar referencias e excluir os CODEND obsoletos com mapa persistente.
-- A tabela de backup define exatamente o conjunto que sera atualizado.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
DECLARE
  v_id VARCHAR2(30):='RMD_END_'||TO_CHAR(SYSTIMESTAMP,'YYYYMMDDHH24MISSFF3');
  v_bkp NUMBER;v_upd NUMBER;v_col NUMBER;
BEGIN
  INSERT INTO BKP_RMD_PAD_TSIEND
  SELECT v_id,SYSTIMESTAMP,SYS_CONTEXT('USERENV','SESSION_USER'),ROWIDTOCHAR(E.ROWID),E.*
  FROM TSIEND E
  JOIN (
    SELECT RID FROM (
      SELECT RID,TIPO,NOMEEND,NORM,COUNT(*) OVER(PARTITION BY TIPO,NORM) QTD_GRUPO FROM (
        SELECT ROWIDTOCHAR(ROWID) RID,TIPO,NOMEEND,
          REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEEND),
            'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇáàâãäéèêëíìîïóòôõöúùûüçÃãÕõÂâÊêÎîÔôÛû',
            'AAAAAEEEEIIIIOOOOOUUUUCAAAAAEEEEIIIIOOOOOUUUUCAAAOOAAEIIOOUU')),' {2,}',' ') NORM
        FROM TSIEND
      )
    ) WHERE QTD_GRUPO=1 AND DECODE(NOMEEND,NORM,0,1)=1
  ) X ON X.RID=ROWIDTOCHAR(E.ROWID);
  v_bkp:=SQL%ROWCOUNT;

  MERGE INTO TSIEND E USING (
    SELECT ROWID_ORIGINAL,
      REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEEND),
        'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇáàâãäéèêëíìîïóòôõöúùûüçÃãÕõÂâÊêÎîÔôÛû',
        'AAAAAEEEEIIIIOOOOOUUUUCAAAAAEEEEIIIIOOOOOUUUUCAAAOOAAEIIOOUU')),' {2,}',' ') NORM
    FROM BKP_RMD_PAD_TSIEND WHERE ID_EXECUCAO=v_id
  ) M ON (ROWIDTOCHAR(E.ROWID)=M.ROWID_ORIGINAL)
  WHEN MATCHED THEN UPDATE SET E.NOMEEND=M.NORM;
  v_upd:=SQL%ROWCOUNT;

  IF v_bkp<>v_upd THEN RAISE_APPLICATION_ERROR(-20332,'Backup e atualizacao de TSIEND divergiram.');END IF;
  SELECT COUNT(*) INTO v_col FROM (
    SELECT TIPO,REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEEND),
      'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ','AAAAAEEEEIIIIOOOOOUUUUC')),' {2,}',' ') N
    FROM TSIEND GROUP BY TIPO,REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEEND),
      'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ','AAAAAEEEEIIIIOOOOOUUUUC')),' {2,}',' ')
    HAVING COUNT(*)>1
  );
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('STATUS=CONCLUIDO_PARCIAL; ID_EXECUCAO='||v_id||'; REGISTROS='||v_upd||'; GRUPOS_COLISAO_PRESERVADOS='||v_col);
EXCEPTION WHEN OTHERS THEN ROLLBACK;RAISE;
END;
/
