-- Recompila objetos invalidos apenas quando a sessao possui o privilegio necessario.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
SET SQLBLANKLINES ON
DECLARE
  v_schema VARCHAR2(128):=SYS_CONTEXT('USERENV','CURRENT_SCHEMA');
  v_usuario VARCHAR2(128):=SYS_CONTEXT('USERENV','SESSION_USER');
  v_antes NUMBER;
  v_depois NUMBER;
  v_priv NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_antes FROM ALL_OBJECTS
  WHERE OWNER=v_schema AND STATUS='INVALID';

  SELECT COUNT(*) INTO v_priv FROM SESSION_PRIVS
  WHERE PRIVILEGE='ALTER ANY PROCEDURE';

  IF v_antes=0 THEN
    DBMS_OUTPUT.PUT_LINE('STATUS=CONCLUIDO; OBJETOS_INVALIDOS=0');
  ELSIF v_schema<>v_usuario AND v_priv=0 THEN
    DBMS_OUTPUT.PUT_LINE('STATUS=IGNORADO_SEM_PRIVILEGIO; OBJETOS_INVALIDOS='||v_antes
      ||'; USUARIO='||v_usuario||'; SCHEMA='||v_schema||'; PRIVILEGIO_NECESSARIO=ALTER ANY PROCEDURE');
  ELSE
    DBMS_UTILITY.COMPILE_SCHEMA(SCHEMA=>v_schema,COMPILE_ALL=>FALSE);
    SELECT COUNT(*) INTO v_depois FROM ALL_OBJECTS
    WHERE OWNER=v_schema AND STATUS='INVALID';
    DBMS_OUTPUT.PUT_LINE('STATUS=CONCLUIDO; INVALIDOS_ANTES='||v_antes||'; INVALIDOS_DEPOIS='||v_depois);
  END IF;
END;
/

COLUMN OBJECT_TYPE FORMAT A24
COLUMN OBJECT_NAME FORMAT A50
SELECT OBJECT_TYPE,OBJECT_NAME
FROM ALL_OBJECTS
WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND STATUS='INVALID'
ORDER BY OBJECT_TYPE,OBJECT_NAME;

PROMPT === FIM RECOMPILACAO OBJETOS INVALIDOS ===
