SET SERVEROUTPUT ON SIZE UNLIMITED
SET PAGESIZE 200
PROMPT === TIPOS DOS CAMPOS SUSPEITOS TGFFIN ===
SELECT COLUMN_ID, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE
  FROM ALL_TAB_COLUMNS
 WHERE OWNER='SANKHYA' AND TABLE_NAME='TGFFIN'
   AND COLUMN_NAME IN ('TIPJURO','TIPMULTA','TIPMARCCHEQ','TPAGNFCE','ORIGEM','PROVISAO','RATEADO','RECDESP','SEQUENCIA','CODTIPTIT','VLRDESDOB','DTVENC')
 ORDER BY COLUMN_ID;
PROMPT === VALORES ROTULADOS DO FINANCEIRO NATIVO NUNOTA 2082 ===
SELECT 'NUFIN='||NUFIN||' NUNOTA='||NUNOTA||' CODTIPTIT='||CODTIPTIT||' TIPJURO='||NVL(TO_CHAR(TIPJURO),'<NULL>')||' TIPMULTA='||NVL(TO_CHAR(TIPMULTA),'<NULL>')||' TIPMARCCHEQ='||NVL(TIPMARCCHEQ,'<NULL>')||' TPAGNFCE='||NVL(TO_CHAR(TPAGNFCE),'<NULL>')||' ORIGEM='||NVL(ORIGEM,'<NULL>')||' PROVISAO='||PROVISAO||' RATEADO='||RATEADO||' RECDESP='||RECDESP||' SEQUENCIA='||SEQUENCIA||' VLRDESDOB='||VLRDESDOB||' DTVENC='||TO_CHAR(DTVENC,'YYYY-MM-DD') AS DADOS
  FROM TGFFIN WHERE NUNOTA=2082;
PROMPT === TIPJURO EM TGFTPV ===
SELECT C.NUNOTA,C.CODTIPVENDA,C.DHTIPVENDA,V.TIPJURO
  FROM TGFCAB C LEFT JOIN TGFTPV V ON V.CODTIPVENDA=C.CODTIPVENDA AND V.DHALTER=C.DHTIPVENDA
 WHERE C.NUNOTA=2082;
