-- Read-only MEDCHAP: diagnostico do SMTP principal (TSIPAR MSDSMTPPROP) e da TSISMTP SEM expor valores.
-- R02 (25/09/2026): formato posicional host:porta;seguranca;usuario;remetente;SENHA;flag - o 5o campo (senha criptografada) NUNCA e selecionado.
-- Valores sensiveis nao aparecem: so aparecem campos nao secretos, tamanho e indicadores da conta interna de testes do Deploy Agent.
SELECT 'TSIPAR_MSDSMTPPROP' ORIGEM, P.CHAVE ITEM,
       TO_CHAR(LENGTH(P.TEXTO)) TAMANHO,
       CASE WHEN INSTR(LOWER(P.TEXTO),'email-smtp.us-east-1.amazonaws.com')>0 THEN 'SIM' ELSE 'NAO' END SERVIDOR_TESTE_DEPLOY,
       CASE WHEN INSTR(LOWER(P.TEXTO),'noreply@sankhya.com.br')>0 THEN 'SIM' ELSE 'NAO' END REMETENTE_TESTE_DEPLOY,
       REGEXP_SUBSTR(P.TEXTO,'[^'||CHR(59)||']+',1,1)||' | seg='||REGEXP_SUBSTR(P.TEXTO,'[^'||CHR(59)||']+',1,2)||' | usuario='||REGEXP_SUBSTR(P.TEXTO,'[^'||CHR(59)||']+',1,3)||' | remetente='||REGEXP_SUBSTR(P.TEXTO,'[^'||CHR(59)||']+',1,4)||' | campo5=<omitido>'||' | campo6='||REGEXP_SUBSTR(P.TEXTO,'[^'||CHR(59)||']+',1,6) ESTRUTURA_SEM_VALORES
  FROM TSIPAR P WHERE P.CHAVE='MSDSMTPPROP'
UNION ALL
SELECT 'COLUNA_TSISMTP', COLUMN_NAME, DATA_TYPE||'('||DATA_LENGTH||')', NULLABLE, NULL, NULL
  FROM ALL_TAB_COLUMNS WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND TABLE_NAME='TSISMTP'
UNION ALL
SELECT 'COLUNA_TSIPAR', COLUMN_NAME, DATA_TYPE||'('||DATA_LENGTH||')', NULLABLE, NULL, NULL
  FROM ALL_TAB_COLUMNS WHERE OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND TABLE_NAME='TSIPAR'
UNION ALL
SELECT 'FK_PARA_TSISMTP', C.TABLE_NAME, C.CONSTRAINT_NAME, NULL, NULL, NULL
  FROM ALL_CONSTRAINTS C JOIN ALL_CONSTRAINTS R ON R.OWNER=C.R_OWNER AND R.CONSTRAINT_NAME=C.R_CONSTRAINT_NAME
 WHERE C.CONSTRAINT_TYPE='R' AND R.TABLE_NAME='TSISMTP' AND R.OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
