-- Read-only MEDCHAP: contas da TSISMTP sem colunas secretas (SENHA/tokens nunca selecionados) e referencias por FK.
SELECT 'TSISMTP' ORIGEM, TO_CHAR(S.CODSMTP) CODSMTP, S.SERVIDOR, TO_CHAR(S.PORTA) PORTA, S.TIPO, CASE WHEN LOWER(S.SERVIDOR)='email-smtp.us-east-1.amazonaws.com' THEN '<omitido>' ELSE S.USUARIO END USUARIO, S.REMETENTE, S.PADRAO,
       S.IGNORACERTIFICADO, S.USEOAUTH,
       CASE WHEN LOWER(S.SERVIDOR)='email-smtp.us-east-1.amazonaws.com' OR LOWER(S.REMETENTE)='noreply@sankhya.com.br' THEN 'CONTA_TESTE_DEPLOY' ELSE 'CONTA_CLIENTE' END CLASSIFICACAO
  FROM TSISMTP S
UNION ALL SELECT 'REF_TGFEMP', TO_CHAR(CODSMTP), TO_CHAR(COUNT(*)), NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL FROM TGFEMP WHERE CODSMTP IS NOT NULL GROUP BY CODSMTP
UNION ALL SELECT 'REF_TPQPLA', TO_CHAR(CODSMTP), TO_CHAR(COUNT(*)), NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL FROM TPQPLA WHERE CODSMTP IS NOT NULL GROUP BY CODSMTP
UNION ALL SELECT 'REF_TMDMSG', TO_CHAR(CODSMTP), TO_CHAR(COUNT(*)), NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL FROM TMDMSG WHERE CODSMTP IS NOT NULL GROUP BY CODSMTP
UNION ALL SELECT 'REF_TSIARF', TO_CHAR(CODSMTP), TO_CHAR(COUNT(*)), NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL FROM TSIARF WHERE CODSMTP IS NOT NULL GROUP BY CODSMTP
UNION ALL SELECT 'REF_TMDFMG', TO_CHAR(CODSMTP), TO_CHAR(COUNT(*)), NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL FROM TMDFMG WHERE CODSMTP IS NOT NULL GROUP BY CODSMTP
