-- Read-only: colunas das FKs que apontam para TSISMTP.
SELECT CC.TABLE_NAME, CC.COLUMN_NAME, CC.CONSTRAINT_NAME
  FROM ALL_CONSTRAINTS C JOIN ALL_CONSTRAINTS R ON R.OWNER=C.R_OWNER AND R.CONSTRAINT_NAME=C.R_CONSTRAINT_NAME
  JOIN ALL_CONS_COLUMNS CC ON CC.OWNER=C.OWNER AND CC.CONSTRAINT_NAME=C.CONSTRAINT_NAME
 WHERE C.CONSTRAINT_TYPE='R' AND R.TABLE_NAME='TSISMTP' AND R.OWNER=SYS_CONTEXT('USERENV','CURRENT_SCHEMA')
