-- Preflight read-only MEDCHAP DISTRIBUIDORA DE MEDICAMENTOS CHAPECO LTDA (origem: modelo FOCUSFINTAXPRD 23/09/2026). Somente SELECT/WITH via oracle_direct.py query. Sem DML/DDL.
SELECT U.USERNAME, U.DEFAULT_TABLESPACE, Q.TABLESPACE_NAME, Q.BYTES, Q.MAX_BYTES
  FROM USER_USERS U
  LEFT JOIN USER_TS_QUOTAS Q ON 1 = 1
