-- Preflight read-only MEDCHAP DISTRIBUIDORA DE MEDICAMENTOS CHAPECO LTDA (origem: modelo FOCUSFINTAXPRD 23/09/2026). Somente SELECT/WITH via oracle_direct.py query. Sem DML/DDL.
SELECT CODEMP,
       TRIM(NOMEFANTASIA) AS NOMEFANTASIA,
       TRIM(RAZAOSOCIAL) AS RAZAOSOCIAL,
       REGEXP_REPLACE(TO_CHAR(CGC), '[^0-9]', '') AS CNPJ,
       CASE
         WHEN UPPER(TRIM(RAZAOSOCIAL)) = 'MEDCHAP DISTRIBUIDORA DE MEDICAMENTOS CHAPECO LTDA' THEN 'RAZAO_SOCIAL_EXATA'
         WHEN UPPER(TRANSLATE(RAZAOSOCIAL,'ÁÀÂÃÉÊÍÓÔÕÚÇ','AAAAEEIOOOUC')) LIKE '%MEDCHAP%DISTRIBUIDORA%MEDICAMENTOS%CHAPECO%' THEN 'RAZAO_SOCIAL_EQUIVALENTE_ACENTOS'
         WHEN UPPER(REPLACE(RAZAOSOCIAL, ' ', '')) LIKE '%MEDCHAP%'
           OR UPPER(REPLACE(NOMEFANTASIA, ' ', '')) LIKE '%MEDCHAP%' THEN 'VARIACAO_MEDCHAP'
         WHEN UPPER(RAZAOSOCIAL) LIKE '%CHAPEC%' OR UPPER(NOMEFANTASIA) LIKE '%CHAPEC%'
           OR UPPER(RAZAOSOCIAL) LIKE '%MEDICAMENTO%' OR UPPER(NOMEFANTASIA) LIKE '%MEDICAMENTO%' THEN 'VARIACAO_TOKEN'
         ELSE 'SEM_TOKEN'
       END AS CLASSIFICACAO
  FROM TSIEMP
 ORDER BY CODEMP
