-- Preflight read-only MEDCHAP DISTRIBUIDORA DE MEDICAMENTOS CHAPECO LTDA (origem: modelo FOCUSFINTAXPRD 23/09/2026). Somente SELECT/WITH via oracle_direct.py query. Sem DML/DDL.
SELECT OWNER, OBJECT_NAME, OBJECT_TYPE, STATUS, CREATED, LAST_DDL_TIME
  FROM ALL_OBJECTS
 WHERE OWNER IN (SYS_CONTEXT('USERENV','SESSION_USER'), SYS_CONTEXT('USERENV','CURRENT_SCHEMA'))
   AND (OBJECT_NAME LIKE 'RMD\_%' ESCAPE '\' OR OBJECT_NAME LIKE 'BKP\_%' ESCAPE '\')
 ORDER BY CREATED, OWNER, OBJECT_NAME
