-- Preflight read-only MEDCHAP DISTRIBUIDORA DE MEDICAMENTOS CHAPECO LTDA (origem: modelo FOCUSFINTAXPRD 23/09/2026). Somente SELECT/WITH via oracle_direct.py query. Sem DML/DDL.
SELECT CODVOL,DESCRVOL,
       CASE WHEN REGEXP_LIKE(CODVOL,'[0-9]') THEN 'IGNORAR_NUMERAL'
            WHEN DESCRVOL<>UPPER(DESCRVOL) THEN 'DESCRICAO_MINUSCULA'
            ELSE 'AVALIAR' END SITUACAO
FROM TGFVOL
ORDER BY CODVOL
