-- Preflight read-only MEDCHAP DISTRIBUIDORA DE MEDICAMENTOS CHAPECO LTDA (origem: modelo FOCUSFINTAXPRD 23/09/2026). Somente SELECT/WITH via oracle_direct.py query. Sem DML/DDL.
WITH DESTINOS(TO_CODE) AS (
  SELECT 'CD' FROM DUAL UNION ALL SELECT 'CX' FROM DUAL UNION ALL SELECT 'KG' FROM DUAL
  UNION ALL SELECT 'LT' FROM DUAL UNION ALL SELECT 'PC' FROM DUAL UNION ALL SELECT 'UN' FROM DUAL
  UNION ALL SELECT 'MT' FROM DUAL UNION ALL SELECT 'PT' FROM DUAL UNION ALL SELECT 'TN' FROM DUAL
  UNION ALL SELECT 'RL' FROM DUAL UNION ALL SELECT 'BL' FROM DUAL UNION ALL SELECT 'FR' FROM DUAL
  UNION ALL SELECT 'JG' FROM DUAL UNION ALL SELECT 'SC' FROM DUAL UNION ALL SELECT 'CJ' FROM DUAL
  UNION ALL SELECT 'FL' FROM DUAL UNION ALL SELECT 'DZ' FROM DUAL UNION ALL SELECT 'KT' FROM DUAL
  UNION ALL SELECT 'BD' FROM DUAL UNION ALL SELECT 'BG' FROM DUAL UNION ALL SELECT 'M2' FROM DUAL
  UNION ALL SELECT 'M3' FROM DUAL UNION ALL SELECT 'GR' FROM DUAL UNION ALL SELECT 'FD' FROM DUAL
  UNION ALL SELECT 'PAR' FROM DUAL
), CANONICOS AS (
  SELECT D.TO_CODE,V.DESCRVOL FROM DESTINOS D JOIN TGFVOL V ON V.CODVOL=D.TO_CODE
), CANDIDATOS AS (
  SELECT S.CODVOL FROM_CODE,D.TO_CODE,'CODIGO_SEM_PONTUACAO' MOTIVO
  FROM TGFVOL S JOIN CANONICOS D
    ON REGEXP_REPLACE(TRANSLATE(UPPER(S.CODVOL),
       'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ','AAAAAEEEEIIIIOOOOOUUUUC'),'[^A-Z]','')=D.TO_CODE
  WHERE S.CODVOL<>D.TO_CODE AND NOT REGEXP_LIKE(S.CODVOL,'[0-9]')
  UNION ALL
  SELECT S.CODVOL,D.TO_CODE,'DESCRICAO_EQUIVALENTE'
  FROM TGFVOL S JOIN CANONICOS D
    ON REGEXP_REPLACE(REGEXP_REPLACE(TRANSLATE(UPPER(TRIM(S.DESCRVOL)),
       'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ','AAAAAEEEEIIIIOOOOOUUUUC'),'[^A-Z]',''),'S$','')
     = REGEXP_REPLACE(REGEXP_REPLACE(TRANSLATE(UPPER(TRIM(D.DESCRVOL)),
       'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ','AAAAAEEEEIIIIOOOOOUUUUC'),'[^A-Z]',''),'S$','')
  WHERE S.CODVOL<>D.TO_CODE AND NOT REGEXP_LIKE(S.CODVOL,'[0-9]')
)
SELECT FROM_CODE,MAX(TO_CODE) TO_CODE,LISTAGG(MOTIVO,',') WITHIN GROUP(ORDER BY MOTIVO) MOTIVOS
FROM CANDIDATOS
GROUP BY FROM_CODE
HAVING COUNT(DISTINCT TO_CODE)=1
ORDER BY FROM_CODE
