-- Preflight read-only MEDCHAP DISTRIBUIDORA DE MEDICAMENTOS CHAPECO LTDA (origem: modelo FOCUSFINTAXPRD 23/09/2026). Somente SELECT/WITH via oracle_direct.py query. Sem DML/DDL.
SELECT '18_TGFCGM_ORIGEM_EMP1_1900_1' ITEM,COUNT(*) QTD FROM TGFCGM WHERE CODEMP=1 AND ANO=1900 AND MES=1
UNION ALL SELECT '18_TGFCMV_CODCONFIG_1',COUNT(*) FROM TGFCMV WHERE CODCONFIG=1
UNION ALL SELECT '18_TGFCGM_DESTINOS',COUNT(*) FROM TGFCGM WHERE CODEMP<>1
UNION ALL SELECT '19_PARCEIROS_TOTAL',COUNT(*) FROM TGFPAR
UNION ALL SELECT '20_TTKINDAGT_SEQUENCIA_1',COUNT(*) FROM TTKINDAGT WHERE SEQUENCIA=1
UNION ALL SELECT '20_TTKNOT_TOTAL',COUNT(*) FROM TTKNOT
UNION ALL SELECT '20_TTKEVT_TOTAL',COUNT(*) FROM TTKEVT
UNION ALL SELECT '21_ICMS_DIVERGENTES',COUNT(*) FROM TGFPAR
 WHERE (TIPPESSOA='J' AND IDENTINSCESTAD IS NOT NULL AND UPPER(TRIM(IDENTINSCESTAD))<>'ISENTO' AND NVL(CLASSIFICMS,'Z')<>'R')
    OR (TIPPESSOA='F' AND IDENTINSCESTAD IS NOT NULL AND UPPER(TRIM(IDENTINSCESTAD))<>'ISENTO' AND NVL(CLASSIFICMS,'Z')<>'P')
    OR (NVL(UPPER(TRIM(IDENTINSCESTAD)),'ISENTO')='ISENTO' AND NVL(CLASSIFICMS,'Z')<>'C')
UNION ALL SELECT '22_PARCEIROS_A_ANALISAR',COUNT(*) FROM TGFPAR WHERE CGC_CPF IS NOT NULL
