-- Preflight read-only MEDCHAP DISTRIBUIDORA DE MEDICAMENTOS CHAPECO LTDA (origem: modelo FOCUSFINTAXPRD 23/09/2026). Somente SELECT/WITH via oracle_direct.py query. Sem DML/DDL.
SELECT '24_TGFPAR_TOTAL' ITEM,COUNT(*) QTD FROM TGFPAR
UNION ALL SELECT '25_TGFPRO_TOTAL',COUNT(*) FROM TGFPRO
UNION ALL SELECT '26_TGFTIT_TOTAL',COUNT(*) FROM TGFTIT
UNION ALL SELECT '27_TSICID_TOTAL',COUNT(*) FROM TSICID
UNION ALL SELECT '28_TGFTPV_TOTAL',COUNT(*) FROM TGFTPV
