-- Preflight read-only MEDCHAP DISTRIBUIDORA DE MEDICAMENTOS CHAPECO LTDA (origem: modelo FOCUSFINTAXPRD 23/09/2026). Somente SELECT/WITH via oracle_direct.py query. Sem DML/DDL.
SELECT 'TSIEND_TOTAL' ITEM,COUNT(*) QTD FROM TSIEND
UNION ALL
SELECT 'TSIEND_GRUPOS_COLISAO',COUNT(*) FROM (
 SELECT TIPO,REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEEND),'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ','AAAAAEEEEIIIIOOOOOUUUUC')),' {2,}',' ') N
 FROM TSIEND GROUP BY TIPO,REGEXP_REPLACE(TRIM(TRANSLATE(UPPER(NOMEEND),'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ','AAAAAEEEEIIIIOOOOOUUUUC')),' {2,}',' ')
 HAVING COUNT(*)>1
)
