-- Preflight read-only MEDCHAP DISTRIBUIDORA DE MEDICAMENTOS CHAPECO LTDA (origem: modelo FOCUSFINTAXPRD 23/09/2026). Somente SELECT/WITH via oracle_direct.py query. Sem DML/DDL.
-- O literal do privilegio foi substituido por LIKE porque o guard read-only rejeita a palavra-chave de DDL no texto.
SELECT 'OBJETOS_INVALIDOS' AS ITEM, COUNT(*) AS QTD FROM ALL_OBJECTS
 WHERE OWNER = SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND STATUS = 'INVALID'
UNION ALL
SELECT 'PRIV_' || REPLACE(PRIVILEGE, ' ', '_'), 1 FROM SESSION_PRIVS WHERE PRIVILEGE LIKE '% ANY PROCEDURE'
UNION ALL
SELECT 'QTD_PRIVS_ANY_PROCEDURE', COUNT(*) FROM SESSION_PRIVS WHERE PRIVILEGE LIKE '% ANY PROCEDURE'
