-- Preflight read-only MEDCHAP DISTRIBUIDORA DE MEDICAMENTOS CHAPECO LTDA (origem: modelo FOCUSFINTAXPRD 23/09/2026). Somente SELECT/WITH via oracle_direct.py query. Sem DML/DDL.
SELECT TABLE_NAME, TRIGGER_NAME, STATUS
  FROM ALL_TRIGGERS
 WHERE OWNER = SYS_CONTEXT('USERENV','CURRENT_SCHEMA') AND STATUS <> 'ENABLED'
 ORDER BY TABLE_NAME, TRIGGER_NAME
