-- Preflight read-only MEDCHAP DISTRIBUIDORA DE MEDICAMENTOS CHAPECO LTDA (origem: modelo FOCUSFINTAXPRD 23/09/2026). Somente SELECT/WITH via oracle_direct.py query. Sem DML/DDL.
SELECT COUNT(*) AS QTD_LINHAS_TGFNUM_TGFFIN FROM TGFNUM WHERE ARQUIVO = 'TGFFIN'
