-- Preflight read-only MEDCHAP DISTRIBUIDORA DE MEDICAMENTOS CHAPECO LTDA (origem: modelo FOCUSFINTAXPRD 23/09/2026). Somente SELECT/WITH via oracle_direct.py query. Sem DML/DDL.
SELECT U.CODUSU,
       TRIM(U.NOMEUSU) AS NOMEUSU,
       LOWER(TRIM(U.EMAIL)) AS EMAIL,
       U.CODGRUPO,
       U.CODEMP
  FROM TSIUSU U
 ORDER BY LOWER(TRIM(U.EMAIL)), U.CODUSU
