-- Preflight read-only MEDCHAP DISTRIBUIDORA DE MEDICAMENTOS CHAPECO LTDA. Somente SELECT/WITH via oracle_direct.py query. Sem DML/DDL.
-- Estado inicial do Card 09 (escopo do dashboard) e artefatos FDUP de tentativas anteriores, antes de qualquer mapa.
SELECT 'ESCOPO_DASHBOARD_NOTAS_SEM_FIN' AS METRICA, TO_CHAR(COUNT(*)) AS VALOR
  FROM TGFCAB C JOIN TGFTOP T ON T.CODTIPOPER=C.CODTIPOPER AND T.DHALTER=C.DHTIPOPER
 WHERE T.ATUALFIN<>0 AND C.TIPMOV<>'Z' AND NOT EXISTS (SELECT 1 FROM TGFFIN F WHERE F.NUNOTA=C.NUNOTA)
UNION ALL SELECT 'TABELAS_FDUP_ANTERIORES', TO_CHAR(COUNT(*)) FROM ALL_TABLES
 WHERE OWNER IN (SYS_CONTEXT('USERENV','SESSION_USER'), SYS_CONTEXT('USERENV','CURRENT_SCHEMA'))
   AND TABLE_NAME LIKE 'BKP\_RMD\_FDUP%' ESCAPE '\'
UNION ALL SELECT 'LINHAS_TGFNUM_TGFFIN', TO_CHAR(COUNT(*)) FROM TGFNUM WHERE ARQUIVO='TGFFIN'
UNION ALL SELECT 'ULTCOD_TGFNUM_TGFFIN', TO_CHAR(MAX(ULTCOD)) FROM TGFNUM WHERE ARQUIVO='TGFFIN'
UNION ALL SELECT 'TOTAL_TGFFIN', TO_CHAR(COUNT(*)) FROM TGFFIN
UNION ALL SELECT 'TGFNFE_COM_XML', TO_CHAR(COUNT(*)) FROM TGFNFE WHERE XML IS NOT NULL
