-- Script gerado a partir de: MODELO SANKHYA Contas Bancarias.xlsx

-- AVISOS (ajustar manualmente antes de executar):
-- Abas lidas: 2 no arquivo — 1 de empresa (4 conta(s) no script).
--   Empresas: Contas (4).
--   Auxiliar (nao gera conta): Bancos.

-- ===== PARCEIROS (BANCOS) -- TGFPAR =====
INSERT INTO TGFPAR (CODPARC, NOMEPARC, RAZAOSOCIAL, TIPPESSOA, CGC_CPF, ATIVO, CLIENTE, FORNECEDOR, CODCID, IDENTINSCESTAD, CLASSIFICMS, DTCAD, DTALTER)
VALUES ((SELECT NVL(MAX(CODPARC), 0) + 1 FROM TGFPAR), 'BANCO DO BRASIL', 'BANCO DO BRASIL S.A.', 'J', '00000000000191', 'S', 'N', 'S', (SELECT CODCID FROM TSICID WHERE NOMECID LIKE '%BRASILIA%' AND ROWNUM = 1), 'ISENTO', 'C', TO_DATE('25/09/2026', 'DD/MM/YYYY'), TO_DATE('25/09/2026', 'DD/MM/YYYY'));
COMMIT;

INSERT INTO TGFPAR (CODPARC, NOMEPARC, RAZAOSOCIAL, TIPPESSOA, CGC_CPF, ATIVO, CLIENTE, FORNECEDOR, CODCID, IDENTINSCESTAD, CLASSIFICMS, DTCAD, DTALTER)
VALUES ((SELECT NVL(MAX(CODPARC), 0) + 1 FROM TGFPAR), 'SANTANDER', 'BANCO SANTANDER (BRASIL) S.A.', 'J', '90400888000142', 'S', 'N', 'S', (SELECT CODCID FROM TSICID WHERE NOMECID LIKE '%SAO PAULO%' AND ROWNUM = 1), 'ISENTO', 'C', TO_DATE('25/09/2026', 'DD/MM/YYYY'), TO_DATE('25/09/2026', 'DD/MM/YYYY'));
COMMIT;

INSERT INTO TGFPAR (CODPARC, NOMEPARC, RAZAOSOCIAL, TIPPESSOA, CGC_CPF, ATIVO, CLIENTE, FORNECEDOR, CODCID, IDENTINSCESTAD, CLASSIFICMS, DTCAD, DTALTER)
VALUES ((SELECT NVL(MAX(CODPARC), 0) + 1 FROM TGFPAR), 'ITAU', 'ITAU UNIBANCO S.A.', 'J', '60701190000104', 'S', 'N', 'S', (SELECT CODCID FROM TSICID WHERE NOMECID LIKE '%SAO PAULO%' AND ROWNUM = 1), 'ISENTO', 'C', TO_DATE('25/09/2026', 'DD/MM/YYYY'), TO_DATE('25/09/2026', 'DD/MM/YYYY'));
COMMIT;

INSERT INTO TGFPAR (CODPARC, NOMEPARC, RAZAOSOCIAL, TIPPESSOA, CGC_CPF, ATIVO, CLIENTE, FORNECEDOR, CODCID, IDENTINSCESTAD, CLASSIFICMS, DTCAD, DTALTER)
VALUES ((SELECT NVL(MAX(CODPARC), 0) + 1 FROM TGFPAR), 'SICOOB', 'BANCO COOPERATIVO DO BRASIL S.A. - BANCOOB', 'J', '02038232000164', 'S', 'N', 'S', (SELECT CODCID FROM TSICID WHERE NOMECID LIKE '%BRASILIA%' AND ROWNUM = 1), 'ISENTO', 'C', TO_DATE('25/09/2026', 'DD/MM/YYYY'), TO_DATE('25/09/2026', 'DD/MM/YYYY'));
COMMIT;

-- ===== AGENCIAS E CONTAS -- TSIAGE / TSICTA =====
INSERT INTO TSIAGE (CODAGE, NOMEAGE, CODBCO) VALUES ('4072', '4072-X AGENCIA BANCO DO BRASIL', 1);
COMMIT;

INSERT INTO TSICTA (CODCTABCOINT, CODCTABCO, DESCRICAO, CODBCO, CODAGE, CODEMP, DTALTER, ATIVA, CLASSE)
VALUES ((SELECT NVL(MAX(CODCTABCOINT), 0) + 1 FROM TSICTA), '8855', '8855-2 BANCO DO BRASIL', 1, '4072', NVL((SELECT CODEMP FROM TSIEMP WHERE CGC = '00577604000103'), NULL), '25/09/2026', 'S', 'C');
COMMIT;

INSERT INTO TSIAGE (CODAGE, NOMEAGE, CODBCO) VALUES ('3711', '3711 AGENCIA SANTANDER', 33);
COMMIT;

INSERT INTO TSICTA (CODCTABCOINT, CODCTABCO, DESCRICAO, CODBCO, CODAGE, CODEMP, DTALTER, ATIVA, CLASSE)
VALUES ((SELECT NVL(MAX(CODCTABCOINT), 0) + 1 FROM TSICTA), '1300039831', '1300039831 SANTANDER', 33, '3711', NVL((SELECT CODEMP FROM TSIEMP WHERE CGC = '00577604000103'), NULL), '25/09/2026', 'S', 'C');
COMMIT;

INSERT INTO TSIAGE (CODAGE, NOMEAGE, CODBCO) VALUES ('1312', '1312 AGENCIA ITAU', 341);
COMMIT;

INSERT INTO TSICTA (CODCTABCOINT, CODCTABCO, DESCRICAO, CODBCO, CODAGE, CODEMP, DTALTER, ATIVA, CLASSE)
VALUES ((SELECT NVL(MAX(CODCTABCOINT), 0) + 1 FROM TSICTA), '99591', '99591-1 ITAU', 341, '1312', NVL((SELECT CODEMP FROM TSIEMP WHERE CGC = '00577604000103'), NULL), '25/09/2026', 'S', 'C');
COMMIT;

INSERT INTO TSIAGE (CODAGE, NOMEAGE, CODBCO) VALUES ('3069', '3069 AGENCIA SICOOB', 756);
COMMIT;

INSERT INTO TSICTA (CODCTABCOINT, CODCTABCO, DESCRICAO, CODBCO, CODAGE, CODEMP, DTALTER, ATIVA, CLASSE)
VALUES ((SELECT NVL(MAX(CODCTABCOINT), 0) + 1 FROM TSICTA), '96507', '96507-3 SICOOB', 756, '3069', NVL((SELECT CODEMP FROM TSIEMP WHERE CGC = '00577604000103'), NULL), '25/09/2026', 'S', 'C');
COMMIT;
